microsoft/fast

packages/fast-react-components-fluent/src/button/index.ts, packages/fast-react-components-fluent/src/design-system/breakpoints.ts, packages/fast-react-components-fluent/src/design-system/fonts.ts, packages/fast-react-components-fluent/src/design-system/index.ts, packages/fast-react-components-fluent/src/design-system/typography.ts, packages/fast-react-components-fluent/src/utilities/index.ts
Resolves #109 
For [details on formatting](https://fluentweb.com/prototyping/contribution-policy#pull-request-guidance) pull requests.
=> feat(fluent): adds fluent breakpoints and typographic ramp for heading, subheading, paragraph and caption

packages/fast-jss-manager-angular/README.md
<body>
<footer>
For [details on formatting](https://fluentweb.com/prototyping/contribution-policy#pull-request-guidance) pull requests.
=> docs: update readme

README.md
- migrated package detail over to wiki
- updates project description
- updates grammar
=> docs: update documentation for better clarity

README.md
<body>
<footer>
For [details on formatting](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md#pull-request-guidance) pull requests.
=> docs: update to readme directing traffic to wiki

.codeclimate.yml, .travis.yml, package-lock.json, package.json, packages/fast-animation/package.json, packages/fast-colors/package.json, packages/fast-components-react-base/package.json, packages/fast-components-react-msft/package.json, packages/fast-components-styles-msft/package.json, packages/fast-development-site-react/package.json, packages/fast-jss-manager-angular/package.json, packages/fast-jss-manager-react/package.json, packages/fast-jss-manager/package.json, packages/fast-permutator/package.json, packages/fast-tslint-rules/package.json, packages/fast-viewer-react/package.json
<body>
details below
<footer>
https://docs.codeclimate.com/docs/configuring-test-coverage
=> devops: add test coverage

packages/fast-permutator/README.md
<body>
- Updates permutator readme
<footer>
=> readme: updates fast-permutator documentation

README.md, packages/fast-animation/README.md
=> docs(readme): add badges for package quality, activity, contributors, and license

README.md
=> docs: remove total contributors and commit badges

packages/fast-development-site-react/app/components/polymer-heading.ts, packages/fast-development-site-react/package-lock.json, packages/fast-development-site-react/package.json
=> fix(tests): fix polymer issue during lerna run test

packages/fast-development-site-react/package-lock.json, packages/fast-development-site-react/package.json, packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-jss-manager-angular/.babelrc, packages/fast-jss-manager-angular/.npmignore, packages/fast-jss-manager-angular/package-lock.json, packages/fast-jss-manager-angular/package.json, packages/fast-jss-manager-angular/src/manage-jss.ts, packages/fast-jss-manager-react/package.json, packages/fast-jss-manager-react/src/manage-jss.tsx
<body>
closes #204 closes #259 
<footer>
=> refactor: remove instances of uuid in favor of lodash uniqueId in react packages

packages/fast-components-react-base/src/button/button.props.ts, packages/fast-components-react-base/src/divider/divider.props.ts, packages/fast-components-react-base/src/foundation/foundation.props.ts, packages/fast-components-react-base/src/hypertext/hypertext.props.ts, packages/fast-components-react-base/src/toggle/toggle.props.ts, packages/fast-components-react-base/src/typography/typography.props.ts
Closes [#248](https://github.com/microsoft/fast-dna/issues/248)
=> doc(props): update props documentation for consistency

packages/fast-development-site-react/src/components/breadcrumb/breadcrumb-item.tsx, packages/fast-development-site-react/src/components/breadcrumb/index.tsx, packages/fast-development-site-react/src/components/design-system/index.ts, packages/fast-development-site-react/src/components/shell/action-bar.tsx, packages/fast-development-site-react/src/components/shell/canvas.tsx, packages/fast-development-site-react/src/components/shell/header.tsx, packages/fast-development-site-react/src/components/shell/index.tsx, packages/fast-development-site-react/src/components/shell/info-bar.tsx, packages/fast-development-site-react/src/components/shell/pane-collapse.tsx, packages/fast-development-site-react/src/components/shell/pane.tsx, packages/fast-development-site-react/src/components/site/category-item.tsx, packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-development-site-react/src/components/site/menu.tsx, packages/fast-development-site-react/src/components/toc/index.tsx, packages/fast-development-site-react/src/components/toc/toc-item.tsx, packages/fast-development-site-react/src/components/toc/toc-menu.tsx
=> feat(development site): update the styling to reflect the new comps

packages/fast-components-styles-msft/src/hypertext/index.ts
=> refactor(hypertext): remove code duplication in hypertext styles

packages/fast-animation/lib/animateGroup/index.ts, packages/fast-animation/lib/fade/index.ts, packages/fast-components-styles-msft/src/hypertext/index.ts, packages/fast-development-site-react/src/components/breadcrumb/breadcrumb-item.tsx, packages/fast-development-site-react/src/components/shell/action-bar.tsx, packages/fast-development-site-react/src/components/shell/canvas.tsx, packages/fast-development-site-react/src/components/shell/header.tsx, packages/fast-development-site-react/src/components/shell/index.tsx, packages/fast-development-site-react/src/components/shell/info-bar.tsx, packages/fast-development-site-react/src/components/shell/pane-collapse.tsx, packages/fast-development-site-react/src/components/shell/pane.tsx, packages/fast-development-site-react/src/components/shell/row.tsx, packages/fast-development-site-react/src/components/site/category-item.tsx, packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-development-site-react/src/components/site/menu.tsx, packages/fast-development-site-react/src/components/toc/index.tsx, packages/fast-development-site-react/src/components/toc/toc-item.tsx, packages/fast-development-site-react/src/components/toc/toc-menu.tsx
Issue #285 , Issue #284 , Issue #287 , Issue #290 
<body>
<footer>
=> Update to use new utilities and refactored style names

packages/fast-permutator/src/index.js, packages/fast-permutator/src/utilities/get-example.js
=> fix(permutator): fix duplicate code for handling required and optional data

packages/fast-animation/client/examples/app/components/TestPage.tsx, packages/fast-animation/lib/animateGroup/index.ts, packages/fast-animation/lib/animateSequence/index.ts, packages/fast-animation/lib/utilities/invokeFunctionForEach.ts
=> fix(animation): refactor animate sequence and group to remove code duplication

packages/fast-permutator/src/utilities/get-deep-prop-locations.js, packages/fast-permutator/src/utilities/is-location-recursive.js, packages/fast-permutator/src/utilities/resolve-recursive-references.js
=> fix(permutator): refactor repeated code to check if a location is recursive into a new utility

packages/fast-form-generator-react/src/form/README.md, packages/fast-markdown-msft-react/.babelrc, packages/fast-markdown-msft-react/.npmignore, packages/fast-markdown-msft-react/README.md, packages/fast-markdown-msft-react/package-lock.json, packages/fast-markdown-msft-react/package.json, packages/fast-markdown-msft-react/src/index.spec.ts, packages/fast-markdown-msft-react/src/index.ts, packages/fast-markdown-msft-react/src/rule.ts, packages/fast-markdown-msft-react/tsconfig.json, packages/fast-markdown-msft-react/tslint.json
=> feat(markdown): add utility to convert markdown to msft component strings

packages/fast-jss-utilities/README.md
=> docs: update README.md to be correct

lerna.json, package.json, packages/fast-animation/package.json, packages/fast-browser-extensions/package.json, packages/fast-colors/package.json, packages/fast-components-class-name-contracts-base/package.json, packages/fast-components-class-name-contracts-msft/package.json, packages/fast-components-react-base/package.json, packages/fast-components-react-msft/package.json, packages/fast-components-styles-msft/package.json, packages/fast-development-site-react/package.json, packages/fast-form-generator-react/package.json, packages/fast-glyphs-msft/package.json, packages/fast-jest-snapshots-react/package.json, packages/fast-jss-manager-angular/package.json, packages/fast-jss-manager-react/package.json, packages/fast-jss-manager/package.json, packages/fast-jss-utilities/package.json, packages/fast-markdown-msft-react/package.json, packages/fast-permutator/package.json, packages/fast-tslint-rules/package.json, packages/fast-viewer-react/package.json
Closes [#360](https://github.com/Microsoft/fast-dna/issues/360)
=> update(packages): bumps all packages to 1.0.4

.travis.yml, packages/fast-animation/package.json, packages/fast-components-react-base/package.json, packages/fast-components-react-msft/package.json, packages/fast-development-site-react/package.json, packages/fast-form-generator-react/package.json, packages/fast-permutator/package.json, packages/fast-viewer-react/package.json
Closes [364](https://github.com/Microsoft/fast-dna/issues/364)
=> build(travis-ci) : fix build timeout issues

package-lock.json, packages/fast-development-site-react/app/app.tsx, packages/fast-development-site-react/app/components/button.schema.json, packages/fast-development-site-react/app/components/button.tsx, packages/fast-development-site-react/app/components/paragraph.schema.json, packages/fast-development-site-react/app/components/paragraph.tsx, packages/fast-development-site-react/package-lock.json, packages/fast-development-site-react/package.json, packages/fast-development-site-react/src/components/shell/pane.tsx, packages/fast-development-site-react/src/components/site/action-bar.tsx, packages/fast-development-site-react/src/components/site/category-item.tsx, packages/fast-development-site-react/src/components/site/category.tsx, packages/fast-development-site-react/src/components/site/component-view-toggle.tsx, packages/fast-development-site-react/src/components/site/component-wrapper.tsx, packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-development-site-react/src/components/toc/toc-item.tsx, packages/fast-development-site-react/src/utilities/componentExampleFactory.tsx, packages/fast-development-site-react/src/utilities/componentFactory.tsx, packages/fast-development-site-react/typings.d.ts, packages/fast-form-generator-react/app/index.tsx, packages/fast-form-generator-react/package.json, packages/fast-form-generator-react/src/form/form-item.select.tsx, packages/fast-markdown-msft-react/package.json
=> feat(form): add the form generator to the development site

packages/fast-components-react-base/tsconfig.json, packages/fast-components-react-base/typings.d.ts, packages/fast-components-react-msft/tsconfig.json, packages/fast-components-react-msft/typings.d.ts
=> chore(build): add the typings definitions file to accomodate importing JSON files

.travis.yml
=> chore(packages): add configurations to fix Travis CI errors during Lerna publish

.travis.yml
=> chore(packages): add condition to ignore code coverage for deploy

packages/fast-development-site-react/app/app.tsx, packages/fast-development-site-react/src/components/shell/action-bar.tsx, packages/fast-development-site-react/src/components/shell/canvas.tsx, packages/fast-development-site-react/src/components/shell/pane.tsx, packages/fast-development-site-react/src/components/site/action-bar.tsx, packages/fast-development-site-react/src/components/site/component-view.tsx, packages/fast-development-site-react/src/components/site/component-wrapper.tsx, packages/fast-development-site-react/src/components/site/dev-tools.tsx, packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-development-site-react/src/components/toc/toc-menu.tsx
=> feat(docs): add development site tools panel

.travis.yml
=> chore(packages): updates to include debugging

.travis.yml
Upgrading statement to write into .npmrc file
=> chore(packages): update to include token and email in .npmrc file

.travis.yml
=> chore(packages): update to configuration with lerna publish

.travis.yml
Experimental update to generate the change logs, commit and provide status on those changes.
=> chore(packages): add conventional commits and status to publish

packages/fast-components-class-name-contracts-base/src/checkbox/index.ts, packages/fast-components-react-base/src/checkbox/__snapshots__/checkbox.spec.ts.snap, packages/fast-components-react-base/src/checkbox/checkbox.props.ts, packages/fast-components-react-base/src/checkbox/checkbox.tsx, packages/fast-components-react-base/src/checkbox/examples.data.ts, packages/fast-components-react-msft/src/checkbox/examples.data.ts, packages/fast-components-styles-msft/src/checkbox/index.ts
<body>
- Update styles for cross-browser support
- Fixes incorrect state handler
<footer>
Closes [#304](https://github.com/Microsoft/fast-dna/issues/304)
=> feat(checkbox): update styling and incorrect states

packages/fast-components-react-msft/src/divider/__snapshots__/divider.spec.ts.snap, packages/fast-components-react-msft/src/divider/divider.spec.ts, packages/fast-components-react-msft/src/hypertext/__snapshots__/hypertext.spec.ts.snap, packages/fast-components-react-msft/src/hypertext/hypertext.spec.ts, packages/fast-components-react-msft/src/image/__snapshots__/image.spec.ts.snap, packages/fast-components-react-msft/src/image/image.spec.ts, packages/fast-components-react-msft/src/label/__snapshots__/label.spec.ts.snap, packages/fast-components-react-msft/src/label/label.spec.ts, packages/fast-components-react-msft/src/typography/__snapshots__/typography.spec.ts.snap, packages/fast-components-react-msft/src/typography/typography.spec.ts
Closes [#341](https://github.com/microsoft/fast-dna/issues/341).
See related [issue](https://github.com/Microsoft/fast-dna/issues/402).
<body>
<footer>
=> test(snapshots): add missing snapshots for non-Chroma JSS components

packages/fast-components-react-msft/src/index.ts
=> fix(typography): fixes an issue where typography was not being exported

packages/fast-components-react-base/src/button/__snapshots__/button.spec.ts.snap, packages/fast-components-react-base/src/button/button.tsx
=> fix(button): fixes an issue where href was not being passed as part of the created anchor element

packages/fast-development-site-react/app/app.tsx, packages/fast-development-site-react/app/components/button.schema.json, packages/fast-development-site-react/app/components/button.tsx, packages/fast-development-site-react/src/components/site/action-bar.tsx, packages/fast-development-site-react/src/components/site/dev-tools-code-preview.tsx, packages/fast-development-site-react/src/components/site/dev-tools.tsx, packages/fast-development-site-react/src/components/site/index.tsx
=> feat(code-preview): add react code preview

packages/fast-components-react-msft/src/image/__snapshots__/image.spec.ts.snap, packages/fast-components-react-msft/src/image/examples.data.ts, packages/fast-development-site-react/src/components/shell/action-bar.tsx, packages/fast-development-site-react/src/components/shell/index.tsx, packages/fast-development-site-react/src/components/shell/pane.tsx, packages/fast-development-site-react/src/components/shell/row.tsx, packages/fast-development-site-react/src/components/site/action-bar.tsx, packages/fast-development-site-react/src/components/site/component-view.tsx, packages/fast-development-site-react/src/components/site/component-wrapper.tsx, packages/fast-development-site-react/src/components/site/index.tsx
=> fix(development-site): update styling

packages/fast-animation/package-lock.json, packages/fast-browser-extensions/package-lock.json, packages/fast-colors/package-lock.json, packages/fast-components-class-name-contracts-base/package-lock.json, packages/fast-components-class-name-contracts-msft/package-lock.json, packages/fast-components-react-base/package-lock.json, packages/fast-components-react-msft/package-lock.json, packages/fast-components-styles-msft/package-lock.json, packages/fast-development-site-react/app/components/button.schema.json, packages/fast-development-site-react/app/components/paragraph.schema.json, packages/fast-development-site-react/package-lock.json, packages/fast-development-site-react/src/components/shell/pane.tsx, packages/fast-form-generator-react/package-lock.json, packages/fast-form-generator-react/src/form/form-item.children.style.ts, packages/fast-form-generator-react/src/form/form-item.textarea.style.ts, packages/fast-form-generator-react/src/form/form-item.theme.style.ts, packages/fast-form-generator-react/src/form/form-section.style.ts, packages/fast-form-generator-react/src/form/form.style.ts, packages/fast-form-generator-react/src/utilities/form-input.style.ts, packages/fast-glyphs-msft/package-lock.json, packages/fast-jest-snapshots-react/package-lock.json, packages/fast-jss-manager-angular/package-lock.json, packages/fast-jss-manager-react/package-lock.json, packages/fast-jss-manager/package-lock.json, packages/fast-jss-utilities/package-lock.json, packages/fast-markdown-msft-react/package-lock.json, packages/fast-permutator/package-lock.json, packages/fast-tslint-rules/package-lock.json, packages/fast-viewer-react/package-lock.json
Closes [#419](https://github.com/Microsoft/fast-dna/issues/419)
<body>
<footer>
=> feat(form generator): updates styles found in configuration pane

packages/fast-development-site-react/src/components/shell/header.tsx, packages/fast-development-site-react/src/components/shell/pane.tsx, packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-development-site-react/src/components/toc/toc-menu.tsx, packages/fast-form-generator-react/app/components/align-horizontal/__snapshots__/align-horizontal.spec.tsx.snap, packages/fast-form-generator-react/app/components/align-vertical/__snapshots__/align-vertical.spec.tsx.snap, packages/fast-form-generator-react/app/components/any-of/__snapshots__/any-of.spec.tsx.snap, packages/fast-form-generator-react/app/components/attribute-assignment/__snapshots__/attribute-assignment.spec.tsx.snap, packages/fast-form-generator-react/app/components/checkbox/__snapshots__/checkbox.spec.tsx.snap, packages/fast-form-generator-react/app/components/general-example/__snapshots__/general-example.spec.tsx.snap, packages/fast-form-generator-react/app/components/number-field/__snapshots__/number-field.spec.tsx.snap, packages/fast-form-generator-react/app/components/objects/__snapshots__/objects.spec.tsx.snap, packages/fast-form-generator-react/app/components/one-of/__snapshots__/one-of.spec.tsx.snap, packages/fast-form-generator-react/app/components/text-field/__snapshots__/text-field.spec.tsx.snap, packages/fast-form-generator-react/app/components/theme/__snapshots__/theme.spec.tsx.snap, packages/fast-form-generator-react/app/components/weight-properties/__snapshots__/weight-properties.spec.tsx.snap, packages/fast-form-generator-react/src/form/form.props.ts, packages/fast-form-generator-react/src/form/form.tsx
=> chore(dev-site): fix dev site spacing and styling issues for the left pane and header

packages/fast-form-generator-react/package-lock.json, packages/fast-form-generator-react/src/class-name-contracts/form-item.array.class-name-contract.ts, packages/fast-form-generator-react/src/class-name-contracts/form-item.children.class-name-contract.ts, packages/fast-form-generator-react/src/form/form-item.array.style.ts, packages/fast-form-generator-react/src/form/form-item.array.tsx, packages/fast-form-generator-react/src/form/form-item.children.style.ts, packages/fast-form-generator-react/src/form/sorting.tsx, packages/fast-form-generator-react/src/utilities/form-input.style.ts
Closes [#425](https://github.com/Microsoft/fast-dna/issues/425)
<body>
<footer>
=> fix(form generator): fixes drag and drop, updates styles and shape

packages/fast-development-site-react/src/components/site/action-bar.tsx, packages/fast-development-site-react/src/components/site/component-view.tsx, packages/fast-development-site-react/src/components/site/component-wrapper.tsx, packages/fast-development-site-react/src/components/site/dev-tools.tsx
Hide the created but empty tab panels and detail section temporarily.
=> chore: hide empty tab panels and detail section

.circleci/config.yml, .circleci/run-coverage-locally.sh, packages/fast-jss-manager-react/package.json, packages/fast-markdown-msft-react/package.json
=> chore: update code coverage for circle-ci

packages/fast-form-generator-react/src/form/form-item.align-horizontal.style.ts, packages/fast-form-generator-react/src/form/form-item.align-vertical.style.ts
Closes [#429](https://github.com/Microsoft/fast-dna/issues/429)
<body>
<footer>
=> fix(form generator): fix malformed vertical alignment svgs and update const for readability

.circleci/config.yml, .circleci/run-coverage-locally.sh
=> update to use env variables on circle ci web

packages/fast-development-site-react/src/components/shell/index.tsx, packages/fast-development-site-react/src/components/site/index.tsx
Closes [#439](https://github.com/Microsoft/fast-dna/issues/439)
<body>
<footer>
=> fix(development site): add font-family globally

packages/fast-development-site-react/src/components/site/dev-tools.tsx, packages/fast-development-site-react/src/components/site/index.tsx
=> feat(schema): add schema view to dev tools

README.md
=> update readme to remove travis ci

packages/fast-form-generator-react/src/form/form-item.array.style.ts, packages/fast-form-generator-react/src/form/form-item.array.tsx, packages/fast-form-generator-react/src/form/form-item.checkbox.style.ts, packages/fast-form-generator-react/src/form/form-item.children.style.ts, packages/fast-form-generator-react/src/form/form-item.children.tsx, packages/fast-form-generator-react/src/form/form-item.theme.style.ts, packages/fast-form-generator-react/src/form/form-section.style.ts, packages/fast-form-generator-react/src/utilities/form-input.style.ts
Closes [#430](https://github.com/Microsoft/fast-dna/issues/430)
<body>
<footer>
=> feat(form generator): add focus/hover states

README.md
* update links to issues now that 'choose' is supported
* update content to reflect expanded Wiki documentation
=> docs: update repository home page

packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-development-site-react/src/components/toc/toc-item.tsx
=> fix(dev-site): fixes html5 validation issues with dev site markup

packages/fast-animation/client/examples/app/app.tsx, packages/fast-animation/package-lock.json, packages/fast-animation/package.json, packages/fast-components-react-base/package-lock.json, packages/fast-components-react-base/package.json, packages/fast-components-react-base/webpack.config.js, packages/fast-components-react-msft/package-lock.json, packages/fast-components-react-msft/package.json, packages/fast-components-react-msft/webpack.config.js, packages/fast-layouts-react/src/pane/pane.tsx
=> chore(perf): remove unnecessary instances of lodash in favor of lodash-es and add bundle analyzer to react-msft for debugging perf

packages/fast-components-class-name-contracts-base/src/index.ts, packages/fast-components-class-name-contracts-base/src/text-field/index.ts, packages/fast-components-react-base/app/examples.ts, packages/fast-components-react-base/src/index.ts, packages/fast-components-react-base/src/text-field/README.md, packages/fast-components-react-base/src/text-field/__snapshots__/text-field.spec.ts.snap, packages/fast-components-react-base/src/text-field/examples.data.ts, packages/fast-components-react-base/src/text-field/examples.data.tsx, packages/fast-components-react-base/src/text-field/index.ts, packages/fast-components-react-base/src/text-field/text-field.props.ts, packages/fast-components-react-base/src/text-field/text-field.schema.json, packages/fast-components-react-base/src/text-field/text-field.spec.ts, packages/fast-components-react-base/src/text-field/text-field.tsx, packages/fast-components-react-msft/app/examples.ts, packages/fast-components-react-msft/src/index.ts, packages/fast-components-react-msft/src/text-field/examples.data.ts, packages/fast-components-react-msft/src/text-field/index.ts, packages/fast-components-styles-msft/src/index.ts, packages/fast-components-styles-msft/src/text-field/index.ts
=> feat(textfield) : add new component

packages/fast-components-styles-msft/src/button/index.ts, packages/fast-components-styles-msft/src/checkbox/index.ts, packages/fast-components-styles-msft/src/label/index.ts, packages/fast-components-styles-msft/src/toggle/index.ts, packages/fast-development-site-react/src/components/shell/header.tsx, packages/fast-development-site-react/src/components/site/action-bar.tsx, packages/fast-development-site-react/src/components/toc/toc-menu.tsx
<body>
closes #481, closes #483 ( & other fit and finish)
<footer>
=> chore(style): fit and finish for components and doc site

packages/fast-components-styles-msft/src/checkbox/index.ts
Closes [#482](https://github.com/Microsoft/fast-dna/issues/482)
<body>
<footer>
=> fix(checkbox): fix broken indeterminate state UI in Firefox

README.md
=> add Discord link to join the community

packages/fast-application-utilities/.babelrc, packages/fast-application-utilities/README.md, packages/fast-application-utilities/package-lock.json, packages/fast-application-utilities/package.json, packages/fast-application-utilities/src/index.ts, packages/fast-application-utilities/src/localization.spec.ts, packages/fast-application-utilities/src/localization.ts, packages/fast-application-utilities/tsconfig.json, packages/fast-application-utilities/tslint.json, packages/fast-components-react-msft/app/app.tsx, packages/fast-components-react-msft/package.json, packages/fast-development-site-react/app/app.tsx, packages/fast-development-site-react/app/components/button/button.tsx, packages/fast-development-site-react/app/components/paragraph/paragraph.tsx, packages/fast-development-site-react/app/design-system/index.ts, packages/fast-development-site-react/app/index.tsx, packages/fast-development-site-react/package.json, packages/fast-development-site-react/src/components/shell/info-bar.tsx, packages/fast-development-site-react/src/components/site/category-item.tsx, packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-development-site-react/webpack.config.js, packages/fast-jss-manager-react/src/manage-jss.tsx
=> feat(localization): adds direction rtl/ltr updating

packages/fast-animation/.npmignore, packages/fast-animation/package.json
=> chore(animation): fixes incorrect npm registry config and unmarks package as private

CONTRIBUTING.md
Updates Team/Group names for better management and alignment into open source
=> docs: update to contribution policy

packages/fast-layouts-react/README.md
=> chore(fast-layouts-react): add readme.md

packages/fast-components-styles-msft/src/button/index.ts, packages/fast-components-styles-msft/src/text-field/index.ts, packages/fast-components-styles-msft/src/utilities/colors.ts
=> fix(fast-components-styles-msft): remove duplicate code and creates a utility to apply mixed colors

packages/fast-components-react-msft/webpack.config.js, packages/fast-permutator/__tests__/test-utils/index.js, packages/fast-permutator/package.json, packages/fast-permutator/src/utilities/get-deep-prop-locations.js, packages/fast-permutator/src/utilities/get-example.js, packages/fast-permutator/src/utilities/permutate-schemas.js, packages/fast-permutator/src/utilities/remove-empty-objects.js, packages/fast-permutator/src/utilities/remove-undefined.js, packages/fast-permutator/src/utilities/resolve-all-of.js, packages/fast-permutator/src/utilities/resolve-dependencies.js, packages/fast-permutator/src/utilities/resolve-not-required.js, packages/fast-permutator/src/utilities/resolve-one-of-any-of.js, packages/fast-permutator/src/utilities/resolve-recursive-references.js, packages/fast-permutator/src/utilities/resolve-references.js, packages/fast-permutator/src/utilities/resolve-schema-props.js, packages/fast-permutator/src/utilities/set-deep-object.js
=> fix(permutator): fix an issue where lodash was being referred to and not lodash-es

README.md
=> chore(docs): update root readme.md

packages/fast-jss-manager-react/README.md, packages/fast-jss-manager-react/src/jss.ts, packages/fast-jss-manager-react/src/manage-jss.spec.tsx, packages/fast-jss-manager-react/src/manage-jss.tsx, packages/fast-permutator/package-lock.json
=> feat(jss-manager): update to enable server-side rendering of stylesheets.

packages/fast-components-react-msft/app/app.tsx, packages/fast-components-react-msft/package-lock.json, packages/fast-components-styles-msft/package.json, packages/fast-components-styles-msft/src/button/index.ts, packages/fast-components-styles-msft/src/checkbox/index.ts, packages/fast-components-styles-msft/src/design-system/index.ts, packages/fast-components-styles-msft/src/toggle/index.ts, packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-jss-utilities/src/localization.spec.ts, packages/fast-jss-utilities/src/localization.ts, packages/fast-permutator/package-lock.json
=> feat(fast-components-react-msft): add localized styles and enable ltr/rtl swapping on documentation site

packages/fast-development-site-react/src/components/site/dev-tools-code-preview.tsx, packages/fast-form-generator-react/src/class-name-contracts/form-item.children.class-name-contract.ts, packages/fast-form-generator-react/src/form/form-item.children.style.ts, packages/fast-form-generator-react/src/form/form-item.children.text.tsx, packages/fast-form-generator-react/src/form/form-item.children.tsx, packages/fast-form-generator-react/src/form/form.tsx, packages/fast-form-generator-react/src/utilities/form-input.style.ts
=> feat(development-site): add ability to have children as strings in the form generator and development site dev tools

packages/fast-development-site-react/src/components/site/index.tsx
=> fix(fast-development-site-react): fix the selection model to always point to a menu item

packages/fast-development-site-react/src/components/site/action-bar.tsx, packages/fast-development-site-react/src/components/site/index.tsx
=> fix(fast-development-site): fix a pathing issue between the detail and example pages

packages/fast-components-react-msft/app/app.tsx, packages/fast-development-site-react/src/components/site/category-documentation.tsx, packages/fast-development-site-react/src/components/site/component-wrapper.tsx, packages/fast-development-site-react/src/components/site/dev-tools-code-preview.tsx, packages/fast-development-site-react/src/components/site/dev-tools.tsx, packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-layouts-react/src/canvas/canvas.tsx
Closes #547, closes #537, closes #538, closes #549, closes #550, closes #539
=> chore(fast-development-site-react) string formatting, styling and spacing adjustments

packages/fast-components-react-msft/app/app.tsx, packages/fast-development-site-react/app/app.tsx, packages/fast-development-site-react/src/components/shell/info-bar.tsx, packages/fast-development-site-react/src/components/site/category.tsx, packages/fast-development-site-react/src/components/site/index.tsx
=> feat(fast-development-site): Create infobar for fast site

packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-layouts-react/app/index.tsx, packages/fast-layouts-react/src/pane/pane.tsx, packages/fast-layouts-react/src/row/row.props.ts, packages/fast-layouts-react/src/row/row.tsx
=> feat(fast-development-site): add resize capability to row component

packages/fast-jest-snapshots-react/package.json
=> chore(fast-jest-snapshots-react): update package to be publicly available on npm

packages/fast-layouts-react/src/row/row.tsx
=> chore(row): fix for row resizes on window resize

packages/fast-development-site-react/src/components/site/dev-tools.tsx
=> fix(fast-development-site)add scrolling to Dev Tools

packages/fast-components-react-msft/app/app.tsx, packages/fast-development-site-react/src/components/shell/header.tsx, packages/fast-development-site-react/src/components/site/menu.tsx
=> fix(fast-development-site) Move design kit link behind Site Menu

packages/fast-development-site-react/src/components/site/configuration-panel.tsx, packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-form-generator-react/app/components/align-horizontal/__snapshots__/align-horizontal.spec.tsx.snap, packages/fast-form-generator-react/app/components/align-vertical/__snapshots__/align-vertical.spec.tsx.snap, packages/fast-form-generator-react/app/components/any-of/__snapshots__/any-of.spec.tsx.snap, packages/fast-form-generator-react/app/components/attribute-assignment/__snapshots__/attribute-assignment.spec.tsx.snap, packages/fast-form-generator-react/app/components/checkbox/__snapshots__/checkbox.spec.tsx.snap, packages/fast-form-generator-react/app/components/general-example/__snapshots__/general-example.spec.tsx.snap, packages/fast-form-generator-react/app/components/number-field/__snapshots__/number-field.spec.tsx.snap, packages/fast-form-generator-react/app/components/objects/__snapshots__/objects.spec.tsx.snap, packages/fast-form-generator-react/app/components/one-of/__snapshots__/one-of.spec.tsx.snap, packages/fast-form-generator-react/app/components/text-field/__snapshots__/text-field.spec.tsx.snap, packages/fast-form-generator-react/app/components/theme/__snapshots__/theme.spec.tsx.snap, packages/fast-form-generator-react/app/components/weight-properties/__snapshots__/weight-properties.spec.tsx.snap, packages/fast-form-generator-react/src/form/form.tsx
=> fix(fast-development-site): remove component name and add presets tab

packages/fast-development-site-react/package-lock.json, packages/fast-development-site-react/package.json, packages/fast-development-site-react/src/components/site/dev-tools-code-preview-style.ts, packages/fast-development-site-react/src/components/site/dev-tools-code-preview.tsx
=> feat(fast-development-site): add syntax highlighting to code preview

packages/fast-components-react-msft/src/text-field/examples.data.tsx
=> fix(fast-development-site): fix for text field example not rendering

packages/fast-components-react-base/README.md, packages/fast-components-react-msft/README.md, packages/fast-components-styles-msft/README.md, packages/fast-development-site-react/README.md, packages/fast-form-generator-react/README.md, packages/fast-form-generator-react/src/form/README.md, packages/fast-glyphs-msft/README.md, packages/fast-glyphs-msft/utilities/README.md, packages/fast-jss-manager-angular/README.md, packages/fast-jss-manager-react/README.md, packages/fast-jss-manager/README.md, packages/fast-jss-utilities/README.md, packages/fast-markdown-msft-react/README.md
=> docs: update README files to include missing documentation

packages/fast-development-site-react/README.md, packages/fast-development-site-react/src/components/site/component-wrapper.tsx, packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-glyphs-msft/glyphs/transparency.svg
=> feat(fast-development-site): add component transparency toggle to info bar

package.json, packages/fast-animation/package.json, packages/fast-application-utilities/package.json, packages/fast-browser-extensions/package.json, packages/fast-colors/package.json, packages/fast-components-class-name-contracts-base/package.json, packages/fast-components-class-name-contracts-msft/package.json, packages/fast-components-react-base/package.json, packages/fast-components-react-msft/package.json, packages/fast-components-styles-msft/package.json, packages/fast-development-site-react/package-lock.json, packages/fast-development-site-react/package.json, packages/fast-form-generator-react/package.json, packages/fast-glyphs-msft/package.json, packages/fast-jest-snapshots-react/package.json, packages/fast-jss-manager-angular/package-lock.json, packages/fast-jss-manager-angular/package.json, packages/fast-jss-manager-react/package.json, packages/fast-jss-manager/package.json, packages/fast-jss-utilities/package.json, packages/fast-layouts-react/package.json, packages/fast-markdown-msft-react/package.json, packages/fast-permutator/package.json, packages/fast-sketch-library/package.json, packages/fast-tslint-rules/package.json, packages/fast-viewer-react/package.json
<body>
Updates include code coverage, making package.json files consistent, and updating to use URL for contact rather than a deprecated EMAIL address.
<footer>
=> chore(packages): update for consistency

packages/fast-components-react-msft/app/app.tsx
=> chore(fast-development-site): update class name contract for hyperlink

.github/CODEOWNERS, .github/CODEOWNERS.md
=> chore(github): add required code owner sign-off for packages

packages/fast-components-react-msft/src/index.ts, packages/fast-markdown-msft-react/package.json, packages/fast-markdown-msft-react/src/index.spec.ts, packages/fast-markdown-msft-react/src/index.ts, packages/fast-markdown-msft-react/src/rule.ts
=> chore(fast-markdown-msft-react): update markdown rules to reference enums

packages/fast-development-site-react/src/components/site/component-wrapper.tsx
=> fix(fast-development-site): correctly display component view border

packages/fast-development-site-react/src/components/site/index.tsx
=> feat(fast-development-site-react): add ability to update component values dynamically from outside the site

packages/fast-form-generator-react/src/utilities/form-input.style.ts
Closes [#599](https://github.com/Microsoft/fast-dna/issues/599)
<body>
<footer>
=> fix(fast-form-generator-react): update + glyph positioning

packages/fast-components-styles-msft/package.json, packages/fast-components-styles-msft/src/button/index.ts, packages/fast-components-styles-msft/src/checkbox/index.ts, packages/fast-components-styles-msft/src/hypertext/index.ts, packages/fast-components-styles-msft/src/text-field/index.ts, packages/fast-components-styles-msft/src/toggle/index.ts
=> feat(fast-components-styles-msft): set default config values as a fallback if there is a missing or incomplete design system

packages/fast-components-react-base/src/button/examples.data.tsx, packages/fast-components-react-base/src/checkbox/examples.data.tsx, packages/fast-components-react-base/src/divider/examples.data.tsx, packages/fast-components-react-base/src/hypertext/examples.data.tsx, packages/fast-components-react-base/src/image/examples.data.tsx, packages/fast-components-react-base/src/label/examples.data.tsx, packages/fast-components-react-base/src/text-field/examples.data.tsx, packages/fast-components-react-base/src/toggle/examples.data.tsx, packages/fast-components-react-base/src/typography/examples.data.tsx, packages/fast-components-react-msft/src/button/examples.data.tsx, packages/fast-components-react-msft/src/checkbox/examples.data.tsx, packages/fast-components-react-msft/src/divider/examples.data.tsx, packages/fast-components-react-msft/src/heading/examples.data.tsx, packages/fast-components-react-msft/src/hypertext/examples.data.tsx, packages/fast-components-react-msft/src/image/examples.data.tsx, packages/fast-components-react-msft/src/label/examples.data.tsx, packages/fast-components-react-msft/src/text-field/examples.data.tsx, packages/fast-components-react-msft/src/toggle/examples.data.tsx, packages/fast-components-react-msft/src/typography/examples.data.tsx, packages/fast-form-generator-react/app/components/index.ts
=> fix: update imports of JSON schemas to not use * as notation

packages/fast-css-editor-react/.babelrc, packages/fast-css-editor-react/.npmignore, packages/fast-css-editor-react/README.md, packages/fast-css-editor-react/app/app.tsx, packages/fast-css-editor-react/app/components/editor.spec.tsx, packages/fast-css-editor-react/src/editor.schema.json, packages/fast-css-editor-react/src/index.tsx, packages/fast-css-editor-react/src/position/README.md, packages/fast-css-editor-react/src/position/position.schema.json
=> chore: update the CSS editor to use a flattened property structure

packages/fast-components-class-name-contracts-msft/src/flipper/index.ts, packages/fast-components-class-name-contracts-msft/src/index.ts, packages/fast-components-react-msft/app/examples.ts, packages/fast-components-react-msft/src/flipper/README.md, packages/fast-components-react-msft/src/flipper/examples.data.tsx, packages/fast-components-react-msft/src/flipper/flipper.props.ts, packages/fast-components-react-msft/src/flipper/flipper.schema.json, packages/fast-components-react-msft/src/flipper/flipper.tsx, packages/fast-components-react-msft/src/flipper/index.ts, packages/fast-components-styles-msft/src/flipper/index.ts, packages/fast-components-styles-msft/src/index.ts
=> feat(fast-components-react-msft): add flipper as a new component

packages/fast-components-styles-msft/src/divider/index.ts
=> fix(divider): fix divider component so that it is styled

packages/fast-components-styles-msft/src/checkbox/index.ts
=> fix(checkbox): fix broken visual style and glyph in rtl

packages/fast-components-react-base/package.json, packages/fast-components-react-base/src/toggle/__snapshots__/toggle.spec.ts.snap, packages/fast-components-react-base/src/toggle/toggle.props.ts, packages/fast-components-react-base/src/toggle/toggle.tsx, packages/fast-components-react-msft/src/toggle/examples.data.tsx, packages/fast-components-styles-msft/src/toggle/index.ts
=> fix(toggle): toggle "Selected" option does not work and is missing background color

packages/fast-components-react-msft/app/app.tsx, packages/fast-development-site-react/README.md, packages/fast-development-site-react/app/app.tsx, packages/fast-development-site-react/src/components/site/component-wrapper.tsx, packages/fast-development-site-react/src/components/site/index.tsx
=> feat(fast-development-site): add component theme support

packages/fast-form-generator-react/src/form/form-section.utilities.tsx
=> fix(fast-form-generator-react): correct the validation between oneOf and anyOf checks

packages/fast-components-react-base/src/image/image.schema.json
=> chore(image): update image schema to match the current code implementation

packages/fast-components-react-msft/webpack.config.js
=> chore(fast-components-react-msft): add a title to the webpack app

packages/fast-form-generator-react/src/form/form-item.children.style.ts, packages/fast-form-generator-react/src/utilities/form-input.style.ts
=> fix(fast-form-generator-react): entire list item should be clickable when navigating between sections

packages/fast-components-react-msft/app/examples.ts
=> chore(docs): correctly alphabetize docs site component links

packages/fast-components-styles-msft/src/label/index.ts
=> fix(label): added dark theme support for label

packages/fast-components-react-msft/src/button/README.md
=> chore(button): update readme documentation to specify how to create an anchor

packages/fast-development-site-react/src/components/toc/toc-item.tsx, packages/fast-form-generator-react/src/form/form-item.array.style.ts, packages/fast-form-generator-react/src/utilities/form-input.style.ts
Closes [#666](https://github.com/Microsoft/fast-dna/issues/666)
<body>
<footer>
=> feat (fast-form-generator): update pop-up menu style, address incorrect shadowing 

packages/fast-components-styles-msft/src/toggle/index.ts
=> fix(toggle): fix labels on toggle to support dark theme

packages/fast-development-site-react/src/components/shell/info-bar.tsx, packages/fast-development-site-react/src/components/site/index.tsx
=> fix(fast-development-site): text cursor for non interactable areas should be default cursor

packages/fast-components-react-msft/package-lock.json, packages/fast-components-react-msft/package.json, packages/fast-components-react-msft/src/button/__snapshots__/button.spec.tsx.snap, packages/fast-components-react-msft/src/button/button.spec.ts, packages/fast-components-react-msft/src/button/button.spec.tsx, packages/fast-components-react-msft/src/checkbox/__snapshots__/checkbox.spec.ts.snap, packages/fast-components-react-msft/src/checkbox/checkbox.spec.ts, packages/fast-components-react-msft/src/divider/__snapshots__/divider.spec.ts.snap, packages/fast-components-react-msft/src/divider/divider.spec.ts, packages/fast-components-react-msft/src/flipper/__snapshots__/flipper.spec.tsx.snap, packages/fast-components-react-msft/src/flipper/flipper.spec.ts, packages/fast-components-react-msft/src/flipper/flipper.spec.tsx, packages/fast-components-react-msft/src/heading/__snapshots__/heading.spec.tsx.snap, packages/fast-components-react-msft/src/heading/heading.spec.ts, packages/fast-components-react-msft/src/heading/heading.spec.tsx, packages/fast-components-react-msft/src/hypertext/__snapshots__/hypertext.spec.ts.snap, packages/fast-components-react-msft/src/hypertext/hypertext.spec.ts, packages/fast-components-react-msft/src/image/__snapshots__/image.spec.ts.snap, packages/fast-components-react-msft/src/image/image.spec.ts, packages/fast-components-react-msft/src/label/__snapshots__/label.spec.ts.snap, packages/fast-components-react-msft/src/label/label.spec.ts, packages/fast-components-react-msft/src/text-field/__snapshots__/text-field.spec.ts.snap, packages/fast-components-react-msft/src/text-field/text-field.spec.ts, packages/fast-components-react-msft/src/toggle/__snapshots__/toggle.spec.ts.snap, packages/fast-components-react-msft/src/toggle/toggle.spec.ts, packages/fast-components-react-msft/src/typography/__snapshots__/typography.spec.ts.snap, packages/fast-components-react-msft/src/typography/typography.spec.ts
=> feat(fast-components-react-msft): add enzyme and unit tests for MSFT specific components

packages/fast-form-generator-react/src/form/form-item.textarea.style.ts
=> fix(fast-form-generator): remove resize behavior and update fontfamily

packages/fast-components-styles-msft/src/hypertext/index.ts
=> fix(hypertext): update foreground to use design system colors for theming support

packages/fast-development-site-react/src/components/shell/header.tsx, packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-development-site-react/src/components/site/menu.tsx
=> feat(fast-development-site): update waffle menu style and animations

packages/fast-colors/README.md, packages/fast-colors/package-lock.json, packages/fast-colors/package.json, packages/fast-colors/src/contrast.spec.ts, packages/fast-colors/src/contrast.ts, packages/fast-colors/src/index.ts, packages/fast-colors/src/luminosity.spec.ts, packages/fast-colors/src/luminosity.ts
=> feat(colors): add contrast and luminosity utilities

packages/fast-components-react-msft/README.md
=> chore(fast-components-react-msft): fix incorrect web address in documentation in readme

packages/fast-development-site-react/src/components/toc/toc-item.tsx, packages/fast-development-site-react/src/components/toc/toc-menu.tsx
=> feat(fast-development-site): add hover and focus states to TOC menu items

packages/fast-components-react-base/src/label/examples.data.tsx, packages/fast-components-react-base/src/label/label.props.ts, packages/fast-components-react-base/src/label/label.spec.tsx, packages/fast-components-react-base/src/label/label.tsx
=> fix(label): fix spelling error in interface name for managed classes

packages/fast-development-site-react/src/components/site/action-bar.tsx, packages/fast-development-site-react/src/components/site/component-view-toggle.tsx, packages/fast-development-site-react/src/components/site/configuration-panel.tsx
=> feat(fast-development-site): add hover and focus states to action bar items

packages/fast-form-generator-react/src/form/form-item.children.style.ts
=> fix(fast-form-generator): alignment of fast form children text and glyph

packages/fast-development-site-react/app/app.tsx, packages/fast-development-site-react/src/components/site/dev-tools-code-preview.tsx, packages/fast-development-site-react/src/components/site/dev-tools.tsx, packages/fast-development-site-react/src/components/site/index.tsx
Closes [#555](https://github.com/Microsoft/fast-dna/issues/555)
<body>
<footer>
=> feat(fast-development-site-react): add enums for tabType for better type safety and clarity

packages/fast-components-react-base/src/hypertext/README.md, packages/fast-components-react-base/src/hypertext/hypertext.tsx, packages/fast-components-react-msft/src/hypertext/README.md, packages/fast-components-react-msft/src/hypertext/__snapshots__/hypertext.spec.ts.snap
=> fix(hyperlink): correctly handle href as a handled prop and update documentation

README.md
<body>My friends Nick and Jane say this project doesn’t actually support Angular.
<footer>I like to help OSS projects maintain their documentation.
=> docs(fast-dna): remove reference to Angular

.circleci/config.yml
=> chore(build): fix build break due to incorrect lerna version install

packages/fast-components-react-base/src/horizontal-overflow/__snapshots__/horizontal-overflow.spec.tsx.snap, packages/fast-components-react-base/src/horizontal-overflow/examples.data.tsx, packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
Closes [#781](https://github.com/Microsoft/fast-dna/issues/781)
<body>
<footer>
=> fix(fast-components-react-base): allow horizontal overflow to accept passed class names

packages/fast-components-react-base/README.md
=> fix: correct documentation of implementation of base component

packages/fast-components-react-base/src/button/examples.data.tsx, packages/fast-components-react-base/src/checkbox/examples.data.tsx, packages/fast-components-react-base/src/dialog/examples.data.tsx, packages/fast-components-react-base/src/divider/examples.data.tsx, packages/fast-components-react-base/src/horizontal-overflow/examples.data.tsx, packages/fast-components-react-base/src/hypertext/examples.data.tsx, packages/fast-components-react-base/src/image/examples.data.tsx, packages/fast-components-react-base/src/label/examples.data.tsx, packages/fast-components-react-base/src/tabs/examples.data.tsx, packages/fast-components-react-base/src/text-field/examples.data.tsx, packages/fast-components-react-base/src/toggle/examples.data.tsx, packages/fast-components-react-base/src/typography/examples.data.tsx, packages/fast-components-react-msft/src/button/examples.data.tsx, packages/fast-components-react-msft/src/checkbox/examples.data.tsx, packages/fast-components-react-msft/src/dialog/examples.data.tsx, packages/fast-components-react-msft/src/divider/examples.data.tsx, packages/fast-components-react-msft/src/flipper/examples.data.tsx, packages/fast-components-react-msft/src/heading/examples.data.tsx, packages/fast-components-react-msft/src/hypertext/examples.data.tsx, packages/fast-components-react-msft/src/image/examples.data.tsx, packages/fast-components-react-msft/src/label/examples.data.tsx, packages/fast-components-react-msft/src/text-field/examples.data.tsx, packages/fast-components-react-msft/src/toggle/examples.data.tsx, packages/fast-components-react-msft/src/typography/examples.data.tsx, packages/fast-development-site-react/src/components/site/category-item.tsx, packages/fast-development-site-react/src/utilities/component-detail-example-factory.tsx, packages/fast-development-site-react/src/utilities/component-example-factory.tsx, packages/fast-development-site-react/src/utilities/component-factory.tsx, packages/fast-development-site-react/src/utilities/index.ts, packages/fast-jest-snapshots-react/src/index.ts
=> fix: remove extraneous requirements for snapshot interface

packages/fast-form-generator-react/app/components/number-field/__snapshots__/number-field.spec.tsx.snap, packages/fast-form-generator-react/app/components/text-field/__snapshots__/text-field.spec.tsx.snap, packages/fast-form-generator-react/app/components/weight-properties/__snapshots__/weight-properties.spec.tsx.snap, packages/fast-form-generator-react/src/form/form-item.select.tsx, packages/fast-form-generator-react/src/form/form-section.tsx
=> fix(fast-form-generator-react): fix form item select to return the correct value based on type

packages/fast-animation/__tests__/index.ts, packages/fast-animation/client/examples/app/components/TestPage.tsx, packages/fast-animation/lib/animate/index.ts, packages/fast-animation/lib/animateGroup/index.ts, packages/fast-animation/lib/fade/index.ts, packages/fast-animation/lib/tsconfig.json, packages/fast-animation/package-lock.json, packages/fast-animation/package.json, packages/fast-animation/tsconfig.json
closes #796
This PR implement's partial interfaces for the Keyframe interface - this is due to an outstanding issue in TypeScript.
More details here: #815
=> chore: update fast-animation's TypeScript

packages/fast-components-react-base/src/checkbox/checkbox.spec.tsx, packages/fast-components-react-base/src/checkbox/checkbox.tsx
=> chore(checkbox): update to coding standards

.github/ISSUE_TEMPLATE/Feature_request.md
Update the `.github/` template features.
=> chore(github): update to improve wording on feature template

packages/fast-form-generator-react/app/components/any-of/__snapshots__/any-of.spec.tsx.snap, packages/fast-form-generator-react/app/components/any-of/any-of.schema.json, packages/fast-form-generator-react/app/components/objects/objects.schema.json, packages/fast-form-generator-react/src/form/form-item.children.tsx, packages/fast-form-generator-react/src/form/form-section.props.ts, packages/fast-form-generator-react/src/form/form.props.ts, packages/fast-form-generator-react/src/form/form.spec.ts, packages/fast-form-generator-react/src/form/form.tsx, packages/fast-form-generator-react/src/form/form.utilities.ts
=> chore(fast-form-generator-react): update the component tracker to use the navigation utility

.github/CODEOWNERS
Update ownership for developer operations specific files
=> chore(devops): update for devops specific files and ownership

packages/fast-components-react-msft/app/color-picker.tsx
=> fix(fast-components-react-msft): update label attribute used in color picker

packages/fast-development-site-react/src/components/site/configuration-panel.tsx
=> fix: set scrolling overflow on configuration panel

packages/fast-components-react-msft/src/caption/caption.props.ts, packages/fast-components-react-msft/src/caption/caption.spec.tsx, packages/fast-components-react-msft/src/caption/caption.tsx, packages/fast-components-react-msft/src/caption/index.ts, packages/fast-components-react-msft/src/index.ts, packages/fast-components-react-msft/src/subheading/index.ts
=> fix(fast-components-react-msft): fix missing exports from package

packages/fast-components-react-msft/src/caption/index.ts
=> fix(caption): add missing reference for caption className contract interface

packages/fast-components-react-base/src/text-field/text-field.props.ts, packages/fast-components-react-base/src/text-field/text-field.tsx
=> fix: implement the correct prop interface for unhandled props in text-field

packages/fast-components-styles-msft/src/dialog/index.ts, packages/fast-components-styles-msft/src/utilities/elevation.ts
=> feat(style): add elevation shadow ramp and functions

packages/fast-components-react-base/README.md, packages/fast-components-react-msft/README.md
=> chore(docs): fix component readme for consistency

packages/fast-components-react-msft/package.json
=> fix(call-to-action): fix glyph import due to missing package dependency

.github/CODEOWNERS
=> chore(codeowners): add additional markdown codeowner

packages/fast-components-react-base/src/foundation/foundation.spec.tsx, packages/fast-components-react-base/src/foundation/foundation.ts, packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx, packages/fast-components-react-base/src/progress/progress.tsx, packages/fast-components-react-base/src/tabs/tabs.tsx, packages/fast-components-react-msft/src/button/button.tsx
=> feat: add slot-selection support to foundation

packages/fast-colors/src/range.ts
=> fix: correct range function behavior

packages/fast-jest-snapshots-react/README.md, packages/fast-jest-snapshots-react/package.json, packages/fast-jest-snapshots-react/src/__snapshots__/index.spec.tsx.snap, packages/fast-jest-snapshots-react/src/index.spec.tsx, packages/fast-jest-snapshots-react/src/index.ts
=> feat: support test-case descriptions

packages/fast-browser-extensions/package.json, packages/fast-components-react-base/package.json, packages/fast-components-react-msft/package.json, packages/fast-css-editor-react/package.json, packages/fast-development-site-react/package.json, packages/fast-form-generator-react/package.json, packages/fast-layouts-react/package.json, packages/fast-sketch-library/package.json, packages/fast-viewer-react/package.json
=> chore: update webpack-cli

packages/fast-components-react-base/src/checkbox/__snapshots__/checkbox.spec.tsx.snap, packages/fast-components-react-base/src/checkbox/checkbox.tsx
Closes [#948](https://github.com/Microsoft/fast-dna/issues/948)
<body>
<footer>
=> fix: update checkbox to render label DOM only when label text exists

packages/fast-components-react-base/src/image/image.tsx
=> fix: implement slot utility into image

packages/fast-components-styles-msft/src/index.ts
=> fix: export elevation from root of msft styles package

README.md
Makes the first sentence easier to understand and consistent with the description of FAST-DNA in other places, such as https://opensource.microsoft.com/tags/typescript .
=> chore: update grammar in root readme

packages/fast-components-react-msft/app/app.tsx
Sort examples prior adding them to menu
fixes #852
=> chore: sort examples before adding them to menu

packages/fast-components-react-base/src/tabs/tab-panel.props.ts, packages/fast-components-react-base/src/tabs/tab-panel.tsx, packages/fast-components-react-base/src/tabs/tab.props.ts, packages/fast-components-react-base/src/tabs/tab.tsx, packages/fast-components-react-base/src/tabs/tabs.tsx
=> fix: explicitly apply an additional active prop to Tab and TabPanel via the Tabs component instead of using unhandledProps

packages/fast-components-class-name-contracts-base/src/managed-classes.ts, packages/fast-components-class-name-contracts-msft/src/progress/index.ts, packages/fast-components-react-base/src/tabs/examples.data.tsx, packages/fast-development-site-react/src/components/site/index.tsx, packages/fast-development-site-react/src/components/site/menu.tsx, packages/fast-form-generator-react/src/class-name-contracts/form-item.array.class-name-contract.ts, packages/fast-form-generator-react/src/class-name-contracts/form-item.children.class-name-contract.ts, packages/fast-jss-manager/src/index.ts, packages/fast-layouts-react/src/container/container.tsx, packages/fast-layouts-react/src/page/page.tsx
=> fix: allow nested at rules in styles without needing to define it in the class name contract

packages/fast-components-class-name-contracts-base/src/managed-classes.ts
=> fix: removes index type from ManagedClasses

packages/fast-components-react-msft/src/call-to-action/__snapshots__/call-to-action.spec.tsx.snap, packages/fast-components-react-msft/src/dialog/__snapshots__/dialog.spec.ts.snap, packages/fast-components-react-msft/src/divider/__snapshots__/divider.spec.ts.snap, packages/fast-components-react-msft/src/flipper/__snapshots__/flipper.spec.tsx.snap, packages/fast-components-react-msft/src/metatext/__snapshots__/metatext.spec.tsx.snap, packages/fast-components-react-msft/src/progress/__snapshots__/progress.spec.tsx.snap, packages/fast-components-react-msft/src/text-field/__snapshots__/text-field.spec.ts.snap, packages/fast-components-react-msft/src/toggle/__snapshots__/toggle.spec.ts.snap, packages/fast-jss-manager-react/src/jss-manager.tsx
=> fix: reintroduce componentDidMount in JSS manager to address incidental regressions

build/testing/applitools/run-msft-docs.js, packages/fast-components-class-name-contracts-base/README.md, packages/fast-development-site-react/README.md, packages/fast-web-utilities/README.md, packages/fast-web-utilities/src/html.spec.ts, packages/fast-web-utilities/src/numbers.spec.ts, packages/fast-web-utilities/src/strings.spec.ts
Fixes some typos in documentation and test output.
=> chore: fix typos in documentation and test output

packages/fast-application-utilities/.npmignore, packages/fast-browser-extensions/.npmignore, packages/fast-components-class-name-contracts-base/.npmignore, packages/fast-components-class-name-contracts-msft/.npmignore, packages/fast-components-react-base/.npmignore, packages/fast-components-react-msft/.npmignore, packages/fast-components-styles-msft/.npmignore, packages/fast-css-editor-react/.npmignore, packages/fast-development-site-react/.npmignore, packages/fast-form-generator-react/.npmignore, packages/fast-jss-manager-angular/.npmignore, packages/fast-jss-manager-react/.npmignore, packages/fast-jss-manager/.npmignore, packages/fast-jss-utilities/.npmignore, packages/fast-layouts-react/.npmignore, packages/fast-sketch-library/.npmignore, packages/fast-viewer-react/.npmignore
=> chore: update .npmignore files across monorepo

README.md
=> chore: add prettier badge to readme

packages/fast-components-react-msft/src/call-to-action/__snapshots__/call-to-action.spec.tsx.snap, packages/fast-components-react-msft/src/call-to-action/examples.data.tsx, packages/fast-components-styles-msft/src/call-to-action/index.ts
=> fix: remove external margin, padding, and fix RTL micro-interaction on MSFT call to action

packages/fast-development-site-react/src/utilities/error-boundary.tsx
=> fix: correct error boundary relative path mistake

packages/fast-form-generator-react/.npmignore
=> chore: ignore www file from fast-form-generatore package

packages/fast-jss-manager-react/src/jss-manager.spec.tsx, packages/fast-jss-manager-react/src/jss-manager.tsx
=> fix: correct jssStyleSheet style element ordering

packages/fast-viewer-react/src/rotate/rotate.tsx, packages/fast-viewer-react/src/select-device/select-device.tsx, packages/fast-viewer-react/src/viewer-content/viewer-content.tsx, packages/fast-viewer-react/src/viewer/viewer.tsx
=> fix: address an issue where @types/react was referenced but not found

packages/fast-components-styles-msft/src/design-system/index.ts
=> chore: update MSFT foreground color from #000 to #111

build/convert-readme.js, packages/fast-components-react-base/src/button/README.md, packages/fast-development-site-react/app/app.tsx, packages/fast-development-site-react/app/components/button/button.tsx, packages/fast-development-site-react/app/components/button/index.ts, packages/fast-development-site-react/app/components/index.ts, packages/fast-development-site-react/app/components/paragraph/index.ts, packages/fast-development-site-react/app/components/span/index.ts, packages/fast-development-site-react/app/components/span/span.schema.json, packages/fast-development-site-react/app/components/span/span.tsx, packages/fast-development-site-react/src/components/site/category-documentation.tsx
Closes [#617](https://github.com/Microsoft/fast-dna/issues/617)
<body>
<footer>
=> feat: add default message when no documentation is provided in development site

packages/fast-components-react-base/src/context-menu-item/context-menu-item.props.ts, packages/fast-components-react-base/src/context-menu-item/context-menu-item.spec.tsx, packages/fast-components-react-base/src/context-menu-item/examples.data.tsx, packages/fast-components-react-base/src/context-menu/README.md, packages/fast-components-react-base/src/context-menu/context-menu.tsx, packages/fast-components-react-base/src/context-menu/examples.data.tsx, packages/fast-components-react-msft/package.json, packages/fast-components-react-msft/webpack.config.js
Closes [#1122](https://github.com/Microsoft/fast-dna/issues/1122)
<body>
<footer>
=> chore: formats spelling of context menu and context menu item to be consistent across documentation and code commenting

packages/fast-development-site-react/src/components/site/index.tsx
=> fix: add a check for a theme, if it is not available use an empty object

packages/fast-form-generator-react/app/components/align-horizontal/__snapshots__/align-horizontal.spec.tsx.snap, packages/fast-form-generator-react/app/components/align-vertical/__snapshots__/align-vertical.spec.tsx.snap, packages/fast-form-generator-react/app/components/any-of/__snapshots__/any-of.spec.tsx.snap, packages/fast-form-generator-react/app/components/attribute-assignment/__snapshots__/attribute-assignment.spec.tsx.snap, packages/fast-form-generator-react/app/components/checkbox/__snapshots__/checkbox.spec.tsx.snap, packages/fast-form-generator-react/app/components/number-field/__snapshots__/number-field.spec.tsx.snap, packages/fast-form-generator-react/app/components/objects/__snapshots__/objects.spec.tsx.snap, packages/fast-form-generator-react/app/components/one-of/__snapshots__/one-of.spec.tsx.snap, packages/fast-form-generator-react/app/components/text-field/__snapshots__/text-field.spec.tsx.snap, packages/fast-form-generator-react/app/components/theme/__snapshots__/theme.spec.tsx.snap, packages/fast-form-generator-react/app/components/weight-properties/__snapshots__/weight-properties.spec.tsx.snap, packages/fast-jss-manager-react/src/jss-manager.spec.tsx, packages/fast-jss-manager-react/src/jss-manager.tsx
=> fix: JSSManager should create stylesheets prior to initial render

packages/fast-jss-manager-react/src/jss.ts
=> fix: explicitly define JSS types in the JSS manager

packages/fast-css-editor-react/app/app.tsx, packages/fast-css-editor-react/src/editor.props.ts, packages/fast-css-editor-react/src/editor.schema.json, packages/fast-css-editor-react/src/editor.spec.tsx, packages/fast-css-editor-react/src/editor.tsx, packages/fast-css-editor-react/src/spacing/README.md, packages/fast-css-editor-react/src/spacing/index.ts, packages/fast-css-editor-react/src/spacing/spacing.props.ts, packages/fast-css-editor-react/src/spacing/spacing.schema.json, packages/fast-css-editor-react/src/spacing/spacing.spec.tsx, packages/fast-css-editor-react/src/spacing/spacing.style.ts, packages/fast-css-editor-react/src/spacing/spacing.tsx
=> feat: add CSS spacing component

packages/fast-components-styles-msft/src/index.ts
=> feat: ensure all utilities are exported in the package distribution

packages/fast-components-styles-msft/src/context-menu-item/index.ts
=> fix: replace deprecated applyType function in context menu item with applyTypeRampConfig

packages/fast-components-react-base/src/button/button.tsx, packages/fast-components-react-base/src/card/card.tsx, packages/fast-components-react-base/src/label/label.tsx, packages/fast-components-react-base/src/typography/typography.tsx, packages/fast-components-react-msft/webpack.config.js, packages/fast-layouts-react/src/grid/grid.tsx, packages/fast-viewer-react/webpack.config.js
=> fix: updating typings to fix errors caused by @types/react update

packages/fast-components-react-msft/.npmignore, packages/fast-css-editor-react/.npmignore, packages/fast-viewer-react/.npmignore
=> fix: add www directory to npmignore where it is missing

packages/fast-components-styles-msft/src/checkbox/index.ts
=> fix: add missing position value to root node of checkbox

packages/fast-components-react-msft/webpack.config.js
Splits out vendor bundle
Remove source-maps in prod
=> chore: performance improvments for webpack

packages/fast-components-react-base/src/context-menu-item/context-menu-item.props.ts, packages/fast-components-react-base/src/context-menu-item/context-menu-item.spec.tsx, packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx
=> fix: handle context menu item keydown and click events

packages/fast-components-styles-msft/src/button/index.ts
=> fix font family inheritance issue due to user agent definition in certain browsers

packages/fast-components-react-base/src/button/button.spec.tsx, packages/fast-components-react-base/src/button/button.tsx, packages/fast-components-react-base/src/checkbox/checkbox.spec.tsx, packages/fast-components-react-base/src/checkbox/checkbox.tsx, packages/fast-components-react-base/src/context-menu-item/context-menu-item.spec.tsx, packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx, packages/fast-components-react-base/src/horizontal-overflow/resize-observer.ts, packages/fast-components-react-base/src/image/image.spec.tsx, packages/fast-components-react-base/src/image/image.tsx, packages/fast-components-react-base/src/label/label.spec.tsx, packages/fast-components-react-base/src/label/label.tsx, packages/fast-components-react-base/src/radio/radio.spec.tsx, packages/fast-components-react-base/src/radio/radio.tsx, packages/fast-components-react-base/src/tabs/tab-panel.spec.tsx, packages/fast-components-react-base/src/tabs/tab-panel.tsx, packages/fast-components-react-base/src/tabs/tab.spec.tsx, packages/fast-components-react-base/src/tabs/tab.tsx, packages/fast-components-react-base/src/typography/typography.spec.tsx, packages/fast-components-react-base/src/typography/typography.tsx, packages/fast-components-react-msft/src/action-trigger/action-trigger.tsx, packages/fast-components-react-msft/src/call-to-action/call-to-action.tsx, packages/fast-components-react-msft/src/caption/caption.tsx, packages/fast-components-react-msft/src/flipper/flipper.tsx, packages/fast-components-react-msft/src/heading/heading.tsx, packages/fast-components-react-msft/src/paragraph/paragraph.tsx, packages/fast-components-react-msft/src/subheading/subheading.tsx
=> fix: update components to handle undefined className

packages/fast-components-class-name-contracts-msft/src/progress/index.ts, packages/fast-components-react-msft/src/progress/README.md, packages/fast-components-react-msft/src/progress/progress.tsx, packages/fast-components-styles-msft/src/progress/index.ts
This PR updates the style of the horizontal progress. We will add the circular style at a later time.
Partial fix for: #1130
=> fix (progress): to include updated indeterminate animation

.github/pull_request_template.md
Chore to add "-" before the checkbox '[]' syntax.
Checkboxes now render properly in preview.
[x] **Chore**: A change that does not impact distributed packages.
[ ] **Bug fix**: A change that fixes an issue, link to the issue above.
[ ] **New feature**: A change that adds functionality.
[ ] This change causes current functionality to break.
[ ] I have added tests for my changes.
[x] I have tested my changes.
[x] I have updated the project documentation to reflect my changes.
[x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://microsoft.github.io/fast-dna/docs/en/contributing/standards) for this project.
=> chore: added the dashes back in so markdown checkboxes will render

packages/fast-browser-extensions/README.md
Fix for formatting and minor updates to copy.
Create more consistency and quality.
[x] **Chore**: A change that does not impact distributed packages.
[ ] **Bug fix**: A change that fixes an issue, link to the issue above.
[ ] **New feature**: A change that adds functionality.
[ ] This change causes current functionality to break.
[ ] I have added tests for my changes.
[x] I have tested my changes.
[x] I have updated the project documentation to reflect my changes.
[x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://microsoft.github.io/fast-dna/docs/en/contributing/standards) for this project.
=> chore: update fast-browser-extensions readme

packages/fast-breakpoint-tracker-react/README.md
Made minor formatting and copy changes to the breakpoint tracker readme.
Improved quality and accuracy.
=> chore: update fast breakpoint tracker readme

packages/fast-application-utilities/README.md
Fixed some formatting and added code fence languages.
Improving quality.
=> chore: update fast-application-utilities readme

packages/fast-animation/README.md
Updated markdown formatting and minor edits to grammar, sentence structure, and punctuation.
Click here for details on [formatting pull requests](https://microsoft.github.io/fast-dna/docs/contributing/working#formatting-messages).
=> chore: update content on fast-animation readme

packages/fast-browser-extensions/src/extension/manifest.ts, packages/fast-permutator/package.json
Author name was incorrectly stating Fluent Web and it should be Microsoft.
Improve accuracy of package.json files.
=> chore: update to fix incorrect author name

docs/en/contributing/install.md, docs/en/contributing/packages.md, docs/en/contributing/policies.md, docs/en/contributing/standards.md, docs/en/contributing/testing.md, docs/en/contributing/working.md, docs/en/contributing/writing-style-guide.md, docs/en/packages/fast-animation.md, website/i18n/en.json, website/sidebars.json, website/static/css/custom.css
Updated the FAST Animation README and added a version of it to the doc site. The md file is currently duplicate pending an automation task to impart package markdown files to the doc site. A writing style guide was also added to the doc site. Some style changes were made to fix styling issues that were exposed with the new documents. Fixed a bug that slipped through previously where mobile menus were not themed properly making them unreadable.
The FAST Animation README was updated to follow the latest guidance for contributing packages. As part of that effort, a Writing style guide was created to outline our writing best practices to drive more consistent writing across the project.
=> chore: update fast animation readme and add writing style guide docs

packages/fast-development-site-react/src/components/site/configuration-panel.tsx
fixed clipping issue in config panel
Closes #1263 
Before:
After:
=> fix: clipping issue in config panel

packages/fast-components-class-name-contracts-base/src/index.ts, packages/fast-components-class-name-contracts-base/src/text-area/index.ts, packages/fast-components-react-base/app/examples.ts, packages/fast-components-react-base/src/index.ts, packages/fast-components-react-base/src/text-area/README.md, packages/fast-components-react-base/src/text-area/examples.data.tsx, packages/fast-components-react-base/src/text-area/index.ts, packages/fast-components-react-base/src/text-area/text-area.props.ts, packages/fast-components-react-base/src/text-area/text-area.schema.json, packages/fast-components-react-base/src/text-area/text-area.spec.tsx, packages/fast-components-react-base/src/text-area/text-area.tsx, packages/fast-components-react-msft/app/examples.ts, packages/fast-components-react-msft/src/index.ts, packages/fast-components-react-msft/src/text-area/README.md, packages/fast-components-react-msft/src/text-area/examples.data.tsx, packages/fast-components-react-msft/src/text-area/index.ts, packages/fast-components-styles-msft/src/index.ts, packages/fast-components-styles-msft/src/text-area/index.ts, packages/fast-components-styles-msft/src/text-field/index.ts
=> feat: add text area as a new component

packages/fast-components-styles-msft/src/card/index.ts, packages/fast-components-styles-msft/src/dialog/index.ts
=> feat: add rounded corners to MSFT card and dialog components

website/static/css/custom.css
Chore to fix for several CSS issues on the doc site. 
Anchors now show up the proper color. Buttons on splash no longer get pink underline. Mobile menus no longer show content from behind the menus on mobile.
=> chore: update several css styles for anchors and mobile menus

packages/fast-components-react-base/src/context-menu-item/context-menu-item.spec.tsx, packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx
`onClick` and `onKeyDown` unhandled props were being clobbered by props applied internally by the `ContextMenuItem`, which caused these event handlers to never get called. This PR ensures those unhandled prop callbacks work as epxcted
fixes #1260
=> fix: ensure onClick and onKeyDown unhandledProps on ContextMenuItem are triggered as expected

packages/fast-components-react-msft/src/action-toggle/README.md
Fixed capitalization on action toggle readme and made minor updates to the description.
=> chore: fixed capitalization on action toggle readme and minor edits

docs/en/contributing/install.md, docs/readme.md
Added npm as prerequisite to install.md
We have had feedback from two people now that they missed installing npm first. This should help avoid that misstep. 
=> chore: add prerequisites to install markdown

packages/fast-components-styles-msft/src/design-system/index.ts, packages/fast-jss-utilities/README.md, packages/fast-jss-utilities/src/index.ts, packages/fast-jss-utilities/src/with-defaults.spec.ts, packages/fast-jss-utilities/src/with-defaults.ts
=> feat: add generic function for deep merging two objects for use with design system defaults

packages/fast-components-styles-msft/src/text-action/index.ts
=> fix: update text action height to be 32 total pixels

packages/fast-data-utilities-react/src/__tests__/plugins/map-children-prop-to-callback-passing-class-name.tsx, packages/fast-data-utilities-react/src/index.spec.ts, packages/fast-data-utilities-react/src/index.ts
Fix an issue where children were not being properly identified before being passed to a plugin.
=> fix: update to use children ids from data when resolving data from a plugin

packages/fast-colors/README.md
Minor grammar and markdown linting fixes on README.md
Improved readability, less squiggly lines.
=> chore: update grammar to fix lint errors

packages/fast-development-site-react/app/app.tsx, packages/fast-development-site-react/app/components/paragraph/paragraph.schema.json, packages/fast-development-site-react/app/plugins/text-plugin.ts, packages/fast-development-site-react/package.json, packages/fast-development-site-react/src/components/site/index.tsx
Adds plugins and updates examples to the component library packages to allow the form generator in the development site the ability to edit properties on functional code.
This allows the use of react render props by passing in optional plugins to replace the default behavior of the mapDataToComponent function.
=> feat: add form plugin option to development site

packages/fast-form-generator-react/src/form/form-item.array.style.ts, packages/fast-form-generator-react/src/form/form-item.children.style.ts
Form array items and form children items didn't seem actionable. Added hover state to form array items and form children items and updated cursor.
Form array items and form children items didn't seem actionable. 
=> fix: added hover state and updated cursor on form array & form children

packages/fast-components-styles-msft/src/utilities/breakpoints.ts, packages/fast-components-styles-msft/src/utilities/typography.ts
=> feat: deprecate breakpoint interface, breakpoint values, and applyBreakpoint function

packages/fast-development-site-react/src/components/site/component-view-toggle.tsx
Remove margin from component view toggle so button does not bleed into component preview area
Before:
After:
Removed margin
fix visually broken component 
=> fix: Margin should be removed on component view toggle

packages/fast-development-site-react/src/components/site/configuration-panel.tsx
when scrollbar become visible it was pushing the content of the config panel. Set the `overflowY` to `scroll` to always leave room for scrollbar
Prevent content from sifting when scrollbar becomes visible.
=> fix: prevent scroll bar from pushing content in config panel

packages/fast-viewer-react/package.json
* Update webpack related packages to newer versions
This solves the security vulnerability of using Webpack < 3.1.11.  https://nvd.nist.gov/vuln/detail/CVE-2018-14732
=> chore: update fast-viewer-react with security patch

packages/fast-viewer-react/package.json, packages/fast-viewer-react/webpack.config.js
* Updates Webpack for better consistency 
* Update Webpack for optimizations using mode
Improved performance and maintainability
=> chore: update fast-viewer-react with webpack optimizations

packages/fast-form-generator-react/app/index.tsx, packages/fast-form-generator-react/src/class-name-contracts/form-item.array.class-name-contract.ts, packages/fast-form-generator-react/src/class-name-contracts/form-item.children.class-name-contract.ts, packages/fast-form-generator-react/src/form/form-category.style.ts, packages/fast-form-generator-react/src/form/form-item.align-horizontal.style.ts, packages/fast-form-generator-react/src/form/form-item.align-vertical.style.ts, packages/fast-form-generator-react/src/form/form-item.array.spec.tsx, packages/fast-form-generator-react/src/form/form-item.array.style.ts, packages/fast-form-generator-react/src/form/form-item.array.tsx, packages/fast-form-generator-react/src/form/form-item.checkbox.style.ts, packages/fast-form-generator-react/src/form/form-item.children.style.ts, packages/fast-form-generator-react/src/form/form-item.children.tsx, packages/fast-form-generator-react/src/form/form-item.number-field.style.ts, packages/fast-form-generator-react/src/form/form-item.section-link.style.ts, packages/fast-form-generator-react/src/form/form-item.select.style.ts, packages/fast-form-generator-react/src/form/form-item.select.tsx, packages/fast-form-generator-react/src/form/form-item.textarea.style.ts, packages/fast-form-generator-react/src/form/form-item.theme.style.ts, packages/fast-form-generator-react/src/form/form-section.style.ts, packages/fast-form-generator-react/src/form/form.constants.style.ts, packages/fast-form-generator-react/src/form/form.style.ts, packages/fast-form-generator-react/src/form/form.utilities.style.ts, packages/fast-form-generator-react/src/index.ts, packages/fast-form-generator-react/src/utilities/index.ts
This was a refactor that somehow was not cherry picked correctly from a branch @janechu had for my large dark theme overhaul. 
Organizes fast form project better
=> fix: remove utilities folder refactor

packages/fast-application-utilities/README.md, packages/fast-application-utilities/src/localization.ts
=> feat: deprecate fast-application-utilities package

packages/fast-components-class-name-contracts-base/src/tabs/index.ts, packages/fast-components-react-base/src/tabs/examples.data.tsx, packages/fast-components-react-base/src/tabs/tabs.tsx
Closes [#1344](https://github.com/Microsoft/fast-dna/issues/1344)
Fixes issue in `Tabs` where class names for `Tab` and `TabPanel` were not correctly assigned.
Was unable to use `Tabs` in `Carousel` correctly.
=> fix: child component class name assignment in tabs

packages/fast-css-editor-react/app/README.md, packages/fast-css-editor-react/app/app.tsx, packages/fast-css-editor-react/app/exports.constants.ts, packages/fast-css-editor-react/webpack.config.js
Removal of the dependency on the `fast-development-site-react` package and use the exported components on an HTML Element.
This allows more meaningful testing of the CSS editors components.
=> chore: update the testing application UI

packages/fast-components-react-msft/src/action-toggle/action-toggle.tsx
=> fix: pass action toggle glyph to beforeContent to ensure that underline on hover only impacts the text

packages/fast-viewer-react/src/viewer-content/viewer-content.base.tsx
=> fix: remove duplicate export of viewer content base component

packages/fast-css-editor-react/src/editor.constants.style.ts, packages/fast-css-editor-react/src/editor.utilities.style.ts, packages/fast-css-editor-react/src/position/position.props.ts, packages/fast-css-editor-react/src/position/position.style.ts, packages/fast-css-editor-react/src/position/position.tsx, packages/fast-css-editor-react/src/spacing/spacing.style.ts, packages/fast-css-editor-react/src/spacing/spacing.tsx
Updates to the CSS editor components to match the new `fast-form-generator-react` package styling.
The tooling must match, therefore this package has been updated to reflect the new styling direction.
=> feat: update styling to match the FAST form generator

packages/fast-navigation-generator-react/.npmignore, packages/fast-navigation-generator-react/.npmrc, packages/fast-navigation-generator-react/.prettierignore, packages/fast-navigation-generator-react/README.md, packages/fast-navigation-generator-react/app/app.tsx, packages/fast-navigation-generator-react/app/configs/children.schema.json, packages/fast-navigation-generator-react/app/configs/example.data.ts, packages/fast-navigation-generator-react/app/configs/no-children.schema.json, packages/fast-navigation-generator-react/app/index.tsx, packages/fast-navigation-generator-react/babel.config.js, packages/fast-navigation-generator-react/package.json, packages/fast-navigation-generator-react/src/index.ts, packages/fast-navigation-generator-react/src/navigation/index.ts, packages/fast-navigation-generator-react/src/navigation/navigation.constants.style.ts, packages/fast-navigation-generator-react/src/navigation/navigation.props.ts, packages/fast-navigation-generator-react/src/navigation/navigation.spec.tsx, packages/fast-navigation-generator-react/src/navigation/navigation.style.ts, packages/fast-navigation-generator-react/src/navigation/navigation.tsx, packages/fast-navigation-generator-react/src/navigation/navigation.utilities.spec.ts, packages/fast-navigation-generator-react/src/navigation/navigation.utilities.style.ts, packages/fast-navigation-generator-react/src/navigation/navigation.utilities.ts, packages/fast-navigation-generator-react/tsconfig.json, packages/fast-navigation-generator-react/tslint.json, packages/fast-navigation-generator-react/typings.d.ts, packages/fast-navigation-generator-react/webpack.config.js
This is to add the `@microsoft/fast-navigation-generator-react` package which will work in conjunction with the `@microsoft/fast-form-generator-react` package.
To further enhance tooling this package is being added to work with the other tooling packages that are already available. This should allow anyone to create an extensible application for editing/navigating/prototyping via a generated React UI.
Closes #1354 
=> feat: add a navigation tool to work with the form generator

packages/fast-data-utilities-react/src/__tests__/schemas/children-plugin.schema.json, packages/fast-data-utilities-react/src/index.spec.ts, packages/fast-data-utilities-react/src/index.ts
This adds a missing normalizer wrapper for a data location so that it can match plugins inside of arrays.
=> fix: add missing check for array syntax when resolving paths to plugin IDs

packages/fast-data-utilities-react/src/index.spec.ts, packages/fast-data-utilities-react/src/index.ts
An additional fix for normalizing the paths created for array items when they are not nested.
=> fix: add additional check on array normalization when items are not nested

packages/fast-animation/package.json, packages/fast-application-utilities/package.json, packages/fast-breakpoint-tracker-react/package.json, packages/fast-colors/package.json, packages/fast-components-foundation-react/package.json, packages/fast-components-react-base/package.json, packages/fast-components-react-base/webpack.config.js, packages/fast-components-react-msft/package.json, packages/fast-css-editor-react/package.json, packages/fast-css-editor-react/webpack.config.js, packages/fast-data-utilities-react/package.json, packages/fast-development-site-react/package.json, packages/fast-form-generator-react/package.json, packages/fast-jss-manager-angular/package.json, packages/fast-jss-manager-react/package.json, packages/fast-jss-utilities/package.json, packages/fast-layouts-react/package.json, packages/fast-markdown-msft-react/package.json, packages/fast-navigation-generator-react/package.json, packages/fast-permutator/package.json, packages/fast-viewer-react/src/viewer/viewer.base.spec.tsx, packages/fast-viewer-react/webpack.config.js, packages/fast-web-utilities/package.json
A fix for a build break occurring in a test file.
=> chore: fix a build break in a test file

package.json, packages/fast-components-react-msft/package.json
png-async is a dependency of eyes.util.  eye.util is a dependency of eyes.selenium and eyes.images.  Png-async was breaking on windows operating system upstream because it included a 'nul' file name.
Fix the issue so that Windows build agents will run again.
=> fix: update package versions to fix png-async nul file

packages/fast-components-class-name-contracts-msft/src/carousel/index.ts, packages/fast-components-class-name-contracts-msft/src/index.ts, packages/fast-components-react-base/src/tabs/tabs.tsx, packages/fast-components-react-msft/app/app.tsx, packages/fast-components-react-msft/app/components/carousel-dark-image-content-child-options.tsx, packages/fast-components-react-msft/app/components/carousel-dark-image-content.schema.json, packages/fast-components-react-msft/app/components/carousel-dark-image-content.tsx, packages/fast-components-react-msft/app/components/carousel-hero-content-child-options.tsx, packages/fast-components-react-msft/app/components/carousel-hero-content.schema.json, packages/fast-components-react-msft/app/components/carousel-hero-content.tsx, packages/fast-components-react-msft/app/components/carousel-light-image-content-child-options.tsx, packages/fast-components-react-msft/app/components/carousel-light-image-content.schema.json, packages/fast-components-react-msft/app/components/carousel-light-image-content.tsx, packages/fast-components-react-msft/app/examples.ts, packages/fast-components-react-msft/src/carousel/README.md, packages/fast-components-react-msft/src/carousel/carousel.props.ts, packages/fast-components-react-msft/src/carousel/carousel.schema.json, packages/fast-components-react-msft/src/carousel/carousel.spec.tsx, packages/fast-components-react-msft/src/carousel/carousel.tsx, packages/fast-components-react-msft/src/carousel/examples.data.tsx, packages/fast-components-react-msft/src/carousel/index.ts, packages/fast-components-react-msft/src/index.ts, packages/fast-components-styles-msft/src/carousel/index.ts, packages/fast-components-styles-msft/src/index.ts
Closes [#1128](https://github.com/Microsoft/fast-dna/issues/1128)
** This is an initial PR - many changes will come with the review. Please pull down. A style guide for the sequence indicators does not exist as of yet.
Adds the basic MSFT carousel:
- uses `<Tabs />`
- cycles to the appropriate tab on arrowing left or right
- cycles to the appropriate tab by clicking a sequence indicator
- cycles to next or previous slide on `<Flipper /> click
- no autoplay
- flippers are always visible (but not to screen readers)
- no transitions or animation
=> feat: add carousel as a MSFT component

packages/fast-components-class-name-contracts-base/src/badge/index.ts, packages/fast-components-class-name-contracts-base/src/index.ts, packages/fast-components-class-name-contracts-msft/src/badge/index.ts, packages/fast-components-class-name-contracts-msft/src/index.ts, packages/fast-components-react-base/app/examples.ts, packages/fast-components-react-base/src/badge/README.md, packages/fast-components-react-base/src/badge/badge.props.ts, packages/fast-components-react-base/src/badge/badge.schema.json, packages/fast-components-react-base/src/badge/badge.spec.tsx, packages/fast-components-react-base/src/badge/badge.tsx, packages/fast-components-react-base/src/badge/examples.data.tsx, packages/fast-components-react-base/src/badge/index.ts, packages/fast-components-react-base/src/index.ts, packages/fast-components-react-msft/app/examples.ts, packages/fast-components-react-msft/src/badge/README.md, packages/fast-components-react-msft/src/badge/badge.props.ts, packages/fast-components-react-msft/src/badge/badge.schema.json, packages/fast-components-react-msft/src/badge/badge.spec.tsx, packages/fast-components-react-msft/src/badge/badge.tsx, packages/fast-components-react-msft/src/badge/examples.data.tsx, packages/fast-components-react-msft/src/badge/index.ts, packages/fast-components-react-msft/src/index.ts, packages/fast-components-styles-msft/src/badge/index.ts, packages/fast-components-styles-msft/src/index.ts
Closes [#1278](https://github.com/Microsoft/fast-dna/pull/1278)
Adds the badge component.
Provides the badge component to users.
=> feat: add badge as an MSFT component

packages/fast-components-styles-msft/src/card/index.ts, packages/fast-components-styles-msft/src/dialog/index.ts
=> fix: card and dialog shadows should always be black regardless of theme

packages/fast-jss-utilities/README.md
=> chore: focus visible polyfill documentation had misspelled word due to missing space

packages/fast-form-generator-react/README.md, packages/fast-form-generator-react/app/index.tsx, packages/fast-form-generator-react/src/form/form-category.tsx, packages/fast-form-generator-react/src/form/form-control.props.ts, packages/fast-form-generator-react/src/form/form-control.tsx, packages/fast-form-generator-react/src/form/form-item.align-horizontal.tsx, packages/fast-form-generator-react/src/form/form-item.align-vertical.tsx, packages/fast-form-generator-react/src/form/form-item.array.tsx, packages/fast-form-generator-react/src/form/form-item.children.tsx, packages/fast-form-generator-react/src/form/form-item.file-upload.tsx, packages/fast-form-generator-react/src/form/form-item.mapping.tsx, packages/fast-form-generator-react/src/form/form-item.select.spec.tsx, packages/fast-form-generator-react/src/form/form-item.select.tsx, packages/fast-form-generator-react/src/form/form-item.theme.tsx, packages/fast-form-generator-react/src/form/form-section.props.ts, packages/fast-form-generator-react/src/form/form-section.tsx, packages/fast-form-generator-react/src/form/form.props.ts, packages/fast-form-generator-react/src/form/form.spec.tsx, packages/fast-form-generator-react/src/form/form.tsx, packages/fast-form-generator-react/src/form/form.utilities.ts
This allows the location (lodash path syntax) in the `fast-form-generator-react` to be controlled.
The feature for allowing the user to control the location is now fully implemented with this change. This means that should a user wish to tie in other tooling that relies on location (eg. `fast-navigation-generator-react`) it will be able to sync locations between these tooling components.
=> feat: add a controlled location state

build/testing/applitools/run-msft-docs.js, build/testing/sauce-labs/test-browsers.js, website/i18n/en.json, website/pages/en/index.js, website/siteConfig.js
Update to fix broken links
This will be merged after the new links are up and running pending approval on https://explore-stage.fastdna.net 
resolves #1379 
=> fix: update broken links after migrated msft-docs to explore

packages/fast-navigation-generator-react/README.md, packages/fast-navigation-generator-react/src/navigation/navigation.props.ts, packages/fast-navigation-generator-react/src/navigation/navigation.spec.tsx, packages/fast-navigation-generator-react/src/navigation/navigation.tsx
Adds an optional `dataLocation` prop to be used in conjunction with the `onLocationUpdate` callback to fully control the component.
This completes the controlled story for the Navigation component which allows the user to fully update the state of the navigation from a single prop.
=> feat: add the ability to control the navigation via props

packages/fast-navigation-generator-react/src/navigation/navigation.utilities.spec.ts, packages/fast-navigation-generator-react/src/navigation/navigation.utilities.ts
Matches the React children dataLocations created by the form generator by adding the "props" keyword.
This resolves an issue where the Navigation and Form generator created different data locations.
=> fix: matches dataLocations from the form generator by including the keyword 'props'

packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-outline.ts
updating swatch deltas to match evolved design guidance.
=> feat: update neutral-outline and neutral-stealth offsets

.azure-devops/explore.config.yml
This will allow us to create a new pipeline on Azure DevOps for building and releasing the Component Explorer located at https://explore-stage.fastdna.net
Improve performance and organization of pipeline for component explorer website.
=> chore: add azure devops pipeline for building and deploying explorer

packages/fast-css-editor-react/package.json
Fixes a circular dependency when attempting to use the css editor in the dev site.
=> chore: update to resolve a circular dependency issue

packages/fast-development-site-react/app/app.tsx, packages/fast-development-site-react/app/components/button/button.tsx, packages/fast-development-site-react/package.json, packages/fast-development-site-react/src/components/site/configuration-panel.tsx, packages/fast-development-site-react/src/components/site/index.tsx
This is an update to the `fast-development-site-react` package to allow the application of CSS on child components.
In order to provide real world scenarios, this change will allow the formatting and adjusting of various CSS properties to be applied to components and their children.
=> feat: add a component navigation and css editor

packages/fast-components-react-base/app/index.tsx, packages/fast-components-react-msft/app/app.tsx
This adds the ability to modify children styles in the development site for the component packages.
=> chore: add the new styling prop to the dev site for the component packages

README.md, docs/en/contributing/status.md, website/i18n/en.json, website/sidebars.json
* add new status page and configuration
* update root readme to link to new status page
* update root readme to link to component explorer
Documentation improvements to new infrastructure.
=> chore: add documentation for system status

packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-outline.spec.ts
=> chore: fixing color unit tests

packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
This fixes an issue where partial pixels were calculated which meant that clicking a previous or next button could result in not being able to scroll to the end or beginning of the items in Horizontal Overflow.
Resolves #1378
=> fix: update to the Horizontal Overflow component to account for partial pixels when scrolling

packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.spec.tsx, packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
Adds a check to for the number of children so that if they increase the overflow callback is fired.
Resolves #1376
=> fix: update to the Horizontal Overflow component to fire the overflow callback when more children have been added

packages/fast-components-styles-msft/src/utilities/color/accent-fill.spec.ts, packages/fast-components-styles-msft/src/utilities/color/accent-fill.ts, packages/fast-components-styles-msft/src/utilities/color/common.ts, packages/fast-components-styles-msft/src/utilities/color/index.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill.ts
Adds a *selected* color to all fill recipes, allowing elements using those recipes to appear selected
=> feat: add selected color to all fill recipes 

packages/fast-css-editor-react/app/app.tsx, packages/fast-css-editor-react/app/index.tsx, packages/fast-css-editor-react/src/editor.style.ts, packages/fast-css-editor-react/src/position/position.style.ts, packages/fast-css-editor-react/src/spacing/spacing.style.ts, packages/fast-form-generator-react/app/index.tsx, packages/fast-form-generator-react/src/class-name-contracts/form.class-name-contract.ts, packages/fast-form-generator-react/src/form/form.style.ts, packages/fast-form-generator-react/src/form/form.tsx, packages/fast-navigation-generator-react/src/navigation/navigation.style.ts
Normalizes the styles on root level tooling components.
The components would show up incorrectly if they were added on white backgrounds, this gives them a default correct background matching the default theme.
=> fix: normalize colors and backgrounds across tooling packages

packages/fast-components-styles-msft/src/badge/index.ts
Adding a PR at the request of @Falkicon 
=> fix: update badge accent color to white as mitigation for contrast ratio issue

packages/fast-components-class-name-contracts-base/src/dialog/index.ts, packages/fast-components-react-base/src/dialog/dialog.tsx, packages/fast-components-styles-msft/src/dialog/index.ts
closes #1339 (not 99...)
I don't believe this is a breaking change as the API is not affected. It does add a new div wrapper and class name contract, but the styled component remains centered.
=> fix: add additional wrapper to dialog to prevent subpixel aliasing due to css transforms

packages/fast-components-styles-msft/src/utilities/color/index.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.ts
adds neutral fill input color recipe
=> feat: add neutral fill input recipe

packages/fast-css-editor-react/src/position/position.props.ts, packages/fast-css-editor-react/src/position/position.spec.tsx, packages/fast-css-editor-react/src/position/position.tsx
Added "relative" to position options in the `<Position />` component
Positioning an element relatively is a common scenario 
=> feat: add "relative" and "fixed" to the position options

packages/fast-jest-snapshots-react/package.json, packages/fast-jest-snapshots-react/src/index.spec.tsx, packages/fast-jest-snapshots-react/tsconfig.json
=> chore: adds test coverage to fast-jest-snapshots-react

packages/fast-components-class-name-contracts-msft/src/action-toggle/index.ts, packages/fast-components-react-msft/src/action-toggle/action-toggle.props.ts, packages/fast-components-react-msft/src/action-toggle/action-toggle.schema.json, packages/fast-components-react-msft/src/action-toggle/action-toggle.spec.tsx, packages/fast-components-react-msft/src/action-toggle/action-toggle.tsx, packages/fast-components-react-msft/src/action-toggle/examples.data.tsx
=> feat: update action toggle style to key off appearance prop rather than selected state

packages/fast-data-utilities-react/src/index.ts
This will export a useful function for generating all possible lodash path strings from a given object.
=> feat: add a function to generate lodash path locations from an object to the exports

packages/fast-components-react-msft/app/app.tsx, packages/fast-components-react-msft/src/toggle/examples.data.tsx
=> chore: fix incorrect toggle example data

packages/fast-components-class-name-contracts-msft/src/carousel/index.ts, packages/fast-components-react-msft/app/components/carousel-dark-image-content.schema.json, packages/fast-components-react-msft/app/components/carousel-dark-image-content.tsx, packages/fast-components-react-msft/app/components/carousel-hero-content.schema.json, packages/fast-components-react-msft/app/components/carousel-hero-content.tsx, packages/fast-components-react-msft/app/components/carousel-light-image-content.schema.json, packages/fast-components-react-msft/app/components/carousel-light-image-content.tsx, packages/fast-components-react-msft/src/carousel/README.md, packages/fast-components-react-msft/src/carousel/carousel.tsx, packages/fast-components-react-msft/src/carousel/examples.data.tsx, packages/fast-components-styles-msft/src/carousel/index.ts
Closes [#1410](https://github.com/Microsoft/fast-dna/issues/1410)
Update carousel in several places:
- new [design updates](https://www.figma.com/file/FnigSVQnGOXbEW8HQuEu1ZMo/UIS-%2F-Components-(light-theme)?node-id=0%3A1) (to sequence indicator and flippers) 
- adds form generator editor functionality for slide clontent (can now update test slide data)
- adds the functionality to add class names based on slide transition direction change
=> feat: update carousel functionality and design

packages/fast-components-styles-msft/src/dialog/index.ts
=> fix: update name in dialog so styles are actually applied

packages/fast-components-styles-msft/src/utilities/color/accent-fill.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-outline.ts, packages/fast-components-styles-msft/src/utilities/color/palette.spec.ts, packages/fast-components-styles-msft/src/utilities/color/palette.ts
Puts in safegaurds to make sure we are not accessing index of a palette that don't exist. 
=> fix: update to not return undefined when trying to return colors

README.md
The link to the component explorer was incorrect.
Was: https://explore.fast-dna.net/
Should be: https://explore.fastdna.net/
=> fix: update broken anchor href

packages/fast-navigation-generator-react/src/navigation/navigation.style.ts, packages/fast-navigation-generator-react/src/navigation/navigation.utilities.style.ts
A small style adjustment to make dropdowns align with non-dropdowns in a treeview.
This provides better visual UI for the navigation when there are dropdowns and non-dropdown items in a treeview on the same level.
=> fix: update alignment to be relative to letters and not the dropdown arrows

packages/fast-colors/src/colorlib/colorConverters.ts, packages/fast-colors/src/colorlib/parseColor.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground-cut.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground.spec.ts, packages/fast-components-styles-msft/src/utilities/color/common.spec.ts, packages/fast-components-styles-msft/src/utilities/color/common.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-outline.spec.ts, packages/fast-components-styles-msft/src/utilities/color/palette.spec.ts, packages/fast-components-styles-msft/src/utilities/color/palette.ts
=> feat: remove chroma from color utilities

packages/fast-components-react-msft/src/call-to-action/call-to-action.schema.json, packages/fast-components-react-msft/src/call-to-action/call-to-action.tsx, packages/fast-components-styles-msft/src/call-to-action/index.ts
Closes [#1454](https://github.com/Microsoft/fast-dna/issues/1454)
Fixes a few issues with the disabled CTA
- now shows up in editor
- now does not transform on hover
- removes href when disabled so it actually gets the `disabled` attribute is no longer actionable (before it was setting `aria-disabled` and was still actionable)
=> fix: update call to action to handle disabled state correctly

packages/fast-layouts-react/src/pane/pane.props.ts, packages/fast-layouts-react/src/pane/pane.tsx
=> feat: add prop to support setting initial width on Pane

packages/fast-form-generator-react/README.md, packages/fast-form-generator-react/app/configs/index.ts, packages/fast-form-generator-react/app/configs/plugin/plugin.schema.json, packages/fast-form-generator-react/app/configs/plugin/plugin.ts, packages/fast-form-generator-react/app/index.tsx, packages/fast-form-generator-react/src/form/form-control.props.ts, packages/fast-form-generator-react/src/form/form-item.children.tsx, packages/fast-form-generator-react/src/form/form-plugin.utilities.spec.ts, packages/fast-form-generator-react/src/form/form-plugin.utilities.ts, packages/fast-form-generator-react/src/form/form.props.ts, packages/fast-form-generator-react/src/form/form.spec.tsx, packages/fast-form-generator-react/src/form/form.tsx, packages/fast-form-generator-react/src/form/form.utilities.spec.ts, packages/fast-form-generator-react/src/form/form.utilities.ts, packages/fast-form-generator-react/src/index.ts, packages/fast-form-generator-react/src/plugin.ts
This adds a flexible plugin system to the form generator that will allow a user to update a schema or portion of a schema based on updates to the data.
This will allow more complicated interactions with the form, for example conditionally querying an external API if a data has been specified.
Resolves #1337
=> feat: add plugin system

packages/fast-components-styles-msft/src/carousel/index.ts
fix: const in carousel styles is missing closing )
=> fix: const in carousel styles is missing closing )

packages/fast-components-react-msft/src/button/button.tsx
=> chore: update to improve generate className function of MSFT button

packages/fast-components-react-msft/webpack.config.js
Updates title to reflect the actual intended title.
The title that displays on browser tab inaccurately described what the site is.  This is the "Component explorer".
=> chore: update website title

packages/fast-components-styles-msft/src/carousel/index.ts, packages/fast-components-styles-msft/src/flipper/index.ts
Add new color system to `<Carousel />` component. Also updated flipper to have a 80% opacity on the background element only. This is now the design for `<Flipper />` moving forward. 
Shown in these screenshots below:
=> feat: apply new color system to carousel

packages/fast-colors/README.md, packages/fast-colors/src/contrast.ts, packages/fast-colors/src/luminosity.ts, packages/fast-colors/src/range.ts, packages/fast-colors/src/rgb.ts
Adds deprecation warnings to all exported functions from `@microsoft/fast-colors`
Prepping library for version 4.0
=> feat: add deprecation warnings to fast-colors

packages/fast-components-react-msft/app/components/carousel-hero-content.tsx, packages/fast-components-react-msft/src/carousel/examples.data.tsx, packages/fast-components-styles-msft/src/carousel/index.ts
Closes [#1493](https://github.com/Microsoft/fast-dna/issues/1493)
Small updates to the carousel to fix a few bugs:
- fixes incorrect mapping in example data
- fixes incorrect JSS
- streamlines JSS
=> chore: update carousel example data to use correct JSS styles

packages/fast-components-react-msft/src/context-menu/examples.data.tsx, packages/fast-components-styles-msft/src/action-toggle/index.ts, packages/fast-components-styles-msft/src/action-trigger/index.ts, packages/fast-components-styles-msft/src/badge/index.ts, packages/fast-components-styles-msft/src/breadcrumb/index.ts, packages/fast-components-styles-msft/src/button/index.ts, packages/fast-components-styles-msft/src/call-to-action/index.ts, packages/fast-components-styles-msft/src/card/index.ts, packages/fast-components-styles-msft/src/checkbox/index.ts, packages/fast-components-styles-msft/src/context-menu-item/index.ts, packages/fast-components-styles-msft/src/context-menu/index.ts, packages/fast-components-styles-msft/src/divider/index.ts, packages/fast-components-styles-msft/src/flipper/index.ts, packages/fast-components-styles-msft/src/hypertext/index.ts, packages/fast-components-styles-msft/src/number-field/index.ts, packages/fast-components-styles-msft/src/patterns/input-field.ts, packages/fast-components-styles-msft/src/pivot/index.ts, packages/fast-components-styles-msft/src/progress/index.ts, packages/fast-components-styles-msft/src/radio/index.ts, packages/fast-components-styles-msft/src/text-action/index.ts, packages/fast-components-styles-msft/src/toggle/index.ts, packages/fast-components-styles-msft/src/typography/index.ts
Fixes based on @bheston review.
https://github.com/Microsoft/fast-dna/issues/1478
=> fix: update to improve animations functionality and style

packages/fast-form-generator-react/src/form/form-item.children.style.ts
When text is longer than one line in the component children it wraps and breaks the boundary of its container.
Before:
After:
=> fix: text from wrapping in child item of fast form

packages/fast-jss-manager-react/src/jss-manager.spec.tsx, packages/fast-jss-manager-react/src/jss-manager.tsx, packages/fast-jss-manager-react/src/manage-jss.spec.tsx, packages/fast-jss-manager-react/src/manage-jss.tsx
Adds the ability to pass a react ref to a component managed by the JSSManager HOC. 
Closes https://github.com/Microsoft/fast-dna/issues/1435
BREAKING CHANGE: significant prop API change
=> feat: update to enable innerRef prop on JSS managed components

packages/fast-css-editor-react/README.md, packages/fast-tooling-react/README.md, packages/fast-tooling-react/app/app.tsx, packages/fast-tooling-react/app/pages/css-editor.tsx, packages/fast-tooling-react/src/css-editor/editor.props.ts, packages/fast-tooling-react/src/css-editor/editor.schema.json, packages/fast-tooling-react/src/css-editor/editor.spec.tsx, packages/fast-tooling-react/src/css-editor/editor.style.ts, packages/fast-tooling-react/src/css-editor/editor.tsx, packages/fast-tooling-react/src/css-editor/index.ts, packages/fast-tooling-react/src/css-editor/position/index.ts, packages/fast-tooling-react/src/css-editor/position/position.props.ts, packages/fast-tooling-react/src/css-editor/position/position.schema.json, packages/fast-tooling-react/src/css-editor/position/position.spec.tsx, packages/fast-tooling-react/src/css-editor/position/position.style.ts, packages/fast-tooling-react/src/css-editor/position/position.tsx, packages/fast-tooling-react/src/css-editor/spacing/index.ts, packages/fast-tooling-react/src/css-editor/spacing/spacing.props.ts, packages/fast-tooling-react/src/css-editor/spacing/spacing.schema.json, packages/fast-tooling-react/src/css-editor/spacing/spacing.spec.tsx, packages/fast-tooling-react/src/css-editor/spacing/spacing.style.ts, packages/fast-tooling-react/src/css-editor/spacing/spacing.tsx, packages/fast-tooling-react/src/index.ts, packages/fast-tooling-react/src/style/utilities.ts
Adds the CSS editor to the tooling package and deprecates the previous CSS editor.
Continues the work on #1423 
=> feat: add css editor to the tooling package

packages/fast-components-styles-msft/src/utilities/color/accent-fill.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground-cut.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-focus.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground-hint.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-outline.ts
The current memoization techniques do not work. We can optomize these functions with functional memoization at a later point, but we should remove the bug for the time being. Tracking future work in #1524
=> fix: remove memoization from color utilities

packages/fast-breakpoint-tracker-react/package.json, packages/fast-components-foundation-react/package.json, packages/fast-components-react-base/package.json, packages/fast-components-react-base/src/listbox/listbox.spec.tsx, packages/fast-components-react-base/src/listbox/listbox.tsx, packages/fast-components-react-base/src/select/select.spec.tsx, packages/fast-components-react-msft/package.json, packages/fast-css-editor-react/package.json, packages/fast-form-generator-react/package.json, packages/fast-jss-manager-react/package.json, packages/fast-navigation-generator-react/package.json, packages/fast-tooling-react/package.json, packages/fast-viewer-react/package.json
=> chore: fix build break due to missing jest module resolver for json files

website/static/css/custom.css
Updated custom.css with a new class that styles items within the sidebar left panel in the website
According to the team the style was different then expected.
=> fix: update styling in left navigation to match right navigation

website/package.json
updated docusaurus to version 1.7.2 on package.json in a attemp to resolve the issue described in bug #1497
=> chore: update version of docusaurus to the latestUpdated docusaurus version

packages/fast-permutator/README.md
Deprecates the fast-permutator package
The package's `getExample` function has been migrated and renamed to `getDataFromSchema` in the fast-tooling-react package.
=> feat: deprecate the permutator package

packages/fast-tooling-react/README.md, packages/fast-tooling-react/src/data-utilities/generate.spec.ts, packages/fast-tooling-react/src/data-utilities/generate.ts
Adds a check for the examples key to be used if default has not been provided.
This aligns with the new JSON schema generics.
https://json-schema.org/understanding-json-schema/reference/generic.html
=> feat: add a check for the examples key in JSON schema when generating data

packages/fast-development-site-react/src/components/site/index.tsx, website/i18n/en.json
When the page was being refreshed, the initial state of the component was being set disconsidering the current location, which would reset the state as if it was a fresh navigation.
https://github.com/Microsoft/fast-dna/issues/1303
=> fix: update component status bar to always reflect the active component

packages/fast-components-react-msft/webpack.config.js
Removes module alias of a module not dependend on directly so that it can be  correclty resolved.
=> chore: remove alias of module we do not directly depend on

packages/fast-components-foundation-react/src/foundation/foundation.spec.tsx, packages/fast-components-foundation-react/src/foundation/foundation.ts
Added new test to represent the steps for repro in bug #1329 
Fixed the issue on the component
#1329 
=> fix: added test for bug #1329 and fixed the bug

packages/fast-components-react-msft/package.json, packages/fast-development-site-react/package.json, packages/fast-layouts-react/package.json, packages/fast-viewer-react/package.json
Ensures `@microsoft/fast-jss-manager-react` is a peer dependency for all packages to avoid potentional for duplicate versions of the library in a single codebase
=> feat: ensure fast-jss-manager-react is a peer dependency for all packages

packages/fast-components-styles-msft/src/design-system/index.ts, packages/fast-components-styles-msft/src/utilities/color/accent-fill.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-outline.ts, packages/fast-components-styles-msft/src/utilities/color/palette.ts
Adds recipe deltas to the design system so that they can be adjusted. Also changes the neutral/accent palette data so they accept a simple array of color strings instead of a palette config. This will make palette adjustment more flexible long-term.
=> feat: add deltas to design-system and update palettes to be an array of swatches

packages/fast-tooling-react/README.md, packages/fast-tooling-react/app/pages/css-editor.tsx, packages/fast-tooling-react/src/css-editor/editor.props.ts, packages/fast-tooling-react/src/css-editor/editor.schema.json, packages/fast-tooling-react/src/css-editor/editor.spec.tsx, packages/fast-tooling-react/src/css-editor/editor.tsx, packages/fast-tooling-react/src/css-editor/position/position.props.ts, packages/fast-tooling-react/src/css-editor/position/position.schema.json, packages/fast-tooling-react/src/css-editor/position/position.spec.tsx, packages/fast-tooling-react/src/css-editor/position/position.tsx, packages/fast-tooling-react/src/css-editor/spacing/spacing.props.ts, packages/fast-tooling-react/src/css-editor/spacing/spacing.schema.json, packages/fast-tooling-react/src/css-editor/spacing/spacing.spec.tsx, packages/fast-tooling-react/src/css-editor/spacing/spacing.tsx, packages/fast-tooling-react/src/css-editor/utilities/form-item.tsx, packages/fast-tooling-react/src/utilities/form-item.base.tsx, packages/fast-tooling-react/src/utilities/form-item.common.ts, packages/fast-tooling-react/src/utilities/form-item.soft-remove.tsx
Updates the CSS editor to have a similar interface to the `Form` and other tooling, consolidates some logic to allow addition of other components to be easier.
=> feat: update and refactor the CSS editor

packages/fast-tooling-react/package.json, packages/fast-tooling-react/src/data-utilities/location.ts, packages/fast-tooling-react/src/form/utilities/form.tsx
This updates the JSON schema validator to use ajv which is more up-to-date and performant, and has a larger community than some of the other options available.
Resolves #1527
=> feat: update to use ajv as the JSON schema validator

packages/fast-components-styles-msft/package.json, packages/fast-components-styles-msft/src/utilities/acrylic.ts, packages/fast-components-styles-msft/src/utilities/elevation.ts
Removes final chroma-js references. We are now chroma-free
=> feat: remove chroma

packages/fast-components-styles-msft/src/utilities/color/accent-fill.spec.ts, packages/fast-components-styles-msft/src/utilities/color/accent-fill.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground-cut.spec.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground-cut.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground.spec.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/accent.ts, packages/fast-components-styles-msft/src/utilities/color/common.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-focus.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-focus.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground-hint.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground-hint.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-outline.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-outline.ts, packages/fast-components-styles-msft/src/utilities/color/palette.spec.ts, packages/fast-components-styles-msft/src/utilities/color/palette.ts
Updates color typings to make more sense, fixes some errors in tests.
=> fix: update color utility typings

packages/fast-layouts-react/src/index.ts, packages/fast-layouts-react/src/utilities/breakpoint-tracker.spec.ts, packages/fast-layouts-react/src/utilities/breakpoint-tracker.ts, packages/fast-layouts-react/src/utilities/index.ts
=> feat: add setter to breakpoint tracker to enable customizing breakpoints in fast-layouts

packages/fast-development-site-react/src/components/site/index.tsx
Fixes an issue where the examples were not able to be exited on the examples route.
=> fix: resolve an issue with the examples route not being editable

packages/fast-colors/README.md
Adds initial documentation to `@microsoft/fast-color` `README.md`
=> chore: adds documentation to fast-colors readme

packages/fast-components-styles-msft/src/badge/index.ts, packages/fast-components-styles-msft/src/breadcrumb/index.ts, packages/fast-components-styles-msft/src/button/index.ts, packages/fast-components-styles-msft/src/card/index.ts, packages/fast-components-styles-msft/src/checkbox/index.ts, packages/fast-components-styles-msft/src/context-menu-item/index.ts, packages/fast-components-styles-msft/src/context-menu/index.ts, packages/fast-components-styles-msft/src/dialog/index.ts, packages/fast-components-styles-msft/src/label/index.ts, packages/fast-components-styles-msft/src/metatext/index.ts, packages/fast-components-styles-msft/src/patterns/input-field.ts, packages/fast-components-styles-msft/src/pivot/index.ts, packages/fast-components-styles-msft/src/radio/index.ts, packages/fast-components-styles-msft/src/select-option/index.ts, packages/fast-components-styles-msft/src/select/index.ts, packages/fast-components-styles-msft/src/text-action/index.ts, packages/fast-components-styles-msft/src/toggle/index.ts, packages/fast-components-styles-msft/src/utilities/border.ts, packages/fast-components-styles-msft/src/utilities/typography.ts
Change the utilities so that they can more easily be used in stylesheets that are not functions
=> feat: change utilities to work with non-function stylesheets

packages/fast-tooling-react/app/pages/css-editor.tsx, packages/fast-tooling-react/src/style/utilities.ts
Updates styling so that the remove button is in the correct location on the `Form`.
=> fix: updates the styling of children and array items so that the remove button is inline with the add button

packages/fast-jss-manager-react/src/index.ts
Adds consumer export so authors can gain access to the DesignSystem object inside of a React component.
=> feat: add context-consumer to package exports

packages/fast-tooling-react/README.md
Removed WAAPI badge because it is not relevant to this package.
=> chore: update README.md to remove irrelevant WAAPI badge

packages/fast-components-react-msft/src/action-trigger/action-trigger.schema.json, packages/fast-components-react-msft/src/badge/badge.schema.json, packages/fast-components-react-msft/src/breadcrumb/breadcrumb.schema.json, packages/fast-components-react-msft/src/button/button.schema.json, packages/fast-components-react-msft/src/call-to-action/call-to-action.schema.json, packages/fast-components-react-msft/src/caption/caption.schema.json, packages/fast-components-react-msft/src/heading/heading.schema.json, packages/fast-components-react-msft/src/hypertext/hypertext.schema.json, packages/fast-components-react-msft/src/label/label.schema.json, packages/fast-components-react-msft/src/metatext/metatext.schema.json, packages/fast-components-react-msft/src/paragraph/paragraph.schema.json, packages/fast-components-react-msft/src/subheading/subheading.schema.json, packages/fast-components-react-msft/src/toggle/toggle.schema.json, packages/fast-components-react-msft/src/typography/typography.schema.json
Adds children as required in the `@microsoft/fast-components-react-msft` components.
=> fix: add children as required in JSON schemas where children are expected

packages/fast-components-styles-msft/src/index.ts
=> fix: ensure all MSFT style utilities are exported

packages/fast-layouts-react/src/column/column.props.ts
=> fix: ensure column props are a union type of both handled and unhandled props

packages/fast-components-react-base/src/context-menu-item/context-menu-item.spec.tsx, packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx, packages/fast-components-react-base/src/context-menu/context-menu.tsx
Ensures that a context-menu-item's `onInvoke` callback gets fired when an item is right clicked.
Closes #1599
=> feat: invoke context-menu-item from right click

packages/fast-layouts-react/src/row/row.props.ts, packages/fast-layouts-react/src/row/row.tsx
=> feat: add prop to support setting initial height on Row

packages/fast-layouts-react/src/row/row.tsx
=> fix: update initial row height to be 40 to match previous implementation

.github/pull_request_template.md
This PR updates the pull request template to remove explicit word requirements in `description` details. I believe that the primary requirements are listed below. I believe the removed text which explicitly requires the use of "add", "remove", "update" limits a contributors ability to provide a detailed explanation. While those words may typically fit many scenarios, trying to ensure all descriptions use a specific set of words is tedious and limits the ability to be concise and avoid redundancy.
Description is ultimately secondary to the required types of `fix`, `feat`, `chore`.
```
<description> is required and speaks to what the user gets from this PR:
- Be concise.
- Use all lowercase characters. 
- Use imperative, present tense (e.g. `add` not `adds`.)
- Do not end your description …
```
=> chore: remove requirement to start pr descriptions with explicit words

packages/fast-layouts-react/app/index.tsx, packages/fast-layouts-react/src/grid/grid.tsx
This PR allows Grid to accept null children without breaking.
It is common practice in react to return null from a function or
component in order to render nothing. It is also common to use ternary
operations inside brackets to [conditionally render
elements](https://reactjs.org/docs/conditional-rendering.html)
=> fix: fast-layouts-react accepts null children

packages/fast-components-styles-msft/package.json, packages/fast-components-styles-msft/src/design-system/index.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground.spec.ts, packages/fast-components-styles-msft/src/utilities/color/accent.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/palette.ts
Ensures that unit-tests are run during build gate
=> chore: add unit-tests to fast-components-styles-msft build-gate

packages/fast-layouts-react/src/row/row.tsx
Prevents `initialHeight` from being applied as a DOM attribute
=> fix: prevent error from unhandled props in Row

packages/fast-tooling-react/src/__tests__/schemas/children.schema.json, packages/fast-tooling-react/src/form/form/form-control.spec.tsx, packages/fast-tooling-react/src/form/form/form-control.tsx
Fixes an issue where ids in schemas were not restricting the allowable child options.
=> fix: fixes a reversion where ids no longer restricted the child options

packages/fast-tooling-react/src/form/form/form-item.array.props.ts, packages/fast-tooling-react/src/form/form/form-item.array.spec.tsx, packages/fast-tooling-react/src/form/form/form-item.array.style.ts, packages/fast-tooling-react/src/form/form/form-item.array.tsx
Adds the ability to unset/reset an array.
=> feat: allow an array to be unset/reset if it is optional

packages/fast-components-styles-msft/src/auto-suggest-option/index.ts, packages/fast-components-styles-msft/src/badge/index.ts, packages/fast-components-styles-msft/src/button/index.ts, packages/fast-components-styles-msft/src/carousel/index.ts, packages/fast-components-styles-msft/src/checkbox/index.ts, packages/fast-components-styles-msft/src/context-menu-item/index.ts, packages/fast-components-styles-msft/src/context-menu/index.ts, packages/fast-components-styles-msft/src/divider/index.ts, packages/fast-components-styles-msft/src/flipper/index.ts, packages/fast-components-styles-msft/src/hypertext/index.ts, packages/fast-components-styles-msft/src/label/index.ts, packages/fast-components-styles-msft/src/metatext/index.ts, packages/fast-components-styles-msft/src/number-field/index.ts, packages/fast-components-styles-msft/src/patterns/input-field.ts, packages/fast-components-styles-msft/src/pivot/index.ts, packages/fast-components-styles-msft/src/progress/index.ts, packages/fast-components-styles-msft/src/radio/index.ts, packages/fast-components-styles-msft/src/select-option/index.ts, packages/fast-components-styles-msft/src/select/index.ts, packages/fast-components-styles-msft/src/text-action/index.ts, packages/fast-components-styles-msft/src/text-area/index.ts, packages/fast-components-styles-msft/src/text-field/index.ts, packages/fast-components-styles-msft/src/toggle/index.ts, packages/fast-components-styles-msft/src/utilities/border.ts, packages/fast-components-styles-msft/src/utilities/design-system.ts, packages/fast-components-styles-msft/src/utilities/disabled.ts, packages/fast-components-styles-msft/src/utilities/format.spec.ts, packages/fast-components-styles-msft/src/utilities/format.ts, packages/fast-jss-utilities/src/units.ts
The formatter allows us to format an input string with designSystemResolvers, meaning we don't need access to a DesignSystem value to format properties like border. This will help enable us to move away from function stylesheets, which are less performant than object stylesheets when design-system values change at runtime.
=> feat: add DesignSystemResolver formatting utility

.github/CODEOWNERS
=> chore: update codeowners to remove old packages and include fast-tooling-react

packages/fast-components-react-base/src/context-menu/context-menu.schema.json, packages/fast-components-react-msft/src/context-menu/context-menu.schema.json
Fixes an issue where `ContextMenu` errors when trying to display `ContextMenuItem`.
=> fix: updates the allowed children ids for the context menu component

packages/fast-components-styles-msft/src/context-menu/index.ts
Fixes issue where context-menu drop shadow was not rendering
=> fix: ensure context-menu drop shadow renders

package.json
Prettier will now only be run on staged files during the pre-commit hook
Prior, prettier was run against all files and then any changed file (staged or not) was added to the commit - this was slow and files were added to commits they weren't intended to be added to. This fixes both issues.
=> chore: fix prettier hook to only fix changed files on pre-commit hook

packages/fast-components-class-name-contracts-msft/src/button/index.ts, packages/fast-components-react-msft/src/button/button.props.ts, packages/fast-components-react-msft/src/button/button.schema.json, packages/fast-components-react-msft/src/button/button.spec.tsx, packages/fast-components-react-msft/src/button/examples.data.tsx, packages/fast-components-styles-msft/src/button/index.ts
Added `stealth` appearance to `<Button/>` `appearance` props.
Closes: #1598 
Stealth is a reoccurring pattern we see throughout Microsoft UI. This allows us to quickly repeat the pattern without having to copy styles over and over.
=> feat: add stealth appearance to button appearance enum

packages/fast-components-styles-msft/src/button/index.ts, packages/fast-components-styles-msft/src/utilities/density.ts, packages/fast-components-styles-msft/src/utilities/design-system.ts
Converts button stylesheet to be an object instead of a function - this will improve the performance of button render when the design-system changes.
Performance
=> fix: refactor button component stylesheet

packages/fast-components-react-base/src/radio/examples.data.tsx, packages/fast-components-react-base/src/radio/radio.props.ts, packages/fast-components-react-base/src/radio/radio.schema.json, packages/fast-components-react-base/src/radio/radio.spec.tsx, packages/fast-components-react-base/src/radio/radio.tsx, packages/fast-components-react-msft/src/radio/radio.schema.json
=> feat: add name prop to radio component

packages/fast-components-react-msft/src/text-action/examples.data.tsx, packages/fast-components-react-msft/src/text-action/text-action.spec.tsx, packages/fast-components-react-msft/src/text-action/text-action.tsx
Closes [#1656](https://github.com/Microsoft/fast-dna/issues/1656)
Removes restrictions on glyph rendering within text action
Text action restricted glyphs and buttons sharing the same space (before or after). This restriction needs to be lifted to align with new designs and allow proper usage.
=> feat: remove restriction on glyph rendering in text action

packages/fast-tooling-react/app/pages/form/index.ts, packages/fast-tooling-react/src/__tests__/schemas/one-of-deeply-nested.schema.json, packages/fast-tooling-react/src/data-utilities/location.ts, packages/fast-tooling-react/src/form/utilities/form.spec.ts
Prevents the validator from not being able to find a valid oneOf/anyOf schema option.
=> fix: prevent a -1 on a oneOf/anyOf validation check

packages/fast-tooling-react/README.md, packages/fast-tooling-react/src/css-editor/editor.props.ts, packages/fast-tooling-react/src/css-editor/editor.style.ts, packages/fast-tooling-react/src/css-editor/editor.tsx, packages/fast-tooling-react/src/css-editor/height/height.props.ts, packages/fast-tooling-react/src/css-editor/height/height.schema.json, packages/fast-tooling-react/src/css-editor/height/height.spec.tsx, packages/fast-tooling-react/src/css-editor/height/height.style.ts, packages/fast-tooling-react/src/css-editor/height/height.tsx, packages/fast-tooling-react/src/css-editor/height/index.ts, packages/fast-tooling-react/src/css-editor/position/position.style.ts, packages/fast-tooling-react/src/css-editor/spacing/spacing.style.ts, packages/fast-tooling-react/src/css-editor/width/index.ts, packages/fast-tooling-react/src/css-editor/width/width.props.ts, packages/fast-tooling-react/src/css-editor/width/width.schema.json, packages/fast-tooling-react/src/css-editor/width/width.spec.tsx, packages/fast-tooling-react/src/css-editor/width/width.style.ts, packages/fast-tooling-react/src/css-editor/width/width.tsx
Adds components for width and height and adds them to the CSSEditor.
=> feat: add width and height components to the CSS Editor

packages/fast-components-react-msft/src/pivot/examples.data.tsx
The 2nd pivot example looked broken without text for the first item in `<Pivot/>`. 
Closes: #1694 
Removed 2nd Pivot example.
=> chore: remove unnecessary pivot example

packages/fast-layouts-react/package.json
Corrects peer dependency version string
=> fix: correct peer dependency string

packages/fast-components-react-msft/src/select/select.tsx
=> fix: reset viewbox to center default select icon

packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.ts
Aligns `neutralFillInput` recipe with designs
=> feat: update neutral-fill-input recipe

packages/fast-components-styles-msft/src/design-system/index.ts
Adjusts delta offsets to align with design files
=> feat: adjust selected deltas

packages/fast-tooling-react/src/form/form/form-section.tsx
Allows the user to have the oneOf/anyOf select label be a title.
Resolves #1681 
=> feat: labels for oneOf/anyOf use JSON schema title metadata

packages/fast-tooling-react/app/pages/form/index.ts, packages/fast-tooling-react/src/__tests__/schemas/badge.schema.json, packages/fast-tooling-react/src/__tests__/schemas/const.schema.json, packages/fast-tooling-react/src/data-utilities/generate.ts, packages/fast-tooling-react/src/form/form/form-control.tsx, packages/fast-tooling-react/src/form/form/form-item.display.props.ts, packages/fast-tooling-react/src/form/form/form-item.display.spec.tsx, packages/fast-tooling-react/src/form/form/form-item.display.style.ts, packages/fast-tooling-react/src/form/form/form-item.display.tsx, packages/fast-tooling-react/src/form/form/form-item.select.tsx, packages/fast-tooling-react/src/form/utilities/form.tsx
Adds a new form item to deal with JSON schema 'const' values as well as single enum items which are treated in the same way. This adds an indicator for a const value that can be set.
Resolves #1674 
=> feat: support added for JSON schema keyword 'const'

packages/fast-development-site-react/src/components/site/configuration-panel.tsx
Fixes an issue for style mapping to children in the development site.
=> fix: updates the dev site to the new CSS Editor API

packages/fast-components-styles-msft/README.md, packages/fast-components-styles-msft/src/auto-suggest/index.ts, packages/fast-components-styles-msft/src/card/index.ts, packages/fast-components-styles-msft/src/context-menu/index.ts, packages/fast-components-styles-msft/src/dialog/index.ts, packages/fast-components-styles-msft/src/select/index.ts, packages/fast-components-styles-msft/src/utilities/elevation.ts
Adds a new function to apply elevation in style sheets so we don't have to have a reference to the design system.
Fixes one of the few remaining places we still needed to reference the design system in style sheet code by changing to a function that is a DesignSystemResolver.
Added a new function to match the 'apply' naming convention of other similar utility functions, as well to be able to continue support and deprecate the previous function.
=> fix: updated elevation function to use the correct design system accessor structure

packages/fast-components-react-base/package.json, packages/fast-components-react-msft/package.json, packages/fast-jss-manager-angular/package.json, packages/fast-layouts-react/package.json, packages/fast-tooling-react/package.json
Looks like jest updated their code-coverage algorithm, so this reduces our coverage to pass new algorithm. 
=> chore: reduce coverage to fix build break

packages/fast-components-react-base/src/checkbox/checkbox.schema.json, packages/fast-components-react-base/src/dialog/dialog.schema.json, packages/fast-components-react-base/src/image/image.schema.json, packages/fast-components-react-base/src/radio/radio.schema.json, packages/fast-components-react-msft/src/checkbox/checkbox.schema.json, packages/fast-components-react-msft/src/dialog/dialog.schema.json, packages/fast-components-react-msft/src/flipper/flipper.schema.json, packages/fast-components-react-msft/src/image/image.schema.json, packages/fast-components-react-msft/src/radio/radio.schema.json, packages/fast-development-site-react/app/components/paragraph/paragraph.schema.json, packages/fast-development-site-react/app/components/span/span.schema.json, packages/fast-tooling-react/src/__tests__/schemas/general-example.schema.json, packages/fast-tooling-react/src/__tests__/schemas/general.schema.json, packages/fast-tooling-react/src/__tests__/schemas/number-field.schema.json, packages/fast-tooling-react/src/__tests__/schemas/text-field.schema.json
=> fix: schemas should use examples as arrays

packages/fast-components-class-name-contracts-msft/src/action-toggle/index.ts, packages/fast-components-class-name-contracts-msft/src/action-trigger/index.ts, packages/fast-components-class-name-contracts-msft/src/call-to-action/index.ts, packages/fast-components-react-msft/src/action-toggle/action-toggle.props.ts, packages/fast-components-react-msft/src/action-toggle/action-toggle.schema.json, packages/fast-components-react-msft/src/action-toggle/action-toggle.spec.tsx, packages/fast-components-react-msft/src/action-toggle/examples.data.tsx, packages/fast-components-react-msft/src/action-trigger/action-trigger.props.ts, packages/fast-components-react-msft/src/action-trigger/action-trigger.schema.json, packages/fast-components-react-msft/src/action-trigger/action-trigger.spec.tsx, packages/fast-components-react-msft/src/action-trigger/action-trigger.tsx, packages/fast-components-react-msft/src/action-trigger/examples.data.tsx, packages/fast-components-react-msft/src/button/examples.data.tsx, packages/fast-components-react-msft/src/call-to-action/call-to-action.props.ts, packages/fast-components-react-msft/src/call-to-action/call-to-action.schema.json, packages/fast-components-react-msft/src/call-to-action/call-to-action.spec.tsx, packages/fast-components-react-msft/src/call-to-action/call-to-action.tsx, packages/fast-components-react-msft/src/call-to-action/examples.data.tsx, packages/fast-components-styles-msft/src/action-toggle/index.ts, packages/fast-components-styles-msft/src/action-trigger/index.ts, packages/fast-components-styles-msft/src/call-to-action/index.ts
Updated Action toggle, Action trigger, and Call to action to have the same complete set of appearance options.
We recently formalized the 'stealth' appearance for button, but not every other button-like component. This update makes the components less opinionated about what type of component can have a given style.
=> feat: updated all button-like components to have the same appearance style options

packages/fast-tooling-react/app/app.tsx, packages/fast-tooling-react/app/pages/css-property-editor.tsx, packages/fast-tooling-react/src/css-property-editor/index.ts, packages/fast-tooling-react/src/css-property-editor/property-editor.props.ts, packages/fast-tooling-react/src/css-property-editor/property-editor.spec.tsx, packages/fast-tooling-react/src/css-property-editor/property-editor.style.ts, packages/fast-tooling-react/src/css-property-editor/property-editor.tsx, packages/fast-tooling-react/src/css-property-editor/property-editor.utilities.ts, packages/fast-tooling-react/src/style/constants.ts
Preliminary work to add a CSS property editor.
This adds a CSS property editor which allows for advanced CSS property editing.
=> feat: add an ad-hoc css property editor

packages/fast-components-react-msft/app/utilities/additional-props.plugin.ts, packages/fast-components-react-msft/src/text-action/examples.data.tsx, packages/fast-components-react-msft/src/text-action/text-action.props.ts, packages/fast-components-react-msft/src/text-action/text-action.tsx, packages/fast-components-styles-msft/src/text-action/index.ts
Fixes issue with the input button not being able to be correctly controlled via the form generator
=> fix: addresses data issues with input button in text action

packages/fast-components-react-base/src/slider/slider.tsx, packages/fast-components-react-msft/src/slider/examples.data.tsx, packages/fast-components-styles-msft/src/slider-label/index.ts, packages/fast-components-styles-msft/src/slider/index.ts
- Added density support to the slider styles.
- Cleaned up to use design system utility functions where appropriate.
Slider needs to be inclusive with density.
=> fix: update slider to support density and other minor style polish

packages/fast-tooling-react/app/pages/form/index.ts, packages/fast-tooling-react/src/__tests__/schemas/defaults.schema.json, packages/fast-tooling-react/src/form/form/form-control.tsx, packages/fast-tooling-react/src/form/form/form-item.display.spec.tsx, packages/fast-tooling-react/src/form/form/form-item.display.tsx, packages/fast-tooling-react/src/form/form/form-section.props.ts, packages/fast-tooling-react/src/form/form/form-section.spec.tsx, packages/fast-tooling-react/src/form/form/form-section.tsx, packages/fast-tooling-react/src/form/form/form.tsx, packages/fast-tooling-react/src/form/utilities/form.spec.ts, packages/fast-tooling-react/src/form/utilities/form.tsx
Allows for inheritance in for default values.
Resolves #1612 
=> feat: allow defaults to be inherited

packages/fast-components-react-msft/app/app.tsx, packages/fast-components-styles-msft/src/design-system/design-system.schema.json, packages/fast-development-site-react/src/components/site/configuration-panel.tsx, packages/fast-development-site-react/src/components/site/index.tsx
Adds an optional design system prop to the development site.
=> feat: add optional design system to the development site

packages/fast-development-site-react/src/components/site/index.tsx
Fixes an issue where the designSystemEditing prop was optional but still expected.
=> fix: removes the requirement for design system editing in the configuration panel

packages/fast-components-styles-msft/src/utilities/color/index.ts
=> feat: export isDarkMode as a new named function

packages/fast-development-site-react/src/components/site/configuration-panel.tsx
Prevent the any direct style editing from occuring when the navigation is not on a component or child.
=> fix: prevent non-children from showing the style editing in the configuration panel

packages/fast-tooling-react/app/configs/example.data.ts, packages/fast-tooling-react/app/pages/navigation.tsx, packages/fast-tooling-react/app/pages/navigation/children.schema.json, packages/fast-tooling-react/app/pages/navigation/example.data.ts, packages/fast-tooling-react/app/pages/navigation/no-children.schema.json, packages/fast-tooling-react/src/data-utilities/location.ts, packages/fast-tooling-react/src/data-utilities/mapping.ts, packages/fast-tooling-react/src/data-utilities/types.ts, packages/fast-tooling-react/src/form/utilities/form.tsx, packages/fast-tooling-react/src/navigation/navigation.props.ts, packages/fast-tooling-react/src/navigation/navigation.spec.tsx, packages/fast-tooling-react/src/navigation/navigation.tsx, packages/fast-tooling-react/src/navigation/navigation.utilities.spec.ts, packages/fast-tooling-react/src/navigation/navigation.utilities.ts
Shows navigational hierarchy of children for more complex data structures.
Resolves #1696
=> feat: allow complex object and array nesting in the navigation

packages/fast-tooling-react/src/css-property-editor/property-editor.spec.tsx, packages/fast-tooling-react/src/css-property-editor/property-editor.tsx, packages/fast-tooling-react/src/css-property-editor/property-editor.utilities.ts, packages/fast-web-utilities/src/strings.spec.ts, packages/fast-web-utilities/src/strings.ts
Filter results to show keys as dash separated and camelCased when returned by the onChange callback.
=> feat: show values as dash separated and send camelCase values in the CSS property editor callback

packages/fast-tooling-react/src/css-editor/height/height.spec.tsx, packages/fast-tooling-react/src/css-editor/height/height.tsx, packages/fast-tooling-react/src/css-editor/width/width.spec.tsx, packages/fast-tooling-react/src/css-editor/width/width.tsx
Fixes an issue where the width and height from the CSS editor can go from controlled to uncontrolled.
=> fix: resolves an issue where height and width can go from controlled to uncontrolled state

packages/fast-components-styles-msft/src/utilities/color/accent-fill.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground-cut.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/accent.ts, packages/fast-components-styles-msft/src/utilities/color/common.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-focus.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground-hint.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-outline.ts, packages/fast-components-styles-msft/src/utilities/color/palette.ts
Refactor color utilities to abstract common patterns
=> fix: reduce color utility footprint

README.md
Fix typo in README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/fast-dna/1786)
=> chore: fix typo in root readme

CONTRIBUTING.md
Adds documentation for contributors on how to document breaking changes.
This clarifies how contributors can document breaking changes so that a clear migration strategy is outlined.
=> chore: add to contributor documentation on how to deal with breaking changes

packages/fast-tooling-react/app/app.tsx, packages/fast-tooling-react/app/pages/form-and-navigation.tsx, packages/fast-tooling-react/app/pages/form.tsx
Adds an example of the Navigation component working with the Form component for integration testing.
=> chore: add an integrated example of the form and navigation to the tooling tests app

packages/fast-tooling-react/src/navigation/navigation.spec.tsx, packages/fast-tooling-react/src/navigation/navigation.tsx, packages/fast-tooling-react/src/navigation/navigation.utilities.ts
Fixes an issue where when the data type is children it fires an unnecessary location update callback.
=> fix: add check for data type to make sure children don't fire a location update callback

packages/fast-color-explorer/app/design-system.ts, packages/fast-jss-manager-react/src/design-system-provider.tsx, packages/fast-jss-manager-react/src/jss-manager.tsx
The DesignSystemProvider can accept any value type so we really shouldn't impose restrictions on the data type of a "design system" - this makes the design system a simple generic value.
=> fix: makes design system entirely generic

packages/fast-color-explorer/app/app.tsx, packages/fast-color-explorer/app/design-system.ts, packages/fast-color-explorer/app/gradient.tsx, packages/fast-color-explorer/app/state.ts, packages/fast-components-styles-msft/src/design-system/index.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground.spec.ts, packages/fast-components-styles-msft/src/utilities/color/accent.spec.ts, packages/fast-components-styles-msft/src/utilities/color/accent.ts, packages/fast-components-styles-msft/src/utilities/color/color-constants.ts, packages/fast-components-styles-msft/src/utilities/color/palette.spec.ts, packages/fast-components-styles-msft/src/utilities/design-system.ts
Reverts microsoft/fast-dna#1799
=> Revert "fix: track base colors in design system"

packages/fast-components-class-name-contracts-msft/src/index.ts, packages/fast-components-class-name-contracts-msft/src/text-action/index.ts, packages/fast-components-class-name-contracts-msft/src/text-field/index.ts, packages/fast-components-react-msft/src/text-action/examples.data.tsx, packages/fast-components-react-msft/src/text-action/index.ts, packages/fast-components-react-msft/src/text-action/text-action.props.ts, packages/fast-components-react-msft/src/text-action/text-action.schema.json, packages/fast-components-react-msft/src/text-action/text-action.spec.tsx, packages/fast-components-react-msft/src/text-action/text-action.tsx, packages/fast-components-react-msft/src/text-field/examples.data.tsx, packages/fast-components-react-msft/src/text-field/index.ts, packages/fast-components-react-msft/src/text-field/text-field.props.ts, packages/fast-components-react-msft/src/text-field/text-field.schema.json, packages/fast-components-react-msft/src/text-field/text-field.spec.tsx, packages/fast-components-react-msft/src/text-field/text-field.tsx, packages/fast-components-styles-msft/src/design-system/index.ts, packages/fast-components-styles-msft/src/patterns/input-field.ts, packages/fast-components-styles-msft/src/text-action/index.ts, packages/fast-components-styles-msft/src/text-field/index.ts
Added 'appearance' property to support outlined and filled input fields.
The update in motivation for design alignment is that controls either have an outline or a plate, but not both.
=> feat: update the text input components to add 'filled' appearance

packages/fast-tooling-react/README.md, packages/fast-tooling-react/app/pages/code-preview/examples.data.ts, packages/fast-tooling-react/app/pages/code-preview/index.tsx, packages/fast-tooling-react/src/data-utilities/index.ts, packages/fast-tooling-react/src/data-utilities/mapping.spec.ts, packages/fast-tooling-react/src/data-utilities/mapping.ts
This refactors the code preview to be more maintainable.
=> feat: refactor and export data mapping to code preview

packages/fast-jss-manager-react/README.md
Adds documentation to help address common issues and questions about the jss manager.
=> chore: update JSS manager readme with perf instructions

packages/fast-components-styles-msft/README.md
=> chore: add documentation for common MSFT style utilities

docs/en/contributing/working.md
=> chore: update contributing documentation with latest PR guidance

README.md
Update badge markup for circle ci and lerna
Lerna changed their domain which caused our badge to break.  CircleCI seems to be case sensitive so that also broke that badge.
=> chore: update badges to resolve broken links

packages/fast-tooling-react/src/data-utilities/mapping.ts
Fixes a memory leak in the data mapper when using nested react components.
=> fix: address a memory leak in the mapDataToComponent utility

packages/fast-tooling-react/package.json, packages/fast-tooling-react/src/navigation/navigation.tsx
Adds a missing dependency to the package.
=> fix: add a missing dependency to the package

packages/fast-components-react-msft/app/app.tsx, packages/fast-components-styles-msft/src/design-system/design-system.schema.json, packages/fast-development-site-react/src/components/site/configuration-panel.tsx, packages/fast-development-site-react/src/components/site/index.tsx
There was a few bugs related to design system changes in the component explorer. This cleans up how this works and bridges communication between the sliders and pickers at the bottom of the component explorer and the design system config panel.
Closes: #1783 
1. Changing color string in design system config panel crashed the component.
2. Changing the background color picker was not reflected in the design system config panel
3. The density slider no longer worked and was not reflected in the design system config panel.
4. The accent color picker no longer worked.
=> fix: density slider and color pickers in component explorer

packages/fast-components-react-msft/src/carousel/carousel.props.ts, packages/fast-components-react-msft/src/carousel/carousel.spec.tsx, packages/fast-components-react-msft/src/carousel/carousel.tsx, packages/fast-components-react-msft/src/carousel/examples.data.tsx, packages/fast-components-react-msft/src/carousel/index.ts
closes #1826 
This PR closes an issue where the theme interface for the carousel slide was not being exported. Additionally, the slide interface was also not being exported. This PR also **renames** both interfaces with a namespace to the component to ensure that there aren't future long term conflicts with generic/global names. *Since neither of these interfaces were exported, I am not considering it a breaking change to rename them.*
=> fix: export carousel slide theme and carousel slide interfaces

packages/fast-tooling-react/src/css-property-editor/property-editor.spec.tsx, packages/fast-tooling-react/src/css-property-editor/property-editor.utilities.ts
Fixes an issue where deleting a value in the CSS property editor will cause a runtime error.
=> fix: allow undefined values for properties in the CSS property editor

packages/fast-components-react-msft/src/carousel/carousel.spec.tsx, packages/fast-components-react-msft/src/carousel/carousel.tsx
=> fix: add lifecycle hook to update carousel activeId when props change

packages/fast-components-styles-msft/src/button/index.ts
Closes [#1715](https://github.com/microsoft/fast-dna/issues/1715)
Updates button style to support ms-high-contrast.
=> fix: update button style to support ms-high-contrast

packages/fast-components-class-name-contracts-base/src/index.ts, packages/fast-components-class-name-contracts-base/src/viewport-positioner/index.ts, packages/fast-components-react-base/app/examples.ts, packages/fast-components-react-base/src/viewport-positioner/README.md, packages/fast-components-react-base/src/viewport-positioner/examples.data.tsx, packages/fast-components-react-base/src/viewport-positioner/index.ts, packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.props.ts, packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.schema.json, packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.spec.tsx, packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.tsx
Viewport positioner is a container that positions itself relative to another html element "anchor" while taking into account available space in a parent viewport.  This container enables menus that flip to avoid the edge of the viewport, flyouts, etc... 
=> feat: add viewport positioner component

packages/fast-development-site-react/app/app.tsx, packages/fast-development-site-react/package.json, packages/fast-development-site-react/src/components/site/category-item.tsx, packages/fast-development-site-react/src/components/site/index.tsx
Solves an issue where the props being updated by an injected design system would cause the internal state of the data to change. Since this is not intended to ever be updated during the viewing of the dev site this has been removed.
Resolves #1837
=> fix: remove an issue where the design system would cause component data to be reset

packages/fast-components-react-msft/app/app.tsx
Design system was not updating properly because we had our directions mixed up in the MSFT app.
=> chore: designSystem localization not set properly in msft app

.github/pull_request_template.md, CNAME, CONTRIBUTING.md, README.md, packages/fast-animation/README.md, website/core/Footer.js, website/i18n/en.json, website/siteConfig.js
Updates to use custom domain name https://www.fast.design instead of https://microsoft.github.io/fast-dna for documentation site.
Note: Formatting was not done by me.  That seems to have been done by docusaurus autogenerating during compilation.
* fixes all links
* adds cname file for new custom domain
* updates docusaurus config files
=> chore: update to switch to custom domain name for documentation

packages/fast-components-react-msft/src/action-toggle/action-toggle.tsx, packages/fast-components-react-msft/src/action-toggle/examples.data.tsx, packages/fast-components-react-msft/src/auto-suggest-option/auto-suggest-option.tsx
`isNullOrUndefined` has been deprecated and is being imported from node.
I imported `isNil` from lodash to replace `isNullOrUndefined`
=> chore: replaced import `isNullOrUndefined` with `isNil`

packages/fast-components-styles-msft/src/button/index.ts, packages/fast-components-styles-msft/src/select/index.ts
=> fix: remove incorrect min-width values from select and button components

packages/fast-components-class-name-contracts-msft/src/button-base/index.ts, packages/fast-components-react-msft/src/button-base/button-base.spec.tsx, packages/fast-components-react-msft/src/button-base/button-base.tsx
Previously this logic only existed in derivatives of the button component, however it technically is valid for button scenarios as well. This PR adds the logic to button so we do not need to duplicate it in the derivatives.
=> feat: add classname to MSFT button for when either before or after content and children exist

packages/fast-colors/src/color-blending.ts
New color utility function.
Part of the color algorithm update.
=> feat: add "color" blend mode

packages/fast-components-react-msft/src/background/background.props.ts, packages/fast-components-react-msft/src/background/background.spec.tsx, packages/fast-components-react-msft/src/background/background.tsx
Adds design-system merging function to background component so that a custom merging function can be supplied to the rendered design system.
The `DesignSystemProvider` exposes the ability to provide a custom merging function. The background component is essentially a fancy `DesignSystemProvider` so it should also have this ability.
=> feat: add design system merging function to background component

packages/fast-tooling-react/README.md, packages/fast-tooling-react/app/app.tsx, packages/fast-tooling-react/app/pages/navigation-menu.tsx, packages/fast-tooling-react/src/index.ts, packages/fast-tooling-react/src/navigation-menu/index.ts, packages/fast-tooling-react/src/navigation-menu/navigation-menu-item.props.ts, packages/fast-tooling-react/src/navigation-menu/navigation-menu-item.tsx, packages/fast-tooling-react/src/navigation-menu/navigation-menu.props.ts, packages/fast-tooling-react/src/navigation-menu/navigation-menu.spec.tsx, packages/fast-tooling-react/src/navigation-menu/navigation-menu.style.ts, packages/fast-tooling-react/src/navigation-menu/navigation-menu.tsx
Adds a navigation menu component to the @microsoft/fast-tooling-react package.
Resolves #1829
=> feat: add a navigation menu

packages/fast-tooling-react/src/form/form/form.tsx, packages/fast-tooling-react/src/form/utilities/form.tsx
A performance improvement due to only checking for a modified schema when the onSchemaChange callback has been passed.
=> fix: only check for a modified schema when the onSchemaChange callback is expected to be called

packages/fast-tooling-react/src/data-utilities/mapping.ts
Improves a perf issue that can occur when neither child options or plugins are passed yet both location mapping functions are used against the schema.
=> fix: check to see if any child options or plugins have been passed before attempting to map their locations

packages/fast-components-react-msft/src/text-action/index.ts
Exports missing contract from bundle
fixes #1895 
=> fix: export Text Action class name contract

packages/fast-tooling-react/src/css-editor/editor.style.ts, packages/fast-tooling-react/src/css-property-editor/property-editor.style.ts, packages/fast-tooling-react/src/form/align/align.style.ts, packages/fast-tooling-react/src/form/form/form.style.ts, packages/fast-tooling-react/src/form/text-align/text-align.style.ts, packages/fast-tooling-react/src/navigation-menu/navigation-menu.style.ts, packages/fast-tooling-react/src/navigation/navigation.style.ts, packages/fast-tooling-react/src/style/constants.ts, packages/fast-tooling-react/src/style/utilities.ts
Adds a line down the side of navigation items to align visually more closely with other Microsoft development tools.
=> feat: add hierarchical lines to the Navigation component UI

packages/fast-tooling-react/src/navigation/navigation-tree-item.props.ts, packages/fast-tooling-react/src/navigation/navigation-tree-item.tsx, packages/fast-tooling-react/src/navigation/navigation.style.ts, packages/fast-tooling-react/src/navigation/navigation.tsx
Changes a children item to use a grab and grabbing cursor when dragging.
=> feat: add grab hand when hovering a draggable item

packages/fast-tooling-react/src/navigation/navigation.tsx
Additional cleanup after the removal of unnecessary aria attributes.
=> chore: cleanup redundant position in set

packages/fast-tooling-react/src/navigation/navigation.tsx
Updates sorting behavior to respect drag and drop positioning.
=> fix: refine sorting behavior to be more precise when dealing with items that are not children items

packages/fast-components-styles-msft/src/breadcrumb/index.ts, packages/fast-components-styles-msft/src/card/index.ts, packages/fast-components-styles-msft/src/checkbox/index.ts, packages/fast-components-styles-msft/src/context-menu-item/index.ts, packages/fast-components-styles-msft/src/flipper/index.ts, packages/fast-components-styles-msft/src/hypertext/index.ts, packages/fast-components-styles-msft/src/pivot/index.ts, packages/fast-components-styles-msft/src/radio/index.ts, packages/fast-components-styles-msft/src/select/index.ts, packages/fast-components-styles-msft/src/toggle/index.ts
Fixed underline on breadcrumb link hover.
Updated card corner radius to elevated.
Fixed cursors for checkbox, radio button, context menu, pivot, select, and toggle.
Updated toggle to use modern style sheet syntax.
Noticed a few cursors that weren’t correct during a recent review.
=> fix: component style and cursor fixes

packages/fast-development-site-react/README.md
Deprecates the `@microsoft/fast-development-site-react` as we have moved to storybook and have no plans of updating this package.
See #1902 for details.
=> feat: deprecate the development site

packages/fast-components-react-msft/src/carousel/carousel.props.ts, packages/fast-components-react-msft/src/carousel/carousel.spec.tsx, packages/fast-components-react-msft/src/carousel/carousel.tsx
=> feat: add callback for when carousel active id changes

packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.spec.tsx, packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.tsx
Ensures that unhandled props do not override pre-existing attributes and merges style properties on the component.
=> fix: ensure unhandled props are passed first and merge with existing style properties

packages/fast-components-react-base/src/slider/slider.schema.ts, packages/fast-components-react-msft/src/slider/slider.schema.ts, packages/fast-components-react-msft/src/subheading/subheading.schema.ts
Schemas are wrong for `<Slider/>` in msft and base packages and `<Subheading/>` in msft package.
=> fix: slider & subheading schemas are incorrect

packages/fast-components-react-msft/src/carousel/carousel.props.ts, packages/fast-components-react-msft/src/carousel/carousel.spec.tsx, packages/fast-components-react-msft/src/carousel/carousel.stories.tsx, packages/fast-components-react-msft/src/carousel/carousel.tsx
=> feat: add flag to carousel onActiveIdUpdate to denote if the update was initiated by autoplay

packages/fast-component-explorer/app/explorer.props.ts, packages/fast-component-explorer/app/explorer.style.ts, packages/fast-component-explorer/app/explorer.tsx, packages/fast-component-explorer/app/preview.style.ts, packages/fast-component-explorer/app/preview.tsx, packages/fast-component-explorer/package.json
Update preview controls to use MSFT components, add toggle for theme switching and move controls to right side of canvas.
Closes: #1934
Closes: #1935 
=> feat: add theme switching & move preview controls

packages/fast-layouts-react/package.json, packages/fast-layouts-react/src/pane/pane.tsx
=> feat: add support to resize pane using left/right arrow keys

packages/fast-components-class-name-contracts-msft/src/flyout/index.ts, packages/fast-components-class-name-contracts-msft/src/index.ts, packages/fast-components-react-msft/src/flyout/README.md, packages/fast-components-react-msft/src/flyout/flyout.props.ts, packages/fast-components-react-msft/src/flyout/flyout.schema.ts, packages/fast-components-react-msft/src/flyout/flyout.spec.tsx, packages/fast-components-react-msft/src/flyout/flyout.stories.tsx, packages/fast-components-react-msft/src/flyout/flyout.tsx, packages/fast-components-react-msft/src/flyout/index.ts, packages/fast-components-styles-msft/src/flyout/index.ts, packages/fast-components-styles-msft/src/index.ts
Adds a new styled component “flyout” to the MSFT package.
=> feat: add flyout as a new component

packages/fast-layouts-react/src/pane/pane.props.ts, packages/fast-layouts-react/src/pane/pane.tsx
=> feat: add onResize callback to Pane

packages/fast-layouts-react/src/row/row.props.ts, packages/fast-layouts-react/src/row/row.tsx
Adds the ability to resize the row via keyboard arrow (up/down) and provides an onResize callback.
=> feat: add support to resize via keyboard and provide an onResize callback

packages/fast-tooling-react/app/configs/example.data.ts, packages/fast-tooling-react/app/pages/navigation.tsx, packages/fast-tooling-react/app/pages/navigation/children.schema.json, packages/fast-tooling-react/app/pages/navigation/example.data.ts, packages/fast-tooling-react/src/navigation/navigation-tree-item.props.ts, packages/fast-tooling-react/src/navigation/navigation-tree-item.tsx, packages/fast-tooling-react/src/navigation/navigation.props.ts, packages/fast-tooling-react/src/navigation/navigation.style.ts, packages/fast-tooling-react/src/navigation/navigation.tsx, packages/fast-tooling-react/src/navigation/navigation.utilities.spec.ts, packages/fast-tooling-react/src/navigation/navigation.utilities.ts
This allows children to be dropped onto other components in the default react location for children.
Resolves #1938
Resolves #1979
=> fix: add drag and drop of components to their direct children

packages/fast-component-explorer/app/explorer.style.ts, packages/fast-component-explorer/app/explorer.tsx, packages/fast-component-explorer/package.json
Added accent color picker to explorer site.
Closes: #1936 
Allows users to change accent color
=> feat: add accent color picker to explorer site

packages/fast-tooling-react/src/data-utilities/location.ts
=> fix: correcting missing data-location reference

packages/fast-component-explorer/app/utilities/configs/progress.ts, packages/fast-components-class-name-contracts-msft/src/progress/index.ts, packages/fast-components-react-msft/package.json, packages/fast-components-react-msft/src/progress/README.md, packages/fast-components-react-msft/src/progress/progress.props.ts, packages/fast-components-react-msft/src/progress/progress.schema.ts, packages/fast-components-react-msft/src/progress/progress.spec.tsx, packages/fast-components-react-msft/src/progress/progress.stories.tsx, packages/fast-components-react-msft/src/progress/progress.tsx, packages/fast-components-styles-msft/src/progress/index.ts
Add circular progress to MSFT `<progress/>` component.
Closes: #1130 
Indeterminate:
Determinate:
=> feat: add circular progress component

packages/fast-tooling-react/src/viewer/select-device/select-device.style.ts
A style update for the `SelectDevice` component to add padding for the dropdown arrow.
=> fix: adjust spacing on SelectDevice dropdown for the dropdown arrow

packages/fast-component-explorer/app/app.tsx, packages/fast-component-explorer/app/explorer.style.ts, packages/fast-component-explorer/app/explorer.tsx
Styling updates to match designs.
=> feat: style the explorer site

packages/fast-component-explorer/app/explorer.tsx, packages/fast-component-explorer/app/utilities/configs/carousel.ts
Fix some naming issues and a redundant wrapper.
=> chore: fix some incorrect naming and a redundant wrapper

packages/fast-tooling-react/src/css-editor/color/color.props.ts, packages/fast-tooling-react/src/css-editor/color/color.schema.json, packages/fast-tooling-react/src/css-editor/color/color.spec.tsx, packages/fast-tooling-react/src/css-editor/color/color.style.ts, packages/fast-tooling-react/src/css-editor/color/color.tsx, packages/fast-tooling-react/src/css-editor/color/index.ts, packages/fast-tooling-react/src/css-editor/editor.props.ts, packages/fast-tooling-react/src/css-editor/editor.tsx
Add a css color picker into tooling
=> feat: add css color picker

packages/fast-component-explorer/package.json, packages/fast-component-explorer/webpack.config.js
Adds focus-visible pollyfill to component explorer.
=> chore: wire up focus-visible to component explorer

packages/fast-tooling-react/app/pages/css-editor.tsx, packages/fast-tooling-react/src/css-editor/border/border.props.ts, packages/fast-tooling-react/src/css-editor/border/border.schema.json, packages/fast-tooling-react/src/css-editor/border/border.spec.tsx, packages/fast-tooling-react/src/css-editor/border/border.style.ts, packages/fast-tooling-react/src/css-editor/border/border.tsx, packages/fast-tooling-react/src/css-editor/border/index.ts, packages/fast-tooling-react/src/css-editor/editor.props.ts, packages/fast-tooling-react/src/css-editor/editor.tsx
=> feat: add css border component

packages/fast-tooling-react/package.json, packages/fast-tooling-react/src/css-editor/box-shadow/box-shadow.props.tsx, packages/fast-tooling-react/src/css-editor/box-shadow/box-shadow.schema.json, packages/fast-tooling-react/src/css-editor/box-shadow/box-shadow.style.ts, packages/fast-tooling-react/src/css-editor/box-shadow/box-shadow.tsx, packages/fast-tooling-react/src/css-editor/box-shadow/index.ts, packages/fast-tooling-react/src/css-editor/color/color.style.ts, packages/fast-tooling-react/src/css-editor/color/color.tsx, packages/fast-tooling-react/src/css-editor/editor.props.ts, packages/fast-tooling-react/src/css-editor/editor.tsx
follow up task for string manipulation: #2055 
Add css box shadow component
=> feat: add css boxShadow

packages/fast-tooling-react/src/css-editor/height/height.style.ts, packages/fast-tooling-react/src/css-editor/width/width.style.ts
Made `<CSSWidth/>` and `<CSSHeight/>` width dynamic.
=> fix: width and height styles

packages/fast-tooling-react/app/app.tsx, packages/fast-tooling-react/app/pages/style-editors.tsx
This is a test page for the tooling to show both the CSS editor and CSS property editor in tandem during testing.
=> chore: add a test page for both CSS editor and CSS property editor to test in tandem

packages/fast-tooling-react/src/css-editor/border/border.props.ts, packages/fast-tooling-react/src/css-editor/border/border.spec.tsx, packages/fast-tooling-react/src/css-editor/border/border.tsx, packages/fast-tooling-react/src/css-editor/box-shadow/box-shadow.style.ts, packages/fast-tooling-react/src/css-editor/box-shadow/box-shadow.tsx, packages/fast-tooling-react/src/css-editor/color/color.spec.tsx, packages/fast-tooling-react/src/css-editor/color/color.tsx, packages/fast-tooling-react/src/css-editor/editor.props.ts, packages/fast-tooling-react/src/css-editor/editor.spec.tsx, packages/fast-tooling-react/src/css-editor/editor.tsx, packages/fast-tooling-react/src/css-editor/position/position.tsx
Fixed:
Removing css property values should remove css from editor.
Removing css property name should remove css from edtior.
Removing css property from editor should update css controls.
Fixed tests
=> fix: css editor functionality

packages/fast-components-react-msft/src/paragraph/paragraph.schema.ts
=> fix: reduce text in paragraph schema

packages/fast-tooling-react/src/css-property-editor/property-editor.tsx
Adding a single property then removing it from the css controls does not remove it from the css property editor.
=> fix: css data gets out of sync

packages/fast-tooling-react/src/css-editor/box-shadow/box-shadow.style.ts
=> fix: correct alignment and remove pointer events from % unit

packages/fast-tooling-react/package.json, packages/fast-tooling-react/src/navigation/navigation-tree-item.props.ts, packages/fast-tooling-react/src/navigation/navigation-tree-item.tsx, packages/fast-tooling-react/src/navigation/navigation.spec.tsx, packages/fast-tooling-react/src/navigation/navigation.style.ts, packages/fast-tooling-react/src/navigation/navigation.tsx, packages/fast-tooling-react/webpack.config.js
Updates to make the expand different from the selection of an item in Navigation and updates it to the new design.
Resolves #2046
=> feat: change Navigation selection UX and update UI to new design guidance

packages/fast-tooling-react/src/css-editor/background/background.props.ts, packages/fast-tooling-react/src/css-editor/background/background.schema.json, packages/fast-tooling-react/src/css-editor/background/background.spec.tsx, packages/fast-tooling-react/src/css-editor/background/background.style.ts, packages/fast-tooling-react/src/css-editor/background/background.tsx, packages/fast-tooling-react/src/css-editor/background/index.ts, packages/fast-tooling-react/src/css-editor/border/border.props.ts, packages/fast-tooling-react/src/css-editor/border/border.tsx, packages/fast-tooling-react/src/css-editor/color/color.spec.tsx, packages/fast-tooling-react/src/css-editor/color/color.tsx, packages/fast-tooling-react/src/css-editor/editor.props.ts, packages/fast-tooling-react/src/css-editor/editor.tsx
Added CSS background component,
Removed default selections for components
Closes: #2070 , Closes: #2071 
=> feat: add css Background, fix default border style

packages/fast-component-explorer/app/explorer.tsx
changed the background on the viewer from `#111111` to `#333333`
closes #2038 
=> chore: update viewer background color in dark theme

packages/fast-component-explorer/app/explorer.style.ts, packages/fast-component-explorer/app/explorer.tsx, packages/fast-component-explorer/app/preview.style.ts
- created `applyScrollbarStyle` function to explorer.style and add them to navigation, properties, viewer pane.
- update format function
=> chore: update scrollbar style in component explorer

packages/fast-tooling-react/app/pages/form-and-navigation.tsx, packages/fast-tooling-react/src/navigation/navigation.props.ts, packages/fast-tooling-react/src/navigation/navigation.tsx, packages/fast-tooling-react/src/navigation/navigation.utilities.ts
During duplication an object may be converted to an array, this means that there should be an included argument to update the data location.
=> fix: address an issue in controlled state where Navigation should pass an updated data location

packages/fast-component-explorer/app/config.ts, packages/fast-component-explorer/app/explorer.tsx
Removes the root level navigation item in the Component Explorer 'components' and flattens the navigation menu.
Resolves #2034 
=> chore: remove root level 'components' tree item and flatten tree item navigation menu

packages/fast-components-react-msft/src/index.ts
=> fix: export flyout from package root

packages/fast-component-explorer/app/explorer.style.ts
Add variable font to component explorer.
=> chore: implement variable fonts

packages/fast-web-utilities/package.json
Establishes that `@microsoft/fast-web-utilities` has no side effects so that Webpack can tree shake the package.
=> fix: establish no side effects in fast-web-utilities

packages/fast-components-react-base/src/index.ts, packages/fast-components-react-base/src/utilities/index.ts
<!--- Provide a summary of your changes in the title field above. For guidance on formatting, see the # Description
Added support code for intersection observer and resize observer to the package exports.
Need to use observers in other packages.
=> fix: export observer support code from base package

packages/fast-component-explorer/app/utilities/configs/accent-button.ts, packages/fast-component-explorer/app/utilities/configs/index.ts, packages/fast-component-explorer/app/utilities/configs/lightweight-button.ts, packages/fast-component-explorer/app/utilities/configs/neutral-button.ts, packages/fast-component-explorer/app/utilities/configs/outline-button.ts, packages/fast-component-explorer/app/utilities/configs/stealth-button.ts
Closes [#2084 ](https://github.com/microsoft/fast-dna/issues/2084)
Adds button examples to explorer.
=> chore: adds other button examples to explorer

packages/fast-components-react-msft/src/progress/index.ts
`ProgressSize` was not exported.
=> chore: ProgressSize was not exported

packages/fast-animation/lib/animateGroup/index.ts
AnimateGroup uses the `onFinish` callback of the longest animation to determine when the group is done animating. `AnimateGroup` would override the existing `onFinish` callback on the animation if it existed. This change ensures that the `AnimateTo` or `AnimateFrom` instance's `onFinish` callback gets called if it exists.
=> fix: ensure all animation onFinish callbacks are called when used with an AnimateGroup

packages/fast-components-react-msft/src/index.ts, packages/fast-components-styles-msft/src/utilities/color/accent-fill.spec.ts, packages/fast-components-styles-msft/src/utilities/color/accent-fill.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground.spec.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/color-constants.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-divider.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-card.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-focus.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground-hint.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground-hint.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-layer.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-outline.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-outline.ts, packages/fast-components-styles-msft/src/utilities/color/palette.spec.ts, packages/fast-components-styles-msft/src/utilities/color/palette.ts
Removes references to some redundant code that we have better abstractions for. Deprecates said code.
=> feat: remove references to unnecessary code

packages/fast-colors/src/parse-color.ts
Deprecate `namedColors`. `parseColorNamed` should be used instead to access `ColorRGBA64` instances of named colors.
=> fix: add deprecation notice to namedColors export

packages/fast-component-explorer/app/explorer-region.tsx, packages/fast-component-explorer/app/explorer.props.ts, packages/fast-component-explorer/app/explorer.style.ts, packages/fast-component-explorer/app/explorer.tsx, packages/fast-component-explorer/app/icons/chevrons.tsx, packages/fast-component-explorer/app/preview.style.ts, packages/fast-components-react-msft/src/progress/index.ts
Styling improvements to component explorer.
=> chore: style improvements to component explorer

packages/fast-component-explorer/app/config.ts
The initial route is wrong so site appears to be broken.
=> fix: broken initial route

packages/fast-component-explorer/app/explorer.style.ts, packages/fast-component-explorer/app/explorer.tsx
1. Moved scenario select to be left aligned.
2. Added logic so iFrame / Viewer fills available area.
=> chore: update styling of explorer site

packages/fast-component-explorer/app/explorer.tsx
Enable active state on Navigation Menu
=> chore: enable active location

packages/fast-components-react-msft/src/progress/progress.props.ts, packages/fast-components-react-msft/src/progress/progress.spec.tsx
=> fix: ensure unhandled props are correctly extended for progress component

packages/fast-component-explorer/app/explorer.tsx
Closes: #2145
Background of iFrame was not theming:
Before:
After:
=> chore: background of iframe does not respect theme

packages/fast-components-react-base/src/select/select.spec.tsx, packages/fast-components-react-base/src/select/select.tsx
=> feat: support navigating select options using arrow keys without opening menu

packages/fast-components-react-msft/src/carousel/carousel.props.ts, packages/fast-components-react-msft/src/carousel/carousel.spec.tsx, packages/fast-components-react-msft/src/carousel/carousel.tsx
=> feat: support custom flippers being passed into carousel

packages/fast-components-react-base/src/radio/radio.props.ts
Radio unhandled props currently extends all HTML attributes. This is actually incorrect and creates issues when certain attributes are passed to a Div which are not supported by the Div element. This corrects the typing.
=> fix: correct typing of radio unhandled props

packages/fast-jss-manager-react/README.md, packages/fast-jss-manager-react/src/index.ts, packages/fast-jss-manager-react/src/jss-manager.spec.tsx, packages/fast-jss-manager-react/src/jss-manager.tsx, packages/fast-jss-manager-react/src/sheet-manager.ts
Allow asigning a custom JSS object for stylesheet generation with the JSSManager.
=> feat: make the jss instance of the JSSManager configurable

packages/fast-component-explorer/package.json, packages/fast-jss-manager-react/src/jss.ts
Make change to force an update
=> fix: force an update to jss-manger for publishing

packages/fast-tooling-react/package.json, packages/fast-tooling-react/src/css-editor/border-radius/border-radius.props.ts, packages/fast-tooling-react/src/css-editor/border-radius/border-radius.schema.json, packages/fast-tooling-react/src/css-editor/border-radius/border-radius.spec.tsx, packages/fast-tooling-react/src/css-editor/border-radius/border-radius.style.ts, packages/fast-tooling-react/src/css-editor/border-radius/border-radius.tsx, packages/fast-tooling-react/src/css-editor/border-radius/index.ts, packages/fast-tooling-react/src/css-editor/editor.props.ts, packages/fast-tooling-react/src/css-editor/editor.tsx, packages/fast-tooling-react/src/utilities/parse-css-string.spec.ts, packages/fast-tooling-react/src/utilities/parse-css-string.ts
adds css Border radius component.
=> feat: add css border radius component

packages/fast-components-styles-msft/src/dialog/index.ts
Updated modal dialog background to simple opacity dark mask.
Aligning with the visual direction of related teams and responding to feedback regarding contrast in dark mode.
=> feat: update modal dialog background to simple opacity dark mask

packages/fast-jss-manager-react/README.md, packages/fast-jss-manager-react/src/index.ts, packages/fast-jss-manager-react/src/jss-manager.spec.tsx, packages/fast-jss-manager-react/src/jss-manager.tsx, packages/fast-jss-manager-react/src/sheet-manager.ts
Adds to the ability to configure the JSS instance used by the JSSmanager.
Enables adding / removing plugins and supplying alternative JSS versions to be used by the JSSmanager.
=> feat: support custom jss instance

packages/fast-components-styles-msft/src/button/index.ts, packages/fast-components-styles-msft/src/design-system/index.ts, packages/fast-components-styles-msft/src/flyout/index.ts, packages/fast-components-styles-msft/src/heading/index.ts, packages/fast-components-styles-msft/src/outline-button/index.ts, packages/fast-components-styles-msft/src/patterns/button.ts, packages/fast-components-styles-msft/src/select/index.ts, packages/fast-components-styles-msft/src/subheading/index.ts, packages/fast-components-styles-msft/src/utilities/color/common.ts, packages/fast-components-styles-msft/src/utilities/density.ts, packages/fast-components-styles-msft/src/utilities/design-system.spec.ts, packages/fast-components-styles-msft/src/utilities/design-system.ts, packages/fast-components-styles-msft/src/utilities/fonts.ts, packages/fast-components-styles-msft/src/utilities/typography.ts, packages/fast-jss-utilities/src/acrylic.ts, packages/fast-web-utilities/src/dom.ts
Adjusts stylesheets to be more performant.
=> fix: various performance improvements to stylesheets

packages/fast-colors/src/color-converters.ts, packages/fast-colors/src/color-rgba-64.ts, packages/fast-colors/src/named-colors.ts, packages/fast-colors/src/parse-color.ts
BREAKING CHANGE: removes named color exports.
Use `parseColor` to retrieve a `ColorRGBA64` instance of a named color.
Bundle minification
=> feat: remove ColorRGBA64 instance exports

packages/fast-components-styles-msft/src/stealth-button/index.ts
=> fix: correct incorrectly named className contract for stealth button

packages/fast-components-styles-msft/src/context-menu-item/index.ts
converts camelCase name to dash-case
=> fix: fix camelCase style in context-menu-item

packages/fast-components-react-base/src/checkbox/checkbox.props.ts, packages/fast-components-react-base/src/checkbox/checkbox.schema.ts, packages/fast-components-react-base/src/checkbox/checkbox.spec.tsx, packages/fast-components-react-base/src/checkbox/checkbox.stories.tsx, packages/fast-components-react-base/src/checkbox/checkbox.tsx, packages/fast-components-react-msft/src/checkbox/checkbox.schema.ts, packages/fast-components-react-msft/src/checkbox/checkbox.stories.tsx
=> feat: add label prop to replace slots in checkbox

packages/fast-components-react-base/src/checkbox/checkbox.tsx
=> fix: check classNames for checkbox state indicator and input using utility

packages/fast-jss-utilities/src/max-lines.ts
Max-lines applies dash-case properties.
=> fix: converting max-lines to dash case

packages/fast-jss-utilities/src/acrylic.ts
=> fix: add webkit prefixed backdrop filter property in acrylic utility

packages/fast-components-react-base/src/radio/radio.props.ts, packages/fast-components-react-base/src/radio/radio.schema.ts, packages/fast-components-react-base/src/radio/radio.spec.tsx, packages/fast-components-react-base/src/radio/radio.stories.tsx, packages/fast-components-react-base/src/radio/radio.tsx, packages/fast-components-react-msft/src/radio/radio.schema.ts, packages/fast-components-react-msft/src/radio/radio.stories.tsx
=> feat: add render prop for label instead of slot in radio

packages/fast-jss-manager-react/README.md
=> fix: Updating README for managed-jss-react to remove typo

packages/fast-layouts-react/src/pane/pane.tsx, packages/fast-layouts-react/src/row/row.tsx
Added `role="seprator"` removed `aria-hidden`
Closes: #2175 
=> fix: separator announced as button

packages/fast-components-class-name-contracts-msft/src/progress/index.ts, packages/fast-components-react-msft/src/progress/progress.props.ts, packages/fast-components-react-msft/src/progress/progress.schema.ts, packages/fast-components-react-msft/src/progress/progress.spec.tsx, packages/fast-components-react-msft/src/progress/progress.tsx, packages/fast-components-styles-msft/src/progress/index.ts
Add pause prop to `<Progress/>` component.
Closes: #2192 2192
Indeterminate:
Indeterminate Circular:
Determinate:
Determinate Circular:
=> fix: add paused state to progress

packages/fast-color-explorer/app/color-blocks.tsx, packages/fast-color-explorer/app/gradient.tsx, packages/fast-color-explorer/app/service-worker-registration.ts, packages/fast-color-explorer/app/state.ts, packages/fast-color-explorer/app/swatch.tsx, packages/fast-color-explorer/package.json
=> chore: fix prettier config path in color explorer

packages/fast-jss-utilities/src/acrylic.ts
=> fix: check for DOM in backdropFilterSupport prior to accessing document properties

packages/fast-web-utilities/src/dom.ts
=> fix: exit focus visible utility immediately with false value if DOM is unavailable

packages/fast-layouts-react/src/grid/grid.tsx, packages/fast-layouts-react/src/page/page.tsx
=> fix: add prefix for ms-grid in fast-layouts-react page and grid components

packages/fast-storybook-design-system-addon/package.json, packages/fast-storybook-design-system-addon/src/index.tsx, packages/fast-storybook-presets/package.json
=> fix: fixes issues caused by updating storybook

packages/fast-component-explorer/app/explorer.props.ts, packages/fast-component-explorer/app/explorer.tsx, packages/fast-component-explorer/app/utilities/configs/accent-button.ts, packages/fast-component-explorer/app/utilities/configs/auto-suggest-option.ts, packages/fast-component-explorer/app/utilities/configs/badge.ts, packages/fast-component-explorer/app/utilities/configs/button.ts, packages/fast-component-explorer/app/utilities/configs/caption.ts, packages/fast-component-explorer/app/utilities/configs/context-menu-item.ts, packages/fast-component-explorer/app/utilities/configs/heading.ts, packages/fast-component-explorer/app/utilities/configs/label.ts, packages/fast-component-explorer/app/utilities/configs/lightweight-button.ts, packages/fast-component-explorer/app/utilities/configs/metatext.ts, packages/fast-component-explorer/app/utilities/configs/neutral-button.ts, packages/fast-component-explorer/app/utilities/configs/outline-button.ts, packages/fast-component-explorer/app/utilities/configs/paragraph.ts, packages/fast-component-explorer/app/utilities/configs/select-option.ts, packages/fast-component-explorer/app/utilities/configs/stealth-button.ts, packages/fast-component-explorer/app/utilities/configs/subheading.ts
1. Added functionality to set the scenario to custom when props in config panel are changed
2. Updated scenario data to not include language related to state
Closes: #2206 
Closes: #2207 
=> feat: set scenario to custom / update scenarios

packages/fast-components-styles-msft/src/utilities/color/palette.ts
This changes a linear search to use a binary search.
This should increase performance when doing contrast checking.
=> fix: use binary search as a lookup in swatchByContrast utility

packages/fast-color-explorer/app/color-blocks.tsx, packages/fast-components-styles-msft/src/design-system/index.ts, packages/fast-components-styles-msft/src/utilities/color/accessible-recipe.ts, packages/fast-components-styles-msft/src/utilities/color/index.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-toggle.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground-hint.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground-toggle.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/palette.ts, packages/fast-components-styles-msft/src/utilities/color/recipe.ts, packages/fast-components-styles-msft/src/utilities/design-system.ts
Adds a new fill recipe to be used for toggled or selected state of input controls like checkboxes, radio buttons, and toggle switches.
The current implementation of these controls uses more of an outlined style in selected and unselected states. There has been some feedback and discussion about making the states more distinct. This new fill recipe opens the path for a soon-to-be-updated set of input controls that uses a more bold fill color on selected state.
The updates in the color explorer are temporary to illustrate and test the new colors, and will be rolled into the main components in another PR.
This also cleans up some code in other recipes that use contrast and deltas to determine swatch colors. I would like to apply this to accent color based recipes in the future, so looking …
=> feat: added input toggle fill recipe.

packages/fast-components-styles-msft/src/slider/index.ts, packages/fast-components-styles-msft/src/utilities/border.ts
Updated slider thumb size to be slightly smaller, fitting better with the rest of the components.
Request from partner team, and consideration already in process as part of making the controls more cohesive.
=> feat: update slider thumb size

.github/CODEOWNERS
Added Nick as a code owner to `fast-components-*`. I think he deserves it. ;)
Would be good to have more owners to unblock when people are out or busy.
=> chore: add Nick as a code owner for components packages

packages/fast-components-styles-msft/src/design-system/design-system.schema.ts, packages/fast-components-styles-msft/src/design-system/index.ts, packages/fast-components-styles-msft/src/utilities/color/accent-fill.ts, packages/fast-components-styles-msft/src/utilities/color/accent-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/accessible-recipe.ts, packages/fast-components-styles-msft/src/utilities/color/common.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-toggle.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground-hint.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-outline.spec.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-outline.ts, packages/fast-components-styles-msft/src/utilities/design-system.ts
Added focus states to color recipes. Will hook these up to components in another round.
The default design system will likely not have offsets that produce visual differences for this state, but adding it to complete the options and provide the ability to replicate more OS and design styles, including Windows 10.
=> feat: add focus states to color recipes

packages/fast-components-styles-msft/src/toggle/index.ts
Adds RTL styles for state indicator of toggle.
fixes #2251
=> fix: adds proper RTL styles for toggle state indicator

packages/fast-storybook-design-system-addon/src/panel.tsx
Corrects selector to apply custom BG to - storybook update removed the selector we were targeting.
=> fix: storybook background not displaying correctly

packages/fast-tooling-react/src/form/custom-controls/control.align.props.ts, packages/fast-tooling-react/src/form/custom-controls/control.align.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/control.align.style.ts, packages/fast-tooling-react/src/form/custom-controls/control.align.tsx, packages/fast-tooling-react/src/form/custom-controls/control.file-upload.props.ts, packages/fast-tooling-react/src/form/custom-controls/control.file-upload.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/control.file-upload.style.ts, packages/fast-tooling-react/src/form/custom-controls/control.file-upload.tsx, packages/fast-tooling-react/src/form/custom-controls/control.text-align.props.ts, packages/fast-tooling-react/src/form/custom-controls/control.text-align.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/control.text-align.style.ts, packages/fast-tooling-react/src/form/custom-controls/control.text-align.tsx, packages/fast-tooling-react/src/form/custom-controls/control.theme.props.ts, packages/fast-tooling-react/src/form/custom-controls/control.theme.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/control.theme.style.ts, packages/fast-tooling-react/src/form/custom-controls/control.theme.tsx, packages/fast-tooling-react/src/form/custom-controls/index.ts
This updates some custom form controls to be able to be injected to the plugin system.
As a preliminary step in the conversion of controls to use a plugin system, this change converts some un-used custom form controls to be usable with the new plugin system. At a later time when the plugin system is fully implemented these will be exported and documented as controls that may be injected into the form.
Related to #551
=> chore: update custom form controls to use new template and plugin system

packages/fast-tooling-react/src/form/utilities/form.tsx
Performance work done in a previous PR changed a check of a schema to see whether the schema had any modifications when new props are passed by just checking the schemas ID. This change will simply check to see if the schema is different via pointer, regardless of whether the ID is the same.
This is still a performant solution, if a schema is updated the implementer will need to do something like use the spread operator, making sure to create a new object so that the newly updated schema has registered and updates are done accordingly.
Closes #2286 
=> fix: check for different schemas by reference

packages/fast-tooling-react/README.md, packages/fast-tooling-react/app/pages/form.tsx, packages/fast-tooling-react/app/pages/form/index.ts, packages/fast-tooling-react/src/__tests__/schemas/control-plugin.schema.json, packages/fast-tooling-react/src/form/controls/control.number-field.props.ts, packages/fast-tooling-react/src/form/controls/control.section-link.props.ts, packages/fast-tooling-react/src/form/controls/control.textarea.props.ts, packages/fast-tooling-react/src/form/custom-controls/control.file-upload.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/control.theme.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/index.ts, packages/fast-tooling-react/src/form/form-control-switch.props.ts, packages/fast-tooling-react/src/form/form-control-switch.spec.tsx, packages/fast-tooling-react/src/form/form-control-switch.tsx, packages/fast-tooling-react/src/form/form-dictionary.props.ts, packages/fast-tooling-react/src/form/form-dictionary.tsx, packages/fast-tooling-react/src/form/form-section.props.ts, packages/fast-tooling-react/src/form/form-section.tsx, packages/fast-tooling-react/src/form/form.props.ts, packages/fast-tooling-react/src/form/form.spec.tsx, packages/fast-tooling-react/src/form/form.tsx, packages/fast-tooling-react/src/form/index.ts, packages/fast-tooling-react/src/form/templates/index.ts, packages/fast-tooling-react/src/form/templates/plugin.control.single-line.tsx, packages/fast-tooling-react/src/form/templates/plugin.control.utilities.tsx, packages/fast-tooling-react/src/form/templates/template.control.utilities.props.tsx
Adds a plugin for use in creating custom controls for the form, allows the form to accept custom controls.
This allows the passing of custom controls to the Form to use in place of the default form controls.
Closes #551 
=> feat: allow control plugins to be passed to the form

packages/fast-layouts-react/src/canvas/canvas.tsx, packages/fast-layouts-react/src/column/column.tsx, packages/fast-layouts-react/src/container/container.tsx, packages/fast-layouts-react/src/grid/grid.tsx, packages/fast-layouts-react/src/page/page.tsx, packages/fast-layouts-react/src/pane/pane.tsx, packages/fast-layouts-react/src/row/row.tsx, packages/fast-layouts-react/src/utilities/string-extensions.ts
Adds className utility to resolve managed classes for fast-layouts package
=> feat: add classNames utility to fast-layouts

packages/fast-layouts-react/src/container/container.tsx
=> fix: add missing display name for container in fast-layouts

packages/fast-layouts-react/src/pane/pane.tsx
In certain scenarios it's possible for pane to be passed as a number and not a pixel value when a pixel value is expected.
=> fix: ensure minWidth value is passed as pixels in pane

packages/fast-components-react-msft/src/progress/progress.tsx
Looks when we refactored to use `classNames` utility there was a regression in how the `size` `className` was being applied and the `control` size `className` was always being overwritten by the `container` size `className`. We are defaulting the prop `size` so just  applying a single class fixes the issue.
=> fix: progress `size` class names conflicting

packages/fast-layouts-react/package.json, packages/fast-layouts-react/src/canvas/canvas.spec.tsx, packages/fast-layouts-react/src/canvas/canvas.tsx, packages/fast-layouts-react/src/column/column.spec.tsx, packages/fast-layouts-react/src/column/column.tsx, packages/fast-layouts-react/src/container/container.spec.tsx, packages/fast-layouts-react/src/grid/grid.no-css-grid.spec.tsx, packages/fast-layouts-react/src/grid/grid.spec.tsx, packages/fast-layouts-react/src/grid/grid.tsx, packages/fast-layouts-react/src/page/page.no-css-grid.spec.tsx, packages/fast-layouts-react/src/page/page.spec.tsx, packages/fast-layouts-react/src/pane/pane.spec.tsx, packages/fast-layouts-react/src/row/row.spec.tsx
Adds tests for components in `fast-layouts-react`
=> chore: add tests for fast-layouts components

packages/fast-components-styles-msft/src/carousel/index.ts
=> fix: remove incorrectly applied display value of block from flipper style in carousel

packages/fast-tooling-react/package.json
This updates the dependencies on `react-dnd` and `react-dnd-html5-backend` to the versions features are being used from.
An incorrect version was allowed to be used as a dependency.
=> fix: update the react-dnd dependencies to the correct version since form is using the new hooks features

packages/fast-jss-utilities/src/acrylic.ts
fix boolean statement to ensure document.* is not called if canUseDOM is false.
Ensure statement is isomorphic.
Issue: #2220
=> fix: isomorphic check in acrylic.js

packages/fast-jss-utilities/README.md
=> chore: correct apply-focus-visible documentation

packages/fast-components-styles-msft/src/utilities/color/common.spec.ts, packages/fast-components-styles-msft/src/utilities/color/common.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.spec.ts, packages/fast-components-styles-msft/src/utilities/color/palette.ts
Optimizes color utilities to be more efficient
Performance
=> fix: optimize several color utilities

packages/fast-components-class-name-contracts-msft/src/action-toggle/index.ts, packages/fast-components-react-msft/src/action-toggle/action-toggle.spec.tsx, packages/fast-components-react-msft/src/action-toggle/action-toggle.stories.tsx, packages/fast-components-react-msft/src/action-toggle/action-toggle.tsx, packages/fast-components-styles-msft/src/action-toggle/index.ts
Minimizes styles and render code.
bundle size / perf improvements.
=> fix: refactor action toggle

packages/fast-component-explorer/app/explorer.style.ts, packages/fast-component-explorer/app/explorer.tsx, packages/fast-components-styles-msft/src/design-system/design-system.schema.ts
Allow users to edit design system values inside the component explorer.
Closes: #2355 
=> feat: add design system editing to component explorer site

packages/fast-components-styles-msft/src/badge/index.ts
Refactor badge styles to not make use of `withDesignSystemDefaults`
=> fix: refactor badge styles

packages/fast-components-react-base/src/hypertext/hypertext.spec.tsx, packages/fast-components-react-base/src/hypertext/hypertext.tsx, packages/fast-components-styles-msft/src/hypertext/index.ts
Reduce stylesheet and remove unnecessary render code
=> fix: refactor hypertext

packages/fast-components-styles-msft/src/utilities/elevation.spec.ts, packages/fast-components-styles-msft/src/utilities/elevation.ts
Reduce size of elevation utility code.
=> fix: refactoring elevation utilities

packages/fast-web-utilities/src/dom.ts
new canUsedForcedColors is not isomorphic.
update to have canUseDOM check before accessing window variable.
this function currently throws exception when running server side.
Issue #2379 
=> fix: canUsedForcedColors function is not isomorphic

packages/fast-components-styles-msft/src/action-toggle/index.ts, packages/fast-components-styles-msft/src/select-option/index.ts, packages/fast-components-styles-msft/src/slider/index.ts, packages/fast-components-styles-msft/src/text-action/index.ts, packages/fast-components-styles-msft/src/toggle/index.ts, packages/fast-components-styles-msft/src/utilities/high-contrast.ts, packages/fast-components-styles-msft/src/utilities/important.ts, packages/fast-jss-utilities/README.md, packages/fast-jss-utilities/src/format.spec.ts, packages/fast-jss-utilities/src/format.ts
Adds new important utility that provides a slight perf improvement and circumvents a bug in the vendor-prefixer JSS plugin.
=> feat: add new important utility

packages/fast-components-styles-msft/src/design-system/index.ts, packages/fast-components-styles-msft/src/utilities/border.ts, packages/fast-components-styles-msft/src/utilities/cursor.ts, packages/fast-components-styles-msft/src/utilities/density.ts, packages/fast-components-styles-msft/src/utilities/typography.ts, packages/fast-jss-utilities/src/units.spec.ts, packages/fast-jss-utilities/src/units.ts
Various bundle reductions across utilities. 
=> fix: various bundle size reductions

packages/fast-tooling-react/src/navigation/navigation.tsx, packages/fast-tooling-react/src/navigation/navigation.utilities.spec.ts, packages/fast-tooling-react/src/navigation/navigation.utilities.ts
After an update was done to pathing to use square brackets on paths, a break occured for the duplication shortcut in Navigation.
This resolves the bug of duplication not targeting arrays, strings and objects correctly.
=> fix: use dot notation for manipulating objects and arrays during duplication

packages/fast-component-explorer/app/explorer.props.ts, packages/fast-component-explorer/app/explorer.tsx, packages/fast-component-explorer/app/preview.tsx, packages/fast-component-explorer/package.json
Adds transparency toggle to component explorer.
Closes: #2356
=> feat: add transparency toggle to component explorer

packages/fast-tooling-react/src/form/controls/control.children.style.ts, packages/fast-tooling-react/src/form/controls/control.children.tsx
Makes children dropdown positioning relative to the control.
The children dropdown would expand to the width of the next element with positioning set. This could result in a full page wide dropdown.
=> fix: addresses a positioning issue for the form children control

packages/fast-tooling-react/src/__tests__/schemas/children.schema.json, packages/fast-tooling-react/src/form/utilities/navigation.spec.ts, packages/fast-tooling-react/src/form/utilities/navigation.ts
Resolves an issue where navigating to string children would cause the Form to throw an error.
=> fix: addresses an issue where navigation to string children was causing an error to throw

CONTRIBUTING.md
=> chore: update CONTRIBUTING.md for yarn building

packages/fast-components-react-msft/src/progress/index.ts
`ProgressSize` is not exported.
=> fix: ProgressSize is not exported

packages/fast-components-styles-msft/src/design-system/index.ts, packages/fast-components-styles-msft/src/utilities/color/neutral-divider.ts
Update divider recipe to invert in dark mode and adjusted delta.
The earlier dark on dark was an exploration with partner teams, but is not a general convention, so adjusting for a more traditional style.
=> fix: update divider recipe to invert in dark mode and adjusted delta

packages/fast-jss-manager-angular/README.md
This PR deprecates the Angular JSS manager package.
The package is no longer under active development (and has not been for quite some time).
=> chore: mark angular jss manager package as deprecated

packages/fast-tooling-react/src/form/controls/control.children.tsx, packages/fast-tooling-react/src/form/form-section.tsx, packages/fast-tooling-react/src/form/form.props.ts, packages/fast-tooling-react/src/form/form.spec.tsx, packages/fast-tooling-react/src/form/form.tsx, packages/fast-tooling-react/src/form/utilities/form.tsx
This fixes an issue where state was falling out of sync when props were updated in the form section and children control.
This caused an error when switching between certain schemas which had similar properties after render had been invoked. This logic has now been moved to the getDerivedStateFromProps lifecycle hook so that state may be updated before rendering.
=> fix: update state for sections and children control when schemas or data have been updated

packages/fast-react-utilities/.npmignore, packages/fast-react-utilities/.npmrc, packages/fast-react-utilities/.prettierignore, packages/fast-react-utilities/README.md, packages/fast-react-utilities/babel.config.js, packages/fast-react-utilities/package.json, packages/fast-react-utilities/src/index.ts, packages/fast-react-utilities/src/use-timeout.spec.tsx, packages/fast-react-utilities/src/use-timeout.ts, packages/fast-react-utilities/src/use-transition-state.spec.tsx, packages/fast-react-utilities/src/use-transition-state.ts, packages/fast-react-utilities/tsconfig.build.json, packages/fast-react-utilities/tsconfig.json, packages/fast-react-utilities/tslint.json, yarn.lock
Adds a React utilities library for general purpose utilities that depend on React APIs.
As we move toward using more functional components and hooks, having a general purpose React utility library that can be leveraged by all packages will be useful and promote general-purpose factoring of UI logic.
=> feat: adds React utilities package

packages/fast-color-explorer/app/app.tsx, packages/fast-color-explorer/app/gradient.tsx, packages/fast-color-explorer/app/service-worker-registration.ts, packages/fast-color-explorer/app/state.ts, packages/fast-color-explorer/app/swatch.tsx, packages/fast-color-explorer/package.json, packages/fast-development-site-react/.prettierignore, yarn.lock
mismatch prettier versions was causing build failures and differences in prettier output depending on where the cmd was run.
This change aligns versions and fixes any issues resulting from doing so.
=> chore: ensure prettier works correctly

packages/fast-component-explorer/app/explorer.props.ts, packages/fast-component-explorer/app/explorer.style.ts, packages/fast-component-explorer/app/explorer.tsx, packages/fast-component-explorer/app/preview.props.ts, packages/fast-component-explorer/app/preview.style.ts, packages/fast-component-explorer/app/preview.tsx
Replace using `get` with `classNames` utility for `className`.
Closes: #2387 
=> chore: replace `get` with `classNames` utility

packages/fast-components-react-base/src/select/select.props.ts, packages/fast-components-react-base/src/select/select.spec.tsx, packages/fast-components-react-base/src/select/select.tsx, packages/fast-components-react-msft/src/select/select.spec.tsx, packages/fast-components-react-msft/src/select/select.tsx
Reverts microsoft/fast-dna#2393
=> revert: "fix: improve select aria"

packages/fast-tooling-react/README.md
The README contained incorrect information about which prop can be used for the Viewer component when passing custom messages to the iframe.
There was an incorrect prop name in the README.
=> fix: update the README

packages/fast-components-react-msft/assets/carousel-hero-content.tsx, packages/fast-components-react-msft/src/carousel/carousel.stories.tsx
Add story to Carousel to showcase that the sequence indicator container should not be overlapping any actions in the content corners of the carousel. This is partially dependent on the implementation of the carousel content (as the width of the indicators must be reduced), but is described in the story so it is clearly known what to look for when viewing the story.
This story is associated with PR #2405 which fixed the sequence indicator container going full width across the carousel and covering up content.
=> chore: add story with buttons to track sequence indicator container width

packages/fast-components-styles-msft/src/utilities/elevation.spec.ts, packages/fast-components-styles-msft/src/utilities/elevation.ts
Updated elevation shadow calculation to increase top definition on lower levels and darker backgrounds.
Before (top) and after (bottom):
The previous shadows didn't leave much definition on the top edge, making it hard to determine elevation particularly for something like a pane that is docked to the bottom.
Also, shadows against darker backgrounds wash out, so increased the opacity based on the background.
=> feat: update elevation shadow

packages/fast-components-react-base/src/auto-suggest/auto-suggest.props.ts, packages/fast-components-react-base/src/auto-suggest/auto-suggest.schema.ts, packages/fast-components-react-base/src/auto-suggest/auto-suggest.spec.tsx, packages/fast-components-react-base/src/auto-suggest/auto-suggest.stories.tsx, packages/fast-components-react-base/src/auto-suggest/auto-suggest.tsx, packages/fast-components-react-msft/src/auto-suggest/auto-suggest.schema.ts, packages/fast-components-react-msft/src/auto-suggest/auto-suggest.stories.tsx, packages/fast-components-react-msft/src/auto-suggest/auto-suggest.tsx
Added optional `filterSuggestions` and `menuTrigger` prop to base `autoSuggest`.
Closes: #2458 
Added functionality to better align with aria spec and user expectations
=> feat: add filtering and onFocus to autoSuggest

packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.spec.tsx, packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
Was a bug in my last commit to the previous horizontal overflow fix that evaded my tests, so fixed it and added a test.
function was returning incorrect result
=> fix:  horizontal overflow position data error, add test

packages/fast-web-utilities/package.json, packages/fast-web-utilities/src/dom.spec.ts, packages/fast-web-utilities/src/dom.ts
This PR adds new utilities for checking valid HTMLElements and checking when those elements are in view.
Adding these utilities outside the context of #2479 though they will be useful for that task.
=> feat: add new utilities for checking HTML elements

packages/fast-components-react-base/src/toggle/toggle.props.ts, packages/fast-components-react-base/src/toggle/toggle.schema.ts, packages/fast-components-react-base/src/toggle/toggle.spec.tsx, packages/fast-components-react-base/src/toggle/toggle.tsx, packages/fast-components-react-msft/src/toggle/toggle.schema.ts
Adds a name prop to toggle to ensure an accessible name can be set.
=> feat: add name prop to toggle

docs/en/getting-started/design-system.md, docs/en/getting-started/jss.md, docs/en/getting-started/modifying-components.md, docs/en/getting-started/the-basics.md, docs/en/getting-started/utilities.md, website/sidebars.json
This PR adds documentation for those getting started with the FAST-DNA components.
=> chore: add getting started documentation

packages/fast-tooling-react/app/index.tsx, packages/fast-tooling-react/package.json, packages/fast-tooling-react/src/form/controls/control.array.spec.tsx, packages/fast-tooling-react/src/form/controls/control.children.spec.tsx, packages/fast-tooling-react/src/form/form-control-switch.spec.tsx, packages/fast-tooling-react/src/form/form-section.spec.tsx, packages/fast-tooling-react/src/form/form.spec.tsx, packages/fast-tooling-react/src/form/index.tsx, packages/fast-tooling-react/src/navigation/navigation.spec.tsx, yarn.lock
BREAKING CHANGE: This changes how contexts are used for the BareForm
component due to the update of react-dnd to 9.0.0
This updates the TypeScript and react-dnd dependencies. It results in an updated usage of BareForm to use the DndProvider, for more details see: https://github.com/react-dnd/react-dnd/issues/1560
We should allow users to upgrade to the latest versions as many of them are using react-dnd outside of the Form and thus would have to have duplicate versions. We were also stuck on 3.3.3, and are behind several nice TypeScript features and fixes.
=> feat: update dependencies to allow the use of latest typescript version

packages/fast-tooling-react/src/form/controls/control.array.spec.tsx, packages/fast-tooling-react/src/form/controls/control.button.spec.tsx, packages/fast-tooling-react/src/form/controls/control.checkbox.spec.tsx, packages/fast-tooling-react/src/form/controls/control.children.spec.tsx, packages/fast-tooling-react/src/form/controls/control.display.spec.tsx, packages/fast-tooling-react/src/form/controls/control.display.tsx, packages/fast-tooling-react/src/form/controls/control.number-field.spec.tsx, packages/fast-tooling-react/src/form/controls/control.section-link.spec.tsx, packages/fast-tooling-react/src/form/controls/control.select.spec.tsx, packages/fast-tooling-react/src/form/controls/control.textarea.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/control.align.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/control.file-upload.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/control.text-align.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/control.theme.spec.tsx, packages/fast-tooling-react/src/form/form-control-switch.spec.tsx, packages/fast-tooling-react/src/form/form-control-switch.tsx, packages/fast-tooling-react/src/form/form-dictionary.spec.tsx, packages/fast-tooling-react/src/form/form-section.tsx, packages/fast-tooling-react/src/form/templates/template.control.single-line.spec.tsx, packages/fast-tooling-react/src/form/templates/template.control.standard.spec.tsx, packages/fast-tooling-react/src/form/templates/template.control.utilities.props.tsx, packages/fast-tooling-react/src/form/templates/template.control.utilities.spec.tsx, packages/fast-tooling-react/src/form/templates/template.control.utilities.tsx
Allows the schema associated with the control to be passed so that any additional metadata that has been added to the schema is accessible.
Closes #2391 
=> feat: pass the schema to the control to allow arbitrary metadata to be accessed

packages/fast-tooling-react/README.md, packages/fast-tooling-react/src/css-editor/color/color.props.ts, packages/fast-tooling-react/src/css-editor/color/color.spec.tsx, packages/fast-tooling-react/src/css-editor/color/color.style.ts, packages/fast-tooling-react/src/css-editor/color/color.tsx, packages/fast-tooling-react/src/css-editor/editor-data.schema.ts, packages/fast-tooling-react/src/css-editor/editor.constants.ts, packages/fast-tooling-react/src/css-editor/editor.schema.json, packages/fast-tooling-react/src/css-editor/editor.spec.tsx, packages/fast-tooling-react/src/css-editor/editor.style.ts, packages/fast-tooling-react/src/css-editor/editor.tsx, packages/fast-tooling-react/src/css-editor/index.ts
closes: #2347 
Converted css Editor to use form and to work with the `<CSSColor/>` component.
=> feat: convert cssEditor to use form

packages/fast-tooling-react/package.json, packages/fast-tooling-react/src/message-system/index.ts, packages/fast-tooling-react/src/message-system/message-system.props.ts, packages/fast-tooling-react/tsconfig.build.json, packages/fast-tooling-react/tsconfig.build.message-system.json, packages/fast-tooling-react/webpack.config.js, yarn.lock
This is the initial message system which registers and de-registers components.
Begins addressing #2482
=> feat: add message system

packages/fast-tooling-react/src/message-system/index.ts, packages/fast-tooling-react/src/message-system/message-system.props.ts
Adds initialization message to be passed to the message system which initializes data.
The data will serve as a single source to be used among the various tooling components. As such, the message system will handle it.
Adds to #2482
=> feat: add initialization with data to message system

packages/fast-tooling-react/src/data-utilities/array.spec.ts, packages/fast-tooling-react/src/data-utilities/array.ts, packages/fast-tooling-react/src/data-utilities/duplicate.spec.ts, packages/fast-tooling-react/src/data-utilities/duplicate.ts, packages/fast-tooling-react/src/data-utilities/location.ts, packages/fast-tooling-react/src/data-utilities/schema.ts, packages/fast-tooling-react/src/form/form-section.props.ts, packages/fast-tooling-react/src/form/utilities/form.spec.ts, packages/fast-tooling-react/src/form/utilities/form.tsx, packages/fast-tooling-react/src/message-system/index.ts, packages/fast-tooling-react/src/message-system/message-system.props.ts, packages/fast-tooling-react/src/navigation/navigation.tsx, packages/fast-tooling-react/src/navigation/navigation.utilities.spec.ts, packages/fast-tooling-react/src/navigation/navigation.utilities.ts
This moves the duplication utility to the data-utilities folder and inserts it into the message system so that it can use it.
Continues the work on #2482 
As part of the data manipulation, the message system needs to be able to duplicate data.
=> feat: place duplicate data functionality in data utilities and add duplication to the message system

packages/fast-tooling-react/README.md, packages/fast-tooling-react/src/css-editor/editor-data.schema.ts, packages/fast-tooling-react/src/css-editor/editor.constants.ts, packages/fast-tooling-react/src/css-editor/editor.schema.json, packages/fast-tooling-react/src/css-editor/editor.tsx, packages/fast-tooling-react/src/css-editor/height/height.props.ts, packages/fast-tooling-react/src/css-editor/height/height.spec.tsx, packages/fast-tooling-react/src/css-editor/height/height.style.ts, packages/fast-tooling-react/src/css-editor/height/height.tsx, packages/fast-tooling-react/src/css-editor/width/width.props.ts, packages/fast-tooling-react/src/css-editor/width/width.spec.tsx, packages/fast-tooling-react/src/css-editor/width/width.style.ts, packages/fast-tooling-react/src/css-editor/width/width.tsx
=> feat: convert width and height to use standard control plugin in css editor

packages/fast-tooling-react/README.md, packages/fast-tooling-react/src/css-editor/background/background.props.ts, packages/fast-tooling-react/src/css-editor/background/background.spec.tsx, packages/fast-tooling-react/src/css-editor/background/background.style.ts, packages/fast-tooling-react/src/css-editor/background/background.tsx, packages/fast-tooling-react/src/css-editor/editor-data.schema.ts, packages/fast-tooling-react/src/css-editor/editor.constants.ts, packages/fast-tooling-react/src/css-editor/editor.schema.json, packages/fast-tooling-react/src/css-editor/editor.tsx, packages/fast-tooling-react/src/css-editor/index.ts
=> feat: convert background to use standard control plugin in css editor

packages/fast-tooling-react/src/__tests__/datasets/invalid-data.ts, packages/fast-tooling-react/src/__tests__/schemas/defaults.schema.json, packages/fast-tooling-react/src/form/controls/control.array.spec.tsx, packages/fast-tooling-react/src/form/controls/control.array.style.ts, packages/fast-tooling-react/src/form/controls/control.array.tsx, packages/fast-tooling-react/src/form/controls/control.button.spec.tsx, packages/fast-tooling-react/src/form/controls/control.checkbox.spec.tsx, packages/fast-tooling-react/src/form/controls/control.children.spec.tsx, packages/fast-tooling-react/src/form/controls/control.display.spec.tsx, packages/fast-tooling-react/src/form/controls/control.number-field.spec.tsx, packages/fast-tooling-react/src/form/controls/control.section-link.spec.tsx, packages/fast-tooling-react/src/form/controls/control.select.spec.tsx, packages/fast-tooling-react/src/form/controls/control.textarea.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/control.align.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/control.file-upload.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/control.text-align.spec.tsx, packages/fast-tooling-react/src/form/custom-controls/control.theme.spec.tsx, packages/fast-tooling-react/src/form/form-control-switch.spec.tsx, packages/fast-tooling-react/src/form/form-control-switch.tsx, packages/fast-tooling-react/src/form/form-section.tsx, packages/fast-tooling-react/src/form/templates/template.control.single-line.spec.tsx, packages/fast-tooling-react/src/form/templates/template.control.standard.spec.tsx, packages/fast-tooling-react/src/form/templates/template.control.utilities.props.tsx, packages/fast-tooling-react/src/form/templates/template.control.utilities.tsx
Show errors next to array items in the Form instead of only on the array.
Closes #2303 
=> feat: display errors next to each array item in the Form

packages/fast-tooling-react/src/form/utilities/form.tsx, packages/fast-tooling-react/src/utilities/ajv-validation.ts
Validation errors are not updated.
Validation errors are not refreshing for the user so user doesn't now what is broken.
=> fix: Validation error are not updated after property value change

packages/fast-tooling-react/src/data-utilities/generate.ts
Fix an import that was updated in the master branch.
This fixes an update to an import that was moved in the feature branch.
=> fix: update an import that has been moved to the data utilities

packages/fast-tooling-react/src/data-utilities/relocate.spec.ts, packages/fast-tooling-react/src/data-utilities/relocate.ts, packages/fast-tooling-react/src/message-system/index.ts, packages/fast-tooling-react/src/message-system/message-system.props.ts
Allow post messages to be sent to add or remove data from the message systems data blob.
Condinues addressing #2482 
=> feat: allow adding and removing data from the message-system

packages/fast-tooling-react/tsconfig.build.message-system.json, packages/fast-tooling-react/webpack.config.js
Due to the message system imports updating, the message system is now located inside a webworker folder in the dist directory. This appears to be a stable location and should not update as long as imports are confined to the src directory.
The message system updated the location of the index.js file due to the typescript compiler locating imports that necessitated their own folder.
=> chore: update the location of the exported webworker

packages/fast-tooling-react/src/data-utilities/index.ts, packages/fast-tooling-react/src/data-utilities/react-child.schema.ts, packages/fast-tooling-react/src/data-utilities/react-children.schema.spec.ts, packages/fast-tooling-react/src/data-utilities/react-children.schema.ts, packages/fast-tooling-react/src/data-utilities/react-element.schema.ts, packages/fast-tooling-react/src/data-utilities/react-text.schema.ts
Create an exportable JSON schema that defines the React Children.
This adds an exportable object to be used in component libraries which will replace type "children".
Begins addressing #2485
=> feat: add a JSON schema for react children

packages/fast-tooling-react/README.md, packages/fast-tooling-react/src/form/form.props.ts
As a first step in deprecating the childOptions and reactProperties, these sections have been marked as deprecated.
Begins to address #2524 
=> feat: mark child options and react properties as deprecated

packages/fast-tooling-react/src/message-system/index.ts, packages/fast-tooling-react/src/message-system/message-system.props.ts, packages/fast-tooling-react/src/message-system/plugin.ts
In preparation for deprecating `childOptions` and `type: "children"` this is initial scaffolding  to treat that functionality as a plugin for the message system.
=> feat: add an initial plugin system for the message system

.github/stale.yml
Prevents stalebot from closing *issues* if they are stale. *issues* will still get marked as stale, but will not be closed.
Increases time required for pull requests to become stale.
=> chore: adjust stalebot settings

packages/fast-components-styles-msft/src/progress/index.ts
This fix changes the outer most div display to be `inline` instead of `block`.
Closes: #2494 
**After:**
This allows the circular `progress` to be easily positioned within UI without any style overrides
=> fix: circular progress is 100% width

packages/fast-browser-extensions/README.md, packages/fast-components-react-msft/package.json, packages/fast-glyphs-msft/README.md, packages/fast-jest-snapshots-react/README.md
This PR marks the following packages as deprecated and no-longer under active development.
- fast-glyphs-msft
- fast-jest-snapshots-react
- fast-browser-extensions
=> fix: mark fast-glyphs, fast-jest-snapshots-react and fast-browser-extensions packages as deprecated

packages/fast-tooling-react/src/form/utilities/navigation.spec.ts, packages/fast-tooling-react/src/form/utilities/navigation.ts
The root level navigation item should have any specified default applied, this was not occurring and would only show defaults at scoped levels.
=> fix: ensure root level items in the form have default

packages/fast-tooling-react/src/style/utilities.ts
Ensure that top level box-sizing settings cannot mess up the styling of the form.
=> fix: adjust and harden some small style properties on control indicators in the form

README.md
This change adds a link to the staging site to the package root readme file.
Related to #2540, the staging site now maps to the `master` branch. The production will be manually deployed (for the time being) aside NPM publishes. This allows our published component explorer to align with the latest published version of our packages. 
Adding the staging site provides a way to share, see, and validate changes which are staged for production.
=> chore: add staging site link to root readme

packages/fast-tooling-react/src/form/templates/template.control.utilities.spec.tsx, packages/fast-tooling-react/src/form/templates/template.control.utilities.tsx
Check data against defaults for all potential data types (not just strings or other immutable data).
=> fix: check the data against the defaults for all data types

packages/fast-tooling-react/README.md, packages/fast-tooling-react/src/form/index.ts
Default form controls are added as exports for the use case of providing extra information or modifying the config before it is added to the control.
=> feat: add default controls to the export and fix documentation for overriding controls with types

packages/fast-tooling-react/src/__tests__/schemas/invalid-data.schema.json, packages/fast-tooling-react/src/form/form-dictionary.spec.tsx, packages/fast-tooling-react/src/form/form-dictionary.tsx, packages/fast-tooling-react/src/form/form.spec.tsx, packages/fast-tooling-react/src/form/utilities/form.spec.ts, packages/fast-tooling-react/src/form/utilities/form.tsx
Provide more targeted errors for data locations so that the Form shows the correct errors.
=> fix: adjust precision when assigning errors to data locations

packages/fast-tooling-react/src/form/utilities/form.spec.ts, packages/fast-tooling-react/src/form/utilities/form.tsx
This solves some redundant logic that was messing up invalid message inheritance when bubbling up the tree.
=> fix: remove redundant checks when assigning validation errors to invalid messages

packages/fast-tooling-react/package.json, packages/fast-tooling/.npmignore, packages/fast-tooling/.prettierignore, packages/fast-tooling/README.md, packages/fast-tooling/package.json, packages/fast-tooling/src/index.ts, packages/fast-tooling/src/schemas/child.schema.ts, packages/fast-tooling/src/schemas/children.schema.spec.ts, packages/fast-tooling/src/schemas/children.schema.ts, packages/fast-tooling/src/schemas/element.schema.ts, packages/fast-tooling/src/schemas/index.ts, packages/fast-tooling/src/schemas/keywords.ts, packages/fast-tooling/src/schemas/text.schema.ts, packages/fast-tooling/tsconfig.build.json, packages/fast-tooling/tsconfig.json, packages/fast-tooling/tslint.json, yarn.lock
In accordance with our projects conventions, this package will hold any framework-less tooling.
=> feat: add new package for framework-less tooling

packages/fast-components-react-msft/src/context-menu/context-menu.props.ts, packages/fast-components-react-msft/src/context-menu/context-menu.spec.tsx, packages/fast-components-react-msft/src/context-menu/context-menu.tsx, packages/fast-components-react-msft/src/context-menu/index.ts, packages/fast-components-styles-msft/src/context-menu-item/index.ts, packages/fast-components-styles-msft/src/context-menu/index.ts
Closes: #2250 
Updated `<ContextMenu/>` to use `neutralLayerFloating`
Before:
After:
=> feat: update ContextMenu to neutralLayerFloating

packages/fast-tooling-react/app/pages/viewer/custom-message-page.tsx, packages/fast-tooling-react/app/pages/viewer/custom-message-page.viewer-content.tsx
An improvement on the local manual test app for the `Viewer` to see custom messaging solutions.
=> chore: improve the example in the test app for custom messages in the Viewer

packages/fast-tooling-react/src/form/form-section-validation.props.ts, packages/fast-tooling-react/src/form/form-section-validation.spec.tsx, packages/fast-tooling-react/src/form/form-section-validation.style.ts, packages/fast-tooling-react/src/form/form-section-validation.tsx, packages/fast-tooling-react/src/form/form-section.props.ts, packages/fast-tooling-react/src/form/form-section.spec.tsx, packages/fast-tooling-react/src/form/form-section.style.ts, packages/fast-tooling-react/src/form/form-section.tsx, packages/fast-tooling-react/src/form/utilities/form.tsx, packages/fast-tooling-react/src/style/utilities.ts
In the Form section which represents an object there is an alert showing a top level invalidation message, often there are multiple messages, when there are more than 1 message there will now be a chevron expand/collapse to show/hide the rest of the errors. This will in future also allow the ability to clear errors from this location.
=> feat: allow viewing of all validation errors present on an object

packages/fast-tooling-react/src/form/controls/control.button.tsx
The value setting to null was triggering form submittal behavior such as reporting validity on invalid form elements. This fix stops any default button clicking behavior.
=> fix: ensure that setting a value to null does not trigger any default button click behavior

packages/fast-figma-plugin-msft/.npmrc
figma plugin shouldn't be generating package-lock.json files
=> chore: don't generate package locks

docs/en/getting-started/utilities.md
A customer mentioned broken links on the Getting Started utility page at https://stackoverflow.com/questions/55935949/docusaurus-how-to-open-external-links-in-new-tab
Docusaurus automatically converts all markdown links to a relative URL for the documentation site.  If you want to use an external link you must instead use HTML within your markdown on Docusaurus as noted on [https://stackoverflow.com/questions/55935949/docusaurus-how-to-open-external-links-in-new-tab](SO).
This change will have to be published to be realized after this PR goes in.
Fixes broken links
=> chore: update to fix broken external link

packages/fast-figma-plugin-msft/src/plugin-data.ts
import `isComponentNode` and `isInstanceNode` data types, and add these to the list of supported figma node types to which the plugin can apply fill and stroke color
- `import` the data types `isComponentNode` and `isInstanceNode`
- add these data types to the list of supported figma node types in `export function supports(node: BaseNode, type: keyof PluginData): boolean`
Allow the figma plugin to apply colors to component and instance nodes
=> feat: enable the ability for the plugin to apply color to component and instance nodes

packages/fast-tooling-react/README.md, packages/fast-tooling-react/src/form/index.ts
This adds the `ControlTemplateUtilities` to the root level exports of the tooling package.
If the user wishes to create their own control template, this will assist them should the wish to extend the same functionality used by the `StandardControlPlugin` class.
=> feat: add the ControlTemplateUtilities to the root level export for greater flexibility when using the control plugin system

packages/fast-tooling-react/src/css-editor/background/background.style.ts, packages/fast-tooling-react/src/css-editor/border-radius/border-radius.style.ts, packages/fast-tooling-react/src/css-editor/border/border.style.ts, packages/fast-tooling-react/src/css-editor/box-shadow/box-shadow.style.ts, packages/fast-tooling-react/src/css-editor/color/color.style.ts, packages/fast-tooling-react/src/css-editor/height/height.style.ts, packages/fast-tooling-react/src/css-editor/position/position.style.ts, packages/fast-tooling-react/src/css-editor/spacing/spacing.style.ts, packages/fast-tooling-react/src/css-editor/width/width.style.ts, packages/fast-tooling-react/src/form/controls/control.array.style.ts, packages/fast-tooling-react/src/form/controls/control.button.style.ts, packages/fast-tooling-react/src/form/controls/control.children.style.ts, packages/fast-tooling-react/src/form/controls/control.display.style.ts, packages/fast-tooling-react/src/form/controls/control.number-field.style.ts, packages/fast-tooling-react/src/form/controls/control.select.style.ts, packages/fast-tooling-react/src/form/controls/control.textarea.style.ts, packages/fast-tooling-react/src/form/custom-controls/control.align.style.ts, packages/fast-tooling-react/src/form/custom-controls/control.text-align.style.ts, packages/fast-tooling-react/src/form/custom-controls/control.theme.style.ts, packages/fast-tooling-react/src/form/form-dictionary.style.ts, packages/fast-tooling-react/src/form/form-one-of-any-of.style.ts, packages/fast-tooling-react/src/form/form-section-validation.style.ts, packages/fast-tooling-react/src/form/form.style.ts, packages/fast-tooling-react/src/form/templates/template.control.single-line.style.ts, packages/fast-tooling-react/src/form/templates/template.control.standard.style.ts, packages/fast-tooling-react/src/style/utilities.ts, packages/fast-tooling-react/src/viewer/rotate/rotate.style.ts, packages/fast-tooling-react/src/viewer/select-device/select-device.style.ts
Performance cleanup on the application of styles.
=> fix: performance enhancement, update functions to plain objects for styling

packages/fast-tooling-react/src/__tests__/schemas/defaults.schema.json, packages/fast-tooling-react/src/form/controls/control.array.style.ts, packages/fast-tooling-react/src/form/controls/control.button.spec.tsx, packages/fast-tooling-react/src/form/controls/control.button.style.ts, packages/fast-tooling-react/src/form/controls/control.button.tsx, packages/fast-tooling-react/src/form/controls/control.checkbox.spec.tsx, packages/fast-tooling-react/src/form/controls/control.checkbox.style.ts, packages/fast-tooling-react/src/form/controls/control.checkbox.tsx, packages/fast-tooling-react/src/form/controls/control.display.spec.tsx, packages/fast-tooling-react/src/form/controls/control.display.style.ts, packages/fast-tooling-react/src/form/controls/control.display.tsx, packages/fast-tooling-react/src/form/controls/control.number-field.spec.tsx, packages/fast-tooling-react/src/form/controls/control.number-field.style.ts, packages/fast-tooling-react/src/form/controls/control.number-field.tsx, packages/fast-tooling-react/src/form/controls/control.section-link.spec.tsx, packages/fast-tooling-react/src/form/controls/control.section-link.style.ts, packages/fast-tooling-react/src/form/controls/control.section-link.tsx, packages/fast-tooling-react/src/form/controls/control.select.spec.tsx, packages/fast-tooling-react/src/form/controls/control.select.style.ts, packages/fast-tooling-react/src/form/controls/control.select.tsx, packages/fast-tooling-react/src/form/controls/control.textarea.spec.tsx, packages/fast-tooling-react/src/form/controls/control.textarea.style.ts, packages/fast-tooling-react/src/form/controls/control.textarea.tsx, packages/fast-tooling-react/src/form/form-control-switch.tsx, packages/fast-tooling-react/src/form/utilities/form.tsx, packages/fast-tooling-react/src/style/constants.ts, packages/fast-tooling-react/src/style/utilities.ts
Adds default classes and styles to assist in the understanding that a control is using default values.
Closes #2576 
=> feat: add default classes and stylings to differentiate when the value of an item is not set but a default has been provided

packages/fast-components-react-base/src/tabs/tabs.spec.tsx, packages/fast-components-react-base/src/tabs/tabs.tsx
=> fix: prevent default on tabs component navigation

.circleci/config.yml
Add a new `resource_class` to `config.yml` set to `large` so bump up resources.  This is temporarily set on a new "Performance" plan under trial.  We will determine long term plan after testing and checking out data for 7 days.  
Circle CI's pipeline has been experiencing out of memory exceptions due to limited ram of 4096gb breaking builds intermittently. 
=> chore: adds new resource class for circle ci

packages/fast-tooling-react/README.md
=> chore: correct form import documentation

packages/fast-figma-plugin-msft/src/color-recipies.ts, packages/fast-figma-plugin-msft/src/interface/plugin-ui.state.ts, packages/fast-figma-plugin-msft/src/interface/plugin-ui.tsx, packages/fast-figma-plugin-msft/src/interface/strings.ts, packages/fast-figma-plugin-msft/src/main.ts, packages/fast-figma-plugin-msft/src/messaging/ui.ts, packages/fast-figma-plugin-msft/src/plugin-data.ts, packages/fast-figma-plugin-msft/src/utilities/design-system.ts, packages/fast-figma-plugin-msft/src/utilities/node.ts, packages/fast-figma-plugin-msft/src/utilities/paint.ts, packages/fast-figma-plugin-msft/tslint.json
Adds theme support to Figma plugin, allowing setting light / dark theme for a node.
=> feat: add light / dark theme support to Figma plugin

packages/fast-storybook-presets/src/setup.tsx
Updates the font in storybook to have proper fallbacks and allows us to more accurately test our components.
Before:
After:
=> fix: update fonts in storybook

docs/en/contributing/install.md, package.json
Simplifies the getting started documentation and build process.
* Adds script `prepare` to automatically execute Lerna command as part of Install.
* Adds links for Lerna and Yarn to open in a new window.  We always want external references to open in a new window rather than redirect our users off our www.fast.design.
I experienced some confusion on a informational message from Lerna during the installation and prepare step.  I researched the [issue](https://remarkablemark.org/blog/2019/04/06/lerna-bootstrap-prepare-yarn-workspaces/) and looks like an improvement that could be made since `yarn run prepare` is invalid and that could confuse others.
=> chore: update to simplify getting started and improve documentation

packages/fast-components/src/design-system-provider/design-system-provider.ts
Fix reference to the target of the observable calls.
=> fix: reference to observable target

packages/fast-components/.storybook/main.js, packages/fast-components/package.json, packages/fast-components/tsconfig.json, yarn.lock
Changes storybook configuration to use ts-loader instead of awesome-typescript-loader. awesome-typescript-loader used a locked version of typescript, not the version that was installed by the project, which was causing various issues with packages compiled from a later version of typescript. ts-loader gives us greater control over the typescript cli and options used by the loader, and is actively maintained.
=> chore: use ts-loader for fast-components development environment

packages/fast-element/tslint.json
relaxing the max-classes-per-file tslint rule because in many cases we have two or more small closely related classes that don't need an additional file for clarity
=> chore: relax max-classes-per-file tslint rule

packages/fast-tooling-react/src/style/utilities.ts
Styling update to the select in the tooling components to prevent text overflow.
=> fix: adjust select styling to prevent text overflow

packages/fast-tooling-react/src/data-utilities/generate.spec.ts, packages/fast-tooling-react/src/data-utilities/generate.ts
Removal of the deprecated property in JSON schema used to identify React properties such as children.
=> chore: remove search for children using the deprecated reactProperties JSON schema extension

.github/CODEOWNERS
This PR adds codeowners for the web component specifications.
=> chore: add codeowners for specifications

specs/README.md
This PR adds additional information to the README as it relates to creating new specs. The change adds explicit details on how to submit a spec and advises spec authors to remove any additional boilerplate when submitting a PR.
=> chore: add explicit details for creating specs to readme

.circleci/config.yml
Circle CI is **blocked** currently, because our trail performance plan expired.  This will downgrade to the default plan, to unblock the build pipeline.  
As soon as this goes in, we should be able to approve the next PR to implement GitHub Actions and deprecate Circle CI.
Unblock build pipeline.
=> chore: update to downgrade circle-ci back to default

packages/fast-tooling-react/src/data-utilities/schema.ts, packages/fast-tooling-react/src/form/utilities/form.tsx
Removes an unused schema typing. This typing is available with the `CombiningKeyword` export from fast-tooling.
=> chore: remove unused schema typing

packages/fast-tooling-react/package.json, packages/fast-tooling-react/src/data-utilities/index.ts, packages/fast-tooling-react/src/data-utilities/location.ts, packages/fast-tooling-react/src/data-utilities/types.ts, packages/fast-tooling-react/src/form/controls/control.section.props.ts, packages/fast-tooling-react/src/form/controls/control.section.tsx, packages/fast-tooling-react/src/form/controls/utilities/control-switch.tsx, packages/fast-tooling-react/src/form/controls/utilities/dictionary.tsx, packages/fast-tooling-react/src/form/utilities/breadcrumb.ts, packages/fast-tooling-react/src/form/utilities/form.spec.ts, packages/fast-tooling-react/src/form/utilities/form.tsx, packages/fast-tooling/src/data-utilities/types.ts
This moves more non-react specific types to the non-react tooling package.
=> chore: update imports to use the fast tooling package for types

.github/workflows/ci-daily.yml, .github/workflows/ci-weekly.yml
We use Code Climate to analyze our code quality.  The script has already been added to GitHub Actions and it runs successfully.  Unfortunately, there is a bug in the process and this PR will aim to resolve and patch.
Resolve existing bug in code quality process.
=> chore: update code climate configuration

packages/fast-tooling-react/README.md, packages/fast-tooling/README.md
This updates the `fast-tooling` and `fast-tooling-react` README.md files to be inline with the updated APIs and moved utilities.
=> chore: update README files for tooling

packages/fast-tooling-react/package.json
Bumps the `@microsoft/fast-tooling-react` version to a prerelease of 2.0.0.
There was also a mistake during the publish, I blame @nicholasrice for the fact that 2.0.0 without any prerelease versioning is now published 🙄. Thankfully, it is tagged as canary.
=> chore: bump the fast-tooling-react version to 2.0.0-alpha.0

packages/fast-tooling-react/src/index.ts
The updates needed for the `CSSEditor` are still incomplete, due to this there is no way to add the message system. As such, the `CSSEditor` component is removed from the `fast-tooling-react` exports to be evaluated at another time.
=> chore: remove the CSS editor from exports as the work to refactor it using the form is incomplete

packages/fast-components/src/index.ts
I noticed that we were exporting the name tag example, which I don't think we want to actually ship. Considering our goal with fast-components is to export "all the things" that help us compose the components, I thought we should export the form-associated abstract class.
=> chore: remove name tag as export

packages/fast-tooling-react/README.md, packages/fast-tooling/README.md
Some small updates to the README files in `fast-tooling` and `fast-tooling-react`.
=> chore: update README files for better wording and formatting

packages/fast-tooling-react/app/pages/css-editor.tsx, packages/fast-tooling-react/app/pages/form/index.ts, packages/fast-tooling-react/app/pages/style-editors.tsx, packages/fast-tooling-react/src/__tests__/schemas/index.ts, packages/fast-tooling-react/src/__tests__/schemas/text.schema.ts
Fix a few broken import references in the test app and add a simple string schema to ensure there is a simple data test for the `Form`.
=> chore: update the test app with a simple string schema

packages/fast-components/src/checkbox/checkbox.stories.ts, packages/fast-components/src/checkbox/checkbox.styles.ts, packages/fast-components/src/checkbox/checkbox.template.ts, packages/fast-components/src/checkbox/checkbox.ts, packages/fast-components/src/checkbox/fixtures/base.html, packages/fast-components/src/checkbox/index.ts, packages/fast-components/src/design-system-provider/design-system-provider.styles.ts, packages/fast-components/src/design-system-provider/design-system-provider.ts, packages/fast-components/src/form-associated/index.ts, packages/fast-components/src/index.ts, packages/fast-components/src/styles/disabled.ts, packages/fast-components/src/styles/display.ts, packages/fast-components/src/styles/index.ts, packages/fast-components/src/utilities.ts, specs/form-associated-custom-element.md
Adds the fast-checkbox web component. The spec is still out in code-review awaiting sign-off - I will update this PR accordingly.
=> feat: add checkbox web component

packages/fast-element/docs/roadmap.md
A brief document listing out things I think we might do with `fast-element` in the short, medium, and longer terms.
Getting various ideas out of my head and various discussed features into written form; making planning more public. Some of what is listed is experimental or speculative.
=> doc(fast-element): add roadmap

packages/fast-tooling-react/README.md, packages/fast-tooling-react/app/pages/form-and-navigation.tsx, packages/fast-tooling-react/app/pages/navigation.tsx, packages/fast-tooling-react/src/form/form.spec.tsx, packages/fast-tooling-react/src/form/index.tsx, packages/fast-tooling-react/src/navigation/index.ts, packages/fast-tooling-react/src/navigation/index.tsx, packages/fast-tooling-react/src/navigation/navigation.props.ts, packages/fast-tooling-react/src/navigation/navigation.spec.tsx, packages/fast-tooling-react/src/navigation/navigation.tsx, packages/fast-tooling-react/src/viewer/viewer/viewer.tsx
This updates the tooling components which are intended to work together to include a "Modular" prefixed version. This should prevent breaking changes in the future when more shared contexts are used such as allowing drag and drop into the `Viewer`.
This also removes the optional `dragAndDropReordering` on the `Navigation` as it is now assumed that drag and drop is possible. As some background context, this prop was used to ensure a standalone version did not break, however this is now fixed by having multiple exports.
Closes #2774 
=> feat: update tooling 'ecosystem' components with the Modular prefix

packages/fast-components/src/card/card.stories.ts, packages/fast-components/src/card/card.styles.ts, packages/fast-components/src/card/card.template.ts, packages/fast-components/src/card/card.ts, packages/fast-components/src/card/fixtures/card.html, packages/fast-components/src/card/index.ts
This PR adds `card` as a new web component based on [the spec](https://github.com/microsoft/fast-dna/blob/master/specs/card/card.md).
Outstanding issues:
- While we have a stub of the design system provider in, we have not yet included the concept of `elevation`. This PR includes an initial stub for elevation but does not resolve the overall design system implementation.
=> feat: add card as a new web component

specs/template.md
This PR adds a section to the spec template for *non-goals*.
=> chore: add non-goals section to spec template

packages/fast-tooling/package.json, packages/fast-tooling/src/data-utilities/generate.spec.ts, packages/fast-tooling/src/data-utilities/generate.ts, packages/fast-tooling/src/data-utilities/relocate.spec.ts, packages/fast-tooling/src/data-utilities/relocate.ts, packages/fast-tooling/src/message-system/message-system.utilities.spec.ts, packages/fast-tooling/src/message-system/message-system.utilities.ts, packages/fast-tooling/src/message-system/navigation.spec.ts, packages/fast-tooling/src/message-system/navigation.ts
Fixes a few minor issues such as:
- An erroneous message system return
- Unnecessary if checks
- Unnecessary declarations of arguments
- Removal of code that is never reached
Add more unit tests to reach 100 test coverage on `@microsoft/fast-tooling`.
=> fix: correct some erroneous message system navigation returns, add more unit testing to bring code quality up

packages/fast-tooling-react/README.md, packages/fast-tooling-react/src/data-utilities/index.ts, packages/fast-tooling-react/src/data-utilities/mapping.spec.tsx, packages/fast-tooling-react/src/data-utilities/mapping.tsx, packages/fast-tooling-react/src/index.ts, packages/fast-tooling/src/data-utilities/mapping.spec.ts, packages/fast-tooling/src/data-utilities/mapping.ts
Using the new `mapDataDictionary`, this `reactMapper` function will take a dictionary of React components and return the mapper required by the `mapDataDictionary` to transform the data dictionary into a nested React component instance.
=> feat: add mapper function to create React components

packages/fast-components/src/index.ts, packages/fast-components/src/text-field/fixtures/text-field.html, packages/fast-components/src/text-field/index.ts, packages/fast-components/src/text-field/text-field.stories.ts, packages/fast-components/src/text-field/text-field.styles.ts, packages/fast-components/src/text-field/text-field.template.ts, packages/fast-components/src/text-field/text-field.ts
This PR adds text field as a new component
=> feat: add text field web component

packages/fast-components/src/index.ts, packages/fast-components/src/text-area/fixtures/text-area.html, packages/fast-components/src/text-area/index.ts, packages/fast-components/src/text-area/text-area.stories.ts, packages/fast-components/src/text-area/text-area.styles.ts, packages/fast-components/src/text-area/text-area.template.ts, packages/fast-components/src/text-area/text-area.ts
This PR adds Text Area as a web component.
=> feat: add text area web component

packages/fast-components/src/index.ts, packages/fast-components/src/switch/fixtures/base.html, packages/fast-components/src/switch/index.ts, packages/fast-components/src/switch/switch.stories.ts, packages/fast-components/src/switch/switch.styles.ts, packages/fast-components/src/switch/switch.template.ts, packages/fast-components/src/switch/switch.ts, specs/switch.md
This PR adds Switch as a web component.
=> feat: add switch as new web component

packages/fast-tooling-react/package.json, packages/fast-tooling/package.json, yarn.lock
Bumps the `@microsoft/fast-tooling` and `@microsoft/fast-tooling-react` versions.
This is part of the overall testing strategy for the alpha build of the v2 of FAST tooling.
=> chore: bump fast-tooling and fast-tooling-react versions

packages/fast-tooling-react/src/form/form.tsx
Fixes an issue where the same schema was being referred to when validation occurs for linked items. This change ensures that the schema being validated against is the schema for that dictionary item.
=> fix: refers to the schema dictionary so that each linked item can be validated for errors

.github/workflows/ci-daily.yml
GitHub Secrets should not be used for code coverage reporting if we want contributor builds to succeed.  
> Secrets are environment variables that are encrypted and only exposed to selected actions. Anyone with **collaborator** access to this repository can use these secrets in a workflow.
Code Climate has confirmed as a best practices to not use as a secret and to expose directly into our the pipeline configuration.  
> Yes, we generally recommend exposing the ID. It's a low-risk decision.
> 
> Here's one of ours: https://github.com/codeclimate/codeclimate/blob/master/.circleci/config.yml
> 
> At most, you risk having someone upload a coverage payload with your id, resulting in incorrect coverage shown on your Code Climate results. That incorrect data would be replaced with your own …
=> chore: update to allow contributors to run code coverage

.github/workflows/cd-explore-stage.yml, .github/workflows/ci-daily.yml, .github/workflows/ci-weekly.yml, README.md
Update the naming conventions so when you're on the GitHub Actions page, it's more intuitive how the different workflows are being used.
Improve intuitable readability. Names should be consist, distinguishing between CI or CD, and remove duplicativeness.  Also, add badge for component explorer section of root readme.  Also, wanted to update specify the branch and event.
=> chore: update naming conventions for better consistency

packages/fast-tooling-react/app/README.md, packages/fast-tooling-react/app/app.tsx, packages/fast-tooling-react/app/pages/web-components.tsx, packages/fast-tooling-react/app/pages/web-components/fancy-button.schema.ts, packages/fast-tooling-react/app/pages/web-components/fancy-button.ts, packages/fast-tooling-react/app/pages/web-components/index.ts, packages/fast-tooling-react/app/pages/web-components/text.schema.ts, packages/fast-tooling-react/app/pages/web-components/web-component-viewer-content.tsx
Creates a page in the test app for `@microsoft/fast-tooling-react` that includes various tooling components and renders them as web components.
=> chore: add an environment to validate web components work with tooling

packages/fast-components/src/checkbox/checkbox.styles.ts, packages/fast-components/src/styles/focus.ts, packages/fast-components/src/styles/index.ts, packages/fast-components/src/switch/switch.styles.ts, packages/fast-components/src/text-area/text-area.styles.ts, packages/fast-components/src/text-field/text-field.styles.ts
Adds simple focus-visible utility to smartly use focus-visible selectors when available, and focus selectors when not. Closes #2812
Change exposes an importable string that will resolve to `"focus-visible"` when focus-visible is supported and `"focus"` when it isn't. We'll be able to use this string to construct focus selectors that will select for for `:focus-visible` when the selector can be recognized and `:focus` when not.
=> feat: adds focus-visible support to components

packages/fast-tooling/src/message-system/index.ts, packages/fast-tooling/src/message-system/message-system.utilities.props.ts, packages/fast-tooling/src/message-system/message-system.utilities.spec.ts, packages/fast-tooling/src/message-system/message-system.utilities.ts, packages/fast-tooling/src/message-system/types.ts, packages/fast-tooling/src/message-system/validation.props.ts
Adds a validation message to the message system.
Resolves #2822 
=> feat: add validation to the message system

packages/fast-tooling-react/app/pages/web-components/web-component-viewer-content.tsx, packages/fast-tooling-react/src/form/form.props.ts, packages/fast-tooling-react/src/form/form.spec.tsx, packages/fast-tooling-react/src/form/utilities/breadcrumb.ts, packages/fast-tooling-react/src/navigation/navigation-tree-item.props.ts, packages/fast-tooling-react/src/navigation/navigation.props.ts, packages/fast-tooling-react/src/navigation/navigation.spec.tsx, packages/fast-tooling-react/src/navigation/navigation.tsx, packages/fast-tooling/src/message-system/message-system.utilities.props.ts, packages/fast-tooling/src/message-system/message-system.utilities.ts, packages/fast-tooling/src/message-system/navigation.props.ts, packages/fast-tooling/src/message-system/navigation.spec.ts, packages/fast-tooling/src/message-system/navigation.ts
Clean up various naming oddities:
- Interface names with redundant naming such as "tree" for navigation, except where needed
- the use of 'active' when passing an id should indicate that is the active id
- the web component page that was not updated with the new updates to the `mapDataDictionary` utility
=> fix: cleanup interface names and fix the web component renderer in the test app

specs/README.md, specs/progress.md
Adds spec for `<fast-progress/>`
This assumes we want similar functionality that we have in the current react version of progress.
=> chore: add progress web component spec

specs/README.md, specs/badge.md
Adds spec for `<fast-badge/>`
This assumes we want similar functionality that we have in the current react version of badge.
=> chore: add badge web component spec

packages/fast-components/src/checkbox/checkbox.template.ts, packages/fast-components/src/checkbox/checkbox.ts, packages/fast-components/src/form-associated/index.ts, packages/fast-components/src/switch/switch.template.ts, packages/fast-components/src/switch/switch.ts, packages/fast-components/src/text-area/text-area.ts, packages/fast-components/src/text-field/text-field.ts, packages/fast-components/src/utilities.ts
Implements the boolean attr mode for all boolean attributes.
=> fix: implement new boolean attribute mode

.github/workflows/ci-weekly.yml
During the weekly performance analysis I discovered we were duplicating job steps still in the pipeline for yarn lerna prepare and this eliminates that to improve performance and consistency build like the other jobs on GH Actions.
Discovery of perf issue and specific lerna version being installed. 
=> chore: update to mac builds for better performance and consistency

packages/fast-components/src/text-field/fixtures/text-field.html, packages/fast-components/src/text-field/text-field.stories.ts, packages/fast-components/src/text-field/text-field.styles.ts, packages/fast-components/src/text-field/text-field.template.ts, packages/fast-components/src/text-field/text-field.ts
The initial text field work was unfortunately not being exposed as a form element. This PR updates the control to be a form associated element.
=> fix: udpate text tield as form connected

packages/fast-tooling/src/message-system/message-system.utilities.props.ts, packages/fast-tooling/src/message-system/message-system.utilities.spec.ts, packages/fast-tooling/src/message-system/message-system.utilities.ts, packages/fast-tooling/src/message-system/types.ts
This allows any arbitrary message to be sent via a custom message which can contain any content sufficing that it includes the "custom" type. This will allow components opted in to the message system to pass arbitrary messages that the message system may not need to store or act on.
There is a requirement to validate a oneOf if data is provided inside the `Form` component so as to show which oneOf item is selected. This should be done via the validation system, however the message system does not need to know the outcome, therefore a custom message is required to allow the `Form` and the validation to communicate separately.
=> feat: allow custom messages to be sent to the message system which will return them

packages/fast-tooling/src/data-utilities/ajv-validation.spec.ts, packages/fast-tooling/src/data-utilities/ajv-validation.ts, packages/fast-tooling/src/message-system/message-system.utilities.props.ts, packages/fast-tooling/src/message-system/validation.props.ts
This allows for validation of sets of schemas against data. It will be useful in contexts such as identifying which oneOf or anyOf schema is valid against current data.
Partially resolves #2824 
=> feat: allow a request/response custom validation message to be sent to the AjvMapper

specs/README.md, specs/number-field.md
Adds a new specification for number field. 
=> chore: add number field field spec

packages/fast-tooling-react/app/pages/form-and-navigation.tsx, packages/fast-tooling-react/app/pages/navigation/example.data.ts, packages/fast-tooling-react/src/navigation/navigation-tree-item.props.ts, packages/fast-tooling-react/src/navigation/navigation-tree-item.tsx, packages/fast-tooling-react/src/navigation/navigation.props.ts, packages/fast-tooling-react/src/navigation/navigation.spec.tsx, packages/fast-tooling-react/src/navigation/navigation.style.ts, packages/fast-tooling-react/src/navigation/navigation.tsx, packages/fast-tooling/src/message-system/message-system.utilities.props.ts, packages/fast-tooling/src/message-system/message-system.utilities.spec.ts, packages/fast-tooling/src/message-system/message-system.utilities.ts
This change allows linked data to be dragged before and after other linked data. It also greatly reduces the complexity of the dragging elements, limiting them to only the single `<span>` or `<a>` elements that represent the "triggers". This assists in reducing the overlap that was happening  between elements as drop targets via the `react-dnd` package.
Additionally in order to allow an item to be dragged before or after another item, an additional property was added to the message systems `addLinkedData` action to specify the index that the linked data could be spliced into.
=> feat: more precise drag and drop allowed before and after linked data
