microsoft/fast

- CONTRIBUTING.md
- README.md
- packages/fast-components-class-name-contracts/README.md
<body>
Migrates content from fluentweb.com that is particular to FAST.
<footer>
For [details on formatting](https://fluentweb.com/prototyping/contribution-policy#pull-request-guidance) pull requests.
> docs: updates developer documentation

- packages/fast-components-react-base/webpack.config.js
- packages/fast-components-react-msft/webpack.config.js
`fast-components-react-base` and `fast-components-react-msft` development environments should now correctly perform a page-reload when source-files change.
closes #201
> setup webpack-dev-server SPA support

- package-lock.json
- packages/fast-animation/package-lock.json
- packages/fast-browser-extensions/package-lock.json
- packages/fast-colors/package-lock.json
- packages/fast-components-class-name-contracts-base/package-lock.json
- packages/fast-components-class-name-contracts-msft/package-lock.json
- packages/fast-components-react-base/package-lock.json
- packages/fast-components-react-msft/package-lock.json
- packages/fast-components-styles-msft/package-lock.json
- packages/fast-development-site-react/package-lock.json
- packages/fast-development-site-react/package.json
- packages/fast-glyphs-msft/package-lock.json
- packages/fast-jest-snapshots-react/package-lock.json
- packages/fast-jss-manager-angular/package-lock.json
- packages/fast-jss-manager-react/package-lock.json
- packages/fast-jss-manager/package-lock.json
- packages/fast-jss-utilities/package-lock.json
- packages/fast-permutator/package-lock.json
- packages/fast-tslint-rules/package-lock.json
- packages/fast-viewer-react/package-lock.json
- packages/fast-viewer-react/package.json
Establish @types/node^9.0.0 dev dependency for packages that rely on @types/react-dom so that @types/node^10.0.0 will not be installed.
closes #335
> fix: travis-CI build-break

- packages/fast-components-react-msft/app/index.tsx
- packages/fast-development-site-react/src/utilities/componentExampleFactory.tsx
- packages/fast-development-site-react/src/utilities/componentFactory.tsx
- packages/fast-markdown-msft-react/package-lock.json
closes #303 
<body>
Adds a design system provider to the component example factory to allow a design system to optionally be passed to style the components that appear on the canvas
<footer>
> fix(dev-site): add design system provider to component example factory

- packages/fast-components-react-msft/src/button/button.tsx
> fix(button): fixes button import which caused it to be unusable outside the monorepository

- .travis.yml
- lerna.json
Ignoring test coverage will eliminate any errors from blocking publish of packages.
- `loglevel=verbose` was removed as it didn't provide any extra details
- added `|` to help bash script execute cleaner
> chore(packages): update to ignore test coverage for publishing

- .travis.yml
Deploying with NPM provider is not working and we think it's because Travis assumes that it's a single package. Instead, we're using Lerna and need it's published argument to work.  This is an attempt to test the theory.
> update to use script in deploy not npm

- packages/fast-components-class-name-contracts-base/src/toggle/index.ts
- packages/fast-components-styles-msft/src/button/index.ts
- packages/fast-components-styles-msft/src/toggle/index.ts
- packages/fast-development-site-react/src/components/site/action-bar.tsx
- packages/fast-development-site-react/src/components/site/component-view-toggle.tsx
closes #342 
There are still 4 warnings in toggle caused by `-ms-high-contrast` media queries - I'm working with the JSS author on how best we can resolve these warnings.
> fix(jss): fix errors caused by un-linked JSS rules

- packages/fast-form-generator-react/app/components/align-horizontal/align-horizontal.tsx
- packages/fast-form-generator-react/app/components/align-vertical/__snapshots__/align-vertical.spec.tsx.snap
- packages/fast-form-generator-react/app/components/align-vertical/align-vertical.tsx
- packages/fast-form-generator-react/app/components/checkbox/__snapshots__/checkbox.spec.tsx.snap
- packages/fast-form-generator-react/app/components/general-example/__snapshots__/general-example.spec.tsx.snap
- packages/fast-form-generator-react/app/components/general-example/general-example.config.ts
- packages/fast-form-generator-react/app/components/general-example/general-example.schema.json
- packages/fast-form-generator-react/app/components/general-example/general-example.spec.tsx
- packages/fast-form-generator-react/app/components/general-example/general-example.tsx
- packages/fast-form-generator-react/app/components/index.ts
- packages/fast-form-generator-react/app/components/number-field/number-field.tsx
- packages/fast-form-generator-react/app/components/text-field/text-field.tsx
- packages/fast-form-generator-react/app/components/theme/theme.tsx
- packages/fast-form-generator-react/app/components/weight-properties/weight-properties.tsx
- packages/fast-form-generator-react/app/index.tsx
- packages/fast-form-generator-react/src/class-name-contracts/form-item.array.class-name-contract.ts
- packages/fast-form-generator-react/src/class-name-contracts/form-item.children.class-name-contract.ts
- packages/fast-form-generator-react/src/form/form-item.align-vertical.tsx
- packages/fast-form-generator-react/src/form/form-item.array.style.ts
- packages/fast-form-generator-react/src/form/form-item.array.tsx
- packages/fast-form-generator-react/src/form/form-item.checkbox.style.ts
- packages/fast-form-generator-react/src/form/form-item.checkbox.tsx
- packages/fast-form-generator-react/src/form/form-item.children.style.ts
- packages/fast-form-generator-react/src/form/form-item.children.tsx
- packages/fast-form-generator-react/src/form/form-item.number-field.style.ts
- packages/fast-form-generator-react/src/form/form.style.ts
- packages/fast-form-generator-react/src/utilities/form-input.style.ts
Closes [#417](https://github.com/Microsoft/fast-dna/issues/417)
<body>
Adds a general examples page that shows all form generator components together (more like they would be on the live site, updates all SVGs to be proper, and tweaks JSS as needed.
<footer>
> feat(form generator): add SVGs, additional JSS, and general examples

- packages/fast-development-site-react/src/components/site/component-wrapper.tsx
- packages/fast-development-site-react/src/utilities/error-boundary.tsx
- packages/fast-development-site-react/src/utilities/index.ts
<body>
Adds an error boundary to the component example wrapper to isolate errors and prevent an issue where the entire view is unable to load due to component specific errors.
closes #436 
<footer>
> feat(dev-site): adds error boundary to dev site component wrapper to prevent entire views from breaking

- .circleci/config.yml
Further removes environment from config.yml completely.
close #427
> chore: remove environment vars for circle-ci

- packages/fast-layouts-react/src/index.ts
<body>
enables a user to import components as expected:
```
import { Column } from "@microsoft/fast-layouts-react"
```
<footer>
closes #553 
> fix(fast-layouts-react): fix export issue to allow Column, Grid, and Page components to be imported from the root level of the package

- CONTRIBUTING.md
The CONTRIBUTING.md should include information about Code Owners, how to become one and where to find the information on who is currently a Code Owner.
> docs: update CONTRIBUTING.md to include Code Owners

- packages/fast-development-site-react/src/components/site/index.tsx
> fix(fast-development-site): fix for component detail stretching full height when dev tools is hidden

- packages/fast-development-site-react/src/components/site/dev-tools.tsx
> fix(fast-development-site): fix devtools stretches vertically when horizontal scrollbar is visible

- packages/fast-form-generator-react/app/components/any-of/__snapshots__/any-of.spec.tsx.snap
- packages/fast-form-generator-react/app/components/one-of/__snapshots__/one-of.spec.tsx.snap
- packages/fast-form-generator-react/src/form/form-item.textarea.tsx
> fix(fast-form-generator-react): sets the value of the textarea to an empty string if it is undefined

- packages/fast-development-site-react/src/components/site/index.tsx
<body>
Theming shipped in 1.9.0 as optional, and while it's not a required prop from an interface level, a bug exists that causes it to be present to render the site. The Site component initial state expects `this.props.themes[0]` as a value. Since undefined is not an array, length does not exist and cannot be checked so an exception is thrown.
<br>
<br>
This PR checks for the existence of an array as well as length in order to set `theme` state on the site component.
closes #696 
<footer>
> fix(fast-development-site): fixes site component issue where state is expected for theme even if it does not exist

- packages/fast-css-editor-react/app/app.tsx
- packages/fast-css-editor-react/app/components/position.spec.tsx
- packages/fast-css-editor-react/src/editor.schema.json
- packages/fast-css-editor-react/src/position/README.md
- packages/fast-css-editor-react/src/position/index.tsx
- packages/fast-css-editor-react/src/position/position.schema.json
Resolves #706
BREAKING CHANGE: The API for the fast-css-editor-react libraries CSSPosition and CSSEditor exports is changing to use strings instead of numbers for the left, right, top and bottom CSS properties. This is a fix needed to map directly to JSS and other CSS systems.
> fix(fast-css-editor-react): update the api to accept strings for position

- packages/fast-components-react-base/src/label/label.schema.json
- packages/fast-components-styles-msft/src/label/index.ts
Closes [#656](https://github.com/Microsoft/fast-dna/issues/656)
update element shift when changing HTML element type, updates schema language
<body>
<footer>
> fix(label): remove label element shift when changing HTML type in configure pane

- packages/fast-components-react-msft/README.md
- packages/fast-components-react-msft/src/button/button.props.ts
- packages/fast-components-react-msft/src/button/button.schema.json
- packages/fast-components-react-msft/src/button/button.spec.tsx
- packages/fast-components-react-msft/src/button/button.tsx
- packages/fast-components-react-msft/src/button/examples.data.tsx
Closes: #702 
BREAKING CHANGE: The API for the fast-components-react-msft button has 4 boolean props (justified, lightweight, outline and primary). These values are mutually exclusive and cannot be applied simultaneously. For this reason an enum is a more appropriate approach. This fix removes those booleans and passes a single prop.
> fix(button): update to use enum for button types

- packages/fast-web-utilities/src/html.ts
> fix(fast-web-utilities): fix an issue where getClientRectWithMargin threw an error in EDGE and IE strict modes due to readonly properties

- packages/fast-components-react-base/src/button/button.tsx
- packages/fast-components-react-base/src/dialog/dialog.tsx
- packages/fast-components-react-base/src/foundation/foundation.spec.tsx
- packages/fast-components-react-base/src/foundation/foundation.ts
- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
- packages/fast-components-react-base/src/hypertext/hypertext.tsx
- packages/fast-components-react-base/src/label/label.tsx
- packages/fast-components-react-base/src/tabs/tab-panel.tsx
- packages/fast-components-react-base/src/tabs/tab.tsx
- packages/fast-components-react-base/src/tabs/tabs.tsx
- packages/fast-components-react-msft/src/button/button.tsx
> fix(foundation): ensures that children are never rendered to the root element by unhandledProps

- packages/fast-components-react-base/app/index.tsx
- packages/fast-components-react-msft/app/app.tsx
- packages/fast-development-site-react/app/app.tsx
- packages/fast-development-site-react/src/components/site/index.tsx
Closes [#621](https://github.com/Microsoft/fast-dna/issues/621)
<body>
<footer>
> feat(fast-development-site-react): add component example transparency as opt-out

- .circleci/config.yml
- build/clean-package-locks.js
- packages/fast-animation/package.json
Updating CircleCI to use workflows will improve performance and allow additional testing through fan-out strategy that will be added later.  With fan-out we can run integration/regression/publishing all in parallel.
closes #428
> chore(circle-ci): update to switch to use workflows

- packages/fast-layouts-react/src/page/page.tsx
> fix(page): replaces "auto" with "0" to fix a cross-browser compatability issue regarding how "auto" is handled

- packages/fast-jss-utilities/src/acrylic.ts
> fix(acrylic): sets background property to undefined instead of null to prevent error due to jss expectations

- README.md
The link was incorrect on "good first issue".
> fix(docs): update link for contributors to find good first issue

- packages/fast-components-react-msft/src/button/button.spec.tsx
- packages/fast-components-react-msft/src/button/button.tsx
> fix(button): add missing super of generateClassNames method when appearance prop is not set

- packages/fast-components-react-base/package.json
<body>
Tab component expects enum which doesn't exist in referenced peer dependency version. Anyone who has v1.9.2 will get compile errors.
<footer>
> fix(fast-components-react-base): update peer dependency version for `fast-web-utilities`

- .codeclimate.yml
Removing `TODO` from `.codeclimate.yml` plugins will ensure that when found in code it will be ignored and we can put this in code with task and description for work to be done later. 
For details on this [plugin](https://docs.codeclimate.com/docs/fixme) 
closes #586
> chore: remove TODO statement check

- packages/fast-components-react-base/src/label/__snapshots__/label.spec.tsx.snap
- packages/fast-components-react-base/src/label/label.spec.tsx
- packages/fast-components-react-base/src/label/label.tsx
- packages/fast-components-react-msft/src/label/__snapshots__/label.spec.ts.snap
- set the class "label" to always show, even when hidden prop is true.
resolve #957
> fix: update label to always apply label class-name

- packages/fast-components-react-base/src/checkbox/checkbox.tsx
As per the issue, we should apply `indeterminate` property irrespective of `checked` state.
Fixes #968
> fix: apply checkbox `indeterminate` property regardless of "checked" state

- packages/fast-components-react-msft/src/flipper/__snapshots__/flipper.spec.tsx.snap
- packages/fast-components-react-msft/src/flipper/examples.data.tsx
Clean up chore for the flipper examples.
> chore: fix the flipper examples to use the correct property name

- packages/fast-components-styles-msft/src/progress/index.ts
> fix: replace lodash reference in MSFT component styles with lodash-es

- packages/fast-components-react-base/package.json
- packages/fast-components-react-base/src/divider/divider.props.ts
- packages/fast-components-react-base/src/image/image.props.ts
- packages/fast-components-react-base/src/text-field/text-field.props.ts
Several base-component prop interfaces we're incorrectly extended, causing type-errors when values we're applied as react props. EG, react defined "type" as an optional string where FAST defines "type" as an enum - when an enum is applied as a prop, an error is generated claiming that an enum is not assignable to a string type.
> fix: update on incorrectly extended prop interfaces

- packages/fast-permutator/__tests__/test-schemas/index.js
- packages/fast-permutator/__tests__/test-utils/index.js
- packages/fast-permutator/package.json
Fixes unit test grammar and adds verbose option to unit test output, so these are shown when running unit tests.
closes #75
> chore: Update grammar used in unit testing output

- packages/fast-development-site-react/src/components/site/index.tsx
> fix: add overflow behavior to dev site pane to ensure all TOC items can be accessed

- packages/fast-components-styles-msft/src/button/index.ts
- packages/fast-components-styles-msft/src/call-to-action/index.ts
- packages/fast-components-styles-msft/src/label/index.ts
- packages/fast-components-styles-msft/src/text-field/index.ts
- packages/fast-components-styles-msft/src/toggle/index.ts
- packages/fast-components-styles-msft/src/utilities/typography.ts
> feat: deprecate responsive type ramp and update ramp to even values

- packages/fast-components-styles-msft/src/utilities/elevation.ts
> fix: ensure that elevation shadow values are rounded to the nearest tenth

- packages/fast-components-styles-msft/src/button/index.ts
- packages/fast-components-styles-msft/src/call-to-action/index.ts
> fix: fix incorrect MSFT button JSS selector chains and add missing padding

- packages/fast-components-react-msft/app/app.tsx
Hiding density slider for the time being because the experience feels broken
> chore: hide density slider

- packages/fast-development-site-react/src/components/site/component-view.tsx
- packages/fast-development-site-react/src/components/site/component-wrapper.tsx
- packages/fast-development-site-react/src/components/site/index.tsx
This change ensures that the entire canvas is filled with the user-defined background color in the component examples view. It also ensures that component separators are derived from the background color, allowing them to look more consistent across light and dark theme experiences.
> feat: apply theme background color to examples view

- packages/fast-components-react-msft/src/button/button.schema.json
> fix: correct misspelled button enum value

- packages/fast-components-styles-msft/src/hypertext/index.ts
Targeting href in the style to apply brand color for hypertext was not working in Edge. Changing the target in the style to be :link and :visited does work in both Edge and Chrome.
closes #883
> fix: style change targeting :link and :visited rather than href

- packages/fast-components-styles-msft/src/hypertext/index.ts
Hypertext hover and focus do not work in Edge
closes: #1159
> fix: hypertext hover and focus do not work in Edge

- packages/fast-components-react-msft/src/text-field/examples.data.tsx
- packages/fast-components-styles-msft/src/divider/index.ts
- packages/fast-components-styles-msft/src/text-field/index.ts
Closes [#1239](https://github.com/Microsoft/fast-dna/issues/1239)
Removes margin from components and addresses placeholder text color for the disabled state in text-field.
Noticed margin and placeholder issue when creating `text action` component.
> fix: remove margins from components and fix text-field placeholder color in disabled state

- website/static/css/custom.css
This small fix adds new CSS properties to for table of contents on the doc site. These properties prevent the line from wrapping onto the next line and adds an ellipsis.
Some long TOC items were wrapping onto the next item making it unreadable. This fix forces the text to stay on one line and get an ellipsis when it is cut off.
> chore: small fix to text wrap in toc for doc site

- packages/fast-form-generator-react/src/class-name-contracts/form-item.array.class-name-contract.ts
- packages/fast-form-generator-react/src/class-name-contracts/form-item.children.class-name-contract.ts
- packages/fast-form-generator-react/src/form/form-item.array.spec.tsx
- packages/fast-form-generator-react/src/form/form-item.array.style.ts
- packages/fast-form-generator-react/src/form/form-item.array.tsx
- packages/fast-form-generator-react/src/form/form-item.children.style.ts
- packages/fast-form-generator-react/src/form/form-item.children.tsx
- packages/fast-form-generator-react/src/form/form-item.section-link.tsx
- packages/fast-form-generator-react/src/form/form-section.tsx
- packages/fast-form-generator-react/src/form/form-section.utilities.tsx
- packages/fast-form-generator-react/src/form/sorting.tsx
- packages/fast-form-generator-react/src/utilities/form-input.style.ts
This change updates the handling of the array data type in the `fast-form-generator-react` package to use a simplified method of controlling it and removes the drop down menu.
This change will go into a feature branch which also addresses a UI change for the handling of the React children data type.
This simplifies the UI for adding and removing array items.
[ ] This change causes current functionality to break.
> feat: simplify array UI by removing the dropdown menu

- README.md
- docs/en/contributing/install.md
- docs/en/contributing/packages.md
- docs/en/contributing/standards.md
- docs/en/contributing/working.md
Update to link into start of developer documentation.  Currently, this start page/getting started is work in progress.
When clicking on current link it takes you to the developer documentation main readme.  This is great if that readme contains getting started or different documentation. But, on initial load of this page it's the same exact content and this might be confusing to users.  They may immediately click away without seeing out other developer documentation.  This will temporarily change the link to the install page of documentation.
> chore: update link to developer documentation install page

- packages/fast-components-styles-msft/src/heading/index.ts
The MSFT design language has proposed an update to use semibold across all headings. This aligns the change in code. 
> feat: update MSFT headings to semibold

- packages/fast-components-styles-msft/src/utilities/typography.ts
This reverts commit 0698ad11efb32f93f44e383d89d9e64132d5107a.
> fix: revert "update the T4 type ramp to 28 size and 36 line-height (#1261)"

- packages/fast-components-styles-msft/src/radio/index.ts
In some cases the selector that adds padding between the label and toggle on a radio button gets overridden by a padding=0 style on the label, this is fragile because of the issue Jane describes here - https://github.com/Microsoft/fast-dna/issues/1279
It showed up in the print dialog for edge zero where radio buttons had no space between toggle and label.
While we chew on the bigger specificity issue it seemed worthwhile to fix the issue with radio button by using margin instead of padding for spacing.  This is the appropriate property to use anyway and avoids the collision with the other padding value.
- [X ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [x ] I have tested my changes.
> fix: update to use margin instead of padding for radio button label

- packages/fast-components-styles-msft/src/action-toggle/index.ts
- packages/fast-components-styles-msft/src/action-trigger/index.ts
Disabled action toggle glyph not dimmed like text, was using wrong color for glyph in css
Disabled action toggles don't look right. 
Fixes 1288 - https://github.com/Microsoft/fast-dna/issues/1288
> fix: update disabled action toggle/trigger glyph color

- build/documentation/copy-package-readme.js
- package.json
- website/sidebars.json
This PR adds a script that automates the copying of documentation files into `docs/en/packages`, a folder that stores package `readme` pages to be used by Docusaurus. For this script there is a new npm command in the main project's package.json, `docs:build`.
Also included is this script is a function that handles the execution of  `copy-package-readme.js`'s dry-run. For the dry run there is a new npm command in the main project's package.json, `docs:dry-run`.
To test changes:
1. In the root folder, run `npm run docs:dry-run`. The output here should give an overview of what this command will do.
3. run `npm run docs:build`. If successful this command will:
- add to/update all package `readme.md` files in `docs/en/packages`
- add to/update the `Packages` array in `website/sidebars.json`
- …
> chore: update automation process for docusaurus documentation generation

- packages/fast-components-react-msft/src/context-menu/examples.data.tsx
- packages/fast-components-styles-msft/src/context-menu-item/index.ts
- packages/fast-components-styles-msft/src/context-menu/index.ts
Fix context menu styles to match new designs
Fix context menu styles to match new designs Design here:
https://www.figma.com/file/FnigSVQnGOXbEW8HQuEu1ZMo/UIS-Components?node-id=133%3A0
> fix: context menu styles to match new designs

- packages/fast-components-react-base/src/tabs/tabs.spec.tsx
- packages/fast-components-react-base/src/tabs/tabs.tsx
Preventing Type Error when active ID is not found among current tabs.
https://github.com/Microsoft/fast-dna/issues/1218
> fix: Changing activeID on Tabs component causes type error

- packages/fast-navigation-generator-react/app/configs/example.data.ts
- packages/fast-navigation-generator-react/src/navigation/navigation.props.ts
- packages/fast-navigation-generator-react/src/navigation/navigation.spec.tsx
- packages/fast-navigation-generator-react/src/navigation/navigation.tsx
- packages/fast-navigation-generator-react/src/navigation/navigation.utilities.spec.ts
- packages/fast-navigation-generator-react/src/navigation/navigation.utilities.ts
Shows the text as the children string if children is a string, adds a root level expandable item.
Changing the location requires a root level item and children can sometimes be strings and not components. This should resolve both of these issues.
> feat: add root level component navigation and ability to have string children

- packages/fast-components-styles-msft/src/patterns/input-field.ts
- packages/fast-components-styles-msft/src/text-area/index.ts
- packages/fast-components-styles-msft/src/text-field/index.ts
Closes [#1374](https://github.com/Microsoft/fast-dna/issues/1374)
Adds a pattern for the shared MSFT styling of input fields. 
The same pattern existed in _text area_ and _text field_ and would soon exist in other components (_number field_, etc.) therefore a shared pattern makes sense.
> feat: add common MSFT input field style pattern

- build/documentation/copy-package-readme.js
Fixes #1392 
Makes it so that the `copy-package-readme.js` script creates the `docs/en/packages` folder if it doesn't exist, instead of generating an error.
Without this change running `npm run docs:build` or `npm run docs:dry-run` would fail if the `docs/en/packages` folder didn't exist.
> fix: update to create packages folder when it doesn't already exist

- packages/fast-components-class-name-contracts-base/src/listbox/index.ts
- packages/fast-components-react-base/src/listbox-item/examples.data.tsx
- packages/fast-components-react-base/src/listbox-item/listbox-item.tsx
- packages/fast-components-react-base/src/listbox/examples.data.tsx
- packages/fast-components-react-base/src/listbox/listbox.props.ts
- packages/fast-components-react-base/src/listbox/listbox.schema.json
- packages/fast-components-react-base/src/listbox/listbox.spec.tsx
- packages/fast-components-react-base/src/listbox/listbox.tsx
- add and implement autofocus and disabled props to listbox, these were found to needed to implement Select component
- exposed some utility static functions.  These are used by the Select component when it wants to manipulate selected items when the listbox is not actually instanciated.
Towards a working select component
> feat: add additional functionality to listbox base

- packages/fast-form-generator-react/src/form/form-item.children.spec.tsx
- packages/fast-form-generator-react/src/form/form-item.children.tsx
This allows the addition of strings as children without returning an object, which while valid causes some confusion.
Standardization of the returned object to a simple string.
> fix: fixes an issue where objects were returned when strings were selected in the children UI

- packages/fast-components-styles-msft/src/text-action/index.ts
closes #1418 
Focus is applied on text action dynamically. The overall text action wrapper is shown to have focus when the text field itself is focused. The focus visible selector applied to text field should zero out the text field focus state to ensure that there is no focus rect when focused.
> fix: remove border during focus visible from text field in text action

- packages/fast-components-react-base/src/listbox/listbox.spec.tsx
Listbox tests were spewing warnings about attaching elements to document body.  Created a container and used that instead.
Warnings are bad...
> fix:  listbox tests no longer spew warnings

- packages/fast-components-react-base/src/number-field/examples.data.tsx
- packages/fast-components-react-base/src/number-field/number-field.schema.json
- packages/fast-components-react-msft/src/number-field/examples.data.tsx
The `defaultValue` attribute for inputs are expected to be string. I noticed that we were typing our examples as "any" in several places to overcome type errors. I think these errors were actually valid. Default value is expected as a string, our examples and schema showed it as a number. I don't believe this is a breaking change as the components actual contract is not changing.
- [] This change causes current functionality to break.
> fix: remove defaultValue from number field schema and examples

- packages/fast-components-styles-msft/README.md
- packages/fast-components-styles-msft/package.json
- packages/fast-components-styles-msft/src/utilities/color/index.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-foreground-hint.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.ts
- packages/fast-components-styles-msft/src/utilities/color/palette.ts
Adds hover and active states to the neutral-foreground recipe
> feat: add neutral-foreground states

- packages/fast-components-class-name-contracts-base/src/horizontal-overflow/index.ts
- packages/fast-components-react-base/src/horizontal-overflow/examples.data.tsx
- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.node.spec.tsx
- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.spec.tsx
- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
closes #1428 
Adds a className to provide more fine grain control over the list item being render on the wrapper of horizontal overflow children. 
*Note*: If the className is undefined, add style for the list item to ensure it renders with `display: inline-block`
> feat: add class name for horizontal overflow items

- packages/fast-components-react-base/src/context-menu/context-menu.props.ts
- packages/fast-components-react-base/src/context-menu/context-menu.spec.tsx
- packages/fast-components-react-base/src/context-menu/context-menu.tsx
- packages/fast-components-react-base/src/context-menu/examples.data.tsx
Adds a public function the `ContextMenu` to bring focus to the appropriate menu item. Also adds an opt-in prop (`enableFocusVisible`) to bring focus to invoke the focus method when the component mounts, which is generally desired. Making `enableFocusVisible` false by default ensures we don't change behavior of existing implementations of `ContextMenu`.
closes #1398
> feat: add focus features to ContextMenu

- packages/fast-components-styles-msft/package.json
- packages/fast-components-styles-msft/src/design-system/index.ts
- packages/fast-components-styles-msft/src/utilities/color/accent-foreground-cut.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/accent-foreground.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/accent.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/color-constants.ts
- packages/fast-components-styles-msft/src/utilities/color/index.ts
- packages/fast-components-styles-msft/src/utilities/color/palette.ts
Integrates `@microsoft/fast-colors` palette generation tooling into MSFT style utilities
> feat: integrate fast-dna/colors palette generation into msft color utilities

- packages/fast-colors/__tests__/parseColorTest.test.ts
- packages/fast-colors/src/colorlib/parseColor.ts
Adds utility function to help identify which color format a color string conforms to. This will enable authors to implement opt-in color parsing.
For instance, an app may decide that they want to support only `HexRGB` and `WebRGB` formats - using the existing `parseColor` would make explicit references to code that is not needed for processing those formats and lead to in-product dead code.
Providing color identifiers allows authors to identify and parse colors without bundling parsing code unnecessary for their app.
closes #1470
> feat: add color identifier functions

- packages/fast-components-styles-msft/src/utilities/color/index.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-focus.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-focus.ts
Adds recipe for generating the neutral-focus color
> feat: add neutral-focus recipe

- packages/fast-colors/__tests__/parseColorTest.test.ts
- packages/fast-colors/src/colorlib/parseColor.ts
- packages/fast-components-styles-msft/src/utilities/color/accent-foreground.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/common.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/palette.spec.ts
Adds strict string validation for color strings to ensure that they are properly formatted. Also improves string hex string parser to accept shorthand hex (3 digit for RGB, 4 digit for RGBA/ARGB) to improve compatibility with CSS colors.
Performance impact of the change: https://jsperf.com/rgb-regex-vs-string-check
closes #1473, #1474
> feat: adds shorthand hex parsing to color parsers

- packages/fast-jss-utilities/src/apply-focus-visible.ts
Adds the focus-visible attribute selector to the applyFocusVisible utility. This is necessary for both compliance with the polyfill but also because React has started stripping the `.focus-visible` class during render cycles when class attribute values change.
closes #1443
> fix: adding attribute selector to focus-visible selector

- build/documentation/generate-typedocs.js
- package.json
Implements #1382
Creates a script that copies package `readme.md` files into `docs/en/packages`. Then uses typedoc to generate Typedoc API documentation that are also added to `docs/en/packages`. Converts these api files into markdown using the `markdown` theme from [typedoc-plugin-markdown](https://github.com/tgreyuk/typedoc-plugin-markdown). Also contains a dry-run version for the script.
To run the dry run:
Run `npm run docs:build:dry-run` in root
To run the regular process:
Run `npm install` to install the new `typedoc` and `typedoc-plugin-markdown` packages
Run `npm run docs:build:api` in root
`cd website`
Run `npm run start`
Navigate to the relevant package readme pages, scroll to the bottom, there should be a link to the related typeoc api doc there
When `npm run build` is run in …
> chore: add script for typedoc docusaurus integration

- packages/fast-components-styles-msft/src/action-toggle/index.ts
- packages/fast-components-styles-msft/src/action-trigger/index.ts
- packages/fast-components-styles-msft/src/call-to-action/index.ts
- packages/fast-components-styles-msft/src/heading/index.ts
- packages/fast-components-styles-msft/src/paragraph/index.ts
- packages/fast-components-styles-msft/src/subheading/index.ts
> fix: increase specificity on MSFT styled components which are derived from other MSFT components

- packages/fast-components-react-base/src/select/select.tsx
Select was focusing on next item rather than select trigger on menu close.  This forces focus back to the trigger.
> fix: update focus events on keyboard close of menu

- packages/fast-components-styles-msft/src/action-toggle/index.ts
- packages/fast-components-styles-msft/src/action-trigger/index.ts
- packages/fast-components-styles-msft/src/call-to-action/index.ts
a negative margin was introduced to `<ActionToggle/>`, `<ActionTrigger/>` and `<CallToAction/>` causing it to render outside its parents container.
Before:
After:
> fix: remove -10 margin from components that use Justified appearance

- packages/fast-jss-manager-react/src/design-system-provider.spec.tsx
- packages/fast-jss-manager-react/src/design-system-provider.tsx
Adds memoization mechanisms to the `DesignSystemProvider` so that a new design system object will only be created directly after props or context changes. This will allow the JSSManager to more accuratly determine if designSystem values have changed and prevent un-necessary recompiles of stylesheets.
closes #1517
> fix: update to prevent new design-system object creation when values don't change

- packages/fast-components-react-base/src/listbox/README.md
- packages/fast-components-react-base/src/listbox/listbox.props.ts
- packages/fast-components-react-base/src/listbox/listbox.spec.tsx
- packages/fast-components-react-base/src/listbox/listbox.tsx
In order to support the auto-suggest component listbox required some additional functionality:
- a prop to disable typeAhead functionality
- a prop for a callback when an item is invoked
- a behavior where supplying a new value for the "defaultSelection" prop in uncontrolled mode essentially resets focus and selection.
Functionality required to support auto-suggest
> feat: add enhancements for auto-suggest

- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.spec.tsx
- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
Added a private reference to the resize observer (resizeObserver) in horizontal-overflow. Assign the observer if it is created on component did mount and disconnect it on component will unmount
Bugfix for #1515
> fix: update to disconnect the resize observer on component will unmount

- packages/fast-components-react-base/src/select/select.spec.tsx
- packages/fast-components-react-base/src/select/select.tsx
- packages/fast-components-react-msft/src/select/select.spec.tsx
- packages/fast-components-react-msft/src/select/select.tsx
Noticed that we were ignoring trigger render functions provided in props.  Also cleaned up syntax a bit.
Our custom select component should support custom trigger render functions just like our base component does
> fix: custom trigger was being ignored in styled select

- build/documentation/copy-package-readme.js
Makes small improvements to the `build/documentation/copy-package-readme.js` file including:
- uses the `chalk` dependency to make console.log statements easier to read
- makes the terminal output itself easier to read, makes it easier to see if all doc readmes were updated successfully
- makes it so that the glob function recognizes lowercase `readme` titles in POSIX systems 
I would notice these smaller issues while writing `build/documentation/generate-typedocs.js` and decided to make a separate PR for them.
> chore: refactor how copy readme script prints output to terminal 

- packages/fast-components-styles-msft/src/badge/index.ts
- packages/fast-components-styles-msft/src/design-system/index.ts
- packages/fast-components-styles-msft/src/heading/index.ts
- packages/fast-components-styles-msft/src/paragraph/index.ts
- packages/fast-components-styles-msft/src/patterns/input-field.ts
- packages/fast-components-styles-msft/src/subheading/index.ts
- packages/fast-components-styles-msft/src/utilities/fonts.ts
closes #306 
This is a transparent change to how we manage font weights in order to provide support for variable font use. Instead of using internal constants, we expose a way to support user declared values. This allows users to pass different design system values for fontWeight depending on if they want to / can support variable fonts in a given experience. Additionally, this is an important move as we've been operating under an internal assumption that font weights are constant and defined but font family is not. Technically while certain font families support similar weights, our previous implementation was tightly coupled to the MSFT SegoeUI font family.
> feat: add design system support for font weights

- packages/fast-layouts-react/src/utilities/breakpoint-tracker.spec.ts
- packages/fast-layouts-react/src/utilities/breakpoint-tracker.ts
Currently there is no way to gather the current breakpoint value without an update. This PR exposes a public function which provides access to the current breakpoint at any given time without needing to trigger an update.
> feat: add public function to breakpoint tracker to get current breakpoint

- packages/fast-jss-manager-react/src/design-system-provider.tsx
- packages/fast-jss-manager/babel.config.js
- packages/fast-jss-manager/package.json
- packages/fast-jss-manager/src/index.spec.ts
- packages/fast-jss-manager/src/index.ts
- packages/fast-jss-manager/tsconfig.json
- packages/fast-jss-utilities/src/with-defaults.ts
Deeply merging array values is unperformant and generally undesired. Fixes merging to merge arrays by value
> fix: update design-system merging strategy to not deeply merge array values

- package.json
- packages/fast-animation/package.json
- packages/fast-breakpoint-tracker-react/package.json
- packages/fast-browser-extensions/package.json
- packages/fast-colors/package.json
- packages/fast-components-class-name-contracts-base/package.json
- packages/fast-components-class-name-contracts-msft/package.json
- packages/fast-components-foundation-react/package.json
- packages/fast-components-react-base/package.json
- packages/fast-components-react-msft/package.json
- packages/fast-components-styles-msft/package.json
- packages/fast-development-site-react/package.json
- packages/fast-glyphs-msft/package.json
- packages/fast-jest-snapshots-react/package.json
- packages/fast-jss-manager-angular/package.json
- packages/fast-jss-manager-react/package.json
- packages/fast-jss-manager/package.json
- packages/fast-jss-utilities/package.json
- packages/fast-layouts-react/package.json
- packages/fast-markdown-msft-react/package.json
- packages/fast-sketch-library/package.json
- packages/fast-tooling-react/package.json
- packages/fast-tslint-rules/package.json
- packages/fast-web-utilities/package.json
Affixes typescript to `v3.3.3` because later versions exhaust allotted memory. Seems to be the same issue as https://github.com/Microsoft/TypeScript/issues/30794
> chore: affix typescript to v3.3.3

- build/documentation/generate-typedocs.js
- website/pages/_config.yml
This fix adds a `_config.yml` file to the `website/build` folder so that github pages will load files with an underscore prefix. Also changes when 'API Reference' links are added to `readme.md` files to prevent them from linking to api documentation that wasn't built. 
Fix #1544 
Github pages wouldn't recognize the documentation site api files because they had an underscore prefix, a `.nojekyll` or `_config.yml` file needed to be added to the sites root folder for them to be recognized. More info on can be found [here](https://help.github.com/en/articles/files-that-start-with-an-underscore-are-missing). 
'API Reference' links would be added to package readme.md documentation files even if the api documentation didn't build correctly. This would lead to a 404 error, since the link wasn't …
> fix: prevent documentation site API links from routing to 404 pages

- packages/fast-components-react-msft/src/background/background.props.ts
- packages/fast-components-styles-msft/README.md
- packages/fast-components-styles-msft/src/utilities/color/accent-fill.ts
- packages/fast-components-styles-msft/src/utilities/color/accent.ts
- packages/fast-components-styles-msft/src/utilities/color/background-color.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/background-color.ts
- packages/fast-components-styles-msft/src/utilities/color/index.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-fill.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-focus.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-layer.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-layer.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-outline.ts
- packages/fast-components-styles-msft/src/utilities/color/palette.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/palette.ts
Adds new color recipes for applying layer background and the design system background color.
closes  #1610
> feat: add layer and background-color recipes

- packages/fast-development-site-react/src/components/site/index.tsx
Added a mapping for "en-rtl" so rtl is actually applied when it is selected
Noticed it wasn't working while developing components.
> fix: Update locales so en-rtl applies rtl attribute

- packages/fast-layouts-react/src/utilities/breakpoint-tracker.spec.ts
- packages/fast-layouts-react/src/utilities/breakpoint-tracker.ts
Update current breakpoint value in BreakpointTracker when new Breakpoint values is set.
https://github.com/Microsoft/fast-dna/issues/1625
- [x ] I have tested my changes.
> fix: update the current breakpoint value when new breakpoints are set

- packages/fast-jss-utilities/src/apply-focus-visible.ts
Style properties assigned to a function value were not getting updated with the result of the function because of an issue with JSS tracking the selector string. Changing the position of the attribute selector fixes the issue in all browsers but this is really a JSS issue.
closes #1641
> fix: changes focus-visible polyfill selector so that it works in edge

- packages/fast-components-react-base/src/checkbox/checkbox.props.ts
- packages/fast-components-react-base/src/checkbox/checkbox.schema.json
- packages/fast-components-react-base/src/checkbox/checkbox.spec.tsx
- packages/fast-components-react-base/src/checkbox/checkbox.tsx
- packages/fast-components-react-base/src/checkbox/examples.data.tsx
- packages/fast-components-react-msft/src/checkbox/checkbox.schema.json
Closes issue referenced in #1639. Same issue for radio is present for checkbox due to the nested nature of the input.
> feat: add name prop to checkbox component

- packages/fast-components-react-msft/src/text-action/text-action.props.ts
- packages/fast-components-react-msft/src/text-action/text-action.tsx
Closes [#1645](https://github.com/Microsoft/fast-dna/issues/1645)
Adds callbacks for onFocus and onBlur to the input within text action
> fix: add onFocus and onBlur callbacks to the input within text action

- packages/fast-tooling-react/src/form/form/form.tsx
Addresses an issue where in the uncontrolled version of the form generator with regards to the "oneOf" and "anyOf" keywords results in erroneous pathing when trying to navigate through nested objects.
> fix: allow navigation in nested oneOf/anyOf objects when the form is uncontrolled

- packages/fast-tooling-react/app/pages/form/index.ts
- packages/fast-tooling-react/src/__tests__/schemas/nested-one-of.schema.json
- packages/fast-tooling-react/src/form/align/align.spec.tsx
- packages/fast-tooling-react/src/form/file-upload/file-upload.spec.tsx
- packages/fast-tooling-react/src/form/form/form-control.spec.tsx
- packages/fast-tooling-react/src/form/form/form-control.tsx
- packages/fast-tooling-react/src/form/form/form-item.array.props.ts
- packages/fast-tooling-react/src/form/form/form-item.checkbox.spec.tsx
- packages/fast-tooling-react/src/form/form/form-item.children.props.ts
- packages/fast-tooling-react/src/form/form/form-item.number-field.spec.tsx
- packages/fast-tooling-react/src/form/form/form-item.props.tsx
- packages/fast-tooling-react/src/form/form/form-item.section-link.spec.tsx
- packages/fast-tooling-react/src/form/form/form-item.section-link.tsx
- packages/fast-tooling-react/src/form/form/form-item.select.spec.tsx
- packages/fast-tooling-react/src/form/form/form-item.textarea.spec.tsx
- packages/fast-tooling-react/src/form/text-align/text-align.spec.tsx
- packages/fast-tooling-react/src/form/theme/theme.spec.tsx
Places the oneOf/anyOf select dropdown in a single location and fixes the section link click.
Also resolves #1671 
> fix: resolves an issue where clicking on a section link that contained a oneOf/anyOf keyword results in an exception

- packages/fast-tooling-react/src/form/form/form-item.array.props.ts
- packages/fast-tooling-react/src/form/form/form-item.array.spec.tsx
- packages/fast-tooling-react/src/form/form/form-item.array.style.ts
- packages/fast-tooling-react/src/form/form/form-item.array.tsx
- packages/fast-tooling-react/src/form/form/form-item.section-link.props.ts
- packages/fast-tooling-react/src/form/form/form-item.section-link.spec.tsx
- packages/fast-tooling-react/src/form/form/form-item.section-link.style.ts
- packages/fast-tooling-react/src/form/form/form-item.section-link.tsx
- packages/fast-tooling-react/src/form/utilities/form.tsx
Shows a red underline on objects and arrays if they are invalid or if they contain invalid data.
Closes #1663 
> feat: show a red underline for objects and arrays if they contain invalid data

- packages/fast-components-react-base/src/radio/radio.schema.json
- packages/fast-components-react-msft/src/radio/radio.schema.json
I noticed that the schema for radio did not properly identify the `inputId` prop as required. This PR is to fix that.
> fix: correct radio schema to identify inputId as required property

- packages/fast-components-styles-msft/src/action-toggle/index.ts
- packages/fast-components-styles-msft/src/action-trigger/index.ts
- packages/fast-components-styles-msft/src/context-menu-item/index.ts
- packages/fast-components-styles-msft/src/text-action/index.ts
1. Action toggle/trigger lightweight disabled icon color is wrong, but goes right on hover.
2. Text action border missing hover state color change
3. Context menu item foreground should not change colors on states
> fix: styling for actionToggle, contextMenuItem & textAction

- packages/fast-tooling-react/app/pages/form/index.ts
- packages/fast-tooling-react/src/__tests__/schemas/merged-one-of.schema.json
- packages/fast-tooling-react/src/form/form/form-section.tsx
- packages/fast-tooling-react/src/form/utilities/form.spec.ts
- packages/fast-tooling-react/src/form/utilities/form.tsx
Uses a merge to correctly validate against oneOf/anyOf subschemas.
Resolves #1684 
> fix: use a merge strategy for oneOf/anyOfs during validation

- packages/fast-components-react-base/src/auto-suggest/auto-suggest.tsx
- packages/fast-components-react-base/src/listbox/listbox.tsx
I noticed weird scrolling behavior on these components, realized we weren't marking the events as handled so browser did the scroll thing.
Poor user experience, focused elements could get scrolled out of view.
> fix: handle key arrow events to prevent unwanted scrolling in listbox & autosuggest

- packages/fast-tooling-react/package.json
- packages/fast-tooling-react/src/data-utilities/location.spec.ts
- packages/fast-tooling-react/src/data-utilities/location.ts
- packages/fast-tooling-react/src/data-utilities/mapping.ts
- packages/fast-tooling-react/src/form/form/form-item.section-link.tsx
- packages/fast-tooling-react/src/form/form/form-section.tsx
- packages/fast-tooling-react/src/form/form/form.tsx
- packages/fast-tooling-react/src/form/utilities/form.spec.ts
- packages/fast-tooling-react/src/form/utilities/form.tsx
Updates the string mapping from data locations to schema locations to primarily rely on the JSON schema instead of the data. This allows for navigation without data as well as more reliable nesting behavior for oneOf/anyOf arrays.
Closes #1689, #1683 
> feat: add ability to traverse form without data

- packages/fast-components-styles-msft/src/button/index.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-foreground-hint.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-foreground-hint.ts
- packages/fast-components-styles-msft/src/utilities/color/palette.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/palette.ts
There are several circumstances where we need to retrieve a swatch that has a contrast relative to some other contrast. This change introduces a genericised function that allows doing so where the inputs and conditions can be customized to the circumstance.
> fix: adds utility to retrieve swatch based on contrast comparisons

- packages/fast-components-styles-msft/src/typography/index.ts
Changes typography to use `...applyScaledTypeRamp()` so type reacts to design system density changes. If its decided to opt out of scaling you can wrap your `<Typohgraphy />` component in a `<DesignSystemProvider />` and lock the density.
Closes: #1759
> feat: add scaled type ramp to typography

- packages/fast-color-explorer/app/app.tsx
- packages/fast-color-explorer/app/design-system.ts
- packages/fast-color-explorer/app/gradient.tsx
- packages/fast-color-explorer/app/state.ts
- packages/fast-components-styles-msft/src/design-system/index.ts
- packages/fast-components-styles-msft/src/utilities/color/accent-foreground.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/accent.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/accent.ts
- packages/fast-components-styles-msft/src/utilities/color/color-constants.ts
- packages/fast-components-styles-msft/src/utilities/color/palette.spec.ts
- packages/fast-components-styles-msft/src/utilities/design-system.ts
- Added base accent and neutral color to design system to enable subsequent change in palette generation.
- Updated color explorer app to use design system and to indicate base colors.
Removes the constant for accent color, which needs to update when the accent color changes or the accent palette is regenerated.
This change is necessary for another change that will adjust the palette generation such that the accent color is not necessarily in the middle.
> fix: track base colors in design system

- packages/fast-components-styles-msft/src/checkbox/index.ts
- packages/fast-components-styles-msft/src/radio/index.ts
As described in #1800, the radio and checkbox styling within `fast-components-styles-msft` is currently showing it's `:hover` styling even while `disabled`.
I have corrected this by adding an additional [:enabled](https://www.w3.org/TR/selectors-3/#UIstates) CSS selector to the styling of both elements.  This has [great browser support](https://caniuse.com/#search=%3Aenabled) and resolves the issue as shown below.
Fixes #1800 
No.
- There do not appear to be any tests around the styling
- I have visual tested my changes with the .gifs above
- No documentation to update
> fix: remove hover styling from radios and checkboxes when disabled

- packages/fast-tooling-react/app/pages/code-preview/examples.data.ts
- packages/fast-tooling-react/src/data-utilities/mapping.spec.ts
- packages/fast-tooling-react/src/data-utilities/mapping.ts
Fixes an issue where nested children components that were self closing without attributes showed an indent and multiple children components would not display.
> fix: address formatting issue with self closing children and multiple children components

- packages/fast-tooling-react/src/navigation/navigation-tree-item.tsx
This fixes a build break caused by a TypeScript update where unnecessary and incorrect type declarations can take precedence over implicit types.
> fix: removed an unnecessary type assigned to the navigation items in Navigation

- packages/fast-components-react-base/src/index.ts
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.tsx
Realized the export for the viewport positioner component got left behind with my test code
Component isn't much use if not exported
> fix: add missing viewport positioner export

- packages/fast-components-styles-msft/src/text-action/index.ts
Closes [#1854](https://github.com/microsoft/fast-dna/issues/1854)
TextAction after glyph margins were incorrect, causing it to appear with no spacing from the end edge of the container. Now fixed.
> fix: addresses incorrect after-glyph margin in text action

- packages/fast-components-react-base/src/select/select.tsx
Select menu could remain open when focus was put outside of the menu.
The expected user interaction for this type of menu is that it does not remain open when focus is elsewhere.  Our previous mechanism only caught loss of focus as a result of a mouse click.
Fixes:
https://github.com/microsoft/fast-dna/issues/1814
> fix: select menu closes on blur event

- packages/fast-tooling-react/src/data-utilities/location.spec.ts
- packages/fast-tooling-react/src/data-utilities/location.ts
- packages/fast-tooling-react/src/data-utilities/mapping.spec.ts
- packages/fast-tooling-react/src/data-utilities/mapping.ts
The mapDataToComponent utility was unable to identify children inside of array objects, this has been addressed.
Resolves #1813 
> fix: addresses an issue in the mapDataToComponent utility where plugins and children would not work on objects inside arrays

- packages/fast-components-styles-msft/src/checkbox/index.ts
Set the checkbox cursor on hover, but not if disabled.
All actionable components should respond to hover with a cursor change.
> fix: set checkbox cursor to pointer on hover

- packages/fast-components-styles-msft/src/patterns/input-field.ts
Updated active state fill and fixed focus border.
Fill should not change on active state because it causes an undesirable flash.
Fixed an issue with the focus rect caused by the underlying input styling.
> feat: update outline field style

- packages/fast-color-explorer/app/app.tsx
- packages/fast-color-explorer/app/color-blocks.tsx
- packages/fast-color-explorer/app/colors.ts
- packages/fast-color-explorer/app/control-pane.tsx
- packages/fast-color-explorer/app/design-system.ts
- packages/fast-color-explorer/app/gradient.tsx
- packages/fast-color-explorer/app/state.ts
-Added a marker on the gradients for the base input color
-Added hover and active to the neutral foreground example
Part of the color algorithm update, to support visualizing the base ramp color in its position.
> feat: color explorer default state and base color marker

- packages/fast-components-styles-msft/src/button/index.ts
- packages/fast-components-styles-msft/src/hypertext/index.ts
- packages/fast-components-styles-msft/src/lightweight-button/index.ts
- packages/fast-components-styles-msft/src/patterns/button.ts
Updated lightweight button underline to 1px on hover/active, 2px on focus.
Updated hyperlink underline to 1px on rest/hover/active, 2px on focus.
The hover and active underline should match with normal outline widths (1px), only focus should use the focus width (2px).
> feat: update lightweight button and hyperlink underline size

- packages/fast-components-styles-msft/src/utilities/color/accent-foreground.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-fill-card.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-fill-input.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-fill-stealth.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-fill.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/palette.spec.ts
- packages/fast-components-styles-msft/src/utilities/design-system.spec.ts
Just a little typo I found going through some tests.
> chore: update typo in tests

- packages/fast-tooling-react/app/pages/form.tsx
- packages/fast-tooling-react/app/pages/form/plugin/plugin.ts
- packages/fast-tooling-react/src/__tests__/schemas/plugin.schema.json
- packages/fast-tooling-react/src/form/form/form.tsx
- packages/fast-tooling-react/src/form/utilities/form.spec.ts
This fixes the generated navigation when using tightly nested oneOfs.
> fix: allows the navigation to update using the active location when new props are passed

- packages/fast-color-explorer/app/color-blocks.tsx
- packages/fast-components-styles-msft/src/design-system/design-system.schema.ts
- packages/fast-components-styles-msft/src/design-system/index.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-focus.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-focus.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-foreground-hint.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-foreground.ts
- packages/fast-components-styles-msft/src/utilities/color/palette.ts
- packages/fast-components-styles-msft/src/utilities/design-system.ts
Updated neutral foreground recipes to be based on contrast instead of offset.
Deprecated references to "light" or "dark" offsets or recipes.
This is to address the design when there are multiple app layers with increasing color depth, and the contrast increases between the layers because the foreground text was fixed white or almost black.
> feat: update neutral foreground recipes to be based on contrast

- packages/fast-components-styles-msft/src/accent-button/index.ts
- packages/fast-components-styles-msft/src/button/index.ts
- packages/fast-components-styles-msft/src/utilities/color/index.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-focus.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-focus.ts
Updated neutral focus recipe to be based on contrast.
Design feedback was that the focus rect was too contrasty as previously designed and implemented.
This update makes it relative to the background, and also adds an inner ring where necessary like on an accent button.
> feat: update neutral focus recipe to be based on contrast

- packages/fast-components-styles-msft/src/design-system/design-system.schema.ts
- packages/fast-components-styles-msft/src/design-system/index.ts
- packages/fast-components-styles-msft/src/utilities/border.ts
- packages/fast-components-styles-msft/src/utilities/design-system.ts
This change adds a new design system value for elevated corner radius instances. Previously this was calculated to be twice the size of the corner radius; however, when working with larger numbers the delta becomes extreme, and a separate property provides greater flexibility.
> feat: add unique design system value for elevated corner radius

- packages/fast-components-styles-msft/README.md
- packages/fast-components-styles-msft/src/auto-suggest/index.ts
- packages/fast-components-styles-msft/src/context-menu/index.ts
- packages/fast-components-styles-msft/src/dialog/index.ts
- packages/fast-components-styles-msft/src/select/index.ts
- packages/fast-components-styles-msft/src/utilities/border.ts
Added applyElevatedCornerRadius and deprecated the 'floating' version of the same.
The new design system property is called is called “elevated” and it is intended to be used for all elevated surfaces. “Floating” generally refers to higher elevation items like dialogs or drop-lists.
> feat: added applyElevatedCornerRadius and deprecated the 'floating' version

- packages/fast-components-react-base/src/viewport-positioner/README.md
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.props.ts
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.spec.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.tsx
The viewport positioner placement logic did not account for cases where the positioner was not initially placed immediately below the anchor element.  This change adds logic to do that.  Also added "verticalLocktoDefault" and "horizontalLocktoDefault" props to enable authors to use the component to place a flyout without adjusting for available space.
That the positioner didn't adjust for offset between the anchor and the positioner was an oversight interfering with partner implementations.  
> fix: enable viewport postioner to correct for base position offset from anchor

- packages/fast-components-styles-msft/src/design-system/index.ts
Cleaned up the wording and standardized the punctuation on the comments in DesignSystem.
Making the intent and functionality more clear.
> chore: Cleaned up some comments on the design system properties

- packages/fast-tooling-react/app/configs/children.schema.json
- packages/fast-tooling-react/src/navigation/navigation-tree-item.props.ts
- packages/fast-tooling-react/src/navigation/navigation-tree-item.tsx
- packages/fast-tooling-react/src/navigation/navigation.spec.tsx
- packages/fast-tooling-react/src/navigation/navigation.style.ts
- packages/fast-tooling-react/src/navigation/navigation.tsx
Adds the following:
- Direct nesting of default React children
- Adds distinction between children items and other complex objects by italicizing non-children items
- Sorts items to nest non-children before children
Resolves #1831 #1832
> feat: allow children in the React default children prop to be directly nested in the Navigation component

- packages/fast-color-explorer/app/color-blocks.tsx
- packages/fast-components-styles-msft/src/design-system/design-system.schema.ts
- packages/fast-components-styles-msft/src/design-system/index.ts
- packages/fast-components-styles-msft/src/divider/index.ts
- packages/fast-components-styles-msft/src/utilities/color/index.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-divider.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-divider.ts
- packages/fast-components-styles-msft/src/utilities/design-system.ts
Added neutral divider color recipe.
The outline recipe is too strong for use as a divider line in many places. This can be thought of as an alternative to a drop shadow for separating content areas. Like a drop shadow, it stays dark as long as possible, even in dark mode.
> feat: add neutral divider color recipe.

- packages/fast-color-explorer/app/color-blocks.tsx
- packages/fast-color-explorer/app/swatch.tsx
- packages/fast-components-styles-msft/src/utilities/color/neutral-focus.ts
Fixed accent color inner focus to work with container light/dark mode.
Added swatch for inner accent color.
Updated contrast calculation to support this different relationship.
The inner focus ring for accent color was correctly 3.5 : 1 against the outer ring, but going darker on very light backgrounds instead of lighter. Updated to fit desired styling.
> fix: accent color inner focus

- packages/fast-components-styles-msft/src/carousel/index.ts
Addresses fill being applied to flipper svg in dark slide theme in carousel.
> fix: updates fill being applied to flipper svg in dark slide theme in carousel

- packages/fast-tooling-react/src/navigation/navigation.style.ts
expanded arrow does not match design.
after:
Closes: #1933 
> fix: Navigation arrows should only tip 45 degrees

- packages/fast-components-styles-msft/src/utilities/color/index.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-layer.ts
Added neutral layer recipes to clarify usage for cards and floating surfaces.
With the updated color guidance, the layer guidance is more formalized including clarifying the relationship cards have to their background and the slight differences in light and dark modes.
> feat: added neutral layer recipes to clarify usage for cards and floating surfaces

- packages/fast-components-styles-msft/src/design-system/design-system.schema.ts
Added HEX value `pattern` property to schema for `backgroundColor` and `accentBaseColor`
closes #1945 
> feat: add regex pattern for HEX value in design system schema

- packages/fast-components-react-msft/src/background/background.props.ts
- packages/fast-components-react-msft/src/background/background.spec.tsx
- packages/fast-components-react-msft/src/background/background.tsx
Change to background component which allows to avoid tag rendering if tag property is set to null.
Avoid of creation of redundant div elements if <background> is used only as background context provider.
https://github.com/microsoft/fast-dna/issues/1982
> feat: add ability to avoid tag rendering for background component

- packages/fast-components-styles-msft/src/select/index.ts
An apparently unnecessary z-index = 1 css style was being applied to the select menu and was causing z-index issues with some layouts.
It is unlikely but possible that this style change could impact some layouts.  If that is an issue the fix is to add a stylesheet override for the "select_menu" classname which applies the desired z-index to the menu.
Fixes this bug (the first two issues in the bug were already fixed by updating fast-dna):
https://github.com/microsoft/fast-dna/issues/1958
- [] This change causes current functionality to break.
> fix: remove unnecessary z-index value in select menu styling

- packages/fast-components-react-base/src/toggle/toggle.props.ts
- packages/fast-components-react-base/src/toggle/toggle.schema.ts
- packages/fast-components-react-base/src/toggle/toggle.spec.tsx
- packages/fast-components-react-base/src/toggle/toggle.tsx
- packages/fast-components-react-msft/src/toggle/README.md
- packages/fast-components-react-msft/src/toggle/toggle.schema.ts
- packages/fast-components-react-msft/src/toggle/toggle.stories.tsx
Made `selectedMessage`, `statusMessageId` and `unselectedMessage` optional because there are design cases where we don't want a status message.
> fix: [toggle] make selected & unselected messages optional 

- packages/fast-components-styles-msft/src/slider-label/index.ts
- packages/fast-components-styles-msft/src/slider/index.ts
Set high contrast media query to slider label tick mark. slider thumb (rest, hover and active state). The background and foreground of the slider track.
High contrast 1
High contrast 2
High contrast black
High contrast white
closes #1984 
When user turns on high contrast the slider does not show up
> fix: high contrast for slider component

- packages/fast-components-styles-msft/src/toggle/index.ts
Add high contrast media queries to the `input` and `stateIndicator` in both unselected and selected state.
The different states in high contrast mode.
Unselected (High contrast black theme)
rest/hover/active
Selected (High contrast black theme)
rest/hover/active
What toggle looks like on selected state, in other high contrast theme.
Selected (High contrast 1 theme)
Selected (High contrast 2 theme)
Selected (High contrast white theme)
This solves the issue for when a user sets the toggle to "selected" there is no visual queue letting the user know the toggle is on "selected".
closes #1985 
> fix: high contrast on toggle component

- packages/fast-tooling-react/src/data-utilities/location.spec.ts
- packages/fast-tooling-react/src/data-utilities/location.ts
Plugins were only being resolve against data structures that had a "props" key. This meant that a react child would not have a plugin resolved if `children` was of a type other than object, meaning strings, booleans, and numbers could would not be correctly resolved. This fixes that issue.
> fix: resolve plugins against objects without props

- packages/fast-tooling-react/src/data-utilities/location.ts
Utilize normalized data locations in plugin location resolution so we don't get miss-matches.
> fix: normalize data locations of plugins

- packages/fast-tooling-react/src/css-property-editor/property-editor.style.ts
- packages/fast-tooling-react/src/css-property-editor/property-editor.tsx
Some minor tweaks to the css property editor's "click to create row" behavior.  Rows extend to the width of the component to more reliably insert after the click, also check for top/bottom insertion when clicking outside rows.  Hide outlines that could show up on click.
Getting closer to matching behavior of edge css prop editor
> feat: refine css prop editor create row behavior

- packages/fast-components-react-base/src/slider/README.md
- packages/fast-components-react-base/src/slider/slider.props.ts
- packages/fast-components-react-base/src/slider/slider.spec.tsx
- packages/fast-components-react-base/src/slider/slider.tsx
- packages/fast-components-react-msft/src/slider/README.md
Adds a prop by which developers can convert a slider value before it is shown to the user (through screen readers at this point as developers already have control of labels).
This was an issue dev encountered and the idea that a developper could want to use a slider to select values in an array seemed like a general use case we should support.
> feat: add slider display value converter

- packages/fast-components-react-base/src/auto-suggest/auto-suggest.props.ts
- packages/fast-components-react-base/src/auto-suggest/auto-suggest.spec.tsx
- packages/fast-components-react-base/src/auto-suggest/auto-suggest.tsx
Added a flag to Autosuggest's onValueChange event to indicate that the change was due to focus on a suggested option.
Without something like this page authors are unable to tell whether they should repopulate options as a user navigates the list of options.  This allows them to choose not to refresh the options but still react to changes if they desire.  This is an optional param so not a breaking change.
https://github.com/microsoft/fast-dna/issues/1989
> fix: add flag to autosuggest onValueChange event to label when change is from a suggested option

- packages/fast-tooling-react/src/css-property-editor/property-editor.style.ts
Tweak CSS so wrapping brackets on css property editor are on their own lines.
Noticed that when there were no content in the editor the brackets displayed incorrectly
> fix: tweak CSS editor styling so wrapping brackets are always on different lines

- packages/fast-components-styles-msft/src/call-to-action/index.ts
Fixes an issue where a the call to action glyph was not transforming properly in RTL markets. This PR adds a missing index for the format function to ensure that the values map as expected.
> fix: missing format index prevented rtl support for call to action transform

- packages/fast-tooling-react/src/form/form/form-item.children.tsx
The form from form-generator was interpreting the children button controls as submit button, causing weird behavior when the users pressed the "enter" key.
> fix: ensure enter does not 'click' buttons

- packages/fast-tooling-react/src/css-property-editor/property-editor-row.props.ts
- packages/fast-tooling-react/src/css-property-editor/property-editor-row.tsx
- packages/fast-tooling-react/src/css-property-editor/property-editor.spec.tsx
This allows the typing of CSS properties in spinal case.
Resolves #2045 
> fix: allow typing in spinal case for the CSS property name

- packages/fast-tooling-react/src/form/form/form-item.checkbox.style.ts
- packages/fast-tooling-react/src/style/utilities.ts
fix: use focus visible in form items that support it
https://github.com/microsoft/fast-dna/issues/1950
I was unable to get the focus visible behavior to work on select elements, so these are excluded for now.
- [] **Chore**: A change that does not impact distributed packages.
- [] **New feature**: A change that adds functionality.
- [] I have updated the project documentation to reflect my changes.
> fix: use focus visible in form items that support it

- packages/fast-tooling-react/src/css-property-editor/property-editor-row.props.ts
- packages/fast-tooling-react/src/css-property-editor/property-editor-row.tsx
- packages/fast-tooling-react/src/css-property-editor/property-editor.tsx
Only transform the name of a property once it is being committed so that there is no need to store the trailing dash in state, this also allows the deletion of dashes.
> fix: allow the deletion via keyboard of dashes in property names

- packages/fast-layouts-react/src/pane/pane.props.ts
- packages/fast-layouts-react/src/pane/pane.tsx
- packages/fast-layouts-react/src/row/row.props.ts
- packages/fast-layouts-react/src/row/row.tsx
Added collapsed measurements as props instead of constants.
The layout package was built before density was added to the components. There was a fixed assumption to the minimum size a pane could be when collapsed, that doesn't coordinate well with density other than the default. Also, this is beneficial for many other design reasons allowing complete flexibility in sizing.
> feat: added collapsed measurements as props instead of constants

- packages/fast-tooling-react/src/navigation/navigation-tree-item.props.ts
- packages/fast-tooling-react/src/navigation/navigation-tree-item.tsx
- packages/fast-tooling-react/src/navigation/navigation.spec.tsx
- packages/fast-tooling-react/src/navigation/navigation.tsx
- packages/fast-tooling-react/src/navigation/navigation.utilities.ts
feat: add ability to duplicate items in navigation
The navigation component should log key combinations which allow duplication of data for any child items which could be components or primitive data.  The intent was for this to work with "ctrl+d" but Edge seems to be intercepting that so currently using "shift+d" while we investigate.
https://github.com/microsoft/fast-dna/issues/2032
> feat: add ability to duplicate component children in react "children" property using Ctrl + D in the navigation component

- packages/fast-component-explorer/app/explorer.tsx
set z-index on Select component to "1"
closes #2033 
When opening the scenario option, the drop down goes behind the iframe. The solution fixes that issue.
- x] **Bug fix**: A change that fixes an issue, link to the issue above.
> chore: dropdown in Explorer from going behind the iframe

- packages/fast-layouts-react/src/pane/pane.tsx
- packages/fast-layouts-react/src/row/row.tsx
`collapsedWidth` and `collapsedHeight` were being added to the DOM via unhandled props because they were not enumerated as handled props. This change adds those properties to the handled props property of `Row` and `Pane`
> fix: enumerate collapseWidth and collapseHeight as handled props

- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.spec.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.stories.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.tsx
- no observer mode actually works now
- added missing story for viewport positioner
- Viewport positioner will attempt to reinitialize twice if dom refs are not populated which can easily happen if viewport is initialized in same render pass as the positioner.
- some functionality was broken
> fix: resolve issues with viewport positioner no-observer mode

- packages/fast-components-react-base/src/slider/slider.spec.tsx
- packages/fast-components-react-base/src/slider/slider.tsx
Slider was previously always rounding down on clicks between increments, now it moves to the nearest one
Previous behavior was incorrect and made it nearly impossible to click on the track to get to the highest value increment on the track
> fix: slider moves to nearest increment on click

- packages/fast-tooling-react/src/navigation-menu/navigation-menu.style.ts
Add selection state to `<NavigationMenu/>`
Closes: #2035 
After:
> chore: style selection state of navigation menu

- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.spec.tsx
- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
Cancel any queued callbacks to the resize and scroll handlers when the component unmounts
Fix for issue #2022
- No changes are necessary
> fix: cancel any callbacks queued by raf-throttle on componentWillUnmount

- packages/fast-components-styles-msft/src/dialog/index.ts
Dialog was content gets clipped zoomed.
Closes: #1871 
> fix: dialog elements clipped when zoomed

- packages/fast-components-styles-msft/src/button/index.ts
- packages/fast-components-styles-msft/src/design-system/index.ts
- packages/fast-components-styles-msft/src/flyout/index.ts
- packages/fast-components-styles-msft/src/heading/index.ts
- packages/fast-components-styles-msft/src/outline-button/index.ts
- packages/fast-components-styles-msft/src/patterns/button.ts
- packages/fast-components-styles-msft/src/select/index.ts
- packages/fast-components-styles-msft/src/subheading/index.ts
- packages/fast-components-styles-msft/src/utilities/color/common.ts
- packages/fast-components-styles-msft/src/utilities/density.ts
- packages/fast-components-styles-msft/src/utilities/design-system.spec.ts
- packages/fast-components-styles-msft/src/utilities/design-system.ts
- packages/fast-components-styles-msft/src/utilities/fonts.ts
- packages/fast-components-styles-msft/src/utilities/typography.ts
- packages/fast-jss-utilities/src/acrylic.ts
- packages/fast-web-utilities/src/dom.ts
Memoize colors, various selector adjustments, and removal of `ensureDesignSystemDefaults`
> fix: various perf improvements to stylesheets

- packages/fast-components-class-name-contracts-base/src/slider/index.ts
- packages/fast-components-react-base/src/slider/slider.spec.tsx
- packages/fast-components-react-base/src/slider/slider.tsx
Slider thumb orientation classes were not being applied
https://github.com/microsoft/fast-dna/issues/2124
> fix: correct bad slider thumb orientation modifier classnames

- packages/fast-components-react-base/src/slider/slider.tsx
Previously Slider used pageX/pageY to determine cursor position during dragging, this caused odd slider behavior when cursor overlapped other i-frames during a drag operation (noticed this when dragging over the component list in the component explorer app).  Using clientX/clientY instead fixes the issue.
Odd slider behavior during dragging
> fix: improve slider drag

- packages/fast-components-react-base/src/radio/radio.props.ts
> fix: correct type value for radio on change

- packages/fast-components-react-base/src/radio/radio.props.ts
- packages/fast-components-react-base/src/radio/radio.spec.tsx
- packages/fast-components-react-base/src/radio/radio.tsx
Fixes type issue when assigning className unhandled prop
> fix: define defaultProps type of radio correctly

- packages/fast-components-styles-msft/src/button/index.ts
- packages/fast-components-styles-msft/src/patterns/button.ts
> fix: button before and after content missing margin and remove incorrect high contrast selector

- packages/fast-components-react-base/src/select/select.props.ts
- packages/fast-components-react-base/src/select/select.spec.tsx
- packages/fast-components-react-base/src/select/select.tsx
- packages/fast-components-react-msft/src/select/select.stories.tsx
Previously the select menu changed the selected state of the select as options got focus, now this only happens when an item is invoked by a click or keyboard enter or space.  A new callback has been added for those that may want to act on menu focus changes.
!!! NOTE: It is possible that some implementations based on the old behavior may not behave as expected with this change.  Please test your Select implementations  !!!
https://github.com/microsoft/fast-dna/issues/2181
> fix: :bangbang: single mode select menu changes selection on invoke, not focus

- packages/fast-layouts-react/src/utilities/breakpoint-tracker.ts
> fix: set default value for breakpoint tracker subscriptions to prevent exception when server side rendering

- packages/fast-components-styles-msft/src/button/index.ts
We noticed the glyphs was changing color #FFF in color explorer.
`fill: accentForegroundCut,` was effecting this and it is not needed here.
> fix: beforeContent and afterContent in Buttons changing to white when hovered

- packages/fast-storybook-design-system-addon/package.json
Was trying to build fast-components-react-msft and it failed on this (oddly bootstrapping worked ok though).
fix build break.
> fix: building some fast packages failed because of missing dependency ref

- packages/fast-components-styles-msft/src/design-system/index.ts
- packages/fast-components-styles-msft/src/index.ts
- packages/fast-components-styles-msft/src/utilities/fonts.ts
Removes circular dependency in styles package causing runtime errors on build packages.
> fix: remove circular dependency

- packages/fast-color-explorer/app/app.tsx
- packages/fast-color-explorer/app/design-system.ts
- packages/fast-components-react-msft/src/background/README.md
- packages/fast-components-react-msft/src/background/background.props.ts
- packages/fast-components-react-msft/src/background/background.spec.tsx
- packages/fast-components-react-msft/src/background/background.tsx
Deprecated and updated references to LightModeBackgrounds and DarkModeBackgrounds.
These enums replicate another background layer enum that has previously been deprecated. Using indexes for background offsets is fragile because it doesn't account for variable sized palettes. Updating to use layer recipes instead.
> feat: deprecated and updated references to LightModeBackgrounds and DarkModeBackgrounds

- packages/fast-layouts-react/src/column/column.tsx
- packages/fast-layouts-react/src/grid/grid.tsx
- packages/fast-layouts-react/src/page/page.tsx
Gives developers the ability to override styles created by page/grid/column components
> fix: ensure experience-defined styles override page/grid/column inline styles

- packages/fast-tooling-react/src/style/utilities.ts
Edge appears to be setting default placeholder to black. Added a selector to add consistancy across browsers.
Before:
After:
> chore: default placeholder for input is wrong in Edge

- packages/fast-components-react-base/src/slider/slider.spec.tsx
- packages/fast-components-react-base/src/slider/slider.tsx
- packages/fast-components-react-msft/src/slider/slider.stories.tsx
Home and end keys moves slider thumbs to beginning or end of the range.
https://github.com/microsoft/fast-dna/issues/1914
> fix: enable home and end keys on slider

- packages/fast-tooling-react/README.md
- packages/fast-tooling-react/app/pages/form-and-navigation.tsx
- packages/fast-tooling-react/src/form/controls/control.array.spec.tsx
- packages/fast-tooling-react/src/form/controls/control.array.tsx
- packages/fast-tooling-react/src/form/controls/control.children.spec.tsx
- packages/fast-tooling-react/src/form/controls/control.children.tsx
- packages/fast-tooling-react/src/form/form-control-switch.spec.tsx
- packages/fast-tooling-react/src/form/form-section.spec.tsx
- packages/fast-tooling-react/src/form/form-section.tsx
- packages/fast-tooling-react/src/form/form.spec.tsx
- packages/fast-tooling-react/src/form/index.ts
This change adds a BareForm that does not provide the drag and drop context. This is for use when the Form is used in conjunction with the Navigation.
After the consolidation of drag and drop libraries it was noticed that using the Navigation and Form together caused an error due to multiple globals being introduced from the HTML5Backend. To combat this a secondary export is added in this PR for those who need to use both.
> feat: add a BareForm secondary export without drag and drop context

- packages/fast-tooling-react/src/form/form.spec.tsx
- packages/fast-tooling-react/src/form/form.tsx
Trigger validation change in form constructor to bubble up configuration errors.
Closes #2285
> fix: Validation errors not displayed on component creation in fast-tooling-react form

- packages/fast-components-styles-msft/src/text-action/index.ts
Updated the flex-basis parameter of textField. This makes it compatible with IE11. It does not recognize the third parameter "0" as valid.
Makes the control compatible with IE11.
> fix: text-action compatibility with ie11

- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.spec.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.tsx
Noticed that viewport positioner was incorrectly adding additional classnames in addition to the correct ones.  Fixed that and tightened the tests to check for this.
Made using positioning classes useless to control layout.
> fix: viewport positioner adds incorrect classnames

- packages/fast-components-react-base/src/select/select.schema.ts
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.props.ts
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.schema.ts
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.spec.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.stories.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.tsx
- packages/fast-components-react-msft/src/flyout/flyout.tsx
- packages/fast-components-react-msft/src/select/select.schema.ts
This change adds a new "scaleToAvailableSpace" prop to viewport positioner.  Default is false which is the current behavior of a fixed size positioner. When it is set to true the positioner will dynamically scale to fill all the available space in the assigned region.  This is useful for scaling menus and the such.
Provide a means of scaling positioned content to available space.
> feat: add dynamic scaling capability to viewport positioner

- packages/fast-components-styles-msft/src/metatext/index.ts
Metatext creates a typography element and assigns a size to it of t7 - styling the font-size explicitly in the stylesheet is redundant.
> fix: remove font-size styles from metatext

- packages/fast-color-explorer/app/app.tsx
- packages/fast-color-explorer/app/design-system.ts
- packages/fast-component-explorer/app/explorer-region.tsx
- packages/fast-component-explorer/app/explorer.tsx
- packages/fast-component-explorer/app/preview.tsx
- packages/fast-components-styles-msft/src/design-system/design-system.schema.ts
- packages/fast-components-styles-msft/src/design-system/index.ts
- packages/fast-components-styles-msft/src/utilities/color/index.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-layer.spec.ts
- packages/fast-components-styles-msft/src/utilities/color/neutral-layer.ts
- packages/fast-components-styles-msft/src/utilities/color/palette.ts
- packages/fast-components-styles-msft/src/utilities/design-system.ts
- Added luminance setting to design system
- Updated layer recipes to use luminance setting if configured
- Updated a couple apps to use luminance instead of fixed background
Dark and light mode has been based on the background color only, requiring us to force it by hard-coding either black or white, and doesn't allow for any other range except light or dark as we've defined it.
This allows any custom level of luminance, while staying within the layer system. Enums represent our standard light and dark mode base level.
> feat: add luminance to design system

- packages/fast-components-react-base/src/viewport-positioner/viewport-context.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.spec.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.stories.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.tsx
- packages/fast-components-react-msft/src/flyout/flyout.stories.tsx
Viewport context is intended to provide developers with an easy way to set the viewport for a region of the dom tree without having to pass down the reference through multiple component layers.  Any viewport positioners that are children of the context will use that as the viewport if none are specified in it's props.
Make developers life easier
> feat: add viewport context

- packages/fast-storybook-design-system-addon/src/panel.tsx
Fixes error being thrown in fast-components-react-msft's storybook site.
> fix: fix msft components storybook site

- packages/fast-components-react-msft/src/select/select.tsx
- packages/fast-components-styles-msft/src/select/index.ts
The approach of using actual wrapping dom elements was interfering with advanced layout options for select menu.  A slight change of approach allows passing of color to base component using only context and not actually wrapping the menu in a dom element. 
Removing wrapping dom element and using only context + css makes layout easier (and removes an element from the dom)
> fix: use only context and jss styles to apply select menu background

- packages/fast-components-styles-msft/src/utilities/high-contrast.ts
- packages/fast-web-utilities/src/dom.spec.ts
- packages/fast-web-utilities/src/dom.ts
There is a typo on canUsedForcedColors. It should be called canUseForcedColors
deprecated and replaced `canUsedForcedColors`
close #2380 
> fix: canUsedForcedColors should be called canUseForcedColors

- packages/fast-tooling-react/README.md
- packages/fast-tooling-react/app/pages/form/index.ts
- packages/fast-tooling-react/src/__tests__/schemas/categories.schema.json
- packages/fast-tooling-react/src/__tests__/schemas/dictionary.schema.json
- packages/fast-tooling-react/src/form/form-category.props.ts
- packages/fast-tooling-react/src/form/form-category.spec.tsx
- packages/fast-tooling-react/src/form/form-category.tsx
- packages/fast-tooling-react/src/form/form-section.props.ts
- packages/fast-tooling-react/src/form/form-section.tsx
- packages/fast-tooling-react/src/form/utilities/form.tsx
- packages/fast-tooling-react/webpack.config.js
Allows the use of categories to be set for properties in the JSON schema.
Closes #1655 
> feat: allow properties to be categorized

- packages/fast-components-react-base/src/slider-track-item/slider-track-item.spec.tsx
- packages/fast-components-react-base/src/slider/slider.tsx
- packages/fast-web-utilities/src/localization.ts
Slider's mechanism for detecting direction (ltr/rtl) could fail to detect the correct setting on initial render.  We now check after mounting and after any renders.
Sliders would be incorrect on initial render in rtl scenarios.
> fix: slider can miss dir setting on initial render.

- packages/fast-components-class-name-contracts-base/src/select/index.ts
- packages/fast-components-react-base/src/select/select.tsx
- packages/fast-components-react-msft/src/select/select.stories.tsx
- packages/fast-components-styles-msft/src/select/index.ts
Added a managed class to select and modified styles to support scaling menus.  Aside from tweaking styles and defaults they should essentially work now.
Being able to have select menus scale according to available space has been a requested feature.
> feat: select class and style support for scaling menus

- packages/fast-components-styles-msft/src/utilities/color/common.ts
- packages/fast-components-styles-msft/src/utilities/color/palette.ts
Fixed a problem attempting to parse a color string that was actually a function.
Resolves an issue with dynamic luminance with tinted neutral.
> fix: fix a bug causing luminance matching to fail if not grey

- packages/fast-tooling-react/src/__tests__/schemas/one-of.schema.json
- packages/fast-tooling-react/src/form/form-section.tsx
- packages/fast-tooling-react/src/form/form.spec.tsx
The category update did not include checks for oneOf arrays in the schema.
> fix: ensure categories are included when the schema also includes oneOf

- packages/fast-color-explorer/app/control-pane.tsx
- packages/fast-color-explorer/app/gradient.tsx
Updated the marker dot to show when the base color is light.
Now:
The marker was previously a white dot, which was usually visible, although not always accessible, unless the base color was very light.
> fix: color explorer marker colors don't show on light colors

- packages/fast-layouts-react/src/grid/grid.no-css-grid.spec.tsx
- packages/fast-layouts-react/src/grid/grid.props.ts
- packages/fast-layouts-react/src/grid/grid.spec.tsx
- packages/fast-layouts-react/src/grid/grid.tsx
- packages/fast-layouts-react/src/grid/index.ts
- yarn.lock
Related to: [https://github.com/microsoft/fast-dna/issues/2408](https://github.com/microsoft/fast-dna/issues/2408)
For server side rendering we want to ensure we use the same grid styles that the client would produce. To do this we want to be able to set the grid styles ourselves instead of calling canUseCssGrid() which defaults to false on the server.
This change adds a new prop "display" to the grid component which can be one of "grid" or "-ms-grid". When provided this prop will be used to determine the styles that are used.
> feat: add display prop to Grid component for SSR support

- packages/fast-components-styles-msft/src/heading/index.ts
- packages/fast-components-styles-msft/src/paragraph/index.ts
- packages/fast-components-styles-msft/src/subheading/index.ts
- packages/fast-components-styles-msft/src/typography/index.ts
closes #2465 
This changes fixes issues related to applying default cursor styles to ALL instances of the typography component. A common scenario for users is to wrap the typography component within a button or hypertext component. With the cursor applied to typography, this would cause the element to appear as though it was not clickable and require overrides by the implementor. By all intents and purposes, applying this wholesale is "buggy" behavior and this PR is intended to fix it.
The default cursor is valuable from a design system standpoint with semantic elements such as Heading, Subheading, and Paragraph. The Typography component, however, is more of a utility component which maps to the visual type ramp. The utility itself exists to provide visible weight, and applying the cursor …
> fix: remove cursor pointer from typography and apply to semantic components

- packages/fast-components-react-base/src/slider/slider.spec.tsx
- packages/fast-components-react-base/src/slider/slider.tsx
The slider component can only query the dom for direction until after it has mounted.  Previously we rendered in default ltr and if we detect rtl after the component mounted we reset the state and triggered a render to correct the layout to rtl.  This meant we ran layout logic twice in rtl and that css transitions could be triggered by the ltr to rtl layout changes.  With this change we only render the component root element on the first pass, check for direction on componentDidMount() and only render the component internals at that point.
Users reported seeing transition animations on rtl ui.  Slight perf gain on rtl by avoiding running layout twice.
> fix: delay rendering slider internals until after direction check

- packages/fast-components-react-base/src/select/select.spec.tsx
- packages/fast-components-react-base/src/select/select.tsx
- packages/fast-components-react-msft/src/select/select.spec.tsx
- packages/fast-components-react-msft/src/select/select.tsx
On focus the Select component was not providing desired info to assistive technologies. When a select menu is not open screen readers should recite: the label of the select control, the current value, the component name ("menu button" on Anaheim & Chrome, but "button" on spartan), that it is collapsed.
This is a second approach at this (https://github.com/microsoft/fast-dna/pull/2393);
Improve Select component accesibility
> fix: adjust select Aria

- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.spec.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.tsx
viewport positioner sets it's opacity to 0 until after initial placement is complete.  This change simplifies that logic and removes code that checked that dom during render which was generating a React warning.
Looking at the dom during render bad, simpler logic good
> fix: simplify viewport-positioner flicker avoidance logic and remove dom ref

- packages/fast-tooling-react/src/__tests__/schemas/objects.schema.json
- packages/fast-tooling-react/src/form/form-control-switch.tsx
- packages/fast-tooling-react/src/form/form-section.props.ts
- packages/fast-tooling-react/src/form/form-section.spec.tsx
- packages/fast-tooling-react/src/form/form-section.style.ts
- packages/fast-tooling-react/src/form/form-section.tsx
- packages/fast-tooling-react/src/form/form.tsx
This feature changes the wrapping element for a JSON schema type `object` to `fieldset` and passes a `disabled` state down to any sub properties it may have.
Closes #1841, closes  #1842 
> feat: allow an object to be disabled, which will disable all of its properties and sub-properties

- packages/fast-tooling-react/src/__tests__/datasets/dictionary.ts
- packages/fast-tooling-react/src/form/form-control-switch.spec.tsx
- packages/fast-tooling-react/src/form/form-control-switch.tsx
- packages/fast-tooling-react/src/form/form-dictionary.props.ts
- packages/fast-tooling-react/src/form/form-dictionary.spec.tsx
- packages/fast-tooling-react/src/form/form-dictionary.tsx
- packages/fast-tooling-react/src/form/form-section.tsx
- packages/fast-tooling-react/src/form/form.tsx
- packages/fast-tooling-react/src/form/utilities/form.tsx
- yarn.lock
Adds the ability to see additional property keys in an object if the schema specifies `additionalProperties: false`. This gives the user the ability to remove them and ensure the data is valid.
Closes #2478 2452
> feat: show additional properties when false and present a way to remove them

- packages/fast-components-react-base/src/dialog/dialog.spec.tsx
- packages/fast-components-react-base/src/dialog/dialog.stories.tsx
- packages/fast-components-react-base/src/dialog/dialog.tsx
Modal dialogs were always focusing to the top of the tab queue on mount which was interfering with the autofocus option of other components.
https://github.com/microsoft/fast-dna/issues/2495
> fix: modal dialogs do not move focus if already within

- packages/fast-components-react-base/src/horizontal-overflow/README.md
- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.props.ts
- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.schema.ts
- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.spec.tsx
- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.stories.tsx
- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
This started as a fix to some browsers not scrolling focused elements into view when user tabbed to them, but that seems to be getting fixed in the browser (chromium at least).  This change should address any remnants of that issue but additionally it significantly modifies the scroll behavior to the component such that content should always smooth scroll into view even if users navigate through content quickly either by clicking the previous/next buttons or rapidly tabbing.
This change also adds a configurable "peek" property which moves the focused item away from the edge of the viewport if there is available space such that the next/previous item is partially visible.
https://github.com/microsoft/fast-dna/issues/2126
And a desire to improve how our components animate to create a …
> feat: horizontal overflow smooth scrolling

- packages/fast-tooling-react/src/data-utilities/generate.spec.ts
- packages/fast-tooling-react/src/data-utilities/generate.ts
Addresses an issue where nested oneOf/anyOfs inside of a provided schema would not be accounted for when generating data.
Closes #2508 
> fix: account for nested oneOfs when generating example data

- packages/fast-tooling-react/README.md
- packages/fast-tooling-react/src/form/form.props.ts
Mark the props for form plugins and the `onSchemaChange` callback as deprecated to be removed in 2.0.0.
Preparation for #2509 
> feat: deprecate the form plugins and onSchemaChange callback

- packages/fast-tooling-react/src/form/form-section.style.ts
The update to use `<fieldset>` on form sections caused some browsers to use their default styles on the `fieldset` element causing undesirable results. This fix will reset one of the CSS properties that causes the validation errors to overflow so that we have ellipsis working correctly on long validation error strings.
> fix: address an overflow issue in form validation messages when displayed inline

- packages/fast-tooling-react/README.md
- packages/fast-tooling-react/src/css-editor/box-shadow/box-shadow.props.tsx
- packages/fast-tooling-react/src/css-editor/box-shadow/box-shadow.style.ts
- packages/fast-tooling-react/src/css-editor/box-shadow/box-shadow.tsx
- packages/fast-tooling-react/src/css-editor/editor-data.schema.ts
- packages/fast-tooling-react/src/css-editor/editor.constants.ts
- packages/fast-tooling-react/src/css-editor/editor.schema.json
- packages/fast-tooling-react/src/css-editor/editor.tsx
- packages/fast-tooling-react/src/css-editor/index.ts
> feat: convert box-shadow to use standard control plugin in css editor

- packages/fast-tooling-react/README.md
- packages/fast-tooling-react/src/css-editor/border-radius/border-radius.props.ts
- packages/fast-tooling-react/src/css-editor/border-radius/border-radius.spec.tsx
- packages/fast-tooling-react/src/css-editor/border-radius/border-radius.style.ts
- packages/fast-tooling-react/src/css-editor/border-radius/border-radius.tsx
- packages/fast-tooling-react/src/css-editor/editor-data.schema.ts
- packages/fast-tooling-react/src/css-editor/editor.constants.ts
- packages/fast-tooling-react/src/css-editor/editor.schema.json
- packages/fast-tooling-react/src/css-editor/editor.tsx
> feat: convert border-radius to use standard control plugin in css editor

- packages/fast-tooling-react/src/form/controls/control.textarea.spec.tsx
- packages/fast-tooling-react/src/form/controls/control.textarea.tsx
Accept empty strings as the value and as default values provided, previously they were evaluated as falsey, causing some unexpected behavior when entering an empty string which would fall back to default values.
> fix: allow empty strings in the textarea form control for value and default

- packages/fast-components-styles-msft/src/button/index.ts
- packages/fast-components-styles-msft/src/lightweight-button/index.ts
Bug: 
Accessibility: MAS4.3.1: HighContrast:  "Back to extensions home" button looks like static text in High contrast themes.
https://microsoft.visualstudio.com/Edge/_workitems/edit/24461248/
In high contrast mode, the lightweight button looks like plain text, so I added the underline.
High Contrast Black
rest
hover
High Contrast White
rest
hover
> fix: lightweight button looks like plain text in high contrast mode

- packages/fast-components-react-base/src/auto-suggest/auto-suggest.spec.tsx
- packages/fast-components-react-base/src/auto-suggest/auto-suggest.tsx
Setting the value prop on the auto select component was not fully controlling the value as the user interacted with it
User found a bug.
> fix: Auto suggest value prop overrides interaction with component

- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.spec.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.stories.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.tsx
Viewport positioner was not resetting on anchor change.  This fix causes it to check for anchor changes and reposition if required.
Users had encountered issue with positioner not reacting to anchor change.
> fix: viewport positioner resets on anchor change

- packages/fast-components-styles-msft/src/utilities/color/neutral-layer.ts
Updated description and metadata for L1 alt layer to no longer be deprecated. The most applicable semantic name should be used.
I originally deprecated this to better associate "card container" and "card" recipes. There are valid uses for an alternate L1 color that are not card containers, so using the card container recipe is somewhat misleading. Restoring this as a valid and recommended alternative.
> feat: update description and metadata for L1 alt layer as no longer deprecated

- packages/fast-components-react-msft/src/pivot/pivot.spec.tsx
- packages/fast-components-react-msft/src/pivot/pivot.tsx
Author provided `onUpdate` callbacks were not getting invoked when the pivot updated the active slide. This change wires the callback.
> fix: pivot onUpdate function should be called on update

- packages/fast-tooling-react/src/form/controls/control.checkbox.spec.tsx
- packages/fast-tooling-react/src/form/controls/control.checkbox.style.ts
- packages/fast-tooling-react/src/form/controls/control.checkbox.tsx
- packages/fast-tooling-react/src/form/templates/template.control.single-line.tsx
The checkbox does not visually show the checkmark when the checkbox control is used inside the `StandardControlPlugin`.
When using a control the means of indicating it's value should always be self contained, this was not the case for the checkbox control. This change rectifies this issue.
> fix: checkbox control is visually represented with a checkmark when used outside of the SingleLineControlPlugin

- packages/fast-components-react-base/src/utilities/extract-element.spec.tsx
- packages/fast-components-react-base/src/utilities/extract-element.ts
- packages/fast-components-react-base/src/utilities/index.ts
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.spec.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.tsx
Moving the extractElementFromRef function from Viewport Positioner to base component utilities as it will be used by other components.
Code reuse, reduce duplication.
> feat: move extractElementFromRef function to utilities

- packages/fast-components-react-base/src/dialog/dialog.spec.tsx
- packages/fast-components-react-base/src/dialog/dialog.tsx
Support for aria-modal has increased and we're now a full revision beyond its inclusion in the WAI-ARIA specification. This PR adds the attribute to the dialog component.
> feat: add aria-modal attribute to modal dialogs

- packages/fast-components-styles-msft/src/radio/index.ts
The label's default color is overwriting the high contrast color, so as a result, the label is not showing the correct color value.
Update:
Removed `-adjust: none` from the root of component, and only set it on input and indicator. By doing this we do not have to set any color value to the label.
> fix: radio label color is being overwritten in high contrast 

- packages/fast-components-react-msft/src/flyout/flyout.tsx
The component *Flyout* uses *ViewportPositioner* for placement of the flyout. It handles the lock properties *horizontalLockToDefault* and *verticalLockToDefault* which were added later. But these properties were not forwarded to the *ViewportPositioner* thus leading to anyone using flyout component and using these properties to have no effect on the,
The pdf in Edge has a new feature, which uses the Flyout Component to show the feature. At some of the system configuration it was behaving weirdly where the flyout was going above the toolbar. To fix this we tried using this property to always make it come at bottom. But the property was not respected. Upon debugging and with the FAST team we figured that it was this mistake where the lock properties were not respected. By changing this …
> fix: ensure the horizontalLockFromDefault property from ViewportPositioner is passed to Flyout

- packages/fast-components-class-name-contracts-base/src/select/index.ts
- packages/fast-components-react-base/src/select/select.spec.tsx
- packages/fast-components-react-base/src/select/select.tsx
- packages/fast-components-react-msft/src/select/select.spec.tsx
- packages/fast-components-react-msft/src/select/select.stories.tsx
- packages/fast-components-styles-msft/src/select/index.ts
Found that styling for menu needed to be able to differentiate styling for "scaleToFit" mode, so added a class for that and tweaked our styles.
Styles that worked for scale to fit mode needed adjustments for when that is disabled (bad margins).  
- [] **Bug fix**: A change that fixes an issue, link to the issue above.
> fix: select - add css class for scaleToFit mode

- packages/fast-components-react-base/src/select/select.spec.tsx
- packages/fast-components-react-base/src/select/select.tsx
- packages/fast-components-react-msft/src/select/select.spec.tsx
- packages/fast-components-react-msft/src/select/select.tsx
Avoid adding "undefined" to the aria tag rendered on the component when the labelledBy prop is not set.  Remove "aria-live" tag from trigger as it was incorrectly causing value to be read on page load.
- nothing good could come from an incorrect aria attribute
- narrator should not read values when select is not focused
> fix: select "aria-labelledby" should never be"undefined" string, remove "aria-live" tag

- specs/README.md
- specs/template.md
This PR adds a new top-level `specs` folder for storing team specs. A spec template is provided as well as a readme to serve as an index of specs.
We'd like to increase transparency over the component design and implementation process, both inside and outside of our team. We'd also like to enable richer design discussions and greater consistency in our components. We believe spending some time writing specs for new components will enable these goals and result in higher-quality components in the end.
A secondary goal is to enable upstreaming our component specs to the open-ui project, helping to improve the open-ui process and content.
> doc(specs): introduce spec template

- packages/fast-element/src/behaviors/binding-base.ts
- packages/fast-element/src/behaviors/property.ts
- packages/fast-element/src/observation/array-observer.ts
- packages/fast-element/src/observation/observable.ts
During the process of implementing the Krausest benchmarks, several bugs were discovered. The bugs fixed in this PR relate to duplicate collection subscriptions or duplicate entries being added into a DOM update batch.
Duplicate DOM batch entries causes unnecessary work to be done on an update, while duplicate collection subscriptions result in an n^2 increase in collection operations over time for certain scenarios.
> fix(fast-element): prevent duplicate subscription and DOM update queuing

- packages/fast-element/src/behaviors/binding-base.ts
- packages/fast-element/src/controller.ts
- packages/fast-element/src/directives/repeat.ts
- packages/fast-element/src/directives/when.ts
- packages/fast-element/src/observation/array-observer.ts
- packages/fast-element/src/observation/notifier.ts
- packages/fast-element/src/observation/observable.ts
- packages/fast-element/src/observation/subscriber-collection.ts
This PR improves general performance, improves startup metrics, and reduces memory allocation.
Tracking observable subscribers previously involved creating a new array and pushing subscribers into that array for each source object. The constant creation of arrays along with the use of `Array#push` creates memory pressure, which has an affect on performance as well.
This PR takes an approach based on some techniques I've used previously in Aurelia. Instead of creating an `Array`, we create a `SubscriberCollection`. The subscriber collection is optimized for the most common scenario of 1 - 3 subscribers per observable property or array. With this in mind, it can store the subscriber in an internal field, allowing it to avoid `Array#push`. If the collection ever exceeds three subscribers, it …
> perf(fast-element): improve subscribe/unsubscribe by reducing alloc

- packages/fast-element/src/dom.ts
- packages/fast-element/src/template-compiler.ts
- packages/fast-element/src/template.ts
- packages/fast-element/src/view.ts
Improve the speed of view creation, particularly in the context of `when` and `repeat`.
Previously, when creating a synthetic view, each time a view was created the view would inject a stable start node into the view. This PR moves that into the template instance so that the start node can be created once, during template compilation, and only if needed based on detecting whether or not the current first node is stable.
This PR also removes the unnecessary extra end node and moves behavior binding to use a more efficient `for` loop (sans arrow function and closure).
> perf(fast-element): improve synthetic view creation speed

- packages/fast-components-react-base/src/viewport-positioner/README.md
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.props.ts
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.spec.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.stories.tsx
- packages/fast-components-react-base/src/viewport-positioner/viewport-positioner.tsx
- packages/fast-components-react-msft/src/flyout/flyout.props.ts
- packages/fast-components-react-msft/src/flyout/flyout.tsx
Adds a Boolean prop "delayContentInstanciation" to viewport positioner which defaults to false. When true the contents of the positioner are not instanciated until after an initial rendering pass where the empty component is placed in the layout.  The reason for this is that partners have encountered issues where the contents of a positioner get focus before the component gets placed and as a result the browser's scroll into view behavior is triggered as an undesirable side effect.
This change also required the component to support resizing of the positioner due to changing content size which it did not previously.
Tests have also been improved and coverage increased.
Addresses unwanted scroll into view behavior.
> feat: viewport positioner enable delayed instanciation

- packages/fast-element/src/directives/repeat.ts
- packages/fast-element/src/observation/array-change-records.ts
- packages/fast-element/src/observation/array-observer.ts
- packages/fast-element/src/observation/subscriber-collection.ts
- packages/fast-element/src/view.ts
This PR re-writes the internal mechanism for array change observation and how the repeat directive works in conjunction with that.
When benchmarking the library, most benchmarks looked pretty solid, but a few were way out of range. Here is a snapshot of the perf before this PR:
Notice "swap rows" and "append rows to large table". After this PR, here's what the perf metrics look like:
"swap rows" is close to 10x faster and "append rows to large table" is almost 2x faster. Additionally, "create rows", "replace all rows", and "clear rows" also improved, enabling fast-element to now beat lit-html by a noticeable amount, being only .03 off from hand-optimized vanilla JS.
Additionally, memory allocation was improved. Here's the before:
And the after:
This is not a breaking change for element …
> perf(fast-element): new strategy for array observation and repeat

- packages/fast-layouts-react/src/page/page.no-css-grid.spec.tsx
- packages/fast-layouts-react/src/page/page.spec.tsx
- packages/fast-layouts-react/src/page/page.tsx
Fix logic in application of cssGridPropertyName in Page.tsx.
https://github.com/microsoft/fast-dna/issues/2689
> fix: applying the cssGridPropertyName correctly in Page.tsx

- packages/fast-components-react-msft/src/carousel/carousel.stories.tsx
- packages/fast-components-styles-msft/src/carousel/index.ts
closes: #2682 
Added an `after` pseudo element to handle focus visual. Updated stories to use simple state handler to prevent autoplay when carousel is focued.
Before:
After:
> fix: update sequence indicators to have visual focus styling

- packages/fast-element/src/behaviors/behavior.ts
- packages/fast-element/src/behaviors/binding-base.ts
- packages/fast-element/src/behaviors/trigger.ts
- packages/fast-element/src/controller.ts
- packages/fast-element/src/custom-element.ts
- packages/fast-element/src/di.ts
- packages/fast-element/src/directives/bind.ts
- packages/fast-element/src/directives/directive.ts
- packages/fast-element/src/directives/ref.ts
- packages/fast-element/src/directives/repeat.ts
- packages/fast-element/src/directives/when.ts
- packages/fast-element/src/expression.ts
- packages/fast-element/src/fast-element.ts
- packages/fast-element/src/instructions.ts
- packages/fast-element/src/observation/array-observer.ts
- packages/fast-element/src/observation/notifier.ts
- packages/fast-element/src/observation/observable.ts
- packages/fast-element/src/observation/subscriber-collection.ts
- packages/fast-element/src/projectors.ts
- packages/fast-element/src/styles.ts
- packages/fast-element/src/template-compiler.ts
- packages/fast-element/src/template.ts
- packages/fast-element/src/view.ts
A refactor PR that renames all interfaces to remove the "I" prefix.
According to the team's code style guidelines, interfaces should not start with an "I".
No functionality has changed. However, the type names for most interface types changed as part of this PR, so anyone dependent on those types would need to update. It's unlikely that anyone is dependent on that. Even if so, the fix is a very simple find/replace chore.
> refactor(all): remove I from interface names

- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.props.ts
- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.spec.tsx
- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
Add fixedHeight property to HorizontalOverflow.
https://github.com/microsoft/fast-dna/issues/2687
When server side rendering - the children heights are not calculated meaning height is always "auto". This feature allows a known fixed height to be used instead.
> feat: add fixed height to horizontal overflow

- packages/fast-components-react-msft/src/action-trigger/action-trigger.stories.tsx
- packages/fast-components-react-msft/src/button/button.stories.tsx
- packages/fast-components-react-msft/src/call-to-action/call-to-action.stories.tsx
- packages/fast-components-styles-msft/src/accent-button/index.ts
- packages/fast-components-styles-msft/src/action-trigger/index.ts
- packages/fast-components-styles-msft/src/button/index.ts
- packages/fast-components-styles-msft/src/lightweight-button/index.ts
- packages/fast-components-styles-msft/src/neutral-button/index.ts
- packages/fast-components-styles-msft/src/outline-button/index.ts
- packages/fast-components-styles-msft/src/stealth-button/index.ts
- packages/fast-components-styles-msft/src/utilities/high-contrast.ts
closes: #2696 
This change makes sure that when a `<Button/>` is passed a `href` and renders an `<a/>` that the hover and active states remain the same. Since `:enabled` selectors don't apply to `<a/>` we need to specify and `hover` and `active` state for `<a/>`.
this change applies to all appearance variations of `<Button/>`, `<AccentButton/>`, `<LightweightButton/>`, `<NeutralButton/>`, `<OutlineButton/>`, `<StealthButton/>`, all appearance variations of `<ActionTrigger/>`, and all appearance variations of `<CallToAction/>` so please test accordingly.
> fix: button anchors have no hover or active states

- packages/fast-element/src/controller.ts
- packages/fast-element/src/custom-element.ts
- packages/fast-element/src/directives/repeat.ts
- packages/fast-element/src/directives/when.ts
- packages/fast-element/src/expression.ts
- packages/fast-element/src/template.ts
- packages/fast-element/src/view.ts
This PR improves the types related to templates/views and removes some unnecessary code.
The design of the `Template` interface was a bit awkward, requiring the consumer to call a method with a boolean that would return a different type based on the boolean value. This PR creates two new template interfaces instead (`ElementViewTemplate`, `SyntheticViewTemplate`), which each have a `create` method that returns the appropriate type (`ElementView`, `SyntheticView`). The actual underlying implementation is the same, but this allows the type system to ensure that the template and the view it creates is being used consistently, based on the intent. This can be seen in the updates to `when` and `repeat` which now take a dependency on a particular template type. With this in place, some …
> refactor(fast-element): improve types and remove unneeded code for views

- packages/fast-tooling-react/src/form/controls/control.linked-data.props.ts
- packages/fast-tooling-react/src/form/controls/control.linked-data.spec.tsx
- packages/fast-tooling-react/src/form/controls/control.linked-data.style.ts
- packages/fast-tooling-react/src/form/controls/control.linked-data.tsx
- packages/fast-tooling-react/src/form/controls/index.ts
- packages/fast-tooling-react/src/form/controls/utilities/control-switch.spec.tsx
- packages/fast-tooling-react/src/form/controls/utilities/control-switch.tsx
- packages/fast-tooling-react/src/form/controls/utilities/types.ts
- packages/fast-tooling-react/src/form/form.tsx
- packages/fast-tooling-react/src/form/templates/template.control.bare.spec.tsx
- packages/fast-tooling-react/src/form/templates/template.control.single-line.spec.tsx
- packages/fast-tooling-react/src/form/templates/template.control.standard.spec.tsx
Add linked data control to the `Form`. This makes adding and removing linked data a default behavior.
Relies on #2710 and #2705, #2704 to pass the build
> feat: add linked data control to update dictionary data

- packages/fast-tooling-react/src/data-utilities/generate.spec.ts
- packages/fast-tooling-react/src/data-utilities/generate.ts
Removes the now redundant checks for `reactProperties` and `childOptions`.
The changes made to the data structure to turn it into a dictionary of data addresses both of these options where adding a new item is done by consulting a schema dictionary. This is now no longer done even if a dictionary link is specified and required, which may be a feature later.
> chore: remove react specific checks from data generation

- specs/README.md
- specs/form-associated-custom-element.md
This specification is designed to outline a base class for implementing custom form elements in web components.
(living) prototype implementation of this spec exists here: https://github.com/microsoft/fast-dna/blob/users/nirice/wc-checkbox-prototype/packages/fast-components/src/checkbox/checkbox.ts
> chore: adds form-associated-custom-element spec

- packages/fast-element/src/behaviors/attribute.ts
Addresses the issue that occurs when properties with a null or undefined value are bound to an HTML attribute.
When binding something like `aria-label=${x => x.ariaLabel}`, if the `ariaLabel` property's value is `undefined` the the `aria-label` attribute gets set to the string "undefined", which is not desirable.
This PR fixes the above behavior such that if the value is either `null` or `undefined` the attribute is removed from the DOM all-together.
A follow-up feature is to allow our custom attributes to behave as boolean attributes and to also provide type conversion. For example, the string "true" often needs to be converted to the boolean value `true`. Boolean attributes and attribute type conversion are two separate features, but often a boolean …
> fix(fast-element): undefined/null should remove the html attribute

- packages/fast-components/src/form-associated/index.ts
- packages/fast-components/tslint.json
Removes the member ordering requirement from tslint for the `@microsoft/fast-components` package
The `@microsoft/fast-components` package makes heavy use of the decorators and FastElement class exposed by `@microsoft/fast-element`. One key capability is the ability to define a observable property, which will automatically invoke a named callback when the property changes if the callback is defined. See the following:
```TypeScript
@observable public disabled: boolean = false;
private disabledChanged() {
// do something when this.disabled changes
}
```
A useful  code structure is to group the property and the change callback together in the file. Member ordering linting rules makes this difficult though for several reasons:
1. The callback must be a method, not a property
2. The method and …
> chore: disable member ordering for fast-components package

- packages/fast-tooling/README.md
- packages/fast-tooling/src/data-utilities/index.ts
- packages/fast-tooling/src/data-utilities/mapping.spec.ts
- packages/fast-tooling/src/data-utilities/mapping.ts
This is a mapping utility for the data dictionary to allow a user an easy method for transforming the data.
This will be used as a replacement for the now defunct (due to the update to the data dictionary interface) utility `mapDataToComponent`. There can now be React specific and other methods for mapping data in the data dictionary.
> feat: add a data mapper

- packages/fast-components/src/card/card.styles.ts
- packages/fast-components/src/dialog/dialog.styles.ts
- packages/fast-components/src/styles/elevation.ts
- packages/fast-components/src/styles/index.ts
Brings over the elevation algorithm into `@microsoft/fast-components` package.
Follow up to this work will be to correct the algorithm when dependency support is added to `@microsoft/fast-element`: https://github.com/microsoft/fast-dna/issues/2778
> feat: add elevation algorithm to web-components

- packages/fast-element/docs/building-components.md
- packages/fast-element/src/fast-element.ts
Allow element authors to provide shadow and element options as overrides of defaults.
Prior to this change, if an element author wanted to configure their shadow root with `delegatesFocus: true`, they would also have to specify the `mode`, even though they didn't want to change this behavior. As of this PR, the shadow and element options config objects allow the element author to only specify what is different from the defaults. When the final element definition is built up, the overrides are merged with our library defaults to produce the final options object used by the underlying platform APIs.
> feat(fast-element): base shadow and element options on defaults

- packages/fast-tooling/src/data-utilities/mapping.spec.ts
- packages/fast-tooling/src/data-utilities/mapping.ts
- packages/fast-tooling/src/data-utilities/types.ts
Adds an HTML mapper, this ties in to #2800 and provides a mapping function for the data structures into HTML elements so that they can be attached to the DOM.
This will aide in the dynamic creation of web components.
> feat: add a mapper for HTML elements

- packages/fast-components-react-base/src/tabs/tabs.tsx
Preact does not filter out `null` results in `children.map` added a function to filter for truthyness.
This PR is form 2018 and never got merged in:
https://github.com/preactjs/preact-compat/pull/461
> fix: ensure null values are removed from tabs

- packages/fast-element/src/directives/when.ts
- packages/fast-element/src/fast-element.ts
- packages/fast-element/src/interfaces.ts
- packages/fast-element/src/view.ts
A small PR that adds some API docs for clarity and fixes a couple small bugs.
A typing fix was needed in order to prevent decorator errors. Types were relaxed in order to address the issue. While doing this work, I noticed a small issue with `when` and the order of view removal, so I fixed that. I also wanted to start the process of documenting APIs, so I added some comments to the recent API changes to make them clearer (when I was working on fixing `when` I realized they needed some explanation.)
> fix(fast-element): type fixes, api docs, and one op order correction

- packages/fast-element/src/template-compiler.ts
- packages/fast-element/src/template.ts
- packages/fast-element/src/view.ts
After removing a view from the DOM, its firsChild and lastChild node pointers were not refreshed, causing subsequent removals to fail.
This fixes issue #2816. Additionally, a second bug was fixed in template compilation, which only manifested when the first node of a view is a marker node.
> fix(view): ensure first/last child correct after removing view

- packages/fast-tooling-react/src/data-utilities/mapping.spec.tsx
- packages/fast-tooling-react/src/data-utilities/mapping.tsx
- packages/fast-tooling/src/data-utilities/mapping.spec.ts
- packages/fast-tooling/src/data-utilities/mapping.ts
- packages/fast-tooling/src/message-system/data.props.ts
- packages/fast-tooling/src/message-system/navigation.props.ts
This change updates the `mapDataDictionary`, `htmlResolver`, `htmlMapper`, `reactMapper` and `reactResolver` utilities. The mapping now takes place at the root level data item in the data dictionary and traverses the tree of data items and executes a mapper, then it travels back up in the reverse order to the root level data item and executes a resolver. This allows for the multiple nesting of items in HTML as the parent item must be created before multiple items can be inserted.
> feat: add the ability to nest multiple items at the same level in an element

- packages/fast-tooling-react/src/form/templates/template.control.utilities.tsx
Adds in prop that should have been passed to the config to allow for the default browser validation to work.
> fix: add back in browser default validation when objects are used

- packages/fast-tooling-react/app/pages/form/index.ts
- packages/fast-tooling-react/src/__tests__/schemas/disabled.schema.ts
- packages/fast-tooling-react/src/__tests__/schemas/index.ts
- packages/fast-tooling-react/src/form/controls/control.section.style.ts
- packages/fast-tooling-react/src/form/templates/const-value.props.ts
- packages/fast-tooling-react/src/form/templates/const-value.tsx
- packages/fast-tooling-react/src/form/templates/default-value.props.ts
- packages/fast-tooling-react/src/form/templates/default-value.tsx
- packages/fast-tooling-react/src/form/templates/template.control.bare.style.ts
- packages/fast-tooling-react/src/form/templates/template.control.utilities.tsx
Does the following:
- Removes disabled styling from the `<fieldset>` which represents objects. This was causing a multiplication effect on contained types on opacity.
- Adds a disabled prop to the components which now prevents a user from modifying the value via the generated UI for setting const, default and soft remove.
Resolves #2796
> fix: update opacity so that it no longer applies to objects and prevents users from modifying the value via const, soft remove and default buttons

- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
A recent change to horizontal overflow added an isOverflow() check on mount which could result in a null ref error when the item container ref was null.    Straightforward fix was to have getItemWidths() return an empty array rather than null when the ref is nil.
Manifested in partner tests.  Not sure how to replicate this in our test environment - ie. trigger componentDidMount without having a valid container ref.
> fix: update to avoid null ref error on horizontal overflow mount

- packages/fast-element/src/attributes.ts
- packages/fast-element/src/controller.ts
- packages/fast-element/src/fast-element.ts
- packages/fast-element/src/observation/observable.ts
This PR adds support for type conversion of attribute values as well as boolean attribute behavior.
Specifically, this PR implements #2742 by adding new APIs to the AttributeDefinition class, which is now used by attribute getters and setters to change values. The APIs are also used to respond to the onAttributeChangedCallback.
The feature enables three modes (`reflect`, `boolean`, `none`) per the above issue, and also enables a custom converter, per the above issue. A `booleanConverter` is provided out of the box and is automatically set when in `boolean` mode.
Here's how one would create a custom element with a boolean attribute behavior:
```TypeScript
@customElement(...)
export class Switch extends FastElement {
@attr({ mode: 'boolean' }) disabled = false;
}
```
This PR also updates …
> feat(fast-element): boolean attributes and type conversion

- packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
We were using a reduce function without an inial value so it could throw on an empty array.  Added an initial value of 0.
Avoid throwing error
> fix: horizontal overflow - add initial value to reduce fn to avoid throw

- packages/fast-element/src/template-compiler.ts
Host attributes that don't have a special directive associated with them are missing their attribute name.
This PR fixes a host attribute bug that was an oversight during the last revamp of how attribute and property binding works.
This particular bug and another one from earlier this week signals to me that we are far enough along where we need to get tests on the core library, so we can prevent regressions. Up until the last two weeks, various aspects of the library have been volatile enough that extensive tests would have slowed down the ability to revise and pivot quickly. I think we're past that point now and we need to get the infrastructure and some basic tests in place. Unless we have another urgent need, I plan to make that my next task.
> fix(fast-element): ensure host attributes have a target name

- packages/fast-components-react-base/src/select/select.spec.tsx
- packages/fast-components-react-base/src/select/select.tsx
When a menu item is selected via click we will force focus to the trigger element.  We previously did this only for keyboard selection but some accessiblity scenarios benefit from ensuring focus remains on the component with mouse/touch selection as well.
Partners raised issue.
> fix: select focus on trigger on click selection in menu

- packages/fast-components-react-base/src/tabs/tabs.spec.tsx
- packages/fast-components-react-base/src/tabs/tabs.tsx
- packages/fast-components-react-msft/src/carousel/carousel.tsx
- packages/fast-components-react-msft/src/pivot/pivot.tsx
This change fixes the interaction model to align with the W3C specification.
It was recently brought to my attention that the MSFT carousel and pivot components both prevent page scroll behavior on arrow up/down events. While that behavior is expected for vertically oriented tabs, it is unexpected for horizontally oriented tabs. The [W3C specification](https://w3c.github.io/aria-practices/#keyboard-interaction-20) specifically details that horizontal tabs do not listen for up/down events to enable the default browser behavior:
> If the tab list is horizontal, it does not listen for Down Arrow or Up Arrow so those keys can provide their normal browser scrolling functions even when focus is inside the tab list.
With this in mind, I've updated the control to behave as expected. In addition, …
> fix: correct tabs interaction model to map to the w3c specification and add default orientation

- packages/fast-tooling-react/src/form/utilities/breadcrumb.spec.ts
- packages/fast-tooling-react/src/form/utilities/breadcrumb.ts
Corrects an issue where there was incorrect sequence of the breadcrumbs displaying where sometimes the items were reversed. This now reverses all breadcrumb items at the end of the process.
> fix: update breadcrumbs to have the proper sequence when nesting linked data

- packages/fast-tooling-react/src/navigation/navigation.props.ts
- packages/fast-tooling-react/src/navigation/navigation.tsx
This cleans up a redundant state item that was missed on the last pass, `isDragging` which is not necessary for styling purposes anymore. It also updates the parent location in the linked data as this was falling out of sync after more than one drag and drop event.
> fix: remove a redundant state for dragging, update the parent location of the linked data during hover

- packages/fast-tooling-react/src/navigation/navigation-tree-item.tsx
This helps address some of the performance hit when ending a drop over a navigation item that is not a drop target, there is however still a delay when dropping outside of the `<Navigation />` component.
This also removes the monitored but unused `isOver` property from the `react-dnd` monitor.
Starts to address #2867
> fix: improve performance on the end drag by making all navigation items drop targets

- packages/fast-element/src/dom.ts
When checking if a node is a marker node, ensure that it is not null or undefined.
While working on the `fast-divider` component, @chrisdholt discovered an odd case where the compiler would throw on one of two nearly-identical templates. The only difference is that one template had no children, and the second had a single empty text node. As it turns out, the compiler was not accounting for the case where a template would have no child nodes. It seems an odd case, but is legitimate. This PR fixes the issue by checking before accessing properties on the node.
> fix(fast-element): ensure node exists when checking if it's a marker

- packages/fast-element/src/attributes.ts
- packages/fast-element/src/controller.ts
- packages/fast-element/src/directives/binding.ts
- packages/fast-element/src/directives/repeat.ts
- packages/fast-element/src/directives/when.ts
- packages/fast-element/src/fast-element.ts
- packages/fast-element/src/observation/array-observer.ts
- packages/fast-element/src/observation/observable.ts
Up until now, a binding expression in a template could only observe the last property accessed in the expression. This PR enables observation of all properties accessed in the expression.
This PR introduces the `ObservableExpression` class, which implements all the machinery needed to evaluate an expression while observing it. Here's how it works:
When Instantiated:
* `ObservableExpression` is first instantiated with a normal `Expression` as well as an `ExpressionObserver`.
When `evaluate` is called:
* The observer sets itself as the `watcher` for all observables and then invokes the expression.
* Each `Observable` invokes `Observable.track()` when its getter is accessed, which gets routed to the current `watcher` so that it knows what object and property was just accessed.
* The …
> feat(fast-element): add multi property binding support

- packages/web-components/fast-components/src/text-area/README.md
- packages/web-components/fast-components/src/text-area/text-area.ts
This PR adds form association support to the textarea web component.
> fix: form associate the textarea component

- packages/react/fast-components-styles-msft/src/toggle/index.ts
When you tab into the toggle component it would add the inner border but main border was not changing color. I added a high contrast border on the apply focus state. This will give a clearer indication that the toggle has been focused.
close #2926
before
after
> fix: high contrast focus border on toggle when unselected

- packages/web-components/fast-components/src/text-field/text-field.styles.ts
Fix and update high contrast colors on the icons and when hovering over the text field. 
When hovering on the text field it was showing a white background. 
The fix shows no background and only the border changes color.
The icons are fixed with ButtonText color.
before
after
When hovering over the `fill` version of the text field, the border was still changing color when disabled.
The fix sets the border to GrayText when hovered.
> fix: update high contrast colors on hover on text field component

- packages/web-components/fast-components/src/switch/switch.styles.ts
Updated the background of the switch, when selected, to be Highlight color. When disabled, the labels are also set to GrayText color. There is also a double border on tab focus, in the selected state. 
before
after
> fix: update high contrast colors on switch component

- packages/web-components/fast-components/src/flipper/flipper.styles.ts
None of the high contrast colors were showing up, part of the fix was adding a missing semicolon. On hover, we now see Highlight and HighlightText color.
Added rule sets for disabled state.
before
after
Added focus visible.
> fix: high contrast color for hover and disabled, in flipper web component

- packages/web-components/fast-components/src/custom-properties/behavior.ts
- packages/web-components/fast-components/src/design-system-consumer/design-system-consumer.ts
Improves the performance of the algorithm for finding an element's contextual design-system-provider element.
A previous change adjusted the recipe system to associate with stylesheets instead of components. In introducing that change, a side effect was that each recipe was resolving the design-system-provider independently, leading to a significant amount of duplicated work.
This change adjust the `findProvider` algorithm used by recipes to first check to see if a provider has been stored on the source object. If it has, a reference to that provider will be returned. Additionally, when a provider is found, a reference top the provider is stored on the source object for future invocations of the function. This means each element is only finding the provider once.
This change also …
> fix: improve performance of finding contextual design-system-providers

- packages/web-components/fast-components/src/slider-label/fixtures/base.html
- packages/web-components/fast-components/src/slider-label/slider-label.styles.ts
- packages/web-components/fast-components/src/slider-label/slider-label.template.ts
- packages/web-components/fast-components/src/slider-label/slider-label.ts
- packages/web-components/fast-components/src/slider/index.ts
- packages/web-components/fast-components/src/slider/slider.styles.ts
Taking a high contrast color pass in slider and slider label.
The disabled color on the slider and slider label is not being set to the disabled color.
I was able to add a fix to the slider.
Instead of adding the fix for `slider-label` inside the `slider` component, I added a disabled attribute to`slider-label` and also set the disabled styles inside the label component. This will also not have the `slider-label` style dependent on `slider`.
Added disabled to the SliderConfiguration and if the `slider` is disabled, the `slider-label` style will get set.
Also added a disabled example for `slider-label`.
When hovering over the slider thumb, it is now set to Highlight.
> fix: high contrast color on slider and slider label

- packages/tooling/fast-tooling/README.md
- packages/tooling/fast-tooling/src/message-system/message-system.props.ts
- packages/tooling/fast-tooling/src/message-system/message-system.spec.ts
- packages/tooling/fast-tooling/src/message-system/message-system.ts
In the case where data and schemas are fetched from another system but the initialization of the message system needs to occur before this happens, allow an initialization message to be sent and the initial config to only include the location of the web worker.
Resolves #2975 
Requires the completion of #2982 
> feat: allow initialization to occur after creating an instance of the MessageSystem

- packages/tooling/fast-tooling/README.md
- packages/tooling/fast-tooling/src/message-system/message-system.props.ts
- packages/tooling/fast-tooling/src/message-system/message-system.spec.ts
- packages/tooling/fast-tooling/src/message-system/message-system.ts
Includes the ability to use a `Worker` instance directly. This is to facilitate the use of the webpack `worker-loader`.
Resolves #2990 
> feat: allow the use of an already instantiated Worker in the MessageSystem config

- packages/web-components/fast-components/src/slider/slider.template.ts
- packages/web-components/fast-components/src/slider/slider.ts
* removed warning caused in slider 
* prefixing attributes, disabled and readonly that may be false
> chore: removed warning caused in slider and prefixing attributes that may be false

- packages/web-components/fast-components/src/tabs/tab/tab.styles.ts
- packages/web-components/fast-components/src/tabs/tabs.styles.ts
Adding forced colors to fix high contrast.
Adding forced colors to tab to remove borders, and tabs to set high contrast color on the indicator.
before
after
> fix: high contrast color on tab indicator

- packages/web-components/fast-components/src/radio/radio.styles.ts
Update the radio indicator color
The radio indicator is now visible when the radio is checked. 
before
after
Also, set the colors to invert on hover.
> fixed: high contrast color on radio indicator

- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
Update to add high contrast color on checkbox when selected, hovered, and focused.
The fix is based on the principles we established in our other checkbox components.
In the checked state, the checkbox background is filled with the Highlight color. When hovering, the colors are inverted. Tabbed focus gets a double border treatment.
rest-hover-focus
> fix: update selected, hover and focus high contrast colors for checkbox

- packages/web-components/fast-components/src/button/button.styles.ts
- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components/src/flipper/flipper.styles.ts
- packages/web-components/fast-components/src/progress/progress-ring/progress-ring.styles.ts
- packages/web-components/fast-components/src/progress/progress/progress.styles.ts
- packages/web-components/fast-components/src/radio/radio.styles.ts
- packages/web-components/fast-components/src/slider-label/slider-label.styles.ts
- packages/web-components/fast-components/src/slider/slider.styles.ts
- packages/web-components/fast-components/src/styles/patterns/button.ts
- packages/web-components/fast-components/src/switch/switch.styles.ts
- packages/web-components/fast-components/src/tabs/tab/tab.styles.ts
- packages/web-components/fast-components/src/tabs/tabs.styles.ts
- packages/web-components/fast-components/src/text-area/text-area.styles.ts
- packages/web-components/fast-components/src/text-field/text-field.styles.ts
Following the work on adding a forced-colors behavior function. I have gone through to move all of our high contrast styles from forced-colors media query into `forcedColorsStylesheetBehavior`. This implementation will conditionally apply high-contrast styles to the components.
> fix: move high contrast styles to use forced color stylesheet behavior

- packages/web-components/fast-components/src/flipper/flipper.styles.ts
Set the opacity to 1 on the before pseudo-class because the highlight color is too dimmed when hovered.
before
after
> fix: opacity on before pseudo class when hovering

- packages/tooling/fast-figma-plugin-msft/package.json
- packages/tooling/fast-figma-plugin-msft/src/core/ui/index.tsx
- packages/tooling/fast-figma-plugin-msft/src/core/ui/swatch.tsx
- packages/tooling/fast-figma-plugin-msft/src/global.css
- yarn.lock
Standardizes the color-picker control so we don't have differences and bugs stemming from native implementations of the color picker.
The color-picker shipped by OSX likes to send 100s of events per second while the user is dragging around the color-wheel. This requires a whole host of issues to fix, including debouncing the event, maintaining an un-denounced state so the picker doesn't feel laggy, and reconciling the two when the user stops interacting.
> fix: replace color picker in figma plugin

- packages/web-components/fast-components/src/design-system-provider/index.ts
Adds typeramp to the design-system provider as configurable design-system properties.
> feat: adding typeramp values

- packages/tooling/fast-tooling-react/src/data-utilities/mapping.spec.tsx
- packages/tooling/fast-tooling-react/src/data-utilities/mapping.tsx
- packages/tooling/fast-tooling/src/data-utilities/mapping.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/mapping.ts
Creates a new options in the configuration for the `mapDataDictionary` utility that allows for mappers to be assigned using `pluginId` in the JSON schema.
> feat: add plugin system to the data dictionary mapping utility

- packages/web-components/fast-components/src/radio-group/README.md
- packages/web-components/fast-components/src/radio-group/fixtures/base.html
- packages/web-components/fast-components/src/radio-group/index.ts
- packages/web-components/fast-components/src/radio-group/radio-group.spec.md
- packages/web-components/fast-components/src/radio-group/radio-group.stories.ts
- packages/web-components/fast-components/src/radio-group/radio-group.styles.ts
- packages/web-components/fast-components/src/radio-group/radio-group.template.ts
- packages/web-components/fast-components/src/radio-group/radio-group.ts
- packages/web-components/fast-components/src/radio/radio.template.ts
- packages/web-components/fast-components/src/radio/radio.ts
- specs/README.md
* Add radio group component
* tabindex support for tab navigation
* arrow key navigation
radio-group component allows children radio buttons to be treated as a single select group.
> feat: add radio-group component

- sites/fast-website/package.json
- sites/fast-website/src/app/components/gradient-picker/index.ts
- sites/fast-website/src/app/components/index.ts
- sites/fast-website/src/app/index.ts
- sites/fast-website/src/public/index.html
- sites/fast-website/tsconfig.json
- sites/fast-website/webpack.config.js
- sites/fast-website/yarn.lock
Load fast-components for consumption on the website project.
This shoehorns all WCs available, we should probably reduce this from loading all to just the ones we need in the future.
> chore: load all the fast-components

- packages/react/fast-components-react-base/src/auto-suggest/auto-suggest.spec.tsx
- packages/react/fast-components-react-base/src/auto-suggest/auto-suggest.tsx
Add `aria-expanded` attribute to auto-suggest combobox input.
- [Accessibility fix](https://www.w3.org/WAI/GL/wiki/Using_the_WAI-ARIA_aria-expanded_state_to_mark_expandable_and_collapsible_regions) - combobox must have aria-expanded
- Resolves #3009
> fix: add aria-expanded state to auto-suggest input

- sites/fast-website/src/app/components/index.ts
- sites/fast-website/src/app/components/section-header/index.ts
- sites/fast-website/src/app/components/section-header/section-header.styles.ts
- sites/fast-website/src/app/components/section-header/section-header.template.ts
- sites/fast-website/src/app/components/section-header/section-header.ts
- sites/fast-website/src/public/index.html
- sites/fast-website/src/public/style.css
This component is used in the hero section and in every other section down the page.
The templates consist of one default slot and three named slots (`badge`, `body` and `action`)
> feat: create section-header component for marketing site

- lerna.json
- package.json
- tsconfig.json
- yarn.lock
This PR adds the new `fast-website` and its `devDependencies` to the Yarn and Lerna workspaces.
Since we're temporarily using ultra-new additions from within the repo, we want to make sure our node_modules are pointing to the local neighbor instead of downloading the package independently.
> chore: add fast-website to the yarn and lerna workspaces

- packages/web-components/fast-components/src/index.ts
This commit adds `cssCustomPropertyBehaviorFactory` to the bundled exports.
Closes #3077
As mentioned in [this comment](https://github.com/microsoft/fast-dna/pull/3061#discussion_r421011341), the `cssCustomPropertyBehaviorFactory` wasn't getting exported via the index bundle.
> fix: add custom-properties exports to fast-components bundle

- packages/web-components/fast-components/src/radio-group/fixtures/base.html
- packages/web-components/fast-components/src/radio-group/radio-group.styles.ts
- packages/web-components/fast-components/src/radio-group/radio-group.template.ts
- packages/web-components/fast-components/src/radio-group/radio-group.ts
In response to #3069 adding the orientation attribute to fast-radio-group to allow for vertical orientation and a default of horizontal.
Motivation described in proposal #3069.
> feat: add vertical and horizontal orientation for radio-group

- packages/web-components/fast-components/src/button/button.template.ts
- packages/web-components/fast-components/src/button/button.ts
Move class setter to template.
Setting the class in the change callback can cause a runtime error because the `appearance` value is initialized in the constructor, which in turn calls the change callback and sets the class attribute. Setting element attributes in the constructor causes a runtime error in Chromium and is to be avoided.
> fix: move appearance class application to template

- packages/utilities/fast-eslint-rules/.eslintrc.js
It is sometimes nice to know which arguments a function has access to even if the implementation does not use those arguments.
This change configures eslint to not warn when function arguments go unused.
This change is a related to https://github.com/microsoft/fast-dna/pull/3113#discussion_r424000211
> fix: update eslint config to not warn on function args

- packages/web-components/fast-components/src/slider/fixtures/base.html
- packages/web-components/fast-components/src/slider/slider.ts
When any margin or offset was present with a slider, that offset wasn't taken into account when calculating the thumb's position.
Fixes #3121
> fix: set slider thumb offset against its left position in the document

- packages/web-components/fast-components/src/design-system-provider/index.ts
- packages/web-components/fast-foundation/src/design-system-provider/design-system-property.ts
- packages/web-components/fast-foundation/src/design-system-provider/design-system-provider.ts
The `@designSystemProperty` decorator originally made an assumption that the property being decorated was *also* an observable property. 
This change removes that assumption and does work to set up the attr / observable itself.
closes #3110
> feat: wrap attr and observable into designSystemProperty decorator

- packages/web-components/fast-components/src/default-palette.ts
- sites/fast-website/package.json
- sites/fast-website/src/app/components/color-swatch/color-swatch.styles.ts
- sites/fast-website/src/app/components/color-swatch/color-swatch.template.ts
- sites/fast-website/src/app/components/color-swatch/color-swatch.ts
- sites/fast-website/src/app/components/color-swatch/index.ts
- sites/fast-website/src/app/components/content-placement/content-placement.template.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.ts
- sites/fast-website/src/app/components/index.ts
- sites/fast-website/src/public/index.html
Adds finished preview layout and background and accent color selection.
> feat: add accent color and background color selection

- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components/src/radio/radio.styles.ts
- packages/web-components/fast-components/src/switch/switch.styles.ts
- packages/web-components/fast-components/src/text-area/fixtures/text-area.html
- packages/web-components/fast-components/src/text-area/text-area.styles.ts
- packages/web-components/fast-components/src/text-field/text-field.styles.ts
- packages/web-components/fast-foundation/src/checkbox/checkbox.template.ts
- packages/web-components/fast-foundation/src/checkbox/checkbox.ts
- packages/web-components/fast-foundation/src/radio/radio.template.ts
- packages/web-components/fast-foundation/src/radio/radio.ts
- packages/web-components/fast-foundation/src/switch/switch.template.ts
- packages/web-components/fast-foundation/src/switch/switch.ts
- packages/web-components/fast-foundation/src/text-area/text-area.template.ts
- packages/web-components/fast-foundation/src/text-area/text-area.ts
- packages/web-components/fast-foundation/src/text-field/text-field.template.ts
- packages/web-components/fast-foundation/src/text-field/text-field.ts
This fix removes `childNodes.length` check and replaces it with the `slotted` directive. `childNodes.length` is a one-time render. If child nodes changes, `childNodes.length` won't update because it's not observable.
> fix: replaces childNodes.length check with slotted

- packages/web-components/fast-components-msft/src/badge/badge.styles.ts
- packages/web-components/fast-components-msft/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components-msft/src/radio/radio.styles.ts
- packages/web-components/fast-components-msft/src/slider/slider.styles.ts
- packages/web-components/fast-components-msft/src/styles/patterns/button.ts
- packages/web-components/fast-components-msft/src/switch/switch.styles.ts
- packages/web-components/fast-components-msft/src/tabs/tabs.styles.ts
- packages/web-components/fast-components-msft/src/text-area/text-area.styles.ts
- packages/web-components/fast-components-msft/src/text-field/text-field.styles.ts
- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components/src/flipper/flipper.styles.ts
- packages/web-components/fast-components/src/menu-item/menu-item.styles.ts
- packages/web-components/fast-components/src/radio/radio.styles.ts
- packages/web-components/fast-components/src/slider/slider.styles.ts
- packages/web-components/fast-components/src/styles/patterns/button.ts
- packages/web-components/fast-components/src/switch/switch.styles.ts
- packages/web-components/fast-components/src/text-area/text-area.styles.ts
- packages/web-components/fast-components/src/text-field/text-field.styles.ts
1. Cleans up several styling issues
2. Focus visuals incorrect on some controls.
3. Focus visuals not visible on some controls.
4. Disabled controls still had hover and active states.
5. Alignment of padding across text input controls
6. Maps type ramp to design system in MSFT
Example Before:
Example After:
> fix: focus visuals and style clean up

- packages/react/fast-components-react-base/src/stack-panel/stack-panel.spec.tsx
- packages/react/fast-components-react-base/src/stack-panel/stack-panel.tsx
Stop rendering items when we reach the end of a too short itemspan array
Could throw otherwise, esp when rendering children before recalculating layout after update.
> fix: stackpanel should not throw when itemspan list is too short

- packages/react/fast-components-react-base/src/checkbox/checkbox.props.ts
- packages/react/fast-components-react-base/src/checkbox/checkbox.schema.2.ts
- packages/react/fast-components-react-base/src/checkbox/checkbox.schema.ts
- packages/react/fast-components-react-base/src/checkbox/checkbox.spec.tsx
- packages/react/fast-components-react-base/src/checkbox/checkbox.tsx
- packages/react/fast-components-react-base/src/radio/radio.props.ts
- packages/react/fast-components-react-base/src/radio/radio.schema.2.ts
- packages/react/fast-components-react-base/src/radio/radio.schema.ts
- packages/react/fast-components-react-base/src/radio/radio.spec.tsx
- packages/react/fast-components-react-base/src/radio/radio.tsx
This PR adds a first class prop for aria-hidden to the radio and checkbox input elements. Due to the way that unhandled props are passed, adding a non-visible label to the checkbox or radio is currently not fully possible. Previously attempts were made to use the hidden attribute on the label element, but the global attribute here actually breaks the relationship. If the label is not visibly present, it is not passed on to AT either.
> feat: add first class prop for aria-label to radio and checkbox

- packages/web-components/fast-components/src/slider/fixtures/base.html
- packages/web-components/fast-foundation/src/slider/slider-utilities.ts
- packages/web-components/fast-foundation/src/slider/slider.ts
Existing value and positioning calculations would break when negative values were used for positioning, min, max.
* Unified the percentage calc for label positioning and thumb positioning
* Made the calculations work when min or position values are negative numbers
> fix: bug in positioning when negative numbers were involved

- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.ts
Adds density slider to marketing site
> feat: adds density slider to marketing site

- packages/web-components/fast-foundation/src/radio-group/radio-group.ts
Some child elements in the default slot were getting filtered out of the slottedRadios collection thus breaking the group related functionality, also there was no check to see there was a collection and at least one item in that collection before setting focus to the first element.
* now checking there is at least one element in the radio collection before setting default focus
* replaced HTMLInputElement with any to avoid compilation error and to allow more component types to be in the collection
> fix: children components not always added to the internal slotted radio control collection

- packages/web-components/fast-components-msft/src/radio-group/fixtures/radio-group.html
- packages/web-components/fast-components-msft/src/slider/fixtures/slider.html
- packages/web-components/fast-components/src/radio-group/fixtures/base.html
- packages/web-components/fast-components/src/slider/fixtures/base.html
- packages/web-components/fast-components/src/slider/slider.styles.ts
- packages/web-components/fast-foundation/src/radio-group/radio-group.ts
- packages/web-components/fast-foundation/src/slider/slider.ts
* fixed issue with arrow keys navigating the whole page as well as the silder
* fixed bug where initial value of slider was not setting the thumb position correctly
* fixed bug in vertical orientation where movement via mouse was not correct
* Added headers to all the examples in slider and radio-group
* Fixed color for radio-group slotted labels in fast-components
> fix: slider vertical navigation and value setting bugs

- sites/fast-website/src/app/components/color-swatch/color-swatch.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.ts
This change makes styling improvements and hooks up the remainder of the design system knobs except the hue and saturation sliders.
**UPDATE** Added hue and saturation sliders
> feat: remainder of design system knobs

- packages/react/fast-components-styles-msft/src/slider-label/index.ts
Updated the slider label offset to match with the lower and upper bounds of the slider thumb.
The min and max labels were positioned too far outside of the bounds of the control, resulting in alignment discrepancies with other components.
Before and after:
> fix: update min / max slider label position

- sites/fast-website/src/app/components/content-placement-container/content-placement-container.styles.ts
- sites/fast-website/src/app/components/content-placement-container/content-placement-container.template.ts
- sites/fast-website/src/app/components/content-placement-container/content-placement-container.ts
- sites/fast-website/src/app/components/content-placement/content-placement.styles.ts
- sites/fast-website/src/app/data/feature.data.ts
- sites/fast-website/src/app/data/framework.data.ts
- sites/fast-website/src/public/index.html
- add feature cards to content-placement-container
- create data to be used to create feature cards
- update hover styling for both feature and community section
- the color when a card is not hovered on is currently --neutral-foreground-hint though it would be ideal if we had a --neutral-foreground-inactive of some sort to use for the variable here, but currently hint is closest to the color in figma
- --neutral-fill-active is used for the background of the card on hover. This is lighter than the color in the figma, but shows a contrast against the current background color so the hover background can be seen
- add withBehaviors to styles
> chore: add feature card to content-placement-container and update hover styles

- packages/web-components/fast-element/docs/ACKNOWLEDGEMENTS.md
- packages/web-components/fast-element/docs/api-report.md
- packages/web-components/fast-element/docs/guide/defining-elements.doc.md
- packages/web-components/fast-element/src/__test__/helpers.ts
- packages/web-components/fast-element/src/__test__/setup-node.ts
- packages/web-components/fast-element/src/directives/binding.spec.ts
- packages/web-components/fast-element/src/directives/binding.ts
- packages/web-components/fast-element/src/directives/when.spec.ts
- packages/web-components/fast-element/src/directives/when.ts
- packages/web-components/fast-element/src/dom.spec.ts
- packages/web-components/fast-element/src/dom.ts
- packages/web-components/fast-element/src/interfaces.ts
- packages/web-components/fast-element/src/template-compiler.spec.ts
- packages/web-components/fast-element/src/template.spec.ts
- packages/web-components/fast-element/src/template.ts
- packages/web-components/fast-element/src/view.ts
- packages/web-components/fast-element/tsconfig.json
This feature adds the ability for expressions located in arbitrary HTML content to return a template to be rendered into that location.
For an overview of the feature, have a read through issue #3039. The technical approach outlined there was exactly what was put into place here. Additionally, some basic cache smarts were added to the content binding mechanism, enabling the entire `when` directive to be deleted and instead simply be *syntax sugar* on top of the low-level composition capabilities. Everything from #3039 is implemented in this PR with the exception of the changes to `repeat`. Those are planned for a separate PR next week.
Unit tests have been added around content composition, `repeat`, and other areas touched by this PR. As part of the unit test writing process, I realized …
> feat(fast-element): add content composition

- packages/web-components/fast-foundation/package.json
- packages/web-components/fast-foundation/src/fixture.spec.ts
- packages/web-components/fast-foundation/src/fixture.ts
- packages/web-components/fast-foundation/src/utilities/composed-parent.spec.ts
Creates a new `fixture` helper function to set up custom element tests. Also a `uniqueElementName` helper was added to facilitate generating unique element names for test scenarios.
We need some basic utilities to aid in testing web components, including creating them, binding them, and pushing them through their lifecycle, while being able to make assertions along the way.
See `fixture.spec.ts` for example usage.
This PR is dependent on APIs in this PR: https://github.com/microsoft/fast-dna/pull/3182
Note: I'll push another commit in a bit that adds code docs.
After we get some usage of this within our components, I'd like to move this either to its own package, like `@microsoft/fast-testing` where we could also add other test helpers and make this available for the community to use.
> feat(fast-foundation): add element test helper

- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components/src/radio/radio.styles.ts
- packages/web-components/fast-components/src/switch/switch.styles.ts
- packages/web-components/fast-components/src/tabs/tab/tab.styles.ts
Making sure the colors are correct, in high contrast mode, when the components are at rest, hover, selected, or focused.
The background was still showing accent when checked, the fix resolves this issue.
Add a box-shadow border around checkbox on focus, in both unchecked and checked states.
Fixed to remove accent color when the radio is selected. Also added a box-shadow border for focus state.
When the switch is set to on, you will see the accent color show up when hovering the switch component.
Also, add a box-shadow border.
for focus state.
The tab shows an accent and neutral fill color, when selected. The fix removes the background color and sets the foreground and fill to Highlight.
When hovering over the tabs, the background is set to Highlight, and the foreground and fill colors are …
> fix: high contrast updates on checkbox, radio, switch and tabs, web components

- packages/web-components/fast-components-msft/src/card/card.styles.ts
- packages/web-components/fast-components-msft/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components-msft/src/dialog/dialog.styles.ts
- packages/web-components/fast-components-msft/src/flipper/flipper.styles.ts
- packages/web-components/fast-components-msft/src/radio/radio.styles.ts
- packages/web-components/fast-components-msft/src/slider/slider.styles.ts
- packages/web-components/fast-components-msft/src/switch/switch.styles.ts
- packages/web-components/fast-components-msft/src/tabs/tab/tab.styles.ts
- packages/web-components/fast-components-msft/src/text-field/text-field.styles.ts
…ipper, radio, slider, switch, tabs, and text-field
Fixes high contrast on the card, checkbox, dialog, flipper, radio, slider, switch, tabs, and text-field, components.
Fixed the white background on the checkbox component when hovered. 
Fixed the white background on the radio component when hovered. 
Fixed the issue on the switch control for both on/off state, to show the correct color when hovering.
The foreground on the read-only text field now shows the correct color.
The tab content now changes to highlight when selected.
Fixed the focus state on the thumb cursor in the slider component.
Fixed the focus state on the flipper component.
Add a transparent border on the main style of the dialog component, so we don't have to add a border in high contrast mode. The system will just change …
> fix: update high contrast on styles

- packages/tooling/fast-tooling/src/data-utilities/mapping.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/mapping.ts
- packages/tooling/fast-tooling/src/data-utilities/web-component.ts
Instead of using the JSON schema `enum` property this updates to use the `customData` format used by vscode seen [here](https://github.com/Microsoft/vscode-html-languageservice/blob/master/docs/customData.md).
> fix: use the vscode values instead of enum in a web component attribute definition

- packages/web-components/fast-foundation/src/anchor/README.md
- packages/web-components/fast-foundation/src/badge/README.md
- packages/web-components/fast-foundation/src/button/README.md
- packages/web-components/fast-foundation/src/card/README.md
- packages/web-components/fast-foundation/src/checkbox/README.md
- packages/web-components/fast-foundation/src/dialog/README.md
- packages/web-components/fast-foundation/src/divider/README.md
- packages/web-components/fast-foundation/src/flipper/README.md
- packages/web-components/fast-foundation/src/menu-item/README.md
- packages/web-components/fast-foundation/src/menu/README.md
- packages/web-components/fast-foundation/src/progress/README.md
- packages/web-components/fast-foundation/src/radio-group/README.md
- packages/web-components/fast-foundation/src/radio/README.md
- packages/web-components/fast-foundation/src/slider-label/README.md
- packages/web-components/fast-foundation/src/slider/README.md
- packages/web-components/fast-foundation/src/switch/README.md
- packages/web-components/fast-foundation/src/tabs/README.md
- packages/web-components/fast-foundation/src/text-area/README.md
- packages/web-components/fast-foundation/src/text-field/README.md
This PR adds additional component documentation and basic usage examples for fast-foundation.
> chore: add additional component documentation for `fast-foundation`

- README.md
This PR updates the language in the root readme to better represent the current offerings of FAST-DNA.
> chore: update root readme language

- README.md
Hi, this just fix the Microsoft React Components link in the README.md.
> chore: fix React Components link

- sites/site-utilities/src/definitions/fast-components/index.ts
- sites/site-utilities/src/definitions/native/heading.definition.ts
- sites/site-utilities/src/definitions/native/image.definition.ts
- sites/site-utilities/src/definitions/native/index.ts
- sites/site-utilities/src/definitions/native/paragraph.definition.ts
- sites/site-utilities/src/definitions/native/span.definition.ts
Adds the `<h1> - <h6>`, `<p>` and `<span>` elements to the `sites/site-utilities` definitions.
This provides more native elements to use in the Component Explorer and Creator. It is very useful in cases where an element will not look right unless there is some text content inside it, such as `<fast-card>`.
> chore: add additional native element definitions to the site-utilities

- sites/fast-website/src/app/components/content-placement-container/content-placement-container.styles.ts
- sites/fast-website/src/app/components/content-placement-container/content-placement-container.template.ts
- sites/fast-website/src/app/components/content-placement/content-placement.styles.ts
- sites/fast-website/src/app/components/feature-card/feature-card.styles.ts
Rework responsive behavior in cards sections for frameworks, features, and community.
Refactor inner border implementation in frameworks section.
Remove media queries that are no longer needed.
> chore: responsive layout modification of cards sections

- packages/web-components/fast-components/docs/guide/color.doc.md
Adds more accurate and complete descriptions of the usable color pieces. Describes the behavior name and the resulting css custom property name.
> chore: correct import name and custom property name

- sites/fast-website/src/public/index.html
Replaces lorem ipsum text.
Launching a website with lorem ipsum is generally considered bad practice.
> chore: update copy

- packages/web-components/fast-components-msft/rollup.config.js
- packages/web-components/fast-components/rollup.config.js
- packages/web-components/fast-element/rollup.config.js
- packages/web-components/fast-foundation/rollup.config.js
Add a non-minified script file output to all web components packages.
As part of the recent web components build improvements, we added a single file script build, so that customers could simply add a script tag to their page and begin using the components and building their own. As we discussed putting this on CDN we thought it would be nice to have both minified and non-minified versions available. Prior to this PR, the build only emitted minified versions. This PR updates each package to produce two script tag builds, a `.js` that is not minified and a `.min.js` that is.
This is a breaking change to the script file name as the `.js` file was previously minified but after this PR is now non-minified, with the `.min.js` now being the minified version.
> chore(web-components): add non-min script build

- sites/fast-website/src/app/components/content-placement-container/content-placement-container.styles.ts
- sites/fast-website/src/app/components/content-placement-container/content-placement-container.template.ts
- sites/fast-website/src/app/components/feature-card/feature-card.styles.ts
- sites/fast-website/src/app/data/feature.data.ts
- sites/fast-website/src/app/data/framework.data.ts
- add header subscript to framework cards
- grey out links on non hovered community cards
- display numbers on feature cards using index instead of data file
Update: numbers on feature cards are now displayed using css
Community before:
Community after:
Frameworks before:
Frameworks after:
> chore: update card/content styling to match figma

- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/public/index.html
Added max-width of 95vw to fast-frame styles host.  Between 661px and 800px screen width there was an overflow issue that this resolves.
Before:
After:
> fix: overflow issue between 661px and 800px widths

- sites/fast-website/src/app/components/content-placement-container/content-placement-container.styles.ts
- sites/fast-website/src/app/components/content-placement-container/content-placement-container.template.ts
- sites/fast-website/src/app/components/content-placement-container/content-placement-container.ts
- sites/fast-website/src/app/components/content-placement-container/templates/community.template.ts
- sites/fast-website/src/app/components/content-placement-container/templates/feature.template.ts
- sites/fast-website/src/app/components/content-placement-container/templates/framework.template.ts
- sites/fast-website/src/app/components/feature-card/feature-card.styles.ts
Refactor content placement container to select template based on section.  The selectTemplate and selectData functions in the content-placement-container component pass the imported template and data based on the value of the select attribute provided, allowing for removal of the $when function.  Section templates have been separated to their own individual files.
Update styling for feature section in content placement container.
> chore: refactor repeat select template by section

- packages/web-components/fast-element/src/observation/observable.ts
This PR invokes `Object.seal` on the `defaultExeuctionContext` so that its properties cannot be removed or reconfigured, and additional properties cannot be added. This will prevent intentional or unintentional alterations to the context which would affect all views across the system.
Technically a breaking change, but not likely to affect anyone who isn't doing something they shouldn't be.
> fix(fast-element): seal the default execution context

- packages/web-components/fast-components-msft/package.json
- packages/web-components/fast-components/package.json
- packages/web-components/fast-element/package.json
- packages/web-components/fast-foundation/package.json
Adds new configuration to the `package.json` files for web components that enable clean CDN URLs for the latest script-file builds of our libraries. This is leveraging [unpkg](https://unpkg.com/). The URLs will be as follows:
* https://unpkg.com/@microsoft/fast-element
* https://unpkg.com/@microsoft/fast-foundation
* https://unpkg.com/@microsoft/fast-components
* https://unpkg.com/@microsoft/fast-components-msft
> chore(web-components): add unpkg config for nicer cdn urls

- packages/react/fast-components-styles-msft/src/progress/index.ts
- packages/web-components/fast-components-msft/src/progress/progress-ring/progress-ring.styles.ts
- packages/web-components/fast-components-msft/src/progress/progress/progress.styles.ts
- packages/web-components/fast-components/src/progress/progress-ring/progress-ring.styles.ts
- packages/web-components/fast-components/src/progress/progress/progress.styles.ts
Updated progress from accent fill to accent foreground.
In dark mode the wrong accent color was used, resulting in low contrast and failing accessibility tests.
> fix: update progress from accent fill to accent foreground

- packages/web-components/fast-components-msft/docs/api-report.md
- packages/web-components/fast-components-msft/src/anchor/fixtures/anchor.html
- packages/web-components/fast-components-msft/src/styles/patterns/button.ts
- packages/web-components/fast-components-msft/temp/api-report.md
- packages/web-components/fast-components/src/anchor/fixtures/anchor.html
- packages/web-components/fast-components/src/button/fixtures/button.html
- packages/web-components/fast-components/src/styles/patterns/button.ts
- packages/web-components/fast-element/docs/api-report.md
Several issues outlined in #3269 were making styling buttons and anchors difficult. While there still exists some complexity in styling padding / borders, this PR aims to reduce the styling edge-cases that arise from the implementation details of both fast-button and fast-anchor.
> fix: correct anchor and button stylesheets

- .github/workflows/cd-www-stage.yml
This updates to use the correct path on GitHub Actions for "CD -FAST".
This will fix the broken CD to deploy new www to stage.
> chore: update to correct path from www to static

- sites/fast-website/package.json
- sites/fast-website/src/app/components/card-section/card-section.styles.ts
- sites/fast-website/src/app/components/color-swatch/color-swatch.styles.ts
- sites/fast-website/src/app/components/color-swatch/color-swatch.template.ts
- sites/fast-website/src/app/components/color-swatch/color-swatch.ts
- sites/fast-website/src/app/components/content-placement-container/content-placement-container.styles.ts
- sites/fast-website/src/app/components/content-placement/content-placement.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
- sites/fast-website/src/app/components/feature-card/feature-card.styles.ts
- sites/fast-website/src/app/components/feature-card/feature-card.ts
- sites/fast-website/src/app/components/navigation/navigation.styles.ts
- sites/fast-website/src/app/components/section-header/section-header.styles.ts
- sites/fast-website/src/app/components/side-navigation/side-navigation.styles.ts
- sites/fast-website/src/public/index.html
- sites/website/docusaurus.config.js
- sites/website/package.json
- sites/website/src/docs/api/fast-foundation.api.json
- yarn.lock
> chore: fix broken ui in fast-website, various content fixes, update to use new color vars

- packages/web-components/fast-element/src/directives/binding.ts
Super quick fix to change the default event listener behavior to not capture (this was an oopsie on my part). I'll circle back around and add more tests to binding in general when some time opens up.
This is technically a breaking change.
> fix(fast-element): default event handler behavior should be no capture

- sites/fast-website/src/app/components/background-design/background-design.styles.ts
- sites/fast-website/src/app/components/background-design/background-design.template.ts
- sites/fast-website/src/app/components/background-design/background-design.ts
This change dims the background when the page is scrolled past the hero.
To aid visual accessibility, the background needs to provide better contrast when behind the page content.
> chore: update to dim bg when page scrolls beyond hero

- packages/web-components/fast-components-msft/src/styles/patterns/button.ts
- packages/web-components/fast-components/src/styles/patterns/button.ts
A bug in the website illustrated that buttons were able to get into a state where the internal control height could get out of sync with the WC height. This PR ensures the control height matches the root height.
> fix: ensure button control height matches wc root height

- sites/fast-website/src/app/components/content-placement-container/templates/feature.template.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.ts
- sites/fast-website/src/app/components/side-navigation/side-navigation.template.ts
- sites/fast-website/src/app/data/community.data.ts
While using screen readers like VoiceOver, Narrator, and NVDA, and tabbing onto anchors and buttons, that only have icons, the screen readers only read out 'link'. I went through and added aria-label on any anchors and buttons that only displays an icon.
When tabbing through the fast-frame component, while in full screen, I was unable to tab into the controls in the last column, because they were set to tabIndex="-1". I added an isResponsive observable that will toggle the tabIndex between the full and mobile size window.
Also set tabIndex="0" on the color swatch item.
Known issue that I will tackle separately as to not hold up these changes. They could be changes that have to be made within the components.
Running NVDA, the aria-label does not get read on the anchor and button …
> fix: screen reader for anchors and buttons and tab focus inside fast-frame component 

- sites/fast-website/src/app/css/style.css
- sites/fast-website/src/public/index.html
Constrain site-section-headers to 900px width at non-mobile breakpoint
> chore: constrain site-section-header in non-mobile width

- packages/web-components/fast-components-msft/src/tabs/fixtures/tabs.html
- packages/web-components/fast-components/src/tabs/fixtures/base.html
- packages/web-components/fast-foundation/src/tabs/tabs.ts
-Updated selectedTab to be the `event.currentTarget` to ensure the selected tab is always an existing tab so the activeid does not become undefined.
-Added fixture example to check for this
Solves the issue of any element except a text node or icon being passed to the tabs causes the tabs to switch to  the first tab even when selecting the other tabs.
Before:
After:
closes #3349 
> fix: selected tab becoming undefined when tab slot pass anything except icon or text node

- sites/fast-website/src/public/index.html
- sites/website/src/docs/api/fast-components-msft.api.json
- sites/website/src/docs/api/fast-components.api.json
- yarn.lock
Fixes documentation link in nav bar.
> fix: fixing link to documentation

- sites/fast-website/src/app/components/background-design/background-design.styles.ts
- sites/fast-website/src/app/components/background-design/background-design.ts
- sites/fast-website/src/app/components/side-navigation/side-navigation.ts
- sites/fast-website/src/app/css/style.css
- sites/fast-website/src/public/index.html
- sites/fast-website/webpack.prod.js
This commit resolves a console error on the homepage and addresses DOM ordering and stacking for fixed elements.
These issues were introduced with #3358 since the DOM is now loaded after the bundle.
> fix: wait to initialize homepage components with dom dependencies

- sites/fast-component-explorer/app/fast-components/configs/fast-text-field.ts
Update the example for text-field by adding a placeholder.
before
after
> fix: add a placeholder to the fast-text-field example in fast component explorer

- packages/web-components/fast-element/src/directives/binding.spec.ts
- packages/web-components/fast-element/src/observation/observable.spec.ts
- packages/web-components/fast-element/src/observation/observable.ts
Prevents the `BindingObserver` from notifying subscribers when it is disconnected.
Certain binding scenarios can cause a BindingObserver to register a change, but due to the async nature of batched updates, the observer may be disconnected before subscribers are notified (e.g. some conditional rendering scenarios). In this case, we do not want to notify the subscribers. Doing so can cause some error states as the subscribers may be bindings that are unbound and thus no longer have access to the source object to execute the lambda against. If that happens, null reference exceptions ensue.
The fix introduces a simple guard before notifying subscribers, based on already existing state in the BindingObserver. A test was added to verify the fix. I also made a few other improvements to binding …
> fix(fast-element): do not notify when binding observer is disconnected

- packages/web-components/fast-components-msft/src/slider/slider.styles.ts
- packages/web-components/fast-components/src/slider/slider.styles.ts
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/slider/slider.ts
* added touch related events for dragging the slider thumb on mobile devices
* issue fixed when the vertical slider was further down the page scrolling could cause the track min and max to be incorrect.
> fix: slider thumb does not respond to touch events, vertical sliders track parameters incorrect after scrolling page

- packages/tooling/fast-tooling-react/src/navigation-menu/navigation-menu-item.tsx
- packages/tooling/fast-tooling-react/src/navigation-menu/navigation-menu.spec.tsx
render `<button/>` instead of `<span/>` for navigation-menu-items when `onLocationUpdate` callback is included
Currently, navigation-menu-item children that include the `onLocationUpdate` callback can only be selected on a mouse click. The enter/space keys do not work. This change enables keyboard navigation to select these items.
For example, the [Components explorer](https://explore.fast.design/components/fast-accordion) navigation menu cannot be navigated by keyboard.
> fix: render buttons instead of spans for navigation-menu-item

- packages/web-components/fast-components-msft/docs/api-report.md
- packages/web-components/fast-components-msft/src/anchor/index.ts
- packages/web-components/fast-components-msft/src/button/index.ts
- packages/web-components/fast-components/src/anchor/index.ts
- packages/web-components/fast-components/src/button/index.ts
- packages/web-components/fast-components/temp/api-report.md
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/anchor/README.md
- packages/web-components/fast-foundation/src/anchor/anchor.template.ts
- packages/web-components/fast-foundation/src/anchor/anchor.ts
- packages/web-components/fast-foundation/src/button/README.md
- packages/web-components/fast-foundation/src/button/button.template.ts
- packages/web-components/fast-foundation/src/button/button.ts
Currently, the appearance attribute isn't a standardized attribute across all anchors and buttons. Even if the attribute existed, we don't see semantic alignment across what those appearances are. This change moves the appearance attribute into the implementation for a given design system - FAST and MSFT.
This opens up the ability to extend the foundation anchor or button without that additional attribute. For instance, if I have a navigation item with a fixed appearance, it's less-than-ideal to have an appearance attribute on that component where it's not needed.
For those using fast-foundation and leveraging the appearance attribute, this breaks and would require the addition of the appearance attr along with an `appearanceChanged` implementation to fix. …
> feat: move appearance attributes of anchor and button out of fast-foundation

- packages/tooling/fast-tooling-react/src/form/controls/control.linked-data.spec.tsx
- packages/tooling/fast-tooling-react/src/form/controls/control.linked-data.tsx
This change allows the autocompletion on the input of the linked data control in the `<Form />`.
Now, when `Tab` is pressed the value will autocomplete if there is a single matching item in the linked data list. If `Enter` is pressed the current value will be evaluated against lazily (lowercase values) or strictly (exact value) and if a single match can be found using either of these methods then the value will be added.
An example of where this helps:
Example 1: The list of supplied linked data includes:
```json
[
"Foo",
"foo"
]
```
When `"foo"` is typed, it will match `"Foo"` and `"foo"` in the dropdown, however if enter is pressed then it will match `"foo"` exactly and add this value.
Example 2: the list of supplied linked data includes:
```json
[
"foo-Bar",
"foo",
]
```
When …
> feat: allow the autocompletion of a linked data value

- packages/web-components/fast-components-msft/src/styles/patterns/button.ts
- packages/web-components/fast-components/src/styles/patterns/button.ts
Removed a duplicate `accentFillActiveBehavior.var` on the accent button's, active background value.
closes #3451 
> fix: the accent button will now show active color when clicked

- packages/web-components/fast-foundation/src/button/button.spec.md
Both button components delegate focus which does not match the spec.
The spec should match the implementation. I'm assuming that the component is the source of truth in this case.
> docs(fast-foundation): specify that fast-button delegates focus

- packages/web-components/fast-components/src/design-system-provider/index.ts
Type ramp values in `fast-design-system-provider` are hard coded rather than using values set in `fastDesignSystemDefaults`.
Fixes unexpected behavior of design system property values not changing when defaults are changed.
> fix: fast-components type ramp should use design system defaults

- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
Since all of these components in fast-frame are considered examples, to be consistent, they all prefixed with "Example"
Changed to read "dark mode" as that is more specific than "mode"
Notes:
- I would like to update the slider component to have something like an "aria-value-now-unit" attribute. To be able to have the screen reader also read out the type of unit, like pixels, inches, etc. Currently, as you change the numbers on the slider, for example, border-radius, visualizing "3 pixels" is better than "3".
- There is know bug that NVDA will not read out aria-label on host element components, like an anchor, button, and text field.
Fixes #3465 
> fix: add aria label to the components in fast frame section on the website

- packages/web-components/fast-element/src/styles.spec.ts
- packages/web-components/fast-element/src/styles.ts
This PR fixes issue #3476 which prevented `StyleElementStyles` from working properly against the `document` element in browsers without native support for `adoptedStyleSheets`.
Inside `fast-element` the `ElementStyles` base class abstracts away the particular style association implementation so that we can apply styles regardless of whether or not the browser supports `adopedStyleSheets`. Browsers like Firefox do not yet support this feature, so at runtime the `StyleElementStyles` concrete implementation is selected for use. With `adoptedStyleSheets` both `ShadowRoot` and `document` support the feature, so styles can easily be added globally or to the shadow root. However, `HTMLStyleElement` instances cannot be added as a child node of `document` as a work around, because `document` can …
> fix(fast-element): style element styles should work with the document

- packages/web-components/fast-components-msft/docs/api-report.md
- packages/web-components/fast-components/src/anchor/index.ts
- packages/web-components/fast-components/src/button/index.ts
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/button/button.ts
- packages/web-components/fast-foundation/src/checkbox/checkbox.ts
- packages/web-components/fast-foundation/src/radio/radio.ts
- packages/web-components/fast-foundation/src/slider/slider.ts
- packages/web-components/fast-foundation/src/switch/switch.ts
- packages/web-components/fast-foundation/src/text-field/text-field.ts
This PR fixes an issue where attributes were defined too early for the custom element, specifically as it relates to form associated elements. This work moves the work to set proxy attributes to the connected callback.
Closes #3456 
> fix: move setAttribute calls for proxy elements to connectedCallback

- packages/web-components/fast-components-msft/src/slider-label/slider-label.styles.ts
- packages/web-components/fast-components/src/slider-label/slider-label.styles.ts
- packages/web-components/fast-foundation/src/radio-group/radio-group.template.ts
- packages/web-components/fast-foundation/src/slider-label/slider-label.template.ts
- packages/web-components/fast-foundation/src/tree-item/tree-item.template.ts
Some &nbsp; entries got accidentally injected into the slider label and radio group templates causing styling issues, removing them from the templates.
> fix: removing un-needed nbsp; in slider-label and radio-group templates

- packages/web-components/fast-components/src/radio-group/fixtures/base.html
Replaced `${neutralForegroundRestBehavior.var}` with `--var(neutral-foreground-rest)` on the label's color style.
It looks like this was only happening in the `radio-group` fixture file, in fast-components.
Fixes #3505 
> fix: replaced template literal with reference to --var on label color style in radio group

- packages/web-components/fast-components/src/menu/fixtures/menu.html
- packages/web-components/fast-foundation/src/menu-item/menu-item.ts
Adding a basic checked state toggling to radio and checkbox type menu items.  Currently both have the same behavior but radio type items are expected to have radio group capabilities added at a later date.
https://github.com/microsoft/fast/issues/3481
> feat: basic menu item check state toggling

- packages/web-components/fast-components-msft/docs/api-report.md
- packages/web-components/fast-components-msft/src/design-system-provider/index.ts
- packages/web-components/fast-components-msft/src/styles/behaviors.ts
- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/design-system-provider/index.ts
- packages/web-components/fast-components/src/fast-design-system.ts
- packages/web-components/fast-components/src/index.ts
- packages/web-components/fast-components/src/styles/direction.ts
- packages/web-components/fast-components/src/styles/index.ts
- packages/web-components/fast-components/temp/api-report.md
This change adds a `direction` property to the design systems for FAST and MSFT to track the primary document direction. It also adds two behaviors to resolve CSS custom properties to direction-based values based on the design-systems direction. Ideally this wouldn't be necessary, but there are still significant gaps in browser support for https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties.
Related to #3246. This addresses most of the issues in that thread but does not add the behavior to conditionally apply `ComposableStyles` based on direction. That piece is not blocking so taking as a follow-up.
> feat: adds direction property to design system

- packages/web-components/fast-components-msft/src/tree-item/fixtures/tree-item.html
- packages/web-components/fast-components-msft/src/tree-item/tree-item.styles.ts
- packages/web-components/fast-components-msft/src/tree-view/fixtures/tree-view.html
- packages/web-components/fast-components/src/tree-item/tree-item.styles.ts
- packages/web-components/fast-components/src/tree-view/fixtures/tree-view.html
- packages/web-components/fast-components/temp/api-report.md
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/tree-item/README.md
- packages/web-components/fast-foundation/src/tree-item/tree-item.template.ts
- packages/web-components/fast-foundation/src/tree-item/tree-item.ts
- packages/web-components/fast-foundation/src/tree-view/README.md
- packages/web-components/fast-foundation/src/tree-view/tree-view.template.ts
- packages/web-components/fast-foundation/src/tree-view/tree-view.ts
Tree items at the root level were not styled correctly if they did not have children, indentation was incorrect. Also this fix allow developers to add arbitrary elements into the tree view structure.
closes #3516
> fix: address nested styling issues and provide a more intuitive API for nesting

- packages/web-components/fast-components-msft/src/tree-view/fixtures/tree-view.html
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/tree-item/tree-item.ts
- packages/web-components/fast-foundation/src/tree-view/tree-view.ts
This PR makes a couple of small updates to the tree view and tree item components based on feedback provided after merging #3528.
> fix: update nested to be observable and set isNestedItem method to readonly

- packages/web-components/fast-element/docs/guide/defining-elements.md
Fix a minor typo "filed->field" in defining-elements.md
Fix a small typo "filed->field" in defining-elements.md
https://fast.design/docs/fast-element/defining-elements
> docs: correct minor typo

- packages/web-components/fast-components/src/slider/slider.stories.ts
name collision where slider-label story is affected by addon channel listener in slider story causing slider-label story to crash
> fix: fixed error in slider story causing issue in slider-label story

- packages/web-components/fast-components/src/card/card.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.ts
Updated fast-card to use a relative color recipe.
Updated the fast.design site component sampler to better respond to changes of the neutral color and light or dark mode,
A card has two applicable color recipes for it's background color, but the most flexible one is `neutralFillCardRest` because it will adjust the card background for whatever container it's in. `neutralLayerCard` is a fixed value intended for an optimized and backwards compatible case over `neutralLayerCardContainer` only. This was causing the fast.design component sampler to not reflect the color change correctly.
Further, the sampler is updated to adjust both the layer luminance and the neutral color used for the background. The latter shows off more of the color handling with the addition of non-grey swatches. The …
> fix: update fast-card and component sampler color handling

- packages/web-components/fast-components/src/button/fixtures/button.html
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/button/button.spec.ts
- packages/web-components/fast-foundation/src/button/button.ts
- packages/web-components/fast-foundation/src/form-associated/form-associated.ts
#3534 describes an issue where a `FASTButton[type=submit]` does not actually submit the parent form. In fixing this, I also noticed that a `FASTButton[type=reset]` does not reset the form. This introduces a fix to both behaviors.
A `FASTButton[type=reset]` will simply invoke the `reset()` method of the associated form element when clicked.
Submission behavior is a bit more complicated. The `FASTButton[type=submit]` will *try* to use the `requestSubmit()` method of the form if it exists, supplying the method with the button's proxy element as the submitting element (see #3534) for more info. If the `requestSubmit()` method is unavailable (Safari) then the proxy's `click()` method will be invoked.
closes #3534
**Adding or modifying component(s) in …
> fix: add form submission and reset behavior to Button

- packages/web-components/fast-components/src/tree-item/tree-item.styles.ts
- sites/fast-component-explorer/app/preview.tsx
* Use the design system direction behavior to allow for rtl sensitive css
* Update component explorer to set the direction when updated in the design system provider
closes #3546
> fix: use design system direction support for glyph in treeview

- specs/breadcrumb.md
The file has specs for `fast-breadcrumb` and `fast-breadcrumb-item`
> docs(spec): add breadcrumb spec

- packages/web-components/fast-components/src/slider/slider.styles.ts
As explained on #3634, the min-width default value (design-unit * 60px) is not a number that give enough flexibility for a default instance of the slider, preventing us to change the width from 100% to 0% unless override the default of min-width
#3634 Is the cause of this pull request, and as discussed on Discord the value is being changed to `design-unit * 1px`, but I would like to have more discussion around it.
While doing the change I have discovered the same issue will happen with a `fast-slider` in a vertical mode, and I believe the fix here will not be as simple as setting it to `design-unit * 1px` because doing that the slider will normally appear with a height of `4px` in case of fast design system provider, on Firefox when you don't have set the height manually it appears as …
> fix: update min-width of fast-slider to design-unit * 1px

- packages/web-components/fast-components/src/radio/radio.styles.ts
This PR corrects the visual design of the FAST radios.
Somewhere between v2 and v3 of the homepage design specs, the corner radius for the radio buttons shifted to align with checkboxes. From a visual design standpoint, this is incorrect. Further, from an accessibility standpoint, this is even more problematic. The controls appear to the be same and have no distinct difference; this PR corrects the radios to be circular at all times solving both the visual design problem and the accessibility issue presented by this appearing the same as a checkbox.
> fix: correct radio corner radius value

- packages/web-components/fast-foundation/docs/integrations/blazor.md
The previous link would cause a compilation error as it would interpret the '@' as a binding.
This occurs in the example script link in the getting started documentation for Blazor integration
- [X ] **Chore**: A change that does not impact distributed packages.
> chore: add @@ to escape blazor binding in doc cdn link

- packages/tooling/fast-tooling/src/schemas/web-component.schema.ts
- packages/web-components/fast-components/src/__test__/README.md
- packages/web-components/fast-components/src/__test__/component.schema.json
This change adds the Open UI JSON schema definition with a link to the original JSON schema.
This provides the JSON schema to test against Open UI definitions for FAST components as they are created. Adding a testing mechanism will come later leveraging the `ajv` library.
> chore: add Open UI schema to use as testing against FAST component definitions

- .github/workflows/ci-daily.yml
- .github/workflows/ci-weekly.yml
- packages/tooling/fast-tooling-wasm/package.json
- packages/tooling/fast-tooling-wasm/permutator/__tests__/test.c
- packages/tooling/fast-tooling-wasm/permutator/build.js
- packages/tooling/fast-tooling-wasm/permutator/permutate_number.c
- packages/tooling/fast-tooling-wasm/permutator/type.c
Adds checks for minimum and maximum to set the random numbers generated with a range of 100. Adds a check if the minimum is greater than maximum (which should fail validation checks regardless) a number is returned. Adds unit testing for the number type.
Resolves #3565
> fix: add checks for minimum and maximum out of bounds and add tests for the number type

- packages/web-components/fast-components/src/radio/radio.styles.ts
I noticed while working on the homepage that the fast-radios can get into a scenario where they are shrinking. In scenarios where space is limited, we should ensure that the radio itself does not shrink. 
> fix: ensure radios do not shrink

- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
This PR fixes an issue where the example radios were not wrapped in a radiogroup and resulted in inaccessable behavior.
closes #3676 
> chore: example radios on website should be wrapped in a radiogroup

- packages/web-components/fast-components/src/styles/patterns/button.ts
Closes: #3667 
when `fast-anchor` `appearance` is set to `hypertext` the underline can render larger than the the text. Changing display from `inline-flex`  to `inline-block` fixes the issue and does not appear to negatively impact any other appearance with or without end and start slots.
Before:
After:
After for other appearances and layouts (Anchor and Button):
Anchor
Button
> fix: anchor (hypertext) line can render outside

- packages/web-components/fast-foundation/src/text-field/text-field.ts
Autofocus seems to work but in the context of other wrapping frameworks it might be happening too soon.
potentially closes #3685 
> fix: wrapping set focus in dom.queueupdate

- packages/web-components/fast-components/src/anchor/fixtures/anchor.html
- packages/web-components/fast-components/src/styles/patterns/button.ts
- reset `min-width` on hyperlink anchors and buttons
- restore `display: inline-flex` on anchors and buttons
The switch from `inline-flex` to `inline-block` in #3674 caused elements on the homepage to become misaligned. 
> fix: hypertext and lightweight display and min-width styles

- packages/web-components/fast-components/src/styles/patterns/button.ts
Fix the high contrast color on the underline of the anchor component when hovered.
before
after
> fix: anchor underline high contrast color is set to LinkText

- packages/web-components/fast-foundation/src/tabs/tabs.ts
see the issue for details
Change the way we select the active tab when using home or end touch on a keyboard. I use the same mechanism than when using left and right touch. It make animation smoother than directly set where the active tab should be.
Before :
After :
see the issue for details : https://github.com/microsoft/fast/issues/3692
> fix: correct tabs animation when using home/end touch

- CODE_OF_CONDUCT.md
- README.md
- build/testing/sauce-labs/test-browsers.js
- packages/web-components/README.md
- packages/web-components/fast-components/README.md
- packages/web-components/fast-element/README.md
- packages/web-components/fast-foundation/README.md
- sites/fast-website/src/public/index.ejs
- sites/site-utilities/statics/server/server.js
- sites/website/src/docs/community/writing-documentation.md
`X-XSS-Protection` to be removed as it provides a false sense of security and WebScout requires it to be removed.  Additionally, `http` references were found inside code.  We should **never** link to `HTTP`.  Always, reference the `HTTPS`.
WebScout discovered another batch of updates to make.
> chore: update security for xss and http 

- packages/web-components/fast-element/src/dom.ts
This PR improves our `trustedTypes` polyfill so that it does not rely on `globalThis`, which itself may not be implemented in all environments.
Closes #3783 
Some folks are trying to use `fast-element` in browsers that do not implement `globalThis`. Instead of increasing our library or the app developer's code by requiring a polyfill for `globalThis`, this PR removes the need for `globalThis` altogether. It was possible do this since `globalThis` was only used in one place and that usage was easy to re-work without `globalThis`.
> feat(fast-element): improve trustedTypes polyfill to not use globalThis

- packages/web-components/fast-components/src/slider/fixtures/base.html
- packages/web-components/fast-components/src/slider/slider.styles.ts
- packages/web-components/fast-foundation/src/slider/README.md
- packages/web-components/fast-foundation/src/slider/slider.spec.md
- packages/web-components/fast-foundation/src/slider/slider.template.ts
- yarn.lock
We now have a default height, --fast-slider-height,  of (--thumb-size * 10px), which should translate to 160px for our design defaults. There is also a min-height based on --thumb-size
Some rationale behind this decision, height:100% works different than width:100% in that if you don't have anything specifying an actual height then height:100% does nothing, whereas width:100% will have the control span all the width available. Because pages are intended to scroll vertically, the height is arbitrary
but pages are intended to span the full width. So that the slider doesn't appear broken at first we want to specify a default height that can easily be overridden by inline style.
closes #3644
**Adding or modifying component(s) in `@microsoft/fast-components` …
> fix: consistent with min-width, min-height is at least the thumb size

- packages/web-components/fast-element/src/__test__/helpers.ts
- packages/web-components/fast-element/src/template-compiler.spec.ts
- packages/web-components/fast-element/src/template-compiler.ts
The template compiler was overzealous in removing comments from a template. As a result, this caused the compiled template directive targeting to get out of sync with the tree walker results when HTML comments were present in the template. This PR simply removes the completely unnecessary code that was removing comments. If a developer wants to put comments in their code, we shouldn't mess with it anyway.
Closes #3777
> fix(fast-element): do not remove developer comments when compiling templates

- sites/fast-color-explorer/app/control-pane.tsx
Add `sketch-picker .flexbox-fix span` style selector to fix the label color on the sketch picker input. This resolves the color-contrast fail from the Accessibility Insight results,
https://webcompliance.trafficmanager.net/ScanResultsApi/GetAccessibilityScanReport?siteId=3b40f9fe-a96d-4751-25f1-08d7e21203a9&urlId=242795
before
after
> fix: label on sketch picker input is using the correct color

- packages/web-components/fast-element/src/dom.ts
During our release testing, we discovered that everything was completely broken in Firefox 🤣 What was the cause? Well, we recently removed our dependency on the `globalThis` standard as part of our `trustedTypes` polyfill. Unfortunately, Firefox did not like the way our polyfill attempted to patch the global object (without using `globalThis`). As a result, I have reverted our `trustedTypes` feature test and polyfll to be based on `globalThis` and have added a polyfill for `globalThis`.
At some point in the future, we'll be able to remove both of these polyfills, but we should probably have them baked in for now, since they are fairly small and prevent our customers from having to find and add implementations themselves.
> fix(fast-element): add globalThis polyfill to fix trustedTypes polyfill

- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
Fixes style bugs on the homepage for the `.content-badge` and the Fast Frame `<fast-switch>`.
The `fast-switch` element requires `use-defaults` to display properly, and the new `.content-badge` shouldn't have padding.
> fix: badge padding and fast-switch defaults on homepage fast-frame

- packages/web-components/fast-components/src/styles/recipes.ts
- packages/web-components/fast-components/src/styles/size.ts
- packages/web-components/fast-components/src/tree-item/tree-item.styles.ts
Adding hover style to the expand collapse button in tree items
The purpose of the background is to increase comprehension of the two different interactive elements within an item. We received interaction study indication that people had trouble understanding the difference between selecting a node and expanding it. The button area functions differently, but doesn't indicate such, so this change is to frame it to help differentiate the parts.
> feat: add hover state for expand collapse button in tree-item

- packages/web-components/fast-components/src/accordion/accordion-item/accordion-item.styles.ts
- packages/web-components/fast-components/src/styles/patterns/button.ts
adds font-family: inherit to the `.control` for fast-accordion-item and fast-button
Fixes #3827 
> fix: add font-family inherit to controls for button and accordion item

- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
Update to center the indicator by setting top and left to 50% and shifting it up and left by half of its own width and height, because the indicator is off by a pixel.
closes #3796 
before
after
> fix: center the indeterminate indicator inside the checkbox

- packages/web-components/fast-components/src/tree-item/tree-item.styles.ts
Mirror the arrow glyph for rtl mode on the tree-item using direction behavior in css
closes #3800 
> fix: mirror the arrow glyph of tree-item for rtl resting and expanded

- packages/web-components/fast-components/src/slider/fixtures/base.html
- packages/web-components/fast-components/src/slider/slider.styles.ts
There was a margin-left being set to align the track properly in vertical mode, but that wasn't correct in RTL. Modified css to utilize use margin-inline-start which adjusts in rtl mode appropriately.
closes #3818 
> fix: use margin-inline-start to fix mis-aligned thumb on slider in rtl and vertical orientation

- packages/web-components/fast-element/src/template-compiler.spec.ts
- packages/web-components/fast-element/src/template-compiler.ts
This PR adds one line of code to ensure all compiled template content is "adopted" into the main document. This prevents a particular bug in adoptedStyleSheets that causes the style sheets to be removed if the content is shifted in and out of the document and its original document fragment.
Fixes #3670
> fix(fast-element): workaround for adoptedStyleSheets Chromium bug

- packages/tooling/fast-tooling/src/data-utilities/monaco.spec.md
This changes the baseline interpretation of data to use the string or string array values that are set by Monaco and leverage their HTML parser to get a data structure that can be converted into the `DataDictionary`. This should be a cleaner method of implementation as there does not need to be an intermediary Token data structure. Some optimizations may need to be considered and this spec expanded on once the basic functionality is in.
> chore: update the monaco utility spec to use the monaco value as a baseline

- sites/website/src/docs/design-systems/fast-frame.md
- sites/website/src/docs/design-systems/overview.md
it's => its, themeing => theming
> chore: typo in docs

- packages/web-components/fast-element/docs/api-report.md
- packages/web-components/fast-element/src/dom.ts
- packages/web-components/fast-element/src/index.ts
- packages/web-components/fast-element/src/platform.ts
Third time is the charm! Apparently my `globalThis` polyfill did not work on old versions of Safari and iOS. So, this PR introduces a `$global` export based on some code I've been using for a long time. Hopefully this concludes the saga.
Fixes #3862 
It's possible this could be considered a breaking change since we are no longer polyfilling `globalThis` but have replaced it with our own export `$global` which we use internally.
> fix(fast-element): better global support for older browsers

- packages/web-components/fast-components/src/design-system-provider/index.ts
I see no reason for density to be type `0`
> fix: density type is a number

- packages/web-components/fast-foundation/src/tree-view/tree-view.template.ts
When tabbing out of the `tree-view` component, you can now tab back into it. What was happening, is the `tabindex` for `tree-view` was not being set to `0` when tabbing out of the `tree-view`
closes #3801 
> fix: able to keyboard tab back in the tree view

- packages/web-components/fast-element/docs/api-report.md
- packages/web-components/fast-element/docs/guide/leveraging-css.md
- packages/web-components/fast-element/src/fast-definitions.spec.ts
- packages/web-components/fast-element/src/fast-definitions.ts
- packages/web-components/fast-element/src/index.ts
- packages/web-components/fast-element/src/styles.spec.ts
- packages/web-components/fast-element/src/styles.ts
This PR enables the `PartialFASTElementDefinition` used by the `@customElement` decorator and `FASTElementDefinition` class to receive an array of `ComposableStyle` instances in addition to the previously supported single instance. Additionally, `ElementStyles.create` has been exposed as an imperative mechanism for creating `ElementStyles` instances and is now used internally by the `FASTElementDefinition` and `css` helper.
Closes #3868
> feat(fast-element): enable custom element to accept a styles array

- packages/web-components/fast-foundation/src/radio/radio.ts
If a radio button has been checked, clicking it again with the mouse should not toggle it to unchecked.
closes #3887 
Looking at the behavior on
https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html
and
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio
> fix: radio button should not be unselected with mouse click

- packages/web-components/fast-components/src/switch/fixtures/base.html
- packages/web-components/fast-components/src/switch/switch.styles.ts
When hovering over any part of switch the cursor should be the disabled cursor if the control is readonly or disabled and pointer otherwise
closes #3893 
Style changes only, and added test of readonly in the fixture
> fix: cursor should be disabledCursor when switch is readonly or disabled, otherwise pointer

- packages/web-components/fast-components/src/anchored-region/anchored-region.stories.ts
- packages/web-components/fast-components/src/anchored-region/fixtures/base.html
- packages/web-components/fast-foundation/src/anchored-region/anchored-region.spec.md
- packages/web-components/fast-foundation/src/anchored-region/anchored-region.ts
The current version of anchored region falls back to call to expensive getBoundingClientRect calls in circumstances when the provided viewport/anchor pair doesn't "work" with intersection observer as can happen with intervening "position: fixed" elements in the dom hierarchy.  I recently discovered that intersection observer seems to always work at returning an initial event with valid entries for any element when the viewport is null, so I modified anchored region to take advantage of that for reliability and performance.
The cost of this change is that anchored region no longer attempts to watch for intersection events to update its position, but instead with only update itself when prompted by a call to its "update()" function, when an attribute or property is changed, or when the …
> feat:  Anchored region reliability/perf improvements

- packages/web-components/fast-foundation/src/tree-item/tree-item.ts
* fixed a bug where hitting right arrow key on leaf node would mess up the next left arrow keydown
* right arrow key expands a node if not expanded, or moves to first child, or does nothing
closes #3886 
Expected keyboarding behavior for arrow keys and an example in action
https://w3c.github.io/aria-practices/#TreeView
https://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2a.html
> fix: tree-view right and left arrow keyboarding should behave as wai-aria spec suggests

- packages/web-components/fast-foundation/src/badge/badge.template.ts
- packages/web-components/fast-foundation/src/badge/badge.ts
The badge component had odd behavior when passing inline styles and there was a scenario you could end up in where nothing would be applied if fill was not passed. This change creates a function to ensure attributes are handled correctly here.
> fix: ensure badge always applies inline-style when attributes exist

- packages/web-components/fast-foundation/src/dialog/dialog.ts
Ran into this while trying to hide the Dialog component in order to apply some CSS transitions, where it would still trap focus when hidden. The related issue is closed and the project tests pass after making the change (and my hidden dialogues no longer trap the focus).
Changes the dialog component, but doesn't change any part of the public interface.
> fix: remove placeholder functions for boolean attributes in dialog component

- packages/tooling/fast-tooling/src/data-utilities/mapping.vscode-html-languageservice.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/mapping.vscode-html-languageservice.ts
Changes the parser to attempt to parse an attribute as a string, when it is null (no value but present) it is considered `true`, and when an incomplete attribute is passed it is treated as an empty string.
An example of this:
```html
<input required />
```
Although `required` is considered `true`, the value from `vscode-html-languageservice` is `null`.
Additionally, an error will throw while typing in the Monaco editor because when "=" is passed after an attribute it will evaluate to a non-parsable string. This will be overcome by simply passing an empty string back when the value cannot be parsed.
> fix: allow null attributes when mapping from Monaco editor values to be treated as booleans

- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/checkbox/checkbox.spec.ts
- packages/web-components/fast-foundation/src/checkbox/checkbox.ts
- packages/web-components/fast-foundation/src/form-associated/form-associated.ts
- packages/web-components/fast-foundation/src/radio/radio.spec.ts
- packages/web-components/fast-foundation/src/radio/radio.ts
- packages/web-components/fast-foundation/src/slider/slider.ts
- packages/web-components/fast-foundation/src/switch/switch.spec.ts
- packages/web-components/fast-foundation/src/switch/switch.ts
- packages/web-components/fast-foundation/src/text-field/text-field.spec.ts
- packages/web-components/fast-foundation/src/text-field/text-field.ts
This change adds a mechanism to `FormAssociated` to set field validity after constraint property changes, including `value` and `required`. By default, this new `validate()` method sets validity to the validity of the *proxy* element, using the validationMessage of the proxy. This behavior can be overridden or extended for an implementing element.
closes #3761
> fix: adds constraint validation to all form-associated elements

- packages/web-components/fast-element/docs/api-report.md
- packages/web-components/fast-element/docs/guide/using-directives.md
- packages/web-components/fast-element/src/directives/children.spec.ts
- packages/web-components/fast-element/src/directives/children.ts
- packages/web-components/fast-element/src/directives/node-observation.ts
- packages/web-components/fast-element/src/directives/slotted.ts
- packages/web-components/fast-element/src/index.ts
Fixes #3883 where `subtree` observation when using the `children` directive did not capture all relevant nodes.
While working with @eljefe223 on the new `fast-select` component, we discovered that the `children` decorator was not able to properly capture subtree descendants even when configured to do so. This PR fixes that issue by applying a selector to "all" children in the subtree case, fixing the incorrect assumption that nodes would always be direct children of the directive's target.
There were some modifications to interfaces to account for different configuration options but I don't think this will practically affect anyone.
> fix(fast-element): enable subtree observation in the children decorator
