- specs/divider.md
> chore: add divider spec

- packages/fast-components/src/badge/badge.stories.ts
- packages/fast-components/src/badge/badge.styles.ts
- packages/fast-components/src/badge/badge.template.ts
- packages/fast-components/src/badge/badge.ts
- packages/fast-components/src/badge/fixtures/base.html
- packages/fast-components/src/badge/index.ts
- packages/fast-components/src/index.ts
Adds `fast-badge` as a web component.
> feat: add badge web component

- packages/fast-components/src/divider/divider.stories.ts
- packages/fast-components/src/divider/divider.styles.ts
- packages/fast-components/src/divider/divider.template.ts
- packages/fast-components/src/divider/divider.ts
- packages/fast-components/src/divider/fixtures/divider.html
- packages/fast-components/src/divider/index.ts
This PR adds Divider as a web component.
This is a DRAFT PR which is based on #2863 and depends on that PR being accepted and merged.
> feat: add divider as web component

- packages/fast-tooling-react/README.md
- packages/fast-tooling-react/app/pages/viewer/content.tsx
- packages/fast-tooling-react/app/pages/viewer/index.tsx
- packages/fast-tooling/README.md
This adds missing documentation for:
- The validation and `AjvMapper`
- The custom messages
It also adds an example in the `@microsoft/fast-tooling-react` app for using custom messages through the `<Viewer />` component.
> chore: add documentation for custom messages and validation as well as an example in the viewer portion of the test app

- packages/fast-components/src/divider/divider.template.ts
Now that a fix has been committed with #2876, this PR updates the divider web component to remove a subtle space in the template. Marking this as a chore since its not necessarily required as a fix for any distribution.
> chore: fix divider template to remove unnecessary space

- packages/fast-tooling-react/package.json
- packages/fast-tooling/package.json
This manually bumps the `@microsoft/fast-tooling` and `@microsoft/fast-tooling-react`. This is the final alpha release bump before a series of integration tests that will be performed. The official release of v2.0.0 on `@microsoft/fast-tooling-react` is pegged to the week of April 6th and should  unblock #2859.
> chore: manually bump fast-tooling and fast-tooling-react

- packages/fast-components/src/index.ts
A couple of components and our style utilities were not being exported. This PR exports those.
> fix: export missing components and styles

- packages/fast-tooling-react/src/data-utilities/mapping.spec.tsx
- packages/fast-tooling-react/src/data-utilities/mapping.tsx
Data was not being mapped correctly in the reactMapper utility, this maps them properly to the React component.
> fix: update mappings so that the reactMapper maps props properly

- packages/fast-tooling-react/package.json
This is an alpha package bump for the repository, the package version has already been released at this version.
> chore: package bump to 2.0.0-alpha.4

- packages/fast-tooling-react/package.json
- packages/fast-tooling/package.json
This updates the package.json file for `@microsoft/fast-tooling` and `@microsoft/fast-tooling-react` to be more descriptive of their contents.
> chore: update the package.json descriptions

- packages/fast-tooling/src/data-utilities/ajv-validation.spec.ts
- packages/fast-tooling/src/message-system/message-system.utilities.props.ts
- packages/fast-tooling/src/message-system/message-system.utilities.spec.ts
- packages/fast-tooling/src/message-system/message-system.utilities.ts
Adds the list of ids that have been created from the linked data.
There was no feedback before on an outgoing message that linked data was added to see what the new linked data ids were, this resolves that so the message contains that information.
> feat: add all of the ids associated with the linked data when linked data has been added

- packages/fast-components/src/badge/fixtures/base.html
Removes extra closing tag in base.html
> chore: remove extra closing tag in badge examples

- packages/fast-components/src/checkbox/checkbox.styles.ts
- packages/fast-components/src/checkbox/checkbox.template.ts
Aligns the class name and part name with other input controls.
Checkbox used the class and part name "checkbox" to expose styling hooks for the element representing the input itself. Other controls in the package use the name "control" for this purpose. This PR aligns checkbox with these other controls.
> fix: align checkbox class and part name to align with other controls

- packages/fast-eslint-rules/README.md
> chore: fix eslint readme mistake

- specs/README.md
- specs/tooltip.md
This PR proposes adding a new spec for `tooltip`. This work is dependent upon the anchored region.
> chore: add tooltip spec

- packages/react/fast-storybook-presets/package.json
- packages/react/fast-storybook-presets/src/index.ts
- packages/react/fast-storybook-presets/src/setup.tsx
- yarn.lock
This PR adds a performance add-on package to storybook which allows for creating performance benchmarks and testing. The default settings for the package provide basic perf functionality. Additional functionality and component/story specific tests are also supported: https://github.com/atlassian-labs/storybook-addon-performance#usage-interactions
> feat: add performance benchmark package to fast-storybook-presets

- .github/workflows/cd-explore-stage.yml
This PR fixes a pathing issue related to broken workflows.
> chore: fix explore site pathing issue for github actions workflow

- .github/workflows/ci-daily.yml
This PR adds caching for yarn dependencies to improve build times when possible.
> chore: add dependency caching for yarn with github actions

- packages/web-components/fast-components/.npmignore
- packages/web-components/fast-element/.npmignore
> chore: ensure npmignore files include config files

- packages/web-components/fast-components/src/checkbox/checkbox.spec.md
- packages/web-components/fast-components/src/radio/radio.md
> chore: add radio spec

- packages/web-components/fast-components/src/styles/patterns/button.ts
The majority of the changes are to fix the disabled state to render it correctly. Setting the opacity and adding disabled cursor. Each button was also given individual overrides to make sure the disabled state looked correct.
Accent button was updated to have its background set to Highlight on rest. Also added double border when focused.
before
after
> fix: high contrast colors on button web components

- packages/web-components/fast-element/src/observation/observable.ts
Removes an `if` condition that can never be `true`. This also removes circular references between high and low level parts of the system.
See issue #2965.
This is not a breaking change.
> fix(fast-element): remove unnecessary references

- packages/web-components/fast-components/src/index.ts
This fixes an issue where anchored region is not being exported from the package. Currently treating as a chore since we have not published since this went in and there is no reason to additionally bump the package with a patch.
> chore: export anchored region

- packages/web-components/fast-components/src/anchored-region/anchored-region.ts
> fix: make anchorElement observable and check for detectors before disconnect

- packages/react/fast-jss-manager-react/src/jss-manager.spec.tsx
- yarn.lock
This will remove the unused `const` while maintaining the unit test in order to remove warnings output to the console.
During unit testing I noticed warnings and it's best practice to fix warning prior to checkin anything into master.
> chore: remove unused constants outputting warnings during unit testing

- packages/web-components/fast-components/src/index.ts
Temporarily removes the anchored-region from package exports. Component will be exported when known issues are resolved.
Exposing this with current issues is currently blocking publishing of other packages. Removing this form exports is not a breaking change since this has not been published yet, and removing it will unblock publishing of other packages.
> chore: remove export of anchored-region

- specs/README.md
This PR creates a table to better organize the spec root readme and provide insight into which components exist and which components have specs but are still outstanding.
> chore: add table to spec readme to help illustrate component coverage and roadmap

- specs/README.md
- specs/tabs/tabs.md
> chore: add tabs web component spec

- specs/README.md
I had some quick feedback from a few contributors who suggested it might be beneficial to include some additional information. The spec table has now been updated to illustrate:
- components on our roadmap which do not have specs
- components on our roadmap which do have specs but have not been built
- components which have a spec and have been built
This should help provide additional insight and awareness to the community as well as to those who may want to contribute specs and components.
> chore: add spec details and future roadmap components to the web component spec table

- specs/README.md
Fixed the path for the link from the spec README.md
> chore: fixed tabs spec link

- packages/web-components/fast-element/src/template.ts
Adds a `render` method to `ViewTemplate` which takes a data source (to bind to) and an element or element id to render the template into.
I realized that our templating engine isn't dependent on the browser supporting web components and can be used independently to render with a little bit of boilerplate code. Other teams have expressed interest in this capability esp. since it would allow them an upgrade path from IE11 to Edge by starting with basic templates and then moving to web components, all based on the same library. So, I added a simple method to enable pure templating that gets rid of the boilerplate code.
```TypeScript
export class GreetingViewModel {
@observable name: string = 'World';
}
const template = html<GreetingViewModel>`
<h1>Hello ${x => x.name}!</h1>
`;
const vm = new …
```
> feat(fast-element): add a render method to templates for pure templating

- packages/react/fast-components-foundation-react/package.json
- packages/react/fast-components-react-base/package.json
- packages/react/fast-components-react-msft/package.json
- packages/react/fast-components-styles-msft/package.json
- packages/react/fast-jss-manager-react/package.json
- packages/react/fast-jss-utilities/package.json
- packages/react/fast-layouts-react/package.json
- packages/react/fast-react-utilities/package.json
- packages/tooling/fast-tooling-react/package.json
- packages/utilities/fast-animation/package.json
- packages/utilities/fast-colors/package.json
- packages/utilities/fast-web-utilities/package.json
Adds 'text' to the jest `coverageReporters` in the package JSON.
When running jest unit tests there was an issue where the table from `istanbul` was not being displayed, this is fixed by adding 'text' to the array of `coverageReporters`.
> chore: add 'text' to jest coverageReporters

- package.json
- sites/site-utilities/.eslintignore
- sites/site-utilities/.eslintrc.js
- sites/site-utilities/.npmrc
- sites/site-utilities/.prettierignore
- sites/site-utilities/README.md
- sites/site-utilities/babel.config.js
- sites/site-utilities/package.json
- sites/site-utilities/src/index.ts
- sites/site-utilities/src/react/index.ts
- sites/site-utilities/src/react/tooling-dictionaries.ts
- sites/site-utilities/tsconfig.json
Adds a private package that will serve as a way to consolidate logic between the Creator and Component Explorer sites.
This logic could not be added in the `@microsoft/fast-components-react-msft` package as that would cause a dependency on tooling packages which could result in a circular dependency.
> chore: add a site utilities private package to consolidate logic between the Creator and Component Explorer sites

- packages/web-components/fast-components/.storybook/main.js
- packages/web-components/fast-components/package.json
- packages/web-components/fast-components/src/design-system-consumer/design-system-consumer.ts
- packages/web-components/fast-components/src/design-system-provider/design-system-provider.ts
- packages/web-components/fast-components/src/design-system-provider/is-design-system-provider.ts
- packages/web-components/fast-components/src/slider/index.ts
- packages/web-components/fast-components/src/slider/slider.ts
- packages/web-components/fast-element/src/controller.ts
- packages/web-components/fast-element/src/fast-definitions.ts
- packages/web-components/fast-element/src/fast-element.ts
- yarn.lock
Circular dependencies can cause runtime errors in webpack builds. This change resolves all circular dependencies and introduces a webpack plugin to detect circular dependencies in the `@microsoft/fast-components` storybook app that will warn in debug and throw during tests - this should prevent further circular dependencies from making it into the package.
> fix: removes circular dependencies from web-component packages

- packages/web-components/fast-element/src/index.ts
https://github.com/microsoft/fast-dna/pull/3037 moved some exports around which resulted in some externally exported entities being removed from the root export. This change exports them from the main file.
> fix: add exports that were removed during circular reference refactor

- packages/web-components/fast-components/src/design-system-provider/design-system-provider.template.ts
- packages/web-components/fast-components/src/design-system-provider/design-system-provider.ts
- packages/web-components/fast-components/src/design-system-provider/index.ts
- yarn.lock
Updates the designs-system property decorator to accept more ergonomic values. Note that this change **is breaking**:
1. `customProperty` and `customPropertyName` have been combined into the `cssCustomProperty` key
2. Adds a `default` field to store the default value for the design system property
This change also moves the `use-default` attribute to the base provider class out of the FAST design-system provider.
> feat: updates design-system decorator to be more ergonomic and extensible

- packages/tooling/fast-tooling/src/message-system/data.props.ts
- packages/tooling/fast-tooling/src/message-system/data.spec.ts
- packages/tooling/fast-tooling/src/message-system/data.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.ts
Adds the ability to chain linked data together.
This will allow more complex data structures to be added with a single request.
> feat: allow linked data attached to other linked data to be added to a data dictionary

- specs/README.md
- specs/toolbar.md
This PR adds a new spec for a toolbar component.
> chore: add toolbar spec

- sites/fast-website/src/public/index.html
- sites/fast-website/src/public/style.css
Currently, we just have a blank page, so I created some placeholder sections for the components, by adding, header, section, and footer.
> chore: add section layout to the website

- packages/web-components/fast-components/src/radio-group/radio-group.ts
The keyboard navigation seemed to be working inside a toolbar but there were a few cases that would confuse things. Extensively tested the different scenarios and these changes fix the bug.
> fix: fixed bug when navigating in and out of a radio group inside a toolbar

- packages/web-components/fast-components/src/tabs/index.ts
We were not exporting `fast-tab` and `fast-tab-panel`.
> chore: export fast tab and fast tab panel

- packages/web-components/fast-components/src/dialog/dialog.ts
While working to create the `fast-components-msft` package I found that the component was not showing up on the screen. Upon investigation I found that the hidden attribute was no longer being handle as expected. It appears that all the boolean attrs in the dialog component were missing the mode of boolean. This fixes that and the dialog once again renders as expected.
> fix: add missing mode to dialog boolean attrs

- packages/tooling/fast-tooling/src/message-system/data.props.ts
- packages/tooling/fast-tooling/src/message-system/data.spec.ts
- packages/tooling/fast-tooling/src/message-system/data.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.spec.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.ts
Previously linked data could only be added one data location at a time, this updates the API to allow for multiple locations to be used in a single dictionary item.
I am updating the API, although this would normally be considered a breaking change the feature for adding linked data has not gone into a release yet.
> fix: fixes an issue with adding nested linked data

- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
Adds preview section to `fast-frame` component.
> feat: stub in preview section

- sites/fast-component-explorer/app/explorer.props.ts
- sites/fast-component-explorer/app/explorer.tsx
- sites/fast-component-explorer/app/preview.props.ts
- sites/fast-component-explorer/app/preview.style.ts
- sites/fast-component-explorer/app/preview.tsx
- sites/fast-component-explorer/package.json
- yarn.lock
This change addresses the following:
- Do not enable editing controls until the preview is initialized
- Enable transparency background
- Refactor to use the common site-utilities for widgets
Continues the work on #3025 
> fix: ensure data cannot be updated until the preview is initialized, clean up logic with transparency and use site-utilities for widgets

- sites/fast-website/src/app/css/style.css
Set the maximum content width of the content to 1200px. This matches the design and will also fix the current issue where the hover-cards can get into a blurred state. The change also updates the width of the hover-card to 400px.
> chore: update the content width of the page and hover card

- packages/web-components/fast-components/src/badge/badge.styles.ts
- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components/src/radio/radio.styles.ts
- packages/web-components/fast-components/src/styles/patterns/button.ts
- packages/web-components/fast-components/src/switch/switch.styles.ts
- packages/web-components/fast-components/src/tabs/tabs.styles.ts
- packages/web-components/fast-components/src/text-area/text-area.styles.ts
- packages/web-components/fast-components/src/text-field/text-field.styles.ts
Removes hard coded font sizes and replaces them with design system values
> fix: map font sizes to design system values

- sites/fast-tooling-examples/CONTRIBUTORS.md
- sites/fast-tooling-examples/app/example-react-1.ts
- sites/fast-tooling-examples/app/example-web-component-1.ts
- sites/fast-tooling-examples/app/examples/react-1/example.tsx
- sites/fast-tooling-examples/app/examples/react-1/index.html
- sites/fast-tooling-examples/app/examples/react-1/index.tsx
- sites/fast-tooling-examples/app/examples/web-component-1/index.html
- sites/fast-tooling-examples/app/examples/web-component-1/index.ts
- sites/fast-tooling-examples/app/index.html
- sites/fast-tooling-examples/app/index.ts
- sites/fast-tooling-examples/app/registry.ts
- sites/fast-tooling-examples/app/style.css
- sites/fast-tooling-examples/package.json
- sites/fast-tooling-examples/webpack.config.js
- yarn.lock
Adds the basic wiring for examples to exist as folders and routes on the site.
Begins to address #3102 and #3103
> chore: add basic example wiring for both web components and react

- packages/web-components/fast-components-msft/package.json
- packages/web-components/fast-components-msft/src/badge/badge.styles.ts
- packages/web-components/fast-components-msft/src/badge/fixtures/badge.html
- packages/web-components/fast-components-msft/src/badge/index.ts
- packages/web-components/fast-components/src/badge/badge.styles.ts
- packages/web-components/fast-components/src/badge/fixtures/base.html
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/badge/badge.template.ts
- yarn.lock
This PR udpates the badge template to conditionally render the CSS variable map values when one is actually supplied. Additionally, this updates the base styles of Badge in fast-components and adds appearances to `fast-components-msft`.
> feat: update badge API and styles

- packages/web-components/fast-components-msft/package.json
This PR fixes an issue with dependencies. `fast-components` was enumerated as a dependency of `fast-components-msft` which is incorrect - the correct dependency should be `fast-foundation`.
> fix: remove fast-components dependency in fast-components-msft

- sites/fast-creator/webpack.config.js
- sites/fast-tooling-examples/app/examples/native-element-1/index.html
- sites/fast-tooling-examples/app/examples/react-1/example.tsx
- sites/fast-tooling-examples/app/examples/react-1/index.html
- sites/fast-tooling-examples/app/examples/react-1/index.tsx
- sites/fast-tooling-examples/app/index.html
- sites/fast-tooling-examples/package.json
- sites/fast-tooling-examples/webpack.config.js
Adds a working example of the Message System with the `Form` React component from the `@microsoft/fast-tooling-react`.
Shows the example required in #3102
> chore: add simple React example using the Form

- sites/fast-website/package.json
Updates `package.json` to point to the latest versions in the workspace.
Fixes package linking for the `fast-website` project.
> bug fix: update package.json

- sites/website/.gitignore
Excludes the `.docusaurus` folder from git.
> chore(website): ensure docusaurus cache isn't tracked by git

- .github/workflows/cd-color-stage.yml
- .github/workflows/cd-create-stage.yml
This corrects the target build path and adds an additional configuration for the distribution path.
The action was building from `www` path instead of its parent
> fix: update to use the correct build path

- .github/workflows/cd-color-stage.yml
- .github/workflows/cd-create-stage.yml
The new method should allow publishing to multiple regions getting around the bug discovered when testing early where couldn't find the apps.
The service principle used for component explorer did not work for Creator and Color apps because they need to deploy to multiple regions.  
> chore: update to use publishing profile for deployment

- packages/tooling/fast-tooling/src/data-utilities/mapping.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/mapping.ts
- packages/tooling/fast-tooling/src/data-utilities/web-component.ts
This adds an optional property `enum` for a web component attribute definition. 
This further allows for parity between attributes and generated JSON schemas.
> feat: add enums as an option in an attribute

- .github/workflows/cd-static-cdn.yml
Updates the incorrect folder name for 'static-utilities' to instead use 'site-utilities' and fix broken deployment process.
Realized incorrect folder path was being used which broke the deployment process.
> chore: update to path to use correct folder name

- packages/web-components/fast-components/src/card/card.styles.ts
- packages/web-components/fast-components/src/dialog/dialog.styles.ts
- packages/web-components/fast-components/src/flipper/flipper.styles.ts
- packages/web-components/fast-components/src/slider/slider.styles.ts
- packages/web-components/fast-components/src/text-field/text-field.styles.ts
…mponents
Made updates to the high contrast styles for the card, flipper, slider, and text-field components.
Set a transparent border on the default styles on card and dialog. When in high contrast, the border color will automatically be set.
Update the focus state on,
flipper
slider
text-field
> fix: update high contrast on card, dialog, flipper, slider, text-field fast-components

- sites/fast-component-explorer/app/explorer.props.ts
- sites/fast-component-explorer/app/explorer.tsx
- sites/fast-component-explorer/app/preview.props.ts
- sites/fast-component-explorer/app/preview.tsx
Add the theme switcher in which triggers the `fast-design-system-provider` to add a background color. The background color will not show up if the transparency state is active.
> chore: add the theme switcher

- .prettierignore
- packages/web-components/fast-components/src/default-palette.ts
- yarn.lock
Formatting the `default-palette.ts` should be ignored by prettier (see the `.prettierignore` file) and therefore should not have an added trailing `,`.
> chore: update the formatting on the default palette as this file should not include a trailing comma

- sites/fast-website/src/app/css/style.css
Changed the font-size of the section header to 34px.
> fix: change section header font size for mobile

- sites/fast-website/src/app/components/card-section/card-section.styles.ts
- sites/fast-website/src/app/components/content-placement-container/content-placement-container.styles.ts
- sites/fast-website/src/app/components/content-placement-container/content-placement-container.template.ts
- sites/fast-website/src/app/components/feature-card/feature-card.styles.ts
- sites/fast-website/src/app/style/constants.ts
Update single column styling on feature cards.
Update styles to match hover behavior changes in design on feature cards.
> chore: update single column and hover styles on feature cards

- packages/web-components/fast-components-msft/src/flipper/flipper.styles.ts
- packages/web-components/fast-components/src/flipper/flipper.styles.ts
Outline was showing on focus on `fast-flipper` and hover and active states did not match.
> fix: outline on flipper

- build/testing/sauce-labs/test-browsers.js
- sites/website/src/docs/community/build-and-test.md
- sites/website/src/docs/community/contributor-guide.md
- sites/website/src/docs/community/policies.md
- sites/website/src/docs/community/writing-documentation.md
This migrates over previous published documentation to new folder structure.  This does not modify the old structure. I presume one we have all the documentation we want from the old root docs folder we can add a cleanup task to remove on one PR.
Content updates
> chore: add documentation to new docs folder

- sites/site-utilities/src/definitions/index.ts
Bundles the FAST component definitions and native element definitions as a named exports.
In order to reference all component definitions for the `@microsoft/fast-components` package it is easier to bundle these as a named export so that if they are added to this is done automatically. The same is true for the native elements being defined here as this will allow the separation of the custom components and native elements for documentation purposes.
> chore: bundle component definitions and native element definitions as named exports

- packages/web-components/fast-components/.npmignore
- packages/web-components/fast-element/.npmignore
- packages/web-components/fast-foundation/.npmignore
Corrects entries for `karma.conf.js` and `.eslintrc.js` that were misconfigured  in `.npmignore`. Also adds `storybook-static` to `.npmignore` so the storybook site is not published.
> chore: correct to ignore config files

- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.ts
- sites/fast-website/src/app/css/style.css
- sites/fast-website/src/public/index.html
This change adds responsive layouts for `fast-frame`.
> feat: responsive layouts for fast-frame

- packages/web-components/fast-foundation/src/patterns/start-end.ts
This PR removes the static class from the template which was causing the class and styles to persist.
> fix: remove static class from start/end template

- packages/web-components/fast-foundation/docs/guide/webpack.doc.md
This PR adds a basic step-by-step guide on how to setup a TypeScript+Webpack project for FAST Components from scratch.
> doc: add webpack guide

- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.ts
Adds the backdrop to the tablist in `fast-frame` to match the designs. This currently leaves out the blue for performance reasons.
> chore: adds backdrop to tablist in fast-frame

- .github/pull_request_template.md
- packages/web-components/fast-components/CONTRIBUTING.md
- sites/site-utilities/src/definitions/fast-components/README.md
This updates the pull request template to include a checklist specifically for the `@microsoft/fast-components` package and adds markdown files informing contributors about any additional files that should be created for the Component Explorer site to showcase a new or modified component.
The adjustment to the pull request template serves to act as a reminder for contributors to add/modify the appropriate files should they add/modify a component. It should also point them in the right direction on how to make contributions to these files.
> chore: update pull request template and contributing files for components in the @microsoft/fast-components package

- packages/web-components/fast-element/docs/api-report.md
- packages/web-components/fast-element/docs/roadmap.md
- packages/web-components/fast-element/src/attributes.ts
- packages/web-components/fast-element/src/controller.ts
- packages/web-components/fast-element/src/directives/behavior.ts
- packages/web-components/fast-element/src/directives/binding.ts
- packages/web-components/fast-element/src/directives/children.ts
- packages/web-components/fast-element/src/directives/directive.ts
- packages/web-components/fast-element/src/directives/node-observation.ts
- packages/web-components/fast-element/src/directives/ref.ts
- packages/web-components/fast-element/src/directives/repeat.ts
- packages/web-components/fast-element/src/directives/slotted.ts
- packages/web-components/fast-element/src/directives/when.ts
- packages/web-components/fast-element/src/dom.ts
- packages/web-components/fast-element/src/fast-definitions.ts
- packages/web-components/fast-element/src/fast-element.ts
- packages/web-components/fast-element/src/interfaces.ts
- packages/web-components/fast-element/src/observation/array-change-records.ts
- packages/web-components/fast-element/src/observation/array-observer.ts
- packages/web-components/fast-element/src/observation/notifier.ts
- packages/web-components/fast-element/src/observation/observable.ts
- packages/web-components/fast-element/src/styles.ts
- packages/web-components/fast-element/src/template-compiler.ts
- packages/web-components/fast-element/src/template.ts
- packages/web-components/fast-element/src/view.ts
Adds API docs to all public APIs in `fast-element`.
This involves several minor breaking changes where types were fixed up. It should not affect anyone.
> docs(fast-element): add public API docs

- packages/web-components/fast-foundation/src/slider-label/slider-label.template.ts
- sites/site-utilities/src/definitions/fast-components/fast-radio-group.definition.ts
- sites/site-utilities/src/definitions/fast-components/fast-radio.definition.ts
- sites/site-utilities/src/definitions/fast-components/fast-slider-label.definition.ts
- sites/site-utilities/src/definitions/fast-components/fast-slider.definition.ts
* update site definitions for radio-group, radio, slider and slider-label components
> chore: radio-group, radio, slider and slider-label component site definition cleanup

- packages/web-components/fast-components-msft/.gitignore
- packages/web-components/fast-components/.gitignore
- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/temp/api-report.md
- packages/web-components/fast-foundation/docs/api-report.md
Some inconsistencies in web components package .gitignore files were discovered. This PR adds the missing files. It also updates the api-reports for the packages.
> chore(web-components): add missing gitignore files and update api-report

- packages/web-components/fast-foundation/src/dialog/dialog.template.ts
For the primary control of our web components we have a pattern to use "control". This fixes an issue where the part name in use was "root".
> fix: correct css part name for dialog component

- packages/web-components/fast-foundation/src/accordion/README.md
- packages/web-components/fast-foundation/src/anchor/README.md
- packages/web-components/fast-foundation/src/badge/README.md
- packages/web-components/fast-foundation/src/button/README.md
- packages/web-components/fast-foundation/src/card/README.md
- packages/web-components/fast-foundation/src/checkbox/README.md
- packages/web-components/fast-foundation/src/design-system-provider/README.md
- packages/web-components/fast-foundation/src/dialog/README.md
- packages/web-components/fast-foundation/src/divider/README.md
- packages/web-components/fast-foundation/src/flipper/README.md
- packages/web-components/fast-foundation/src/menu-item/README.md
- packages/web-components/fast-foundation/src/menu/README.md
- packages/web-components/fast-foundation/src/progress/README.md
- packages/web-components/fast-foundation/src/radio-group/README.md
- packages/web-components/fast-foundation/src/radio/README.md
- packages/web-components/fast-foundation/src/slider-label/README.md
- packages/web-components/fast-foundation/src/slider/README.md
- packages/web-components/fast-foundation/src/switch/README.md
- packages/web-components/fast-foundation/src/tabs/README.md
- packages/web-components/fast-foundation/src/text-area/README.md
- packages/web-components/fast-foundation/src/text-field/README.md
- sites/website/docusaurus.config.js
- sites/website/package.json
- sites/website/sidebars.js
- sites/website/src/css/custom.css
- sites/website/src/docs/api/fast-components-msft.api.json
- sites/website/src/docs/api/fast-components.api.json
- sites/website/src/docs/api/fast-foundation.api.json
- sites/website/src/prepare-docs.js
This PR does the initial work to add live code examples to the docs site. Additional documentation will be added to include more examples of slotted content, etc in a future PR.
> feat: add live code examples to docs site

- packages/web-components/fast-components-msft/src/index.ts
This PR exports the styles and behaviors related to the MSFT design system from the fast-components-msft package.
> feat: export styles and utils from fast-components-msft

- packages/web-components/fast-components-msft/src/badge/badge.styles.ts
- packages/web-components/fast-components/src/badge/badge.styles.ts
- packages/web-components/fast-foundation/src/accordion/accordion-item/accordion-item.template.ts
- packages/web-components/fast-foundation/src/anchor/anchor.template.ts
- packages/web-components/fast-foundation/src/badge/badge.template.ts
- packages/web-components/fast-foundation/src/button/button.template.ts
There were a few components with missing part names. This PR adds them.
> fix: ensure all component internals have part names

- sites/fast-website/src/app/components/card-section/card-section.styles.ts
- sites/fast-website/src/app/components/content-placement-container/content-placement-container.styles.ts
- sites/fast-website/src/app/components/content-placement/content-placement.styles.ts
Add :focus-within to cards to set background color for visibility when using keyboard navigation.
Before:
After:
> Chore: add :focus-within to all cards

- packages/web-components/fast-element/package.json
Adds the CI api-extractor process to test command of fast-element. This will cause stale API markdown to fail on CI.
> chore: add api-extractor to CI for fast-element

- packages/web-components/fast-components-msft/src/styles/patterns/button.ts
- packages/web-components/fast-components/src/styles/patterns/button.ts
The intent of the hypertext styling on `fast-anchor` is that it be used inline with other text. This change updates the styles to better align with that intent by inheriting line height and font-size. If a user needs a similar solution for a non-inline scenario they can use the `lightweight` appearance of `fast-anchor` where the font size is set to align with other button appearances.
> fix: inherit font size and line height in hypertext styles

- .github/workflows/ci-weekly.yml
Adds Code QL into validation pipeline.
closes #3234 by @jhutchings1 with merge of existing validation actions and new codeQL.
Implement code scanning into the source repository.
> chore: update to merge contribution for codeQL

- .github/workflows/cd-www-stage.yml
- yarn.lock
Update to continuously deploy marketing and documentation site as one.
Required for brand and documentation refresh as part of Web Components work.
> chore: update action to build for www staging

- packages/web-components/fast-components-msft/src/button/button.styles.ts
- packages/web-components/fast-components/src/button/button.styles.ts
`fast-button` was including the hypertext styles as part of its stylesheet, but there is no "hypertext" appearance on `fast-button`. 
> fix: remove hypertext styles from button

- sites/fast-website/src/app/css/style.css
- sites/fast-website/src/public/index.html
- update badge styling to match figma
- update section spacing to match figma
- this was taken from a PR into feature/fast-frame
> chore: update badge style and section spacing

- sites/fast-website/src/app/svg/icon-close.svg
…ment
The close button SVG appears slightly misaligned within the button which is due to the fact that the viewbox is slightly off. This PR adjusts the viewbox to improve the alignment.
> chore: update website nav close svg viewbox to improve vertical alignment

- sites/fast-website/src/app/css/style.css
Fix overlap of footer with community section at 750px width and below.
Before:
After:
> fix: footer overlap below 750px wide

- sites/fast-website/src/app/css/style.css
Fix the navigation github link.
before
after
> fix: update to left align github link inside the navigation flyout

- sites/fast-website/src/app/css/style.css
- sites/fast-website/src/public/index.html
- add divider above footer 
- switch footer text color from neutral-foreground-rest to neutral-foreground-hint to darken it
- note: the divider is a bit dark, but it is using the divider recipe which we would like to use for now
> chore: add divider to footer and darken link text

- sites/fast-website/src/app/css/style.css
Update the grid-column on the header to extend out the logo and the GitHub link. Updated the breakpoint to 900px to fix the overlap of the navigation when scaling down.
logo and github link extended
> fix: resolve the issue where navigation overlaps with the window and extend logo and GitHub link out

- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/css/style.css
Update line-height to sync with font-size variable property for FAST marketing site
> chore: sync line-height with font-size across website

- sites/website/package.json
This PR updates the docusaurus version and fixes the API extractor to a fixed version to mitigate a build break.
> chore: fix api-documenter package version and update docusaurus versions

- sites/fast-website/src/app/components/content-placement/content-placement.styles.ts
- sites/fast-website/src/app/components/feature-card/feature-card.styles.ts
- add opacity to ::before style for "cards"
Before:
After:
Before:
After:
> chore: add opacity to ::before style for cards

- sites/fast-website/src/app/components/content-placement-container/content-placement-container.styles.ts
- sites/fast-website/src/app/components/content-placement-container/templates/feature.template.ts
- sites/fast-website/src/app/data/feature.data.ts
Change fixed anchor text to dynamic in features data and update feature template.
URLs to documentation and GitHub coming in future PR.
> chore: add anchor text to features data and template

- sites/fast-website/src/app/components/content-placement-container/content-placement-container.styles.ts
Remove cursor: pointer from feature and community cards.
> chore: remove cursor pointer from cards

- sites/fast-website/src/app/components/content-placement-container/content-placement-container.styles.ts
- sites/fast-website/src/app/components/content-placement-container/templates/framework.template.ts
- sites/fast-website/src/app/components/content-placement/content-placement.styles.ts
- sites/fast-website/src/app/components/feature-card/feature-card.styles.ts
Add 300ms transition to card sections and cards.  Update hover styles.
> chore: add transition and update card hover styling

- sites/fast-website/src/app/components/background-design/background-design.styles.ts
- sites/fast-website/src/app/components/navigation/navigation.ts
- sites/fast-website/src/app/css/style.css
- add styling to fix nav-bar to the top of screen on mobile
- fix issue for when the mobile menu is open being able to scroll down to the content and move past the menu
> fix: fix nav-menu content scroll issue and fix nav-bar to top of the screen on mobile

- sites/fast-website/src/app/css/style.css
Fixed the height between each section for desktop and mobile mode. I removed the min-height and set the top and bottom margin on each section.
Each section had a different spacing height. 
> fix: adjust the height spacing between the sections for the marketing site

- sites/fast-website/src/app/components/content-placement-container/content-placement-container.styles.ts
Update anchor styling to display underline to separate anchors from plain text in cards.
> fix: display underline in anchors

- sites/fast-website/src/app/css/style.css
Removed the underline in both the header and footer logo.
> fix: removed the underline from the logo

- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.ts
This change fixes the following:
- Accent color selection.
- Background color updating.
- Hue and saturation slider backgrounds.
- Removed density tab and moved density slider to styles tab.
> fix: accent color selection, slider backgrounds and tab reorganization

- sites/fast-component-explorer/app/explorer.tsx
This change checks for any updates to the history api. If it finds that the location path did change it will update the active component accordingly.
> fix: updates the current component when the browser back button is pressed

- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
- sites/fast-website/src/app/data/feature.data.ts
- sites/fast-website/src/app/data/framework.data.ts
- sites/fast-website/src/public/index.html
This PR updates the links and text for the website.
> chore: update website text and links

- sites/fast-website/src/app/css/style.css
fix missing tab focus to header and footer logo. 
> fix: add focus to header and footer logo

- sites/fast-website/src/public/index.html
> chore: initial cta for website should be fast-anchor

- sites/fast-website/src/app/data/community.data.ts
- sites/fast-website/src/public/index.html
- sites/website/docusaurus.config.js
> chore: update website social links

- README.md
Updates the twitter badge to match the new twitter handle.
> doc(readme): fix twitter badge

- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
This PR updates the slider values for the website adaptive UI section.
> chore: update website adaptive ui slider values

- packages/web-components/fast-components-msft/src/dialog/dialog.styles.ts
- packages/web-components/fast-components/src/dialog/dialog.styles.ts
Corrects a bug causing the dialog to appear broken and without styles.
> fix: correct css selector for dialog control

- sites/fast-website/src/app/components/side-navigation/side-navigation.template.ts
This PR standardizes to our current preference of link handling by removing the target attribute from the social links on the website.
> chore: remove target _blank from website social links

- sites/fast-component-explorer/app/explorer.tsx
- sites/fast-component-explorer/app/preview.props.ts
- sites/fast-component-explorer/app/preview.tsx
- yarn.lock
> fix: update standard luminance values for fast-components

- sites/fast-website/src/public/index.html
This PR comments out the side nav indicators as a more intricate solution is needed now that certain design aspects have changed on the page. 
> chore: comment out side navigation indicators and add todo

- sites/fast-website/src/public/index.html
- sites/fast-website/webpack.common.js
- sites/website/docusaurus.config.js
This change fixes an issue where safari would error without showing content and also a broken link.
> fix: addresses an issue where website will not show on safari

- sites/fast-website/src/app/css/style.css
Added margin-top too the hero section when breakpoint hits 900px.
before
after
> fix: adjust top margin on the hero section for mobile view

- sites/fast-color-explorer/webpack.config.js
- sites/fast-component-explorer/webpack.config.js
- sites/fast-creator/webpack.config.js
- sites/fast-tooling-examples/webpack.config.js
- sites/fast-website/webpack.common.js
The manifest file missing several key pieces of information was being added and causing a CORS issue when attempting to fetch it from the CDN.
The manifest files will need to be specific to each site and should not added via the CDN.
Additional issues will be filed to fully explore the PWA story for sites.
> chore: after some testing it would appear that the manifest is being added as a link which was not intended

- sites/fast-website/src/app/components/side-navigation/side-navigation.ts
- sites/fast-website/src/public/index.html
- fix for #3404
- update intersection observer function to fix missed sections on large screens and sections with reduced heights
**note: Please smoke these changes! I do not have a large monitor, so have had Kham run them for me to test that they work, but if we could have further large monitor testing it would be greatly appreciated. 
> fix: for scroll indicator #3404

- packages/web-components/fast-foundation/docs/integrations/angular.md
- packages/web-components/fast-foundation/docs/integrations/vue.md
- sites/website/sidebars.js
This PR adds an integration doc for Angular.
> docs(integrations): add an angular integration doc

- sites/fast-color-explorer/package.json
- sites/fast-color-explorer/webpack.config.js
- sites/fast-component-explorer/package.json
- sites/fast-component-explorer/webpack.config.js
- sites/fast-creator/package.json
- sites/fast-creator/webpack.config.js
- sites/fast-tooling-examples/package.json
- sites/fast-tooling-examples/webpack.config.js
- sites/fast-website/package.json
- sites/fast-website/webpack.common.js
- sites/site-utilities/src/curated-html.json
- sites/website/.gitignore
- sites/website/docusaurus.config.js
- sites/website/src/build-homepage.js
- yarn.lock
This change places the `favicon.ico` file at the root of all built sites. This is the default location for the file so there is no need to link to it, also the CDN was having some trouble with the `.ico` file format which caused a CORS issue.
> chore: add the favicon.ico file to the root of all sites instead of referring to the CDN

- sites/fast-website/package.json
- sites/fast-website/webpack.common.js
This fixes a build break and adds a test to ensure the build for the `website` site folder is tested during the build gate.
> chore: add a test to ensure yarn can build the package and fix an output file directory

- packages/web-components/fast-foundation/src/tabs/tabs.ts
Makes `adjust` method public so we can leverage it in cases were we extend the `tabs` class.
> feat: make tabs adjust method public

- packages/tooling/fast-tooling-react/app/pages/form-and-navigation.tsx
- packages/tooling/fast-tooling-react/src/navigation/navigation.tsx
A runtime error was occurring when linked data was being removed due to a potential de-syncing of the data, this adds a check to make sure an index of linked data is available before attempting to render it.
> fix: checks for the presence of an index of linked data before rendering it

- packages/web-components/fast-components-msft/src/card/card.styles.ts
- packages/web-components/fast-components/src/card/card.styles.ts
There was a transparent border set around the card that is only visible in high contrast.
High contrast work will be done in a separate PR
closes #3440 
before
after
> fix: removed extra padding around fast card component

- packages/web-components/fast-components-msft/src/card/card.styles.ts
- packages/web-components/fast-components/src/card/card.styles.ts
Add box-shadow and background to the card for high-contrast
> feat: add high contrast border color on fast card in high contrast

- packages/web-components/fast-foundation/src/text-field/text-field.template.ts
Since we are using `delegatesFocus ` option, the focus is being set inside the custom element and not on the host element, I removed the aria and role attributes from the template and added the `type` attribute to the input.
closes #3436 
> fix: removed accessibility attributes and added type to input for text field component

- packages/web-components/fast-foundation/src/accordion/README.md
Removes an incorrect implementation detail regarding delegatesFocus shadow option.
> chore: remove delegates focus from accordian readme

- packages/web-components/fast-foundation/src/tabs/tabs.ts
Corrects the spelling of aria-labelledby in tabs. Currently the spelling renders the component inaccessible.
> fix: correct spelling of aria-labelledby in tabs

- packages/web-components/fast-foundation/src/flipper/flipper.template.ts
- packages/web-components/fast-foundation/src/flipper/flipper.ts
Removed `mode: "fromView"` to reflect the value to the DOM.
closes #3464 
> fix: reflect aria-hidden attribute in the DOM for the flipper component

- .github/CODEOWNERS
- packages/tooling/fast-tooling-wasm/.gitignore
- packages/tooling/fast-tooling-wasm/CONTRIBUTING.md
- packages/tooling/fast-tooling-wasm/README.md
- packages/tooling/fast-tooling-wasm/app/index.html
- packages/tooling/fast-tooling-wasm/app/index.ts
- packages/tooling/fast-tooling-wasm/app/schemas/number.schema.json
- packages/tooling/fast-tooling-wasm/package.json
- packages/tooling/fast-tooling-wasm/permutator/README.md
- packages/tooling/fast-tooling-wasm/permutator/wasm.c
- packages/tooling/fast-tooling-wasm/tsconfig.json
- packages/tooling/fast-tooling-wasm/webpack.config.js
This adds a private package `fast-tooling-wasm` which will host any projects that compile to the wasm format. It also includes a small test app and an initial file setup for the `permutator` project. This will be progressively overwritten as the `permutator` project is built out but serves as a starting point for ensuring that all fo the bits and pieces of the package setup are working correctly.
This places non-typescript wasm files in their own location and sets up a manual testing playground.
> chore: add a private package and scaffolding for tooling wasm projects

- packages/web-components/fast-components-msft/src/index.ts
> fix: tree view and tree view item not exported

- sites/site-utilities/CONTRIBUTING.md
- sites/site-utilities/package.json
Due to the icon generation process hanging, and the fact that generating icons should only happen once in a great while, the script for generating icons for the manifest is being removed from the `prepare` script. There should be no danger to this as the generated files are not in the gitignore.
> chore: remove the the generate:icons script from prepare

- sites/fast-website/src/public/index.html
1. Changes the name of role provided to [fast-divider] from "seperator" to "separator" to prevent accessibility issues. 
2. The role "seperator" is not supported. 
**Note:** https://www.w3.org/WAI/PF/aria-1.1/roles#separator
Fixes https://github.com/microsoft/fast/issues/3462
> fix: rename role attribute value of fast-divider from seperator to separator

- sites/website/src/build-homepage.js
Switch from yarn process spawning to webpack API to build the `fast-website` package directly in the `website` process.
The spawn process method doesn't work on Windows without changing some flags, and this method is safer.
The only caveat is that we lose the progress flag, but there may be ways to get stats back if we really miss it.
I've tested it on Ubuntu (WSL2) and Windows (node and yarn directly installed) and both build and run successfully.
> fix: switch to webpack for homepage building

- packages/web-components/fast-foundation/src/dialog/README.md
> chore: remove dialog example which breaks keyboarding

- packages/web-components/fast-components-msft/src/anchor/index.ts
- packages/web-components/fast-components-msft/src/button/index.ts
This change follows up on #3494 to fix #3456 for the `@microsoft/fast-components-msft` package.
> fix: ensure setAttribute is not called during construction

- .github/stale.yml
Updates the stale task to use the new label.
We're re-organizing our labels and various ways we're using GitHub. This updates the stale task to align with the new plan.
> chore: update stale task to use new label

- README.md
We do not currently have a status section as this page was removed so removing here for the time being.
> chore: update to remove status section

- .github/ISSUE_TEMPLATE/report-a-bug.md
- .github/ISSUE_TEMPLATE/request-a-feature.md
This updates or issue templates to assign the new triage label. This is a quick fix in order to get automation working. I'll come back later with another PR to improve the templates more broadly.
> chore: update issue template label assignment

- packages/web-components/fast-components-msft/docs/api-report.md
- packages/web-components/fast-components-msft/src/text-area/index.ts
- packages/web-components/fast-components-msft/src/text-field/index.ts
- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/text-area/index.ts
- packages/web-components/fast-components/src/text-field/index.ts
- packages/web-components/fast-components/temp/api-report.md
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/text-area/text-area.template.ts
- packages/web-components/fast-foundation/src/text-area/text-area.ts
- packages/web-components/fast-foundation/src/text-field/text-field.template.ts
- packages/web-components/fast-foundation/src/text-field/text-field.ts
- sites/site-utilities/src/definitions/fast-components/fast-text-area.definition.ts
- sites/site-utilities/src/definitions/fast-components/fast-text-field.definition.ts
This PR moves the final "appearances" residing in foundation to the components layer. Appearances and the semantics surrounding them are specific to component instances and design systems. Moving this opinionated layer to the components layer.
Users leveraging the components will experience no disruption. Users leveraging this functionality from `fast-foundation` will need to include the appearance in their class. Users leveraging the enum will need to update to leverage the type.
> fix: move text field and text area appearances from foundation to components

- packages/web-components/fast-components-msft/src/slider/fixtures/slider.html
- packages/web-components/fast-components-msft/src/slider/slider.stories.ts
- packages/web-components/fast-components/src/slider/fixtures/base.html
- packages/web-components/fast-components/src/slider/slider.stories.ts
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/slider/slider.template.ts
- packages/web-components/fast-foundation/src/slider/slider.ts
Added `valueTextFormatter` to use on `aria-valuetext`.
To smoke branch. 
Run fast-component(or fast-component-msft)
Enable screen reader
If there is a value unit on the slider example, the screen reader will read it out.
feature-request #3504 
> feat: create an observable function to support aria-valuetext on slider component

- sites/fast-creator/app/configs/linked-data-examples.ts
- sites/fast-creator/app/preview.tsx
- sites/fast-creator/app/utilities/wrapper.ts
This fixes a performance issue in the Creator site which was occurring due to too many listeners being attached and removed on ever DOM update. The load listener was causing the most trouble so this was taken out and placed in the parent component so that it is only assigned a single time.
> perf: fix performance in creator occuring from attaching load listeners

- packages/web-components/fast-foundation/src/design-system-provider/README.md
This change corrects several documentation errors in the "Creating a Design System Provider" section.
closes #3556
> chore: correct provider creation docs

- README.md
- sites/website/src/docs/community/join.md
- sites/website/src/docs/introduction.md
This change updates the url pointing to `good-first-issue` label on github to the correct label `community:good-first-issue`
`Joining the community` section on fast website points to correct github label for `community:good-first-issue`
> chore: correct issues label url

- CONTRIBUTING.md
Fix minor typo in contributing.md
Fixes a typo
> chore: fix typo in contributing.md

- CONTRIBUTING.md
Update url to CODEOWNERS file to absolute url instead of relative
Using a relative url does not work outside of github, like in [docs](https://www.fast.design/docs/community/contributor-guide#code-owners)
> chore: update codeowners use absolute url

- packages/tooling/fast-tooling/src/message-system/data.spec.ts
- packages/tooling/fast-tooling/src/message-system/data.ts
- packages/tooling/fast-tooling/src/message-system/index.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.props.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.spec.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.ts
Adds two new utilities:
- `getLinkedData` which converts data dictionary items to linked data items
- `getLinkedDataList` which returns all dictionary ids that are linked data items for a given dictionary item
These utilities will assist the `Navigation` component in `@microsoft/fast-tooling-react` packages drag and drop functionality by allowing deep nested drag and drop.
> feat: add data utilities to retrieve linked data from a data dictionary and ids of linked data items

- packages/tooling/fast-tooling-react/app/pages/navigation/example.data.ts
- packages/tooling/fast-tooling-react/src/navigation/navigation.props.ts
- packages/tooling/fast-tooling-react/src/navigation/navigation.tsx
- packages/tooling/fast-tooling/src/message-system/data.spec.ts
- packages/tooling/fast-tooling/src/message-system/data.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.spec.ts
The drag and drop in `Navigation` was not properly removing and re-assigning dictionary ids for nested items. This uses the new utilities to resolve this issue. It also includes a slight adjustment to the aforementioned utilities where linked data references were not being unset.
> fix: the Navigation component can now drag and drop nested component

- packages/web-components/fast-components/docs/design/color.md
- packages/web-components/fast-components/docs/design/design-system.md
- packages/web-components/fast-components/rollup.config.js
- sites/website/docusaurus.config.js
- sites/website/package.json
- sites/website/src/build-homepage.js
* Create a new output bundle `fast-components.iife.min.js` for use on the documentation website
* Upgrade Docusaurus and deps to `2.0.0-alpha.60`
The current version of Docusaurus doesn't handle the `type="module"` attribute for script tags so we need a version that can be loaded and called with just a basic script tag.
> fix: update docusaurus and use local fast-components min bundle

- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/accordion/accordion-item/index.ts
- packages/web-components/fast-components/src/accordion/index.ts
- packages/web-components/fast-components/src/anchor/index.ts
- packages/web-components/fast-components/src/anchored-region/index.ts
- packages/web-components/fast-components/src/badge/index.ts
- packages/web-components/fast-components/src/button/index.ts
- packages/web-components/fast-components/src/card/index.ts
- packages/web-components/fast-components/src/checkbox/index.ts
- packages/web-components/fast-components/src/dialog/index.ts
- packages/web-components/fast-components/src/divider/index.ts
- packages/web-components/fast-components/src/flipper/index.ts
- packages/web-components/fast-components/src/menu-item/index.ts
- packages/web-components/fast-components/src/menu/index.ts
- packages/web-components/fast-components/src/progress/progress-ring/index.ts
- packages/web-components/fast-components/src/progress/progress/index.ts
- packages/web-components/fast-components/src/radio-group/index.ts
- packages/web-components/fast-components/src/radio/index.ts
- packages/web-components/fast-components/src/slider-label/index.ts
- packages/web-components/fast-components/src/slider/index.ts
- packages/web-components/fast-components/src/switch/index.ts
- packages/web-components/fast-components/src/tabs/index.ts
- packages/web-components/fast-components/src/tabs/tab-panel/index.ts
- packages/web-components/fast-components/src/tabs/tab/index.ts
- packages/web-components/fast-components/src/text-area/index.ts
- packages/web-components/fast-components/src/text-field/index.ts
- packages/web-components/fast-components/src/tree-item/index.ts
- packages/web-components/fast-components/src/tree-view/index.ts
Export the styles from the component's styles file in their respective index.
fixes #3593 
> fix: exposing styles on all web components

- sites/website/sidebars.js
Add tree-view to the component documentation navigation in fast-website
> chore: added treeview to component documentation in sidebar

- packages/web-components/fast-components/README.md
add missing close html script tag on the fast-components readme file
This fixes an HTML syntax issue.
> chore: add missing close html script tag.

- examples/todo-app-tutorial/src/todo-app.ts
- examples/todo-app-tutorial/src/todo-item.ts
The screen reader was reading out the Unicode, so I added an aria-label attribute to the to-do item button. By default it reads out "Remove item".
> fix: add aria-label to item button to fix screen reader from reading out the Unicode

- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- yarn.lock
This PR updates the badge to be static as badges typically are static over images. This should resolve an issue with color contrast as well.
> chore: update badge to be static color and update temporary image background color

- packages/web-components/fast-components/CONTRIBUTING.md
- packages/web-components/fast-components/src/accordion/accordion-item.open-ui.definition.json
- packages/web-components/fast-components/src/accordion/accordion.open-ui.definition.json
- packages/web-components/fast-components/src/anchor/anchor.open-ui.definition.json
- packages/web-components/fast-components/src/badge/badge.open-ui.definition.json
- packages/web-components/fast-components/src/button/button.open-ui.definition.json
- packages/web-components/fast-components/src/card/card.open-ui.definition.json
- packages/web-components/fast-components/src/checkbox/checkbox.open-ui.definition.json
- packages/web-components/fast-components/src/dialog/dialog.open-ui.definition.json
- packages/web-components/fast-components/src/divider/divider.open-ui.definition.json
- packages/web-components/fast-components/src/flipper/flipper.open-ui.definition.json
- packages/web-components/fast-components/src/menu-item/menu-item.open-ui.definition.json
- packages/web-components/fast-components/src/menu/menu.open-ui.definition.json
- packages/web-components/fast-components/src/progress/progress-ring.open-ui.definition.json
- packages/web-components/fast-components/src/progress/progress.open-ui.definition.json
- packages/web-components/fast-components/src/radio-group/radio-group.open-ui.definition.json
- packages/web-components/fast-components/src/radio/radio.open-ui.definition.json
- packages/web-components/fast-components/src/slider-label/slider-label.open-ui.definition.json
- packages/web-components/fast-components/src/slider/slider.open-ui.definition.json
- packages/web-components/fast-components/src/switch/switch.open-ui.definition.json
- packages/web-components/fast-components/src/tabs/tab-panel.open-ui.definition.json
- packages/web-components/fast-components/src/tabs/tab.open-ui.definition.json
- packages/web-components/fast-components/src/tabs/tabs.open-ui.definition.json
- packages/web-components/fast-components/src/text-area/text-area.open-ui.definition.json
- packages/web-components/fast-components/src/text-field/text-field.open-ui.definition.json
- packages/web-components/fast-components/src/tree-item/tree-item.open-ui.definition.json
- packages/web-components/fast-components/src/tree-view/tree-view.open-ui.definition.json
These are the bare minimum Open UI definitions that will pass a validation checks against https://github.com/microsoft/fast/pull/3636/files#diff-524785af6482ec9201b4c42ba6d83ca9
This is part of the work to integrate Open UI JSON schema compliant configurations into the `@microsoft/fast-components` package.
> chore: add starter Open UI definition files for each component

- packages/web-components/fast-components/src/accordion/fixtures/base.html
- sites/fast-component-explorer/app/fast-components/configs/fast-accordion.ts
Fixes #3653 
Fixes an issue where the expand/collapse slot SVG's for the examples were incorrectly applied.
Current:
https://explore.fast.design
Updated:
> chore: swap expand and collapse icons for accordion on component explorer

- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/radio-group/radio-group.template.ts
- packages/web-components/fast-foundation/src/radio-group/radio-group.ts
- packages/web-components/fast-foundation/src/radio/radio.ts
* Updated how the children elements are collected, looking at them more generically, HTMLElement and have role "radio".
* Fixed space bar usage of selecting radio when in a group
closes #3637
> fix: fix radiogroup tabfocus

- packages/web-components/fast-foundation/src/slider/slider.ts
When the user is dragging the thumb we don't want any animation, just move the thumb position
closes #3662
> fix: turn off animation when dragging

- packages/web-components/fast-element/src/dom.ts
Fixes a build break caused by an accidental merge which introduced prettier regressions.
> chore: fix prettier build break

- sites/site-utilities/statics/server/package.json
- sites/site-utilities/statics/server/server.js
Add Helmet https://github.com/helmetjs/helmet to improve security across node express applications and resolved a high severity issue.
Hardens security in response to WebScouts discover of https://webscout/#/scans/757563/issues?issueId=3692644:
`Detail: x-content-type-options: nosniff was not found in the headers and is required`
> chore(cloud): add helmet for security improvements to node express server

- sites/website/docusaurus.config.js
Home, Components, Community links are now added in the header of the documentation page.
Links to Home, Components and Community are added to the documentation page header.
This PR resolves #3666
> feat: add links to documentation header

- sites/site-utilities/statics/server/package.json
Resolved formatting issues, adds better description, and unpins package version.
Noticed a malformed JSON and discovered that we also should be pinning package dependency in production to limit the risk of packages updating under our feet without our knowledge.
> chore: update to resolve char issue and unpin

- sites/site-utilities/statics/server/server.js
Removes default helmet implementation for securing Express applications specifically removing content security policy.
Fix overly strict security policy breaking svg's and other content security policy assets
> chore: update to helmet configuration to omit csp

- sites/fast-tooling-examples/app/index.html
- sites/site-utilities/src/components/logo/index.tsx
There was an issue with SVG sizing for the inline logo on the Creator, Tooling examples and Component Explorer sites. This change fixes the height so that the SVG can scale appropriately.
> fix: addresses an issue with the inline logo sizing

- .github/CODEOWNERS
This change adds @EisenbergEffect as a top level code owner for pull request sign offs.
@EisenbergEffect is a top level contributor who has in-depth knowledge on all facets of the FAST project.
> chore: add Rob Eisenberg as a top level code owner

- sites/fast-component-explorer/app/explorer.props.ts
- sites/fast-component-explorer/app/explorer.tsx
- sites/fast-component-explorer/package.json
- sites/fast-component-explorer/tsconfig.json
- sites/fast-component-explorer/webpack.config.js
- sites/fast-creator/app/creator.props.ts
- sites/fast-creator/app/creator.tsx
- sites/fast-creator/package.json
- sites/fast-creator/webpack.config.js
- yarn.lock
Adds the Monaco editor to the Component explorer and Creator sites.
**Component explorer**
**Creator**
This will allow users to copy HTML into their projects.
Resolves #3561
~Relies on the completion of #3697 to be error free during run time.~
> feat: add the Monaco editor to the Component explorer and Creator sites

- sites/site-utilities/src/definitions/index.ts
- sites/site-utilities/src/schemas/definition-mapper.ts
This fixes an erroneous import of the component definitions.
This issue causes a runtime error on the Component explorer site.
> fix: updates the imports of component definitions

- sites/fast-website/src/app/data/framework.data.ts
Removed "coming soon" from React under framework section.
React wrapper is now available so removing the coming soon label from React.
React support is no longer coming so, it is available.
> fix: remove coming soon from react

- sites/website/src/css/custom.css
A small PR to change the styles of the ToC button that appears on mobile so that it's more obvious.
Closes #3665
> fix(website): add more obvious styles to the mobile ToC button

- sites/website/src/docs/community/join.md
Copywriting review and edits for join.md documentation.
Improved the documentation and better follow our documentation guidance.
> chore: join documentation copywriting and edits

- yarn.lock
Manual upgrade of elliptic. See https://github.com/microsoft/fast/pull/3595 for more info.
closes  #3595 
> chore(deps): upgrade elliptic from v6.5.1 to v6.5.3

- yarn.lock
> chore(deps): upgrade dot-prop to be >= v4.2.1 

- packages/web-components/fast-components/docs/design/localization.md
Localization docs were sourcing an export from the wrong package - this change corrects that documentation.
> chore: correct export location in localization docs 

- packages/web-components/fast-components/src/button/README.md
- packages/web-components/fast-foundation/src/anchored-region/anchored-region.spec.md
- packages/web-components/fast-foundation/src/anchored-region/anchored-region.ts
- packages/web-components/fast-foundation/src/button/button.spec.md
- packages/web-components/fast-foundation/src/design-system-provider/README.md
- packages/web-components/fast-foundation/src/dialog/dialog.spec.md
- packages/web-components/fast-foundation/src/form-associated/form-associated-custom-element.spec.md
- packages/web-components/fast-foundation/src/form-associated/form-associated.ts
- packages/web-components/fast-foundation/src/menu/menu.spec.md
- packages/web-components/fast-foundation/src/slider/slider.ts
- packages/web-components/fast-foundation/src/switch/switch.spec.md
- packages/web-components/fast-foundation/src/tabs/tabs.spec.md
- packages/web-components/fast-foundation/src/text-field/text-field.spec.md
Fixes typos in the readme as well as spec files for `fast-foundation` package and in button README for `fast-components` package.
> fix: typos in readme and spec files

- yarn.lock
Upgrades kind-of dependency from v6.0.2 to v6.0.3
> chore(deps): upgrade kind-of from v6.0.2 to v6.0.3

- .github/workflows/ci-daily.yml
- .github/workflows/ci-weekly.yml
- packages/tooling/fast-tooling-wasm/package.json
- packages/tooling/fast-tooling-wasm/permutator/__tests__/test.c
- packages/tooling/fast-tooling-wasm/permutator/build.js
This draft is to test whether `gcc` can successfully be run on Windows and Mac in the weekly build which is currently broken.
> chore: fix the weekly build that was incorrectly installing gcc on windows

- sites/fast-component-explorer/package.json
- yarn.lock
Resolved dependable security issue https://github.com/microsoft/fast/network/alert/yarn.lock/prismjs/open 
Dependabot identified a security vulnerability delivered through a dependency.  
> chore: remove package not in use to fix dependency issue

- sites/fast-website/src/public/footer.ejs
- sites/website/docusaurus.config.js
Privacy links were partially correct so modifying for compliance.
**Summary**: No privacy link meeting the Microsoft Privacy Standards was found on the page under test. Any potential privacy links that were found but did not meet the Microsoft Privacy Standards are listed below with the reasons why they do not meet the standards.
**Detail**: The link with InnerText set to 'Privacy &amp; Cookies' and href set to 'https://privacy.microsoft.com/en-US/privacystatement' has the following issues: Privacy link does not redirect. All privacy links must use a link forwarder.
Reference: https://webscout/#/scans/765287/issues?issueId=3764193
Reference: https://webscout/#/scans/765287/issues?issueId=3764191
Issues found on web scout:
**Adding or modifying component(s) …
> chore: update to use recommended privacy links

- .github/workflows/ci-weekly.yml
This will reimplement code scanning so that it works for TypeScript and Javascript. 
Note: The firing GitHub event for `pull_request` will be returned to it's original state of running on cron once this is tested in place.
Code scanning is breaking due to misconfiguration.
> fix: update action for weekly validation on code scanner

- packages/tooling/fast-tooling/app/examples/README.md
- packages/tooling/fast-tooling/app/examples/monaco/index.html
- packages/tooling/fast-tooling/app/examples/monaco/webpack.common.js
- packages/tooling/fast-tooling/app/examples/monaco/webpack.dev.js
- packages/tooling/fast-tooling/app/index.html
- packages/tooling/fast-tooling/app/webpack.common.js
- packages/tooling/fast-tooling/app/webpack.dev.js
- packages/tooling/fast-tooling/package.json
- packages/tooling/fast-tooling/webpack.config.js
This sets up a testing route for the Monaco editor adaptor as well as setting up a scaffolding for future example apps within the `@microsoft/fast-tooling` package. Each example app will have their own webpack file and exist on a route when `webpack-dev-server` is run.
> chore: setup a manual testing route for the monaco editor adaptor

- packages/tooling/fast-tooling/src/data-utilities/monaco.spec.md
This adds a spec file for an adaptor to work between updates provided to the `DataDictionary` via the `MessageSystem` and updates coming from the Monaco editor to consolidate the updates values from both.
This outlines the method for 2 way editing using FAST tooling and the Monaco editor.
> chore: add spec for an adaptor to work with the Monaco editor and Data Dictionary and provide updates

- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components/src/radio/radio.styles.ts
- packages/web-components/fast-components/src/switch/switch.styles.ts
Corrects the RTL styling of the Switch component, mirroring the active-indicator in RTL documents. Also corrects a number of styling issues in Switch, Checkbox, and Radio that were relying on the `:enabled` pseudo-class on the custom element host, a technique that only works in browsers that support `ElementInternals` (which firefox does not)
closes #3767 #3766
> fix: add RTL style to Switch and firefox styling issues in Switch, Checkbox, and Radio

- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
This was a pass to ensure we don't have multiple h1 on the page.
Fix the heading on the fast-frame template to be h4, and add content h4 style selector.
> fix: remove headings tag on fast-frame template

- .github/workflows/cd-www-stage.yml
Fixed pipeline break deploying to staging on https://stage.www.fast.design
Break needs fixed.
> chore(cd): update to correct package install when using yarn

- README.md
- sites/website/src/docs/design-systems/creating-a-design-system.md
- sites/website/src/docs/design-systems/using-the-design-system.md
- sites/website/src/docs/introduction.md
Fixing some incorrect or broken links.
> docs(website): address several broken links

- sites/fast-component-explorer/app/explorer.tsx
Fixes a desync issue where the last state was being used instead of the update from the message system.
Solves a desync issue with data on explore.fast.design.
> fix: address a desync issue on explore site

- packages/web-components/fast-components/src/tabs/tabs.styles.ts
This change is an update to the previous work, which was to align the start and end slot to the tab list. With further discussion on finding the best approach, it was decided that we should not change the padding on the slot but to just align itself to the center.
> fix: update the padding to start and end slot on tabs to add align self

- packages/web-components/fast-components/src/button/button.styles.ts
- packages/web-components/fast-components/src/flipper/flipper.styles.ts
- packages/web-components/fast-components/src/menu-item/menu-item.styles.ts
- packages/web-components/fast-components/src/slider-label/slider-label.styles.ts
- packages/web-components/fast-components/src/slider/slider.styles.ts
- packages/web-components/fast-components/src/styles/patterns/button.ts
- packages/web-components/fast-components/src/tabs/tab/tab.styles.ts
- packages/web-components/fast-components/src/text-field/text-field.styles.ts
- packages/web-components/fast-components/src/tree-item/tree-item.styles.ts
- Modify css for svg fill to use currentcolor when the svg should default to the text color
- Align color fill for menu-item, flipper, text-field, tree-item, tab, and slider into alignment with anchor and button
- Modify text-field input to inherit color from root and root fill to use currentcolor
Align SVG color fill with fast-anchor and fast-button
https://github.com/microsoft/fast/issues/2260
Closes #2260  
> fix: update glyphs to use currentcolor

- packages/web-components/fast-foundation/src/slider/slider.ts
- packages/web-components/fast-foundation/src/tabs/tabs.ts
- packages/web-components/fast-foundation/src/utilities/direction.ts
- packages/web-components/fast-foundation/src/utilities/index.ts
Adds direction functionality on Tabs to swap left and right keyboarding when in RTL
Fixes #3804 for the Tabs issue
Test:
1) run `yarn dev` in *fast-foundation*
2) run `yarn start` in *sites/fast-component-explorer*
3) View Tabs component and switch between LTR and RTL to test keyboarding
> fix: tabs right and left keyboarding in rtl

- packages/tooling/fast-tooling/src/data-utilities/shortcut-action.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/shortcut-action.ts
- packages/tooling/fast-tooling/src/data-utilities/shortcuts.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/shortcuts.ts
Creates a shortcut utility and shortcut action utility for describing shortcuts and posting custom events through the `MessageSystem` to allow these shortcut events to be attached to DOM nodes.
For full spec see #3781 
> feat: add a shortcut utility

- packages/tooling/fast-tooling/src/data-utilities/shortcuts.spec.md
This creates the spec for a shortcuts utility that registers various shortcut actions and provides enough hooks for a context menu.
Resolves #3774
> chore: add spec for shortcuts utility

- packages/web-components/fast-foundation/src/radio-group/radio-group.ts
- sites/fast-component-explorer/app/fast-components/configs/fast-radio-group.ts
Fixes keyboard navigation between Radio Group radios when in RTL by checking for direction using the getDirection utility.
- Fixes #3839 
- Adds one more Radio to Radio Group for fast-component-explorer for proper testing.
> fix: Radio Group right and left keyboarding in RTL

- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/form-associated/form-associated-custom-element.spec.md
- packages/web-components/fast-foundation/src/form-associated/form-associated.ts
> fix: implicit form-associated submission

- yarn.lock
Patch by bumping to more recent version.
Patches security vulnerabilities.
> chore(deps): bump yarns-parser to resolve security vulnerability

- packages/web-components/fast-foundation/src/tree-item/tree-item.ts
added `true` on the return.
closes #3878 
> fix: able to keyboard tab out of tree-view when focused on a child item

- examples/todo-app-tutorial/package.json
- packages/tooling/fast-figma-plugin-msft/package.json
- packages/tooling/fast-tooling-react/package.json
- packages/tooling/fast-tooling-wasm/package.json
- packages/tooling/fast-tooling/package.json
- packages/utilities/fast-animation/package.json
- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/package.json
- packages/web-components/fast-element/package.json
- packages/web-components/fast-foundation/package.json
- sites/fast-color-explorer/package.json
- sites/fast-component-explorer/package.json
- sites/fast-creator/package.json
- sites/fast-tooling-examples/package.json
- sites/fast-website/package.json
- sites/website/src/docs/components/getting-started.md
- yarn.lock
This PR updates webpack across the repository. Certain webpack versions included an issue which can cause builds to hang. It appears that certain contributor pull requests were somehow getting this version installed. This should address the issue and unify the webpack versions across the repo.
> chore: update webpack across repository

- packages/web-components/fast-components/src/badge/badge.definition.ts
- sites/fast-component-explorer/app/fast-components/configs/fast-badge.ts
- sites/site-utilities/src/definitions/native/index.ts
- sites/site-utilities/src/definitions/native/style.definition.ts
- Fixes `circular` attribute to be data type boolean.
- Adds a style definition for css variables that allow badge to render properly
Closes: #3900  
> fix: badge example in component explorer

- packages/tooling/fast-tooling-react/package.json
- packages/web-components/fast-components/docs/api-report.md
- yarn.lock
This PR upgraded packages with known vulnerabilities.
closes #3870 #3849 #3843 
Remediates security vulnerabilities found by dependabots
> Update to remediate high severity vulnerabilities in dependencies

- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/slider/slider.template.ts
This PR corrects aria attributes on slider which did not have an explicit and valid value set.
> fix: aria attributes for slider should have explicit values

- packages/tooling/fast-tooling/src/data-utilities/message-system-utility-action.ts
- packages/tooling/fast-tooling/src/data-utilities/message-system-utility.ts
- packages/tooling/fast-tooling/src/data-utilities/shortcut-action.ts
- packages/tooling/fast-tooling/src/data-utilities/shortcuts.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/shortcuts.ts
This refactor adds an action getter to allow any action to be called from a message utility.
> refactor: make some changes within shortcuts and abstract message system utility to accomodate an action getter

- packages/web-components/fast-foundation/src/accordion-item/accordion-item.spec.ts
- packages/web-components/fast-foundation/src/accordion/accordion.spec.ts
- packages/web-components/fast-foundation/src/anchor/anchor.spec.ts
- packages/web-components/fast-foundation/src/badge/badge.spec.ts
- packages/web-components/fast-foundation/src/button/button.spec.ts
- packages/web-components/fast-foundation/src/checkbox/checkbox.spec.ts
- packages/web-components/fast-foundation/src/dialog/dialog.spec.ts
- packages/web-components/fast-foundation/src/divider/divider.spec.ts
- packages/web-components/fast-foundation/src/flipper/flipper.spec.ts
- packages/web-components/fast-foundation/src/form-associated/form-associated.spec.ts
- packages/web-components/fast-foundation/src/menu-item/menu-item.spec.ts
- packages/web-components/fast-foundation/src/menu/menu.spec.ts
- packages/web-components/fast-foundation/src/progress-ring/progress-ring.spec.ts
- packages/web-components/fast-foundation/src/progress/progress.spec.ts
- packages/web-components/fast-foundation/src/radio-group/radio-group.spec.ts
- packages/web-components/fast-foundation/src/radio/radio.spec.ts
- packages/web-components/fast-foundation/src/slider-label/slider-label.spec.ts
- packages/web-components/fast-foundation/src/slider/slider.spec.ts
- packages/web-components/fast-foundation/src/switch/switch.spec.ts
- packages/web-components/fast-foundation/src/tab-panel/tab-panel.spec.ts
- packages/web-components/fast-foundation/src/tab/tab.spec.ts
- packages/web-components/fast-foundation/src/tabs/tabs.spec.ts
- packages/web-components/fast-foundation/src/text-area/text-area.spec.ts
- packages/web-components/fast-foundation/src/text-field/text-field.spec.ts
- packages/web-components/fast-foundation/src/tree-item/tree-item.spec.ts
- packages/web-components/fast-foundation/src/tree-view/tree-view.spec.ts
This PR adds tests for all components. There are a few components which require specific tests as it pertains to keyboard navigation, focus management, etc which I'll create TODO's for. Unfortunately, I was having trouble with the test runner bringing focus to anything but the test body. We'll need to take those in follow-up issues.
We had no tests. We now have tests.
> chore: add unit tests for fast-foundation components

- packages/tooling/fast-tooling/src/data-utilities/monaco-adaptor-action.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/monaco-adaptor-action.ts
- packages/tooling/fast-tooling/src/data-utilities/monaco-adaptor.spec.md
- packages/tooling/fast-tooling/src/data-utilities/monaco-adaptor.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/monaco-adaptor.ts
Adds an adaptor for the monaco editor and actions, these will register themselves with the `MessageSystem` and update when the `DataDictionary` is updated. They will also provide hooks to use for when the monaco editor models value has been updated.
Relies on #3898, #3916 to pass the build.
Closes #3562
> feat: add monaco adaptor and adaptor actions

- packages/web-components/fast-foundation/src/tabs/README.md
Tabs documentation was using a *lightweight* anchor style in a list of anchors, resulting in a mismatch in visual alignment between list item indicators and the anchor itself. This happens because the *lightweight* style isn't intended to be used inline in text. This PR replaces the *lightweight* style with a *hypertext* style, which *is* intended to be used inline.
closes #3816
> chore: correct tabs examples in documentation

- examples/todo-app-tutorial/package.json
- sites/fast-website/package.json
- yarn.lock
Webpack depends on selfsigned which has a vulnerability in 1.10.7.  This updates webpack across our solution to use the latest and resolves this vulnerability.  Webpack does upgrade to a safe version, with this PR, after running yarn.
Resolve security vulnerability documented https://github.com/microsoft/fast/network/alert/yarn.lock/node-forge/open and the fix documented https://github.com/webpack/webpack-dev-server/pull/2740
> chore: update to resolve sec vulnerability in node-forge

- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/tabs/tabs.spec.ts
- packages/web-components/fast-foundation/src/tabs/tabs.ts
Changing the `activeid` attribute now update the selected tab.
Closes: #3925 
> fix: active id should update selected tab

- sites/fast-component-explorer/app/css/style.css
- sites/fast-component-explorer/app/explorer-region.tsx
- sites/fast-component-explorer/app/explorer.props.ts
- sites/fast-component-explorer/app/explorer.style.ts
- sites/fast-component-explorer/app/explorer.tsx
- sites/fast-component-explorer/app/index.tsx
- sites/fast-component-explorer/app/site-footer.tsx
- sites/fast-component-explorer/package.json
- sites/site-utilities/src/components/direction-switch/direction-switch.props.ts
- sites/site-utilities/src/components/direction-switch/index.tsx
- sites/site-utilities/src/components/logo/index.tsx
- sites/site-utilities/src/components/logo/logo.props.ts
- sites/site-utilities/src/components/style.ts
- sites/site-utilities/src/components/theme-selector/index.tsx
- sites/site-utilities/src/components/theme-selector/theme-selector.props.ts
- sites/site-utilities/src/components/transparency-toggle/index.tsx
- sites/site-utilities/src/components/transparency-toggle/transparency-toggle.props.ts
Refactors the layout of the component explorer site and adds mobile styling & logic.
This allows component explorer to be viewed on mobile in a typical mobile layout.
Main view:
Navigation pane active:
Form pane active:
> feat: add mobile view to the component explore site

- packages/tooling/fast-tooling/app/examples/monaco/data-dictionary-config.ts
- packages/tooling/fast-tooling/app/examples/monaco/index.html
- packages/tooling/fast-tooling/app/examples/monaco/index.ts
- packages/tooling/fast-tooling/app/examples/monaco/monaco-editor-config.ts
- packages/tooling/fast-tooling/app/examples/monaco/schema-dictionary.ts
- packages/tooling/fast-tooling/package.json
- packages/tooling/fast-tooling/tsconfig.json
This adds an example of the Monaco editor working with a few form elements and the `MessageSystem` and `MonacoAdaptor` to create 2 way editing between Monaco and the `MessageSystem`.
Will not pass build until #3917 has been merged.
This allows a certain amount of manual debugging to take place when experimenting with changes to the `MonacoAdaptor`.
> chore: add manual testing in the tooling test app for two way editing

- sites/fast-component-explorer/app/index.tsx
Fixes an issue where styles were not being included in the prod bundle of the component explorer.
> chore: use require instead of import for component explorer styles

- packages/web-components/fast-foundation/src/tooltip/README.md
cleanup on the tooltip read me file
Format to match other components
**Adding or modifying component(s) in `@microsoft/fast-components` checklist*
> fix: clean up tooltip read me

- sites/fast-component-explorer/app/css/style.css
- sites/fast-component-explorer/app/explorer.tsx
Updates the styling for the content area so that selecting diffferent tabs in the dev tools does not cause the height of the page to change.
Resolves #3958 
Resolves #3962
> fix: update formatting to resolve an issue where the dev tools panel would resize

- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/index.ts
The `@microsoft/fast-components` package is missing the progress ring component export.
Resolves #3963
> fix: re-export the progress ring component

- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/tree-item/tree-item.ts
#Description
* Removed case for space key in keydown handler
* verified we are now matching aria spec as dictated here: https://w3c.github.io/aria-practices/#keyboard-interaction-23
> fix: for tree-view removing space bar key handler and match aria spec

- packages/tooling/fast-tooling/src/data-utilities/monaco-adaptor.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/monaco-adaptor.ts
This normalizes values coming in from monaco to de-format them so that extra newlines and leading spaces are not counted as "real values".
Will result in the PR #3949 being removed from "on hold" status.
> fix: removes newlines and leading spaces from returned monaco value

- packages/tooling/fast-tooling/src/data-utilities/monaco-adaptor.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/monaco-adaptor.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.props.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.spec.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.ts
- sites/fast-component-explorer/app/fast-components/configs/fast-accordion.ts
This will allow a dictionary id to be set and default to the root dictionary id.
When initialization is run it may need to preserve the current active dictionary id, as in the monaco adapter. Otherwise the data navigation will be reset to root each time which can cause problems in some other components that rely on it for form rendering.
> feat: allow a dictionary id to be set during initialization

- packages/tooling/fast-tooling/src/data-utilities/monaco-adaptor.ts
- packages/web-components/fast-components/src/accordion/accordion.definition.ts
- sites/fast-component-explorer/app/explorer.tsx
- sites/site-utilities/src/schemas/text.schema.ts
This change allows 2 way editing via the new `MonacoAdaptor` in the Component explorer.
> feat: add monaco adaptor to component explorer site

- sites/fast-component-explorer/app/explorer.tsx
- sites/fast-component-explorer/app/fast-components/configs/fast-accordion.ts
Removes custom as a dropdown option as it functionally does nothing once selected. This change also fixes a typo in a config file for accordion and ensures that data is unique for generated configs.
Resolves #3884
> chore: fix an issue with the accordion config, remove custom as a dropdown option

- packages/web-components/fast-foundation/src/tooltip/README.md
Copy paste error in tooltip read me.
Good docs are good.
> fix: typo in tooltip doc

- packages/web-components/fast-foundation/src/skeleton/README.md
Removes live editor syntax for docusaurus due to inline styles.
> chore: remove live editor for skeleton example on docs

- packages/tooling/fast-tooling/CHANGELOG.md
- packages/tooling/fast-tooling/app/examples/monaco/index.ts
- packages/tooling/fast-tooling/app/index.html
- packages/tooling/fast-tooling/src/data-utilities/monaco-adapter-action.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/monaco-adapter-action.ts
- packages/tooling/fast-tooling/src/data-utilities/monaco-adapter.spec.md
- packages/tooling/fast-tooling/src/data-utilities/monaco-adapter.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/monaco-adapter.ts
- packages/web-components/fast-components/CHANGELOG.md
- packages/web-components/fast-components/docs/api-report.md
- sites/fast-component-explorer/CHANGELOG.md
- sites/fast-component-explorer/app/explorer.tsx
- sites/site-utilities/CHANGELOG.md
Renames "adaptor" to "adapter".
Resolves #3961 
> fix: rename instances of adaptor to adapter

- packages/web-components/fast-foundation/src/tabs/tabs.ts
We were overthinking direction in tabs ;). No need for direction check.
> fix: tabs directional arrow key bug

- sites/fast-component-explorer/app/explorer.props.ts
- sites/fast-component-explorer/app/explorer.style.ts
- sites/fast-component-explorer/app/explorer.tsx
- sites/fast-component-explorer/app/index.tsx
- sites/fast-component-explorer/app/preview.tsx
- sites/site-utilities/package.json
- sites/site-utilities/src/components/editor/editor.props.ts
- sites/site-utilities/src/components/editor/editor.style.css
- sites/site-utilities/src/components/editor/index.tsx
- sites/site-utilities/src/components/index.ts
- sites/site-utilities/src/components/logo/logo.props.ts
- sites/site-utilities/src/schemas/index.ts
- sites/site-utilities/tsconfig.json
- yarn.lock
This change removes core logic from the explorer and places it in a new abstract class `Editor` so that it can be shared with the creator site.
It includes the following changes:
- Add declarations to the site-utilities for typescript (see tsconfig update)
- Update `width` and `height` to the more accurate `viewerWidth` and `viewerHeight`
- Remove any global styles from jssStylesheets and place them in the `.css` file for the `Editor`
- Remove any logic that will need to be shared with the Creator and place it into the `Editor` class
The refactor should not have changed any of the site functionality.
> chore: refactor logic from explore site into a site-utilities abstract component

- packages/web-components/fast-element/docs/guide/defining-elements.md
Based on some community feedback, I've expanded the section of the docs on working with and without decorators.
> docs(fast-element): add more detailed notes on decorator use

- sites/fast-component-explorer/build/convert-scenarios.js
- sites/fast-component-explorer/package.json
- sites/fast-component-explorer/webpack.common.js
- yarn.lock
This adds a build step to convert the newly added scenario `html` files into javascript files with exports that can be read by the component explorer site. The html from these files be converted in the component explorer using a data mapping utility from `@microsoft/fast-tooling` into the `DataDictionary` format after they are imported to the site. The reason this can't be done in the build script is due to the fact that the `@microsoft/fast-tooling` project only exports in the ES6 format.
Continues the work on #3930 
> chore: add a build script for scenarios

- packages/utilities/fast-web-utilities/README.md
Removes the `isRTL()` documentation because that function doesn't exist. AFAIK it never has, so this was likely here by mistake.
closes #3972
> chore: remove documentation entry for function that does not exist

- packages/web-components/fast-components/src/flipper/flipper.definition.ts
This change updates the incorrect assignment of the `direction` attribute from `boolean` to `string` in the component definition.
Resolves #4045 
> fix: updates the definition for the flipper component for the direction attribute

- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/dialog/dialog.spec.ts
- packages/web-components/fast-foundation/src/dialog/dialog.ts
This PR adds methods for showing and hiding the dialog programatically.
closes #3998
> feat: add show and hide methods to dialog

- packages/web-components/fast-components/src/tab-panel/index.ts
- packages/web-components/fast-components/src/tab/index.ts
Removes duplicate exports causing circular dependencies
> fix: remove duplicate exports causing circular dependencies

- .eslintignore
Ensure spec files aren't linted by ignoring them.
> chore: ensure spec files are ignored for eslint

- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
Fixed background and fill color on the fast-frame adaptive UI tab. This fixes the issue that the icon tab disappears when hovering in high contrast.
before
after
> fix: add high contrast color for adaptive UI tab, on hover

- sites/fast-component-explorer/app/explorer.tsx
An issue was found where a runtime error would be thrown on the initial route of the component explorer due to the data dictionary not be initialized correctly.
> chore: fix initial route so that the data dictionary is accurate

- packages/web-components/fast-components/src/card/README.md
- packages/web-components/fast-components/src/card/card.definition.ts
- packages/web-components/fast-components/src/card/card.styles.ts
- packages/web-components/fast-components/src/card/fixtures/card.html
- packages/web-components/fast-components/src/card/index.ts
Closes: #3940
`fast-card` extends design system provider so controls inside have proper Design system context.
After:
> fix: fast card should be design system provider

- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-foundation/src/tree-item/tree-item.spec.ts
- packages/web-components/fast-foundation/src/tree-item/tree-item.template.ts
> fix: ensure tree items with children have a value for aria-expanded

- packages/web-components/fast-components/src/card/index.ts
Removes reference to `fast-components-styles-msft` and updated to use FAST versions.
> fix: Updated Design System reference in fast-card

- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/card/index.ts
Removes circular dependencies in Card.
> fix: remove Card circular dependencies

- packages/web-components/fast-components/src/radio-group/radio-group.styles.ts
Changing radio group orientation to vertical seems to have no effect on layout. This change fixes that issue.
Before:
After:
> fix: radio group orientation "vertical" broken

- packages/web-components/fast-foundation/src/tabs/tabs.spec.ts
- packages/web-components/fast-foundation/src/tabs/tabs.ts
Some old logic was colliding with the recent work that was done to prevent double syncing issues with active indicator.
Closes: #4111 
After:
> fix: active indicator no longer animating

- packages/web-components/fast-components/src/listbox-option/listbox-option.styles.ts
- packages/web-components/fast-components/src/menu-item/menu-item.styles.ts
- packages/web-components/fast-components/src/select/select.styles.ts
- packages/web-components/fast-components/src/slider-label/slider-label.styles.ts
- packages/web-components/fast-components/src/text-field/text-field.styles.ts
closes #4132 and addresses all other components not reflecting body font.
> fix: ensure all components opt into body font

- packages/tooling/fast-tooling/build/generate-mdn-data-files.js
- packages/tooling/fast-tooling/src/css-data.js
- packages/tooling/fast-tooling/src/css-data.properties.ts
- packages/tooling/fast-tooling/src/css-data.syntax.ts
- packages/tooling/fast-tooling/src/css-data.types.ts
- packages/tooling/fast-tooling/src/data-utilities/mapping.mdn-data.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/mapping.mdn-data.ts
This change adds and updates the MDN mappings to include syntaxes, using a similar model as the CSS properties mapping as the syntaxes are using the same patterns.
This is not a full resolution of all syntaxes but serves as a good starting point to be refined.
This is to be used when auto-generating sub controls within the currently in-progress CSS properties control.
> feat: add a mapping of MDN syntaxes to be used as reference

- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/button/index.ts
- packages/web-components/fast-element/docs/api-report.md
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/button/button.template.ts
- packages/web-components/fast-foundation/src/button/button.ts
> add default slot change method

- packages/web-components/fast-foundation/src/utilities/style/direction.ts
This removes references to `shadowRoot` in the `direction` utility so it will work with closed shadowRoot components, like FluentUI. Verified this fixes tree item `rtl` bugs in fluentUI.
FluentUI Screen grab with updated code in node modules:
> fix: remove shadowRoot in direction utility

- packages/tooling/fast-tooling-react/app/pages/form.tsx
- packages/tooling/fast-tooling-react/app/pages/form/index.ts
- packages/tooling/fast-tooling-react/package.json
- packages/tooling/fast-tooling-react/src/__tests__/schemas/control-plugin.schema.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css-ref.props.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css-ref.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.props.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.style.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.property.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.props.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.syntax.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.type.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.value.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/index.ts
- packages/tooling/fast-tooling-react/src/form/custom-elements.d.ts
- packages/tooling/fast-tooling-react/src/utilities/web-components/pragma.ts
- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-foundation/docs/api-report.md
- yarn.lock
This work provides the structure for deciphering MDN data structures provided by `@microsoft/fast-tooling` into generated UI. It also integrates web components from `@microsoft/fast-components`.
This work is going into the `features/form-custom-control` branch until such time that it is ready to merge to the main repository branch.
Provides the foundational work on #3773
> feat: add CSS property control

- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css-ref.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.props.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.tsx
- packages/tooling/fast-tooling-react/src/form/custom-elements.d.ts
- yarn.lock
Converts the `<select>` to `<fast-select>`
Solves part of the work required for #4174
> fix: convert select to fast-select in the CSS control

- packages/web-components/fast-foundation/src/utilities/apply-mixins.ts
Thx to @EisenbergEffect for helping solve this
Should address https://github.com/microsoft/fluentui/issues/16121
> fix: update applyMixin function to ensure metadata for attrs are copied and applied correctly

- packages/web-components/fast-components/src/tooltip/README.md
There is a broken link in the tooltip `Guidance` page
> docs: broken link in tooltip page

- .github/workflows/ci-os-validation.yml
- [x ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [x ] I have added a new component
- [x ] I have added tests for my changes.
> os ci validation

- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.props.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.type.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.value.tsx
This change adds MDN docs specified information (but not provided by the mdn-data package) as data structures to be taken advantage of when creating UI for number-fields, text-fields, CSS functions and multiple values.
- Number-fields will specify any appended units
- Multiple values will specify the number of values and split type
- Functions will specify the name of the function (for value re-mapping e.g. "foo" supplied with function name "bar" will return "bar(foo)")
This provides a framework for more precise UI to be used and for values to be auto-formatted where possible. It will also allow the use of `<fast-number-field>` for a variety of related components.
> feat: add default control configurations for types and uncategorized values with mappings

- .github/workflows/ci-weekly.yml
- .prettierignore
- .prettierrc
- package.json
- sites/fast-color-explorer/app/site-footer.tsx
- sites/fast-component-explorer/app/site-footer.tsx
- sites/fast-creator/app/site-footer.tsx
- sites/fast-website/package.json
- sites/fast-website/rollup.config.js
- yarn.lock
- make sure prettier handles line endings
- add ignored prettier files to top level
- replace `rollup-plugin-ejs` plugin with `rollup-plugin-jst` to remove unnecessary and deprecated dependencies
> (ci-validation) run root-level prettier commands with lerna

- .github/workflows/ci-weekly.yml
fixing windows Platform validation
- [x ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [x ] I have added tests for my changes.
> bug:os-validation

- .github/workflows/ci-weekly.yml
> Os validation

- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/utilities/index.ts
- packages/web-components/fast-foundation/src/utilities/property-stylesheet-behavior.ts
Closes: #4237 
Adds a behavior that allows to attach styles based on any property. Adds a behavior that attaches styles based on appearance.
> feat: Create a behavior for attaching component styles based on an appearance

- packages/web-components/fast-components/src/badge/badge.styles.ts
Fixed badge style typo
Should be `line-height` instead of `height`.
> fix: badge style var typo

- packages/web-components/fast-components/src/skeleton/fixtures/base.html
- packages/web-components/fast-components/src/skeleton/skeleton.styles.ts
Add high contrast color to the background and border of the component. 
Also added a class to the examples that are using the pattern and SVG. This is to set a color on the background of the component in forced-colors mode.  Due to the pattern and inline-svg having a hardcoded color of white, I overwrote the component's background-color to black so the component looks correct in both high contrasts white and black themes.
black theme
white theme
> fix: add forced-colors to skeleton component for high contrast

- packages/web-components/fast-foundation/src/accordion-item/accordion-item.template.ts
Set `aria-hidden="true"` to keep the SVGs from being focused.
> fix: add aria hidden to true on icon in the accordion item component

- .github/workflows/ci-playwright.yml
- playwrightTest/index.js
Cross browser testing with playwright
create ci-playwright.yml for automation instruction
create playwrightTest folder to install playwright dependencies
create index.js for coding the test for cross browsing different os
This will automate cross browser testing as new features being added to the application
This will ensure the application support multiple (major) browsers
> Playwright

- packages/web-components/fast-components/src/accordion-item/accordion-item.styles.ts
This changes the the `accordion-item` content region to be `display: block` when item is expanded. 
> fix: change accordion item region to display block

- sites/website/src/docs/design-systems/fast-frame.md
Fixes reference to the `accentBaseColor` property. It was incorrectly referenced as `accentPaletteBaseColor`.
> chore: correct reference to design system property name

- sites/fast-component-explorer/app/explorer.tsx
- sites/fast-creator/app/creator.tsx
- sites/site-utilities/src/components/logo/index.tsx
- sites/site-utilities/src/components/logo/logo.props.ts
This removes the import of `ColorRecipe` from the deprecated styles package and removes the prop `backgroundColor` which was not used.
Resolves #4272
> chore: remove unused ColorRecipe reference and backgroundColor prop

- packages/tooling/fast-tooling-react/app/pages/form.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.props.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.tsx
This change switches from auto-importing all standard CSS data into the CSS custom control to a prop so that any CSS data can be passed.
This will shrink the package size needed to use the CSS control.
> feat: add a prop for CSS data to be injected to the CSS control

- packages/web-components/fast-foundation/src/tooltip/tooltip.spec.md
> docs(tooltip): broken link in docs

- packages/web-components/fast-foundation/package.json
- yarn.lock
Adds the `lodash-es` dependency as it's been noticed that it was missing in https://github.com/microsoft/fast/issues/3825
> chore: add missing lodash-es deps

- sites/fast-website/src/public/footer.ejs
- sites/website/sidebars.js
- yarn.lock
Adds data grid to the docs site and updates the copyright date to 2021 in the footer of the webiste.
> chore: add data grid to docs site and update website copyright date

- .github/workflows/ci-weekly.yml
Change trigger event on ci-weekly
The ci-weekly is being triggered for each pull-request and push to validate cross-platform
Remove on push and on pull-request Triggers. The ci-weekly will now be triggered on weekly schedule
Fulfill the requirement of cross-platform 
Ensure cross-platform on windows, linux and mac
> chore: change ci-weekly.yml trigger event to on schedule

- .gitignore
- package.json
- yarn.lock
Typedoc was enumerated as a dependency but never used. It also depends on a package with a known security vulnerability. 
> chore: remove unused typedoc dependency

- packages/tooling/fast-tooling-react/app/pages/form.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css-ref.props.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css-ref.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.props.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.property.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.props.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.syntax.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.type.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/css/index.ts
- packages/tooling/fast-tooling-react/src/form/custom-elements.d.ts
Uses the `<fast-number-field>` web component from `@microsoft/fast-components` package for the CSS types `<number>` and `<integer>`.
> feat: use the fast-number-field component for the CSS number type

- packages/tooling/fast-tooling-react/README.md
- packages/tooling/fast-tooling-react/app/pages/form.tsx
- packages/tooling/fast-tooling-react/app/pages/form/index.ts
- packages/tooling/fast-tooling-react/src/__tests__/schemas/category.schema.ts
- packages/tooling/fast-tooling-react/src/__tests__/schemas/index.ts
- packages/tooling/fast-tooling-react/src/form/controls/control.section-link.spec.tsx
- packages/tooling/fast-tooling-react/src/form/controls/control.section.spec.tsx
- packages/tooling/fast-tooling-react/src/form/controls/control.section.tsx
- packages/tooling/fast-tooling-react/src/form/controls/utilities/control-switch.spec.tsx
- packages/tooling/fast-tooling-react/src/form/controls/utilities/control-switch.tsx
- packages/tooling/fast-tooling-react/src/form/controls/utilities/dictionary.spec.tsx
- packages/tooling/fast-tooling-react/src/form/form.props.ts
- packages/tooling/fast-tooling-react/src/form/form.tsx
- packages/tooling/fast-tooling-react/src/form/templates/template.control.bare.spec.tsx
- packages/tooling/fast-tooling-react/src/form/templates/template.control.single-line.spec.tsx
- packages/tooling/fast-tooling-react/src/form/templates/template.control.standard.spec.tsx
- packages/tooling/fast-tooling-react/src/form/templates/template.control.utilities.props.tsx
- packages/tooling/fast-tooling-react/src/form/templates/template.control.utilities.tsx
This adds categories into the form via a passed property `categories`. This can be configured for multiple schemas using the schema id (or $id). For now this will be placed into a feature branch as more functionality, such as collapsibility, and styling, must be applied.
Begins to address #2575
> feat: allow categories to wrap properties in objects

- sites/fast-component-explorer/app/explorer.tsx
An issue occurs during the first load of the explorer site which causes the height of the iframe to be incorrect. This fix addresses it by using the same logic the resize functionality uses to calculate the height.
> chore: address an issue where the height was not resized properly during first load

- packages/tooling/fast-tooling/src/message-system/message-system.props.ts
- packages/tooling/fast-tooling/src/message-system/message-system.spec.ts
- packages/tooling/fast-tooling/src/message-system/message-system.ts
- packages/tooling/fast-tooling/src/message-system/webworker.spec.md
The postMessage used by the message system can only pass JSON data back and forth, since there may be a need to pass more complex functionality between registered services, the message system can now store additional config objects for this purpose.
> feat: allow the message system to store and retrieve configs from registered services

- packages/tooling/fast-tooling/app/examples/shortcuts/data-dictionary-config.ts
- packages/tooling/fast-tooling/app/examples/shortcuts/index.html
- packages/tooling/fast-tooling/app/examples/shortcuts/index.ts
- packages/tooling/fast-tooling/app/examples/shortcuts/schema-dictionary.ts
- packages/tooling/fast-tooling/app/examples/shortcuts/webpack.common.js
- packages/tooling/fast-tooling/app/examples/shortcuts/webpack.dev.js
- packages/tooling/fast-tooling/app/index.html
This change adds a manual test environment to test the shortcuts service. It can be run in the fast-tooling package with `yarn start`.
Reliant on #4355, #4356
> chore: add a browser manual test environment for the shortcuts service

- packages/tooling/fast-tooling/src/message-system/data.props.ts
- packages/tooling/fast-tooling/src/message-system/data.spec.ts
- packages/tooling/fast-tooling/src/message-system/data.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.props.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.spec.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.ts
- packages/tooling/fast-tooling/src/message-system/navigation.ts
This change allows sending to the message system a request to add display text into the data dictionary which is also used by the navigation dictionary. This will allow the message system to make updates that affect the UI in the `<Navigation />` and `<Form />` React components in `@microsoft/fast-tooling-react`.
Partially solves #4352
> feat: allow users to update display text for a data dictionary and navigation dictionary

- packages/web-components/fast-foundation/src/listbox-option/README.md
- packages/web-components/fast-foundation/src/listbox/README.md
- sites/website/package.json
- sites/website/src/docs/components/getting-started.md
This PR fixes a few broken links in the documentation site.
It also aligns the local development npm script name for the documentation site with the script name used throughout the rest of the project.
fixes #4370
> chore: fixes incorrect documentation links

- sites/fast-component-explorer/app/explorer.tsx
- sites/fast-creator/app/creator.props.ts
- sites/fast-creator/app/creator.tsx
- sites/site-utilities/package.json
- sites/site-utilities/src/components/accent-color-picker/index.tsx
- sites/site-utilities/src/components/dimension/index.tsx
- sites/site-utilities/src/components/editor/editor.props.ts
- sites/site-utilities/src/components/editor/editor.style.css
- sites/site-utilities/src/components/editor/index.tsx
- sites/site-utilities/src/components/logo/index.tsx
- sites/site-utilities/src/components/style.ts
- sites/site-utilities/src/components/theme-selector/index.tsx
- sites/site-utilities/src/components/theme-selector/theme-selector.props.ts
- sites/site-utilities/src/custom-elements.d.ts
Removing / replacing some of the dependencies from Site Utilities, Creator and Component Explorer sites. This does not replace all dependencies in Creator or Explorer but does completely remove dependencies from Site Utilities.
Creator Screenshot:
Explorer Screenshot:
Resolves the following:
Fixes: #4262
Fixes: #4264 
Fixes: #4265 
Fixes: #4266 
Fixes: #4268 
Fixes: #4271 
> chore: removing fast-component-react-msft dependencies

- packages/tooling/fast-tooling-react/src/form/controls/control.section.props.ts
- packages/tooling/fast-tooling-react/src/form/controls/control.section.spec.tsx
- packages/tooling/fast-tooling-react/src/form/controls/control.section.style.ts
- packages/tooling/fast-tooling-react/src/form/controls/control.section.tsx
This change adds styling to form categories changing from the default `<fieldset>` and `<legend>` which displays as:
To:
Continues to address #2575
> fix: apply styling to categories

- .github/workflows/ci-weekly.yml
We are updating CI-Weekly on Schedule and On push to Master to be trigger, Removing on pull-request or feature triggers. It is causing unnecessary build.
remove on pull_request and features
Unnecessary triggers 
solve efficiency 
> chore: update to trigger action on master from weekly schedule 

- .github/workflows/ci-weekly.yml
- package.json
- packages/web-components/fast-components/package.json
- yarn.lock
Playwight test is failing likely related to version 1.9.0
downgrade playwright to version 1.8.0
Ensure cross-browser validation
> bug: downgrade playwright to v1.8.0 from v1.9.0

- packages/tooling/fast-tooling-react/README.md
- packages/tooling/fast-tooling-react/app/pages/navigation.tsx
- packages/tooling/fast-tooling-react/src/navigation/navigation.props.ts
- packages/tooling/fast-tooling-react/src/navigation/navigation.spec.tsx
- packages/tooling/fast-tooling-react/src/navigation/navigation.tsx
This change allows the option of specifying JSON schema types that the `<Navigation />` component will render. This results in a simpler UI when unnecessary `type`s are being shown.
Closes #4351 
> feat: allow the specification of types to display in the Navigation

- packages/tooling/fast-tooling-react/README.md
- packages/tooling/fast-tooling-react/src/form/controls/control.section.style.ts
- packages/tooling/fast-tooling-react/src/form/controls/control.section.tsx
- sites/fast-component-explorer/app/explorer.tsx
- sites/fast-creator/app/creator.tsx
- sites/site-utilities/src/components/categories.ts
- sites/site-utilities/src/components/index.ts
This change adds the categories prop to the README as documentation, initial categories for the `<fast-button>` as well as a few minor styling tweaks needed for the single line template control collision with the floated `<legend>`.
> chore: add categories to documentation and initial categories for a button component with some minor style tweaks to account for inline controls

- sites/fast-component-explorer/app/app.tsx
- sites/fast-component-explorer/app/explorer-region.tsx
- sites/fast-component-explorer/app/explorer.props.ts
- sites/fast-component-explorer/app/explorer.style.ts
- sites/fast-component-explorer/app/explorer.tsx
- sites/fast-component-explorer/app/web-components/index.tsx
- sites/fast-creator/app/creator.tsx
- sites/fast-creator/app/web-components/index.tsx
- sites/site-utilities/src/components/dimension/index.tsx
- sites/site-utilities/src/components/editor/editor.style.css
- sites/site-utilities/src/icons/rotate.tsx
Replacing Select and ActionToggle instances in Explorer and Creator with FASTSelect and FASTButton as well as some other cleanup.
Explorer Screenshot:
Note Select in top menu and expand button under the preview area.
Creator Screenshot:
Note the expand button under the preview area.
Fixes: #4267 
Fixes: #4269 
> chore: replacing select and actiontoggle react components with fastselect and fastbutton

- sites/fast-creator/app/creator.tsx
Adds the `types` prop to the `<Navigation />` component implementation in the Creator site. This results in direct nesting of nodes and removal of all other data types (such as string, null, number etc which complicates the navigation).
> chore: add types to Creator for direct node nesting in the navigation

- packages/tooling/fast-tooling-react/README.md
- packages/tooling/fast-tooling-react/app/pages/form.tsx
- packages/tooling/fast-tooling-react/src/__tests__/schemas/category.schema.ts
- packages/tooling/fast-tooling-react/src/form/controls/control.section.props.ts
- packages/tooling/fast-tooling-react/src/form/controls/control.section.spec.tsx
- packages/tooling/fast-tooling-react/src/form/controls/control.section.style.ts
- packages/tooling/fast-tooling-react/src/form/controls/control.section.tsx
- packages/tooling/fast-tooling-react/src/form/controls/utilities/form.tsx
- packages/tooling/fast-tooling-react/src/form/form.props.ts
This adds an expand/collapse button to categories in the `<Form />`.
Expanded:
Collapsed:
Closes #2575
Closes #2530
> feat: add expand/collapse to categories

- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/menu-item/fixtures/menu-item.html
- packages/web-components/fast-components/src/menu-item/menu-item.definition.ts
- packages/web-components/fast-components/src/menu-item/menu-item.styles.ts
- packages/web-components/fast-components/src/menu/fixtures/menu.html
- packages/web-components/fast-components/src/menu/menu.styles.ts
- packages/web-components/fast-components/src/menu/scenarios/index.html
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/menu-item/menu-item.template.ts
- packages/web-components/fast-foundation/src/menu-item/menu-item.ts
- packages/web-components/fast-foundation/src/menu/menu.spec.md
- packages/web-components/fast-foundation/src/menu/menu.template.ts
- packages/web-components/fast-foundation/src/menu/menu.ts
This change adds support for nested menus to the menu and menu-item components.  
```html
<fast-menu>
<fast-menu-item>
Menu item 1
<fast-menu slot="submenu">
<fast-menu-item>Nested Menu item 1.1</fast-menu-item>
<fast-menu-item>Nested Menu item 1.2</fast-menu-item>
<fast-menu-item>Nested Menu item 1.3</fast-menu-item>
</fast-menu>
</fast-menu-item>
<fast-menu-item>
Menu item 2
</fast-menu-item>
<fast-menu-item>
Menu item 3
<fast-menu slot="submenu">
<fast-menu-item>
Nested Menu item 3.1
<fast-menu slot="submenu">
<fast-menu-item>Nested Menu item 3.1.1</fast-menu-item>
<fast-menu-item>Nested Menu item 3.1.2</fast-menu-item>
<fast-menu-item>Nested Menu item 3.1.3</fast-menu-item>
</fast-menu>
</fast-menu-item>
<fast-menu-item>
Nested Menu item 3.2
<fast-menu slot="submenu"> …
```
> feat: add nested menu support

- .github/workflows/ci-weekly.yml
After merging things to master, playwright module was missing again. On the initial set-up, playwright was running on CI. We have removed because it sounds unnecessary. To insure we have playwright module ready before doing any test, we need playwright running on CI. 
cd packages/web-components/fast-components
npm install playwright
yarn test-chromium:pw 
yarn test-firefox:pw 
yarn test-webkit:pw
cause of failure due to playwright module not found.
> Bug: added install playwright to CI

- packages/web-components/fast-components/src/menu-item/menu-item.styles.ts
- packages/web-components/fast-components/src/menu/menu.styles.ts
Aligning `menu-item` to the latest design, by removing the accent color.
menu-item (hover)
menu-item (focus)
menu-item with radio and checkbox selected
> chore: update background color on menu item

- packages/tooling/fast-figma-plugin-msft/package.json
- packages/web-components/fast-components/package.json
- packages/web-components/fast-element/package.json
- packages/web-components/fast-foundation/package.json
- sites/fast-website/package.json
This change updates the version of `@microsoft/fast-element` package to be an alpha version of 1.0.0.
Lerna seems to make it largely impossible to increment from a 0.x.y version to a 1.0.0 package version with conventional commits (https://github.com/lerna/lerna/issues/2325).
By setting an alpha package version, we can use the `--conventional-graduate=@microsoft/fast-element` along with `--conventional-commits` when we publish to increment fast-element to 1.0.0 *and* have accurate changelogs. AFAIK this is the only way to get fast-element to 1.0.0 with changelogs.
once this goes in, to publish we'll want to run:
```
lerna publish --conventional-commits --conventional-graduate=@microsoft/fast-element
```
**Adding or modifying component(s) in …
> chore: update fast-element version

- packages/web-components/fast-components/src/switch/switch.definition.ts
- sites/site-utilities/src/components/categories.ts
This PR categorizes "advanced" attrs for the tooling on the site.
> chore: add component category for advanced attrs to site utilities

- packages/tooling/fast-tooling-react/README.md
- packages/tooling/fast-tooling-react/app/pages/form.tsx
- packages/tooling/fast-tooling-react/app/pages/form/index.ts
- packages/tooling/fast-tooling-react/src/__tests__/schemas/category.schema.ts
- packages/tooling/fast-tooling-react/src/__tests__/schemas/index.ts
- packages/tooling/fast-tooling-react/src/form/controls/control.section-link.spec.tsx
- packages/tooling/fast-tooling-react/src/form/controls/control.section.props.ts
- packages/tooling/fast-tooling-react/src/form/controls/control.section.spec.tsx
- packages/tooling/fast-tooling-react/src/form/controls/control.section.style.ts
- packages/tooling/fast-tooling-react/src/form/controls/control.section.tsx
- packages/tooling/fast-tooling-react/src/form/controls/utilities/control-switch.spec.tsx
- packages/tooling/fast-tooling-react/src/form/controls/utilities/control-switch.tsx
- packages/tooling/fast-tooling-react/src/form/controls/utilities/dictionary.spec.tsx
- packages/tooling/fast-tooling-react/src/form/controls/utilities/form.tsx
- packages/tooling/fast-tooling-react/src/form/form.props.ts
- packages/tooling/fast-tooling-react/src/form/form.tsx
- packages/tooling/fast-tooling-react/src/form/templates/template.control.bare.spec.tsx
- packages/tooling/fast-tooling-react/src/form/templates/template.control.single-line.spec.tsx
- packages/tooling/fast-tooling-react/src/form/templates/template.control.standard.spec.tsx
- packages/tooling/fast-tooling-react/src/form/templates/template.control.utilities.props.tsx
- packages/tooling/fast-tooling-react/src/form/templates/template.control.utilities.tsx
- packages/web-components/fast-components/src/switch/switch.definition.ts
- sites/fast-component-explorer/app/explorer.tsx
- sites/fast-creator/app/creator.tsx
- sites/site-utilities/src/components/categories.ts
- sites/site-utilities/src/components/index.ts
This PR is a merging of the feature branch containing the following PRs:
- https://github.com/microsoft/fast/pull/4322
- https://github.com/microsoft/fast/pull/4387
- https://github.com/microsoft/fast/pull/4397
- https://github.com/microsoft/fast/pull/4403
- https://github.com/microsoft/fast/pull/4430
- https://github.com/microsoft/fast/pull/4434
Resolves #2530 
Resolves #2575 
> feat: add categories for the form

- sites/website/src/docs/design-systems/overview.md
> missprint in font-size number

- .github/workflows/ci-weekly.yml
Discover vulnerabilities across a codebase with
ci-weekly.yml previously included a code section for code quality analysis. This seems to have been removed and requires adding back in.
name: Initialize CodeQL
if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
uses: github/codeql-action/init@v1
with:
languages: javascript, typescript, csharp
name: Perform CodeQL Analysis
uses: github/codeql-action/analyze@v1
There is a if condition. this will execute codeQL only if there is a push to master, and not on schedule trigger.
discover a bad pattern and then find similar occurrences across the entire codebase
https://github.com/microsoft/fast/issues/4405
> chore: Add-CodeQL_Security_Scanner

- .github/workflows/ci-weekly.yml
This work chore was already done previously
we need to remove C# language from code scanner . TypeScript and JavaScript are the main focus
from our github collection, we have 
Fix a build failure
> Chore: add code ql security scanner

- sites/fast-component-explorer/app/app.tsx
- sites/fast-component-explorer/app/explorer-region.tsx
- sites/fast-component-explorer/app/explorer.tsx
- sites/fast-component-explorer/app/web-components/index.tsx
- sites/fast-creator/app/app.tsx
- sites/fast-creator/app/creator.tsx
- sites/fast-creator/app/web-components/devices.ts
- sites/fast-creator/app/web-components/index.tsx
- sites/site-utilities/src/components/dimension/index.tsx
- sites/site-utilities/src/components/editor/editor.style.css
- sites/site-utilities/src/components/logo/index.tsx
- sites/site-utilities/src/custom-elements.d.ts
Applying fixing design issues arising from replacing old controls with fast components and replacing Devices select in Creator with a fast-select.
> chore: fix design changes in creator and explorer

- sites/site-utilities/src/components/dimension/index.tsx
- sites/site-utilities/src/custom-elements.d.ts
Turning off up/down buttons in fast-number-field components in Creator.
Turning off the up/down buttons as a work around for the buttons not rendering correctly with negative density.
> chore: turning off buttons in number fields

- packages/web-components/fast-components/src/styles/patterns/button.ts
> fix: ensure button font size and line height map to design system properties

- .github/workflows/ci-nightly.yml
- package.json
This PR is NOT going to master. It is to fix up a branch with some little changes that I believe is needed to make beachball work.
Context is a chat with Ibrahim about his work on integrating beachball into Fast
> Merges to "users/awentzel/update beachball v1" - some fixes to make the workflow work

- packages/web-components/fast-foundation/docs/integrations/webpack.md
Signed-off-by: tech4gt <varun.gupta1798@gmail.com>
Fixed typo in the sample webpack config file in the integration docs.
> fix: typo in webpack integration docs

- packages/web-components/fast-components/src/anchor/anchor.styles.ts
- packages/web-components/fast-components/src/button/button.styles.ts
- packages/web-components/fast-components/src/utilities/behaviors.ts
Ability to dynamically load style sheets based on `appearance` attribute.
Performance
> feat: add appearance stylesheet behavior

- packages/tooling/fast-tooling/src/data-utilities/mapping.vscode-html-languageservice.spec.ts
- packages/tooling/fast-tooling/src/data-utilities/mapping.vscode-html-languageservice.ts
This change adds error checking for parsed JSON (used as HTML attributes), removal of duplicate matching children and a return value that is always a `DataDictionary` for rendering.
This should improve the data dictionary consolidation when changes occur from the Monaco Editor.
> fix: add error catching for unparsable attributes and checks for other edge cases which may occur when typing in the monaco editor

- sites/fast-creator/app/creator.tsx
This change adds a message event listener to catch and attempt to parse and apply a data dictionary.
> feat: adds a listener and handler for postMessage on the window to catch arbitrary messages and update the data dictionary

- change/@microsoft-fast-foundation-c5c4724e-4955-47c0-8b9f-62ed5d95ac94.json
- packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.spec.ts
- packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.template.ts
This PR removes the role from Horizontal Overflow as it is not a valid ARIA role.
> remove incorrect ARIA role from horizontal overflow

- .github/workflows/cd-publish.yml
Publish with beachball. add ci trigger.
> modify cd-publish to remove ci triggers for manual publishes

- .github/workflows/cd-publish.yml
> update to manually publish only if the actor is a specific author

- .github/workflows/cd-publish.yml
> update to move secret to resolve error of not found

- .github/workflows/cd-publish.yml
> update to use simple string of users

- sites/site-utilities/tsconfig.json
The CSS properties subset was not included in the `dist` folder as `allowJs` was omitted from the `tsconfig.json`.
When running `yarn build` in the `sites/site-utilities` directory, there should now exist the css-data.js file in the `dist` directory.
> fix: allow js files to be exported from site-utilities

- .github/workflows/cd-publish.yml
Add --access public to beachball publish
Scoped packages default to restricted, but you can either publish them as public using npm publish --access=public, or set their access as public using npm access public after the initial publish.
You must have privileges to set the access of a package:
You are an owner of an unscoped or scoped package.
You are a member of the team that owns a scope.
You have been given read-write privileges for a package, either as a member of a team or directly as an owner.
If you have two-factor authentication enabled then you'll be prompted to provide an otp token, or may use the --otp=... option to specify it on the command line.
If your account is not paid, then attempts to publish scoped packages will fail with an HTTP 402 status code (logically enough), …
> Added --access public to unblocked denied access to npm registry

- change/@microsoft-fast-tooling-react-fbf8c445-466b-471d-a930-db2b3784b2ad.json
- packages/tooling/fast-tooling-react/src/form/controls/control.linked-data.style.ts
- packages/tooling/fast-tooling-react/src/form/controls/utilities/dictionary.style.ts
- packages/tooling/fast-tooling-react/src/form/controls/utilities/section.validation.style.ts
- packages/tooling/fast-tooling-react/src/form/form.tsx
Maximizes the width that the default controls can use in the `<Form />`.
Original:
Style update:
> fix: update styling to fit the width of the area the form is placed in

- .github/workflows/ci-daily.yml
- .github/workflows/testing/ci-daily-local.yml
- change/@microsoft-fast-web-utilities-91b4ac01-d035-47f1-bdf9-6bcc87cd4fbf.json
- packages/utilities/fast-web-utilities/.mocharc.json
- packages/utilities/fast-web-utilities/karma.conf.js
- packages/utilities/fast-web-utilities/package.json
- packages/utilities/fast-web-utilities/src/__test__/setup-browser.ts
- packages/utilities/fast-web-utilities/src/__test__/setup-node.ts
- packages/utilities/fast-web-utilities/src/aria.spec.ts
- packages/utilities/fast-web-utilities/src/class-names.spec.ts
- packages/utilities/fast-web-utilities/src/dom.spec.ts
- packages/utilities/fast-web-utilities/src/html.spec.ts
- packages/utilities/fast-web-utilities/src/numbers.spec.ts
- packages/utilities/fast-web-utilities/src/query.spec.ts
- packages/utilities/fast-web-utilities/src/rtl-scroll-converter.spec.ts
- packages/utilities/fast-web-utilities/src/strings.spec.ts
- packages/utilities/fast-web-utilities/tsconfig.build.json
- packages/utilities/fast-web-utilities/tsconfig.json
This test converts all `Jest` tests found in the `@microsoft/fast-web-utilities` package to the Karma/Mocha/Chai test setup used in the web-components packages.
Closes #4548 
There were a very few issues with the conversion, namely the use of Jests stored arguments. In one case this was a little different I checked the use of `nonce` with a `MutationObserver` which can be found in `dom.spec.ts` on line 220.
> chore: convert Jest tests to Karma/Mocha/Chai in fast-web-utilities

- .github/workflows/cd-publish.yml
- .npmrc
1. binary path require configuration
we will use "scripts-prepend-node-path=true" in .npmrc folder and it will solve the problem
2. npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@microsoft%2ffast-foundation - Not found
The PUT is use to insert into an API. Here when publish is writing to npm, it need to have a permission. We need to provide
3. npm token with write access.
.npmrc config communicate with npm and write to //registry.npmjs.org/:_authToken=${NPM_TOKEN}. However this will expose the token, So I moved it to the workflow and use -r as beachball publish docs suggest.
4. Update $NPM_PAT to make sure it has read and write access policies
#4556
> fix: add -r to publish and set node-path to true

- .github/workflows/cd-publish.yml
- build/releasing/customRenderers.ts
…tumRenders.ts
provide default URL for publish: https://registry.npmjs.org/
pm ERR! 404 Not Found - PUT https://registry.npmjs.org/@microsoft%2ffast-foundation - Not found
The PUT is use to insert into an API. Here when publish is writing to npm, it need to have a permission.
Update $NPM_PAT incustomRenders
#4556
> add default registry url with updated npm token

- sites/fast-creator/app/creator.tsx
- sites/fast-creator/app/web-components/index.tsx
- sites/site-utilities/src/schemas/definition-mapper.ts
Adds the slider to the Create site design system editing pane.
Before:
After:
This should make the controls more user friendly.
> feat: add slider to the creator number controls

- change/@microsoft-fast-tooling-4a76dab6-2d89-4cfd-a8ba-24f228cc519b.json
- packages/tooling/fast-tooling/karma.conf.js
This updates the globbing pattern to exclude other packages outside of tooling.
> chore: fix tooling coverage globbing pattern

- .github/workflows/cd-publish.yml
- package.json
Adding to use new service account for additional domain + email capability.
> update to new service account

- packages/utilities/fast-benchmarks/build/utils/get-benchmark-names.js
Fixes an issue in locating benchmark paths and building up the app assets based on those path results. It worked in the existing test-case because the test name is only 1 letter long, but otherwise it fails.
> chore: fix benchmarking pathing issue

- .github/workflows/cd-publish.yml
> add token to publish command

- .github/workflows/cd-publish.yml
- .npmrc
> update NPM token

- .github/workflows/cd-publish.yml
removes verbose which may be failing the publish command.
> update to remove -verbose

- .npmrc
- packages/web-components/fast-element/.npmrc
Testing different NPM registry implementation. 
mponents/CONTRIBUTING.md#configuration)
> update registry from npm teams recommendation

- .npmrc
- package.json
updates configuration to publish based on known test project to isolate possible error culprits.
> reconfigure for known success of npm configurations

- .github/workflows/cd-publish.yml
> add token value to git checkout

- sites/fast-creator/app/web-components/index.tsx
This pull request adds the experimental color picker web component to the Creator site.
> feat: add the color picker to the design system editing UI

- change/@microsoft-fast-components-b941cce6-aad9-473d-bc4e-0b03c92661e6.json
- change/@microsoft-fast-foundation-efa3c97d-df28-4674-b07f-e81ff8d2b3b2.json
- packages/web-components/fast-components/src/breadcrumb-item/breadcrumb-item.styles.ts
- packages/web-components/fast-components/src/breadcrumb/breadcrumb.stories.ts
- packages/web-components/fast-components/src/breadcrumb/fixtures/base.html
- packages/web-components/fast-foundation/src/breadcrumb/breadcrumb.ts
I created the `setItemSeparator` method that will set the separator to true. I also combined `removeLastItemSeparator` with `setItemSeparator`. This was added to fix the issue where if a breadcrumb-item is dynamically added, a separator will also be added to the item if it is not the last breadcrumb-item.
I also added an example showing this scenario in the fixtures.
closes #4420
> fix: add separator on breadcrumb-item when a new item is added

- change/@microsoft-fast-tooling-react-5016cf98-0e86-4ce7-946c-3569db9d3d77.json
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.md
This change updates the draft spec for the `@microsoft/fast-tooling-react` CSS control to reflect upcoming work that will enable overrides for multiple CSS properties. This more accurately reflects how a more modular approach will grant greater flexibility to the UI.
Spec update, no tests needed.
> chore: update the CSS control spec for upcoming work regarding the use of overrides to multiple CSS properties

- change/@microsoft-fast-tooling-react-9df59d93-1449-4b42-8af7-dfdf33850171.json
- packages/tooling/fast-tooling-react/app/pages/form.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.style.ts
This is a styling update to match internally used web component widths in the CSS control with the other controls in the `<Form />`.
Before:
After:
The manual app in `fast-tooling-react` can be seen with these changes using `yarn start`.
> CSS control update to override inner web component widths

- sites/fast-creator/app/css-data.js
- sites/fast-creator/app/web-components/index.tsx
- sites/fast-creator/build/generate-mdn-data-files.js
- sites/fast-creator/package.json
- sites/site-utilities/src/schemas/definition-mapper.ts
This adds the alpha CSS custom control to the Creator site, with a subset of CSS properties.
For manual testing, run `yarn` at the root level to update with the changes from `site-utilities` then in the `fast-creator` site use `yarn start`. You should be able to see the CSS control in action in the `<Form />` component in the right panel.
> chore: add a minimal set of CSS properties and the CSS control to the Creator

- change/@microsoft-fast-tooling-react-8723808c-5a55-4e29-a656-bdfb310385e7.json
- packages/tooling/fast-tooling-react/app/pages/form.tsx
- packages/tooling/fast-tooling-react/app/pages/form/index.ts
- packages/tooling/fast-tooling-react/src/__tests__/schemas/control-plugin.css-with-overrides.schema.ts
- packages/tooling/fast-tooling-react/src/__tests__/schemas/control-plugin.css.schema.ts
- packages/tooling/fast-tooling-react/src/__tests__/schemas/control-plugin.schema.ts
- packages/tooling/fast-tooling-react/src/__tests__/schemas/index.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.md
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.props.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/css/css.plugin.control.standard.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/css/css.plugin.control.utilities.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/css/css.template.control.standard.props.ts
- packages/tooling/fast-tooling-react/src/form/custom-controls/css/css.template.control.standard.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/css/index.ts
This adds the ability to override the CSS custom control (yet to be released) with its own set of controls.
Resolves #4613 
Take a look at the changes to the `control.css.md` file to grasp how the overrides are intended to work. This works in a similar manner to the current control overrides for the `<Form />` in general.
An example has also been added to the manual testing app and can be viewed at `app/pages/form.tsx`.
This is currently only manually tested inside the test app as it is in the midst of development.
> chore: add CSS control plugin overrides

- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/custom-elements.ts
- packages/web-components/fast-components/src/data-grid/index.ts
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/data-grid/data-grid-cell.spec.ts
- packages/web-components/fast-foundation/src/data-grid/data-grid-cell.template.ts
- packages/web-components/fast-foundation/src/data-grid/data-grid-cell.ts
- packages/web-components/fast-foundation/src/data-grid/data-grid-row.spec.ts
- packages/web-components/fast-foundation/src/data-grid/data-grid-row.template.ts
- packages/web-components/fast-foundation/src/data-grid/data-grid-row.ts
- packages/web-components/fast-foundation/src/data-grid/data-grid.spec.ts
- packages/web-components/fast-foundation/src/data-grid/data-grid.template.ts
- packages/web-components/fast-foundation/src/data-grid/data-grid.ts
> feat: update data grid to FoundationElement

- sites/site-utilities/src/components/categories.ts
Place `no-paint`, `use-defaults` and `direction` to the advanced category in the Creator site.
This simplifies the design system form view in the Creator and can be viewed by going to the fast-creator site and running `yarn start`.
> add no-paint, direction, use-defaults design system attributes to the advanced category

- sites/fast-creator/app/css-data.js
- sites/fast-creator/build/generate-mdn-data-files.js
This change updates the list of allowed-to-edit CSS properties in the Creator and updates the generated file imported.
Reviewers can see the change by running `yarn start` in the `fast-creator` site folder and looking in the right pane of the site.
> update the generated CSS property file to include more layout options

- change/@microsoft-fast-components-d2321caf-e4b9-45d0-87e6-e3eabc02b5e7.json
- change/@microsoft-fast-tooling-a9598950-287b-47ee-a37b-d8bf005dee3f.json
- packages/tooling/fast-tooling/package.json
- packages/tooling/fast-tooling/src/web-components/color-picker/color-picker.ts
- packages/web-components/fast-components/package.json
- yarn.lock
This change pins the `devDependency` on `@microsoft/fast-tooling` from the `@microsoft/fast-components` to a patch behind to circumvent an issue where taking a `dependency` on `@microsoft/fast-components` from `@microsoft/fast-tooling` caused a circular dependency. This is only a mono-repository issue because of symlinking, as the utility is only used in component definitions and is not expected to change much in the future. As such, this decoupling is expected to cause minimal maintenance issues.
This change also includes the import of `<fast-text-field>` which is used in the color picker.
> update dependencies to remove circular dependencies and fix component import

- change/@microsoft-fast-element-7d7c3fe3-08a8-492f-a269-5ea16dc91235.json
- packages/web-components/fast-element/docs/api-report.md
- packages/web-components/fast-element/docs/guide/observables-and-state.md
- packages/web-components/fast-element/src/observation/observable.spec.ts
- packages/web-components/fast-element/src/observation/observable.ts
This PR adds a method to `BindingObserver` that allows inspection of the internal `SubscriptionRecord`'s used being used by a `BindingObserver`. This allows us to actually inspect which objects & values are being observed by a `BindingObserver`.
> feat: add method to retrieve bindingObserver subscriptions

- sites/fast-color-explorer/app/app.tsx
- sites/fast-color-explorer/app/color-blocks.tsx
- sites/fast-color-explorer/app/control-pane.tsx
- sites/fast-color-explorer/app/design-system.ts
- sites/fast-color-explorer/app/gradient.tsx
- sites/fast-color-explorer/app/state.ts
- sites/fast-color-explorer/app/swatch.tsx
- sites/fast-color-explorer/package.json
The current Color Explorer still pulls recipes from the deprecated React styles package. This updates them to come from the current web components package. The UI is still built with the deprecated React components however.
> Updated Color Explorer to work with current color recipes

- change/@microsoft-fast-components-b6b4bb43-235c-49bf-bd34-b8c73e11ef47.json
- packages/web-components/fast-components/src/button/button.styles.ts
- packages/web-components/fast-components/src/styles/patterns/button.ts
The anchor component should not have a `disabled` style, so I moved all the disabled selectors out of the common button styles file and added them to the ` button.styles` file. 
closes #4595
> fix: removed disabled style on anchor web component

- change/@microsoft-fast-components-0c440444-07e2-40ef-b07c-b3c1fa30437e.json
- packages/web-components/fast-components/src/button/button.styles.ts
- packages/web-components/fast-components/src/styles/patterns/button.ts
Removed a `:` on hover for accent button style and removed `:host([appearance="lightweight"][disabled])` since the default is appearance is already setting it.
> fix: typo on hover for accent button style

- change/@microsoft-fast-components-feba7547-6535-4841-a123-560094da9661.json
- change/@microsoft-fast-tooling-7e8d4313-271c-4944-a4fa-413c564d5518.json
- packages/tooling/fast-tooling/app/webpack.common.js
- packages/tooling/fast-tooling/karma.conf.js
- packages/tooling/fast-tooling/package.json
- packages/tooling/fast-tooling/tsconfig.esm.json
- packages/tooling/fast-tooling/webpack.message-system.config.js
- packages/web-components/fast-components/package.json
- yarn.lock
This change forces `fast-tooling` to use all component dependencies from the npm registry (instead of the local workspaces). It also updates webpack to force resolution of those dependencies to the version installed from npm.
It's unclear to me why I needed to update webpack configs, but somehow the dependencies were getting resolved to the workspace dependencies, causing `features/design-system-vNext` to fail tests (due to breaking changes in that branch).
> Fixing dependency issues with fast-tooling

- change/@microsoft-fast-foundation-bd4f94a4-5281-432f-897a-a2272f2cfa94.json
- packages/web-components/fast-components/src/button/button.styles.ts
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/card/card.ts
This PR updates Card to extend FoundationElement.
This does not include the component changes for `fast-components` as those changes are dependent on the token API being finalized.
> update card to extend foundation

- specs/template.md
This PR updates our component spec template with two important additions:
1. We want to explicitly incorporate the visual design work as part of the overall spec process.
2. We want to formalize our process a bit more, reflected in the checkpoints called out in the Process section.
Please re-read the entire spec template and consider it in its entirety.
> doc: update the component spec and establish new process checkpoints

- yarn.lock
**Dependencies Update**
CVE-2020-28502
high severity
Vulnerable versions: < 1.6.2
Patched version: 1.6.2
This affects the package xmlhttprequest before 1.7.0; all versions of package xmlhttprequest-ssl. Provided requests are sent synchronously (async=False on xhr.open), malicious user input flowing into xhr.send could result in arbitrary code being injected and run.
CVE-2021-24033
moderate severity
Vulnerable versions: >= 0.4.0, < 11.0.4
Patched version: 11.0.4
react-dev-utils prior to v11.0.4 exposes a function, getProcessForPort, where an input argument is concatenated into a command string to be executed. This function is typically used from react-scripts (in Create React App projects), where the usage is safe. Only when this function is manually invoked with user-provided values (ie: …
> fix: update dependencies to stable version

- yarn.lock
Resolves security vulnerability with a more target approach than the automated dependency resolver.
> update handlebars to resolve security vulnerability

- change/@microsoft-fast-tooling-2184a53f-c01f-469b-bc91-d29c46a208a3.json
- packages/tooling/fast-tooling/package.json
This PR adds @microsoft/fast-colors as a dependency of @microsoft/fast-tooling. It was being used by the ColorPicker component but was never added as a dependency.
> add missing fast-colors dependency to fast-tooling

- change/@microsoft-fast-element-ad8e6227-ad64-4f86-9f52-44ea25546893.json
- packages/web-components/fast-element/docs/guide/using-directives.md
> docs: add missing closing parenthesis to when directive example

- package.json
- yarn.lock
The lockfile has been updated a lot recently with extra changes that broke storybook and other `devDependencies`. Those changes also reverted hard-coded lockfile changes intended to resolve security vulnerabilities.
This PR reverts the lockfile to an earlier state, then reapplies the intended resolutions fixes. I then ran `yarn-deduplicate` to dedupe the entries.
Overrides #4688, #4716
Resolutions for security updates need to be handled in the `resolutions` list in the root-level `package.json`. Changing `yarn.lock` directly (as dependabot and other auditing tools recommend) can lead to those dependencies getting overwritten whenever the lockfile is regenerated.
> restore lockfile entries

- change/@microsoft-fast-tooling-20f069e9-83b2-4d92-9927-b8bcf86c60e8.json
- packages/tooling/fast-tooling/app/webpack.common.js
- packages/tooling/fast-tooling/karma.conf.js
- packages/tooling/fast-tooling/tsconfig.esm.json
- yarn.lock
`fast-tooling` still had aliases in TS and Webpack for packages that seem to have been removed. This PR removes those aliases so that package resolution happens normally.
> remove webpack aliases from packages that don't exist in fast-tooling

- .github/workflows/cd-publish.yml
**Adding a script to notify discord on failure when cd-publish fails.**
Upon failure, for example, and starting with cron scheduled pipeline failures, send an email to the operations team with a link to the failed GitHub Action to be reviewed immediately and proactively solved before customer impact.
#4674
will only be tested on the ci.
- [ x I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)
> add: workflow task to notify discord on failure

- change/@microsoft-fast-components-4a281723-033f-4a74-967d-df71271eac75.json
- packages/web-components/fast-components/.storybook/preview-head.html
- packages/web-components/fast-components/.storybook/preview.js
- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/accordion/accordion.stories.ts
- packages/web-components/fast-components/src/button/button.styles.ts
- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components/src/flipper/flipper.styles.ts
- packages/web-components/fast-components/src/listbox-option/listbox-option.styles.ts
- packages/web-components/fast-components/src/select/select.pw.spec.ts
- packages/web-components/fast-components/src/styles/direction.ts
- packages/web-components/fast-components/src/styles/patterns/button.ts
- packages/web-components/fast-components/src/text-field/text-field.styles.ts
This PR removes some of the last remaining references to the Design System Provider from `@microsoft/fast-components`. There are a few remaining references, but once toolbar goes in and we figure out a solution for tree-item then we'll be good to remove the last remaining references.
> Remove references to DSP

- change/@microsoft-fast-tooling-19c71aa0-001a-4dc2-948e-af550fe4aa6f.json
- change/@microsoft-fast-tooling-react-49db1dda-73ac-4a19-a34f-9ff90ea77af3.json
- packages/tooling/fast-tooling-react/app/pages/form.tsx
- packages/tooling/fast-tooling-react/package.json
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.tsx
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.tsx
- packages/tooling/fast-tooling/karma.conf.js
- packages/tooling/fast-tooling/package.json
- packages/tooling/fast-tooling/src/web-components/color-picker/color-picker.ts
- packages/tooling/fast-tooling/tsconfig.esm.json
- sites/fast-creator/app/creator.tsx
- sites/fast-creator/package.json
- yarn.lock
This change updates to use the new Design System registry as well as named imports from `@microsoft/fast-components` as well as updates the dependencies to not be on `latest` but the current version. This change will be mirrored in another PR to master so that vNext can be unblocked and master can be subsequently unblocked.
This change appears to run fine on the manual apps and web components that are registered to the design system are showing up. Let me know if there is a better method, we are making the assumption that either the user is not going to be on a separate version of the Design System and will be using the same class with this change.
> fix tooling libraries to use the new design system registry and updated named imports

- packages/web-components/fast-components/src/styles/size.ts
- packages/web-components/fast-components/src/tree-item/tree-item.styles.ts
Integrate new `cssPartial` into appropriate structures. Fixes a styling issue in tree-item and replaces an existing one-off implementation.
> integrate CSSPartial where appropriate

- change/@microsoft-fast-foundation-62fde272-7a56-4e1b-93b2-d5ed5c1083bf.json
- packages/web-components/fast-foundation/src/design-system-provider/design-system-provider.ts
- sites/website/src/docs/design-systems/creating-a-design-system.md
A bug came through where the mechanism DSP is using would throw an error. fast-element already abstracts the check so this PR just updates to use that abstraction.
> update DSP to use dom.supportsAdoptedStyleSheets

- change/@microsoft-fast-tooling-a95588f9-8ad5-4ee9-9e50-c91f71db106b.json
- packages/tooling/fast-tooling/src/message-system-service/monaco-adapter.service.spec.ts
- packages/tooling/fast-tooling/src/message-system-service/monaco-adapter.service.ts
This swaps out the old mapping function for data dictionaries and strings (monaco editor values) to the new mapping function that takes into account a previous data dictionary and re-uses previous keys and values where possible.
This should be preceded by #4485 as typing in the monaco editor will error more often without the additional fixes.
> fix: swap to use the new data dictionary mapper in the monaco editor service

- change/@microsoft-fast-tooling-67a247a1-b5b7-4d23-a1ac-85b1756d1362.json
- packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.spec.ts
- packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.ts
- packages/tooling/fast-tooling/src/web-components/html-render-layer/html-render-layer.ts
- packages/tooling/fast-tooling/src/web-components/html-render/html-render.spec.ts
- packages/tooling/fast-tooling/src/web-components/html-render/html-render.template.ts
- packages/tooling/fast-tooling/src/web-components/html-render/html-render.ts
- sites/fast-creator/app/creator.tsx
- sites/fast-creator/app/preview.tsx
Fixes several bugs in the HTMLRender component and the creator integration including:
- Correctly set originatorId and ignore messages from same sender.
- Automatically select the activeDictionaryId element on initilization and data messages.
- Stop assuming that the root element in the dictionary will always be called "root".
- Possible fix for intermittent test failure.
> fix: htmlrender component and creator integration bug fixes

- change/@microsoft-fast-components-23d1c8dc-49ad-41a3-9769-61ef681b8009.json
- packages/web-components/fast-components/src/card/index.ts
Update card to better resolve it's parent element when setting fillColor
In cases where a Card is a direct child of a ShadowRoot, the existing logic would try to get a fillColor for a null value. This updates Card to better resolve it's parentElement in this case, and ensures fillColor is only set when the card has a valid parent element.
> fix Card fill color

- change/@microsoft-fast-tooling-3454cdf9-17dd-456e-bea9-ed2672ea21c1.json
- packages/tooling/fast-tooling/karma.conf.js
- packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.spec.ts
- packages/tooling/fast-tooling/src/web-components/html-render/html-render.spec.ts
This PR disables HTMLRender tests that are causing intermittent CI failures on pull-requests.
> disable html render tests

- change/@microsoft-fast-tooling-703c6295-25d9-4482-a160-ecc7309e280a.json
- change/@microsoft-fast-tooling-react-fc9ddcac-5cd5-4e27-ac46-41ef03c3fa76.json
- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.tsx
- packages/tooling/fast-tooling/app/examples/css-layout/index.html
- packages/tooling/fast-tooling/app/examples/css-layout/index.ts
- packages/tooling/fast-tooling/app/examples/css-layout/webpack.common.js
- packages/tooling/fast-tooling/app/examples/css-layout/webpack.dev.js
- packages/tooling/fast-tooling/app/index.html
- packages/tooling/fast-tooling/src/web-components/css-layout/css-layout.css-properties.ts
- packages/tooling/fast-tooling/src/web-components/css-layout/css-layout.form-associated.ts
- packages/tooling/fast-tooling/src/web-components/css-layout/css-layout.spec.ts
- packages/tooling/fast-tooling/src/web-components/css-layout/css-layout.styles.ts
- packages/tooling/fast-tooling/src/web-components/css-layout/css-layout.template.ts
- packages/tooling/fast-tooling/src/web-components/css-layout/css-layout.ts
- packages/tooling/fast-tooling/src/web-components/css-layout/index.ts
- packages/tooling/fast-tooling/src/web-components/index.ts
- sites/fast-creator/app/css-data.js
- sites/fast-creator/app/web-components/index.tsx
- sites/fast-creator/build/generate-mdn-data-files.js
This creates a CSS layout web component in `@microsoft/fast-tooling` that can be used by itself or with the experimental custom css control in `@microsoft/fast-tooling-react`. It primarily uses the CSS flexbox to update CSS either by the change event or an `onChange` property assigned to the element.
This PR also contains the integration into the Creator design tool.
Running the Creator site will show off the control in the right pane, to view it by itself run `yarn start` to use the manual testing app in `@microsoft/fast-tooling` package.
New unit tests have been added for this component.
> add a layout web component for css properties

- change/@microsoft-fast-tooling-31e4d861-c660-40a3-94ae-1e0b45aa7f4e.json
- packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.template.ts
- packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.ts
Adds prettier changes that were missed during rebase.
> add prettier changes

- change/@microsoft-fast-components-6ea330cd-b126-498e-a706-28b06496c3f8.json
- packages/web-components/fast-components/src/styles/patterns/button.ts
Added `background: transparent` to hover and active state on lightweight and hypertext appearances. This is to fix the issue that the background color shows on hover and active in Firefox and Safari.
closes #4817
> fix: removed background plate on hover and active states on lightweight and hypertext anchor

- sites/fast-component-explorer/webpack.common.js
- sites/fast-creator/webpack.common.js
This adds autosuggest to the monaco editor in the creator and component explorer.
Adds some intellisense per #3563 but due to Monaco Editor not yet allowing customData to describe web components, this is blocked until https://github.com/microsoft/monaco-editor/issues/1723 is addressed.
You can view this by running `yarn start` in the creator and component explorer sites.
> feat: add autosuggestions for the monaco editor

- packages/web-components/fast-components/src/color-vNext/recipes/neutral-layer-card-container.ts
- sites/fast-color-explorer/app/app.tsx
- sites/fast-color-explorer/app/color-blocks.tsx
- sites/fast-color-explorer/app/control-pane.tsx
- sites/fast-color-explorer/app/design-system.ts
- sites/fast-color-explorer/app/recipes.ts
- sites/fast-color-explorer/app/state.ts
- sites/fast-color-explorer/app/swatch.tsx
Added interop layer for Color Explorer to reference new format color recipes
> feat: update color explorer recipe references

- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/custom-elements.ts
- packages/web-components/fast-components/src/index-rollup.ts
- packages/web-components/fast-components/src/index.ts
- sites/fast-color-explorer/app/index.tsx
- sites/fast-color-explorer/app/site-footer.tsx
- sites/fast-component-explorer/app/index.tsx
- sites/fast-component-explorer/app/site-footer.tsx
- sites/fast-creator/app/index.tsx
- sites/fast-creator/app/site-footer.tsx
- sites/fast-website/src/app/components/background-design/background-design.styles.ts
- sites/fast-website/src/app/components/background-design/background-design.ts
- sites/fast-website/src/app/components/card-section/card-section.styles.ts
- sites/fast-website/src/app/components/color-swatch/color-swatch.styles.ts
- sites/fast-website/src/app/components/content-placement-container/content-placement-container.styles.ts
- sites/fast-website/src/app/components/content-placement/content-placement.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.ts
- sites/fast-website/src/app/components/feature-card/feature-card.styles.ts
- sites/fast-website/src/app/components/navigation-item/navigation-item.styles.ts
- sites/fast-website/src/app/components/navigation/navigation.styles.ts
- sites/fast-website/src/app/components/section-header/section-header.styles.ts
- sites/fast-website/src/app/components/side-navigation/side-navigation.styles.ts
- sites/fast-website/src/app/index.ts
- sites/fast-website/src/index-rollup.ts
- sites/fast-website/src/public/index.ejs
This PR removes the DSP and related infrastructure from the fast-website package, and replaces it with a DesignToken implementation.
It also adds an "allComponents" export so that app authors can define all components in a DesignSystem easily.
> remove DSP from fast-website

- packages/tooling/fast-figma-plugin-msft/src/core/ui/components/corner-radius/index.ts
- packages/tooling/fast-figma-plugin-msft/src/core/ui/components/stealth-button/index.ts
- packages/tooling/fast-figma-plugin-msft/src/core/ui/components/swatch/index.ts
- packages/tooling/fast-figma-plugin-msft/src/index.html
- packages/tooling/fast-figma-plugin-msft/src/ui.tsx
This PR removes deprecated assets from the fast-figma-plugin package, replacing with design token implementations.
> remove deprecated assets from Figma plugin

- sites/fast-tooling-examples/app/index.html
- sites/fast-tooling-examples/app/index.ts
This updates the FAST Tooling examples site by removing the `<fast-design-system-provider>` component as a wrapper and uses the design token to change the theme.
Simply run `yarn start` in the fast-tooling-examples site.
> chore: update the tooling examples with the new design tokens and remove the design-system-provider component

- sites/fast-website/src/app/data/framework.data.ts
Updates React integration text for the site.
None
Please read the text and advise :)
> update react integration statement for site

- packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.tsx
- sites/fast-creator/app/app.tsx
- sites/fast-creator/app/configs/library.fast.design-system.mapping.ts
- sites/fast-creator/app/configs/library.fast.design-system.schema.json
- sites/fast-creator/app/configs/library.fast.registry.ts
- sites/fast-creator/app/creator.tsx
- sites/fast-creator/app/index.tsx
- sites/fast-creator/app/preview.tsx
- sites/fast-creator/app/site-footer.tsx
- sites/fast-creator/app/web-components/index.tsx
- sites/site-utilities/src/components/categories.ts
- sites/site-utilities/src/components/logo/index.tsx
This updates the Creator app by removing the `<fast-design-system-provider>` component as a wrapper and uses the design tokens when updates occur.
This change does not update the theme, @bheston do you have a reference as to what needs to happen for theme switching between light and dark mode to occur?
> chore: update the creator with the new design tokens and remove the design-system-provider component

- sites/fast-color-explorer/app/design-system.ts
- sites/fast-color-explorer/app/recipes.ts
Remove 'selected' values from Color Explorer
> Remove "selected" recipes from Color Explorer

- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/horizontal-scroll/fixtures/horizontal-scroll.html
- packages/web-components/fast-components/src/horizontal-scroll/index.ts
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/flipper/flipper.template.ts
- packages/web-components/fast-foundation/src/flipper/flipper.ts
- packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.template.ts
- packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.ts
Adds default previous and next flippers to horizontal-scroll with tabbing enabled.
Adds click behaviour for enter key on focused flippers.
Adds arrow key navigation to horizontal-scroll.
https://github.com/microsoft/fast/issues/4808
https://github.com/microsoft/fast/issues/4713
> Adding keyboard interactions to horizontal-scroll

- packages/web-components/fast-components/.storybook/preview-head.html
- packages/web-components/fast-components/src/accordion-item/accordion-item.styles.ts
- packages/web-components/fast-components/src/button/button.styles.ts
- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components/src/data-grid/data-grid-row.styles.ts
- packages/web-components/fast-components/src/dialog/dialog.styles.ts
- packages/web-components/fast-components/src/disclosure/disclosure.styles.ts
- packages/web-components/fast-components/src/flipper/flipper.styles.ts
- packages/web-components/fast-components/src/horizontal-scroll/fixtures/horizontal-scroll.html
- packages/web-components/fast-components/src/listbox/listbox.styles.ts
- packages/web-components/fast-components/src/menu/menu.styles.ts
- packages/web-components/fast-components/src/radio/radio.styles.ts
- packages/web-components/fast-components/src/slider/slider.styles.ts
- packages/web-components/fast-components/src/styles/patterns/button.ts
- packages/web-components/fast-components/src/switch/switch.styles.ts
- packages/web-components/fast-components/src/toolbar/toolbar.styles.ts
Cleaned up some hard-coded design token names
> Cleaned up some hard-coded design token names

- change/@microsoft-fast-tooling-11ea6c01-6396-4ce7-9172-148f8ebb7958.json
- packages/tooling/fast-tooling/src/web-components/html-render-layer-inline-edit/html-render-layer-inline-edit.style.ts
- packages/tooling/fast-tooling/src/web-components/html-render-layer-inline-edit/html-render-layer-inline-edit.template.ts
- packages/tooling/fast-tooling/src/web-components/html-render-layer-inline-edit/html-render-layer-inline-edit.ts
- packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.spec.ts
- packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.template.ts
- packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.ts
- packages/tooling/fast-tooling/src/web-components/html-render-layer/html-render-layer.ts
- packages/tooling/fast-tooling/src/web-components/html-render/html-render.spec.ts
- packages/tooling/fast-tooling/src/web-components/html-render/html-render.template.ts
- packages/tooling/fast-tooling/src/web-components/html-render/html-render.ts
- sites/fast-creator/app/creator.tsx
- sites/fast-creator/app/preview.tsx
- sites/fast-creator/app/web-components/index.tsx
Adding a new layer to the HTMLRender component that allows for inline editing of text and adding this functionality to Creator. Expected behavior is whenever text within the preview area is double clicked a textarea is placed in the same position of the text node allowing for user input. The text area will resize based on the input and pressing the Enter key will commit the changes. Pressing Esc, Tab or clicking outside of the text area will cancel the interaction.
> feat: add inline edit layer to htmlrender and creator

- change/@microsoft-fast-foundation-8df4f5de-a912-455e-b729-e55874db5189.json
- packages/web-components/fast-foundation/src/tree-item/tree-item.ts
The tree-item component has code to prevent the up/down arrow keys from scrolling the page when they are being used to navigate through the tree-view hierarchy. The left/right arrow keys do not receive this same treatment, and thus if the page (or an element on the page that contains the tree-view) is horizontally scrollable, it will scroll when expanding/collapsing the items.
None - [mentioned in Discord](https://discord.com/channels/449251231706251264/482296787021856768/855695816201863190), can file an issue if necessary.
None.
There's a TODO item in the test code for tree-item saying "Need to add tests for keyboard handling & focus management". So as of right now there's no tests around this and I wasn't sure where to begin with those since there were no examples to work from. I hacked …
> Prevent left/right arrows from scrolling when expanding/collapsing tree-item

- sites/fast-creator/specs/site.spec.md
This change updates the spec file with details on how adding a component library will work in the Creator app.
Read through the change and note any part that does not make sense. Keep in mind the messaging between `creator.tsx` and `preview.tsx` is because the preview exists in an iframe.
> chore: add documentation for adding a component library to the creator

- packages/web-components/fast-components/src/avatar/avatar.vscode.definition.json
- sites/fast-component-explorer/app/fast-components/configs/fast-avatar.ts
- sites/fast-component-explorer/app/fast-components/configs/index.ts
- sites/site-utilities/statics/assets/components/fast-avatar.schema.json
This change adds the FAST avatar `<fast-avatar>` component to the Component Explorer site.
Run the Component Explorer site in `sites/fast-component-explorer` with `yarn start`. Navigate to the Avatar using the menu on the left, you should be able to see the`<fast-avatar>` render.
> chore: add the FAST avatar component to the component explorer site

- change/@microsoft-fast-foundation-ff7d1114-5eeb-4567-bca4-47fa6eea21d1.json
- packages/web-components/fast-foundation/src/design-system/component-presentation.ts
- packages/web-components/fast-foundation/src/design-system/design-system.ts
- packages/web-components/fast-foundation/src/di/di.ts
- packages/web-components/fast-foundation/src/foundation-element/foundation-element.ts
Adds code docs for design system, foundation element, and component presentation. Also, ensures certain internal, dynamically attached properties are less likely to clash with end user code.
Just docs and two private field name changes. All tests should pass.
No additional tests needed.
Will follow up with another PR that adds the DI docs.
> docs(fast-foundation): add api docs for design system and foundation ele

- change/@microsoft-fast-components-169a57c9-05a6-43fb-80e1-19d382618018.json
- packages/tooling/fast-figma-plugin-msft/src/core/ui/components/stealth-button/index.ts
- packages/tooling/fast-figma-plugin-msft/src/core/ui/components/swatch/index.ts
- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/color/recipes/neutral-stroke-divider.ts
- packages/web-components/fast-components/src/design-system-provider/README.md
- packages/web-components/fast-components/src/design-system-provider/design-system-provider.vscode.definition.json
- packages/web-components/fast-components/src/design-system-provider/index.ts
- packages/web-components/fast-components/src/design-tokens.ts
- sites/fast-color-explorer/app/color-blocks.tsx
- sites/fast-color-explorer/app/control-pane.tsx
- sites/fast-color-explorer/app/design-system.ts
- sites/fast-color-explorer/app/recipes.ts
- sites/fast-website/src/app/components/color-swatch/color-swatch.styles.ts
- sites/fast-website/src/app/components/content-placement-container/content-placement-container.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.ts
- sites/fast-website/src/app/components/feature-card/feature-card.styles.ts
- sites/fast-website/src/app/css/logo.css
- sites/site-utilities/statics/assets/components/fast-design-system-provider.schema.json
Updated the fillColor type handling in the design-system-provider.
Also cleaned up token sequence in code. The second commit is **only** a sequence change.
Review the first commit. The second one is sequence change only.
> Design token cleanup

- change/@microsoft-fast-foundation-04e61c24-7d8e-41d9-8d68-5ec10a94aaf0.json
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/design-token/design-token.ts
- packages/web-components/fast-foundation/src/design-token/interfaces.ts
Replaces alpha tsdoc tag with public to surface DesignToken to documentation.
> mark design token public

- change/@microsoft-fast-tooling-e35d28a0-3fbe-4f91-b595-613f12fd515a.json
- packages/tooling/fast-tooling/src/data-utilities/mapping.mdn-data.ts
- packages/tooling/fast-tooling/src/web-components/css-layout/css-layout.spec.ts
- packages/tooling/fast-tooling/src/web-components/css-layout/css-layout.template.ts
- packages/tooling/fast-tooling/src/web-components/css-layout/css-layout.ts
- sites/fast-creator/app/creator.tsx
- sites/fast-creator/app/preview.tsx
- sites/fast-creator/app/web-components/index.tsx
This change:
- Updates the CSS layout web component to respect incoming inline css string values and maps them to the relevant inputs
- Updates the Creator to use the naming "Design Tokens"
- Updates the Creator to use the `key` to track the CSS layout component
Unit tests have been added and can be run in `fast-tooling` with the `yarn run test` command.
> fix: update the CSS layout web component to respect an incoming inline css string value

- sites/fast-creator/app/configs/library.fast.design-system.mapping.ts
This change updates any text in the preview to white/black when the theme is switched.
Before:
After:
Run the Creator app using `yarn start` and toggle the theme button.
> fix: updates the document body to swap the color of text when the theme is toggled between dark and light

- change/@microsoft-fast-components-a5da2587-dbcf-4d4a-a54d-b006517c53be.json
- change/@microsoft-fast-foundation-23849ffd-d2e9-429c-b922-f1972b6fe773.json
- packages/web-components/fast-components/src/design-tokens.ts
- packages/web-components/fast-foundation/src/design-token/design-token.spec.ts
- packages/web-components/fast-foundation/src/design-token/design-token.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.ts
- sites/fast-website/src/app/css/base.css
- sites/fast-website/src/app/css/root.css
This PR fixes a few styling disparities between vNext site and what is published on https://www.fast.design/.
There are still a few differences between the sites which are intentional:
1. accentFillRecipe changed, so you'll notice buttons (and any UI using the accentFill recipe) are a different color. This is notable in the preview pane, where the button fill color is slightly darker and the text color is white instead of black.
2. The base-font-size and line height changed, so text of some controls will be smaller.
It also fixes a bug in DesignToken where tokens aliased to other tokens that were assigned derived values did not get their CSS custom property updated when the derived value changed.
> Fixes to FAST website and DesignToken

- change/@microsoft-fast-tooling-82633ce7-b71d-47f0-9cc8-0db6faff72a3.json
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.props.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.spec.ts
- packages/tooling/fast-tooling/src/message-system/message-system.utilities.ts
- packages/tooling/fast-tooling/src/message-system/types.ts
As part of the work to allow dynamic imports, we have a requirement to add schemas to the schema dictionary. This change adds this ability to the `MessageSystem`.
Check the interfaces to see that they make sense, the request should submit an array of schemas and the message sent back out to registered services should contain the updated schema dictionary.
A unit test has been added for this new functionality.
- Update the schema dictionary in services and components that rely on it
> feat: allow schemas to be added to the schema dictionary

- change/@microsoft-fast-components-eb055108-85e2-4bdd-bbc0-3e8e22e135cf.json
- packages/web-components/fast-components/src/breadcrumb/breadcrumb.styles.ts
When using the `breadcrumb` component, it can become rather large when it displays several items. On mobile, this will quickly be too large for the viewport.
I'm suggesting to allow the breadcrumb container to `wrap` its content over several lines. See screenshots for before/after comparison.
> breadcrumb: allow wrapping of items in the list container

- change/@microsoft-fast-components-2666b9cf-6b9b-4cd4-8696-7092f2f4a7a0.json
- change/@microsoft-fast-foundation-782ed85b-f0bc-42cd-a0da-cc7ade388588.json
- packages/web-components/fast-components/src/avatar/index.ts
- packages/web-components/fast-components/src/card/index.ts
- packages/web-components/fast-components/src/design-system-provider/index.ts
- packages/web-components/fast-components/src/toolbar/index.ts
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/di/di.ts
This PR fixes a few doc comments that were causing api-documenter to fail during website creation.
fixes #4962
> chore: fix website CI failure

- yarn.lock
Resolves and de-duplicates lockfile entries which were missed in a previous merge.
The missing lockfile entries are due to `package.json` dependency changes introduced in #4961.
The process for resolving:
1. Check out a branch based off the main branch, or checkout just the lockfile from the main branch (ex. `git checkout master -- yarn.lock`)
2. Run `yarn --ignore-scripts` to resolve entries.
3. Use `yarn-deduplicate` (`yarn global add yarn-deduplicate`) to deduplicate similar entries.
4. Re-run `yarn --ignore-scripts` to ensure deduplicated entries are sorted.
1. run `git clean -dfx` to remove all untracked files.
2. run `yarn` to re-install all packages and resolve the lockfile.
No new untracked changes should be present in `yarn.lock`.
This will be less of an issue once we switch to …
> resolve lockfile entries

- change/@microsoft-fast-foundation-811d0e53-0f53-46c5-bfe4-e01c4ef9c828.json
- packages/web-components/fast-foundation/src/menu-item/menu-item.ts
I noticed some attributes on menu-item weren't turning on when the attribute existed without adding a "true" value.
> Fixed attr boolean mode on menu item

- sites/fast-creator/app/creator.tsx
This changes the method to the notification to add a library, not that a library has been added, which will get triggered after.
See that the Fluent UI components, while added, do not render correctly in the `master` branch. This change fixes this issue by using the correct method which can be seen by adding a Card component.
> fixes an issue where the wrong library add method was used

- change/@microsoft-fast-components-ede49706-2b46-4fa2-9fe2-1bb24fe9910e.json
- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/combobox/combobox.stories.ts
- packages/web-components/fast-components/src/custom-elements.ts
- packages/web-components/fast-components/src/design-system-provider/index.ts
We kept the DSP for backwards compat, and encourage consumers to transition to setting design token properties directly, though it still is rather convenient, but confusing to use since it doesn't have a visible interface and is not registered by default.
This simple change registers the dsp by default so any experiences using it don't have to register it separately.
> Register design-system-provider

- change/@microsoft-fast-components-836cf194-1c52-43c4-9806-22297b17c450.json
- packages/web-components/fast-components/src/breadcrumb-item/breadcrumb-item.styles.ts
This change resolves the issue that the foreground color is set to black instead of white in the component explorer, by adding `neutralForegroundRest` to host.
before
after
> fix: add neutralForegroundRest color to host in breadcrumb-item style

- change/@microsoft-fast-components-56af9e05-3ae4-4b15-a4aa-659183f0f7c1.json
- packages/web-components/fast-components/src/badge/badge.styles.ts
Adding a transparent border and adjusting the padding to keep the size of the badge the same. This change will not affect anything in default contrast, but will automatically set a border color when the component is in high contrast mode.
before
after
> fix: add border to badge and adjust padding size

- build/transform-fragments.js
- change/@microsoft-fast-components-9f6a1353-6e75-45f3-835d-d6dbf9d8a8ff.json
- packages/web-components/fast-components/src/badge/badge.styles.ts
- packages/web-components/fast-components/src/breadcrumb-item/breadcrumb-item.styles.ts
- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components/src/flipper/flipper.styles.ts
- packages/web-components/fast-components/src/listbox-option/listbox-option.styles.ts
- packages/web-components/fast-components/src/menu-item/menu-item.styles.ts
- packages/web-components/fast-components/src/number-field/number-field.styles.ts
- packages/web-components/fast-components/src/radio/radio.styles.ts
- packages/web-components/fast-components/src/select/select.styles.ts
- packages/web-components/fast-components/src/text-field/text-field.styles.ts
- packages/web-components/fast-components/src/toolbar/toolbar.styles.ts
- packages/web-components/fast-components/src/tooltip/tooltip.styles.ts
- packages/web-components/fast-components/src/tree-item/tree-item.styles.ts
* Simplifies the complexity for the `transformHTMLFragment` and `transformCSSFragment` functions used by Rollup for `fast-foundation` and `fast-components`.
* Re-writes comments in `css` tagged templates to use real CSS comments
* Updated CSS comments to point to issues as `TODO:`s where applicable
Resolves #4692
This affects the compiled `dist` files for `fast-foundation` (`fast-foundation.js` and `fast-foundation.min.js`) and `fast-components` (`fast-components.js` and `fast-components.min.js`). A good way to compare before/after would be to build on `master` first, then copy these files to a separate directory. Then checkout this branch and rebuild. A diff tool should show changes to blank spaces in both HTML and CSS templates.
> Simplify tagged template literals transformer operations

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- CONTRIBUTING.md
Adds a `.vscode` directory and shared default settings for the project.
#3136
The settings we add to the file should only be for maintaining formatting consistency and relieving common cross-platform editor misconfigurations.
When #4001 is ready to be published, we can add it as a recommendation to the `extensions.json` list.
> add vscode settings and extension recommendations

- change/@microsoft-fast-tooling-react-2ba090cc-76d7-46bc-94ab-1c714065e140.json
- packages/tooling/fast-tooling-react/app/pages/navigation.tsx
- packages/tooling/fast-tooling-react/src/navigation/navigation-tree-item.props.ts
- packages/tooling/fast-tooling-react/src/navigation/navigation-tree-item.tsx
- packages/tooling/fast-tooling-react/src/navigation/navigation.props.ts
- packages/tooling/fast-tooling-react/src/navigation/navigation.spec.tsx
- packages/tooling/fast-tooling-react/src/navigation/navigation.tsx
- sites/fast-creator/app/web-components/index.tsx
This change:
- Adds the ability to set a default location for linked data (in the case of web components, this moves a component dropped onto another component to the default slot)
- Increases performance by caching node references during hover
- Ensures that nodes are rendered correcting by testing datasets
- Adding additional data types for more precision on what can be dragged, what can be dropped on, and what are essential non-interactive pieces of data for visual purposes only
The most effecting method for testing would be to build the project and run the Creator application, add a Card and attempt to use drag and drop in a variety of ways.
Unit tests have been added for the testable portions of the code. Due to drag and drop functionality being very hard to test this may require a …
> Various fixes to the Navigation Drag and Drop functionality

- sites/fast-creator/app/creator.tsx
- sites/site-utilities/src/components/editor/index.tsx
Modifying the createMonacoEditor() method in Site-Utilities to allow for the passing in of Monaco editor properties to add to or override the default creation options. Then taking advantage of this feature in Creator to increase the default editor font size from 14px to 16px.
closes #5062
> fix: increase monaco editor font size in creator

- change/@microsoft-fast-components-c5597c1e-f543-43d7-b641-cd05bb9ff7f6.json
- packages/web-components/fast-components/src/breadcrumb-item/breadcrumb-item.styles.ts
Fix vertical alignment of the breadcrumb item separator. In a similar way that `start` and `end` slots are aligned with `display: flex`.
Before:
After:
> fix(breadcrumb-item): add display flex to separator

- sites/site-utilities/src/schemas/definition-mapper.ts
Adds "Image" as an alias in the linked data control so that the user does not have to type "img".
> chore: add an alias for the image html element

- change/@microsoft-fast-components-66aebc9e-b20b-4e0d-88c6-8b0d1946c731.json
- packages/web-components/fast-components/src/tab-panel/tab-panel.styles.ts
> Tab panel display

- package.json
- yarn.lock
Remediation
Upgrade axios to version 0.21.2 or later. For example:
CVE-2021-3749
high severity
Vulnerable versions: <= 0.21.1
Patched version: 0.21.2
axios is vulnerable to Inefficient Regular Expression Complexity
wait-on depends on axios 2.21.1. when wait-on update the version of axios, it will resolve the entry to 2.21.4 version
> fix: security update axios from 0.21.1 to 0.21.4

- change/@microsoft-fast-tooling-react-1fb262fc-156c-4237-a8e4-f60816fb7f41.json
- packages/tooling/fast-tooling-react/src/form/form.style.ts
- sites/fast-creator/app/creator.tsx
- sites/fast-creator/app/preview/constants.ts
- sites/fast-creator/app/preview/preview.tsx
- sites/fast-creator/app/web-components/index.tsx
- sites/site-utilities/src/components/editor/editor.style.css
This change makes the following style updates:
- updates the width of the panes to 300px to allow:
- The color picker overlay to display without clipping
- The fast-tabs to display without clipping
- updates the width of the select to be as minimal as the longest piece of text content will allow
- updates the overflow on several elements where it was unneeded
- updates the form component to be display flex without relying on an outside element to set it
Run the Creator and Explore apps after building the project and test the desktop and mobile views to see the changes.
> fix: small updates to styling to correct for overflow issues

- change/@microsoft-fast-foundation-acdd6aa0-9f9c-41bf-8643-495db31d5a6c.json
- packages/web-components/fast-foundation/src/anchor/anchor.spec.ts
- packages/web-components/fast-foundation/src/anchor/anchor.template.ts
- packages/web-components/fast-foundation/src/breadcrumb-item/breadcrumb-item.spec.ts
- packages/web-components/fast-foundation/src/button/button.spec.ts
- packages/web-components/fast-foundation/src/button/button.template.ts
- packages/web-components/fast-foundation/src/dialog/dialog.spec.ts
- packages/web-components/fast-foundation/src/number-field/number-field.spec.ts
- packages/web-components/fast-foundation/src/number-field/number-field.template.ts
- packages/web-components/fast-foundation/src/text-area/text-area.spec.ts
- packages/web-components/fast-foundation/src/text-area/text-area.template.ts
- packages/web-components/fast-foundation/src/text-field/text-field.spec.ts
- packages/web-components/fast-foundation/src/text-field/text-field.template.ts
- yarn.lock
This fixes `aria-describedby` typos found in Anchor, Breadcrumb, Button, Dialog, Number field and Text Area templates as well as corresponding test and documentation files.
> fix aria-describedby typos

- change/@microsoft-fast-components-6681953d-c678-4b1c-821c-c71eff8483f9.json
- packages/web-components/fast-components/src/tree-view/tree-view.styles.ts
While investigating an unrelated bug I found this duplicated style block. This PR removes it.
> remove duplicate display hidden tree view

- change/@microsoft-fast-foundation-9449a6b8-433e-4cc4-9ac5-3a92b4590464.json
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/tree-item/tree-item.spec.ts
- packages/web-components/fast-foundation/src/tree-item/tree-item.template.ts
- packages/web-components/fast-foundation/src/tree-item/tree-item.ts
- packages/web-components/fast-foundation/src/tree-view/tree-view.spec.ts
- packages/web-components/fast-foundation/src/tree-view/tree-view.template.ts
- packages/web-components/fast-foundation/src/tree-view/tree-view.ts
This PR achieves the following:
1. Organizes selection and focus logic to be managed by the `TreeView`
2. Allows Disabled `TreeItem` to be focusable
3. Fixes Keyboarding bugs
Closes: #4925
> fix: ensure tree item selection is only managed in tree view

- sites/website/src/docs/design-systems/creating-a-component-library.md
- Fixes redirection on preview doc link
- Preview link was being redirected to 'not found page' due to missing prefix slash '/' in doc. [Link](https://www.fast.design/docs/design-systems/creating-a-component-library#composing-a-foundation-component)
> fix: update redirect preview doc link

- examples/design-system-tutorial/src/components/attribution.ts
- examples/design-system-tutorial/src/components/card/card.styles.ts
- examples/design-system-tutorial/src/components/navigation.ts
This PR removes a few references to Fluent that I missed in https://github.com/microsoft/fast/pull/5186. It also corrects a comment about card that I overlooked.
> remove references to fluent in design-system-example project

- change/@microsoft-fast-foundation-790197e1-feb0-4dea-b82e-255e7125e42a.json
- packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.ts
Adds scrollstart and scrollend events to the horizontal-scroll component.
> feat: Add scrollstart and scrollend events to the horizontal-scroll component

- change/@microsoft-fast-foundation-b2c8e484-69fc-4174-971b-99a810ef945b.json
- packages/web-components/fast-foundation/src/tree-item/tree-item.ts
Fixes nested tree items not able to be selected.
> fix: nested tree items not able to be selected

- change/@microsoft-fast-react-wrapper-a959ca07-d92b-4cb9-a857-97447e6390a9.json
Remove change file for react wrapper package to fix publish pipeline
> remove change file for private react wrapper package

- .github/workflows/cd-color-stage.yml
- .github/workflows/cd-explore-stage.yml
- .github/workflows/cd-publish.yml
- .github/workflows/cd-static-cdn.yml
- .github/workflows/cd-www-stage.yml
- .github/workflows/ci-daily.yml
- .github/workflows/ci-weekly.yml
Brings over more intuitive workflow naming to speed up finding status and notification service to discord for all continuous delivery workflows.
* Some users were not totally clear on what CD or CI acronyms are
* Some names are inherent. For example, we know it's FAST, why use it in the name
* Notifications were never working, this implements a known working solution
Relatively low-risk initial changes such that contributors or consumers of FAST have consistent paradigms in place when searching in our workflows, GitHub Actions.
FAST Creator and FAST Labs are good sources to see these same changes working.
> update workflows for consistency to match new implementations on new repositories

- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/color/recipes/contrast-set-recipe.ts
- packages/web-components/fast-components/src/color/recipes/focus-stroke.ts
- packages/web-components/fast-components/src/color/recipes/neutral-fill.ts
- packages/web-components/fast-components/src/color/recipes/neutral-foreground.spec.ts
- packages/web-components/fast-components/src/color/recipes/neutral-foreground.ts
- packages/web-components/fast-components/src/color/recipes/neutral-layer.spec.ts
- packages/web-components/fast-components/src/color/utilities/base-layer-luminance.ts
- packages/web-components/fast-components/src/color/utilities/color-constants.ts
- packages/web-components/fast-components/src/design-tokens.ts
Before making changes to the components I am updating certain recipes, the design token, and the utility files. These are global changes to most, if not all, of the components.
Updated dark mode to 0.09, this aligns with the Figma design
Updated the accent color to use `#80DEEA`
Update `focusStrokeOuter` to 5.5
Update base height to 8
Update`cornerCornerRadius` to 6
Update deltas on  a few design-tokens.
Add layer `layerCornerRadius`. This is used on components like menu and card.
Add `contrast-set-recipe` file. This will be used in the `strokeControlStrongRecipe`
I am using the button example to give an idea of the changes
before
after
> feat: update recipes, design tokens and utility files

- change/@microsoft-fast-react-wrapper-a136ae8c-93c1-453d-b6bb-520e4c8195c6.json
- packages/utilities/fast-react-wrapper/package.json
The `react` peer dependency requirement was `^16.9.0`, which gave errors if a user had a version of react other than the specified one. 
Changing the requirement from `^16.9.0` -> `>=16.9.0` would fix this.
> fix(react-wrapper): change peer dependency for react

- packages/web-components/fast-components/src/card/card.styles.ts
- packages/web-components/fast-components/src/styles/elevation.ts
Add elevationShadowCard recipe and token in the elevation file. 
Updated card to use the new elevationShadowCard design token.
before
after
> chore: visual refresh on card component

- packages/web-components/fast-components/src/flipper/flipper.styles.ts
- packages/web-components/fast-components/src/flipper/index.ts
Removed the accent color, updated it to use new visual states and SVGs.
before
after
> chore: visual refresh on flipper component

- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components/src/checkbox/fixtures/base.html
- packages/web-components/fast-components/src/checkbox/index.ts
- packages/web-components/fast-components/src/design-tokens.ts
Update the size to 18px. Also updated focus to use outline instead of box-shadow.
before
after
> chore: visual refresh on checkbox component

- change/@microsoft-fast-components-ce85fe24-cfca-4d69-a8e5-5a4ba3305d77.json
- packages/web-components/fast-components/src/flipper/flipper.styles.ts
Adds `pointer-events: none` to prevent clicks. 
Other option would be to place a `click` handler on the template and `stopPropagation`. But css approach seems less intrusive.
```ts
public clickHandler(e: Event & MouseEvent) {
if(this.disabled) {
e.stopImmediatePropagation();
}
}
```
Closes: #5385
> fix: disabled flipper button clicks

- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components/src/switch/fixtures/base.html
- packages/web-components/fast-components/src/switch/index.ts
- packages/web-components/fast-components/src/switch/switch.styles.ts
Changed the size to 28x18 and updated the radius.
Update the SVG.
before
after
> chore: visual refresh on switch component

- change/@microsoft-fast-components-60e17a5e-435d-4eec-a32b-6fb4cd488bdb.json
- packages/web-components/fast-components/src/tabs/fixtures/base.html
- packages/web-components/fast-components/src/tabs/tabs.styles.ts
Vertically aligns the `tablist` to the top so it does not jump around when tabpanels have various length content.
Closes: #5389
> fix: vertical tabs from jumping

- change/@microsoft-fast-foundation-ca19e06f-180e-4437-b817-bb79ba4e3992.json
- packages/web-components/fast-foundation/src/tree-item/tree-item.ts
- packages/web-components/fast-foundation/src/tree-view/tree-view.ts
Stop propagation when the `treeItem` is `disabled`
Closes: #5322
> fix: disabled tree items fire `selected-changed` event

- change/@microsoft-fast-foundation-fd64d993-4179-464d-b0d0-61d9e525c439.json
- packages/web-components/fast-foundation/docs/integrations/react.md
Updates React integration docs to address differences in how NodeJS environment variables are set on Windows.
> docs: React integration docs setup for windows

- .github/workflows/cd-www-production.yml
- .github/workflows/cd-www-stage.yml
On manual dispatch, this workflow will build and deploy from master branch into production for https://www.fast.design.
N/A
Will require merging in order to test.
Test in real world
> add workflow to release docs into production

- packages/web-components/fast-components/src/slider/fixtures/base.html
- packages/web-components/fast-components/src/slider/slider.styles.ts
> chore: visual refresh on slider component

- .github/workflows/cd-release-npm.yml
Update to use the correct file path.
The Discord notification is using an out-dated file path.
> update notification path for npm releases

- packages/web-components/fast-components/src/toolbar/toolbar.styles.ts
The change here is to add neutralForegroundRest to fix the foreground color on the text and icons and also update the focus design token.
before
after
> chore: visual refresh for toolbar component

- packages/web-components/fast-components/src/skeleton/fixtures/base.html
- packages/web-components/fast-components/src/skeleton/skeleton.styles.ts
> chore: visual refresh on skeleton component

- CONTRIBUTING.md
Correcting a link that got missed during previous docs fixes.
> docs: fix incorrect link in contributing.md

- sites/website/src/docs/apps-and-experiences/dependency-injection.md
> update docs to include package containing DI

- change/@microsoft-fast-element-f5b1a68a-a58f-4831-9cba-987d44ddf115.json
- packages/web-components/fast-element/docs/guide/using-directives.md
Adding a bit more clarity to `slotted` docs based on community feedback.
* #4293 
Just an update to some markdown.
n/a
Following up for FASTElement 2.0 to see if we can do something that makes slotted nodes sync in time for connect.
> docs(using-directives): clarify slotted directive practices

- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/calendar/calendar.styles.ts
- packages/web-components/fast-components/src/calendar/fixtures/calendar.html
- packages/web-components/fast-components/src/calendar/index.ts
- packages/web-components/fast-components/src/custom-elements.ts
Before (Default)
after
before 
after
before
after
> chore: visual refresh for calendar component

- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/custom-elements.ts
- packages/web-components/fast-components/src/picker/index.ts
- packages/web-components/fast-components/src/picker/picker-list-item.styles.ts
- packages/web-components/fast-components/src/picker/picker-list.styles.ts
- packages/web-components/fast-components/src/picker/picker-menu-option.styles.ts
- packages/web-components/fast-components/src/picker/picker-menu.styles.ts
Before (rest, hover, focused)
After
Before screenshot on the picked items
After
Before screenshot on the picker with picked items
After
> chore: visual refresh for picker component

- change/@microsoft-fast-foundation-04e57c90-6f61-45c2-bd68-eb3b0290373f.json
- packages/web-components/fast-foundation/src/slider-label/slider-label.ts
Updates code to use the `isNaN` function, rather than an equality check.  
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN#the_convenience_of_an_isnan_function
> Unlike all other possible values in JavaScript, it is not possible to use the equality operators (== and ===) to compare a value against NaN to determine whether the value is NaN or not, because both NaN == NaN and NaN === NaN evaluate to false. The isNaN() function provides a convenient equality check against NaN.
> Replace equality check with NaN with the Number.isNan function

- sites/website/src/docs/resources/cheat-sheet.md
Updates to Cheat Sheet including fixing broken links, typos, etc.
Related to https://github.com/microsoft/fast/pull/5458
> docs: cheat sheet updates

- change/@microsoft-fast-foundation-3f4619dc-5ea0-4b93-a226-fa75edcaa983.json
- packages/web-components/fast-foundation/docs/integrations/react.md
This PR adds a link to the GitHub issues discussing decorator incompatibility issues with create-react-app/babel and FAST.
closes #4503
> add link to issue describing decorator incompatibility issues with create-react-app

- change/@microsoft-fast-components-46cc9fbd-6d85-46bd-b0d8-fe2c6b022086.json
- change/@microsoft-fast-foundation-c3992cc9-646d-4b53-9685-04ec988d1039.json
- packages/web-components/fast-components/src/divider/divider.styles.ts
- packages/web-components/fast-components/src/divider/divider.vscode.definition.json
- packages/web-components/fast-components/src/divider/fixtures/divider.html
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/divider/divider.spec.md
- packages/web-components/fast-foundation/src/divider/divider.spec.ts
- packages/web-components/fast-foundation/src/divider/divider.template.ts
- packages/web-components/fast-foundation/src/divider/divider.ts
- sites/site-utilities/statics/assets/components/fast-divider.schema.json
Adds `orientation` to `divider`
Closes: #5492
> feat: add `orientation` to divider

- README.md
Updates the badges on the home page to be relevant for current GitHub Action CI/CD workflows.
Fix broken badge links across home page readme.
> update badges on home page to fix incorrect GH action references

- change/@microsoft-fast-components-30bb2667-0b95-4a7a-9e37-15cf7c78b17f.json
- change/@microsoft-fast-foundation-769f9dc9-d19f-486d-a069-13e71aad0c6a.json
- packages/web-components/fast-components/src/slider/fixtures/base.html
- packages/web-components/fast-foundation/src/slider/slider.ts
This removes the math rounding on the slider thumb position calculation so it shows smaller increments when the `min`/`max` range is large and the `step` is small. Since different browsers round to various decimal points the incremental animation will look different. Safari and FIrefox appear to have the highest tolerances while Chromium rounds lower.
Closes: #5507
> fix: allow slider to show small increment changes

- package.json
This change will pin the `checkchange` check in the github workflow to check for changes against the `features/fast-element-2` branch. Since the branch should only be checking PRs against its contents and not the default branch this is the current workaround for checking for changefiles against non-default branches. This change must be removed prior to inclusion to the default branch.
- Add an issue to remove this change in the feature branch tracking project (https://github.com/microsoft/fast/issues/5612)
> Pin the checkchange to the feature branch

- change/@microsoft-fast-element-08318f12-b72b-4832-b3d2-093ab5a7869a.json
- change/@microsoft-fast-element-08318f12-b72b-4832-b3d2-093ab5a7869b.json
- change/@microsoft-fast-element-08318f12-b72b-4832-b3d2-093ab5a7869c.json
- change/@microsoft-fast-element-08318f12-b72b-4832-b3d2-093ab5a7869e.json
- change/@microsoft-fast-element-08318f12-b72b-4832-b3d2-093ab5a7869f.json
- change/@microsoft-fast-element-08318f12-b72b-4832-b3d2-093ab5a7869g.json
- change/@microsoft-fast-element-08318f12-b72b-4832-b3d2-093ab5a7869h.json
- change/@microsoft-fast-element-08318f12-b72b-4832-b3d2-093ab5a7869i.json
- change/@microsoft-fast-element-08318f12-b72b-4832-b3d2-093ab5a7869j.json
- change/@microsoft-fast-element-422bda9e-1e66-46b2-a665-ca4e8a685cbc.json
- change/@microsoft-fast-element-422bda9e-1e66-46b2-a665-ca4e8a685cbd.json
These are the necessary change files for the current state of work for FAST Element 2.0. Subsequent changes will require a change file after a PR has been added to pin the `checkchange` to the feature branch.
Read the change files carefully and see if you agree with the wording/change type/package/etc.
- Add a PR to pin `checkchange` to the feature branch (#5611)
- Add an issue to remove `checkchange` pinning once feature branch work is complete (https://github.com/microsoft/fast/issues/5612)
> Added change files for FAST Element 2

- yarn.lock
Resolves and deduplicates the lockfile.
All builds and tests should complete and pass as normal.
> resolve lockfile

- beachball.config.js
- package.json
This change moves the branch specificity to beachball config to allow `yarn change` to target the feature branch and also removes the restriction on "major" change updates.
> Add branch pointing to config instead of package scripts

- packages/web-components/fast-ssr/.prettierignore
- packages/web-components/fast-ssr/package.json
This change adds prettier to the `@microsoft/fast-ssr` package.
Note: I ran prettier after the changes and it looks like the current files are gtg. This is more for future proofing.
> Added prettier to fast-ssr package

- change/@microsoft-fast-element-486e25bf-0f0b-42c6-adcc-8a0e99ed88a3.json
- packages/web-components/fast-element/.eslintrc.cjs
- packages/web-components/fast-element/src/dom.ts
- packages/web-components/fast-element/src/observation/array-change-records.ts
- packages/web-components/fast-element/src/observation/array-observer.ts
- packages/web-components/fast-element/src/templating/binding.ts
- packages/web-components/fast-element/src/templating/children.ts
- packages/web-components/fast-element/src/templating/compiler.ts
- packages/web-components/fast-element/src/templating/node-observation.ts
- packages/web-components/fast-element/src/templating/slotted.ts
- packages/web-components/fast-element/src/templating/view.ts
This change does the following:
- Allow `no-non-null-assertion`
- Fixes all other warnings and errors
@EisenbergEffect since these changes affect your work please take a close look, most of the changes are benign but I did move code around to best minimize ignoring the no-use-before-define issues.
> Fixed linting errors and warnings

- packages/web-components/fast-components/src/radio-group/radio-group.styles.ts
- packages/web-components/fast-components/src/radio/fixtures/base.html
- packages/web-components/fast-components/src/radio/index.ts
- packages/web-components/fast-components/src/radio/radio.styles.ts
Updated the size to 18px.
before unchecked
after unchecked
before checked
after checked
> chore: visual refresh on radio component

- packages/web-components/fast-ssr/package.json
- yarn.lock
This PR adds `chokidar` so that we can watch files and re-run the playwright tests. Playwright does not currently have a watcher for this purpose so `chokidar-cli` was added to facilitate this.
> Added watch script and chokidar

- change/@microsoft-fast-router-aa2ec3e2-c2e1-4b6c-8fbb-d42b1cd8f35a.json
- packages/web-components/fast-router/src/contributors.ts
- packages/web-components/fast-router/src/view.ts
This change updates `@microsoft/fast-router` so that it uses the new APIs available from `@microsoft/fast-element`. This unblocks part of the `yarn install` errors currently happening in the build gate.
Relates to #5641 
@EisenbergEffect could you take a look at these changes and verify this is the intended use for the updated `ElementStyles` and `ViewBehaviorTargets`.
> Update the fast-router with the updates to fast-element APIs

- change/@microsoft-fast-components-45865c97-bd37-4f7e-9658-a87af2ae2a75.json
- packages/web-components/fast-components/docs/api-report.md
This api report update comes after the work in #5648 where the installation was finally able to happen, this now allowed for the updates in FAST element 2.0 to update the api report for `@microsoft/fast-components`.
> Update the API report based on foundation updates for FAST element 2.0

- change/@microsoft-fast-foundation-69fea3de-fb85-4188-8a7c-f1f01ae49b0e.json
- packages/web-components/fast-foundation/docs/integrations/webpack.md
Added a missing whitespace to follow the formatting of the rest
> Add missing whitespace

- change/@microsoft-fast-components-23ba0437-b96e-482a-af0d-e0e52afe68f3.json
- change/@microsoft-fast-foundation-efa647d0-eb3b-4e8c-81e9-8cc140f9502e.json
- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/tooltip/fixtures/base.html
- packages/web-components/fast-components/src/tooltip/tooltip.stories.ts
- packages/web-components/fast-components/src/tooltip/tooltip.styles.ts
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/tooltip/tooltip.options.ts
- packages/web-components/fast-foundation/src/tooltip/tooltip.spec.md
- packages/web-components/fast-foundation/src/tooltip/tooltip.ts
This adds corner positions to the tooltip to allow for more options.
New positions include:
- top-left
- top-right
- top-start
- top-end
- bottom-left
- bottom-right
- bottom-start
- bottom-end
Fixed Positions:
Start / End:
Start / End RTL:
closes #5483 
Feedback: Are these location names good?
Please ensure that keyboard functionality, (toggling and Escape actions) work as expected.
> feat: add corner positions to tooltip

- sites/website/docusaurus.config.js
- sites/website/package.json
- yarn.lock
This PR includes the following:
- add breadcrumbs (see screenshots 1 and 2)
- add Docs link to navbar (see screenshots 3 and 4)
Docusaurus version was updated to 2.0.0-beta.16.
- this release introduces breadcrumbs: https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.16
- https://github.com/microsoft/fast/issues/5696
- https://github.com/microsoft/fast/issues/5697
None
---
**Screenshots:**
1 - breadcrumbs light mode
2 - breadcrumbs dark mode
3 - Docs link light mode
4 - Docs link dark mode
> docs: add breadcrumbs and doc link to navbar

- packages/web-components/fast-ssr/server/server.ts
- packages/web-components/fast-ssr/src/fast-command-buffer/index.fixture.html
- packages/web-components/fast-ssr/src/fast-command-buffer/index.ts
Adding a proof of concept FASTCommandBuffer component to the features/fast-element-2 branch. This component handles the buffering of user generated events on SSR rendered components that occur before the components can be hydrated and replays the events when they have.
To run the fixture page, navigate to the /packages/web-components/fast-ssr folder and run "yarn run build-server" and "yarn run test-server". Then browse to "http://localhost:8080/fast-command-buffer".
The red button on the left (button1) is configured to buffer click events and the right button (button2) click and mouseover events. Interact with the buttons and then click the "Fake hydrate" buttons. The events will be replayed which will write out the event info into the text area next to the "replay" button.
Closes #5666
> Add fast command buffer POC

- change/@microsoft-fast-components-928a5b39-d045-476c-a339-8268c157e03d.json
- packages/web-components/fast-components/package.json
Move html language service as dev dependency of fast components.
Fixes #5567
I set the type of change to `minor` as it change the dependency but I'm unsure about that.
> `vscode-html-languageservice` as dev dependency

- change/@microsoft-fast-react-wrapper-f4297b41-a114-4b2f-a6d1-4ae79ad9652d.json
- packages/utilities/fast-react-wrapper/src/index.spec.tsx
- packages/utilities/fast-react-wrapper/src/index.ts
Cache wrapper based on type and name.
Fixes #5746
the first commit add a test case proving the current code is broken.
Added a new wrapped component using a copy of an existing element.
> fix cache wrapper does not differentiate component-of-same-type-using-react-wrapper

- LICENSE
This PR updates the license header with verbiage approved by legal.
https://github.com/microsoft/fast/issues/5768
> update license header

- change/@microsoft-fast-element-a347a5ee-bd7e-4c8b-afd8-cc9eb668e804.json
- packages/web-components/fast-element/docs/guide/using-directives.md
A sample uses the assignment operator and should be an arrow function. Now we can send this code into space.
🚀
> Fixed a typo in a doc example

- change/@microsoft-fast-web-utilities-3a86d750-79f6-412b-a689-f1ec6c6a446b.json
- packages/utilities/fast-web-utilities/package.json
- sites/fast-color-explorer/package.json
- sites/fast-component-explorer/package.json
- yarn.lock
Updates the exenv-es6 dependency to ensure we resolve and lock to the version supporting es modules.
> update exenv-es6 to 1.1.1 to ensure we lock to es module support

- package.json
The latest work to support the CEM makes use of features added in node v15. LTS support has recently bumped up and this change ensures that folks are at least up to date with the minimum support (v15.0.0).
> add supported node engines in package.json to ensure contributors can build the repo

- change/@microsoft-fast-components-8064c5ea-bb37-43b9-8586-3d72ac3c24b6.json
- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/disclosure/index.ts
> set disclosure appearance attribute in connected callback to ensure the element can be constructed without error

- change/@microsoft-fast-components-04703961-05c0-403b-9c2b-5d8e3ef2e5fb.json
- packages/web-components/fast-components/__test__/.mocharc.json
- packages/web-components/fast-components/__test__/harness.mjs
- packages/web-components/fast-components/__test__/rollup.config.js
- packages/web-components/fast-components/__test__/server.mjs
- packages/web-components/fast-components/src/anchor/anchor.pw.spec.ts
- packages/web-components/fast-components/src/button/button.pw.spec.ts
- packages/web-components/fast-components/src/dialog/dialog.pw.spec.ts
- packages/web-components/fast-components/src/horizontal-scroll/horizontal-scroll.pw.spec.ts
- packages/web-components/fast-components/src/listbox/listbox.pw.spec.ts
- packages/web-components/fast-components/src/select/select.pw.spec.ts
- yarn.lock
Updates Mocha, Chai, and Playwright test harness scaffolding so Playwright testing will work again.
Fixes #5804.
All Playwright tests should run and pass in all browsers both locally and on CI. Note that the "Validate Platforms/Browsers" GH Action is set up to pass even if the steps actually failed, so please look at the "Test Playwright (<browser>)" step logs when reviewing.
Replace the Mocha/Express/Chai harness with `@playwright/test` (#5805)
> [fast-components] update playwright test harness and server modules

- packages/web-components/fast-ssr/package.json
- packages/web-components/fast-ssr/src/dom-shim.ts
- packages/web-components/fast-ssr/src/element-renderer/elemenent-renderer.spec.ts
- packages/web-components/fast-ssr/src/element-renderer/element-renderer.ts
- packages/web-components/fast-ssr/src/element-renderer/style-strategy.ts
- packages/web-components/fast-ssr/src/exports.ts
- packages/web-components/fast-ssr/src/styles/style-renderer.ts
- packages/web-components/fast-ssr/src/template-parser/template-parser.ts
- packages/web-components/fast-ssr/src/template-renderer/template-renderer.ts
- packages/web-components/fast-ssr/src/view.ts
- yarn.lock
This PR fixes up several small unrelated bugs I found stress-testing the SSR code w/ real world components. The changes include the following:
- expose the dom-shim from the package's `exports` field, allowing easy installation with `import "@microsoft/fast-ssr/install-dom-shim"
- Configures fast-elements task queue to operate synchronously.
- expanding the DOM shim with APIs leveraged by FAST components
- fixes element rendering when a template element is used by a custom element to bind to the element host
- fixes a bug where binding to classList of a native element did not emit the `class` attribute
- implements a style-strategy that allows retrieval of *all* styles applied to an element. This allows emitting *all* stylesheets applied to an element, not just the styles the element was …
> fix: ssr bug fixes

- sites/site-utilities/statics/server/server.js
Production sites occasionally have errors that have knocked them offline. It looks like something changed from Node 12 to Node 16 in the way errors are handled or perhaps PM2. Additionally, Azure has been updating East Region since last Friday when the first error was realized. Today Azure is updated West Region and the errors happened again. So it appears it may also be something with whatever is being upgraded on the Azure Platform.
In staging a robots file is created to deny crawler access. In production, this file is not needed because we want to crawl. But, when attempting  `fs.unlink` the error was breaking PM2 startup ability and resulting in 503 errors.  This PR solves this problem by instead of throwing an error, writing the error to the console, and gracefully continuing. 
On a …
> update to replace offending code causing 503 outages

- sites/fast-website/src/app/data/design-system.data.ts
This PR updates the design system links for:
- Fluent UI
- VS Code
> website: update design system links

- .github/workflows/ci-validate-platforms.yml
- .github/workflows/ci-validate-pr.yml
Attempts to add the yarn caching back into the build pipeline and update to v3.
n/a
> chore: add yarn cache to build

- .github/workflows/cd-deploy-color-staging.yml
- .github/workflows/cd-deploy-explore-staging.yml
- .github/workflows/cd-deploy-www-staging.yml
- sites/website/docusaurus.config.js
FAST websites have stopped pushing builds to Static Web Apps due to the limitation of 10 builds per Static Web App.  To work around this limitation, this change will only build the website when `sites/**/[site-name]` source code has changed. 
* Component Explorer
* Documentation
* Color Explorer
* Static Web Apps in PRs used to conveniently and quickly test websites have stopped working.
* Static Web App limits are being reached
* Static Web App deployment should be deleted upon PR closure
* Only deploy if the site files have changed
* Both explorers were missing destroy pr's, adding back in.
Testing procedures
1. Test pushing a change outside this package (expect ignore)
2. Test pushing a change inside this package (expect trigger)
3. Test pushing a workflow file change (expect trigger) …
> update workflow configuration for testing websites in pull requests

- change/@microsoft-fast-router-eb0276bc-5afa-40b4-9bbb-b48ac8740b7e.json
- packages/web-components/fast-router/README.md
This PR fixes the URL for the `npm version` badge for the fast-router. It was incorrectly pointing to fast-foundation, pulling in version info from the fast-foundation package.
> fix router version url on fast-router readme

- change/@microsoft-fast-element-95550d39-9c8c-4e02-9145-6e5ff25316da.json
- packages/web-components/fast-element/src/observation/array-observer.spec.ts
Fixing an issue related to a GH merge/non-merge thing.
None
Very small change in a test file to correct the problem.
Existing tests pass.
None at this time.
> fix: merge bug related to moved APIs

- change/@microsoft-fast-element-751fe02e-2247-4050-b738-7a9f48349f54.json
- packages/web-components/fast-element/docs/api-report.md
- packages/web-components/fast-element/src/index.ts
- packages/web-components/fast-element/src/templating/binding.ts
- packages/web-components/fast-element/src/templating/html-directive.ts
This PR stabilizes and documents the new binding APIs.
* Closes #5982 
This PR shuffles the binding code around, makes some naming changes, and adds documentation.
All existing binding tests continue to pass.
Additional PRs will add tests for some of the new APIs that were added a while back but don't yet have tests.
> feat: introduce binding mode and binding config define APIs

- sites/website/docusaurus.config.js
- sites/website/package.json
- yarn.lock
- Updated Docusaurus to the latest beta 2.0.0-beta.20
- In recent versions of Docusaurus, the `hideableSidebar` configuration option has [changed](https://docusaurus.io/docs/sidebar#hideable-sidebar). Changed `docusaurus.config.js` accordingly. 
- Set `autoCollapseCategories` to `true`, this keeps only one active sidebar category open. More about it [here](https://docusaurus.io/docs/sidebar#auto-collapse-sidebar-categories). This saves the user from having too many categories open and helps them focus on the selected section.
> docs: update docusaurus and config changes

- change/@microsoft-fast-ssr-53a23675-ae44-49d8-954c-dd87a429567e.json
- packages/web-components/fast-ssr/package.json
This PR pulls the `private: true` field off of the fast-ssr pacakge.json. This will allow us to publish the package to NPM.
It also modifies the package description.
> remove private field from fast-ssr

- packages/web-components/fast-ssr/package.json
This PR changes `@microsoft/fast-element` to a peer dependency for the `@microsoft/fast-ssr` package. This will help avoid dual-package issues and ensure that the version of fast-element used by the components is the same as the one used by fast-ssr.
> feat: change fast-element to peer dep in fast-ssr

- change/@microsoft-fast-ssr-13ec7f53-e846-46e1-890c-e36f781eeb32.json
- packages/web-components/fast-ssr/.npmignore
This PR updates the `@microsoft/fast-ssr` .npmignore file to ignore build config files, spec files, and the temp directory.
> update SSR npmignore file w/ new project structure

- README.md
- change/@microsoft-fast-router-368645c9-4e93-418a-83a7-73d35dad4c33.json
- packages/web-components/README.md
- packages/web-components/fast-router/README.md
Fixing up a few readme files in light of recent changes and additions.
n/a
Just some markdown to read.
n/a
Lots of documentation work to do over the coming weeks.
> docs: update a few readme files

- .github/workflows/cd-release-npm.yml
This PR temporarily disables through code comments the cronjob scheduler that runs nightly from Su-Th.
Job can still be launched through manual dispatch as needed, though it's not recommended during this time of temporary disablement.
> update to stop nightly publishing

- .github/workflows/ci-validate-platforms.yml
Adds a step to install Playwright browsers for the validate platforms CI process. This step aligns to the step in the validate PR CI process.
> install pw browsers validate platforms CI process

- sites/website/versioned_docs/version-legacy/components/getting-started.md
Replace custom badge that was generated from local packages w/ a badge from badge.fury.io
> fixing fast components badge path

- beachball.config.js
This removes the pinning to the feature branch for the beachball version updates.
Closes #5612
> Remove the branch specific logic for version updates

- beachball.config.js
- packages/tooling/fast-figma-plugin-msft/package.json
- sites/fast-color-explorer/package.json
- sites/fast-website/package.json
This change disallows a user from making major version updates when running beachball to update change files.
> Disallow major version updates

- change/@microsoft-fast-foundation-b0202bdc-91ce-4592-83ed-305b22ae7ae2.json
- packages/web-components/fast-foundation/README.md
Add change file to force `@microsoft/fast-foundation` version bump.
> foundation version bump

- change/@microsoft-fast-web-utilities-f880f76d-2d4a-48c1-81e6-ab05c0b201b5.json
- packages/utilities/fast-web-utilities/README.md
The `README.md` for `@microsoft/fast-web-utilities` is out of date and refers to a now removed export `getKeyCodes`. We no longer support that function nor do we support keyCodes and they were removed in the last version update.
> Updated README for usage of keyboard event keys

- packages/utilities/fast-benchmarks/benchmarks/fast-element/repeat/index.ts
- packages/utilities/fast-benchmarks/package.json
- packages/utilities/fast-benchmarks/scripts/index.js
- packages/utilities/fast-benchmarks/scripts/template.js
- packages/utilities/fast-benchmarks/src/clickTrigger10x.js
- packages/utilities/fast-benchmarks/utils/index.ts
- packages/utilities/fast-benchmarks/utils/query-params.ts
> add repeat benchmarks

- README.md
Small PR to fix a typo in the router's badge in the main readme file.
n/a
n/a
n/a
n/a
> doc: fix router badge in main readme file

- change/@microsoft-fast-foundation-95a55f8c-bf15-4eba-b928-5da6e11497f8.json
- packages/web-components/fast-foundation/src/radio-group/radio-group.spec.ts
- packages/web-components/fast-foundation/src/radio-group/radio-group.ts
This PR is a cherry-pick of #6052 with a modification of the changefile to support our prerelease status.
moves #6052 and closes #6050 in latest.
> fix: compare radio value property instead of attribute when value changes

- change/@microsoft-fast-element-91340a83-abd2-45f9-875e-35793ec54929.json
- packages/web-components/fast-element/src/templating/repeat.spec.ts
- packages/web-components/fast-element/src/templating/repeat.ts
REF: https://github.com/microsoft/fast/issues/5996
When items binding stays the same and recycle property is set to false on the repeat directive, views should be set to 0 and new views should be created. It should not reuse any existing views
https://github.com/microsoft/fast/issues/5996
https://github.com/microsoft/fast/issues/6096
> fix: when recycle is set to false while itemBinding stays the same, views should be recreated

- change/@microsoft-fast-foundation-d965f32f-5814-4495-9555-a8948dd7f839.json
- packages/web-components/fast-foundation/src/checkbox/checkbox.ts
Prevents keypress events from changing the checkbox with spacebar when readonly
closes #6105
> fix: prevent readonly checkbox keypress with space (fast-element-1 cherry pick)

- packages/web-components/fast-components/.storybook/preview-head.html
- packages/web-components/fast-components/docs/api-report.md
- packages/web-components/fast-components/src/accordion-item/accordion-item.styles.ts
- packages/web-components/fast-components/src/accordion/accordion.styles.ts
- packages/web-components/fast-components/src/avatar/avatar.styles.ts
- packages/web-components/fast-components/src/badge/badge.styles.ts
- packages/web-components/fast-components/src/breadcrumb-item/breadcrumb-item.styles.ts
- packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
- packages/web-components/fast-components/src/color/recipes/neutral-layer-2.ts
- packages/web-components/fast-components/src/color/recipes/neutral-layer-3.ts
- packages/web-components/fast-components/src/color/recipes/neutral-layer-4.ts
- packages/web-components/fast-components/src/color/recipes/neutral-layer-floating.ts
- packages/web-components/fast-components/src/color/utilities/base-layer-luminance.ts
- packages/web-components/fast-components/src/data-grid/data-grid-cell.styles.ts
- packages/web-components/fast-components/src/design-tokens.ts
- packages/web-components/fast-components/src/dialog/fixtures/dialog.html
- packages/web-components/fast-components/src/disclosure/fixtures/disclosure.html
- packages/web-components/fast-components/src/listbox-option/listbox-option.styles.ts
- packages/web-components/fast-components/src/styles/patterns/button.ts
A few changes I had locally for the visual update. I'm not sure what will happen with this work under the new component model, but I wanted to close it out.
> Visual update cleanup

- change/@microsoft-fast-foundation-f16f025d-52ef-4c87-b19d-4b14310d2951.json
Missed while merging - fixing up the changelog
> fix change file entry to prerelease type

- change/@microsoft-fast-foundation-191270ff-a804-4a51-85b3-ecd5192d664b.json
- packages/web-components/fast-foundation/src/slider-label/slider-label.ts
> fix: handle change for source.max set to sliderMaxPosition

- change/@microsoft-fast-foundation-b8abffa3-ee40-45b4-b3c2-b86222b16f17.json
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/horizontal-scroll/README.md
- packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.spec.ts
- packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.ts
> cherry pick horizontal scroll scroll-into-view fix into archives/fast-element-1

- change/@microsoft-fast-foundation-f16f025d-52ef-4c87-b19d-4b14310d2951.json
- packages/web-components/fast-foundation/src/checkbox/checkbox.spec.ts
- packages/web-components/fast-foundation/src/checkbox/checkbox.ts
* fix(fast-foundation): turn off indeterminate on checked change
Closes #6112
* Change files
* align with native user control
* Update .vscode/settings.json
* Update .vscode/settings.json
* Update change/@microsoft-fast-foundation-f16f025d-52ef-4c87-b19d-4b14310d2951.json
* test indeterminate removed
* add keypress test
> cherry-pick turn off indeterminate on checked change into archives/fast-element-1

- change/@microsoft-fast-foundation-191270ff-a804-4a51-85b3-ecd5192d664b.json
- packages/web-components/fast-foundation/src/slider-label/slider-label.ts
Cherry picks slider max-width change handling fix into fast-element-1 branch.
> fix: cherry pick slider max-width change handling fix into archives/fast -element-1

- change/@microsoft-fast-foundation-feba8c07-63e5-4317-8cba-e89c2fbfdd01.json
- packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.spec.ts
> chore: fixup cherry picked items for archive/fast-element-1 branch

- sites/website/src/docs/resources/browser-support.md
- sites/website/versioned_docs/version-legacy/resources/browser-support.md
This PR adds documentation specifying the support matrix for `fast-foundation`.
> update browser matrix to specify fast-foundation support

- build/get-package-json.js
- lerna.json
- package.json
- sites/fast-website/package.json
- sites/fast-website/src/app/index.ts
- sites/fast-website/webpack.common.js
- sites/fast-website/webpack.prod.js
- sites/website/src/generate-docs.js
- yarn.lock
The home page we broken, preventing us from making updates to our site and docs. This PR attempts to fix the issues.
n/a
I have removed the homepage from the workspaces configuration in order to enable it to depend on stable FAST package versions. Please check that I have done this correctly.
One of the packages is private, so I fixed that with a `file:` package dependency.
I then had to update several Webpack related configurations related to the Webpack 4 => 5 update.
I just ran the site and took a look. Looks good to me. Please check as well if you can.
We'll eventually need to update this to vNext but we should do that in conjunction with the homepage redesign work.
> fix: build and render issues with the homepage

- sites/website/versioned_docs/version-legacy/introduction.md
A bug was discovered in docusaurus that caused card links to cause 404 in certain scenarios. This PR simplifies the intro temporarily until there's a fix.
n/a
Just reverted the markdown to
Run the site and double check the offending scenarios.
We need to follow up with Docusaurus and see if they can fix the real bug.l
> fix: quick fix for the docs to avoid docusaurus card link bug

- change/@microsoft-fast-foundation-7f2c7978-f217-4e55-91e2-78015cceb552.json
- packages/web-components/fast-foundation/docs/integrations/react.md
- packages/web-components/fast-foundation/docs/integrations/webpack.md
Adding the recommended way to use custom element in React and adding a Babel configuration section under Webpack integration docs. 
https://github.com/microsoft/fast/pull/5957
> docs: add recommended way to use customElements in React, add Babel configuration in Webpack section

- change/@microsoft-fast-element-99c1b093-ba31-4a03-913e-483357af18b8.json
- change/@microsoft-fast-foundation-19c86288-f24f-4c7f-9f04-7959d185f3af.json
- change/@microsoft-fast-react-wrapper-cfd8ced6-69d1-48fd-9792-e04c750c8e65.json
- change/@microsoft-fast-router-ef3d46a8-8a83-4eb2-9195-b27dba553050.json
- packages/web-components/fast-element/src/templating/repeat.spec.ts
- packages/web-components/fast-element/src/templating/repeat.ts
REF: https://github.com/microsoft/fast/pull/6162
https://github.com/microsoft/fast/issues/6161
Adding the solution above to archives/fast-element-1
> fix(fast-element-1): only store views for next loop if it can't be reused right away

- change/@microsoft-fast-ssr-813281f9-b059-4907-adb8-c3fa69e740d9.json
- packages/web-components/fast-ssr/README.md
I missed this in reviewing https://github.com/microsoft/fast/pull/6206, so updating SSR docs to include `render` in the directive support table.
> chore: adds the render directive to the directive support table

- change/@microsoft-fast-foundation-6605102c-6913-4cea-83ca-ee1a6d921b06.json
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/tab/tab.template.ts
- packages/web-components/fast-foundation/src/tab/tab.ts
Adds start and end slot support for tab
closes #6213
> feat: add start end slots to foundation tab

- change/@microsoft-adaptive-ui-c42f4c4e-b1c3-464a-93fe-fa308986cdd4.json
- packages/utilities/adaptive-ui/src/color/swatch.ts
Tiny little bug swapping blue and green values.
> Adaptive UI: fix a color bug in Swatch

- packages/utilities/fast-benchmarks/benchmarks/fast-element/repeat/index.ts
- packages/utilities/fast-benchmarks/package.json
- packages/utilities/fast-benchmarks/scripts/template.js
- yarn.lock
upgrade tachometer to 0.7.0 version in fast-benchmarks
details here: https://github.com/microsoft/fast/issues/6223
https://github.com/microsoft/fast/issues/6223
> chore: upgrade tachometer to 0.7.0 version in fast-benchmarks

- yarn.lock
> chore: fix yarn lock removing private registry

- change/@microsoft-fast-foundation-634ac213-1cbd-426f-aaca-aaa29a9e7768.json
- packages/web-components/fast-foundation/src/tooltip/README.md
- packages/web-components/fast-foundation/src/tooltip/tooltip.ts
> fix: tooltip delay should always use nullable number converter for attr

- .vscode/settings.json
Updates the project's viscose settings file with the latest automatically-applied values.
This property value was updated and is now an object instead of a boolean. See the [default options](https://code.visualstudio.com/docs/getstarted/settings#_default-settings) page for the `editor.quickSuggestions` setting.
N/A
> Update default VS Code setting

- examples/ssr/package.json
- examples/todo-app/package.json
- yarn.lock
This PR updates the versions of the SSR example application so that it uses symlinked local package versions instead of installing the `@microsoft/fast-ssr` package from the NPM registry.
> fix fast-example app

- change/@microsoft-fast-foundation-8bb86cd1-2aae-4cc8-a340-e688a0b23920.json
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/design-token/custom-property-manager.ts
- packages/web-components/fast-foundation/src/design-token/fast-design-token.spec.ts
- packages/web-components/fast-foundation/src/design-token/fast-design-token.ts
This PR expands the structures assignable as DesignToken roots to include the 'PropertyTarget' types. This will facilitate SSR scenarios by allowing authors to register a `PropertyTarget` structure that can easily stringify the DesignToken CSS custom property values for the compilation context, injecting them into the SSR result wherever is appropriate. 
closes #6271
> feat: enable registration of PropertyTarget DesignToken roots

- package.json
We pulish the `archives/fast-element-1` updates via our Github Actions pipeline. Without configuration, the assumed origin is `origin/master` per the documents here: https://microsoft.github.io/beachball/cli/options.html#change-options. This has led to our branch being overwritten in the past whenever we've published archives/fast-element-1.
There is likely a better and more robust configuration solution we can use here to point to whatever the actual origin branch is to scale this out better, but I wanted to unblock publishing of this branch w/o needing to force-push back to master to reset the incorrect push that clobbers it after each publish.
> update branch for fe-1 feature branch to ensure publish changes do not push back to origin/master

- change/@microsoft-fast-foundation-7a4442fd-df6c-4eec-b71f-7c3562c2a461.json
- change/@microsoft-fast-ssr-36acebe8-db4b-486d-bd8d-732d5589467b.json
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/design-token/custom-property-manager.ts
- packages/web-components/fast-foundation/src/design-token/event-strategy.spec.ts
- packages/web-components/fast-foundation/src/design-token/event-strategy.ts
- packages/web-components/fast-foundation/src/design-token/exports.ts
- packages/web-components/fast-foundation/src/design-token/fast-design-token.ts
- packages/web-components/fast-ssr/src/dom-shim.spec.ts
- packages/web-components/fast-ssr/src/dom-shim.ts
This PR adds support for DesignToken in SSR environments. It does this by implementing a resolution strategy that uses custom events (supported in SSR) instead of manual DOM walking (not supported in SSR) to construct DesignTokenNode hierarchies. It also fleshes out the SSR DOM shim's CSSOM to support setting and removing properties on CSSStyleRules, which are used by DesignToken internally. 
closes #6287 #6272
> feat: support DesignToken in SSR

- change/@microsoft-fast-foundation-14d4f603-9786-4d4d-8db4-af050205e43e.json
Fix foundation changefile to enumerate a prerelease change.
> fix patch type on change file

- change/@microsoft-fast-foundation-dc08ca7b-be41-4f42-a66c-c0874376b4a2.json
- packages/web-components/fast-foundation/src/tabs/stories/tabs.stories.ts
- packages/web-components/fast-foundation/src/tabs/tabs.ts
This PR makes sure to focus on the first/last item that is _focusable_ on `home`/`end` key presses. I didn't add tests as there's still a todo for keyboard navigation tests in the test suite.
https://github.com/microsoft/fast/issues/6275
> fix(tabs): home and end navigation

- change/@microsoft-fast-foundation-eb26a2f6-c059-4ee2-bd81-3886503e454b.json
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/button/README.md
- packages/web-components/fast-foundation/src/button/button.ts
- packages/web-components/fast-foundation/src/combobox/README.md
- packages/web-components/fast-foundation/src/combobox/combobox.ts
- packages/web-components/fast-foundation/src/form-associated/form-associated.ts
- packages/web-components/fast-foundation/src/number-field/README.md
- packages/web-components/fast-foundation/src/number-field/number-field.ts
- packages/web-components/fast-foundation/src/search/README.md
- packages/web-components/fast-foundation/src/search/search.ts
- packages/web-components/fast-foundation/src/text-area/README.md
- packages/web-components/fast-foundation/src/text-area/text-area.ts
- packages/web-components/fast-foundation/src/text-field/README.md
- packages/web-components/fast-foundation/src/text-field/text-field.ts
Bringing changes from #6299 into `archives/fast-element-1` branch.
> Fix constraint validation in components (#6299)

- package.json
Fixes the change script to ensure CI runs against the correct branch
> fix change script for archives fast element 1

- change/@microsoft-fast-foundation-c8e72081-257f-474b-803b-0ae63fc25a83.json
- packages/web-components/fast-foundation/src/accordion/accordion.ts
Cherry-picks to resolve this issue in vCurrent
> fix: accordion item should not collapse on unrelated change events

- change/@microsoft-fast-foundation-ddd77b6f-946c-413d-b0b0-aba79ccc3f35.json
- packages/web-components/fast-foundation/src/switch/switch.ts
* ensure switch cannot be invoked via keyboard when in readonly mode
* Change files
> fix: ensure switch cannot be invoked via keyboard when in readonly mode

- change/@microsoft-fast-foundation-e49285a3-c26f-4a81-bb74-104f6f47c2ba.json
- packages/web-components/fast-foundation/src/flipper/flipper.template.ts
This PR updates the Flipper template to remove multiple uses of the `when` directive in favor of a singular template which can be dynamically created based on direction. The Flipper instance will only ever be either next or previous. This removes the multiple conditionals in favor of creating next and previous templates which can be cached and reused.
N/A
> feat: remove when directives in favor of singular template

- change/@microsoft-fast-foundation-95faec6c-6488-452a-8ec7-8229809fa914.json
- packages/web-components/fast-foundation/src/accordion-item/accordion-item.template.ts
- packages/web-components/fast-foundation/src/avatar/avatar.template.ts
- packages/web-components/fast-foundation/src/breadcrumb-item/breadcrumb-item.template.ts
- packages/web-components/fast-foundation/src/checkbox/checkbox.template.ts
- packages/web-components/fast-foundation/src/combobox/combobox.template.ts
- packages/web-components/fast-foundation/src/flipper/flipper.template.ts
- packages/web-components/fast-foundation/src/menu-item/menu-item.template.ts
- packages/web-components/fast-foundation/src/number-field/number-field.template.ts
- packages/web-components/fast-foundation/src/progress-ring/progress-ring.template.ts
- packages/web-components/fast-foundation/src/progress/progress.template.ts
- packages/web-components/fast-foundation/src/select/select.template.ts
- packages/web-components/fast-foundation/src/slider/slider.template.ts
- packages/web-components/fast-foundation/src/switch/switch.template.ts
- packages/web-components/fast-foundation/src/tree-item/tree-item.template.ts
This PR removes use of the the logical OR operator (`||`), a boolean logical operator, when setting default slotted content, in favor of the nullish coalescing operator (`??`). This is both a better application and should provide ever so slightly improved performance.
N/A
> update setting default slotted content with nullish coalescing operator

- change/@microsoft-fast-foundation-ec51332e-f013-4ae6-9471-cc619f17159e.json
- packages/web-components/fast-foundation/src/search/search.spec.ts
- packages/web-components/fast-foundation/src/search/search.ts
* chore: call change when clear button is clicked
* Change files
* Update change/@microsoft-fast-foundation-ec51332e-f013-4ae6-9471-cc619f17159e.json
Co-authored-by: Nicholas Rice <3213292+nicholasrice@users.noreply.github.com>
* Update change/@microsoft-fast-foundation-ec51332e-f013-4ae6-9471-cc619f17159e.json
Co-authored-by: Nicholas Rice <3213292+nicholasrice@users.noreply.github.com>
* Update change/@microsoft-fast-foundation-ec51332e-f013-4ae6-9471-cc619f17159e.json
Co-authored-by: Nicholas Rice <3213292+nicholasrice@users.noreply.github.com>
Co-authored-by: Chris Holt <chhol@microsoft.com>
Cherry picks #6274 into archives/fast-element-1 branch
> feat: [search] call change event when clear button is clicked (#6274)

- .github/workflows/ci-validate-benchmarks.yml
- packages/utilities/fast-benchmarks/benchmarks/fast-element/repeat/index.ts
- packages/utilities/fast-benchmarks/global.d.ts
- packages/utilities/fast-benchmarks/package.json
- packages/utilities/fast-benchmarks/scripts/template.js
- packages/utilities/fast-benchmarks/utils/index.ts
- There was a regression when the when benchmarks was added https://github.com/microsoft/fast/pull/6307, benchmark name was incorrectly generated in template.js. 
- Also simplifying the repeat benchmarks, there were too many queryParams to keep track of, many that are not being used. Reflecting this change in the github actions workflow.
- Added a global.d.ts and making sure it get's compiled along with the Observable benchmark, it was added under the observable folder previously, but deleted by gitignore rules. 
- Fixed a potential memory leak issue around where the id variable was defined, it should have been defined in the generateData function instead of the global scope.
https://github.com/microsoft/fast/pull/6307
> fix: bug in benchmarks producing unstable results 

- examples/ssr/package.json
- examples/ssr/server.js
- examples/todo-app/package.json
- examples/todo-app/src/design-tokens.ts
- examples/todo-app/src/main.ts
- examples/todo-app/src/todo-app.styles.ts
- sites/website/src/docs/design-systems/design-tokens.md
- yarn.lock
This PR updates the `DesignToken` documentation with API changes and new features. It also integrates `DesignToken` into the Todo app and SSR examples to illustrate DesignToken usage.
> chore: Update DesignToken documentation w/ updated API information

- change/@microsoft-fast-element-0e8f4ae8-2971-48e5-9d67-1030099517fc.json
- packages/web-components/fast-element/src/templating/repeat.spec.ts
- packages/web-components/fast-element/src/templating/repeat.ts
Ref: https://github.com/microsoft/fast/pull/6384
> fix: add persistent variable to correctly compare removeIndex against

- change/@microsoft-adaptive-ui-3c7fd1ff-e743-4ee8-a3c1-bb8744bff757.json
- packages/utilities/adaptive-ui/docs/api-report.md
- packages/utilities/adaptive-ui/src/color/palette-rgb.spec.ts
- packages/utilities/adaptive-ui/src/color/palette-rgb.ts
- packages/utilities/adaptive-ui/src/color/swatch.ts
- packages/utilities/adaptive-ui/src/color/utilities/luminance-swatch.ts
- packages/utilities/adaptive-ui/src/color/utilities/opacity.ts
- packages/utilities/adaptive-ui/src/design-tokens/color.ts
- packages/utilities/adaptive-ui/src/design-tokens/index.ts
- packages/utilities/adaptive-ui/src/design-tokens/layer.ts
- packages/utilities/adaptive-ui/src/elevation/recipe.ts
A slight refactoring of the previous `neutralLayer` recipes and tokens to be more general purpose.
Now supports both a "Fixed" set of recipes following the previous `neutralLayer`, etc. usage and an "Interactive" recipe following the `neutralFillLayer` tokens.
> Adaptive UI: add layer recipes and design tokens

- change/@microsoft-fast-foundation-4c1c84ee-317c-4812-b62e-0d0cec04eab3.json
- packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.template.ts
Removes class from template root of HS. Classes should not be on the template root `:host` style selectors should be used instead. This causes issues if you pass a class to the web component.
> fix: [horizontal-scroll] remove class on template root

- change/@microsoft-fast-ssr-d7cea42f-53ec-436e-8e9a-84018a61d554.json
- packages/web-components/fast-ssr/docs/api-report.md
- packages/web-components/fast-ssr/src/request-storage.spec.ts
- packages/web-components/fast-ssr/src/request-storage.ts
This PR adds `RequestStorageManager.uninstallDOMShim()` to support uninstalling the DOM shim installed by `RequestStorageManager.installDOMShim()`, reverting the overridden global getters back to their previous values.
It also updates the behavior to not install the DOM shim if the shim is already installed, which was not a case that was accounted for. 
Additionally, I've updated the implementations to throw if installation or uninstallation of the DOM shim fails (will happen if the properties being assigned are not configurable). Previously this would fail silently.
> feat: adds RequestStorageManager.uninstallDOMShim()

- change/@microsoft-fast-element-a08c159a-3a52-4a42-909e-1bdd7523ff11.json
- packages/web-components/fast-element/src/templating/binding.spec.ts
- packages/web-components/fast-element/src/templating/binding.ts
- packages/web-components/fast-element/src/testing/fakes.ts
Fixes an issue with token list bindings.
Internally tracked.
The real fix is a single typo correction (I will mark the line with a comment). The rest of the changes were made to clarify the code. 
Added tests to ensure correct functionality for token list bindings going forward.
n/a
> fix: tokenList bindings track adds and removes from multiple sources

- change/@microsoft-fast-foundation-788640ed-cd3b-4d9f-bedc-f179aae99903.json
- packages/web-components/fast-foundation/src/accordion/accordion.ts
* add activeid to accordion change event
* Change files
> feat: cherry pick add activeID to accordion change event

- change/@microsoft-fast-react-wrapper-126211af-f7f9-43f8-8199-8253675fd805.json
- change/@microsoft-fast-router-c1b81a38-41ff-427d-a41e-8b1183dc9d43.json
- packages/web-components/fast-element/src/components/attributes.ts
- packages/web-components/fast-element/src/platform.ts
> chore: fix prettier in archive

- change/@microsoft-fast-foundation-4b4b433b-fc2b-4777-a993-0554019f10a7.json
> update change file for floating-ui menu item

- change/@microsoft-fast-foundation-9eda75c8-6106-407b-9040-5989faee48ab.json
- packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.ts
Cherry-pick #6262 into archives
* hidden horizontal-scroll fix
* Change files
* Updating per Stephane's comments
* updating change file
> fix: hidden horizontal-scroll flippers disabled by default (#6262)

- change/@microsoft-fast-ssr-255509ef-5358-49b7-9e84-04b7451cc7ad.json
- packages/web-components/fast-ssr/package.json
This PR updates the path of the `main` field so that the `dist` directory is included in during publishing of the package. It appears newer versions of npm w/ workspaces exhibit different behavior when the path is relatively enumerated. When `./`, the `.gitignore` of the root package is somehow overriding the `.npmignore` file of the package.
This PR aligns the path with the other packages, which do not use `./`.
> fix: ensure fast-ssr dist files get published

- change/@microsoft-fast-ssr-0820ceb4-022f-43f3-b07e-6d3d8dcf5c38.json
- packages/web-components/fast-ssr/package.json
This PR adds an export path for RequestStorge to fast-ssr. This allows the RequestStorage infrastructure to be imported without configuring fast-element that happens during evaluation of the primary export path.
> feat: add RequestStorage export path

- change/@microsoft-fast-ssr-f84b8ea1-ab25-43b9-a402-05950d090422.json
- packages/web-components/fast-ssr/src/dom-shim.ts
This PR exports a few classes from the fast-ssr DOM Shim that were not being exported. It also refactors the shim code slightly to light up intilisense for the object returned from `createWindow()`.
> Fix: export features from DOM shim, refactor for better TypeScript support

- change/@microsoft-fast-ssr-f84b8ea1-ab25-43b9-a402-05950d090422.json
Fixes a change file so that dependentChangeType is "prerelease" to avoid version issues.
> fixing change file dependentChangeType

- packages/utilities/fast-benchmarks/package.json
- yarn.lock
Benchmark pipeline was experiencing consistent failures on the 'Report Benchmark' step. 
The reason for this was the outdated chromedriver package (105.0.0, now 107.0.0) that was installed in fast-benchmarks causing individual benchmarks to fail, thus not actually generating any reports in the Results folder for fast-benchmarks to report. 
The fix is to let tachometer install latest version of chromedriver when starting a benchmark run. Tachometer will do this step automatically if it does not find a chromedriver package already installed. This will replace manually including a version in the fast-benchmarks package. 
The typescript version in package.json was also updated from 4.6.2 to 4.7.2
> fix: remove chromedriver dependency from fast-benchmark

- change/@microsoft-fast-foundation-1eab34df-e56e-484b-95df-6fa33630a274.json
Corrects a malformed change file that would cause unintended package versioning.
> change dependent change type to prerelease

- change/@microsoft-fast-foundation-4f5bbfc3-b1c5-4f4c-84c8-9e7377398b1e.json
- packages/web-components/fast-foundation/src/tabs/tabs.template.ts
> fix: add css part for tabpanel in tabs

- change/@microsoft-fast-foundation-20de3d87-b3fb-4c11-bc22-8772672bafc9.json
> fixup incorrect change file from before we moved to prerelease

- CONTRIBUTING.md
Seems prudent as the project grows and we capture more industry talent to list the steering committee to help increase credibility and awareness.
The documentation site will require an update at https://www.fast.design to deploy these changes.
Tested using markdown rendered built into vscode.
> adds steering committee members by name

- change/@microsoft-fast-foundation-847086bd-78f2-42d8-ad46-df629e4e4bce.json
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/utilities/index.ts
- packages/web-components/fast-foundation/src/utilities/template-helpers.ts
This PR exports the `staticallyCompose` function added in https://github.com/microsoft/fast/pull/6577/files in addition to the type in order to enable others creating their own templates to make use of it.
n/a
> feat: export statically compose function

- packages/utilities/fast-benchmarks/benchmarks/fast-foundation/design-token/index.ts
- packages/utilities/fast-benchmarks/package.json
- packages/utilities/fast-benchmarks/scripts/template.js
- packages/utilities/fast-benchmarks/src/test10k.js
- packages/utilities/fast-benchmarks/tsconfig.json
> compare local ver to 2.26.10

- change/@microsoft-fast-foundation-aa48bf52-4327-4f40-bc59-f9990850cfbd.json
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/progress-ring/stories/progress-ring.register.ts
- packages/web-components/fast-foundation/src/progress-ring/stories/progress-ring.stories.ts
- packages/web-components/fast-foundation/src/progress/README.md
- packages/web-components/fast-foundation/src/progress/base-progress.ts
- packages/web-components/fast-foundation/src/progress/stories/progress.register.ts
- packages/web-components/fast-foundation/src/progress/stories/progress.stories.ts
Paused is currently a noop and only used with regard to visual appearances. Per our approach to not prescribing API's which are primarily related to the visual state of a control, I'm proposing we remove this attribute. Implementations which require a paused attribute can extend the class and add it with the following code:
```ts
export class MyProgress extends Progress {
/**
* Indicates the progress is paused
* @public
* @remarks
* HTML Attribute: paused
*/
@attr({ mode: "boolean" })
public paused: boolean;
}
```
n/a
> feat: remove paused attr from base progress

- change/@microsoft-fast-foundation-e5284c2e-f68d-4e6e-88e6-c7183539a426.json
- packages/web-components/fast-foundation/src/divider/divider.template.ts
This PR adds a slot to divider. As part of work to align with the Fluent team where possible on design system primitive templates, a quick audit shows this common across several design systems (Ant, Stardust, Fluent, to name a few). 
n/a
> feat: add slot to divider template

- change/@microsoft-fast-element-a1c7ab1e-b392-4878-a75d-396e82c3bd6c.json
- packages/web-components/fast-element/docs/api-report.md
- packages/web-components/fast-element/src/context.ts
- packages/web-components/fast-element/src/debug.ts
- packages/web-components/fast-element/src/di/di.ts
- packages/web-components/fast-element/src/dom-policy.ts
- packages/web-components/fast-element/src/dom.ts
- packages/web-components/fast-element/src/interfaces.ts
- packages/web-components/fast-element/src/metadata.ts
- packages/web-components/fast-element/src/pending-task.ts
- packages/web-components/fast-element/src/platform.ts
- packages/web-components/fast-element/src/utilities.ts
This PR continues the process of polish for fast-element 2.0 by reviewing the root files in the `src` folder for:
* Type correctness
* Missing code docs
* Import correctness
* A few random improvements/corrections
* Relates to #6502 
This is a basic set of changes across the root files in the `src` folder, making sure that everything is polished for a future release.
No changes to functionality. Existing tests continue to pass.
As I have time, I plan to continue a similar set of reviews across the entire fast-element codebase in preparation for release.
> fix: cleanup types, docs, etc. in root source files of fast-element

- change/@microsoft-fast-foundation-32fe028e-9bb0-436f-8b70-f6a631c94cc6.json
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/switch/switch.pw.spec.ts
- packages/web-components/fast-foundation/src/switch/switch.ts
Found some residual logic in switch setting classes on the host, this PR removes it.
> fix: remove class logic in checked change

- change/@microsoft-fast-foundation-848c548a-723d-4657-9096-b9896e9d2b73.json
- packages/web-components/fast-foundation/src/slider/slider.ts
- packages/web-components/fast-foundation/src/slider/stories/slider.register.ts
This change removes the focus management from `slider` because its not needed and it makes assumptions about how `:focus-visible` should be rendered.
Calling `.focus()`  will always force the component in a `:focus-visible` state. Removing these calls allows for more flexibility with focus styling.
- [ x] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.
> fix: [slider] remove focus management

- change/@microsoft-fast-foundation-19bde5a4-4383-4eab-9191-79bdf549c6f3.json
- packages/web-components/fast-foundation/src/slider-label/slider-label.ts
- packages/web-components/fast-foundation/src/slider/slider.pw.spec.ts
- packages/web-components/fast-foundation/src/slider/slider.ts
- packages/web-components/fast-foundation/src/slider/stories/slider.register.ts
Closes #5054 by changing the direction of the Slider thumb to instead increase value when sliding upward. This matches the native slider element when in vertical orientation.
#5054 
The slider should remain the same except for how the value is increased or decreased when it is in a vertical orientation.
No tests were affected by this change
> Changes how the Slider works in vertical orientation

- change/@microsoft-fast-web-utilities-8163e5c5-d4fb-4f87-a31c-1327532ed34f.json
- packages/utilities/fast-web-utilities/src/html.spec.ts
- packages/utilities/fast-web-utilities/src/html.ts
- packages/utilities/fast-web-utilities/src/numbers.spec.ts
- packages/utilities/fast-web-utilities/src/query.spec.ts
- packages/utilities/fast-web-utilities/src/rtl-scroll-converter.spec.ts
- packages/utilities/fast-web-utilities/src/strings.spec.ts
- packages/utilities/fast-web-utilities/tsconfig.json
Made changes in tsconfig.json and removed all the eslint errors. Made relevant changes and passed all the test cases.
I convert some parameters value to non-null values and made all the tests cleared. Removed Deprecated ```ClientRect``` and changed to ```DOMRect```.  Need to change the other ones also as there could be more.
> Turned on strictNullChecks, strictPropertyInitialization for fast-web-utilities

- change/@microsoft-fast-foundation-cafc5ae3-9c3e-4715-b923-5e7542e55091.json
- change/@microsoft-fast-foundation-e7783bb0-7855-4d04-ab33-e44b8e5c13a7.json
- packages/web-components/fast-foundation/src/design-token/design-token.spec.ts
- packages/web-components/fast-foundation/src/design-token/interfaces.ts
- sites/fast-website/package.json
This PR reverts the token update that broke fast component typings. #6530 
This was breaking the build and blocking the archives branch.
> revert: token update that broke fast component typings

- change/@microsoft-fast-foundation-d62d3983-0a2f-4aeb-ac8e-ce5809b7b7b8.json
- packages/web-components/fast-foundation/src/calendar/date-formatter.ts
> [cherry-pick] fix(Calendar): add fix for the timezones from #5539 

- change/@microsoft-fast-foundation-ed469427-61b6-4181-b3e6-d1afb71375ce.json
- packages/web-components/fast-foundation/docs/api-report.md
- packages/web-components/fast-foundation/src/slider/README.md
- packages/web-components/fast-foundation/src/slider/slider.ts
> fix: update slider changed methods to protected

- change/@microsoft-fast-foundation-f9588e53-7c01-4dfb-939d-9b48f8c7f06c.json
- packages/web-components/fast-foundation/package.json
This PR is to fix https://github.com/microsoft/fast/issues/6661
> fix `@microsoft/fast-element` version for Fast Foundation package

- yarn.lock
Should unblock `fast-element-1` for publishing. Not sure exactly why this unblocks but I did build `fast-foundation` before running `yarn` at the root. `yarn.lock` updated and seems to fix the build locally.
> fix: unblock archives branch

- sites/fast-website/src/app/index.ts
- sites/site-utilities/package.json
- yarn.lock
Updated dependencies that were out of sync in `fast/site-utilities`
> fix: fix fast-element-1 branch

- change/@microsoft-fast-web-utilities-182be69e-7f5f-409a-a74b-2b069de9000d.json
- packages/utilities/fast-web-utilities/src/rtl-scroll-converter.spec.ts
Removes flaky test which can be reproed here:
https://codepen.io/eljefe223/pen/oNPREaK
Seems like test always returns -0.5
> fix: removed flaky test

- .github/workflows/cd-release-npm.yml
> fix pipeline issue by installing specific version of node

- change/@microsoft-fast-element-ab2f57cd-8443-4b80-992b-53e40897dfe2.json
- change/@microsoft-fast-foundation-d6946c3b-14ca-4576-9732-80c8cdce93a4.json
- packages/web-components/fast-element/docs/api-report.md
- packages/web-components/fast-element/src/interfaces.ts
- packages/web-components/fast-element/src/observation/observable.ts
- packages/web-components/fast-element/src/templating/when.spec.ts
- packages/web-components/fast-element/src/templating/when.ts
- packages/web-components/fast-foundation/src/calendar/calendar.template.ts
- packages/web-components/fast-foundation/src/progress-ring/progress-ring.template.ts
- packages/web-components/fast-foundation/src/progress/progress.template.ts
- yarn.lock
Essentially a cherry-pick from the main branch but the implementation is different so this needs close review.
> [archive] add else case to when directive

- sites/fast-website/src/app/components/background-design/background-design.styles.ts
- sites/fast-website/src/app/components/color-swatch/color-swatch.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/side-navigation/side-navigation.template.ts
- sites/fast-website/src/app/css/header.css
- sites/website/docusaurus.config.js
> [chore: website] fixes a number of a11y issues identified with the docs site

- change/@microsoft-fast-element-2be9c6c0-08eb-4287-85a2-da4a1c7f8ed5.json
- packages/web-components/fast-element/src/components/element-controller.spec.ts
- packages/web-components/fast-element/src/components/element-controller.ts
This PR fixes a bug where behaviors that are added via a stylesheet were not being removed when the host stylesheet was removed. Instead of `removeBehavior`, `removeStyles` was invoking `addBheavior`. 
I corrected the call and added a test.
> fix: fixing bug causing behaviors not to be removed

- change/@microsoft-fast-foundation-e71f6ab0-358d-419f-a04e-112f06cf995e.json
- packages/web-components/fast-foundation/src/tabs/tabs.ts
Cherry-picks #6606 into the archives branch
#6718 as it pertains to stable
> fix: add default activeid value tabs

- change/@microsoft-fast-foundation-0b5947f9-c09e-4d5b-94ce-14674df74ae8.json
- packages/web-components/fast-foundation/docs/api-report.md
Updates the API report for fast-foundation
n/a
> chore: update api report for foundation

- .github/CODEOWNERS
A couple of weeks ago the Steering Committee voted to add additional/new Codeowners for the `fast-foundation` package. The following collaborators were nominated based on ongoing meaningful contributions, expertise, and their commitment to ensuring the success, quality, and continued progress of `fast-foundation`.
New codeowners for foundation:
- @scomea 
- @radium-v 
- @bheston 
- @KingOfTac
> chore: update codeowners for Foundation

- sites/website/docusaurus.config.js
remove algolia from docusaurus
> remove algolia from docusaurus in archive

- sites/website/docusaurus.config.js
Removes algolia from docusaurus
> remove algolia from docusaurus

- change/@microsoft-fast-foundation-aafd43b0-2ac5-4d27-84ce-7274ae1c3168.json
- packages/web-components/fast-foundation/src/menu/menu.ts
Updates the typing to fix an issue in the Menu component.
> fix: update typing for Menu to fix build issue in archive

- sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
- sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts
- sites/fast-website/src/app/components/section-header/section-header.styles.ts
- sites/fast-website/src/app/css/style.css
- sites/website/src/css/custom.css
This PR makes small UI changes and fixes to solve outstanding visual a11y bugs with the current documentation site.
n/a
> high contrast and wcag contrast bug fixes for docs

- .github/pull_request_template.md
With #6955 we no longer need this section of the PR template.
> Remove component section of the pull request template

- .github/CODEOWNERS
This change removes inactive code owners and adds active code owners.
This reflects more closely with current active collaborators on the project.
> Update codeowners file for current collaborators

- change/@microsoft-fast-foundation-2ef73bfd-1375-4187-9757-ed8841ea5edf.json
- packages/web-components/fast-foundation/src/menu-item/menu-item.template.ts
Closes #6848
This is a re-implementation of #6848 due to waiting on response from contributor.
> Remove unmatched closing div

- change/@microsoft-fast-foundation-1c121a16-ff09-467a-b789-87bc2a9a6fa9.json
- packages/web-components/fast-foundation/src/combobox/combobox.pw.spec.ts
- packages/web-components/fast-foundation/src/combobox/combobox.ts
This PR fixes the tests by converting them to Playwright from #6226. Closes #6226.
> fix: Various Combobox fixes with tests. (#6145) (updated)

- change/@microsoft-fast-foundation-2ef73bfd-1375-4187-9757-ed8841ea5edf.json
- change/@microsoft-fast-foundation-d724cbdd-e977-4a77-a52c-e7fc656dfe13.json
- change/@microsoft-fast-router-62d2da2f-c44c-43db-83a6-06364d07b601.json
- change/@microsoft-fast-ssr-f88fb881-5e8e-49cd-9339-b44baebaee7f.json
Some change files used incorrect change types, these have all been changed to prerelease.
> Normalize dependent change types

- change/@microsoft-fast-ssr-8176173d-9744-4690-9420-c31966e0b3b6.json
- examples/ssr/package.json
- package-lock.json
- packages/web-components/fast-ssr/package.json
This fixes a vulnerability with express for open redirects.
The SSR test site is not exposed publicly, nevertheless to close out some vulnerability alerts this change was made.
> Fix a dependency issue with express open redirect vulnerability

- change/@microsoft-fast-element-f2045996-cea9-48f5-9786-4a5e9a616135.json
- package-lock.json
- packages/web-components/fast-element/package.json
Pursuant to the update to tensile-perf https://github.com/microsoft/tensile-perf/pull/33, this change updates the tensile-perf dependency version to take those security updates.
> Update tensile perf dependency

- package-lock.json
Updates the package-lock file to latest using `npm install`. This does not change the package.json files.
Resolves https://github.com/microsoft/fast/pull/7017
> Update the package-lock to latest

- azure-pipelines-ci.yml
- change/@microsoft-fast-ssr-45005c89-fa17-44c9-b1ec-ef76c42e269e.json
- package-lock.json
- packages/web-components/fast-ssr/package.json
This change updates the playwright dependency and pipeline image to the latest version.
> Update playwright to latest

- change/@microsoft-fast-ssr-c6f5d944-52ae-4d8e-83bd-15737e17288b.json
- packages/web-components/fast-ssr/src/styles/fast-style.spec.ts
This PR attempts to address a flakey test in `@microsoft/fast-ssr` caused by the use of `getComputedStyle`.
> Address flakey test

- examples/todo-app/README.md
A simple fix for out-date todo-list example readme.md
> Update todo-app README.md

- packages/web-components/README.md
Fixes broken link in packages/web-components readme
Check the updated link
> fix broken link in packages/web-components readme

- sites/website/src/css/custom.css
This PR fixes light mode a11y bugs to ensure proper contrast
> chore: fix light mode vars to meet 4.5:1 contrast

- change/@microsoft-fast-element-f0154390-43e8-4542-a0bf-a82c9a579f9c.json
- change/@microsoft-fast-html-b0bf4637-05a5-4acf-8ce6-95af63490fd1.json
- packages/web-components/fast-element/src/components/hydration.spec.ts
- packages/web-components/fast-element/src/observation/arrays.spec.ts
- packages/web-components/fast-html/src/fixtures/children/children.spec.ts
- packages/web-components/fast-html/src/fixtures/repeat/repeat.spec.ts
Fixes a flaky test in the children directive in `@microsoft/fast-html`.
> Fix f-template children directive flaky test

- package-lock.json
This PR is from running `npm audit fix` to update some out of date dependencies that include security vulnerabilities.
> Fixes some out of date dependencies

- change/@microsoft-fast-html-0817e3ae-dd1a-4fee-862a-06082a5b231f.json
- package-lock.json
- packages/web-components/fast-html/README.md
- packages/web-components/fast-html/package.json
- packages/web-components/fast-html/rule-tests/attribute-directive.test.yml
- packages/web-components/fast-html/rule-tests/call-expression-with-event-argument.yml
- packages/web-components/fast-html/rule-tests/member-expression.test.yml
- packages/web-components/fast-html/rule-tests/tag-function-to-template-literal.yml
- packages/web-components/fast-html/rules/README.md
- packages/web-components/fast-html/rules/attribute-directives.yml
- packages/web-components/fast-html/rules/call-expression-with-event-argument.yml
- packages/web-components/fast-html/rules/member-expression.yml
- packages/web-components/fast-html/rules/tag-function-to-template-literal.yml
- packages/web-components/fast-html/sgconfig.yml
This PR adds some utilities for converting html tag templates to declarative HTML syntax.
This is a preliminary subset of rules that may be expanded on.
> Add some utilities for converting html tag templates

- change/@microsoft-fast-html-b91c600d-9520-4204-bf38-c5677e9b5a3b.json
- packages/web-components/fast-html/server/server.ts
- packages/web-components/fast-html/src/components/template.ts
We may provide a hook for this later, but at present time it triggers the CSP trusted-types duplication error.
> Remove setting dom policy during view template creation

- change/@microsoft-fast-html-d76fe901-b69f-49e7-8459-a48970d4947c.json
- packages/web-components/fast-html/src/components/utilities.spec.ts
- packages/web-components/fast-html/src/components/utilities.ts
This change fixes left hand chained expression logic to deal with operand precedence.
> Fix left hand expression logic

- change/@microsoft-fast-html-a2d018af-86e2-4f32-83cb-7b8a704c4bae.json
- packages/web-components/fast-html/src/components/schema.spec.ts
- packages/web-components/fast-html/src/components/schema.ts
- packages/web-components/fast-html/src/components/template.ts
See issue description.
Closes #7177
See linked issue next steps.
> Make all generated JSON schemas available via a static property

- change/@microsoft-fast-html-b5d79425-b16a-4147-b3ad-56aa0dacbf08.json
- packages/web-components/fast-html/src/components/utilities.ts
This change ensures that proxied data is matched with the JSON schema.
> Fixes an issue where object properties that are not present in the schema are proxied or observed

- change/@microsoft-fast-html-b4a1b5ed-9bf1-40af-a99b-760b8e8e478e.json
- packages/web-components/fast-html/src/components/utilities.ts
- packages/web-components/fast-html/src/fixtures/observer-map/observer-map.spec.ts
This change re-calls the logic to make items in an array observed when an item is added to the array. There might be some performance issues in this implementation.
> Fixes an issue where new items added to an array were not observed

- change/@microsoft-fast-html-fe962a44-2711-4c3d-b3f0-50653ce1a0be.json
- packages/web-components/fast-html/src/components/observer-map.ts
This check ensures that proxy checking will not result in an error if the object is null or undefined.
> Fixes an issue with undefined or null objects being checked for a proxy property
