microsoft/fast

packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/docs/guide/using-directives.md, packages/web-components/fast-element/src/directives/repeat.spec.ts, packages/web-components/fast-element/src/directives/repeat.ts, packages/web-components/fast-element/src/observation/observable.ts
This PR adds a `parentContext` property to the `ExecutionContext` which is now set by the `repeat` directive's behavior when it sets up its own per-item context. This enables nested repeat templates to access up the repeat context and always get to any higher level repeat or the root view model regardless of the level of nesting.
Closes #3848
=> feat(fast-element): enable parent context references in repeat scenarios

packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/tree-item/tree-item.spec.ts, packages/web-components/fast-foundation/src/tree-item/tree-item.template.ts, packages/web-components/fast-foundation/src/tree-item/tree-item.ts
In order to comply with https://www.w3.org/TR/core-aam-1.2/#mapping_actions. and enable some accessibility scenarios tree view items must be able to react to click events sent to the root of the component.  
Additionally this fix marks some handled key events with prevent default so that they don't trigger additional actions (I noticed space bar was triggering scrolls when I tested)
Fixes https://github.com/microsoft/fast/issues/3914
=> fix: tree view item should have a click handler on root element

sites/fast-component-explorer/app/explorer.style.ts
Added the high contrast foreground color on the pivot tab and the content panel to fix the text in high contrast white theme.
closes #3965 
After
=> fix: update high contrast light theme foreground color on pivot

packages/web-components/fast-element/src/template-compiler.ts
This is an internal refactoring of the template compiler to make the compilation context more explicit, reduce some duplication, and enable future nested calls to the compile function without messing up global state.
=> refactor(fast-element): clean up compilation context concept in compiler

sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
The text color was not changing when in high contrast white theme. Added forced-color query to set the color on text container to use `ButtonText`.
before
after
=> fix: update text on adaptive fast frame component to use high contrast foreground color

packages/web-components/fast-foundation/src/tooltip/README.md, packages/web-components/fast-foundation/src/tooltip/tooltip.template.ts
I noticed that tooltip was not positioning itself properly in our documentation sample at https://www.fast.design/docs/components/tooltip.
After some investigation I found that the component's internal attibute bindings were getting munged into a big string with no spaces:
After much poking around I was able to resolve the issue for tooltip by modifying the template to wrap all attribute value bindings in quotes:
```ts
vertical-positioning-mode="${x => x.verticalPositioningMode}"
```
instead of 
```ts
vertical-positioning-mode=${x => x.verticalPositioningMode}
```
I will open a tracking bug to investigate the issue further as technically we don't require the quotes and it isn't clear what is causing the tooltip template to break without them in our document environment.
Tooltip should …
=> fix: tooltip does not position correctly in documentation sample

packages/web-components/fast-components/src/accordion-item/accordion-item.styles.ts
Adds left-padding to the start element to prevent the focus border from overlapping it. The value is dependent on the design unit value.
This PR fixes #3881 by @scomea. 
Team, please advise whether this is a suitable solution or not.
=> fix: prevent overlap of focus border with start element contents

packages/web-components/fast-components/src/radio-group/fixtures/base.html, packages/web-components/fast-components/src/radio/fixtures/base.html, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/radio-group/radio-group.spec.ts, packages/web-components/fast-foundation/src/radio-group/radio-group.template.ts, packages/web-components/fast-foundation/src/radio-group/radio-group.ts, packages/web-components/fast-foundation/src/radio/radio.ts
If a developer tried to change a particular radio button in a radio group multiple times it would fail to change after the first change.
For input type='radio' there is a bit of a disconnect between the property checked and the attribute checked which is different than most of the other components (though Checkbox has this same behavior). 
* initially when radio group loads we need to look at the last radio with checked attribute and set the property to checked on that radio and set the checked property(NOT the attribute) to false on all the others.
* once that checked property is set, it can only be changed through the property and there is a disconnect between the checked attribute and the checked property.
Also fixed tabindexes when values are changed via code, they were not updated …
=> fix: allow child radio buttons to be changed multiple times from javascript

packages/web-components/fast-components/src/progress/progress.styles.ts
The progress bar was shifting the determinate and indeterminate element. To fix this, I use a box-shadow instead of a border.
Additional work was cleaning up the pause state, combining all the selectors into one rule.
closes #3966 
It's hard to tell, but if you zoom into the component, you can see the difference.
Before
After
=> fix: update high contrast outline color on progress bar

packages/web-components/fast-foundation/src/design-system-provider/design-system-provider.ts
This change adjusts the way the DesignSystemProvider's CSSCustomPropetyTarget is determined, expanding the usage of constructible stylesheets and unifying behavior between open and closed shadow roots.
The existing approach of directly manipulating the `adoptedStyleSheets` of the `shadowRoot` to append a CSSCustomProperty target relies on an open shadow root. When the shadowRoot is closed, CSS custom properties are applied via the `HTMLElement.style.setProperty()` API. We can improve this by utilizing the Controller's `addStyles()` API to perform the style attachment for us so that we don't require access to the shadowRoot. The DSP will still use the `HTMLElement.style.setProperty()` API in cases where constructible styles are not supported.
**Adding or …
=> fix: leverage FASTController.addStyles to attach css custom property target sheet

packages/web-components/fast-foundation/src/design-system-provider/design-system-provider.spec.ts, packages/web-components/fast-foundation/src/design-system-provider/design-system-provider.ts
This PR addresses several issues surrounding nested DesignSystemProviders where the nested provider's `designSystem` object did not contain all of the non-overriden information that the parent provider's `designSystem` contained. 
**Providers that only declared a sub-set of the parent providers DesignSystemProperties would only have the declared properties mirrored to the `designSystem` object.**
```html
<provider-a>
<provider-b></provider-b>
</provider-a>
```
where `<provider-a>` declares designSystemProperties of `a` and `b` and `<provider-b>` declares only `b`, instances of `<provider-b>` would only have `designSystem.b` availible.
Only declared properties of the parent provider were synced down in other cases, meaning multiple nesting of providers dissimilar declared properties would …
=> fix: designSystem property resolution behavior correction

packages/tooling/fast-tooling-react/src/form/controls/control.linked-data.tsx
Removed preventDefault() call in keydownHandler in linkedDataControl when key is tab, this prevented normal tabbing from occurring.
closes #3885 
=> fix: tabbing disabled for when linkedDataControl used in form

packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/controller.spec.ts, packages/web-components/fast-element/src/controller.ts
Adds the capability to add and remove a HTMLStyleElement to a custom element instance via the `Controller.addStyles()` and `Controller.removeStyles()` API. This provides an opportunity to hold a reference to a `CSSStyleSheet` that is attached to the custom element's shadowRoot, even when the shadow root is closed.
closes #4042.
=> feat: support HTMLStyleElement from Controller.addStyles and Controller.removeStyles

packages/web-components/fast-foundation/src/anchored-region/anchored-region.ts
Before anchored region starts up observers it would check to see if the anchor was actually a child of the viewport, but the "contains()" call it was using to verify this did not work with elements within a shadow dom and always returned false which prevented initialization in some scenarios.  Since anchored region now uses the document root as the intersection observer viewport this test isn't actually necessary, so took it out.
Anchored region should work for elements in a shadow dom
=> fix: remove anchored region "contains" test 

packages/web-components/fast-foundation/src/anchored-region/anchored-region.ts, packages/web-components/fast-foundation/src/utilities/direction.ts
The getDirection utility function would call .closest() on the parent node of the element node passed in.  This would throw an exception when .parent is null which happens when the node is a child of a shadow root (there may be other cases too).  Since I'm not sure why we call this on the .parent rather than the node itself I changed the function to use the param directly.
I also removed the local version of getDirection from the AnchoredRegion element and pointed at the utility code instead.  
The function should not throw, and should work correctly even if the element passed to the function is at the root of a shadow dom.  
=> fix: getDirection utility should not throw

sites/fast-website/src/app/components/fast-frame/fast-frame.ts
Recent `fast-radio-group` changes have caused the handler in fast-frame for the color swatches to be checking for the wrong instanceof type, now checking for FASTRadioGroup which should only get emitted when a change in the child radio components forces a change of the parent radio-group's value.
=> fix: colorswatch change handler was checking for the wrong type on the event target

packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/directives/binding.ts, packages/web-components/fast-element/src/directives/directive.ts, packages/web-components/fast-element/src/template.spec.ts, packages/web-components/fast-element/src/template.ts
Prior to this PR, the `html` tagged template helper was hard-coded to only capture attribute and property names if the interpolated value was a function. This PR changes the behavior so that the target name is captured for any directive that inherits from `NamedTargetDirective` of which `BindingDirective` is the only out-of-the-box example.
Note that `BindindDirective`s are created for function interpolated values, so there is no change in behavior for built-ins. However, this opens up the system for more extensibility. In particular, it enables the possibility of creating a two-way binding systems as a plugin.
In addition to this change, a typo was found in the `BindingDirective` which causes bindings to always be interpreted as non-volatile, regardless of the nature of the expression.
=> feat(fast-element): introduce NamedTargetDirective for extensibility

packages/web-components/fast-components/src/accordion-item/accordion-item.styles.ts, packages/web-components/fast-components/src/badge/badge.styles.ts, packages/web-components/fast-components/src/button/button.styles.ts, packages/web-components/fast-components/src/button/index.ts, packages/web-components/fast-components/src/checkbox/checkbox.styles.ts, packages/web-components/fast-components/src/flipper/flipper.styles.ts, packages/web-components/fast-components/src/menu-item/menu-item.styles.ts, packages/web-components/fast-components/src/progress-ring/progress-ring.styles.ts, packages/web-components/fast-components/src/progress/progress.styles.ts, packages/web-components/fast-components/src/radio-group/radio-group.styles.ts, packages/web-components/fast-components/src/radio/radio.styles.ts, packages/web-components/fast-components/src/skeleton/skeleton.styles.ts, packages/web-components/fast-components/src/slider-label/slider-label.styles.ts, packages/web-components/fast-components/src/slider/slider.styles.ts, packages/web-components/fast-components/src/styles/patterns/button.ts, packages/web-components/fast-components/src/switch/switch.styles.ts, packages/web-components/fast-components/src/tab/tab.styles.ts, packages/web-components/fast-components/src/tabs/tabs.styles.ts, packages/web-components/fast-components/src/text-area/index.ts, packages/web-components/fast-components/src/text-area/text-area.styles.ts, packages/web-components/fast-components/src/text-field/index.ts, packages/web-components/fast-components/src/text-field/text-field.styles.ts, packages/web-components/fast-components/src/tooltip/tooltip.styles.ts, packages/web-components/fast-components/src/tree-item/tree-item.styles.ts
Uses attribute selectors instead of the class selectors since it's not always easy to integrate.
To make the library more open for integration (e.g. React and Blazor) since we don't have to bother with the css classes.
- Fixes #4076
css classes can no longer be used.
=> feat: attribute selectors instead of class selectors

packages/web-components/fast-components/src/breadcrumb-item/breadcrumb-item.styles.ts, packages/web-components/fast-components/src/menu-item/menu-item.styles.ts, packages/web-components/fast-components/src/styles/patterns/button.ts, packages/web-components/fast-components/src/text-field/text-field.styles.ts, packages/web-components/fast-components/src/tree-item/tree-item.styles.ts
On buttons and menu-item, the start and end slots have fixed width and height. This will cause elements larger than 16px to clip.
This PR removes the fixed dimension on the start and end slot but keeps the 16px on the SVG.
I also updated the `grid-template-columns` property on the menu-item that will also cause clipping with elements that are larger than 42px.
This should not break any current implementation when using a `button`, `anchor`, or the `menu-item`. This will now allow authors to add larger elements to the start and end slots if the design calls for it.
fixes #3904 
=> fix: update start and end slot to remove fixed width and height

packages/web-components/fast-foundation/src/tabs/tabs.spec.ts, packages/web-components/fast-foundation/src/tabs/tabs.ts
If you would click twice on a same tab, the active indicator would lose track of the active tab, until you click twice again on another tab.
Have the active indicator always in sync with the actual active tab
=> fix: active indicator losing track if double click

packages/web-components/fast-foundation/src/form-associated/form-associated.ts
This change updates the feature-detection algo to check for an implementation of `ElementInternals` in the window, not just for the existence of the `ElementInternals` object. This is because Firefox nightly's window contains the `ElementInternals` object but does not contain an implementation of the `ElementInternals` API, causing invocations of API methods to throw at runtime.
Fixes #4086
=> fix: corrects ElementInternals feature detection

packages/web-components/fast-components/src/design-system-provider/README.md, packages/web-components/fast-components/src/menu/menu.styles.ts
Removed a couple of references to `elevated-corner-radius` which was never implemented in the new FAST design system provider.
Our default component styling does not rely on two different corner radius values. Perhaps this will change, but currently this is misleading.
=> chore: remove elevated-corner-radius which was not in use

.prettierignore, packages/web-components/fast-element/src/controller.spec.ts, packages/web-components/fast-element/src/controller.ts
It is currently very difficult to determine when exactly an element is added or removed from the DOM. Custom elements do have `connectedCallback` and `disconnectedCallback` but these are really only useful to the class implementation and not external code. There is no `connected` or `disconnected` events emitted, and it is [using MutationObserver for this case](https://stackoverflow.com/questions/44935865/detect-when-a-node-is-deleted-or-removed-from-the-dom-because-a-parent-was) is very difficult / expensive.
https://github.com/whatwg/dom/issues/533 tracks a proposal to patch `MutationObserver` with `connected` and `disconnected` records, but this feature has not made its way into implementation yet.
We *can* make "connectedness" easy to observe for `FASTElement` instances though, simply …
=> feat: makes Controller.isConnected an observable property

packages/tooling/fast-tooling-react/app/pages/form.tsx, packages/tooling/fast-tooling-react/src/form/controls/control.select.style.ts, packages/tooling/fast-tooling-react/src/style/css-properties.ts
Created a new css property called `FloatingCSSProperty` with the color of #3b3b3b. This is applied to the option in the select input dropdown. This fixes the issue where the background in the dropdown blends into the background of the pane. 
closes #3979 
before
after
=> fix: updated the background on attribute dropdown in fast tooling used in component explorer

packages/web-components/fast-components/src/flipper/flipper.styles.ts, packages/web-components/fast-components/src/menu-item/menu-item.styles.ts
Added color to the host selector in menu-item to fix high contrast white. Updated the high contrast selector in the flipper style to be set on a class instead of the attribute.
menu-item
before
after
flipper
before
after
=> fix: flipper icon and menu item text in high contrast mode

packages/web-components/fast-components/docs/api-report.md, packages/web-components/fast-components/src/radio/radio.styles.ts, packages/web-components/fast-components/src/slider-label/index.ts, packages/web-components/fast-components/src/slider-label/slider-label.styles.ts, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/radio/radio.ts, packages/web-components/fast-foundation/src/slider-label/slider-label.ts
This change fixes visual bugs in **radio**, **radio-group** and **slider-label**
A recent update changed all style selectors to be attribute based, this was problematic for radio as the checked attribute is on the internal proxy input element and checked styling was broken. Slider-label also suffered from the style attribute selector change, that has been updated to use internal but protected (so fluent-ui components can utilize them) styles, **horizontalStyles** and **verticalStyles**.
=> fix: revert radio to using class selector instead of attr, update slider-label to use internal styles for orientation

packages/web-components/fast-element/docs/guide/observables-and-state.md, packages/web-components/fast-element/src/index.ts
In response to some community questions, I've added a section to the documentation that covers array observation.
=> doc(fast-element): add section on array observation

packages/web-components/fast-components/src/listbox-option/listbox-option.styles.ts
This removes the hover effect for disabled option components as currently the hover affordance gives the perception that the option is still actionable.
Before:
After:
=> fix: remove hover for disabled options

packages/web-components/fast-components/src/button/button.styles.ts, packages/web-components/fast-components/src/styles/patterns/button.ts
Removed the contrast work from the button style and add the high contrast changes to the common button style. Now both button and anchor will get the high contrast changes.
fixes #4133 
=> fix: update high contrast colors in button and anchor components

packages/web-components/fast-components/src/listbox/listbox.definition.ts, packages/web-components/fast-components/src/listbox/scenarios/index.html, sites/fast-component-explorer/app/fast-components/configs/fast-listbox.ts, sites/fast-component-explorer/app/fast-components/configs/index.ts
Adds a scenario for the `<fast-listbox>` element.
=> chore: add listbox scenario

packages/tooling/fast-tooling-react/src/form/controls/utilities/dictionary.tsx
Adding a handler for the enter key in dictionary key fields that triggers a blur event instead of the default enter behavior.
Fixes: #2287 
=> fix: add enter key handler to dictionary keys

packages/tooling/fast-tooling-react/src/form/controls/utilities/dictionary.tsx
Setting the dictionary key input to readonly when the addtionalProperties flag is false. This prevents editing of fields which should only be removable.
Fixes: #2452 
=> fix: making dictonary key readonly on additionalProperties false

packages/web-components/fast-foundation/src/custom-properties/manager.ts
After upgrading the package version from 1.11.1 to 1.12.0 I found my website styles didn't work in Safari running on iPadOS (works fine on Desktop Firefox and Firefox/Chrome on Android). Found I was getting the following error:
```
TypeError: undefined is not an object (evaluating 'this.sheet.rules[this.sheet.insertRule(hostSelector)].style')
```
If I change the following line in fast-foundation/dist/esm/custom-properties/manager.js:
```javascript
this.customPropertyTarget = this.sheet.rules[this.sheet.insertRule(hostSelector)].style;
```
to:
```javascript
const key = this.sheet.insertRule(hostSelector);
this.customPropertyTarget = this.sheet.rules[key].style;
```
Then the styles are working again.
Call insertRule before using it as an object key. Although by my understanding this should …
=> fix: fix type error in custom property manager running on safari

packages/web-components/fast-components/src/select/select.styles.ts
Sets the `fast-select` height to use `heightNumber` instead of allowing it to use intrinsic sizing.
Closes #4145.
=> fix: clamp fast-select height and set its box sizing

packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/package.json, packages/web-components/fast-foundation/src/button/button.spec.ts, packages/web-components/fast-foundation/src/checkbox/checkbox.spec.ts, packages/web-components/fast-foundation/src/checkbox/checkbox.ts, packages/web-components/fast-foundation/src/custom-properties/manager.spec.ts, packages/web-components/fast-foundation/src/design-system-provider/design-system-provider.spec.ts, packages/web-components/fast-foundation/src/dialog/dialog.spec.ts, packages/web-components/fast-foundation/src/fixture.spec.ts, packages/web-components/fast-foundation/src/form-associated/form-associated.spec.ts, packages/web-components/fast-foundation/src/form-associated/form-associated.ts, packages/web-components/fast-foundation/src/listbox/listbox.ts, packages/web-components/fast-foundation/src/radio-group/radio-group.spec.ts, packages/web-components/fast-foundation/src/radio/radio.spec.ts, packages/web-components/fast-foundation/src/radio/radio.ts, packages/web-components/fast-foundation/src/select/select.spec.ts, packages/web-components/fast-foundation/src/select/select.ts, packages/web-components/fast-foundation/src/slider/slider.spec.ts, packages/web-components/fast-foundation/src/switch/switch.spec.ts, packages/web-components/fast-foundation/src/switch/switch.ts, packages/web-components/fast-foundation/src/tabs/tabs.spec.ts, packages/web-components/fast-foundation/src/tabs/tabs.ts, packages/web-components/fast-foundation/src/text-area/text-area.spec.ts, packages/web-components/fast-foundation/src/text-field/text-field.spec.ts
* fix broken `FormAssociated` tests on Firefox
* make sure tests are asynchronous and that each scenario cleans up after itself
* fix a `select` test that was incorrectly using native browser elements
All of the `FormAssociated` tests were working in Chromium but failing in Firefox. There were also some tests that used timeouts and others that didn't utilize async fixture methods. Tests can use the fixture's `parent` and `document` to attach elements like forms when needed, and all fixture-based tests should call `disconnect()` or remove any attached elements at the end of each scenario.
=> fix: formassociated and async tests on firefox

packages/web-components/fast-foundation/src/anchored-region/anchored-region.spec.md, packages/web-components/fast-foundation/src/anchored-region/anchored-region.ts
Anchored region now emits a "loaded" event when it has been positioned and children rendered.
Make it easier for developers to know when child elements are available in the DOM
=> feat: add loaded event to anchored region

packages/web-components/fast-foundation/src/dialog/dialog.ts
This PR corrects a common JS "oopsie" with an event handler in the `dialog` implementation.
Fixes #4105 
I didn't add more tests for dialog. I'm wondering whether we should and what those might look like. Given the nature of this bug, I'm not sure that tabbable was working correctly with the dialog ever. Though, I don't know how tabbable works so I may not be the best person to make that assessment.
Reviewing the code while fixing this bug, I wonder that the mutation observer and `tabbable` functionality should not be hooked up in connect/disconnect, but rather on show/hide of the dialog. I don't know much about how `tabbable` work though.
I also noticed the use of `KeyboardEvent#keyCode` which is deprecated. We might want to make a survey of our components and update anything that uses …
=> fix(dialog): accidental improperly bound this in callback

packages/web-components/fast-components/src/select/select.styles.ts
The Select button's glyph should be styled the same as its container.
=> fix: select indicator glyph sizing

packages/web-components/fast-foundation/src/anchor/anchor.ts, packages/web-components/fast-foundation/src/button/button.ts, packages/web-components/fast-foundation/src/listbox/listbox.ts, packages/web-components/fast-foundation/src/select/select.ts, packages/web-components/fast-foundation/src/text-field/text-field.ts
This PR fixes an issue where global aria attributes are not syncing state.
Fixes https://github.com/microsoft/fluentui/issues/16121
Several of the attribute mixins were applied through mixin inheritance. However, the `applyMixins` helper only copies own properties of the prototype. After some discussion @nicholasrice and I decided the best course of action was to not change the `applyMixins` function (could have some unexpected consequence for consumers) but to use it to apply the base mixins instead of using inheritance. This should provide for the highest compatibility with existing code.
Note: This is a temporary fix. We hope to provide a new feature in fast-element to allow templates to hook into observation of built-in attribute changes without re-defining the aria properties like …
=> fix(fast-foundation): ensure global aria attrs are applied

packages/web-components/fast-components/docs/api-report.md, packages/web-components/fast-foundation/src/anchored-region/anchored-region.spec.md, packages/web-components/fast-foundation/src/anchored-region/anchored-region.ts, packages/web-components/fast-foundation/src/tooltip/tooltip.ts
Minor fixes to anchored region that came to light while putting [nested menus](https://github.com/microsoft/fast/pull/4142) together. 
- use document root element to calculate default viewport as intersection event rootbounds prop doesn't take things like toolbars into account.
- "change" event becomes "positionchange" and no longer bubbles
- threshold attributes default to undefined
bug fixes
=> fix: anchored region default viewport

packages/web-components/fast-components/docs/api-report.md, packages/web-components/fast-components/src/anchor/index.ts, packages/web-components/fast-components/src/button/index.ts, packages/web-components/fast-components/src/styles/patterns/button.ts, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/anchor/anchor.template.ts, packages/web-components/fast-foundation/src/anchor/anchor.ts, packages/web-components/fast-foundation/src/button/button.template.ts, packages/web-components/fast-foundation/src/button/button.ts
This PR adds a feature that dynamically adds an "icon-only" class to the anchor element within the anchor component when its content is an SVG element.
This feature will give the ability to add additional styles to icon-only anchor components.
=> feat: add default slot changed to anchor

packages/tooling/fast-tooling-react/src/form/custom-controls/control.css-ref.props.ts, packages/tooling/fast-tooling-react/src/form/custom-controls/control.css-ref.tsx, packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.props.ts, packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.syntax.tsx, packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.tsx, packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.type.tsx, packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.value.tsx, packages/tooling/fast-tooling/src/data-utilities/mapping.mdn-data.ts
Syntaxes are provided in the same reference format as CSS properties and therefore can take advantage of the same `<CSSRef />` component. This change redirects syntax types to use this component.
This creates re-usability so that, for example, if the same `refCombinatorType` of `exactlyOne` generates a select for a CSS property, it will generate a select for a referenced CSS syntax.
Works on a list item in the related issue #4174
=> feat: use the CSSRef component for syntaxes

packages/web-components/fast-components/src/menu-item/menu-item.definition.ts, packages/web-components/fast-components/src/menu/fixtures/menu.html, packages/web-components/fast-components/src/menu/scenarios/index.html, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/menu-item/menu-item.spec.ts, packages/web-components/fast-foundation/src/menu-item/menu-item.ts, packages/web-components/fast-foundation/src/menu/menu.spec.ts, packages/web-components/fast-foundation/src/menu/menu.ts
Menu items in the same menu with the role "menuitemradio" should behave as "radio groups" allowing only one item of the group to be selected at a time.  Elements with a role of "separator" placed between radio menu items serve to break up radio buttons into independent groups.
Menu items with role of "menuitemradio" must follow a group selection behavior as per https://www.w3.org/TR/wai-aria-1.2/#menuitemradio
=> feat: add radio group functionality to menu items

packages/web-components/fast-foundation/src/tabs/tabs.spec.ts, packages/web-components/fast-foundation/src/tabs/tabs.ts
When setting the _last_ tab to `disabled`, the active indicator would not show up at all. This PR is to fix that
=> fix: display active indicator when tab is disabled

packages/web-components/fast-foundation/src/button/button.template.ts
Added `class="content"` to content span in button template.
In both the FAST and FluentUI lightweight button, the underline on hover and focus is missing. The style for the underline is using `content::before` selector, so adding the content class fixes the issue.
This should fix both FAST and FluentUI.
#4201 for FAST
#16271 for fluentui
=> fix: add class content to fix missing underline on button component

package.json, packages/web-components/fast-components/package.json, packages/web-components/fast-components/src/mocha-typings.d.ts, packages/web-components/fast-components/src/select/select.spec.ts, packages/web-components/fast-components/test/.mocharc.json, packages/web-components/fast-components/test/fixtures/iife.html, packages/web-components/fast-components/test/fixtures/index.html, packages/web-components/fast-components/test/harness.js, packages/web-components/fast-components/test/rollup.config.js, packages/web-components/fast-components/test/tsconfig.json, packages/web-components/fast-components/tsconfig.json, yarn.lock
- add override configs to the `fast-components/test` directory to allow for a node-focused environment
- spawn an express server before running mocha tests and stop it after completing all tests
New `package.json` commands in `fast-components`:
- `yarn clean:test`: clean the `test/dist` directory
- `yarn test:build-tsc`: build spec modules for mocha, outputs to `test/dist`
- `yarn test:build-rollup`: build un-minimized and source-mapped bundles, to be loaded in the playwright browser page instance
- `yarn test:mocha`: run all tests found in `test/dist` with the `test/.mocharc.json` configuration file
- `yarn test:playwright`: run each command above, in order
To avoid conflicts with tests that already exist in `src/color`, the `test:playwright` workflow ignores those files, and the …
=> (features/playwright-integration): add harness script and configs for ts, mocha, rollup

packages/web-components/fast-components/src/listbox-option/listbox-option.styles.ts, packages/web-components/fast-components/src/listbox/listbox.styles.ts, packages/web-components/fast-components/src/select/select.styles.ts
Set color on option component to fix high contrast white.
Removed the hover selector in listbox so the background on the item changes color and not just the border.
Fixed broken hover on select and focus on its listbox. Also fix the color of the indicator.
before
after
=> fix: address broken high contrast colors on listbox and select components

packages/web-components/fast-components/src/slider/fixtures/base.html, packages/web-components/fast-components/src/slider/slider.styles.ts
Closes #4222 
Note: There is no `.slider` class on this component's template, so the css `.slider ` selector was not targeting anything. The disabled cursor still works on the labels and the forcedColors cursor style can be removed with this change as well.
Before:
After:
High Contrast:
=> fix: slider disabled and readonly cursor styles

packages/utilities/fast-web-utilities/src/dom.spec.ts, packages/utilities/fast-web-utilities/src/dom.ts
Detects and uses a nonce when testing `canUseFocusVisible`
Some pages set a CSP nonce for security. This would block the temp stylesheet created by canUseFocusVisible. Instead, use the same approach as JSS and detect/use a page's nonce if found.
=> fix: Allow nonce usage in canUseFocusVisible

packages/web-components/fast-components/docs/api-report.md, packages/web-components/fast-components/src/color/index.ts, packages/web-components/fast-components/src/color/neutral-contrast-fill.ts, packages/web-components/fast-components/src/design-system-provider/index.ts, packages/web-components/fast-components/src/fast-design-system.ts, packages/web-components/fast-components/src/styles/recipes.ts
Created a new fill recipe that would be inverted on a light or dark theme. This fill color would be dark on light theme and light on dark theme. 
I also created `neutralContrastForegroundRestBehavior ` a foreground behavior to use as a color with this recipe 
=> feat: add an inverse color recipe called neutral-contrast-fill

packages/web-components/fast-foundation/src/data-grid/README.md, packages/web-components/fast-foundation/src/data-grid/data-grid-row.template.ts, packages/web-components/fast-foundation/src/data-grid/data-grid.template.ts
Datagrid sample wasn't working in our doc site.  In the process found some issues with malformed templates that likely explain some other data grid bugs.  
Samples should work.
https://github.com/microsoft/fast/issues/4325
=> fix: datagrid doc sample and malformed templates

packages/web-components/fast-foundation/src/accordion/accordion.ts
This adds a simple focus handler on the accordion item so when the accordion item is focused via tabbing it correctly updates the activeItemIndex and activeid to keep the keyboard arrow events in sync.
closes #4330 
=> fix: add focusItem handler to update activeItemIndex when item is focused

packages/web-components/fast-components/src/accordion/fixtures/base.html, packages/web-components/fast-foundation/src/accordion/accordion.ts
Added focusable content to default example
Added check for target to equal current target before handling accordion item key down event.
If the event.target and event.currentTarget are the same then the arrow key press happened on the accordion itself, which is the event we want to act on with arrow up/down keys.
Note: this _also_ makes focus _not_ move if it is on one of the start or end items in the accordion header. I believe this is the appropriate response, as that is focusable content so  the accordion item key down handler should not act on that. Only if the actual accordion item is focused do we want the arrow keys to move focus between accordion items.
closes #4326 
=> fix: accordion arrow key press moves focus from content to accordion header

package.json, yarn.lock
Update node-notifier to latest version 9.0.0
CVE-2020-7789
moderate severity
Vulnerable versions: < 8.0.1
Patched version: 8.0.1
This affects the package node-notifier before 8.0.1. It allows an attacker to run arbitrary commands on Linux machines due to the options params not being sanitised when being passed an array.
node-notifier version 6.0.0 to version 9.0.0
To solve dependabot alert
This solve security issue
=> fix: upgrade node-notifier to version 9.0.0

packages/tooling/fast-tooling/src/data-utilities/mapping.vscode-html-languageservice.spec.ts, packages/tooling/fast-tooling/src/data-utilities/mapping.vscode-html-languageservice.ts
This fixes an issue where the `slot` HTML attribute was added to the data, however this is already taken care of in the mapped `DataDictionary` structure and thus can result in duplicates.
=> fix: remove redundant slot from DataDictionary when mapping an HTML string

packages/web-components/fast-components/src/text-field/fixtures/text-field.html, packages/web-components/fast-foundation/src/utilities/utilities.spec.ts, packages/web-components/fast-foundation/src/utilities/whitespace-filter.ts
The whitespaceFilter in utilities was filtering out anything that was not a TEXT_NODE.
It should return true if the item is an element, so that it doesn't filter elements out.
- Updated filter to check for type of non TEXT_NODE
- Added an example to Text-Field to test that using a <span> element as a label is not filtered out.
- Added tests for whitespaceFilter
=> fix: whitespaceFilter filtering elements

packages/tooling/fast-tooling/src/message-system-service/message-system.service.ts, packages/tooling/fast-tooling/src/message-system-service/monaco-adapter.service.ts, packages/tooling/fast-tooling/src/message-system-service/shortcuts.service.spec.md, packages/tooling/fast-tooling/src/message-system-service/shortcuts.service.spec.ts, packages/tooling/fast-tooling/src/message-system-service/shortcuts.service.ts
This change fixes the issue where the event listener was passed through postMessage which should only accent JSON data but was passing tests as the test environment did not throw an error. It will now be passed to the message system which can be retrieved by other services after initialization.
Reliant on the completion of #4355
=> fix: update the event listener to be passed to a config to the message system

packages/web-components/fast-components/src/listbox/fixtures/base.html, packages/web-components/fast-foundation/src/listbox/listbox.spec.ts, packages/web-components/fast-foundation/src/listbox/listbox.ts, packages/web-components/fast-foundation/src/select/select.spec.ts
- Check for a non-null value when finding the default selected listbox option
- Update listbox fixture content to be more usable
Setting the `selected` attribute on a `<fast-option>` in a `<fast-listbox>` or `<fast-select>` wasn't being handled properly on page load.
=> fix: default selected option in listbox

packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/utilities/match-media-stylesheet-behavior.ts
This PR adds behaviors for "prefers-color-scheme" to support light/dark mode specific stylesheets.
=> feat: add prefers-color-scheme behaviors for light and dark mode

sites/site-utilities/src/definitions/native/common.definition.ts, sites/site-utilities/src/definitions/native/html-native.definition.ts
This maps the native HTML definitions to JSON schema using the new structure.
Incorrect titles in the native HTML element definitions were being mapped.
=> fix: adjust automapping of native html element definitions

packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/di/di.spec.ts, packages/web-components/fast-foundation/src/di/di.ts
This PR enables the use of the `@inject` decorator and the `DI.inject` imperative API on properties of web components. This enables injecting concrete types without a special DI key and also the use of special resolvers such as `@all`.
```ts
export class MyComponent extends FASTEement {
@inject(SomeConcreteThing) thing: SomeConcreteThing;
@all(AnotherThing) otherStuff: AnotherThing[];
}
```
=> feat(di): enable use of the inject decorator on properties

packages/web-components/fast-foundation/docs/integrations/angular.md
tip to help with angular forms integration with input components
add default value accessor for input controls using ngDefaultControl
=> docs(angular.md): add notes on ngDefaultControl

packages/web-components/fast-components/src/combobox/combobox.definition.ts, packages/web-components/fast-components/src/combobox/fixtures/base.html, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/combobox/combobox.spec.ts, packages/web-components/fast-foundation/src/combobox/combobox.template.ts, packages/web-components/fast-foundation/src/combobox/combobox.ts
Adds a `placeholder` attribute to `<fast-combobox>`.
=> feat: add placeholder attribute to combobox component

packages/web-components/fast-foundation/src/menu-item/menu-item.template.ts
A breaking change was unintentionally introduced to menu items with the addition of menuitemcheckbox and menuitemradio styles. The internal template structure was changed which can create breaking changes for others in fast foundation. This PR updates the template to conditionally render the `input-container` only when a control which requires an input is included.
=> fix: conditionally render input container for menuitemcheckbox and menuitemradio

packages/tooling/fast-tooling-react/src/form/controls/control.section.tsx, packages/tooling/fast-tooling-react/src/form/controls/utilities/form.tsx
Discovered an issue while testing where category updates were not occuring when a change to a JSON schema occured. This check ensures that there are no runtime errors when switching schemas with or without categories.
=> fix: checks for different schemas before re-assigning categories

packages/web-components/fast-components/src/horizontal-scroll/fixtures/horizontal-scroll.html, packages/web-components/fast-components/src/horizontal-scroll/horizontal-scroll.styles.ts, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.template.ts, packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.ts
* Switches from `display: inline-block` to `display: inline-flex` for item container
* Replaces `setTimeout` loop with paced `requestAnimationFrame`
* Caches `getScrollPosition` to prevent layout thrashing
=> (horizontal-scroll) performance improvements

packages/tooling/fast-tooling/src/message-system-service/monaco-adapter.service-action.ts, packages/tooling/fast-tooling/src/message-system-service/monaco-adapter.service.spec.ts, packages/tooling/fast-tooling/src/message-system-service/monaco-adapter.service.ts, sites/fast-component-explorer/app/explorer.tsx, sites/fast-creator/app/creator.props.ts, sites/fast-creator/app/creator.tsx, sites/site-utilities/src/components/editor/editor.props.ts, sites/site-utilities/src/components/editor/index.tsx
The two data types, `DataDictionary` which the `fast-tooling` package uses, and a `string[]` value that the Monaco Editor uses, are currently kept in sync using the `onDidChangeContent` callback for Monaco Editor and `postMessage` to the `MessageSystem`.
This creates an issue where any setting of the value of the Monaco editor causes the `onDidChangeContent` to be called which we cannot control. To mitigate this issue, an additional check in the `MonacoAdapter` service uses the string value last set by the Monaco Editor, and if the change does not affect it this means that the update came from `fast-tooling` and that the Monaco editor need not fire a `postMessage` to update the `DataDictionary`.
This work is currently still being evaluated as the `MonacoAdapter` has still not been …
=> chore: allow the monaco adapter to recieve information about the origin of change requests to the editors value

packages/web-components/fast-components/src/number-field/fixtures/number-field.html, packages/web-components/fast-components/src/number-field/number-field.definition.ts, packages/web-components/fast-components/src/number-field/number-field.styles.ts, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/number-field/number-field.spec.ts, packages/web-components/fast-foundation/src/number-field/number-field.template.ts, packages/web-components/fast-foundation/src/number-field/number-field.ts
This PR proposes a method to remove the built in spin button controls and updates the behavior to match current browser defaults.
=> feat: add ability to hide step controls and update reveal on hover and focus-within

packages/web-components/fast-foundation/src/menu/menu.ts
Coding error referenced wrong array.  Corrected and changed to a foreach iterator which seemed more appropriate in this case.
Error could throw.
**Adding or modifying component(s) in `@microsoft/fast-components` checklist*
=> fix: menu reset items attempts to remove event listener on wrong item

packages/web-components/fast-components/src/listbox-option/fixtures/base.html, packages/web-components/fast-components/src/listbox-option/listbox-option.styles.ts, packages/web-components/fast-components/src/select/fixtures/base.html, packages/web-components/fast-components/src/select/select.styles.ts
* Ensure that changing the `--design-unit` on a `fast-option` doesn't cause the text to get clipped
* Force ellipsis on control value when a `fast-select` has an explicit `width` or `max-width`
Example snippet:
```html
<fast-select style="--design-unit: 2;">
<fast-option>This option is short</fast-option>
<fast-option>In a visual height sense</fast-option>
<fast-option>Not character count</fast-option>
</fast-select>
```
Before:
After:
Example snippet:
```html
<fast-select style="width: 100px; min-width: 0">
<fast-option>This option is short</fast-option>
<fast-option>In a visual height sense</fast-option>
<fast-option>Not character count</fast-option>
</fast-select>
```
Before:
After:
**Adding or modifying component(s) in `@microsoft/fast-components` …
=> fix: reduce text clipping when changing design-unit on listbox option

packages/web-components/fast-foundation/src/combobox/combobox.ts
Allows proper navigation for combobox elements with autocomplete after pressing `Escape` or using the `ArrowDown` and `ArrowUp` keys.
Fixes #4440.
=> fix: combobox escape and arrow keys prevent listbox navigation

packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/data-grid/data-grid-row.template.ts, packages/web-components/fast-foundation/src/data-grid/data-grid.template.ts, packages/web-components/fast-foundation/src/data-grid/data-grid.ts
Data grid was incorrectly forcing "fast-data-grid-row" headers and not applying provided prefix.
Data grid rows should create headers to match prefix.
=> fix: data grid should not force fast header

packages/tooling/fast-tooling/src/data-utilities/mapping.vscode-html-languageservice.spec.ts, packages/tooling/fast-tooling/src/data-utilities/mapping.vscode-html-languageservice.ts
In order to better preserve interactions between the `DataDictionary` from the `fast-tooling` `MessageSystem` and the Monaco Editors text value, a new utility has been created to consolidate these formats where possible. The utility `mapVSCodeHTMLAndDataDictionaryToDataDictionary` will parse the Monaco Editor text value using an existing `DataDictionary` to create an updated `DataDictionary`.
This should help keep data structures and navigation more in sync while editing the `DataDictionary` from the Monaco Editor.
=> feat: create a utility that consolidates the changes made to the data structure to preserve as much of the data dictionary as possible

packages/web-components/fast-foundation/src/combobox/combobox.form-associated.ts
The emitted declarations throw an error when used in TypeScript ^4.0 (4.2.3 at the time of this PR). By moving the anonymous mixin class out of the function call, we can get the proper signature for `options`.
Related to at least these three issues:
* microsoft/typescript#37894
* microsoft/typescript#41347
* microsoft/typescript#41994
Our original ticket to track the issue: #4435 
Test method:
1. in `fast-foundation`, run `yarn link`
2. In a new workspace, add `fast-components` with `yarn add @microsoft/fast-components`
3. Create a new file `test.ts`:
```ts
export * from "@microsoft/fast-components";
```
4. Build with tsc: `npx -p typescript@4.2.3 tsc --moduleResolution "Node" --noEmit --target "ESNext" test.ts`
An error should occur: 
``` …
```
=> fix: declarations throw an error when using TypeScript ^4.0

packages/web-components/fast-foundation/.eslintrc.js, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/button/button.form-associated.ts, packages/web-components/fast-foundation/src/button/button.ts, packages/web-components/fast-foundation/src/checkbox/checkbox.form-associated.ts, packages/web-components/fast-foundation/src/checkbox/checkbox.ts, packages/web-components/fast-foundation/src/combobox/combobox.form-associated.ts, packages/web-components/fast-foundation/src/combobox/combobox.ts, packages/web-components/fast-foundation/src/custom-properties/behavior.ts, packages/web-components/fast-foundation/src/design-system-provider/design-system-provider.ts, packages/web-components/fast-foundation/src/form-associated/form-associated.ts, packages/web-components/fast-foundation/src/number-field/number-field.form-associated.ts, packages/web-components/fast-foundation/src/radio/radio.form-associated.ts, packages/web-components/fast-foundation/src/radio/radio.ts, packages/web-components/fast-foundation/src/select/select.form-associated.ts, packages/web-components/fast-foundation/src/slider/slider.form-associated.ts, packages/web-components/fast-foundation/src/slider/slider.ts, packages/web-components/fast-foundation/src/switch/switch.form-associated.ts, packages/web-components/fast-foundation/src/switch/switch.ts, packages/web-components/fast-foundation/src/text-area/text-area.form-associated.ts, packages/web-components/fast-foundation/src/text-area/text-area.ts, packages/web-components/fast-foundation/src/text-field/text-field.form-associated.ts, packages/web-components/fast-foundation/src/text-field/text-field.ts
This change updates all form-associated components to create a named local class before applying the `FormAssociated` mixin function.
It turns out this solves a lot of the `import()` problems that are preventing us from upgrading the API Extractor and TypeScript 4. It also reduces the opportunities for collisions as mitigated in #4475,
This change should only affect the generated `.d.ts` files.
=> fix: reduce surface area for form-associated component types

sites/fast-creator/app/index.tsx, sites/site-utilities/src/components/editor/editor.style.css
I've manually uploaded this font to `https://static.fast.design/assets/fonts/SegoeUI-Roman-VF_web.ttf` for access by the FAST Creator.
Security requires not using third-party services.
=> chore: update font to use cdn for security enhancement

packages/web-components/fast-components/src/flipper/flipper.styles.ts
Set `font-size:0` in flipper.styles.ts for the `.next` and `.previous` slot classes so the glyphs will render in their proper positions regardless of container's inheritable font-size
Fixes #4497 
=> fix: add display:grid to flipper slots to prevent container from changing glyph position

packages/web-components/fast-components/src/anchored-region/anchored-region.definition.ts, packages/web-components/fast-components/src/anchored-region/anchored-region.stories.ts, packages/web-components/fast-components/src/anchored-region/fixtures/base.html, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/anchored-region/anchored-region.spec.md, packages/web-components/fast-foundation/src/anchored-region/anchored-region.ts, sites/site-utilities/statics/assets/components/fast-anchored-region.schema.json
Normally anchored region will only recalculate placement based on either attribute/prop changes, a resize event on the anchor element, or a call to update().  With this change we add an "auto-update" attribute to anchored region that allows for an additional mode - 'auto', which  will prompt the anchored region to additionally check it's placement when the window resizes, the viewport resizes and on any scroll event on the page.
Needed to support document level scaling menus.
- [c] I have modified an existing component
=> feat: add auto-update attribute for anchored region

packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/progress-ring/progress-ring.template.ts, packages/web-components/fast-foundation/src/progress/base-progress.ts, packages/web-components/fast-foundation/src/progress/progress.template.ts
Closes #4517 
Value of `0` for progress is indeterminate this is incorrect, `0` is a `determinate` value. this is also outline in the progress spec
```
- `value`, the value of the progress, if not passed the progress will be put into its "indeterminate" state.
```
=> fix: value of 0 for progress is indeterminate

change/@microsoft-fast-foundation-bf618f1d-588a-4fef-8ee0-aadb2142c79b.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/design-token/design-token.spec.ts, packages/web-components/fast-foundation/src/design-token/design-token.ts
I noticed when doing some implementation tests that a `DesignToken` set to a *falsey* value would be un-resolvable for a node, throwing an exception. This changes resolution logic to correctly handle *falsey* values, so that values like `0`, `""`, `NaN`, and `null` are all valid values for a `DesignToken`.
This change also extends the type-guard to dis-allow `DesignToken<undefined>` and `DesignToken<void>`, because the `undefined` value is used to determine if a value should be resolved from a parent node.
=> fix: ensure DesignToken works with falsey values

sites/site-utilities/statics/server/package.json, sites/site-utilities/statics/server/server.js
This will upgrade Helmet which we use on Express Middleware for improved application security and also add a content security policy CSP for integration with key partners.
* Upgrade security features
* Upgrade includes CSP patches 
* Add CSP
Tested on Creator staging site and in place at the moment.
=> update helmet version to improve security and take on CSP patches

change/@microsoft-fast-foundation-c67228bc-274a-4837-a69d-21e8dc259e5f.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/design-token/design-token.ts, packages/web-components/fast-foundation/src/design-token/interfaces.ts, packages/web-components/fast-foundation/src/index.ts
This PR opens up the types of elements that a `DesignToken` can be get, set, and deleted for to any HTMLElement. This has always worked, but was originally restricted to elements that have an observable connection state. We actually don't need connection observation for getting/setting though, only *using* values (emitting to CSS custom properties).
The `addCustomPropertyFor` and `removeCustomPropertyFor` API's are still locked down to `FASTEelement` elements because for those elements we need to observe connection state, re-evaluating the value when connection state changes.
=> feat: open up getter and setter functions of a DesignToken to HTMLElement types

change/@microsoft-fast-components-3c8fe4fa-c966-40a0-8ac4-41e2aed261f2.json, change/@microsoft-fast-foundation-6a63ccca-5dd8-4d21-aa10-8b15d06966d8.json, packages/web-components/fast-components/src/anchored-region/fixtures/base.html, packages/web-components/fast-foundation/src/anchored-region/anchored-region.ts
Anchored region could use wrong contents dimensions on the initial layout pass when using region dimensions instead of fixed thresholds to determine dynamic placement with default position set.
- Needed to tweak anchored region initial layout timing so that default positioning was able to use the actual size of the anchored region's contents to determine placement.   The previous implementation was grabbing the dimensions of the region too early which could result in incorrect placement.
- found issue during implemention of component in another library.
Currently working on adding a battery of anchored region tests now that we have a test env that works.  Hope to have a pr for that soon.
Expand anchored region testing suite
=> fix: anchored region default positioning without "threshold" set can position incorrectly on initial layout

change/@microsoft-fast-components-be84dce5-5d4e-43bc-967f-c015c3e94c62.json, packages/web-components/fast-components/.storybook/preview.js, packages/web-components/fast-components/src/custom-elements.ts, packages/web-components/fast-components/src/index-rollup.ts, packages/web-components/fast-components/src/index.ts
This PR updates the Storybook configuration to use component definitions. It updates the `index-rollup.ts` file to export a `DesignSystem` instance that has all components exported by the package registered to it, and the DesignSystem applied to the document body. Importing this side-effect into storybook's preview script causes all components to be defined for the Storybook inner-loop.
This PR also ensures that consumers of `fast-components.min.js` have FAST elements defined when the script is added, which is the desired experience for that script.
=> fix: update storybook to use custom element definitions and fix rollup

change/@microsoft-fast-foundation-82d4edb4-882b-4a0b-9cf3-c7eb71edc72b.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/design-token/README.md, packages/web-components/fast-foundation/src/design-token/design-token.spec.ts, packages/web-components/fast-foundation/src/design-token/design-token.ts
This PR enhances Design Token values with the ability to control their own emission to CSS. This is useful when the token value is a structure that does not emit to a valid CSS value. When emitting to CSS, any DesignToken value that has a `createCSS` method will get the product of that function assigned to the custom property value, instead of the DesignToken itself.
See https://github.com/microsoft/fast/compare/users/nirice/add-createCSS-to-design-token-value?expand=1#diff-dc910e98f1afc7f4cc970daabfbd4de573f06b5ca8e82507e225a322a64759df for usage example.
=> feat: adds the ability for an arbitrary Design Token value to control emission to CSS

change/@microsoft-fast-tooling-8262e4bb-e41d-4cda-8269-09137e23b3e4.json, packages/tooling/fast-tooling/src/definitions/native/svg.definition.ts
A `name` slot in the description corresponds to the name of the slot. As such a default slot has an empty string, this has been corrected for a definition being used in the Component Explorer site.
Run `yarn start` in the component explorer site after building the project to check for runtime errors.
=> fix an incorrect definition name which for default slots should be an empty string

change/@microsoft-fast-foundation-deafb619-c242-42d8-a45d-7b2cbca0327e.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/design-system/component-presentation.ts, packages/web-components/fast-foundation/src/design-system/design-system.ts, packages/web-components/fast-foundation/src/foundation-element/foundation-element.spec.ts, packages/web-components/fast-foundation/src/foundation-element/foundation-element.ts
This PR changes the APIs related to ComponentPresentation so that internally we can fast-path the scenario where only one presentation configuration exists for a given tag name.
Noteworthy changes were made in `component-presentation.ts`. The rest was fix-up to use the new APIs.
Existing tests should continue to function after the optimization.
In the future we could look to expand the `ComponentPresentation` such that it could also add/remove behaviors, in addition to templates and styles. We could also look at enabling the presentation object to store a WeakSet of components that use it so that all components with a presentation could be dynamically updated at once. These are just a few ideas for enhancements we could make. Currently, there aren't particular needs for this …
=> feat: encapsulate and optimize ComponentPresentation resolution

packages/web-components/fast-foundation/docs/integrations/aurelia.md
While browsing the docs I noticed a small typo, which this PR fixes.
n/a
n/a
n/a
n/a
=> docs(integrations): fix adpater typo

change/@microsoft-fast-foundation-dfc8ac08-2fb7-4ea0-a824-6db5b72ce23c.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/design-token/README.md, packages/web-components/fast-foundation/src/design-token/custom-property-manager.ts, packages/web-components/fast-foundation/src/design-token/design-token.spec.ts, packages/web-components/fast-foundation/src/design-token/design-token.ts
This PR addresses significant performance issues uncovered with the initial implementation of `DesignTokens`, specifically removing the behavior that using a `DesignToken` as a `CSSDirective` causes value resolution for *each token instance in the stylesheet*. It removes the `addCustomPropertyFor()` and `removeCustomPropertyFor()` methods from `DesignToken`.
Instead, CSS custom properties are written for an element in two cases:
1. A value is *set* for an element via `DesignToken.setValueFor()`
2. A token that some other `DesignToken` *depends* on is set via `DesignToken.setValueFor()`
Setting CSS custom properties in these two cases ensures that all a DesignToken can always be used as a CSS directive, and using the CSSDirective simply interpolates the CSS variable string (no value …
=> feat: improve design token performance

change/@microsoft-fast-foundation-5acf04f9-e080-4f74-bc81-8db1c89758c9.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/design-token/design-token.spec.ts, packages/web-components/fast-foundation/src/design-token/design-token.ts
For some reason the generic type signature for `DesignToken` worked fine with implicit types, but did not work for declared types or types emitted to .d.ts files.
Example:
```ts
// Compiles fine
const a = DesignToken.create<number>("a"); // a is a DesignToken<number>
// Does not compile
const b: DesignToken<number> = DesignToken.create<number>("b"); 
```
This PR adds a long-hand type signature to include all acceptable types in the generic type parameter. It also adds some typing tests to guard against regression.
=> fix DesignToken typing to work with declared types

change/@microsoft-fast-tooling-160defd8-c1aa-443b-8365-6a4d23883291.json, packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.spec.ts, packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.ts, packages/tooling/fast-tooling/src/web-components/html-render/html-render.spec.ts
This resolves an issue with async tests would be skipped because they did not await the message system messages and would then cause coverage errors intermittently.
It's difficult to test this as it fails intermittently but it would appear that this solution works after running it several times.
This affects the html render tests in the `@microsoft/fast-tooling` package.
=> update the html render tests to reliably await message system messages before proceeding

build/releasing/index.ts
Publishing with Beachball is failing because tooling is using `latest` versions.  When beachball attempts to publish, the latest version for tools changes to an actual version, then is unable to bump because that version already exists.
By excluding tools, for now, we can avoid this issue and continue to publish.  @janechu can provide additional details as to the temporary nature of this exclusion.
For exclusion details refer to https://microsoft.github.io/beachball/concepts/groups.html
* Beachball fails thinking it's publishing to an already existing version
Will manually deploy a publish to determine if this in fact resolves our issue.
=> update to exclude tooling from beachball publishing

build/releasing/index.ts
=> Revert "update to exclude tooling from beachball publishing"

.github/workflows/ci-weekly.yml, change/@microsoft-fast-components-7ed967b6-eff5-4071-ab45-ea6f05c428da.json, packages/web-components/fast-components/__test__/harness.js, packages/web-components/fast-components/package.json, yarn.lock
- Fix a mismatched environment variable (`PLAYWRIGHT_BROWSER`)
- Update CI actions to use `actions/cache@v2`
- Add a CI environment variable to store Playwright binaries in `node_modules`
- Split CI playwright browser runs into separate tasks
These changes are intended to make it easier to catch actions that are hanging on the playwright step.
It may be a good idea to store the Playwright binaries as artifacts and load them separately. The [Installation page](https://playwright.dev/docs/installation/#managing-browser-binaries) has some extra environment variables that we may want to explore in the future.
=> split playwright steps in PR actions

change/@microsoft-fast-components-2370cffd-4603-4a31-be75-333aaaa0c377.json, packages/web-components/fast-components/src/data-grid/data-grid.vscode.definition.json, packages/web-components/fast-components/src/data-grid/scenarios/index.html, sites/site-utilities/statics/assets/components/fast-data-grid.schema.json
Added a "manual" (defined in html) data grid example to component explorer scenarios, fixed issue with definition file.
https://github.com/microsoft/fast/issues/4677
=> chore: fix/add to data grid component explorer examples

change/@microsoft-fast-foundation-84313fab-6646-4094-bf23-c2ce86be930c.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/design-system/design-system.spec.ts, packages/web-components/fast-foundation/src/design-system/design-system.ts, packages/web-components/fast-foundation/src/foundation-element/foundation-element.spec.ts, packages/web-components/fast-foundation/src/foundation-element/foundation-element.ts
Enables the consumer of the components to override the component's configured shadow root mode across the design system. Individual component overrides still take precedence.
The first change was made in the `DesignSystem` API, adding a method to provide the configuration and piping that through. The second change was made in `FoundationElement#compose` internals, which now takes advantage of this configuration information when defining the component.
Tests were added both for `DesignSystem` and for `FoundationElement` covering the basic use cases as well as the special light DOM exception.
Future PRs will likely be focused around adding code documentation around `DesignSytem`, `FoundationElement`, and `DI`. We'll also move the various APIs out of alpha as we add the docs.
=> feat(design-system): enable overriding the shadow root mode

change/@microsoft-fast-foundation-8263b273-a2fa-48cd-90d5-d8169775cb6c.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/slider/slider.spec.ts, packages/web-components/fast-foundation/src/slider/slider.ts
This change assumes that all `step` attributes are floating points and adjusts them to be integers during calculations to overcome issues with doing math with floats.
An issue arose when attempting to use the `<fast-slider>` with a `step` attribute of `0.1`. Math in JavaScript with regards to integers is straight forward, however once floats are used it is possible to get floating point issues.
=> fix: allows a float to be accurately used for the step attribute

change/@microsoft-fast-foundation-c4073daf-4cce-41ca-99ef-7e116a739c04.json, packages/web-components/fast-foundation/src/design-token/design-token.ts
Fixes an issues where dependent CSS custom properties would not be written when a dependent value was changed.
DesignToken internals uses a fast-element behavior bound to the CustomElement for which nodes are created to track DOM hierarchy. In some cases, a token value for which other properties use as a dependency can be set for a custom element prior to Controller connection, meaning DOM hierarchy isn't being tracked yet for that element (behaviors not bound).
To guard against this case, the `value` getter would lazily resolve the parent node if no parent existed in the child -> parent map. However, setting dependent tokens goes down a slightly different code-path to retrieve the *rawValue* instead of the value, meaning this guard was being skipped for token dependencies, causing custom …
=> fixes CSSDesignToken dependent-property emission

change/@microsoft-fast-tooling-react-824af1fa-8dd2-450a-88a2-395ddc649c97.json, packages/tooling/fast-tooling-react/src/form/controls/control.textarea.tsx
While the previous fix for this issue worked when the `<Form />` was implemented on it's own, adding multiple services to the `MessageSystem` resulted in the first character typed into the textarea sending the cursor to the end of the string no matter where the text was entered. This prevents the rerender issue by not updating the value of the textarea while the user is typing inside.
Open the fast-tooling-react manual test app and navigate to "form and navigation", this demonstrates the fix.
=> fix: address an issue where the first character typed results in the cursor moving to the end of the text

change/@microsoft-fast-foundation-142496f8-23bc-4ae0-8315-34ab7a5fb8b3.json, change/@microsoft-fast-tooling-31e4d861-c660-40a3-94ae-1e0b45aa7f4e.json, packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.template.ts, packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.ts, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/design-system/component-presentation.ts, packages/web-components/fast-foundation/src/foundation-element/foundation-element.spec.ts, packages/web-components/fast-foundation/src/foundation-element/foundation-element.ts
This PR fixes an issue with `FoundationElement` that prevented derived classes from being used with the `customElement` decorator when no `ComponentPresentation` exists.
* Fixes #4794 
Changes are minimal. We needed to be able to identify when there was no `ComponentPresentation` for a tag name and also fallback to normal behavior in that case.
A test case was added to cover this scenario.
None related at this time.
=> fix(foundation-element): enable subclassing with customElement decorator

change/@microsoft-fast-components-506953be-cfe8-43a7-b669-badef6589ce2.json, packages/web-components/fast-components/src/design-tokens.ts
This PR updates the `neutralPalette` and `accentPalette` to be `DesignToken`'s instead of `CSSDesignTokens`. Palettes are not intended to be used in CSS so this change prevents interpolation usage in `ElementStyles` and removes emission to CSS custom properties.
=> convert palettes to normal design tokens

change/@microsoft-fast-foundation-d92cd6d3-d001-44dd-9f7d-cb8bf2463e03.json, packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.ts
Minor tweak to horizontal scroll's resize handler to remove a check on resize observer entries.  With only one component being observed we can assume all callbacks are related to it and run a bit less code (this function can be invoked frequently).
=> fix: remove unnecessary check from horizontal-scroll resize handler

change/@microsoft-fast-foundation-5d4aa7c3-730c-45e4-b755-7b98c5d6f889.json, packages/web-components/fast-foundation/src/di/di.spec.ts, packages/web-components/fast-foundation/src/di/di.ts
This PR fixes a bug in DI parent container resolution logic. Parent resolution uses event target comparison to ensure that a container doesn't resolve itself, however that logic does not account for the fact that the event is re-targeted to the host element after escaping the shadow DOM.
This PR changes this logic to check the first index of `Event.composedPath()` to inspect the the actual element that dispatched the event.
=> fix di parent container resolution in shadow DOM

change/@microsoft-fast-tooling-fd33301a-07d3-42b3-ba44-a66b1a277bd3.json, packages/tooling/fast-tooling/src/data-utilities/mapping.mdn-data.spec.ts, packages/tooling/fast-tooling/src/data-utilities/mapping.mdn-data.ts
This change adds a small utility to convert inline style strings to a CSS declaration dictionary.
Unit tests have been added.
=> feat: add a utility to convert inline css styles to a property dictionary

change/@microsoft-fast-foundation-8e3a0169-909a-47b6-a4f3-284094236272.json, packages/web-components/fast-foundation/src/number-field/number-field.spec.ts, packages/web-components/fast-foundation/src/number-field/number-field.ts
Number-field does not step up or step down when there is no value set. Step up and step down use the value or 0 if value is  undefined.
https://github.com/microsoft/fast/issues/4840
=> Enable step up and step down for number-field when no value

change/@microsoft-fast-foundation-ec75963d-5f1d-4fec-9c2a-27d2a144fe00.json, packages/web-components/fast-foundation/src/data-grid/data-grid.template.ts, packages/web-components/fast-foundation/src/slider/slider.template.ts
Data grid's template had missing quotes around a value binding that caused failures in some deployment scenarios.  Fixing similar issue in slider as well.
=> fix: malformed data grid template

change/@microsoft-fast-tooling-react-278963d3-b9c9-4e80-bb17-e88b4602d7cc.json, packages/tooling/fast-tooling-react/app/pages/form.tsx, packages/tooling/fast-tooling-react/src/__tests__/schemas/control-plugin.css.schema.ts, packages/tooling/fast-tooling-react/src/form/custom-controls/control.css-ref.props.ts, packages/tooling/fast-tooling-react/src/form/custom-controls/control.css-ref.tsx, packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.tsx, packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.property.tsx, packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.props.ts, packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.syntax.tsx, packages/tooling/fast-tooling-react/src/form/custom-controls/control.css.utilities.tsx
This solves an issue where switching between dictionary IDs (aka in the component nesting structure as seen in the Creator app) would not cause the CSS controls to update. This is fixed using the `key` prop which constructs a unique `key` from a `dictionaryId` and a `dataLocation`.
The manual testing app has been updated to reflect this change, simply add a new css control, change the CSS values and navigate between the two dictionary items.
As previously stated, this alpha component does not have a testing strategy at present since Jest/Enzyme errors. This will need to be addressed in a more comprehensive manner by either switching test suites or adding integration tests.
=> fix: forces the css control to respect state changes which involve switching dictionary IDs

packages/tooling/fast-tooling/app/examples/css-layout/index.html, packages/tooling/fast-tooling/app/examples/css-layout/index.ts
Remove a vestigial reference to the `DesignSystemProvider` in the `@microsoft/fast-tooling` manual test app.
Run the manual test app in `fast-tooling` and there should no longer be errors.
=> chore: update fast-tooling manual test app to not use the design system provider

packages/web-components/fast-components/src/accordion-item/accordion-item.styles.ts, packages/web-components/fast-components/src/breadcrumb-item/breadcrumb-item.styles.ts, packages/web-components/fast-components/src/button/button.styles.ts, packages/web-components/fast-components/src/menu-item/menu-item.styles.ts, packages/web-components/fast-components/src/number-field/number-field.styles.ts, packages/web-components/fast-components/src/radio/radio.styles.ts, packages/web-components/fast-components/src/styles/patterns/button.ts, packages/web-components/fast-components/src/tab/tab.styles.ts, packages/web-components/fast-components/src/text-field/text-field.styles.ts
Fixed high contrast regression on the components. 
accordion-item - fixed expand and collapsed icons
anchor - fixed missing border on focus
breadcrumb-item - fixed icon color and missing underline focus indicator
button - fixed missing border color on focus and update background on active state
menu-item - fixed the color on the `end` content
radio - fixed checked and focus states
tab - fixed disabled color
number-field and text-field - fixed placeholder text to be disabled color
=> fixed: high contrast pass to fix missing and wrong forced color keywords

change/@microsoft-fast-components-37c9c837-7aa1-47ad-b9a7-940d05914708.json, change/@microsoft-fast-foundation-79bb3762-27aa-4243-b274-6cfa916eabbe.json, packages/web-components/fast-components/package.json, packages/web-components/fast-components/src/select/select.pw.spec.ts, packages/web-components/fast-foundation/src/select/select.spec.md, packages/web-components/fast-foundation/src/select/select.spec.ts, packages/web-components/fast-foundation/src/select/select.ts
* Ensures that the `<fast-select>` component emits an `input` event (bubbles, composed) right before it emits a `change` event (bubbles, not composed) when the value is changed via user interaction.
* Fixes an issue where custom events weren't being emitted under a certain navigation scenario. See the Test Plan section for more info.
* Fixes the Playwright script commands in `fast-components`.
* I marked this as a "minor" change and not a "patch" since some existing project might be expecting `change` to be composed.
To test the scenario mentioned above:
1. Add an event listener in the console to track the `change` or `input` events on the `<fast-select>`.
2. Open the `<fast-select>` by clicking it or via keyboard interaction.
3. Change the selected option and close the element.
4. Use …
=> add input event to select component

sites/fast-creator/app/configs/library.fast.import.ts, sites/fast-creator/app/configs/library.fast.ts, sites/fast-creator/app/configs/typings.ts, sites/fast-creator/app/creator.tsx, sites/fast-creator/app/preview/preview.tsx, sites/fast-creator/app/utilities/shared.ts, sites/fast-creator/tsconfig.json
This PR adds logic where adding the FAST components library prompts the preview application to dynamically load and register components from the library. Without this action the components have not been included and will not render.
Run the Creator application and try to add a Card, this should not render correctly as the components have not been imported and registered. Then add the FAST components library using the button in the Libraries tab, the Card should render correctly. Additionally you can add the library first then the card, this should result in the correct rendering of the Card.
- Make the components unavailable to be added until the library they are comprised of are added
- Add in the Fluent UI component library using the same methods the FAST library inclusion is employing
=> feat: convert FAST component library to be a dynamic import

change/@microsoft-fast-components-860c1c29-b6e1-4d9a-93b9-bdc3cf7dbf46.json, packages/web-components/fast-components/.storybook/main.js, packages/web-components/fast-components/.storybook/preview.js, packages/web-components/fast-components/package.json, yarn.lock
Updates Storybook to the latest version.
Updating storybook removes the various Babel warnings that are output while running `storybook` in `fast-components`. These warnings were due to a conflict between `docusaurus` and `storybook` dependencies.
Tested on:
* Ubuntu 20.04 via WSL2 on Windows 10
* MacOS 11.4 Big Sur (Intel)
* MacOS 11.4 Big Sur (Apple silicon)
=> update Storybook from 6.1.17 to 6.3.3

.gitignore, change/@microsoft-fast-components-2fce415d-b7f2-4b76-9488-de81582a65ef.json, packages/web-components/fast-components/docs/api-report.md, packages/web-components/fast-components/src/tooltip/index.ts
Ensure the tooltip's styles are exported like in the other components. Also adds .gitignore entry for .idea directory (Intellij's IDEA). 
Note: My original PR closed after force pushing a rebase. That PR appeared to be stuck on a build / approval step, perhaps because a master merge commit creeped in.
=> fix: export tooltipStyles

change/@microsoft-fast-components-18104f7b-3775-42fb-bb97-2a2af5e65ece.json, change/@microsoft-fast-foundation-2f030e0c-1487-4a5b-ad03-a9b6e1cf80e2.json, packages/web-components/fast-components/src/tooltip/fixtures/base.html, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/tooltip/tooltip.spec.md, packages/web-components/fast-foundation/src/tooltip/tooltip.spec.ts, packages/web-components/fast-foundation/src/tooltip/tooltip.template.ts, packages/web-components/fast-foundation/src/tooltip/tooltip.ts, sites/site-utilities/statics/assets/components/fast-tooltip.schema.json
This change applies anchored region's new auto-update feature to tooltip.  Tooltips will now track their anchors when things scroll or the page resizes.  Authors can retain the current behavior by specifying auto-update-mode="anchor"
Tooltips should track the item they are anchored to as much as possible.
=> feat: add auto position tracking to tooltip

sites/fast-component-explorer/app/explorer.props.ts, sites/fast-component-explorer/app/explorer.tsx, sites/fast-creator/app/creator.props.ts, sites/site-utilities/src/components/editor/editor.props.ts
This fixes a runtime error that was preventing the Component Explorer from loading. Ultimately the schema dictionary was not tied to state and not being passed on via the Editor abstract component, causing a crash from within the Monaco Editor utilities that parse the DataDictionary.
It is recommended to run both the Creator and Component Explorer to check for any unexpected runtime errors.
=> fix an issue where the schema dictionary was not loading in the component explorer

sites/fast-creator/app/creator.tsx
The `onChange` is currently being overwritten for linked data, specifically to allow for the addition of complex examples. This however did not take into account the reordering of linked data, which this PR fixes.
Add a Card to the Creator and in the form, click on the Card to see the internal components, then attempt to drag and drop the components inside it. This should now allow for them to be reordered.
=> fixes an issue where drag and drop was not working in the Form for linked data

change/@microsoft-fast-components-a91fa2e5-2e89-428c-9816-1c67bca53902.json, packages/web-components/fast-components/src/select/select.styles.ts
Fixes a subtle style bug when the select component is active. In the GIF, observe any of the corners as the mouse is depressed.
Before
After
Not sure if this is something that makes sense to test for at this point — let me know what you think.
N/A
=> Fix select border styles when control is active

change/@microsoft-fast-foundation-61f51210-4c16-4b3f-8984-f6a68f6e54d8.json, packages/web-components/fast-foundation/src/test-utilities/fixture.ts
At the request of the community, I've made a small type change to our `fixture` test helper. This should be a non-breaking change but it's technically a change to the API, so I've marked this as "minor" change.
* Related to #4930  but does not fully address the need yet. See Next Steps below.
This is a change to the shape of the interface only, primarily for the purpose of enabling type-safe destructuring of the `Fixture` interface without lint warnings.
Existing tests and TS compilation should suffice in this case.
To fully address the community need, we should make our testing utilities officially available, along with documentation on the site. There is a challenge of making these utilities available, related to where we put them. At present, they are part of the `fast-foundation` …
=> refactor(fixture): mild change to typings to enable typical code pattern

change/@microsoft-fast-tooling-a5f7c374-9e8f-42dc-a75d-2b113b0f7d39.json, packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.style.ts
Adding white-space: nowrap style to pill in html render navigation component to prevent pill content from wrapping and potentially covering the selected element.
=> fix: fix word wrapping bug in html render navigation pill

change/@microsoft-fast-tooling-react-1112709a-9e25-478a-ae24-6285dc69fcf6.json, packages/tooling/fast-tooling-react/src/navigation/navigation.spec.tsx, packages/tooling/fast-tooling-react/src/navigation/navigation.tsx
This change fixes an issue where the expand/collapse states were not reflecting previous states triggered in the Navigation after a navigation message is received.
On Creator try the following:
1. Add A Card (Fluent UI)
2. Expand the div
3. Expand the Card
4. Collapse the Card
5. Collapse the div
6. Use the canvas to select the paragraph
You should see the Navigation does not open up to the location. Next try this on this branch and you should see that logic working.
Unit tests have been added.
=> fix: resolve the expanded navigation items mismatch after triggering the expand trigger then a navigation message

change/@microsoft-fast-tooling-0de8cfd6-61d8-4415-9d31-17c7d5d3d9c1.json, packages/tooling/fast-tooling/src/web-components/html-render-layer-inline-edit/html-render-layer-inline-edit.ts, sites/fast-creator/app/preview/web-components/index.tsx
Adding an attribute to the HTMLRenderInlineEdit component that specifies whether to automatically select all text in the textarea when editing is initiated. 
If the attribute is present then all of the text will be selected when beginning to edit a text node, otherwise the textarea will only be given focus with the cursor placed at the end of the text.
closes: #5064
=> feat: add auto select option to html render inline edit component

sites/site-utilities/statics/server/server.js
The staging site for creator results in a broken image displayed in the preview when you should be seeing the image you selected.
If you open the dev tools and look in the “Console” tab you will see the following security error:
Refused to load the image 'blob:https://stage.create.fast.design/27f23914-383c-4b3d-ae7a-db881cf66402' because it violates the following Content Security Policy directive: "img-src 'self' data: *.fast.design via.placeholder.com".
After a quick search around the nets I saw that the solution is to add “blob:” to the Content Security Policy.
CSP Policy requires additional `blob:` configuration.
In the header it should look like this:
img-src 'self' blob: data: *.fast.design via.placeholder.com;
Instead of this:
img-src 'self' data: *.fast.design via.placeholder.com; …
=> update to content security policy for images and fonts

change/@microsoft-fast-tooling-7856457b-7d8e-4c02-8a8c-25769919cd0c.json, packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.ts, sites/fast-creator/app/preview/web-components/index.tsx
Defaulting to the body resulted in scenarios that did not necessarily trigger the resize observer. This PR adds a "resizeobserverselector" attribute to the HTMLRenderNavigation component so that the resize observer target can be specified by the implementing code to ensure that the observer is attached to an element that will resize as content changes.
The new attribute is optional and the component will default to "document.body" if it is not supplied or if the selector specified does not match anything in the document.
This attribute is then used in Creator to specify the containing element which resizes to fit its children and should always trigger the observer whenever the content changes.
fixes #5063
=> fix: make resize observer target configurable in html render navigation component

change/@microsoft-fast-tooling-0189f240-d3ac-4189-9118-a88f6f2fb223.json, packages/tooling/fast-tooling/app/examples/css-layout/index.ts, packages/tooling/fast-tooling/src/web-components/css-layout/css-layout.spec.ts, packages/tooling/fast-tooling/src/web-components/css-layout/css-layout.styles.ts, packages/tooling/fast-tooling/src/web-components/css-layout/css-layout.template.ts, packages/tooling/fast-tooling/src/web-components/css-layout/css-layout.ts, packages/tooling/fast-tooling/src/web-components/utilities/constants.ts, packages/tooling/fast-tooling/src/web-components/utilities/index.ts, sites/fast-creator/app/web-components/index.tsx
This change adds tooltips for the radio buttons in the FAST tooling CSS layout control.
Closes #5065
This can be seen either by running the test application in the fast-tooling package or by building the entire project and running the Creator application in the sites folder.
Unit tests added.
=> feat: add tooltips to the CSS layout radio buttons

yarn.lock
Updates `tar` lockfile entries to `4.4.17` and `6.1.8`.
#5035
To replicate this process:
Prerequisite: install `yarn-deduplicate` globally with `yarn global add yarn-deduplicate`.
1. Clean your local workspace.
_`git clean -dfx` removes ALL untracked files! Use `git clean -ndx` first to see which files it will remove._
2. Identify the affected packages and their full entries in the lockfile. It will look something like this:
```
package-name@^1.2.3, package-name@^1.2.5, package-name@^1.4.5:
version "1.4.5"
resolved "https://registry.yarnpkg.com/package-name/-/package-name-1.4.5.tgz#abcdef12345
integrity sha512-abcdefghijklmnopqrstuvwxyz
dependencies:
another-package "^1.0.0"
some-dependency "~3.4.5"
```
3. Remove the entire entry from the lockfile.
_A find/replace for the package name …
=> [users/v-imaga/Security-update-bump-tar-to-4.4.15-or-later] fix: security-update-bump tar to 4.4.15 or later

change/@microsoft-fast-tooling-8bafde2b-1ae5-4ac8-9653-f8c7fe7e3527.json, change/@microsoft-fast-tooling-react-2b12a60b-f7de-4575-84e3-c3148f6b3ef0.json, packages/tooling/fast-tooling-react/app/pages/navigation.tsx, packages/tooling/fast-tooling-react/app/pages/navigation/children.schema.ts, packages/tooling/fast-tooling-react/app/pages/navigation/no-children.schema.ts, packages/tooling/fast-tooling-react/src/form/form.tsx, packages/tooling/fast-tooling-react/src/navigation/navigation-tree-item.tsx, packages/tooling/fast-tooling-react/src/navigation/navigation-tree-item.utilities.spec.ts, packages/tooling/fast-tooling-react/src/navigation/navigation-tree-item.utilities.ts, packages/tooling/fast-tooling-react/src/navigation/navigation.props.ts, packages/tooling/fast-tooling-react/src/navigation/navigation.tsx, packages/tooling/fast-tooling-react/src/navigation/navigation.utilities.spec.ts, packages/tooling/fast-tooling-react/src/navigation/navigation.utilities.ts, packages/tooling/fast-tooling/src/data-utilities/index.ts, packages/tooling/fast-tooling/src/data-utilities/relocate.spec.ts, packages/tooling/fast-tooling/src/data-utilities/relocate.ts, packages/tooling/fast-tooling/src/message-system/message-system.utilities.props.ts, packages/tooling/fast-tooling/src/message-system/message-system.utilities.ts, sites/fast-creator/app/web-components/index.tsx
This pull request serves a few purposes:
- Adds a list of linked data that cannot be dropped to via schema IDs
- Fixes a drag and drop reordering bug that did not update the active data dictionary ID if the active data dictionary ID was contained in the removed linked data list
Resolves #5071
Resolves #5067
Build the project and `yarn start` in the Creator site. Attempt to add a few cards, drag and drop them onto various nodes. You should see that the `img` tag which cannot contain content cannot be dropped on. Additionally the run time errors that would occur when the active dictionary id was inside the dragged item should no longer occur.
Unit tests have been added. Additionally a refactor has been done in the `<Navigation />` component to allow for individually unit testing the drag …
=> feat: add a list of linked data that cannot be dropped to

change/@microsoft-fast-components-0af6a2a1-a24b-4f07-9055-37695021d8e6.json, change/@microsoft-fast-foundation-1e3d00a6-0514-4c68-a817-49672aaa3b0c.json, packages/web-components/fast-components/src/horizontal-scroll/index.ts, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/foundation-element/foundation-element.ts, packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.template.ts, packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.ts
Replaces the `<fast-flipper>` components in `<fast-horizontal-scroll>` with `<${context.tagFor(Flipper)}>` by aliasing a new `FoundationElementTemplate` type and extending the types for `nextFlipper` and `previousFlipper`.
This also gives us a reusable base type for all template and CSS functions in the form of `FoundationElementTemplate<T, K = void> = LazyFoundationOption<T, K & FoundationElementDefinition>`.
In Storybook, the flippers should still be rendered as `<fast-flipper>` elements for horizonal scrollers.
The `FoundationElementTemplate` type should be applied to all template and style functions in `fast-foundation` and `fast-components`.
=> allow custom Horizontal Scroller flippers to be context-driven Flipper components

sites/website/src/docs/design-systems/creating-a-component-library.md
This change updates the `counter` example in the Design System documentation to include registering the `fastButton` component (without which, the `buttonTag` reference returns `undefined`).
None.
See https://discordapp.com/channels/449251231706251264/449251231706251266/879796951355387934 for context.
None.
=> Fix example to include fastButton registration

change/@microsoft-fast-foundation-8bbee565-8807-431a-a319-0c30a54d82e3.json, packages/web-components/fast-foundation/src/design-token/design-token.spec.ts, packages/web-components/fast-foundation/src/design-token/design-token.ts
This PR fixes a bug in DesignToken where, when a DesignToken value retrieved a value for the token being set, a maximum-callstack-exceeded error would be thrown. This was happening because the DesignToken would subscribe to changes for itself, causing recursive notification and update processes. 
This change filters out the token being assigned the value from the dependency list, preventing subscription to the token being set.
=> Fixing DesignToken subscription bug causing runtime error

sites/fast-creator/app/configs/fast/library.fast.ts, sites/fast-creator/app/configs/fluent-ui/library.fluent-ui.ts, sites/fast-creator/app/preview/preview.tsx, sites/fast-creator/app/preview/webpack.common.js, sites/fast-creator/app/webpack.common.js
This change fixes an async issue that occurs when FAST components are loaded before the default Fluent UI components in the Creator application. This does not fix the issue where both libraries existing together causes style inconsistencies because of the CSS variable naming overlap. That will be resolved by a future task for name-spacing the CSS variables.
Run the Creator build script to create a production build of the application, then copy to the new `www` folder the `server.js` file in the `@microsoft/site-utilities/statics/server/server.js` and remove lines `22-37` and `49-57`. Also copy the `@microsoft/site-utilities/statics/server/package.json` file. Then run `npm i` and `node server.js`. This should run on `localhost:7001` and should show that the styling async loading issue is …
=> fix: use await to import the registration script to prevent fast components from being preloaded

change/@microsoft-fast-foundation-7ce173bf-8b3d-421d-b51c-5d8decc92f9c.json, packages/web-components/fast-foundation/src/design-token/design-token.ts, sites/website/src/docs/design-systems/design-tokens.md
DesignToken doesn't support volatile bindings because DesignToken relies on knowing which DesignTokens are accessed by the token so that subscriptions can be hooked up to know when dependencies change throughout the DOM. If DesignTokens are conditionally accessed, DesignToken can't be sure it has collected all dependencies. These dependencies are only aggregated once on initial evaluation to avoid excessive subscription / unsubscription code-paths.
This PR forces non-volatile bindings when creating the binding, preventing Observable from sometimes going down the volatile code-path. It also updates documentation to explain that DesignToken derived token values don't support volatile expressions.
=> Explain DesignToken does not work with volatile bindings

change/@microsoft-fast-components-85721f69-3559-4dc8-bba1-53bc102f55a5.json, packages/web-components/fast-components/src/anchor/index.ts, packages/web-components/fast-components/src/avatar/index.ts, packages/web-components/fast-components/src/button/index.ts, packages/web-components/fast-components/src/card/index.ts, packages/web-components/fast-components/src/disclosure/index.ts, packages/web-components/fast-components/src/horizontal-scroll/index.ts, packages/web-components/fast-components/src/number-field/index.ts, packages/web-components/fast-components/src/slider-label/index.ts, packages/web-components/fast-components/src/text-area/index.ts, packages/web-components/fast-components/src/text-field/index.ts, packages/web-components/fast-components/src/toolbar/index.ts
This PR takes advantage of a recently added feature that enables `FoundationElement.compose(...)` calls to specify an additional `baseClass` to use for tag lookup. Some of our components had subclassed foundation classes resulting in the original foundation class not being associated with the tag. This update addresses this issue and now makes it safe to use `contextFor` against any foundation class.
n/a
Code changes are pretty simple. I tried to find all the components that had subclassed a foundation class and then add the `baseClass` configuration.
The underlying feature is covered in unit tests as are the components themselves. No need real for additional tests in this case.
These same changes will need to be applied to the Fluent versions of the components. I'm not sure when the …
=> feat(fast-components): leverage FoundationElement.compose baseClass

change/@microsoft-fast-tooling-5703efbf-0db8-4f95-9203-fa71584a0bff.json, packages/tooling/fast-tooling/karma.conf.js, packages/tooling/fast-tooling/src/web-components/html-render/html-render.ts, sites/fast-creator/app/preview/preview.tsx
Fixing message handling in Creator preview that was not forwarding the correct activeDictionaryId to the HTML Renderer which was causing an exception to be thrown. Also changing HTML Renderer to correctly receive the active ID and gracefully handle the scenario where the active ID does not exist in the Dictionary.
These changes required the branch test coverage to be reduced to 70%. This is temporary until we take time to perform a test coverage push.
Add a card with an image and a paragraph. Select the paragraph and in the left hand nav panel attempt to drag and drop the paragraph. This was resulting in a javascript exception. Now the parent card should be selected and you should be able to drag and drop the paragraph.
=> fix: fixed html renderer exception in some messaging scenarios

change/@microsoft-fast-tooling-react-b2a5da63-bda5-4b37-80c9-e6b2ecc5ed00.json, packages/tooling/fast-tooling-react/src/navigation/navigation-tree-item.tsx
This change adds the linked data type corresponding to linked data that typically includes elements such as `<img />` and `<input />` which do not contain content to a list of items that now allow it to be dropped.
Build and run Creator application and add an `img` element, and another container element such as `div`, then attempt to drag the `img` into the `div`. This should now be possible.
As part of the drag and drop core functionality, this is untestable in unit tests.
=> fix: resolve an issue where linked data that cannot be dropped on was not allowed to drop

change/@microsoft-fast-foundation-48486c53-f43c-4a50-addc-b5ec1f19a59a.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/radio/radio.ts, sites/fast-website/package.json, sites/fast-website/src/app/components/color-swatch/color-swatch.styles.ts, sites/fast-website/src/app/components/color-swatch/color-swatch.template.ts, sites/fast-website/src/app/components/color-swatch/color-swatch.ts, sites/fast-website/src/app/components/fast-frame/fast-frame.template.ts, yarn.lock
Adds two color swatch options to the Colors panel on the website when the [EyeDropper API](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/EyeDropper/explainer.md) is available in the browser. This change also updates the `clickHandler` method on the Radio class to be a class method instead of a property.
* If the browser doesn't support the EyeDropper API, the two extra radio inputs won't be displayed.
* The actual controls that appear on the mouse cursor when `eyedropper.open()` is invoked is entirely handled by the browser.
1. Run the homepage project in `sites/fast-website` (`yarn start`)
2. Browse to the page in either Edge or Chrome Canary 95 or higher.
3. Click the Colors panel in the Fast Frame section of the homepage.
4. Activate the eyedropper selector:
* With the …
=> add custom fast-frame controls for browsers with eyedropper support

build/transform-fragments.js, change/@microsoft-fast-components-468df205-aa0e-4ab9-b585-90413eabada2.json
The CSS transform function can fail if a CSS comment contains an expression:
```css
/* this is a comment with an ${expression} in its contents */
```
This comment gets handled by the AST by splitting it up into parts:
1. `/* this is a comment with an `
2. the evaluation of `expression`
3. ` in its contents */`
Each string chunk (1 and 3) is sent to the `transformCSSFragment` function to be compressed, though since 1 starts with a comment and ends without closing, it can't be determined if there's an expression following or if it's the last chunk. In either scenario, the string is invalid and should throw an error when encountered.
Comments in CSS blocks should not contain `${expressions}` to avoid this issue. Rather than leaving these situations alone (not compressing them), it's better …
=> throw an error when comments in CSS contain expressions

sites/fast-website/src/app/components/fast-frame/fast-frame.styles.ts
Fixes an issue where the recent update to fast-tabs default visual styling was reset (correctly) to block. This addresses a visual regression on the site to ensure it appears as expected.
=> update fast-tab-panel to display flex on website fast-frame panel

packages/tooling/fast-tooling-react/package.json, packages/tooling/fast-tooling/package.json
This change freezes the current `@microsoft/fast-tooling` and `@microsoft/fast-tooling-react` libraries and prevents them from publishing while the migration to the new repository commences. Once the repositories and pipelines are set up, these packages will be removed from this repository.
=> chore: mark the fast-tooling and fast-tooling-react packages as private before the move to the new repositories

change/@microsoft-fast-foundation-84ca8ddb-ca59-43d3-a8cf-c6da286230da.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/foundation-element/foundation-element.ts
Fixes the `TS2344` errors caused by an type incompatibility:
```
Type 'K & FoundationElementDefinition' does not satisfy the constraint 'FoundationElementDefinition'.
Types of property 'template' are incompatible.
```
The error should not be present in either `packages/web-components/fast-foundation/dist/fast-foundation.d.ts` or `packages/web-components/fast-foundation/dist/dts/foundation-element/foundation-element.d.ts` after building.
=> fix type issue for FoundationElementTemplate

change/@microsoft-fast-components-c315a99e-78d1-400e-a54e-8bb28884332a.json, packages/web-components/fast-components/docs/api-report.md, packages/web-components/fast-components/src/custom-elements.ts
Critical fix for regression in scenarios using `allComponents`.
No issues. Discovered by the team late lat night.
Small change in the `allComponents` export to pass the registry params through correctly.
No tests here. We should really have our automated tests do something with Storybook maybe. It would be good to have a guarantee that the Storybook loads and basic scenarios for all components are exercised.
We need to make the same change in the Fluent UI Web Components /cc @chrisdholt
=> fix(allComponents): add missing param to registry

change/@microsoft-fast-foundation-5cf07db0-9c1c-4d0d-9a01-eb155212e068.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/tabs/tabs.ts
active indicator not animating when keyboarding.
Active indicator animates when, new tab is clicked, keyboarding (left, right, down, up, home and end), when activeId `attr` is changed.
=> fix: active indicator not animating when keyboarding

change/@microsoft-fast-components-1aa787ec-5c72-48a8-9733-1aa7a27c9b18.json, change/@microsoft-fast-foundation-83e650ae-505d-4c26-8b4e-b3b2ab75d3ae.json, packages/web-components/fast-components/src/tree-item/fixtures/tree-item.html, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/tree-item/tree-item.ts
This issue updates the click handler for tree item to *not* prevent default in order to enable valid scenarios such as anchors within the control.
closes #5159
=> do not prevent default on tree item click handler

change/@microsoft-fast-foundation-b999493b-a98c-4569-9ae5-27b1215ff0a6.json, packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.spec.ts, packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.ts
Horizontal scroll tests are failing for Mac. This disables the smooth scrolling when the speed is set to 0.
=> fix: Disabling scroll easing for speed=0

packages/utilities/fast-react-wrapper/package.json
Quick package update to prevent attempting to publish the React wrapper until we are ready.
n/a
We are doing this so we don't break the pipelines while we wait for official package publication approval.
n/a
We need to get publishing setup with Microsoft Open Source. Once that's done we can remove the `private` designation and publish.
=> chore(fast-react-wrapper): prevent publish attempt until ready

change/@microsoft-fast-foundation-55d49925-4f05-452e-b65f-39c0f8c58252.json, packages/web-components/fast-foundation/src/menu-item/menu-item.ts
Removes duplicate change event `emit`.
Closes: #5358
=> fix: change event emitted twice

change/@microsoft-fast-components-cede14a5-774e-4dab-b39c-015ac94db509.json, packages/web-components/fast-components/package.json, yarn.lock
Updates Playwright to a newer version for compatibility with `mac12-arm64` machines.
Tested on a MacBook Pro running MacOS 12.0.1 with Apple M1 Pro chip.
Installing packages should complete without errors when running `yarn` on a MacOS 12 device with an M1-based processor.
=> update playwright from 1.11.0 to 1.16.3

change/@microsoft-fast-components-90c5b08c-5716-4699-b157-5c772a4495fc.json, packages/web-components/fast-components/src/switch/switch.styles.ts
Instead of targeting all slots which breaks html elements being passed to the default slot we need to target only the slots we want the margin.
Related: #5407 
- x] I have modified an existing component
=> fix: proper css targeting for margin on slotted content

change/@microsoft-fast-colors-aab7ebc5-03bf-415e-9e08-f95280414752.json, change/@microsoft-fast-components-a5b1c895-d684-4fd7-9005-ef0a2419c0e4.json, packages/utilities/fast-colors/docs/api-report.md, packages/utilities/fast-colors/src/component-state-color-palette.ts, packages/web-components/fast-components/docs/api-report.md, packages/web-components/fast-components/src/color/palette.ts, packages/web-components/fast-components/src/color/recipes/neutral-layer.spec.ts
Updated the palette generation algorithm to maintain the amount of contrast between steps in the ramp rather than fill a fixed number of steps.
As the steps are used for interaction states in components, the fact that the perceived brightness between colors varies across the luminance spectrum, this makes it harder to achieve the same "feel" between light and dark mode. This change uses the closest known mathematical representation of how humans see color and brightness to keep the changes more consistent.
Also, this opens Adaptive Contrast we've been wanting to support for a while, by providing an easy parameter to adjust the amount of contrast between steps. This works best for some recipes, particularly fills. For instance, a neutral button fill will visibly have more contrast as you …
=> Updated to contrast-based palette

change/@microsoft-fast-components-619373e3-3e75-48b7-8fc9-98a416c51910.json, packages/web-components/fast-components/src/combobox/fixtures/base.html, packages/web-components/fast-components/src/select/fixtures/base.html
Updates the storybook fixtures for `<fast-select>` and `<fast-combobox>`, 
A combobox bug was discovered when clicking an associated label. See #5429 for the fix.
The storybook fixtures for select and combobox should now more accurately reflect the various states supported by each component.
=> update select and combobox fixtures

change/@microsoft-fast-components-7253ee5c-f527-43d3-a800-4e3bee4d3030.json, packages/web-components/fast-components/src/menu-item/menu-item.styles.ts, packages/web-components/fast-components/src/menu/fixtures/menu.html
When using a menu next to another menu, submenus will appear under menu items of the next menu.
https://github.com/microsoft/fast/issues/5417
This is the least obtrusive way to get flyout menus to go over other elements. This will fix both the issue of a menu next to another menu as well as submenus going under an element next to it that has `position: relative` or `position: absolute`. Even if that element doesn't have a z-index property. Developers can still manage z-index on the fast-menu-item as in the example that I added to the fixture. They could also add z-index to the fast-menu but that becomes trickier if they are using menus side-by-side.
Not really testable in Jest. Added a working example in the fixtures.
=> fix: incorrect z-index in fast-menu slot='submenu'

change/@microsoft-fast-foundation-a940dbfa-2032-470a-a328-cc925747cf44.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/combobox/combobox.spec.ts, packages/web-components/fast-foundation/src/combobox/combobox.ts
Clicking on a label for a `<fast-combobox>` should move focus to the text input control.
This bug was discovered while updating the fixtures for combobox.
Clicking on label which is associated with a combobox should move focus to the text input in the combobox. Clicking away should close the combobox.
=> fix: focus on combobox input when clicking an associated label

change/@microsoft-fast-components-8cbe62f9-3275-4866-ad93-d062424af767.json, change/@microsoft-fast-foundation-29f3478c-20e9-4088-8f0b-a1adf770691e.json, packages/web-components/fast-components/src/tooltip/fixtures/base.html, packages/web-components/fast-foundation/src/tooltip/tooltip.spec.ts, packages/web-components/fast-foundation/src/tooltip/tooltip.ts
This pr hooks up the new anchored region "center" position option so that "locktoviewport" works with tooltip.  The previous method of using css tricks to get the tooltip look centered was getting clipped in some cases.
=> fix: tooltip doesn't get clipped by viewport

change/@microsoft-fast-components-f3bbcdfe-0cb8-4a25-bf26-4c4593449db7.json, change/@microsoft-fast-foundation-9ae2c02f-3412-4ca0-b766-fba6dad2e98d.json, packages/web-components/fast-components/docs/api-report.md, packages/web-components/fast-components/src/listbox/listbox.vscode.definition.json, packages/web-components/fast-components/src/select/select.styles.ts, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/combobox/combobox.spec.md, packages/web-components/fast-foundation/src/combobox/combobox.spec.ts, packages/web-components/fast-foundation/src/combobox/combobox.template.ts, packages/web-components/fast-foundation/src/combobox/combobox.ts, packages/web-components/fast-foundation/src/listbox-option/listbox-option.spec.ts, packages/web-components/fast-foundation/src/listbox-option/listbox-option.template.ts, packages/web-components/fast-foundation/src/listbox-option/listbox-option.ts, packages/web-components/fast-foundation/src/listbox/index.ts, packages/web-components/fast-foundation/src/listbox/listbox.options.ts, packages/web-components/fast-foundation/src/listbox/listbox.spec.md, packages/web-components/fast-foundation/src/listbox/listbox.spec.ts, packages/web-components/fast-foundation/src/listbox/listbox.template.ts, packages/web-components/fast-foundation/src/listbox/listbox.ts, packages/web-components/fast-foundation/src/select/select.options.ts, packages/web-components/fast-foundation/src/select/select.spec.ts, packages/web-components/fast-foundation/src/select/select.template.ts, packages/web-components/fast-foundation/src/select/select.ts, sites/site-utilities/statics/assets/components/fast-listbox.schema.json
Improves the ARIA states and property handling for the `<fast-option>`, `<fast-listbox>`, `<fast-select>`, and `<fast-combobox>` components.
* Adds `aria-posinset` and `aria-setsize` attributes to `<fast-option>`
* Moves ARIA properties from the `<template>` to the internal `<input>` in `<fast-combobox>`
* Sets the `aria-controls` to match the internal `listbox` element in `<fast-select>` and `<fast-combobox>`
Fixes #5243 and #4824.
Screen reader results can vary drastically based on configuration and browser environment, so I compared the output to these examples:
* [Scrollable Listbox](https://w3c.github.io/aria-practices/examples/listbox/listbox-scrollable.html)
* [Select-Only Combobox](https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html)
* [Editable …
=> fix: listbox-option, listbox, select, and combobox accessibility

change/@microsoft-fast-components-5bc2c851-6675-45d7-b59a-bdf6a9e8a7b4.json, change/@microsoft-fast-element-9d2772cb-2204-4c88-ba6c-08241a150f3d.json, change/@microsoft-fast-foundation-4539ce14-6de8-4215-98fc-c8e3fe6d77ee.json, change/@microsoft-fast-react-wrapper-0aa4e7ec-9186-4de6-b32e-f2f6acf81f8b.json, change/@microsoft-fast-router-7a92c985-720d-4112-9e3a-67b519bf638a.json, examples/design-system-tutorial/package.json, examples/todo-app-tutorial/package.json, package.json, packages/utilities/fast-react-wrapper/package.json, packages/web-components/fast-components/package.json, packages/web-components/fast-element/package.json, packages/web-components/fast-foundation/package.json, packages/web-components/fast-router/package.json, sites/site-utilities/package.json, yarn.lock
Updates packages which have dependencies on the vulnerable `colors` NPM package:
* `rollup-plugin-filesize` from `8.0.2` to `9.1.2`
* updates `http-server` from `0.12.1` to `14.1.0`
* updates `favicons` from `6.1.0` to `6.2.2`
* locks `colors` to `1.4.0` for `karma` in the resolutions field
* locks `colors` to `1.4.0` for `favicons` in the resolutions field
Some packages are still vulnerable:
* Karma https://github.com/karma-runner/karma/pull/3740
* Favicons https://github.com/itgalaxy/favicons/pull/371
Packages which rely on a stricter version range and are less vulnerable:
* Certain Rushstack packages (resolve to unaffected `~1.2.1` range https://github.com/microsoft/rushstack/issues/3147)
* cli-table3 (dependency of Storybook, resolves to lower `^1.1.2` range …
=> chore: resolve vulnerable sub-dependencies

.github/workflows/cd-deploy-color-staging.yml, .github/workflows/cd-deploy-explore-staging.yml, .github/workflows/cd-deploy-www-staging.yml
Allows the PR site deployment steps to continue when encountering errors.
This should make site deployments for PRs succeed with a failure message, rather than display as an action failure.
PR deployment steps for both the Color Explorer and Component Explorer may still fail, but they'll no longer cause every PR to appear as if it has completely failed.
The deploy steps should be modified to either be triggered manually, or made to delete the oldest deployment if there are no more available staging environments.
=> allow pr deploy steps to continue on errors

change/@microsoft-fast-foundation-4ee40a31-ef0d-49e1-bf01-ca13520e74d9.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/number-field/number-field.spec.ts, packages/web-components/fast-foundation/src/number-field/number-field.ts, packages/web-components/fast-foundation/src/slider/slider.spec.ts, packages/web-components/fast-foundation/src/slider/slider.ts
Adds `valueAsNumber` property to number field and slider. See linked issue for background.
Fixes #5506 
Not sure if there needs to be documentation added for this property, let me know if so.
Added unit tests for getting/setting `valueAsNumber` property.
None
=> feat: add valueAsNumber property to number field and slider

change/@microsoft-fast-element-388fae35-a3bd-4880-93de-c69f1dee7166.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/docs/guide/using-directives.md, packages/web-components/fast-element/src/templating/repeat.ts
Proposing this as I am encountering situations where the repeat directive reuses "dirty" views which may have artifacts left over from the previous item it displayed.  This change adds a `recycle` option to the repeat directive which forces the creation of a new view from the template each time a new item is displayed.  The default value of `true` maintains the current behavior.
Saw flickering of past states like images with old content during list manipulation.
=> feat: add 'recycle' option to repeat directives

change/@microsoft-fast-components-298c2320-eea5-42e0-9ef4-278fb8b7c952.json, change/@microsoft-fast-foundation-deec4a21-5dbd-4e3d-870c-b1bbc63cfce1.json, packages/web-components/fast-components/src/listbox/README.md, packages/web-components/fast-components/src/listbox/fixtures/multiselect.html, packages/web-components/fast-components/src/listbox/listbox.stories.ts, packages/web-components/fast-components/src/listbox/listbox.vscode.definition.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/listbox-option/listbox-option.spec.md, packages/web-components/fast-foundation/src/listbox/README.md, packages/web-components/fast-foundation/src/listbox/listbox.element.ts, packages/web-components/fast-foundation/src/listbox/listbox.spec.md, packages/web-components/fast-foundation/src/listbox/listbox.spec.ts, packages/web-components/fast-foundation/src/listbox/listbox.template.ts, packages/web-components/fast-foundation/src/listbox/listbox.ts, sites/site-utilities/statics/assets/components/fast-listbox.schema.json
Adds the `multiple` attribute to `<fast-listbox>`.
* #4190 
This PR supersedes the earlier #4974 PR.
The `<fast-listbox>` element should accept the `multiple` boolean attribute, which will put the component into a mode where more than one option can be selected by a user.
_For the purposes of this implementation, "focus" is the `checked` state of the listbox's options. While interacting with a listbox, focus should remain on the listbox and shouldn't be placed on the options. [See this note for more information](https://www.w3.org/TR/wai-aria-practices-1.2/#h-note-16)._
* The `ArrowDown` key should move focus to the next selectable option.
* Holding `Shift` while pressing `ArrowDown` should toggle focus for the next selectable option.
* The `ArrowUp` key should move focus to the previous …
=> add multiselect functionality to listbox

change/@microsoft-fast-foundation-2addeddd-ae48-4d72-b6bc-7ad7415f6a71.json, packages/web-components/fast-foundation/src/menu/menu.spec.ts, packages/web-components/fast-foundation/src/menu/menu.ts
A user encountered an issue where the menu was not reliably updating the properties on child menu items on subsequent connect events for the same menu.  This change specifically updates child menu items when the component connects as well as when the slotted children change.
user reported
=> fix: menu should update child items on connect

change/@microsoft-fast-components-e8145ce8-2bce-4cb7-8776-807efd872c7e.json, change/@microsoft-fast-foundation-b3093cad-95fb-4a13-8018-99d9429ea39c.json, packages/web-components/fast-components/src/tooltip/fixtures/base.html, packages/web-components/fast-components/src/tooltip/tooltip.stories.ts, packages/web-components/fast-foundation/src/tooltip/tooltip.spec.ts, packages/web-components/fast-foundation/src/tooltip/tooltip.ts
dynamically changing tooltip anchorElement worked, but changing the anchor attribute after the component was created did not.  This change enables anchor attribute changes to take effect.
fixes https://github.com/microsoft/fast/issues/5327
=> fix: changing tooltip anchor attribute should take effect

change/@microsoft-fast-components-31def213-6e59-4866-973f-61494c9ce492.json, change/@microsoft-fast-foundation-4b675f50-9184-4758-8f84-366ba154ae1e.json, packages/web-components/fast-components/src/listbox/fixtures/base.html, packages/web-components/fast-components/src/listbox/listbox.styles.ts, packages/web-components/fast-foundation/src/listbox/listbox.spec.ts, packages/web-components/fast-foundation/src/listbox/listbox.ts
This change adds styling too for a `disabled` `listbox`. This also prevents setting the initial `listbox-item` to `selected` if `listbox` is `disabled`. However, it's important to note that if an item is set to `selected` or the `listbox` is set to `disabled` after initial load the `listbox-item` would remain selected even if the `listbox` is `disabled`. This matches the native behavior of `select` and `option`
Disabled
Disabled but an item is set to selected
Closes: #4137
=> fix: disabled listbox missing styles & allows click

change/@microsoft-fast-components-ad4c2131-3210-4837-819e-c22c0554d1fc.json, packages/web-components/fast-components/src/styles/patterns/button.ts
This was an issue filed awhile ago that only was partially fixed, the `control` `part` in button was not inheriting `font-weight` or `font-size` changes set on the `host` element.
```css
fast-button {
font-size: 30px;
font-weight: 900;
}
```
Before fix:
After fix: 
Closes: #3578
=> fix: font-weight to inherit to button control part

change/@microsoft-fast-components-81388374-b10c-4574-94fc-b77db302786a.json, packages/web-components/fast-components/src/number-field/number-field.styles.ts, packages/web-components/fast-components/src/text-field/text-field.styles.ts
Focus style on text and number fields does not use `focusStrokeWidth` (as e.g. do select).
Question: there is also a variation the text and number fields are using `inset` box-shadow when select is not. Does this need to be changed too? If so which one is the correct style to apply?
Fixes #5565
=> `focusStrokeWidth` not applied on text-field and number-field

change/@microsoft-fast-foundation-c37ba884-df53-40b6-988c-6eff22ae40a3.json, packages/web-components/fast-foundation/src/listbox-option/listbox-option.spec.ts, packages/web-components/fast-foundation/src/listbox-option/listbox-option.ts
Sets the `<fast-option>` value property to always match the `value` attribute if present.
Closes #5569
Two tests added to check value and text content collisions.
=> allow empty string values for listbox-option value attribute

change/@microsoft-fast-colors-647d4127-6f05-471a-9b55-37bea72a2a57.json, packages/utilities/fast-colors/docs/api-report.md, packages/utilities/fast-colors/src/color-converters.spec.ts, packages/utilities/fast-colors/src/color-converters.ts
Calculating an overlay color is the base of the support for opacity in the color algorithms. This is from some of the proof of concept work and automatically determines if the overlay color should be white or black rather than requiring a color to be passed in.
One fewer change in the way of adding support for opacity in the color system!
=> Updated calculateOverlayColor to automatically determine the overlay color

packages/tooling/fast-figma-plugin-msft/src/core/ui/components/generic-recipe/index.ts, packages/tooling/fast-figma-plugin-msft/src/core/ui/components/index.ts, packages/tooling/fast-figma-plugin-msft/src/core/ui/declarations.d.ts, packages/tooling/fast-figma-plugin-msft/src/core/ui/design-token-registry.ts, packages/tooling/fast-figma-plugin-msft/src/core/ui/index.tsx, packages/tooling/fast-figma-plugin-msft/src/core/ui/recipes.ts, packages/tooling/fast-figma-plugin-msft/src/figma/node.ts
Added support for applying text design tokens to text layers in Figma.
The plugin is still very much in-progress, but this is hopefully a nice, contained change.
The test page has been updated to have text recipes applied to all text layers. https://www.figma.com/file/YCFM1UHB0pphAUd8llTGez/Plug-in-Test-Components?node-id=0%3A1
=> Figma plugin: Add support for text recipes

beachball.config.js, change/@microsoft-fast-element-ecbe6511-b19c-4312-91f2-1c354ebd5245.json, change/@microsoft-fast-router-08a4dedc-a404-44ca-ac6a-fe3b4b22a2a1.json, package.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/dom.spec.ts, packages/web-components/fast-element/src/dom.ts
This PR adds a feature that enables switching the rendering engine into a fully synchronous mode. Ordering of DOM updates is still preserved, such that nested tasks do not execute until after the parent task.
Closes #5592 
I added a method called `DOM.setUpdateMode()` to turn on/off async updates. Internally, work is still added to a queue so that ordering is preserved in nested tasks. However, once work is added, if the queue only has one item (it's not being currently drained synchronously) then we begin synchronously draining the queue. Similar updates were made to how exceptions are handled. An interesting detail is that once an exception is thrown the queue needs to be emptied in synchronous mode.
Relevant tests from the async test suite were replicated and modified to ensure …
=> feat: enable synchronous dom updates for SSR

change/@microsoft-fast-element-58e983d2-9c67-4292-b678-88bc265b1fe8.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/components/fast-definitions.spec.ts, packages/web-components/fast-element/src/components/fast-definitions.ts, packages/web-components/fast-element/src/index.ts, packages/web-components/fast-element/src/styles/css.ts, packages/web-components/fast-element/src/styles/element-styles.ts, packages/web-components/fast-element/src/styles/styles.spec.ts
This PR reworks `ElementStyles` so that it is now a concrete class with pluggable strategies for handling how styles are added/removed to/from elements. The strategy is not created until the styles need to be added to an element.
* Closes #5594
The main purpose of this change is to enable our SSR implementation to provide a custom strategy so that it can apply special server behavior around styles. 
All existing style tests were adjusted to the new APIs in order to ensure that previous functionality still works correctly.
We will likely refine the APIs as part of the SSR integration process.
=> feat: enable pluggable style handling strategies

change/@microsoft-fast-element-7ca9a49d-04d0-477b-8e6b-23249c19a3f2.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/package.json
When running `npm run build` inside `@microsoft/fast-element` package, the following error is encountered:
`Error: Error parsing tsconfig.json content: Unknown compiler option 'importsNotUsedAsValues'.`
This happens because running `api-extractor` happens as a final step in the `build`, and the reason this error occurs is that the currently pinned version `typescript` used by `api-extractor` is below `3.8.0` when `importsNotUsedAsValues` was introduced as a flag. This change updates the version, we now have no errors, but the following warnings with this change:
```
Warning: You have changed the public API signature for this project. Updating docs/api-report.md
Warning: dist/dts/dom.d.ts:70:8 - (tsdoc-param-tag-missing-hyphen) The @param block should be followed by a parameter name and …
```
=> Updated api-extractor version and exported markdown

change/@microsoft-fast-element-11926a01-e901-4013-acaa-a512f7281849.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/components/controller.ts, packages/web-components/fast-element/src/components/fast-element.ts
This change updates the function signature of `FASTElement.attributeChangedCallback` to accept `null` as both a previous and next value. This aligns the function signature to the platform behavior, where the 'previous' value will be `null` when the attribute is being added, and the 'next' value will be null when the attribute is being removed.
=> fix: add null value as acceptable value to FASTElement.attributeChangedCallback

change/@microsoft-fast-foundation-3f378ae2-8f62-4b34-a458-937dc73de19e.json, packages/web-components/fast-foundation/src/data-grid/data-grid-row.ts, packages/web-components/fast-foundation/src/data-grid/data-grid.ts, packages/web-components/fast-foundation/src/design-system/component-presentation.ts, packages/web-components/fast-foundation/src/design-token/custom-property-manager.ts, packages/web-components/fast-foundation/src/picker/picker.ts
This work updates components in `@microsoft/fast-foundation` to use updated APIs from FAST Element 2.0.
Relates to #5641
=> Updated to use the new FAST element 2.0 APIs for creating behaviors and creating element styles

change/@microsoft-fast-element-725e8774-1f96-49df-a63d-64d0b4bf5d6b.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/dom.ts, packages/web-components/fast-element/src/index.ts, packages/web-components/fast-element/src/observation/array-change-records.ts, packages/web-components/fast-element/src/styles/element-styles.ts, packages/web-components/fast-element/src/templating/compiler.spec.ts, packages/web-components/fast-element/src/templating/compiler.ts, packages/web-components/fast-element/src/templating/html-directive.ts, packages/web-components/fast-element/src/templating/markup.ts, packages/web-components/fast-element/src/templating/repeat.ts, packages/web-components/fast-element/src/templating/template.spec.ts
This feature exposes new `Markup` and `Parser` API gateways. Some APIs from the `DOM` gateway were moved to the `Markup` gateway, constituting a breaking change. This change did allow us to better encapsulate some internal details while exposing better APIs, particularly for SSR scenarios.
* Closes #5639 
None of the functionality here is really changed. Rather, APIs are moved around to more properly expose various capabilities.
A few documentation comment warnings were also resolved during this refactor. I left the binding-related warnings as is for now since that part of the codebase is still likely to change in a way that would affect the code docs.
Existing tests were fixed up to match the new APIs.
Next, @nicholasrice will take advantage of these new APIs in the SSR work. Based on …
=> feat: expose official Markup and Parser APIs

change/@microsoft-fast-router-d8d52093-fa07-417d-a12d-acdab4a96101.json, packages/web-components/fast-router/src/contributors.ts
Due to a change in https://github.com/microsoft/fast/pull/5649 the `DOM` export no longer contains `createCustomAttributePlaceholder` and has been replaced with a new export that has been utilized in this change.
Related to #5641
=> Fixed an updated export from FAST element 2.0

change/@microsoft-fast-element-715828c0-7339-4dde-a445-8a5407f0a3b9.json, packages/web-components/fast-element/src/observation/array-observer.ts
Fixes a bug in my previous attempt for FE2 to fix duplicate array patching. I discovered this while fixing duplicate patching in FE1.
* Closes #5652 
This is the FE2 version. This was separately applied since the source of this file has significantly changes from FE1.
It's important to note that we still need to configure the array observer factory per library instance but we don't want to patch Array more than once, since that's global.
Please also review #5654
Nearly impossible to test this. All current tests still pass.
I discovered a circular reference from binding through to Markup and back to binding. I have any idea for how to fix this but will do it in a follow-up PR along with some refactoring of the compiler APIs.
=> fix: prevent duplicative array observation patch (FE2)

change/@microsoft-fast-components-069ebb02-c4b4-418d-b067-b778330ef651.json, packages/web-components/fast-components/src/horizontal-scroll/horizontal-scroll.pw.spec.ts
* Fixes the "FASTHorizontalScroll should disable the next flipper if content is less than horizontal-scroll width" test.
* Fixes minor lint warnings in the horizontal scroll playwright tests.
This test was failing on GH Actions for some browsers.
The "FASTHorizontalScroll should disable the next flipper if content is less than horizontal-scroll width" test should pass in all playwright browsers.
This is part of a series of fixes for our Playwright tests:
* #5646
=> fix horizontal scroll playwright test

change/@microsoft-fast-element-e1bbb99b-6d2f-43cf-ab46-772843f26be9.json, packages/web-components/fast-element/src/observation/array-observer.ts
Some folks incorrectly use `for/in` on `Array` instances. This is a bad practice but people still do it and there is lots of legacy code in existence that makes this mistake which may never be updated.
This PR makes our Array observation bookkeeping properties non-numerable so that `for/in` does not return them in the event that a developer makes the above mistake or is using a 3rd party library which makes this mistake.
* #5652
This is a very small change that shifts the code from simple field assignments to `defineProperty` calls, so we can provide descriptor data and make the properties non-enumerable.
All existing tests continue to pass.
A second matching PR will be incoming soon for FASTElement 2.0.
=> fix: defend against for/in use on arrays

change/@microsoft-fast-element-8e5ad334-ac12-466b-8440-415abd011eb0.json, packages/web-components/fast-element/src/observation/array-observer.spec.ts, packages/web-components/fast-element/src/observation/array-observer.ts, packages/web-components/fast-element/src/observation/observable.spec.ts
Some folks incorrectly use `for/in` on `Array` instances. This is a bad practice but people still do it and there is lots of legacy code in existence that makes this mistake which may never be updated.
This PR makes our Array observation bookkeeping properties non-numerable so that `for/in` does not return them in the event that a developer makes the above mistake or is using a 3rd party library which makes this mistake.
* #5652
This is a very small change that shifts the code from simple field assignments to `defineProperty` calls, so we can provide descriptor data and make the properties non-enumerable.
All existing tests continue to pass.
Further improvements to array observation planned next sprint.
=> fix: defend against for/in use on arrays (FE2)

change/@microsoft-fast-element-d6062145-f143-437a-ae17-b8a923f1208e.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/templating/binding.ts
Just adding some basic doc tags to temporarily quiet the api extractor.
* Closes #5664
n/a
I'll follow up this PR with further improvements to the binding system as well as full docs once this work bubbles up in the priority queue.
=> docs: add alpha tags to unfinished binding APIs

change/@microsoft-fast-element-47b69b7f-3b12-4084-b343-e7ee172f5539.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/components/controller.ts
This PR moves the template and style resolution logic into the property getters where it is lazily evaluated. This can then be used by SSR to gain access to the fully resolved template/styles.
* Closes #5638 
* Closes #5618 
Mostly a move of internal code so the functionality can be access for SSR scenarios. Some guards were added to style APIs to make them more resilient and to parallel template APIs.
All existing tests continue to pass.
None at this time.
=> refactor: move template/style resolution to lazy getter

change/@microsoft-fast-components-cc08498d-1968-49eb-82f8-b94e4abb7154.json, change/@microsoft-fast-foundation-aa1aae9c-ad90-401b-ae91-c23afb148cf6.json, packages/web-components/fast-components/src/data-grid/fixtures/base.html, packages/web-components/fast-foundation/src/data-grid/data-grid.spec.ts, packages/web-components/fast-foundation/src/data-grid/data-grid.ts
With this change data-grid will attempt to generate 'grid-template-columns' for a manually constructed grid.
closes https://github.com/microsoft/fast/issues/5659
Tests pass, added check to confirm we don't generate a header when rowsData is empty.
=> fix: generate grid columns for manual grid

change/@microsoft-fast-element-19ee7846-01d0-4dc8-babc-29a4537526a5.json, packages/web-components/fast-element/src/components/controller.spec.ts, packages/web-components/fast-element/src/components/controller.ts
As a first step towards enabling client hydration of SSR'd components, we should not fail when Shadow DOM exists on a component when it's constructed. To accomplish this, we don't attach shadow DOM if it exits, but instead clear out the HTML so that the client view can re-populate it.
Closes #5627 
The feature involves two changes:
1. Detect the existing shadow root in the constructor and note that for later, avoiding attach of a shadow root.
2. When the component is ready to render, and the shadow root was pre-existing, clear out the HTML.
Added a test to assert behavior in the presence of existing shadow dom.
In a future iteration we'll look into upgrading existing shadow DOM content rather than re-creating it.
=> feat: handle existing shadow roots when upgrading

specs/fast-cli.md
This specification is based on the need for FAST to have a CLI for accelerating workflows and provide an easy way to initialize a project. 
Related to https://github.com/microsoft/fast/issues/5578
I believe some work has been done on this already but the priorities have shifted around, this is my interpretation for what the requirements are and what generally the goals should be. Please give this a thorough read and determine if this captures all requirements, an MVP roadmap is included at the bottom. This is targeting the feature branch including FAST element 2.0 and the server side rendering work as I believe these are related.
=> Added specification for a FAST CLI and project initialization package

change/@microsoft-fast-foundation-bde5b90a-8b1c-4115-9221-800c63ad5f7d.json, packages/web-components/fast-foundation/src/data-grid/data-grid.spec.ts, packages/web-components/fast-foundation/src/data-grid/data-grid.ts
Fixing an issue with an earlier change that incorrectly based the number of columns generated based on the number of rows instead of the number of cells in the first row
Found an issue with calendar
Need to add tests for manual grid.  Looking at that now.
=> fix: data grid auto column fix

change/@microsoft-fast-components-fb0919b2-9a12-43b9-a7da-8a4f0b405f01.json, change/@microsoft-fast-foundation-f5abd6ff-1492-4d34-80dc-b57d1489c3df.json, packages/web-components/fast-components/src/horizontal-scroll/fixtures/horizontal-scroll.html, packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.spec.ts, packages/web-components/fast-foundation/src/horizontal-scroll/horizontal-scroll.ts
When there are only 2 items in view, the scroll to previous flipper is not working.
https://github.com/microsoft/fast/issues/5676
The boundary check didn't include if the 
I added a test that includes a container that has only 2 items in view. I also created an example in storybook.
=> Fix: horizontal-scroll to previous doesn't work for 2 item width

change/@microsoft-fast-components-e25eb67c-a6bb-4476-b996-5049eb18f26a.json, change/@microsoft-fast-foundation-dd0eb23b-8eef-49ad-b97d-9b367f71c782.json, packages/web-components/fast-components/src/tooltip/fixtures/base.html, packages/web-components/fast-components/src/tooltip/tooltip.styles.ts, packages/web-components/fast-foundation/src/tooltip/tooltip.ts
According to standards, the tooltip content should remain visible if the pointer is hovered over it:
Hoverable
If pointer hover can trigger the additional content, then the pointer can be moved over the additional content without the additional content disappearing;
Source: https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus
This change adds a short 60ms delay before tooltips are dismissed after mouseOut.  Tooltips remain visible if the anchor or tooltip are hovered before the delay elapses.
closes https://github.com/microsoft/fast/issues/5660
=> fix: tooltips remain visible when hovered

packages/web-components/fast-ssr/src/template-parser/op-codes.ts, packages/web-components/fast-ssr/src/template-parser/template-parser.spec.ts, packages/web-components/fast-ssr/src/template-parser/template-parser.ts
This PR adds a new op type to the template parser, as well as code to emit the op code appropriately.
**Context:**
When a `FASTElement` is registered with a `ViewTemplate` that has a `<template>` element as its root element, the templating engine reflects all of the attributes and bindings on this `<template>` element to the *host element*. It then renders the template content as if this `<template>` element did not exist. 
SSR infrastructure needs to align to this behavior, but it also needs the capability to emit a `<template>` element verbatim, just like any other native HTMLElement. To handle both cases, the template parser will emit op codes for template element opening and closing. These op codes will need to be handled in two different ways:
1. When the TemplateOpenOp is the …
=> Adds TemplateOp to SSR template parser

packages/tooling/fast-vscode-syntax-highlighting/package.json
Sets the `shouldPublish` flag to `false` for the tagged templates syntax highlighting extension to hopefully prevent Beachball from publishing it to NPM.
🤷🏻
=> prevent syntax highlighting extension from publishing to NPM

change/@microsoft-fast-element-a472079b-2d1a-4c93-a8e4-786429b46d18.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/components/fast-definitions.ts, packages/web-components/fast-element/src/dom.ts, packages/web-components/fast-element/src/observation/observable.ts, packages/web-components/fast-element/src/platform.spec.ts, packages/web-components/fast-element/src/platform.ts, packages/web-components/fast-element/src/templating/binding.ts
Currently, you cannot have multiple copies of `@microsoft/fast-element` running on the same page at the same time. This has to do with certain core services and their private state which break each other. For example, an observable defined by one instance of FAST cannot be observed by another because the notifier cache is not shared between the two versions.
This PR attempts to extract a set of core services that can be shared across all instances of `@microsoft/fast-element` running on the same page.
At present, kernel services across fast-element 1.x and 2.x can be shared, provided that fast-element 2.x is loaded first. Another way to put it is that the 2.x kernel is backwards compatible with the 1.x kernel, but the 1.x kernel is not forward compatible with the 2.x kernel, due to new …
=> feat: enable multiple instances of fast-element on a page at once

change/@microsoft-fast-element-5027f6e6-0686-40b1-965f-adc905136502.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/styles/element-styles.ts, packages/web-components/fast-element/src/templating/compiler.spec.ts, packages/web-components/fast-element/src/templating/compiler.ts, packages/web-components/fast-element/src/templating/repeat.ts, packages/web-components/fast-element/src/templating/template.ts
This PR refactors the template compilation process so that the template compiler can be swapped out, which is particularly important for SSR. Along those lines, the code from `ViewTemplate` that worked directly with template elements has been moved into the default compiler so that the SSR compiler doesn't have to work around that.
Closes #5703 
This is mostly a move of code and an addition of an API to configure the compilation function that is used. Not much to it in the end.
All existing compiler and template tests continue to pass. The new API is exercised through the default set of the existing compiler as part of the templating system.
Next steps are for @nicholasrice to leverage these features in the SSR renderer.
=> refactor: enable pluggable template compiler for SSR scenarios

change/@microsoft-fast-element-0e2b9162-79c1-43de-adf5-13989cd29ee1.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/components/controller.spec.ts, packages/web-components/fast-element/src/templating/compiler.ts, packages/web-components/fast-element/src/templating/markup.ts, packages/web-components/fast-ssr/src/template-parser/op-codes.ts, packages/web-components/fast-ssr/src/template-parser/template-parser.spec.ts
Previously, the syntax for embedding markers in comments was different from attributes and content. This PR unifies the markup and parsing so that a single API can be used for all scenarios.
* Closes #5694
* Previous`Markup` APIs for extracting the `HTMLDirective` index from a comment have been removed, since this is now handled by the unified `Parser` API.
* The public export of the `marker` has also been removed. With these changes, I think SSR doesn't need access to those internal details anymore. It can just use the new`Parser` APIs.
* Fixed some compiler logic that was out of sync from FE 1.0.
All existing tests pass.
The next item to work on is #5683 which should provide more of the parsed data via the directive structures so that SSR doesn't have to figure that out.
=> feat: create unified API for parsing markers

change/@microsoft-fast-foundation-5c1ea5fd-9497-4846-bfa7-a8d305856136.json, packages/web-components/fast-foundation/src/tree-view/tree-view.spec.ts, packages/web-components/fast-foundation/src/tree-view/tree-view.ts
Fix to limit tree view selection to a single item.  Regression from here - https://github.com/microsoft/fast/pull/5350.
closes https://github.com/microsoft/fast-blazor/issues/158
Added test for this
=> Fix: tree view single select

change/@microsoft-fast-element-4013c3d3-7d0e-405e-b3d0-c516701f2438.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/index.ts, packages/web-components/fast-element/src/templating/binding.ts, packages/web-components/fast-element/src/templating/compiler.spec.ts, packages/web-components/fast-element/src/templating/compiler.ts, packages/web-components/fast-element/src/templating/html-directive.ts, packages/web-components/fast-element/src/templating/markup.ts, packages/web-components/fast-element/src/templating/template.spec.ts, packages/web-components/fast-element/src/templating/template.ts, packages/web-components/fast-ssr/src/template-parser/template-parser.ts
Expose more metadata about captured bindings through the `AspectedHTMLDirective` interface. This should enable us to remove duplication in the SSR template parser.
* Closes #5683 
This is mostly a refactoring and exposing of metadata that was either present or was implicit. So, it formalizes this as part of the `AspectedHTMLDirective` interface.
The `InlineHTMLDirective` was removed. It seemed like it could be merged with `AspectedHTMLDirective`.
While doing this work, I uncovered a cyclic dependency related to a couple of the areas I was working on. So, I moved the `aggregate` method off the `Parser` gateway. I created a new `Compiler` gateway to host the `aggregate` method as well as the `compile` API and method of changing the strategy for compilation.
Current tests were expanded to …
=> feat: aspected html directive exposes metadata

change/@microsoft-fast-components-39bb9635-0498-4578-9bdc-e067511340bc.json, change/@microsoft-fast-foundation-4f66052e-e470-4bb4-b664-b587959b300b.json, packages/web-components/fast-components/src/data-grid/data-grid.stories.ts, packages/web-components/fast-components/src/data-grid/data-grid.vscode.definition.json, packages/web-components/fast-components/src/data-grid/fixtures/base.html, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/data-grid/data-grid-cell.template.ts, packages/web-components/fast-foundation/src/data-grid/data-grid-cell.ts, packages/web-components/fast-foundation/src/data-grid/data-grid.spec.md, packages/web-components/fast-foundation/src/data-grid/data-grid.spec.ts, packages/web-components/fast-foundation/src/data-grid/data-grid.ts, sites/site-utilities/statics/assets/components/fast-data-grid.schema.json
Yes, your grids can have grids.
This pr adds a nested grid example and some minor fixes/changes to data-grid components to get the keyboarding to work correctly (ie. arrow keys to move around the grid, "Enter" to access a child grid, "esc" to move back to the parent).
The one notable change is adding a "no-tabbing" attribute to data grid so that nested grids don't add themselves to the tab queue which is a proposed fix for this issue: https://github.com/microsoft/fast/issues/4739.  
https://github.com/microsoft/fast/issues/4739
=> feat: nested grid

change/@microsoft-fast-element-06c5f5c1-f172-4ba0-864e-9d9b494adda5.json, change/@microsoft-fast-foundation-e05243ea-6de7-4694-abe1-2c4b64a25077.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/components/controller.ts, packages/web-components/fast-element/src/components/fast-definitions.ts, packages/web-components/fast-element/src/dom.ts, packages/web-components/fast-element/src/index.ts, packages/web-components/fast-element/src/interfaces.ts, packages/web-components/fast-element/src/observation/array-observer.ts, packages/web-components/fast-element/src/observation/observable.ts, packages/web-components/fast-element/src/platform.spec.ts, packages/web-components/fast-element/src/platform.ts, packages/web-components/fast-element/src/polyfills.ts, packages/web-components/fast-element/src/styles/element-styles.ts, packages/web-components/fast-element/src/styles/styles.spec.ts, packages/web-components/fast-element/src/templating/binding.ts, packages/web-components/fast-element/src/templating/compiler.spec.ts, packages/web-components/fast-element/src/templating/compiler.ts, packages/web-components/fast-element/src/templating/html-directive.ts, packages/web-components/fast-foundation/src/data-grid/data-grid-cell.template.ts, packages/web-components/fast-foundation/src/data-grid/data-grid-row.template.ts, packages/web-components/fast-foundation/src/radio/radio.template.ts, packages/web-components/fast-foundation/src/utilities/intersection-service.ts
This PR removes all polyfill and polyfill-like code from fast-element. This reduces the size of fast-element. The polyfills can be included optionally if needed, which is still required for all non-Chromium browsers (due to adoptedStyleSheets). However, if you are targeting a Chromium-based environment only (Edge, WebView2, Electron, etc.) then you no longer have to pay the cost of this code.
* Closes #5751 
It may look like a lot of changes, but it's mostly just moving things around. The one exception is the approach to style strategies which moves that to a core service so that the polyfill-like implementation can be remove from the core and the core can still detect its presence.
All tests continue to pass after the refactor.
Next, I'll be looking at whether we can reduce the amount of …
=> refactor: extract polyfill and polyfill-like code to an optional module

change/@microsoft-fast-foundation-697dbb73-2147-43e2-83dc-a6cf59cb41fb.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/select/select.ts
Changing the "open" attribute in the Select component in Fast-Foundation from @internal to @public. 
When "open" was changed from just a property into an attribute it was not made public as an oversight. This is causing problems with integrating the Custom Element Manifest Analyzer which sees this as an error.
This change also brings the Select component in line with ComboBox which does have a public "open" attribute. 
This is a non-breaking API change.
=> feat: change open attribute in select component from internal to public

change/@microsoft-fast-element-07e66f75-3b9f-4287-b48c-3151388366f4.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/package.json, packages/web-components/fast-element/src/components/attributes.ts, packages/web-components/fast-element/src/components/controller.ts, packages/web-components/fast-element/src/debug.spec.ts, packages/web-components/fast-element/src/debug.ts, packages/web-components/fast-element/src/interfaces.ts, packages/web-components/fast-element/src/observation/observable.ts, packages/web-components/fast-element/src/platform.ts, packages/web-components/fast-element/src/templating/binding.ts, packages/web-components/fast-element/src/templating/compiler.ts, packages/web-components/fast-element/src/templating/slotted.ts
Extract all warn/error message strings from the core library. Add warn/error helpers that can be plugged in using a new debug module. This will allow us to add more messages, and more detail without increasing library size.
* Closes #2209 
* Closes #5323 
All messages were extracted to the new `debug` module. An enum that describes the message is used against a global FAST error/warn API. The error codes needed to be duplicated into the `debug` module in order to enable it to be a single vanilla JS file with no imports. Unfortunately, TS won't allow type-only imports of a const enum. So, there was no way to import that without it creating an import in the dist code, which would be useless.
Without the `debug` module loaded before the main library, these functions are basically no-ops. …
=> feat: add warn/error message infrastructure

change/@microsoft-fast-components-425ca2e5-10ae-4ec1-9d94-78f7fe68d4ce.json, change/@microsoft-fast-foundation-8f418cf2-dfa6-4780-a462-4d87584b70f9.json, packages/web-components/fast-components/src/menu/fixtures/menu.html, packages/web-components/fast-foundation/src/menu-item/menu-item.ts, packages/web-components/fast-foundation/src/menu/menu.spec.ts, packages/web-components/fast-foundation/src/menu/menu.ts
Fixes an issue with menu and menu item elements where elements including the `hidden` attribute were still present in the tabindex.
closes #5691
If you like you can run storybook and view the last example which illustrates the expected behavior
=> fix: elements with hidden attribute should not appear in tabindex

sites/fast-color-explorer/app/components/color-picker/README.md, sites/fast-color-explorer/app/components/color-picker/color-picker.form-associated.ts, sites/fast-color-explorer/app/components/color-picker/color-picker.styles.ts, sites/fast-color-explorer/app/components/color-picker/color-picker.template.ts, sites/fast-color-explorer/app/components/color-picker/color-picker.ts, sites/fast-color-explorer/app/components/color-picker/index.ts, sites/fast-color-explorer/app/index.ts, sites/fast-color-explorer/package.json, yarn.lock
This PR forks the color picker added from FAST tooling to remove a circular dependency. `@microsoft/fast-tooling` takes a dependency on FAST packages, which in turn are hoisted via yarn/lerna. This issue came up while working to unblock #5198. 
n/a
=> fork color picker from fast-tooling to remove circular dependency

change/@microsoft-fast-foundation-c3a0d9cd-9fa9-430f-8518-2da44c6c2590.json, packages/web-components/fast-foundation/src/accordion-item/accordion-item.template.ts
The Acccordion Item had duplicate classes applied for "heading" and the `part` attribute was placed incorrectly on the slot. This PR updates the class name to be `heading-content` and moves the corresponding part to the correct node.
Closes #5764
=> fix heading class name and part association in accordion item

change/@microsoft-fast-components-0f5602ef-a1c2-4f35-83a0-3e883906645e.json, change/@microsoft-fast-element-e7b9adf7-1b40-4e7e-896f-c29600f26654.json, change/@microsoft-fast-foundation-b8a22db2-e6e3-4ba0-a9e1-725a4ef68eda.json, packages/web-components/fast-components/src/styles/size.ts, packages/web-components/fast-components/src/tree-item/tree-item.styles.ts, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/styles/css-directive.ts, packages/web-components/fast-element/src/styles/css.ts, packages/web-components/fast-element/src/styles/styles.spec.ts, packages/web-components/fast-foundation/src/design-token/design-token.spec.ts, packages/web-components/fast-foundation/src/design-token/design-token.ts
This PR implements a new design for `CSSDirective` that matches the new `HTMLDirective` API. The changes are as follows:
* Decouples directives and behaviors.
* Directives can now add 0-N behaviors when they generate CSS.
* createCSS() now receives a method for adding behaviors.
* Base classes removed for directive. Everything is based on interfaces and registration now.
* Directives are now registered with `CSSDirective.define` API
* You can also decorate a class to register it as a directive with `@cssDirective`
* `cssPartial` is now optimized so that it doesn't need to add itself as a behavior unless it is composing `ElementStyles`. This means that partials that compose design tokens should perform better.
* `cssPartial` is changed to `css.partial` to reduce import count
Here's an …
=> feat: new CSSDirective design

change/@microsoft-fast-components-531327b4-265f-452f-b41b-3b0f7feaebbd.json, packages/web-components/fast-components/src/tree-item/tree-item.styles.ts
When expanding groups of tree items, there is a very slight issue where the DOM is conditionally loaded but styles are not fully set. This PR adds a very, very quick animation of opacity to manage the initial load of both DOM and styles which appears to solve the issue.
closes #5166
If reviewing and curious about the ever so slight, likely imperceptible value being used for the transition - please validate using the screen capture in the issue and validate against the fix.
=> fix tree view item visual bug on expansion

change/@microsoft-fast-foundation-f39a8fc1-be44-49f9-bc63-8259f3d18932.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/disclosure/README.md, packages/web-components/fast-foundation/src/disclosure/disclosure.spec.ts, packages/web-components/fast-foundation/src/disclosure/disclosure.template.ts, packages/web-components/fast-foundation/src/disclosure/disclosure.ts
The disclosure component hijacked the host element's title attribute. To resolve this, updating the attribute name to `summary`, which is more semantic as well for this scenario.
Part of the Foundation vNext breaking changes we're doing in coordination with FE2.
closes #5568
Added tests to ensure attributes are accurate, which were previously missing.
=> rename title attribute on disclosure to summary

change/@microsoft-fast-components-aea7ecd2-159c-4509-9d43-61915a704efe.json, change/@microsoft-fast-foundation-fdab8a18-b1dd-43a6-bb9c-c30483efb349.json, packages/web-components/fast-components/src/slider/fixtures/base.html, packages/web-components/fast-components/src/slider/slider.styles.ts, packages/web-components/fast-foundation/src/slider/slider.template.ts
Adds support for a visual indicator of the selected value in the slider track area.
Note the "Next Steps" below.
There are two ways the components currently handle RTL. Some look for `dir=rtl` and others use the design token via the directional behavior. This change is currently not working as expected in rtl. The slider values go from right to left, but there is no way to style the track value differently because the style sheet helper expects the design token. Since the two could be out of sync I didn't want to add that here in favor of resolving rtl support consistently.
=> Added support for styling slider value on the track

change/@microsoft-fast-components-2fd58c1a-a158-410b-8690-fe64e28f8440.json, packages/web-components/fast-components/src/disclosure/index.ts
fast-disclosure was not initializing properly because the base class connected callback was not being invoked.
ad hoc
=> fix: fast-disclosure break

change/@microsoft-fast-foundation-d054ea11-441a-4531-8134-f43dc6d07b8b.json, packages/web-components/fast-foundation/src/listbox-option/listbox-option.spec.ts, packages/web-components/fast-foundation/src/listbox-option/listbox-option.ts
Modifies the listbox-option `text` property to trim out excess spaces.
Fixes #4664.
All tests should pass.
=> trim extra spaces from text in listbox-option

change/@microsoft-fast-foundation-3296c3df-4043-46e8-a1f0-9a7f4e33e1c3.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/calendar/calendar.template.ts, packages/web-components/fast-foundation/src/patterns/start-end.ts, sites/fast-website/src/app/components/navigation/navigation.template.ts
This PR removes the wrapping DOM nodes from the start and end slots. This PR keeps the refs on the slots as those are required by certain classes (such as toolbar). Once we have the next version of Foundation template support in, we can look to customize that as-needed if we like, but for now, I think keeping references to those slots without needing to take any action is a solid baseline of support for extensibility.
Part of #5806 
N/A
=> feat: trim unnecessary nodes from start end

packages/web-components/fast-ssr/src/element-renderer/elemenent-renderer.spec.ts, packages/web-components/fast-ssr/src/template-parser/template-parser.ts, packages/web-components/fast-ssr/src/template-renderer/template-renderer.spec.ts
This PR adjusts the way templates are parsed to allow correctly parsing full document templates. `parseFragment()` was parsing templates as document fragments, which don't contain document elements like `html`, `head`, and `body` causing bindings on those elements to not be evaluated. By using full document parsing (`parse()`, we can ensure bindings on those elements get evaluated.
fixes https://github.com/microsoft/fast/issues/5897
=> fix document element bindings in SSR template rendering

package.json, yarn.lock
To fix building on MacOS with M1 processors, `node-gyp` needs to be resolved to `^9.0.0`
There shouldn't be any major breaking changes that affect our use of `node-gyp` as a dev dependency.
Yarn should complete its install and prepare steps on MacOS with Apple silicon chips (M1 and variants).
=> lock node-gyp to ^9.0.0

packages/web-components/fast-ssr/src/element-renderer/elemenent-renderer.spec.ts, packages/web-components/fast-ssr/src/template-parser/op-codes.ts, packages/web-components/fast-ssr/src/template-renderer/template-renderer.spec.ts, packages/web-components/fast-ssr/src/template-renderer/template-renderer.ts
This PR fixes various bugs around emitting attribute strings for bindings in templates. It also refactors the handing of attribute op codes so to organize like operations and reduce redundant code.
=> fix various binding bugs in SSR template renderer

change/@microsoft-fast-foundation-22faaad5-04d8-4a4c-bb54-a2790225d32c.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/combobox/README.md, packages/web-components/fast-foundation/src/combobox/combobox.ts, packages/web-components/fast-foundation/src/select/README.md, packages/web-components/fast-foundation/src/select/select.ts
This PR fixes the issue that select always operated in "forcedPosition" mode and due to this the direction where the dropdown is opening was never recalculated.
A more detailed description of the issue can be found in the linked issue
Fixes #5810 
All the current tests are passing without modification. I don't know if this can be tested programmatically, if so I'm happy to write those tests.
I've manually tested the changes with the `fast-components` storybook and the component seemed to work as it is expected.
=> fix select dropdown positioning

change/@microsoft-fast-components-3d83e709-1871-4c48-b15a-eb80ad445a9c.json, packages/web-components/fast-components/docs/api-report.md, packages/web-components/fast-components/src/accordion-item/accordion-item.styles.ts, packages/web-components/fast-components/src/badge/badge.styles.ts, packages/web-components/fast-components/src/checkbox/checkbox.styles.ts, packages/web-components/fast-components/src/data-grid/data-grid-cell.styles.ts, packages/web-components/fast-components/src/dialog/fixtures/dialog.html, packages/web-components/fast-components/src/disclosure/fixtures/disclosure.html, packages/web-components/fast-components/src/horizontal-scroll/fixtures/horizontal-scroll.html, packages/web-components/fast-components/src/listbox-option/listbox-option.styles.ts, packages/web-components/fast-components/src/listbox/listbox.styles.ts, packages/web-components/fast-components/src/menu-item/menu-item.styles.ts, packages/web-components/fast-components/src/menu/index.ts, packages/web-components/fast-components/src/menu/menu.styles.ts, packages/web-components/fast-components/src/picker/index.ts, packages/web-components/fast-components/src/picker/picker-list-item.styles.ts, packages/web-components/fast-components/src/picker/picker-menu-option.styles.ts, packages/web-components/fast-components/src/picker/picker-menu.styles.ts, packages/web-components/fast-components/src/picker/picker.styles.ts, packages/web-components/fast-components/src/radio/radio.styles.ts, packages/web-components/fast-components/src/select/index.ts, packages/web-components/fast-components/src/select/select.styles.ts, packages/web-components/fast-components/src/switch/switch.styles.ts, packages/web-components/fast-components/src/tree-item/tree-item.styles.ts
Quick run through some visual issues and one functional issue.
`Disclosure` wasn't loading because it was missing a `super` call.
=> Cleanup some visual state bugs

change/@microsoft-fast-element-230be6d2-2fd7-4d50-938b-fd03e18f362f.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/interfaces.ts, packages/web-components/fast-element/src/templating/repeat.ts, packages/web-components/fast-element/src/templating/template.ts
This PR adjusts the types of the `repeat` helper function so that type inference isn't lost on the parent type in certain situations, and so that the `html` helper can still be used with the `repeat` when no child-context-specific functionality is needed.
* Fixes #5974 
A basic PR that just removes some of the generics. Turns out that TS isn't powerful enough to infer some things, given the extra type info. It actually breaks things. Removing it enables it to function better.
All tests continue to pass. Some manual testing of type inference was done as well.
Some more polish PRs coming after this one but this should settle the template and repeat types.
=> fix: enable safer type inference on the repeat helper

change/@microsoft-fast-element-b447782c-22f3-4f6a-96f5-b7afc160af0b.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/observation/array-observer.spec.ts, packages/web-components/fast-element/src/observation/array-observer.ts, packages/web-components/fast-element/src/observation/observable.ts
This PR adds a new helper to `fast-element` that enables observing the length of an array in a binding expression.
* Closes #5962 
A new `length` function will return the length of the provided array. Before doing so, it will connect an observer to the array (if one is not present), and then subscribe to that for `length` checks (if it isn't already setup). Then, when the array changes, if the new length is different from the old length, a notification will be raised. The helper function also serves to track the access of the `length` itself.
New tests were added to test the helper function in bindings.
No further steps relates to this functionality at this time.
=> feat: enable array length observation

change/@microsoft-fast-element-812c3a96-4de5-4429-907a-86c354742b82.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/templating/binding.spec.ts, packages/web-components/fast-element/src/templating/binding.ts, packages/web-components/fast-element/src/templating/children.ts, packages/web-components/fast-element/src/templating/node-observation.ts, packages/web-components/fast-element/src/templating/slotted.ts
This PR adds a new `twoWay` binding mode/config for use with `fast-element` templates. The new mode is completely tree-shakeable, just like the new `signal` mode.
Here's an example of binding the `value` of an `input` bidirectionally, such that the element's `value` updates on changes to the model's `myProperty` property and the `myProperty` value updates when the element's `change` event fires:
```ts
const template = html`
<input type=text :value=${bind(x => x.myProperty, twoWay)} />
`;
```
If we want to update the model on `input`, we can do this:
```ts
const template = html`
<input type=text :value=${bind(x => x.myProperty, twoWay({ changeEvent: 'input' }))} />
`;
```
If we need to convert the value provided by the element before assigning it back to our model, we can provide a custom …
=> feat: add two-way binding

change/@microsoft-fast-element-5a826d6a-4945-4423-873e-27ef3dba737b.json, packages/web-components/fast-element/package.json, packages/web-components/fast-element/src/interfaces.ts, packages/web-components/fast-element/tsconfig.json
This PR removes the dependency on the `@types/ie11` package which was added to resolve a type issue for `TreeWalker` which is no longer used, making this dependency unnecessary with its removal.
n/a
=> chore: remove dependency on ie11 types

change/@microsoft-fast-foundation-119dceba-853f-4809-8a2b-169352ebe125.json, packages/web-components/fast-foundation/src/search/README.md, packages/web-components/fast-foundation/src/search/search.template.ts, packages/web-components/fast-foundation/src/search/search.ts
While adding tsdoc comments for slots I found an issue with the slot names for the clear button. This PR fixes the slot names to be `clear-button` instead of `close-button`.
=> fix incorrect and non-semantic slot names for search

change/@microsoft-fast-foundation-d461d7cb-5136-4816-94e9-04b46fa8a11e.json, packages/web-components/fast-foundation/src/accordion/accordion.template.ts
This PR removes the deprecated slot name of item for accordion default items.
closes #5515
=> remove deprecated item slot on accordion

packages/web-components/fast-ssr/ACKNOWLEDGEMENTS.md, packages/web-components/fast-ssr/docs/api-report.md, packages/web-components/fast-ssr/package.json, packages/web-components/fast-ssr/src/dom-shim.spec.ts, packages/web-components/fast-ssr/src/dom-shim.ts, packages/web-components/fast-ssr/src/element-renderer/elemenent-renderer.spec.ts, packages/web-components/fast-ssr/src/element-renderer/element-renderer.ts, packages/web-components/fast-ssr/src/element-renderer/fast-element-renderer.ts, packages/web-components/fast-ssr/src/escape-html.ts, packages/web-components/fast-ssr/src/exports.ts, packages/web-components/fast-ssr/src/install-dom-shim.ts, packages/web-components/fast-ssr/src/render-info.ts, packages/web-components/fast-ssr/src/styles/style-renderer.spec.ts, packages/web-components/fast-ssr/src/template-parser/template-parser.spec.ts, packages/web-components/fast-ssr/src/template-parser/template-parser.ts, packages/web-components/fast-ssr/src/template-renderer/directives.ts, packages/web-components/fast-ssr/src/template-renderer/template-renderer.spec.ts, packages/web-components/fast-ssr/src/template-renderer/template-renderer.ts, yarn.lock
This PR removes the `@lit-labs/ssr` dependency from `@microsoft/fast-ssr` and migrates the necessary assets into source-code. This will help stabalize the package and allow us to iterate as necessary to advance the package. Hopfully as the community protocols mature, this code can be migrated to a centralized source and leveraged from there.  I've called out modules that were copied from lit and included them in an `ACKNOWLEDGEMENTS.md` file with license information for the copied code.
closes #5993
=> Implement ElementRenderer and DOM shim directly into SSR package, remove lit-labs/ssr dependency

change/@microsoft-fast-element-4d2683a2-b3a2-4c92-b401-abede39da9b2.json, packages/web-components/fast-element/src/observation/array-observer.ts, packages/web-components/fast-element/src/observation/notifier.spec.ts, packages/web-components/fast-element/src/observation/notifier.ts
This PR fixes a bug in array observation that happens when a subscription is added to an already observed array that has splices queued for delivery but not yet delivered. Without this fix, the new subscriber would receive change notification for changes that happened before it subscribed.
* Fixes #6003 for FAST Element 1.x
The fix involved flushing the changes prior to any subscription being added. However, to enable this, it needed to be possible to override the `subscribe` method of the base class. This was not possible due to some method swizzling in `SubscriberSet`. Therefore, the implementation of `SubscriberSet` was changed to not swizzle and enable method overriding, which is probably a cleaner approach anyway, since the previous implementation could result in surprising behavior …
=> fix(fast-element): do not notify splices for changes pre-subscription

change/@microsoft-fast-element-65662448-c859-4bfd-b06d-a52379348361.json, packages/web-components/fast-element/src/observation/arrays.spec.ts, packages/web-components/fast-element/src/observation/arrays.ts, packages/web-components/fast-element/src/observation/notifier.ts
This PR fixes a bug in array observation that happens when a subscription is added to an already observed array that has splices queued for delivery but not yet delivered. Without this fix, the new subscriber would receive change notification for changes that happened before it subscribed.
* Fixes #6003 for FAST Element 1.x
The fix involved flushing the changes prior to any subscription being added. However, to enable this, it needed to be possible to override the `subscribe` method of the base class. This was not possible due to some method swizzling in `SubscriberSet`. Therefore, the implementation of `SubscriberSet` was changed to not swizzle and enable method overriding, which is probably a cleaner approach anyway, since the previous implementation could result in surprising behavior …
=> fix(fast-element): do not notify splices for changes pre-subscription (v2)

change/@microsoft-fast-foundation-70646681-8dcc-4511-92e1-0062ddbdda8f.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/tabs/README.md, packages/web-components/fast-foundation/src/tabs/tabs.spec.ts, packages/web-components/fast-foundation/src/tabs/tabs.template.ts, packages/web-components/fast-foundation/src/tabs/tabs.ts
This PR changes the boolean attribute of `activeindicator` to `hide-active-indicator` to support a default value of false.
related to #5320
=> feat: update tabs bool attr defaulting to true

change/@microsoft-fast-foundation-20d429c9-afc3-4daf-b3db-0ea73fb37daa.json, packages/web-components/fast-foundation/src/switch/switch.spec.ts, packages/web-components/fast-foundation/src/switch/switch.template.ts
This is to revert the change of adding `aria-required` to switches. Elements with `role="switch"` do not support validation and throw accessibility errors from audit tools when it is present. 
https://github.com/microsoft/fast/issues/6013
=> Revert switch a11y changes

change/@microsoft-fast-element-5804fe41-9a70-4cc2-ad00-bff57d7fed78.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/templating/template.ts
This PR corrects the `type` field of `SyntheticViewTemplate` to be properly generic, fixing some typing issues that can occur when using various directives in combination.
* Closes #6065 
I added a few missing doc comments but the real fix was changing the type of the `type` field of `SyntheticViewTemplate`.
All existing tests continue to pass. This was just a type definition fix.
n/a
=> fix: make SyntheticViewTemplate type a string so it is generally usable

change/@microsoft-fast-element-c5184ad5-9a98-4cd6-8b58-5d717e43fc6b.json, change/@microsoft-fast-foundation-a5bf55a6-6f13-4364-a9cc-8687b7feae18.json, packages/web-components/fast-element/package.json, packages/web-components/fast-element/src/context.spec.ts, packages/web-components/fast-element/src/context.ts, packages/web-components/fast-element/src/metadata.spec.ts, packages/web-components/fast-element/src/metadata.ts, packages/web-components/fast-element/tsconfig.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/design-system/design-system.spec.ts, packages/web-components/fast-foundation/src/design-system/design-system.ts, packages/web-components/fast-foundation/src/di/di.exception.spec.ts, packages/web-components/fast-foundation/src/di/di.get.spec.ts, packages/web-components/fast-foundation/src/di/di.getAll.spec.ts, packages/web-components/fast-foundation/src/di/di.integration.spec.ts, packages/web-components/fast-foundation/src/di/di.spec.ts, packages/web-components/fast-foundation/src/di/di.ts
This PR adds support for the W3C Web Components Community Protocol for Context to FAST 🎉 
The core `Context` features are added to `@microsoft/fast-element` as a special package export named `context`. Basic `Metadata` has also been added in a similar way. The `fast-foundation` DI was then fixed up to both use `Context` events to locate containers as well as be able to plug itself in to handle `Context` requests. This means that someone building components with just `fast-element` can use the `Context` APIs to declare dependencies with decorators on their components, and then the consumer of those components could choose to satisfy those dependencies either by using `Context` APIs or plugging in `DI`.
```ts
export interface AuthService {
login(username: string, password: string): …
```
=> feat: implement W3C WC community context protocol and integrate with DI

change/@microsoft-fast-foundation-95a55f8c-bf15-4eba-b928-5da6e11497f8.json, packages/web-components/fast-foundation/src/radio-group/radio-group.spec.ts, packages/web-components/fast-foundation/src/radio-group/radio-group.ts
Updates the FormGroup `valueChanged` callback to compare the new value with the Radio's value property, rather than the value attribute. This brings it inline with how the comparison is done when the component is first connected.
#6050
=>  fix: RadioGroup does not check correct Radio when Radio value set through property

packages/tooling/fast-figma-plugin-msft/src/core/controller.ts, packages/tooling/fast-figma-plugin-msft/src/core/node.ts, packages/tooling/fast-figma-plugin-msft/src/figma/node.ts, packages/tooling/fast-figma-plugin-msft/src/figma/utility.ts
Some designs call for custom treatment in dark mode. Ideally everything could be a system, but the primary case this comes up is illustration.
This change adds support for Figma components with a "Dark mode" variant property, which will be set according to the context luminosity.
=> Figma plugin: Added support for custom "Dark mode" components

change/@microsoft-adaptive-ui-c2b6a755-6dc3-4265-8bfd-8431ff8cf8d0.json, packages/utilities/adaptive-ui/src/design-tokens/type.ts, packages/utilities/adaptive-ui/src/type/type-ramp.ts
This change fixes a reference where the `design-tokens/type.ts` file imported an interface from `type/type-ramp.ts` while the `type/type-ramp.ts` is also importing various type ramp exports from `design-tokens/type.ts`. Since this interface is only used in `design-tokens/type.ts` it has been moved there.
Another change has been made to the eslint config to catch this issue in the future, see #6138
=> Fixed a cyclical reference

change/@microsoft-adaptive-ui-2e49e17b-a6eb-4ff8-9428-41ecda134255.json, packages/utilities/adaptive-ui/docs/api-report.md, packages/utilities/adaptive-ui/src/design-tokens/elevation.ts, packages/utilities/adaptive-ui/src/design-tokens/index.ts, packages/utilities/adaptive-ui/src/elevation/index.ts, packages/utilities/adaptive-ui/src/elevation/recipe.ts, packages/utilities/adaptive-ui/src/index.ts
Bringing over support for elevation tokens and a default shadow implementation.
All tokens have been renamed to remove "Shadow" as there are other elevation treatments that may not be a box-shadow that can benefit from the same semantic recipes.
=> adaptive-ui: Added tokens for elevation and shadow treatment

change/@microsoft-fast-element-64ffcc23-bbc9-409d-99a7-00a93af07b85.json, packages/web-components/fast-element/src/templating/render.spec.ts, packages/web-components/fast-element/src/templating/render.ts
`createElementTemplate` currently cannot work if the attributes argument is null or undefined. This PR adds the ability for the function to work without attributes passed to it as well as related tests.
Stackblitz with `createElementTemplate` with the fix running on v1.10.2 of `fast-element`
https://stackblitz.com/edit/typescript-n2mura?file=index.ts
I was having trouble with getting binding sources created using a class and the `@observable` decorator on class properties to work properly in the stackblitz example, however I added a test specifically for this scenario in the spec file that does work, so I think it is a stackblitz specific issue.
=> fix: Enable `createElementTemplate` to work without attributes defined

change/@microsoft-fast-foundation-c8e72081-257f-474b-803b-0ae63fc25a83.json, packages/web-components/fast-foundation/src/accordion/accordion.spec.ts, packages/web-components/fast-foundation/src/accordion/accordion.ts, packages/web-components/fast-foundation/src/accordion/stories/accordion.stories.ts
Accordion was listening for `change` events to determine when to open/close items, but was not differentiating between change events generated by the accordion items and those of the children of these items.  This change adds checks to ensure that accordion ignores `change` events from other elements and does not react to events that have been defaultPrevented, 
closes https://github.com/microsoft/fast/issues/6144
We should add some functional accordion tests when we move to playright.  The current set is limited.  Added an issue to track.
https://github.com/microsoft/fast/issues/6157
=> fix: accordion item should not collapse on unrelated change events

change/@microsoft-fast-element-64ffcc23-bbc9-409d-99a7-00a93af07b85.json, change/@microsoft-fast-element-6f2b6b24-e285-4faa-b0a8-5acdedaede8d.json, change/@microsoft-fast-element-7e339741-a763-4313-b23e-4b5644e6ebe2.json, change/@microsoft-fast-foundation-c0150ae1-d206-45b8-8c0e-f0873bc3602e.json, change/@microsoft-fast-foundation-c8e72081-257f-474b-803b-0ae63fc25a83.json, change/@microsoft-fast-ssr-d5fb6092-d576-4983-a2f0-8a7cfb88138a.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/templating/render.spec.ts, packages/web-components/fast-element/src/templating/render.ts, packages/web-components/fast-element/src/templating/repeat.spec.ts, packages/web-components/fast-element/src/templating/repeat.ts, packages/web-components/fast-element/src/templating/when.spec.ts, packages/web-components/fast-element/src/templating/when.ts, packages/web-components/fast-ssr/src/template-renderer/directives.ts
This PR enables `render`, `repeat`, and `when` template helper functions to receive static data in addition to the already supported bindings.
* Closes #6170 
The basic approach has been to simply check the input to the template function and if it's not a function (binding), then to wrap the static value in a binding and pass that along to the directive.
I made a minor breaking change to `repeat` by renaming its `itemsBinding` property to `dataBinding` so that we could have consistent naming across directives. I updated SSR to use this renamed property. I doubt anyone else is directly accessing that in the community.
I have added tests for the new inputs and also added additional tests to `repeat` that were missing for already existing scenarios.
Eventually, I'd like to look into a way to …
=> feat: enable render, repeat, and when template helpers to handle static data

build/get-package-json.js, package.json, sites/fast-website/package.json, sites/website/src/generate-docs.js, yarn.lock
* Fixes the generate-docs script to point to the `@microsoft/fast-components` dependency for `@microsoft/fast-website`.
* Locks `@microsoft/fast-components` to `2.30.2` in `@microsoft/fast-website`.
Merges into #6192.
=> Fix homepage prebuild step (users/eisenbergeffect/fix-homepage)

change/@microsoft-fast-animation-32d3c5b6-562a-4962-8297-e95d92c3f294.json, change/@microsoft-fast-element-9ae2db31-9f6d-41c5-a0fa-e056d7b7c029.json, change/@microsoft-fast-router-19cffffd-de42-4d49-820a-93a1d91d1737.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/components/fast-definitions.spec.ts, packages/web-components/fast-element/src/components/fast-definitions.ts, packages/web-components/fast-element/src/interfaces.ts, packages/web-components/fast-element/src/styles/element-styles.ts, packages/web-components/fast-router/docs/api-report.md, packages/web-components/fast-router/src/view.ts
This PR fixes a bug in `FASTElementDefinition` where the `isDefined` property reported true when the element had not yet been defined with the platform.
* Closes #6199 
While reading through the `FASTElementDefinition` code I realized there was some style normalization code in there that really should be part of `ElementStyles` so I made the minor refactoring. I discovered that the router had previously duplicated this code, so I removed the duplication and switched the router to using the new API.
I have added a test related to the bug. All tests pass.
None at this time.
=> fix: FASTElementDefinition#isDefined should be true only after define

change/@microsoft-fast-element-d157c8b1-cdea-49a3-bb5a-48fcd7652f95.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/debug.spec.ts, packages/web-components/fast-element/src/debug.ts, packages/web-components/fast-element/src/interfaces.ts, packages/web-components/fast-element/src/platform.ts, packages/web-components/fast-element/src/templating/compiler.spec.ts, packages/web-components/fast-element/src/templating/compiler.ts, packages/web-components/fast-element/src/templating/view.spec.ts
If a developer puts attributes on the `template` element at the root of a template, and then tries to create a view without a "host", errors will occur. This PR prevents the errors and outputs warnings to the console instead.
* Closes #6156
The technique used here is to create a `Proxy` that emits warnings on get/set to the underlying element. The proxy is used as the host whenever one isn't provided.
To make the warnings more meaningful, I implemented the debug warning implementation's ability to interpolate named parameters into messages. 
Tests were added for the view host binding scenarios as well as the new debug logging capability. While I was working on this, I realized we didn't have any tests on template host binding, so I added those as well.
We could look at also fixing this on …
=> fix: warn when host bindings are accidentally applied on non CE views

change/@microsoft-fast-ssr-9a72ce54-68fa-4fde-8d84-59c8cfd9d157.json, packages/web-components/fast-ssr/src/template-renderer/directives.ts, packages/web-components/fast-ssr/src/template-renderer/template-renderer.spec.ts
This PR adds an SSR implementation for the `render` directive.
* Closes #6200 
This PR adds code to the SSR package to support the `render` directive. The approach is based on the implementation of the `repeat` directive, which is very similar.
New tests were added based on the pattern that the `repeat` tests used.
n/a
=> feat: enable the render directive to work in SSR

change/@microsoft-fast-element-6932c197-b0cf-43c8-8426-63c0dd29310f.json, packages/web-components/fast-element/src/context.ts, packages/web-components/fast-element/src/debug.ts, packages/web-components/fast-element/src/di/di.ts, packages/web-components/fast-element/src/interfaces.ts
This PR extracts all error messages from the `Context` and `DI` features, updating this code to use the `FAST.error()` helper and the `debug` module.
* Closes #6060 
This PR started with the intent of fixing #6060 by properly handling the key conversion to string. However, during that process it was discovered that context and DI were not yet using the new error messaging system. So, I took this opportunity to update everything to use that system, which internally also handles the string conversion issue.
All existing tests pass.
No additional related work known at this time.
=> feat: extract all error messages from context and DI

change/@microsoft-fast-foundation-33f8e31d-364c-4ef8-985a-3b16ac9716e6.json, packages/web-components/fast-foundation/package.json
Adds an export path for the custom elements manifest, allowing it to be imported and consumed by tooling, and applications.
closes #6217
=> feat: add export for custom-elements manifest

change/@microsoft-adaptive-ui-86f29544-ac82-46b2-9c74-1253dd8a514d.json, packages/utilities/adaptive-ui/docs/api-report.md, packages/utilities/adaptive-ui/src/color/recipes/index.ts, packages/utilities/adaptive-ui/src/design-tokens/color.ts, packages/utilities/adaptive-ui/src/type/type-ramp.ts
Fixed missing export for `black-or-white-by-contrast-set`.
Fixed incorrect default value `0` for `accent-foreground-min-contrast` and `neutral-fill-strong-min-contrast`.
=> Adaptive UI: fixed missing export and incorrect min-contrast token values

change/@microsoft-fast-element-2fee7ceb-82a3-45ee-8d5f-aa2c622619d1.json, packages/web-components/fast-element/src/templating/view.ts
Following up on the discussions related to Repeat directive updateViews(), 
on line 216 `view.insertBefore(location)`, there were discussions around how there could be optimization opportunity to not run insertBefore() if view already exists. 
After investigating, there were 2 solutions, this being one of them. The other being https://github.com/microsoft/fast/tree/users/wendy/insert-before-repeat.
Before making the final decision on which one to use, there were some bug fixes and other optimization work in the Repeat directive that have been added to the master branch:
- https://github.com/microsoft/fast/pull/6072
- https://github.com/microsoft/fast/pull/6153
- https://github.com/microsoft/fast/pull/6162
Included in these fixes, more tests have been added and as a result, solution from …
=> fix: make insertBefore no-op in View if view already exists

change/@microsoft-fast-element-a27fdcc8-d888-4229-ac44-2143ed5695c5.json, change/@microsoft-fast-foundation-1cc57b28-a6e7-4aaf-a8c6-85db045a5197.json, change/@microsoft-fast-ssr-1bf4c529-ce6e-4701-9a14-b8dba91f593a.json, packages/web-components/fast-element/package.json, packages/web-components/fast-foundation/package.json, packages/web-components/fast-ssr/package.json
Tooling that reads from the package.json is unable to when the package is using subpath exports unless the package.json is also exported via subpath
#6255 
#6217
Node scripts using `require.resolve` to read the `package.json` as well as ESM imports throw errors unless the file is exported.
=> feat: Add subpath export for `package.json` to relevant packages

change/@microsoft-fast-foundation-14d4f603-9786-4d4d-8db4-af050205e43e.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/number-field/number-field.ts, packages/web-components/fast-foundation/src/text-area/text-area.ts, packages/web-components/fast-foundation/src/text-field/text-field.ts
In #5900 the select() method was added to the text field, number field, and text area, but it was added as a protected member. It should be public so that it can be called by clients.
See discussion at end of #5626 
N/A
N/A
=> fix: change select() method to public on text field, number field, and text area

change/@microsoft-fast-foundation-5dacab8f-7ec9-4469-9853-e99b87b243c4.json, packages/web-components/fast-foundation/.storybook/preview-head.html, packages/web-components/fast-foundation/src/anchored-region/anchored-region.spec.md, packages/web-components/fast-foundation/src/anchored-region/anchored-region.ts, packages/web-components/fast-foundation/src/anchored-region/stories/anchored-region.stories.ts
Anchored region defaulted to checking the light dom to find the anchor element by id.  With this change it will check the local shadow dom for a matching id before checking the light dom.  Matches a behavior we already have in tooltip and should make it easier to use.
=> feat: anchored-region checks local shadow dom for anchor id

change/@microsoft-fast-web-utilities-0a5de467-491d-4b86-9221-22f97f7d85de.json, packages/utilities/fast-web-utilities/src/dom.spec.ts, packages/utilities/fast-web-utilities/src/dom.ts
Adds `meta[name="csp-nonce"]` to the querySelector for the `getNonce` function so it will look for either `property="csp-nonce"` or `name="csp-nonce"`
Related to #5444 
Should be no breaking changes
=> Add meta name="csp-nonce" to getNonce function

change/@microsoft-fast-element-3f983e5a-b3a2-4c16-a9f4-7f2ef2734574.json, packages/web-components/fast-element/src/templating/repeat.spec.ts, packages/web-components/fast-element/src/templating/repeat.ts
There are 2 options you can set with the Repeat directive: positioning and recycle. When you don't set either options, the default value is being set as expected {positioning: false, recycle: true}. When you set only one of them (like in the repro) {positioning: true}, recycle does not get set, that is probably why you were seeing undefined. The fix needs to give options default values when user only sets one of the properties.
=> fix: recycle feature in Repeat should be set to true by default

change/@microsoft-fast-ssr-93d4338f-50c8-4672-bd23-9ad9939af65a.json, examples/ssr/server.js, packages/web-components/fast-ssr/docs/api-report.md, packages/web-components/fast-ssr/src/declarative-shadow-dom-polyfill.ts, packages/web-components/fast-ssr/src/exports.ts
This PR embeds the necessary CSS and JavaScript polyfill code to ensure that Declarative Shadow DOM (DSD) is properly handled on browsers that don't yet implement the standard.
The SSR example has been updated to emit the polyfill code into the page.
* Closes #6288
The polyfill code is generally available on the web. This PR simply embeds it in our SSR package for convenience.
See the SSR example `server.js` file for usage.
No tests added for this as this just provides a convenience API over a well-known polyfill.
An alternative polyfill method that supports streaming could be added. For this, we would embed a small global script in the page head and then emit a script tag immediately following each DSD instance, which called that global function, passing in the `currentScript`. This has …
=> feat: implement DSD polyfill as an optional plugin for FAST SSR

change/@microsoft-fast-foundation-eb26a2f6-c059-4ee2-bd81-3886503e454b.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/button/README.md, packages/web-components/fast-foundation/src/button/button.ts, packages/web-components/fast-foundation/src/combobox/README.md, packages/web-components/fast-foundation/src/combobox/combobox.ts, packages/web-components/fast-foundation/src/form-associated/form-associated.ts, packages/web-components/fast-foundation/src/number-field/README.md, packages/web-components/fast-foundation/src/number-field/number-field.ts, packages/web-components/fast-foundation/src/search/README.md, packages/web-components/fast-foundation/src/search/search.ts, packages/web-components/fast-foundation/src/text-area/README.md, packages/web-components/fast-foundation/src/text-area/text-area.ts, packages/web-components/fast-foundation/src/text-field/README.md, packages/web-components/fast-foundation/src/text-field/text-field.ts
This PR adds an optional anchor argument to `FormAssociated.validate()`, which gets provided to `ElementInternals.setValidity()`. This anchor is the element to which the browser should focus within a shadowRoot if the element delegates focus. 
All components that implement `FormAssociated` *and* `delegatesFocus` have been updated to invoke validate() with the shadowed element that the element delegates focus to.
fixes #5678
The linked issue offers a brief discussion around potentially using `@open-wc/form-control` package to address this issue. I've opened a separate discussion for that conversation in #6300. For now, I'd like to fix the bug and we can take migration as a separate consideration and task.
=> Fix constraint validation in components

.vscode/extensions.json, change/fast-tagged-templates-e0b4449e-cadc-4e4a-90a5-18b59b58efec.json, packages/tooling/fast-vscode-syntax-highlighting/README.md, packages/tooling/fast-vscode-syntax-highlighting/package.json
* Adds the `ms-fast` publisher to the extension manifest for the `fast-tagged-templates` extension.
* Adds the `ms-fast.fast-tagged-templates` extension to the VS Code recommended extensions configuration for this repository.
* Updates the README with a link to the extension on the Visual Studio Code Marketplace website.
The tagged template extension is published here: https://marketplace.visualstudio.com/items?itemName=ms-fast.fast-tagged-templates
The process for publishing and updating the marketplace is currently manual, though we're looking into how we might be able to make the updating process more hands-off/automated.
=> Add publisher to syntax highlighting extension

change/fast-tagged-templates-e0b4449e-cadc-4e4a-90a5-18b59b58efec.json, packages/tooling/fast-vscode-syntax-highlighting/CHANGELOG.json, packages/tooling/fast-vscode-syntax-highlighting/CHANGELOG.md, packages/tooling/fast-vscode-syntax-highlighting/package.json
Bumps the `fast-tagged-template package` to `0.2.0`.
Since this package isn't published to NPM, it makes more sense to manually bump the version instead of running it through the CI pipeline.
=> bump fast-tagged-templates package to 0.2.0

change/@microsoft-fast-ssr-1ea14677-fc86-46b5-b40c-4fd7970f1a60.json, packages/web-components/fast-ssr/docs/api-report.md, packages/web-components/fast-ssr/src/element-renderer/elemenent-renderer.spec.ts, packages/web-components/fast-ssr/src/element-renderer/element-renderer.ts, packages/web-components/fast-ssr/src/element-renderer/fast-element-renderer.ts, packages/web-components/fast-ssr/src/element-renderer/interfaces.ts, packages/web-components/fast-ssr/src/exports.ts, packages/web-components/fast-ssr/src/render-info.ts, packages/web-components/fast-ssr/src/template-renderer/directives.ts, packages/web-components/fast-ssr/src/template-renderer/template-renderer.spec.ts, packages/web-components/fast-ssr/src/template-renderer/template-renderer.ts
This PR makes some architectural changes to `@microsoft/fast-ssr` to support asynchronous rendering. It does *not* implement any async rendering business logic, but refactors the package and types to support `Promise<string>` return types.
The high level overview of the changes are:
1. Adds a `Configuration` argument to the default export which constructs the SSR renderer. This configuration can take a `renderMode` of `"sync | "async"`, defaulting to `"sync"`, eg `fastSSR({renderMode: "async"});`
2. Refactors the `ElementRenderer` abstract base class to a set of two interfaces, `ElementRenderer` and `AsyncElementRenderer`. The package is refactored to code against the `ElementRenderer` interfaces instead of an abstract class so that it doesn't require a concrete implementation. 
3. …
=> feat: enable async rendering type support

change/@microsoft-fast-element-f2bcaaf6-9732-4ef2-8fb0-985c27afbd2f.json, change/@microsoft-fast-ssr-4675c274-ed0b-4b95-abf3-d8f86163cabd.json, packages/web-components/fast-element/package.json, packages/web-components/fast-element/src/pending-task.ts, packages/web-components/fast-ssr/src/element-renderer/elemenent-renderer.spec.ts, packages/web-components/fast-ssr/src/element-renderer/fast-element-renderer.ts, packages/web-components/fast-ssr/src/test-utilities/consolidate.ts
This PR adds async rendering support to fast-ssr via the [`PendingTask` protocol](https://github.com/webcomponents-cg/community-protocols/blob/main/proposals/pending-task.md). Elements would emit a `PendingTask` event, which contains a promise indicating whether the task is complete. The AsyncElementRenderer then listens for these events, storing them as they emit. During attribute rendering, the AsyncElementRenderer awaits any pending tasks that have been caught (this works recursively, if tasks kick off other tasks). After all tasks have resolved, the renderer continues yielding attributes from the element.
The other approach we've considered is using a special Behavior that contains a Promise. AsyncElementRenderer would inspect an element's behaviors and if these special async …
=> feat: add async rendering support via PendingTask

change/@microsoft-adaptive-ui-2c911859-fa07-4cfb-898e-9cea4af0ac67.json, packages/utilities/adaptive-ui/docs/api-report.md, packages/utilities/adaptive-ui/src/color/recipes/contrast-swatch.ts, packages/utilities/adaptive-ui/src/color/swatch.ts, packages/utilities/adaptive-ui/src/color/utilities/index.ts, packages/utilities/adaptive-ui/src/color/utilities/opacity.ts, packages/utilities/adaptive-ui/src/design-tokens/color.ts
Adds support for rendering neutral recipe colors as an overlay. This supports UI over the Windows 11 mica effect or contrast-safe scenarios over images or gradients.
The feature is applied to the neutral palette only for now, as it produces either a white or black semitransparent overlay instead of a fixed color. This works perfect with a non-tinted grey neutral palette, and it works well for low-saturated colors which might be more common for a tinted-neutral setup. It may not produce the expected colors for an accent color, which is typically more saturated and intended to stand out. Interested in thoughts for future updates in this regard though.
This needs to be applied to components to be tested. Working on getting this into the CLI now.
See above.
=> adaptive-ui: Initial support for opacity in neutral recipes

change/@microsoft-fast-foundation-656e7737-e8d8-4b21-a86d-47dbe895535b.json, packages/web-components/fast-foundation/src/menu-item/menu-item.spec.ts, packages/web-components/fast-foundation/src/menu-item/menu-item.template.ts
this might seem pretentious to simply delete a line but, removing it makes no difference.
the `role` @attr decorated property member (by its default behavior) already reflects to the DOM host, which makes the removed line redundant in template.
https://github.com/microsoft/fast/blob/1d230aa72f4802bb309c4679bf5b2fa27d385e7b/packages/web-components/fast-foundation/src/menu-item/menu-item.ts#L115-L116
is there any other reason why this should stay?
=> refactor(fast-foundation): remove redundant role

change/@microsoft-fast-element-529c9ad7-bad3-4569-8a2d-8561d4df136c.json, change/@microsoft-fast-foundation-326f3cf4-1c81-4d0e-bba4-dcd8520e9cc8.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/components/attributes.spec.ts, packages/web-components/fast-element/src/components/attributes.ts, packages/web-components/fast-element/src/observation/observable.ts, packages/web-components/fast-element/src/platform.ts, packages/web-components/fast-foundation/src/utilities/apply-mixins.ts
This PR addresses an apparently long-standing bug in `fast-element` related to attributes inherited through a class hierarchy. This is the v1 backport of the fix originally [submitted here](https://github.com/microsoft/fast/pull/6378)
* Fixes #6368 
I refactored the attribute code so that is uses the same mechanism as the observable code. I'm not sure why this wasn't done long ago to be honest. It must have just got missed in the very early prototypes.
I also fixed up the `mixin` helper in `fast-foundation` to use the new API.
A failing test was initially added to ensure the changes would fix the bug. All existing tests continue to pass.
n/a
=> fix(fast-element): attributes properly located in inheritance hierarchy (v1)

change/@microsoft-fast-foundation-f2de503c-f983-4a1e-a523-49b76eac024d.json, packages/web-components/fast-foundation/src/avatar/stories/avatar.stories.ts, packages/web-components/fast-foundation/src/horizontal-scroll/stories/horizontal-scroll.stories.ts, packages/web-components/fast-foundation/src/menu-item/stories/menu-item.stories.ts, packages/web-components/fast-foundation/src/select/stories/select.register.ts, packages/web-components/fast-foundation/src/skeleton/stories/skeleton.stories.ts, packages/web-components/fast-foundation/src/slider/stories/slider.stories.ts
Fixes a few storybook-related bugs:
* Use `Updates.enqueue` when calling `renderedStory.$fastController.addStyles` in story decorators
* Fix `isConnected` call in select's `maxHeightChanged` (this is only present in the register module)
* Modify the skeleton card example story parameters to from include no args instead of entirely disabling the controls
Errors were emitted only in Safari when calling `this.$fastController.addStyles` in decorators.
These changes should not affect the playwright tests.
=> fix storybook story bugs

change/@microsoft-fast-element-320549b7-b0d8-43cd-be5a-87342681f7c2.json, change/@microsoft-fast-element-f8e8f658-ebbb-4608-92f7-e26763d9aa4d.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/components/fast-definitions.ts
This PR makes a few changes to `fast-element` that enable [Scoped Custom Elements](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Scoped-Custom-Element-Registries.md). Note that this feature is not yet implemented in any browser. I'm doing this so that polyfills for the feature can be used with FAST and so that we are ready to go as soon as Chromium has a prototype available behind a flag.
* Closes #6327 
The changes required to enable Scoped Custom Elements are pretty minor. There are two parts:
1. Enable a registry to be passed to the shadow dom that contains only the elements that should be visible in the shadow dom.
2. Enable a default registry to be associated with an element definition. This allows the developer to specify which registry to define the component itself …
=> feat: prepare fast-element for scoped custom element registries

change/@microsoft-fast-element-c12038ed-87b3-4493-86dc-c51a5029f7db.json, packages/web-components/fast-element/src/platform.spec.ts, packages/web-components/fast-element/src/platform.ts
We discovered an issue with templates that causes an exception to be thrown when a `null` or `undefined` value is provided literally in the template. This happens because the `html` helper is attempting to determine if the value is a directive. The directive registry then attempts to get the constructor of `null`/`undefined` in order to do the lookup, which fails.
Discovered today and fast tracking the fix.
This fix was simple. We just needed to detect the null/undefined scenario.
I added a couple of tests to verify the bug and the fix.
It would be nice to have more tests for the type registration helper in the future. Fortunately, a lot of that is tested transitively through other scenarios at the moment.
=> fix: do not crash when null/undefined is provided literally in templates

change/@microsoft-fast-element-196bc410-6c26-4cfa-8ba7-8b51a66c2772.json, packages/web-components/fast-element/src/templating/view.spec.ts, packages/web-components/fast-element/src/templating/view.ts
When rebinding a view (as is often the case with repeat), the view's state was incorrect while processing the unbindables and the rebound behaviors.
No issues. The problem was recently discovered and needed a rapid fix.
The `source` property was being set too soon when rebinding, causing behaviors that needed to unbind themselves to get the new source rather than the source they had been bound to. Then, when rebinding the behaviors the `isBound` property was `true` when it should have been `false` at that point, causing some behaviors to not add their needed unbindable behavior (assuming it had already been added when first bound).
Both of these issues were fixed pretty easily by moving the source setting to the right location for rebind scenarios and then ensuring that `isBound` is set …
=> fix: correct view state when processing unbindables during rebind

change/@microsoft-fast-element-afea72fb-a645-4bab-ae21-de581d7d064d.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/templating/binding.spec.ts, packages/web-components/fast-element/src/templating/binding.ts, packages/web-components/fast-element/src/templating/view.ts
While a partner was updating to the latest fast-element beta, we found an issue where `parent` was undefined in nested template composition scenarios. It turns out that the parent context was not being passed through to the composed view.
No issues. Just discovered this morning internally and fast tracking a fix.
The change is to enable passing an optional context to `bind` on views. Content bindings now pass the existing context through the the composed view.
While fixing view, I noticed some missing code docs and an incorrect/obsolete property on `HTMLView`. So, I fixed that as well.
I added a test to ensure this behavior going forward. This was a regression, so the new test should prevent that in the future.
n/a
=> fix: ensure composed templates receive the existing execution context

change/@microsoft-fast-foundation-5689d6c8-9ebe-419b-9297-293568866663.json, packages/web-components/fast-foundation/playwright.config.ts, packages/web-components/fast-foundation/src/accordion/accordion.pw.spec.ts, packages/web-components/fast-foundation/src/button/button.pw.spec.ts, packages/web-components/fast-foundation/src/combobox/combobox.pw.spec.ts, packages/web-components/fast-foundation/src/dialog/dialog.pw.spec.ts, packages/web-components/fast-foundation/src/disclosure/disclosure.pw.spec.ts, packages/web-components/fast-foundation/src/flipper/flipper.pw.spec.ts, packages/web-components/fast-foundation/src/listbox/listbox.pw.spec.ts, packages/web-components/fast-foundation/src/menu-item/menu-item.pw.spec.ts, packages/web-components/fast-foundation/src/menu/menu.pw.spec.ts, packages/web-components/fast-foundation/src/number-field/number-field.pw.spec.ts, packages/web-components/fast-foundation/src/search/search.pw.spec.ts, packages/web-components/fast-foundation/src/select/select.pw.spec.ts, packages/web-components/fast-foundation/src/slider/slider.pw.spec.ts, packages/web-components/fast-foundation/src/tabs/tabs.pw.spec.ts, packages/web-components/fast-foundation/src/tree-item/tree-item.pw.spec.ts, packages/web-components/fast-foundation/src/tree-view/tree-view.pw.spec.ts
Allows flaky tests to wait for a `stable` state.
> Element is considered stable when it has maintained the same bounding box for at least two consecutive animation frames.
https://playwright.dev/docs/actionability
All tests should pass in all pipelines.
=> wait for stable state in flaky playwright tests

yarn.lock
Updates the lockfile entry for `terser` versions between `5.0.0` and `5.14.2` to the latest version `5.15.0`, to resolve a transient dependency vulnerability.
All projects should build successfully and tests should pass as expected.
=> update terser lockfile entry for versions >= 5.0.0 < 5.14.2 to 5.15.0

change/@microsoft-fast-element-94ffb0f7-0710-4351-be86-8aa90f485fd5.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/components/fast-definitions.spec.ts, packages/web-components/fast-element/src/components/fast-definitions.ts, packages/web-components/fast-element/src/components/fast-element.ts
Prior to this PR, it was possible to do this:
```ts
FASTElement.define({...});
```
This would actually define `FASTElement` itself with the platform, meaning every other web component inheriting from FASTElement would inherit any attributes, observables, etc. that happened to be defined on `FASTElement`. We don't want that to ever be possible.
This PR prevents this scenario by detecting a direct `FASTElement` registration and automatically inheriting a base class. The advantage of this approach is that it is now safe to call the API above, which means we also now support creating simple web components without defining a class (FAST will handle that automatically).
I just discovered this issue today and skipped straight to the fix since it only took a few minutes.
I thought it would be …
=> fix: prevent registering FASTElement itself

change/@microsoft-fast-element-162827a3-f51b-45a1-aeb9-f411fc6a46a7.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/interfaces.ts, packages/web-components/fast-element/src/observation/observable.ts
The kernel that is shared between on fast instances on page unintentionally had a method removed between v1 and v2. This PR adds that method back.
Just spotted this one. Quick fix.
There are a couple of renames to params in this PR but the real point of interest is adding the "disconnect" method that is needed for back-compat with v1's kernel. This is not part of the v2 public API but needs to remain in case v1 is consuming the v2. kernel.
The functionality is tested already via the "dispose" method.
n/a
=> fix: observation kernel missing binding observer disconnect method

package.json, yarn.lock
Resolves `d3-color` entries to `^3.1.0` to resolve a security vulnerability.
`d3-color` is a transient dependency of `mermaid`, which is used in the `fast-site` project. `mermaid` depends on both `d3@^7.0.0` as well as `dagre-d3@^0.6.4`, the latter of which is unmaintained and depends on `d3@^5.14`.
Since the version difference for `d3` is already explicitly defined in `mermaid`, it's unlikely that forcing all versions of `d3-color` to the same resolution will have any major impact.
All packages should build successfully and all tests should pass.
The only place where Mermaid is currently being used is the Documentation site's introduction page.
=> resolve d3-color to ^3.1.0

change/@microsoft-adaptive-ui-2719e09a-87b8-4885-82ef-70da2fc5c024.json, packages/utilities/adaptive-ui/src/design-tokens/color.ts
I recently added the "overlay" mode for neutral color recipes, which was intended to be opt-in, but I left the default value turned on. This PR puts it back to the functionality before that feature was introduced.
=> Adaptive UI: Fix overlay default value

change/@microsoft-fast-element-3b13b942-8992-4fab-b487-711ff6c2e981.json, change/@microsoft-fast-react-wrapper-55d635eb-ef4d-4694-8914-ce8f90a1ef7a.json, change/@microsoft-fast-router-93b6ac1d-04e7-40d9-9e17-98a9fb0a1d01.json, change/@microsoft-fast-web-utilities-b69f4abd-7050-4c04-8f50-21e988513fd4.json, package.json, packages/utilities/fast-react-wrapper/package.json, packages/utilities/fast-web-utilities/package.json, packages/web-components/fast-element/package.json, packages/web-components/fast-router/package.json, yarn.lock
Upgrades `karma` in all packages to `^6.4.1`, to upgrade transient dependency `engine.io` to `> 3.6.0`.
The breaking changes listed [here](https://karma-runner.github.io/6.0/about/changelog.html) don't appear to affect our usage.
All packages should build successfully and all tests should pass as expected.
=> upgrade karma to ^6.4.1 to resolve engine.io transient dependency

change/@microsoft-fast-element-86101b93-75a7-43ab-ac5a-69d6bd4bd25f.json, packages/web-components/fast-element/src/templating/binding.spec.ts, packages/web-components/fast-element/src/templating/binding.ts, packages/web-components/fast-element/src/testing/fakes.ts
An optimization that allows event handlers to remain after view teardown, introduced a bug whereby event handlers that fire after the view is unbound, results in errors due to null source and context.
* Internal
The fix was pretty straight forward: just check whether the controller is bound before executing callbacks.
A failing test was added to catch the bug and then the fix was applied to pass the test. To create a test for this, the fake view controller needed to be enhanced. As part of that work some test refactoring was done to clean up the binding tests.
All existing tests continue to pass.
While working on this fix, I saw some extra code in the HTMLDirective that should be cleaned up. There is also an opportunity to improve the tests by using the new view controller fake and …
=> fix: prevent event callbacks when controller is not bound

change/@microsoft-fast-foundation-2266fb9e-f78c-4a18-95f1-7de5f7bc8c5b.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/tree-item/README.md, packages/web-components/fast-foundation/src/tree-item/stories/tree-item.register.ts, packages/web-components/fast-foundation/src/tree-item/tree-item.pw.spec.ts, packages/web-components/fast-foundation/src/tree-item/tree-item.template.ts, packages/web-components/fast-foundation/src/tree-item/tree-item.ts, packages/web-components/fast-foundation/src/tree-view/stories/tree-view.stories.ts
This PR fixes issues related to some updates made during the playwright migration.
It was discovered that on initial load, when the expanded attribute was set for a given item, `aria-expanded` would not be set. The reason for this is that without an explicit invocation in `connectedCallback()` the attribute isn't set. This behavior would seemingly also occur for the selected and disabled attributes as well since they present similar functionality. One reason this wasn't visually caught was because the styling was tied to the `expanded` attribute rather than the `aria-expanded` attribute, so everything seemed fine. Additionally, I've added tests to ensure that when the attribute is present at load, the corresponding ARIA attributes are provided.
An additional removal here is the addition …
=> revert tree item changes from playwright migration

change/@microsoft-fast-element-ddaddb30-57bf-4509-bdbd-9feaadcf73dc.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/templating/binding.ts
This PR is a follow-up to a recent bug fix in events. While doing that work I noticed there was some duplicate code and an odd internal monkey-patching pattern that I wanted to eliminate.
* Related to #6439 
This PR moves bind logic out of separate methods that were monkey patched and into a single method with simple branching logic.
I also noticed a few parameters that missed getting renamed with other APIs changed, so I fixed those up as well.
This was just an internal refactor, so no new tests added. Existing tests all continue to pass.
I'm pondering some ideas to potentially clean some of this up further but I'm not sure about the approach just yet. I also want to get the new security policy work in place first, since that will affect some of this same logic.
=> refactor: remove duplication and re-organize binding behavior logic

change/@microsoft-fast-foundation-cb37e044-b9ac-4719-a213-fbfee4e64ca6.json, packages/web-components/fast-foundation/src/checkbox/README.md, packages/web-components/fast-foundation/src/checkbox/checkbox.pw.spec.ts, packages/web-components/fast-foundation/src/checkbox/checkbox.template.ts, packages/web-components/fast-foundation/src/checkbox/checkbox.ts, packages/web-components/fast-foundation/src/checkbox/stories/checkbox.register.ts
This PR ensures that checkboxes with an `indeterminate` property set an aria-checked value of 'mixed'. This also reverts the move to applying a data-attribute with the fact that `indeterminate` styling of the checkbox can be accomplished via a `mixed` attribute selector.
closes #6448
=> indeterminate checkboxes should set an aria-checked value of 'mixed'

change/@microsoft-fast-foundation-0522614f-d1db-45a7-b87a-3e719b7d174e.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/button/button.ts, packages/web-components/fast-foundation/src/button/stories/button.stories.ts
This PR fixes an issue where NVDA announces slots as clickable if they have an onClick event bound.
Just as a general FYI for those interested. The reason why NVDA announces "clickable clickable button" when a svg is in the start slot is because if you set `aria-hidden` on the svg it is hidden from the SR however NVDA announces elements with a click handler bound to them as clickable so for `FASTButton` where it was binding click handlers to all the slots the announcement would look like "clickable '' clickable [default slot content] button". If the svg is in the end slot then it announces "clickable [default slot content] clickable '' button". This same pattern would hold true for any content in the named slots.
NVDA would announce the named slots in `Button` as clickable if they …
=> Fix: NVDA announces button slots as clickable

change/@microsoft-fast-foundation-3f32a23d-676d-4f08-a6a8-fd448c3b2665.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/tree-item/tree-item.template.ts, packages/web-components/fast-foundation/src/tree-item/tree-item.ts, packages/web-components/fast-foundation/src/tree-view/tree-view.ts
An issue has come up where attempting to check the role attribute as part of the (previous) isTreeItemElement function was always returning null/undefined. Previously the check which was working was comparing the tag name, but this presented a problem for any component extending the Tree Item without "tree item" in the tag name.
After some investigation and discussion w/ @eisenbergeffect, it's likely that this working previously may have in fact been a bug or an inefficiency around lifecycles. All attributes on a template need to be setup as a binding and those bindings don't exist initially when these checks are executing. 
It's always been intended that Tree View support elements with a role of treeitem to the best of its ability. This makes sense considering that someone may want to …
=> add readonly property to identify tree items and update isTreeItemElement check

change/@microsoft-fast-ssr-0f0a8d37-e40b-4788-86db-1a6f1d07e454.json, packages/web-components/fast-ssr/src/dom-shim.spec.ts, packages/web-components/fast-ssr/src/dom-shim.ts
This PR adds a shim for the `MediaQueryList.addEventListener` method. Previously, only the deprecated `addListener` method was shimmed. 
It also updates the `matchMedia()` implementation to always use the window's MediaQueryList constructor. This allows authors to override `MediaQueryList` and have `matchMedia` construct the author-provided override.
=> Shim MediaQueryList.addEventListener to fast-ssr DOM shim

change/@microsoft-fast-foundation-4b4b433b-fc2b-4777-a993-0554019f10a7.json, change/@microsoft-fast-ssr-d20a5285-139e-4090-a290-078ecfe3b5e7.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/package.json, packages/web-components/fast-foundation/src/menu-item/menu-item.template.ts, packages/web-components/fast-foundation/src/menu-item/menu-item.ts, packages/web-components/fast-foundation/src/menu-item/stories/menu-item.register.ts, packages/web-components/fast-foundation/src/menu/README.md, packages/web-components/fast-foundation/src/menu/menu.pw.spec.ts, packages/web-components/fast-ssr/src/dom-shim.spec.ts, yarn.lock
Replaces the methods used to position submenus for menu-item with Floating UI.
Changes the `updateSubmenu` method to be public to allow for overriding the default positioning behavior.
All tests for the menu-item and menu components should pass as expected.
=> Use Floating UI for MenuItem submenus

change/@microsoft-fast-ssr-804e71af-7827-4c43-915a-9bc391332976.json, packages/web-components/fast-ssr/src/element-renderer/elemenent-renderer.spec.ts, packages/web-components/fast-ssr/src/element-renderer/fast-element-renderer.ts
- Fix boolean attribute rendering issues and throw error for unknown/object type of attributes
FAST SSR will crash for boolean type attributes because of escapeHtml and it will also convert object type into `[object Object]` string. This PR fixes both of these 2 issues.
https://github.com/microsoft/fast/issues/6476 (it's reopened as discussed)
New unit tests are added. This branch has the testing code in example project: https://github.com/YusakuNo1/fast/tree/daviwu/ssr-boolean-crash-example
- [x ] I have included a change request file using `$ yarn change`
- [x ] I have added tests for my changes.
- [x ] I have tested my changes.
- [x ] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the …
=> fix: fix boolean crash issue and throw error for unknown/object attributes

change/@microsoft-fast-foundation-d9cd55f5-5363-4cf8-88c0-8cdf107c0014.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/design-token/fast-design-token.ts
This PR implements `HTMLDirective` on `CSSDesignToken` so that it works the same in HTML as it does in CSS.
* Closes #6459 
Very simple implementation. Basically, one line of code plus registering via decorator.
Existing tests pass. Planning to add a simple test to verify this in a follow-up PR, after the security PR is merged. I need test infrastructure from that PR to do it.
Follow up PR to add an HTML Directive tests.
=> feat: enable using design tokens in html

change/@microsoft-fast-element-076c59cf-8308-49f9-9d81-e21e0ca3b1c7.json, change/@microsoft-fast-foundation-9a782ea3-339a-48cc-bd6c-6a53b5ba91ba.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/templating/html-directive.ts, packages/web-components/fast-element/src/utilities.ts, packages/web-components/fast-foundation/src/data-grid/data-grid-row.ts, packages/web-components/fast-foundation/src/data-grid/data-grid.ts, packages/web-components/fast-foundation/src/picker/picker.ts
This is the first of several cleanup tasks designed to prepare fast-element 2.0 for production release. This PR moves `ViewBehaviorOrchestrator` to utilities, since it is not used by fast-element itself and only used by a very specific set of components in foundation. Its usage would not be common.
* #6502 
This is just a basic move of the code. It did cause a break in foundation, but that is easily fixed by correcting the imports to point to the new location.
All existing tests pass. No new tests added as part of this move.
We should add some tests for `ViewBehaviorOrchestrator` in a future PR.
=> chore: move ViewBehaviorOrchestrator to utilities

packages/utilities/fast-benchmarks/scripts/template.js
When a string is passed into the **versions** argument of the node script for running a benchmark in fast-benchmark, it would resolve that as a fast-element version number (i.e 1.9.0 or 2.0.0-beta). The same argument also accepts branch names as a possible value to be passed under **versions**, resulting in a possible bug if someone passes in a branch name that has a '.' in it (ie.  users/jokreitl/update-engine.io)
The solution to this is to strengthen the check for the fast-element version format using regex, anything that does not follow number-period character-number-period character -number will be resolved as a branch name.
#6427
=> fix: use regex to check for version format in fast-benchmarks

change/@microsoft-fast-ssr-98fe57e7-b330-4251-80ac-f87ee4835fb7.json, packages/web-components/fast-ssr/src/dom-shim.spec.ts, packages/web-components/fast-ssr/src/dom-shim.ts
This PR adds `classList`, `className`, and `part` properties to the `HTMLElement` shim for SSR.
* Partial work for #6490  
The main part of this PR is the introduction of an implementation of `DOMTokenList` which is then plugged into `HTMLElement` where appropriate.
Tests for `DOMTokenList` were added. Existing tests continue to pass.
Explore whether any other shims are needed to enable foundation components to function out of the box.
=> feat: shim DOMTokenList for class and part properties on HTMLElement

change/@microsoft-fast-foundation-1eab34df-e56e-484b-95df-6fa33630a274.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/checkbox/README.md, packages/web-components/fast-foundation/src/checkbox/checkbox.pw.spec.ts, packages/web-components/fast-foundation/src/checkbox/checkbox.spec.md, packages/web-components/fast-foundation/src/checkbox/checkbox.template.ts, packages/web-components/fast-foundation/src/checkbox/checkbox.ts
BREAKING CHANGE: remove readOnly property from checkbox's API
by [MDN, read-only](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly) attribute should not exist in checkbox.
> The attribute is not supported or relevant to [`<select>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) or input types that are already not mutable, such as [checkbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox) and [radio](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio) or...
=> fix(foundation): checkbox remove read-only support

change/@microsoft-fast-foundation-9eda75c8-6106-407b-9040-5989faee48ab.json, packages/tooling/fast-figma-plugin-msft/package.json, packages/utilities/fast-react-wrapper/CHANGELOG.json, packages/utilities/fast-react-wrapper/CHANGELOG.md, packages/utilities/fast-react-wrapper/package.json, packages/web-components/fast-foundation/CHANGELOG.json, packages/web-components/fast-foundation/CHANGELOG.md, packages/web-components/fast-foundation/package.json, sites/fast-color-explorer/package.json, sites/fast-website/package.json
Syncs the repo with the post-publish state after the publish failed to push back to the `archives/fast-element-1` branch.
=> sync archives branch after failed push during publish

change/@microsoft-fast-element-adc6fdac-3411-4786-bd9d-b1bb3a82444e.json, change/@microsoft-fast-foundation-0a201408-33b3-497e-8e66-122f78d3f80f.json, change/@microsoft-fast-ssr-7b286a75-f0b4-462d-bc2a-945de03a8271.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/components/attributes.ts, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/card/stories/card.register.ts, packages/web-components/fast-foundation/src/tooltip/README.md, packages/web-components/fast-foundation/src/tooltip/index.ts, packages/web-components/fast-foundation/src/tooltip/stories/tooltip.register.ts, packages/web-components/fast-foundation/src/tooltip/stories/tooltip.stories.ts, packages/web-components/fast-foundation/src/tooltip/tooltip.options.ts, packages/web-components/fast-foundation/src/tooltip/tooltip.pw.spec.ts, packages/web-components/fast-foundation/src/tooltip/tooltip.spec.md, packages/web-components/fast-foundation/src/tooltip/tooltip.template.ts, packages/web-components/fast-foundation/src/tooltip/tooltip.ts, packages/web-components/fast-ssr/src/dom-shim.spec.ts
* Rewrites the `Tooltip` component to use Floating UI.
* Enables built-in `aria-describedby` support. Once the anchor element is resolved, the `aria-describedby` attribute will be added to it to match the tooltip's `id`. If the anchor changes, the `id` will be removed from the old anchor's `aria-describedby` attribute and added to the new anchor.
* Replaces the `position` attribute with `placement` to match the naming convention used by Floating UI.
* Adds the `show` attribute to control the visibility of the tooltip.
* Removes the `delay` attribute as it's no longer needed - tooltip transitions can be controlled via CSS.
* Updates the spec document to reflect the changes.
* Adds a `nullalbleBooleanConverter` to `@microsoft/fast-element` for attributes that are `true`, `false`, or …
=> use Floating UI for tooltip

change/@microsoft-fast-foundation-320b3755-1115-4abf-860a-95a6ac9a9327.json, packages/web-components/fast-foundation/src/data-grid/data-grid.ts
Data-grid was not properly cleaning up generated header on disconnect, so in disconnect/reconnect scenarios the extra row in the dom would create multiple problems.
closes https://github.com/microsoft/fast/issues/6564
Straightforward fix, did not create new tests.
=> fix: data-grid: clean-up header on disconnect

change/@microsoft-fast-element-a8d80d50-029f-4e90-a013-92790032d39c.json, packages/tooling/adaptive-ui-explorer/src/components/color-block.ts, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/di/di.ts, packages/web-components/fast-element/src/dom.ts, packages/web-components/fast-element/src/styles/css.ts
This PR removes duplicative deprecated APIs from `fast-element`.
* Part of [#6502](https://github.com/microsoft/fast/issues/6502)
Just a removal of APIs that were marked deprecated for several releases.
Existing tests continue to pass.
Continuing a survey of the `fast-element` codebase to see if there is any other polish that is needed in preparation for a release.
=> chore: remove deprecated APIs from fast-element

change/@microsoft-fast-foundation-cafc5ae3-9c3e-4715-b923-5e7542e55091.json, packages/web-components/fast-foundation/src/design-token/design-token.spec.ts, packages/web-components/fast-foundation/src/design-token/interfaces.ts
Note: This PR only targets `archives/fast-element-1` as the issue does not reproduce in master. The tests might be useful to pull into master to prevent regressions. See Reviewer Notes.
`DerivedDesignTokenValue` were accidentally opting in to [Distributive Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types) behavior when enum values were used resulting in an enum like:
```ts
const Animal = {
cat: 'cat',
dog: 'dog',
} as const;
type Animal = typeof Animal[keyof typeof Animal];
```
Result in requiring a type of:
```ts
(target: HTMLElement) => Animal.cat | (target: HTMLElement) => Animal.dog
```
Instead of the expected type of:
```ts
(target: HTMLElement) => Animal
```
Fixes #6529.
I opted out of distributive conditional …
=> Allow using enums for derived DesignToken values

change/@microsoft-fast-foundation-03faed3d-3f1a-4cc2-9e08-9e98c8ba4ded.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/accordion-item/accordion-item.pw.spec.ts, packages/web-components/fast-foundation/src/accordion-item/accordion-item.template.ts, packages/web-components/fast-foundation/src/accordion-item/accordion-item.ts, packages/web-components/fast-foundation/src/accordion-item/stories/accordion-item.register.ts, packages/web-components/fast-foundation/src/accordion/README.md, packages/web-components/fast-foundation/src/accordion/accordion.ts, packages/web-components/fast-foundation/src/accordion/stories/accordion.stories.ts
This PR adds a disabled attribute to accordion item and updates the accordion component to adequately observe the attribute with respect to keyboard behaviors.
closes #6581
=> feat: add disabled attribute to accordion item

change/@microsoft-fast-foundation-5a3886ec-6b78-4daf-b7dd-fc42d9ca6149.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/utilities/style/display.ts
While Foundation doesn't export component styles, it does export several helpers for creating design systems. The specific helpers here make sense to continue to share with the community in order to provide common patterns which can be shared rather than duplicated across implementations. This simply removes the deprecation notice for this helper in favor of continuing support.
n/a
=> fix: remove deprecation notice for display helper utility

change/@microsoft-fast-foundation-c597e1e0-fe5a-4e24-8679-a435b94beb03.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/accordion-item/accordion-item.pw.spec.ts, packages/web-components/fast-foundation/src/accordion-item/accordion-item.template.ts, packages/web-components/fast-foundation/src/accordion/README.md, packages/web-components/fast-foundation/src/accordion/accordion.pw.spec.ts, packages/web-components/fast-foundation/src/accordion/accordion.template.ts, packages/web-components/fast-foundation/src/accordion/accordion.ts, packages/web-components/fast-foundation/src/accordion/stories/accordion.stories.ts
This PR refactors the behavior associated for "single" expand-mode accordion instances. It also fixes an issue where disabled buttons of accordion items were focusable via tabbing.
closes #6584
=> fix: accordion "single" expand-mode instances should support defined expanded children

change/@microsoft-fast-foundation-163d8cc4-4555-4850-bd77-634d114cd95f.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/avatar/README.md, packages/web-components/fast-foundation/src/avatar/avatar.spec.md, packages/web-components/fast-foundation/src/avatar/avatar.template.ts, packages/web-components/fast-foundation/src/avatar/avatar.ts, packages/web-components/fast-foundation/src/avatar/stories/avatar.register.ts, packages/web-components/fast-foundation/src/avatar/stories/avatar.stories.ts
Many uses of an `Avatar` do not require `link` functionality. Often when it does it's beneficial to have other visual indications like hover and active indication. This update to `Avatar` allows it to be a general container for an combination of a profile image, initials, and a badge. If it requires click or link functionality it should be used within a `Button` or `Anchor`.
Reviewed under Storybook examples. Might have styling impacts if the `<a>` was expected for layout purposes.
Test styling of any custom `Avatar` components.
=> feat: remove link from avatar

change/@microsoft-fast-foundation-30bb7b36-e241-4543-b762-09555f2be889.json, packages/web-components/fast-foundation/src/switch/stories/switch.register.ts, packages/web-components/fast-foundation/src/switch/stories/switch.stories.ts, packages/web-components/fast-foundation/src/switch/switch.template.ts
This PR removes the status messages from switch. While initially these were thought to bring value to the switch state, switches have become commonplace in modern UI and status specific messages rarely accompany them (see all of iOS settings as an example of this). In an effort to provide "foundational" building blocks of common controls we should remove this excess as part of the component template. Moving the status messages from within the template doesn't prevent the switch from being composed as part of another template and likely enables folks to better associate using ARIA attributes if necessary, whereas that was previously not possible with these baked into the template.
@bheston and @falkicon as FYI.
n/a
=> feat: remove status messages from switch

change/@microsoft-fast-foundation-f0b22146-d95c-483f-b31b-b7eebbb13058.json, packages/web-components/fast-foundation/src/switch/switch.ts
This removes a `readonly` classname which is added to the switch host element.
=> fix: remove readonly classname from switch

change/@microsoft-fast-foundation-630834ad-b6a7-4fb5-82e8-f9a49fa2ec98.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/accordion/README.md, packages/web-components/fast-foundation/src/accordion/accordion.pw.spec.ts, packages/web-components/fast-foundation/src/accordion/accordion.ts
Fixes an issue where swapping expand modes did not trigger the proper updates to the accordion component. This also goes back to setting an item's expand button to aria-disabled attribute vs. disabled.
fixes #6586
=> fix: acccordion expand mode changes should update the UI as expected

change/@microsoft-fast-foundation-700c2cf4-da3a-492b-8907-db7fa835c422.json, packages/web-components/fast-foundation/src/accordion-item/accordion-item.ts, packages/web-components/fast-foundation/src/accordion/accordion.pw.spec.ts, packages/web-components/fast-foundation/src/accordion/accordion.ts
This PR fixes an issue where programmatic changes to a child's expanded property would allow multiple items open in single-expand scenarios. In this update, programmatic changes are observed and only the latest expanded accordion should remain open.
As part of these changes, the API for Accordion Items has changed. The `change` event becomes a specific _click_ event for the click handler. This change removes state handling from the accordion item and moves it into the "parent" accordion as we've done with similar updates to tree view and tree item, menu and menu items.
#6585
Tests have been updated to accommodate this specific scenario
=> fix: observe accordion item expanded state to ensure programmatic changes to children are handled in single expand scenarios

change/@microsoft-fast-foundation-783a779e-e845-401e-b3b0-a1752e3595e3.json, packages/web-components/fast-foundation/src/picker/picker.template.ts, packages/web-components/fast-foundation/src/picker/stories/picker.register.ts
Adds a quote missing in the `Picker` template.
Fixed template binding for tags that are passed in to the component, not rendered in the template.
Cleaned up the styling.
=> fix: missing quote on Picker template

change/@microsoft-fast-foundation-3a1720aa-98a8-4aed-8596-b071ec2d7773.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/radio-group/radio-group.pw.spec.ts, packages/web-components/fast-foundation/src/radio-group/radio-group.template.ts, packages/web-components/fast-foundation/src/radio-group/radio-group.ts, packages/web-components/fast-foundation/src/radio-group/stories/radio-group.register.ts, packages/web-components/fast-foundation/src/radio/README.md, packages/web-components/fast-foundation/src/radio/radio.pw.spec.ts, packages/web-components/fast-foundation/src/radio/radio.template.ts, packages/web-components/fast-foundation/src/radio/radio.ts
This PR proposes a slight refactor of radio group in order to support the disabling of the radiogroup without modifying the state of individual radio children. This PR does a few things:
1) Removes click handling behavior for the radio itself and manages via the group. Per the APG, radios which are not selected (primarily on page-load scenarios) can be selected via "Space" so that behavior remains in tact.
2) Removes behavior modifying each disabled items `disabled` state. For the sake of ensuring we don't break with future changes to the disabledChanged method, I've left this enumerated as _protected_ for now.
3) Assigns a tabindex of -1 to prevent focus from being brought to the element and its children.
4) To ensure that focus does not pass to the radiogroup when clicked, a mousedown …
=> fix: refactor radio group to better manage disabled state and interactions

change/@microsoft-fast-element-59331653-4600-45fc-b598-6087e3bfd94e.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/components/element-controller.ts, packages/web-components/fast-element/src/index.ts, packages/web-components/fast-element/src/observation/observable.ts, packages/web-components/fast-element/src/platform.ts, packages/web-components/fast-element/src/templating/binding-signal.ts, packages/web-components/fast-element/src/templating/binding-two-way.ts, packages/web-components/fast-element/src/templating/binding.ts, packages/web-components/fast-element/src/templating/html-directive.ts, packages/web-components/fast-element/src/templating/template.ts, packages/web-components/fast-element/src/templating/view.ts
This PR continues the work of cleaning up and polishing `fast-element` in preparation for release. It removes the `toJSON` noop from the public API surface and shifts the logic to an internal utility function.
* Part of #6502 
This is a small cleanup PR that centralizes logic and removes some clutter from type definitions.
No changes to functionality. All tests continue to pass.
More PRs coming as part of the general cleanup/polish work.
=> fix: clean up toJSON noop on core fast-element types

change/@microsoft-fast-element-83001531-34b6-4220-aaa5-090b6da18111.json, packages/web-components/fast-element/src/templating/render.spec.ts, packages/web-components/fast-element/src/templating/render.ts
This PR adds the ability to attach directives to the host element provided to `createElementTemplate` as well as consolidating the function's arguments into a single options object, which affects the `RenderInstruction.create` API.
After this change this is now possible:
```ts
class Model {
@observable elementRef: HTMLElement;
handleClick() {}
}
const template = RenderInstruction.createElementTemplate(
"fast-button",
{
attributes: { "@click": x => x.handleClick() },
directives: [ref("elementRef")], // applies to the "button" element being created
content: html`<svg slot="start">...</svg> click me!`
}
);
```
Prior to this change, it was not possible for the `Model` instance to access the `button` element it is bound to. In addition if the `Model` needed the children nodes of the host …
=> Add directives support for `createElementTemplate`

change/@microsoft-adaptive-ui-8f07cca9-405c-4b1f-a02a-710dc954f1aa.json, packages/utilities/adaptive-ui/README.md
Updated the package readme for adaptive-ui to reflect that it will no longer be maintained per #6603.
#6603 
- Publish the adaptive-ui package to update the notes on npmjs
- Mark the package deprecated in the registry
=> Marked @microsoft/adaptive-ui package for deprecation

change/@microsoft-fast-element-603d0ed3-89c6-4505-b1cd-4d26148f994b.json, packages/web-components/fast-element/src/context.spec.ts, packages/web-components/fast-element/src/context.ts, packages/web-components/fast-element/src/interfaces.ts, packages/web-components/fast-element/src/metadata.ts
This PR adds a new `Context.for()` API, modeled after the standard `Symbol.for()` JavaScript API. The new API allows you to get a context by name, if it exists, or create one with the provided name if it doesn't. Any created Context will be cached by name and returned by future calls to the API.
As part of this work, the final bit of cleanup on the `Context` feature was done, along with `Metadata` and core interfaces.
* Relates to issue #6502.
There's not much to this PR. The `Context.for()` API is new and has a pretty simple internal implementation. The rest of the changes are docs and cleanup.
All existing tests continue to pass. Two new tests were added for `Context.for()`.
Cleanup and polish for additional areas of `fast-element` as time permits.
=> feat: add Context.for() and polish Context

change/@microsoft-fast-foundation-3f5da524-dd71-4e14-bae8-982e36915731.json, packages/web-components/fast-foundation/src/data-grid/data-grid.ts, packages/web-components/fast-foundation/src/data-grid/stories/data-grid.stories.ts
Data grid wouldn't render a header element when there is no rows in the data.  Obviously automatic generation of columns needs data, but not when columnDefinitions are provided.  Also fixed a minor bug with scrolling to elements when no data and added a "with columnDefintions" story.
ad-hoc
- [ x] I have included a change request file using `$ yarn change`
- [ x] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.
=> Fix: data-grid with no rows should still render header

change/@microsoft-fast-foundation-bebb95bc-b4fb-48e2-8371-85e34ce9ee40.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/tabs/README.md, packages/web-components/fast-foundation/src/tabs/stories/tabs.register.ts, packages/web-components/fast-foundation/src/tabs/stories/tabs.stories.ts, packages/web-components/fast-foundation/src/tabs/tabs.pw.spec.ts, packages/web-components/fast-foundation/src/tabs/tabs.template.ts, packages/web-components/fast-foundation/src/tabs/tabs.ts
This PR removes the prescriptive approach of adding an "activeindicator" element to the tabs component. While convenient for the default FAST approach and perhaps others, it's a very prescriptive approach to managing an active indicator and ultimately *only* necessary when one wants to animate an active indicator independently of the tabs themselves.
This PR removes the active indicator. We'll tackle examples in a subsequent PR or via a stackblitz example.
=> feat: remove activeindicator from tabs

change/@microsoft-fast-element-207108f3-8e5f-4e90-82d4-3a1590ac5ad9.json, packages/web-components/fast-element/src/context.ts, packages/web-components/fast-element/src/interfaces.ts
TypeScript broke legacy parameter decorators by changing the compiler without updating their distributed types. This PR adds our own version of the `ParameterDecorator` type, to get around TypeScript's "oopsie". Without this fix, certain code will not compile in TS 5. I hope we can remove this after a future TypeScript 5 release.
No associated issue.
This is only a types change. No change to actual behavior.
All tests continue to pass.
I plan to continue review and polish in preparation for release.
=> fix: correct types for a break in TypeScript 5 legacy decorators

change/@microsoft-fast-foundation-0f870b93-d388-4f3a-abb6-7fe71502d122.json, packages/web-components/fast-foundation/src/picker/picker.ts
Picker option filtering should be case insensitive.  We could consider adding customizability later, but the default should be permissive.
ad-hoc
=> fix: picker filter should be case insensitive

change/@microsoft-fast-element-b964400d-bbe0-4401-bd6a-12b1f459d3b2.json, packages/web-components/fast-element/src/components/element-controller.ts
Safari 16.4 released support of adoptedStyleSheets and constructable style sheets. It appears there is a bug in the implementation though, causing intermittent removal of sheets when new sheets are added. In our testing, it appears that using this implementation circumvents the bug.
This PR updates FAST's constructableStyleSheet strategy to use push/splice instead of new array assignment when the browser's adoptedStyleSheet implementation does not use a FrozenArray. Since initial implementation of this code, the CSSOM spec has been [updated to define using an ObservableArray](https://www.w3.org/TR/cssom-1/#ref-for-dom-documentorshadowroot-adoptedstylesheets) for adoptedStyleSheets. This code falls back to array assignment if push and splice are not supported.
I've also filed a [bug …
=> fixes bug in Webkit adoptedStyleSheets implementation

change/@microsoft-fast-element-abaf8433-027c-4daf-a871-2b516797920b.json, packages/web-components/fast-element/src/styles/element-styles.ts, packages/web-components/fast-element/src/styles/styles.spec.ts
Safari 16.4 released support of adoptedStyleSheets and constructable style sheets. It appears there is a bug in the implementation though, causing intermittent removal of sheets when new sheets are added. In our testing, it appears that using this implementation circumvents the bug.
This PR updates FAST's AdoptedStyleSheetsStyles to use push/splice instead of new array assignment when the browser's adoptedStyleSheet implementation does not use a FrozenArray. Since initial implementation of this code, the CSSOM spec has been [updated to define using an ObservableArray](https://www.w3.org/TR/cssom-1/#ref-for-dom-documentorshadowroot-adoptedstylesheets) for adoptedStyleSheets. This code falls back to array assignment if push and splice are not supported.
=> fix: use push/splice for adoptedStyleSheet mutation when available

change/@microsoft-fast-foundation-4ed56949-7343-439d-9bd1-4f76b36c9d1d.json, packages/web-components/fast-foundation/src/picker/picker.ts
Picker "no options" display shows up one keystroke too late because the current detection happens before invalid options based on the last char typed are removed from the dom.
ad-ho
=> Fix: picker show no options

sites/website/src/docs/introduction.md
Closes https://github.com/microsoft/fast/issues/6738
The introduction page has the following line of text:
> One of FAST's driving principals is "strive to adopt open, web standards-based approaches as much as possible."
I believe the line is referring to `principles` as opposed to `principals`.
As a solution, I have just replaced the word `principals` with `principles`.
* https://github.com/microsoft/fast/issues/6738
This is a simple content change. Just make sure the new copy makes sense and the change looks correct.
<details>
<summary>Test Case</summary>
1. Open the documentation site and navigate to the introduction page `/docs/introduction/`
2. Confirm that the text `One of FAST's driving principals is` has been changed to `One of FAST's driving principles is`
</details>
Not …
=> Replaced `principals` with `principles`

change/@microsoft-fast-element-e03719ce-131a-4254-a882-d9bc399664dc.json, packages/web-components/fast-element/src/templating/children.spec.ts, packages/web-components/fast-element/src/templating/children.ts
This PR fixes a runtime exception that would occur when a re-bound `ChildrenDirective` would observe a DOM mutation.
This exception occurs because the `disconnect()` method would null-out the target reference on the observer that is using within the mutation handler. That property was only assigned during initial creation of the observer, so re-binding would skip the assign step and following code would throw when trying to access properties of the null reference. 
fixes #6740
=> fix children directive rebind bug

change/@microsoft-fast-element-e0afb613-ce1a-4f4f-95a8-5518772af979.json, packages/web-components/fast-element/src/templating/compiler.spec.ts, packages/web-components/fast-element/src/templating/compiler.ts, packages/web-components/fast-element/src/templating/view.spec.ts
Coming back around to this with @eisenbergeffect's suggestion. This PR checks or null first and last child references in the template compiler and inserts a comment to gracefully handle null scenarios for views.
closes #6596
=> fix: add comment to empty templates to gracefully handle null first/last child for views

change/@microsoft-fast-react-wrapper-cf03dab8-c553-4726-abe3-112e2aa326bb.json, packages/utilities/fast-react-wrapper/docs/api-report.md, packages/utilities/fast-react-wrapper/src/index.ts
This PR adds a displayName to the react wrapper and makes an adjustment to leverage a single call to `getTagName()` to resolve a consistent name. 
Would replace #6747, closes #6741
=> feat: add displayName to react wrapper

change/@microsoft-fast-foundation-240d2dac-2fd1-4e5f-a760-03c9e5505330.json, packages/web-components/fast-foundation/src/toolbar/toolbar.ts
Fixes an issue where toolbar would throw if the class were used with a template without start or end slots.
fixes #6634
=> fix: toolbar should not throw if start/end slots do not exist

change/@microsoft-fast-foundation-b1cdc933-e7be-42e8-8d85-95a5af001f1a.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/utilities/apply-mixins.ts, packages/web-components/fast-foundation/src/utilities/index.ts
This PR removes the 'applyMixins' function from exported features. 'applyMixins' is an implementation detail of fast-foundation components and doesn't relate to the package's purpose. Additionally, there are better mixin patterns that don't rely on copying property descriptors manually, such as defining mixin classes as functions accepting a base class.
=> chore: remove 'applyMixins' function

change/@microsoft-fast-element-44cfe95a-1f60-4e2e-a3f1-1d02aba63bab.json, packages/web-components/fast-element/src/observation/arrays.spec.ts, packages/web-components/fast-element/src/observation/arrays.ts
This PR fixes a bug where array observer would notify a splice when the mutation that occurred did not alter the array values. It appears in FE2 migration, an attempt to optimize for single-splice processing short-cut the projection process, which would detect non-mutation scenarios like splicing an array with the same values. 
This issue has significant impact of the `repeat` directive, causing it to disconnect and re-connect views un-necessarily. 
fixes ##6431
=> fix: prevent array splice notification on non-mutating splice() calls

change/@microsoft-fast-element-00081d16-c6c4-4ceb-9f3e-83e02b28b92a.json, packages/web-components/fast-element/src/observation/observable.spec.ts, packages/web-components/fast-element/src/observation/observable.ts
This PR adds detection for JavaScript's [Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) syntax to `Observable.isVolatile()`. Prior to this change, expressions that leveraged JavaScript optional chaining would not get detected as volatile, causing bindings to not update appropriately.
=> fix: Adds support for JavaScript optional chaining syntax in bindings

change/@microsoft-fast-foundation-7d8d0430-523b-473a-af77-e2bcf0bc6e38.json, packages/web-components/fast-foundation/src/tabs/tabs.pw.spec.ts, packages/web-components/fast-foundation/src/tabs/tabs.ts
There is a bug in the tabs component where you can use the keyboard (arrows, home/end) to navigate to a hidden tab. None of the tabs will appear as active, but the tab panel for the hidden tab will be displayed.
NA
There is a TODO in the tabs test file for creating tests for keyboard navigation. I have created just two tests to exercise the use cases I fixed.
I would like this change cherry-picked into the `archives/fast-element-1` branch.
=> Prevent keyboard navigation to hidden tab

change/@microsoft-fast-foundation-7d8d0430-523b-473a-af77-e2bcf0bc6e38.json, change/@microsoft-fast-foundation-dc08ca7b-be41-4f42-a66c-c0874376b4a2.json, packages/web-components/fast-foundation/src/tabs/tabs.ts
Cherry-picking two fixes for bugs in the tab control's keyboard navigation.
Commits:
https://github.com/microsoft/fast/commit/84726aa1312068d10df176709d760764d577420f
https://github.com/microsoft/fast/commit/50dba9c58b1bc6ac0c8b948f68dd0cfb6485460b
=> [cherry-pick] two tab navigation fixes

change/@microsoft-fast-foundation-8be8ec30-b786-4058-b066-dacf147547af.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/data-grid/README.md, packages/web-components/fast-foundation/src/data-grid/data-grid-cell.ts, packages/web-components/fast-foundation/src/data-grid/data-grid.ts, packages/web-components/fast-foundation/src/data-grid/stories/data-grid.register.ts, packages/web-components/fast-foundation/src/data-grid/stories/data-grid.stories.ts, packages/web-components/fast-foundation/src/data-grid/stories/examples/complex-cell.ts
Keyboard events emitted from a data grid cell when a cell's internal navigation is active can incorrectly move focus in the parent grid.  Rather than rely on authors to intercept these events the cell component can prevent their propagation.
Additionally, this change adds 
- a simple 'defaultCellFocusTargetCallback` function that authors can use to move focus to the first element of a cell.
- an example of a grid with cells with internal focus targets and internal nav queue
- fixes code that detects the current active element to work within shadow doms
Current tests all work
- [ x] I have included a change request file using `$ yarn change`
=> fix: block cell nav events w internal focus queue active

.github/workflows/cd-deploy-www-production.yml, .github/workflows/cd-deploy-www-staging.yml, .github/workflows/cd-release-npm.yml, .github/workflows/testing/ci-daily-local.yml, CONTRIBUTING.md, sites/website/versioned_docs/version-legacy/community/contributor-guide.md
A lerna update seemed to recently cause an issue when running the publish CI for the archive branch. This led to realizing that the most recent versions of lerna have been being installed on CI. This locks the version to a known, working version to prevent breaks.
=> chore: lock lerna version for CI

change/@microsoft-fast-foundation-cb62e613-5e97-4272-8609-bba0f2f41056.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/combobox/README.md, packages/web-components/fast-foundation/src/data-grid/README.md, packages/web-components/fast-foundation/src/data-grid/data-grid.ts, packages/web-components/fast-foundation/src/listbox/README.md, packages/web-components/fast-foundation/src/listbox/listbox.ts, packages/web-components/fast-foundation/src/select/README.md
This PR changes static methods which are fat arrow functions to normal methods.
Part of #6809
=> fix: change public static methods for listbox and data grid to not be fat arrow fns

change/@microsoft-fast-element-2af3bb19-b65c-49a5-82f8-06ebb38e48cd.json, packages/web-components/fast-element/src/index.ts
This PR updates exports from fast-element to be explicitly defined. Certain tooling doesn't support name-spaced exports. This PR attempts to provide explicit exports for fast-element to better support a broad range of tooling.
N/AA
IF the API report doesn't show a change and the build passes, we should be good!
=> feat: update exports from fast-element to be explicit

change/@microsoft-fast-foundation-ced7ff56-36bf-4d3e-86ab-0efb894e0e53.json, packages/web-components/fast-foundation/package.json
Adds package export for patterns such as tagFor, StartEnd, etc...
n/a
=> feat: export foundation patterns as export path

change/@microsoft-fast-foundation-2ada25c3-3fb4-48ba-893d-e64d11f7f095.json, packages/web-components/fast-foundation/src/toolbar/toolbar.pw.spec.ts, packages/web-components/fast-foundation/src/toolbar/toolbar.ts
Resolves #6819 
When an element in the toolbar is clicked, the toolbar's `activeIndex` should update to be the index of that clicked item. However, there is a bug where this does not happen if a child element within the slotted element is clicked. This PR is intended to resolve that bug.
#6819 
I've updated the `clickHandler` for the toolbar to search `focusableElements` for an entry that _contains_ the clicked element rather than an entry that _is_ the clicked element. No other logic has changed.
I've added two additional tests for the toolbar:
1. Ensure that the toolbar's `activeIndex` updates when an element slotted into the toolbar is clicked (passed with & without this change)
2. Ensure that the toolbar's `activeIndex` updates when a nested element within an element slotted into the …
=> Fix bug in toolbar click handler when a slotted element has child elements

change/@microsoft-fast-foundation-673f775c-c439-46ef-93ae-7bd51076ce27.json, packages/web-components/fast-foundation/src/design-token/design-token.ts, packages/web-components/fast-foundation/src/di/di.ts, packages/web-components/fast-foundation/src/tabs/tabs.spec.ts
Add typing to template variable to remove error seen in code consuming fast-foundation with TypeScript 4.8+
Fixes #6365 
I'm not sure how to test for this. I force locally a TypeScript update to 4.9.5 and fixed the error mentioned in `@microsoft/fast-foundation`.
There are also error in `@microsoft/fast-router` but this does not fix them.
<details><summary>Errors in @microsoft/fast-router</summary>
<pre>
src/configuration.ts(49,9): error TS2322: Type 'DefaultRouteRecognizer<unknown>' is not assignable to type 'RouteRecognizer<TSettings>'.
The types returned by 'recognize(...)' are incompatible between these types.
Type 'Promise<RecognizedRoute<unknown> | null>' is not assignable to type 'Promise<RecognizedRoute<TSettings> | null>'.
Type 'RecognizedRoute<unknown> | null' is not assignable …
=> [archive] Fix usage with TypeScript 4.8+

change/@microsoft-fast-web-utilities-14b2f190-1571-4498-ba72-68bbafb26a20.json, packages/utilities/fast-web-utilities/src/rtl-scroll-converter.spec.ts
Fixes an intermittently failing test that seems to be affected by the device pixel ratio.
This test returns `0.5` on my Macbook Pro, since the test environment gets the same device pixel ratio as my screen (`2`).
The `RtlScrollConverter` test should pass in all environments.
I encountered this bug while testing #6847, but it's present on the main branch as well. Perhaps there's a way to override the behavior that's causing the test runner to use the host's display properties?
=> fix: RtlScrollConverter test on high dpi systems in fast-web-utilities

change/@microsoft-fast-foundation-6460ce7b-2806-47d5-8604-308d3b8151d3.json, packages/web-components/fast-foundation/src/form-associated/form-associated.ts
Fixes an issue where super.disconnectedCallback is not called within the form associated base class
=> fix: call super.disconnected callback in form associated base class

change/@microsoft-fast-web-utilities-14b2f190-1571-4498-ba72-68bbafb26a20.json, change/@microsoft-fast-web-utilities-3092275f-0c7e-4bf4-be96-424047357621.json, packages/utilities/fast-web-utilities/karma.conf.ts, packages/utilities/fast-web-utilities/src/rtl-scroll-converter.spec.ts
Changes the `invertedGetRtlScrollConverter returns correct value` test to pass when any value < 0 is returned.
This PR reverts #6857.
The behavior seems to be related to this Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1324251
It's something called "zoom for DSF" on MacOS, which leads to inaccurate value reporting:
|browser|value|
|-|-|
|Chrome 119.0.6045.107 (Headless/Karma) on Windows 11|`1`|
|Chrome 119.0.6045.123 on Mac (MBP M1, MacOS 14.0)|`0.5`|
|Webkit Nightly|`0`|
|Firefox Nightly|`0`|
So while I do still think that screen DPI is partly to blame for Chrome returning `0.5`, it seems that setting `scrollLeft` to `1` when in rtl mode and receiving anything other than `0` is a bug.
=> fix: rtl scroll converter test asserting incorrect values

.github/CODEOWNERS
Code owners that own individual packages can't approve PR's that include change files at the project root.  This change gives Owners of the "fast-foundation" package need permissions to the root 'change' folder as well in order to approve pr's with change files.
ad-hoc
=> Fix: add code owner permissions to change directory

change/@microsoft-fast-foundation-879984ab-c986-4ae7-93f2-bbebf4530962.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/tabs/README.md, packages/web-components/fast-foundation/src/tabs/tabs.template.ts, packages/web-components/fast-foundation/src/tabs/tabs.ts
The protected "setTabs" function in the `Tabs` component was written as an arrow function which made overriding it difficult as you can't simply call `super.setTabs()` to invoke the base class function when extending the `Tabs` class.  This change converts that function to a class member so it can be overridden more easily.  Additional minor cleanup of component code.
This is a breaking change in that anyone who currently has a workaround to override this function will need to make changes (ie. storing the base class arrow function and invoking it, for example).
Ad hoc.
=> fix: Tabs fn should be overrideable

change/@microsoft-fast-foundation-27c7d069-c14a-43a7-a6f6-6b060a2fe5d1.json, packages/web-components/fast-foundation/src/design-token/fast-design-token.pw.spec.ts
PR #6879 addresses a design token inheritance issue in the `fast-element-1` legacy branch. The issue does not exist in the `master` branch, but we would like to submit a few new test cases (the same ones being added to the legacy branch) to ensure no future regressions.
Additionally, a couple existing tests are modified to better adhere to the apparent intents of the tests.
#6864
=> Add additional design token test cases and test fixes

change/@microsoft-fast-foundation-54b02727-a454-4ca3-aff7-ea01225c6088.json, packages/web-components/fast-foundation/src/design-token/design-token.spec.ts, packages/web-components/fast-foundation/src/design-token/design-token.ts
This fixes a bug where a design token value is incorrectly inherited.
#6864 
I pulled some code for updating CSS reflection into a separate function to reuse. It is now called in response to changes in parent token values.
I added a couple test cases and fixed some formatting and other minor issues with the existing tests.
Unit tests pass.
=> Fix design token CSS variable inheritance bug

change/@microsoft-fast-foundation-b7949ac8-950f-4d90-aae6-0c7134bb95ba.json, packages/web-components/fast-foundation/src/menu/menu.ts
We have a design system in which we are implementing an anchor-based menu item. We believe this item should derive from the Foundation `Anchor` rather than the `MenuItem`. The only issue is that the `Menu` has indenting logic that only works for items that are instances of `MenuItem`. Really, all that it needs is for our custom menu item to define `startColumnCount` and handle styling based on that value. This PR simply replaces a call to `item instanceof MenuItem` with `"startColumnCount" in item`.
None
None
Existing tests continue to pass.
=> Allow non-MenuItem-derived types to be indented properly

.github/workflows/ci-validate-platforms.yml, .github/workflows/ci-validate-pr.yml, .vscode/settings.json
This PR updates the archives/fast-element-1 branch to run the pipelines successfully.
=> update branch policies and pipelines for pull requests on archive

change/@microsoft-fast-foundation-eadfb2dc-2d02-48d8-9106-739f0c3e80d2.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/slider-label/slider-label.template.ts, packages/web-components/fast-foundation/src/slider-label/slider-label.ts, packages/web-components/fast-foundation/src/slider-label/stories/slider-label.register.ts, packages/web-components/fast-foundation/src/slider/README.md, packages/web-components/fast-foundation/src/slider/slider.template.ts, packages/web-components/fast-foundation/src/slider/slider.ts, packages/web-components/fast-foundation/src/slider/stories/slider.register.ts, packages/web-components/fast-foundation/src/slider/stories/slider.stories.ts
As part of the next major release of fast-foundation, we wanted to do a complete review of the component templates and align the structure and naming as much as possible.
This PR is split from #6286 and updates the Slider and Slider Label templates.
Before on the left, update on the right. "C" = class, "P" = part, "R" = role, "S" = slot. 💔 = potentially style-breaking.
- 💔 Rename “track-container” `part` to “track”
- Add "thumb" `class` and `part` wrapper for "thumb" slot
- 💔 Remove duplicate `class` (orientation) on root template element
- 💔 Flatten “container” and “root”
- 💔 Rename “label” to “content”
- Add `part` to "mark" and "content"
Review the Storybook site, or the illustrations of the components before and after, compared to the changes in code.
Tested via comparison against …
=> Foundation: Update Slider templates

change/@microsoft-fast-foundation-422cca6d-1c45-47a9-aa69-517df2d15393.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/accordion-item/accordion-item.template.ts, packages/web-components/fast-foundation/src/accordion-item/accordion-item.ts, packages/web-components/fast-foundation/src/accordion-item/stories/accordion-item.register.ts, packages/web-components/fast-foundation/src/accordion/README.md, packages/web-components/fast-foundation/src/accordion/accordion.pw.spec.ts, packages/web-components/fast-foundation/src/accordion/accordion.template.ts, packages/web-components/fast-foundation/src/accordion/accordion.ts, packages/web-components/fast-foundation/src/accordion/stories/accordion.register.ts, packages/web-components/fast-foundation/src/accordion/stories/accordion.stories.ts
As part of the next major release of fast-foundation, we wanted to do a complete review of the component templates and align the structure and naming as much as possible.
This PR is split from #6286 and applies to Accordion and Accordion Item.
Before on the left, update on the right. "C" = class, "P" = part, "R" = role, "S" = slot. 💔 = potentially style-breaking.
- Remove unused `<template>` wrapper
- 💔 Rename “icon” to “expand-collapse-icon”
- 💔 Rename "region" `class` and `part` to "panel"
Review the Storybook site, or the illustrations of the components before and after, compared to the changes in code.
Tested via comparison against proposal and in Storybook.
=> Foundation: Update Accordion template element naming

change/@microsoft-fast-element-348a13f7-d30c-461e-b725-d9d8c0a10110.json, change/@microsoft-fast-foundation-6e548333-f93d-4f4d-b33e-988e42ca8135.json, packages/web-components/fast-element/docs/api-report.md, packages/web-components/fast-element/src/index.ts, packages/web-components/fast-element/src/styles/element-styles.ts, packages/web-components/fast-foundation/src/design-token/custom-property-manager.ts, packages/web-components/fast-foundation/src/design-token/design-token.spec.ts
This addresses two issues:
1. The last release of the `fast-element-1` branch included a change that exposed a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1522263). 
2. Overriding a design token's value in a stylesheet does not always work. A stylesheet containing custom properties for design tokens is added to `adoptedStyleSheets` alongside other client-defined stylesheets. If a client attempts to override a design token value for an element in CSS, in most cases the order of stylesheets in `adoptedStyleSheets` won't matter because of specificity-based precedence. But if the client stylesheet overrides the token property using the selector `:host`, then whichever stylesheet appears later in `adoptedStyleSheets` will be the one that wins. It seems that the client …
=> Fix CSS custom property precedence issue and work around Chromium bug

change/@microsoft-fast-foundation-452bb1d9-58ef-4cb0-a6fa-0ed41d1ad057.json, packages/web-components/fast-foundation/src/toolbar/toolbar.ts, packages/web-components/fast-foundation/src/utilities/root-active-element.ts
Essentially a cherry-pick of #6888 into archives/fast-element
=> fix: prevent toolbar from stealing focus when focus has already been moved

change/@microsoft-fast-foundation-47afe4a7-9451-4c4c-beba-70305e6b600e.json, packages/web-components/fast-foundation/src/combobox/combobox.pw.spec.ts, packages/web-components/fast-foundation/src/combobox/combobox.ts
Fix issue where the combobox remains open if there's no selection.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
https://github.com/microsoft/fast/issues/5721
https://github.com/microsoft/fluentui/issues/30693
Test in Storybook and review the before/after GIFs.
Tested in Storybook.
=> fix(combobox): close the combobox even if there's no selection

change/@microsoft-fast-foundation-c128481d-c811-401e-9be7-71f80b0350a1.json, packages/web-components/fast-foundation/src/combobox/combobox.spec.ts, packages/web-components/fast-foundation/src/combobox/combobox.ts
Cherry pick of #6923 into the archives branch - thanks @zpeterson!
=> [archives/fast-element-1] fix(cherry-pick): close combobox even if no selection

change/@microsoft-fast-foundation-b611fdcf-dcb8-4290-b4e5-97ebccd89e11.json, packages/web-components/fast-foundation/src/combobox/combobox.spec.ts, packages/web-components/fast-foundation/src/toolbar/toolbar.spec.ts
Ten of the fast-foundation toolbar tests (related to focus) began failing seemingly due to browser changes. The tests fail in Chrome as well as Firefox. It seems that calling `focus()` on the toolbar element does not pass the focus on to a contained element. I've worked around this for nine of the tests by directly focusing a button initially, instead of focusing the toolbar and expecting the button to get focus. The tenth failing test is testing exactly the behavior that stopped working. I believe we will have to just disable that test.
Also, removing a stray `.only` that was apparently checked in accidentally.
=> fix(fast-element1): fix toolbar navigation tests

.github/workflows/ci-validate-pr.yml
Allow the PR validate step to be manually dispatched. This will be helpful for testing against any branch prior to opening a PR.
=> Allow PR validate workflow to manually be dispatched

sites/website/src/docs/advanced/dependency-injection.md
This change fills out the dependency injection documentation with some examples, for regular JavaScript and dependency injection for web components.
The document does not contain an exhaustive list of all the capabilities of our current dependency injection utilities. We will be adding generated API documentation for this, and all other specific exports for users to refer to. See #6979 
- Add `api-extractor` generated documentation for all named exports.
=> Add dependency injection documentation

change/@microsoft-fast-foundation-18c21a13-5985-4fe7-88b6-c1d888f4851f.json, packages/web-components/fast-foundation/docs/api-report.md, packages/web-components/fast-foundation/src/picker/README.md, packages/web-components/fast-foundation/src/picker/picker-context.ts, packages/web-components/fast-foundation/src/picker/picker-list-item.template.ts, packages/web-components/fast-foundation/src/picker/picker-list-item.ts, packages/web-components/fast-foundation/src/picker/picker.spec.ts, packages/web-components/fast-foundation/src/picker/picker.template.ts, packages/web-components/fast-foundation/src/picker/picker.ts, packages/web-components/fast-foundation/src/picker/stories/picker.register.ts, packages/web-components/fast-foundation/src/picker/stories/picker.stories.ts
Picker was missing a disabled state.  This change adds that functionality.
Added some basic tests.
=> fix: add missing picker disabled state

.github/workflows/cd-gh-pages.yml, package.json, sites/website/docusaurus.config.js
This change adds a manually triggerable workflow to deploy the documentation website to github pages.
I've updated the docusaurus configuration as part of this pipeline for testing, we will not updated the DNS until v2 has been published.
=> Add github pages workflow

.github/workflows/cd-gh-pages.yml
The repository does not have permissions to add commits to a branch on GitHub, this adds to the github pages deploy workflow the same tokens used for npm package publishing which must perform a similar action and so should work.
Initial attempt at manually running the workflow ended in a `403`, in theory this change should grant the permissions needed to apply commits to the `gh-pages` branch.
=> Added tokens for github pages workflow

.github/workflows/cd-gh-pages.yml
This change simplifies the `gh-pages` branch to a single commit once the action is run, it also adds in write permissions and assigns a secret token on the deploy step.
Still running into permissions issues, this is a bit of a catch all to see if moving the token will change the `403`.
=> Add GH token to deploy step, additional permissions and settings for the deployed branch

.github/workflows/ci-validate-platforms.yml
Fix workflow macos-11 to macos-latest, macos-11 has been [deprecated](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/) and therefore will never run.
=> Fix workflow macos-11 to macos-latest

.github/workflows/ci-validate-codeql.yml, change/@microsoft-fast-element-66c55455-9b64-4d8c-a517-be10925cfd1a.json, change/@microsoft-fast-element-ed4fc460-a15b-4c5a-adab-36034f4f0c18.json, change/@microsoft-fast-foundation-7a94883b-0ee2-4e65-918c-91a2ce70ebc6.json, change/@microsoft-fast-router-8b07e1d4-0e01-4065-9377-aa36685a56ca.json, change/@microsoft-fast-ssr-f22b45fd-23fb-4386-82fa-72d59f744cd6.json, packages/web-components/fast-element/src/components/hydration.ts, packages/web-components/fast-element/src/dom-policy.ts, packages/web-components/fast-router/src/query-string.ts
This change moves the CodeQL scan to a separate workflow, adds a workflow dispatch to the platform workflow and fixes a few issues identified by CodeQL. It also fixes some change files dependency types.
=> Update CodeQL scanning to separate workflow and fix issues

sites/website/sidebars.js, sites/website/src/docs/advanced/component-libraries.md
This change removes the component library document. This will be written in the future, but we will go without it pre-launch of fast element 2.0.
=> Remove the component libraries doc which is empty

README.md, beachball.config.js, change/@microsoft-fast-element-0d43351b-3cd8-4f95-86db-19252456a901.json, change/@microsoft-fast-router-1a9f7b7a-e0ac-45f7-9e04-63d4d05b9121.json, change/@microsoft-fast-ssr-8934bec5-2646-45ee-8933-1ec20914a162.json, packages/web-components/fast-element/README.md, packages/web-components/fast-router/package.json, packages/web-components/fast-ssr/package.json
Makes updates to support versioning and the major version publish for fast-element.
=> chore: update beachball for versioning FAST Element to a major release

sites/website/src/css/custom.css
This change modifies some small color updates for the documentation site to meet accessibility compliance with link contrast ratios and text-decoration.
=> Fix documentation site contrast ratios and link text underline in articles

change/@microsoft-fast-foundation-030341a5-c95f-4516-a637-9e489443ff23.json, packages/web-components/fast-foundation/src/combobox/combobox.spec.ts, packages/web-components/fast-foundation/src/design-token/design-token.spec.ts, packages/web-components/fast-foundation/src/design-token/design-token.ts
This PR addresses a couple design-token-related bugs:
1. Removing/adding a child element does not update the CSS token reflection of that child. E.g.
- Starting with:
```html
<my-parent>
<my-child></my-child>
</my-parent>
<my-other-parent></my-other-parent>
```
- Define a token `T` (with CSS variable `--T`)
- Explicitly set `T` to "10" for both `<my-child>` and `<my-parent>`
- because `<my-child>`'s value is the same as the inherited value, the value is not reflected to CSS on `<my-child>`
- Explicitly set `T` to "20" for `<my-other-parent>`
- Reparent `<my-child>` under `<my-other-parent>` (detach, then append)
- Because the value "10" is explicitly set on `<my-child>`, the value of the CSS variable `--T` should be "10" for it, but it is not. It is "20", which is incorrect.
- since the …
=> fix(fast-element1): fix design token updates when attaching/detaching nodes and deleting values

change/@microsoft-fast-foundation-e29676d4-d69a-4915-ae60-66ce6e649a92.json, packages/web-components/fast-foundation/src/design-token/design-token.ts, packages/web-components/fast-foundation/src/slider/slider.spec.ts
Fixes #7022
#7022
No new tests, since branch is about to be frozen anyway.
None. Does not apply to mainline.
=> Fix binding observer memory leak

azure-pipelines-ci.yml
This is the first step in replacing the github pipeline with an azure pipeline in order to add additional security checks.
Unfortunately, there is no way to test this until it is on the `master` branch. The steps mirror those found in the [current CI](https://github.com/microsoft/fast/blob/master/.github/workflows/ci-validate-pr.yml).
- Commit this change
- Test run in Azure
- Fix any issues
=> Add azure pipeline CI

beachball.config.js, change/@microsoft-fast-element-161de870-eea2-44b4-a75d-2bc3f19a3b11.json
This change includes:
- A change file for `@microsoft/fast-element` to patch bump which should apply latest tag when published through the CI pipeline
- Not allow bumping dependencies as both of these are in prerelease which does not correctly apply in beachball
I have tested the outcome of these changes with `beachball bump` locally.
=> Patch bump to correct missing latest tag from package

change/@microsoft-fast-element-b679d332-e9c0-4e4a-984b-c06481f24caa.json, packages/web-components/fast-element/src/components/attributes.ts, packages/web-components/fast-element/src/components/element-controller.ts
=> fast-element: Simplify fromView logic and element-controller checks

.github/workflows/cd-release-npm.yml
The publish pipeline needed updating to be inline with the PR pipeline.
=> Update the CI publish pipeline to be inline with PR checks

.github/workflows/cd-release-npm.yml
Looks like these options might have changed without a major package update. As such, following the documentation: https://microsoft.github.io/beachball/concepts/ci-integration.html#github-repo-github-actions
This is currently failing publish when triggered from github actions. This may fix the issue.
=> change -n option to --token as this is present in the new docs

change/@microsoft-fast-element-161de870-eea2-44b4-a75d-2bc3f19a3b11.json, change/@microsoft-fast-element-b679d332-e9c0-4e4a-984b-c06481f24caa.json, package.json
It seems beachball has an issue with dependent change types being patch bumped and attempting to release with the bumpDeps configuration option being set. This changes the current changes in the change folder to bump dependentChangeType to none and to default to dependentChangeType none for future changes.
=> Change dependent change default to none

change/@microsoft-fast-router-86ba00b4-329b-480f-a226-77947ce80499.json, package-lock.json, packages/web-components/fast-router/package.json
The `@microsoft/fast-router` is erroneously using `@microsoft/fast-element` as a direct dependency, this is causing issues during publishing and is the incorrect dependency structure for the package.
=> Change the router to use peerDependency for fast-element

change/@microsoft-fast-element-65a1eb8c-3989-49a5-811f-fcc4274e53d6.json, packages/web-components/fast-element/docs/api-report.api.md, packages/web-components/fast-element/src/debug.ts, packages/web-components/fast-element/src/index.ts, packages/web-components/fast-element/src/observation/arrays.spec.ts, packages/web-components/fast-element/src/observation/arrays.ts, packages/web-components/fast-element/src/templating/repeat.spec.ts, packages/web-components/fast-element/src/templating/repeat.ts
This change updates the `ArrayObserver` to use some array tracking when applying `sort` or `reverse`. This will retain state to overcome the problem seen in #6919. No updates are required by developers.
Closes #6919
=> Update the ArrayObserver to better account for sort and reverse

sites/website/src/css/custom.css
Fixes an a11y issue with the "Docs" link on the documentation site where appropriate contrast is not met.
n/a
=> chore: adjust docs link color to ensure accessibility

change/@microsoft-fast-element-a0dc8892-ba16-4f59-8c59-9125aa60be70.json, package-lock.json, packages/web-components/fast-btr/README.md, packages/web-components/fast-btr/docs/api-report.api.md, packages/web-components/fast-btr/package.json, packages/web-components/fast-btr/server/main.ts, packages/web-components/fast-btr/server/server.ts, packages/web-components/fast-btr/server/tsconfig.json, packages/web-components/fast-btr/src/components/index.ts, packages/web-components/fast-btr/src/components/template.ts, packages/web-components/fast-btr/src/debug.ts, packages/web-components/fast-btr/src/fixtures/binding.fixture.html, packages/web-components/fast-btr/src/index.spec.ts, packages/web-components/fast-btr/src/index.ts, packages/web-components/fast-btr/src/interfaces.ts, packages/web-components/fast-btr/webpack.config.js, packages/web-components/fast-element/docs/api-report.api.md, packages/web-components/fast-element/src/components/element-controller.ts, packages/web-components/fast-element/src/components/fast-definitions.ts, packages/web-components/fast-element/src/components/fast-element.ts, packages/web-components/fast-element/src/index.ts, packages/web-components/fast-element/src/platform.ts
This is some initial work to convert declarative HTML into a `ViewTemplate`.
Some of this is preliminary work to get a workflow established for creation of aspect bindings and other requirements for the declarative HTML. This work also exposes the `fastElementRegistry` as well as exposing some global values to trigger instantiated components to update their internal definitions after a new template has been applied.
- Adding attribute bindings
- Adding logic for common directives such as `when`
=> Add the f-template component which can interpret a text binding and convert it to a ViewTemplate

packages/web-components/fast-btr/src/components/template.ts
This change simplifies the logic by using `innerHTML` to parse and removes the regex which had perf implications. This brings the implementation more inline with how the `html` tag template works.
=> Remove node parsing logic and use innerHTML, remove regex for perf

.github/workflows/cd-gh-pages.yml, .github/workflows/cd-release-npm.yml, .github/workflows/ci-validate-platforms.yml, .github/workflows/ci-validate-pr.yml
The cache github action v2 has been deprecated and is now failing the github action it is used on, this change updates the action to v4 to fix the issue.
See: https://github.com/actions/cache/discussions/1510
=> Update cache action

change/@microsoft-fast-html-6767d25e-8a0b-47c9-8790-6cf2f5e5025e.json, packages/web-components/fast-html/package.json
This change removes the `private` flag on the `@microsoft/fast-html` for initial `1.0.0-alpha.1` release.
=> Remove private flag on initial @microsoft/fast-html package

change/@microsoft-fast-html-5e7702eb-3c09-4b89-a5ad-1f0387043f76.json, packages/web-components/fast-html/package.json
This change removes the redundant `alpha` git tag as there is no stable version as yet, so it can be published as `latest`.
=> Remove alpha tag as there is no stable version for fast-html

change/@microsoft-fast-html-ad397d9b-b0e1-4309-a3ac-48b054d979cb.json, packages/web-components/fast-html/README.md, packages/web-components/fast-html/src/components/template.ts, packages/web-components/fast-html/src/components/utilities.ts, packages/web-components/fast-html/src/fixtures/when/main.ts, packages/web-components/fast-html/src/fixtures/when/when.fixture.html, packages/web-components/fast-html/src/fixtures/when/when.html, packages/web-components/fast-html/src/fixtures/when/when.spec.ts
This change adds a subset of operators to the `f-when` directive in declarative HTML.
The allowed syntax now looks like:
```html
<f-when value="{{show}}">Hello world</f-when>
<f-when value="{{!show}}">Hello world</f-when>
<f-when value="{{varA == 3}}">Equals 3</f-when>
<f-when value="{{varA != 3}}">Not equals 3</f-when>
<f-when value="{{varA >= 2}}">Two and Over</f-when>
<f-when value="{{varA > 2}}">Over two</f-when>
<f-when value="{{varA <= 2}}">Two and Under</f-when>
<f-when value="{{varA < 2}}">Under two</f-when>
<f-when value="{{thisVar || thatVar}}">This or That</f-when>
<f-when value="{{thisVar && thatVar}}">This and That</f-when>
```
Closes #7099
=> Add logic to the when directive for a subset of operators

change/@microsoft-fast-html-62024830-8fe2-4f54-9b7c-abc4c000f200.json, packages/web-components/fast-html/README.md, packages/web-components/fast-html/src/components/template.ts, packages/web-components/fast-html/src/components/utilities.spec.ts, packages/web-components/fast-html/src/components/utilities.ts, packages/web-components/fast-html/src/fixtures/repeat/main.ts, packages/web-components/fast-html/src/fixtures/repeat/repeat.fixture.html, packages/web-components/fast-html/src/fixtures/repeat/repeat.html, packages/web-components/fast-html/src/fixtures/repeat/repeat.json, packages/web-components/fast-html/src/fixtures/repeat/repeat.spec.ts
This change adds the ability to refer to the parent context in declarative HTML bindings.
=> Add parent context access to declarative HTML bindings

change/@microsoft-fast-html-d5ee6250-e24e-4cef-8d98-368747da972c.json, packages/web-components/fast-html/README.md, packages/web-components/fast-html/src/components/utilities.spec.ts, packages/web-components/fast-html/src/components/utilities.ts, packages/web-components/fast-html/src/fixtures/children/children.fixture.html, packages/web-components/fast-html/src/fixtures/children/children.html, packages/web-components/fast-html/src/fixtures/event/event.fixture.html, packages/web-components/fast-html/src/fixtures/event/event.html, packages/web-components/fast-html/src/fixtures/ref/ref.fixture.html, packages/web-components/fast-html/src/fixtures/ref/ref.html, packages/web-components/fast-html/src/fixtures/slotted/slotted.fixture.html, packages/web-components/fast-html/src/fixtures/slotted/slotted.html
This change categorizes bindings into 3 binding types, "client" `{}`, "default" `{{}}`, and "unescaped" `{{{}}}` (functionality to be added in a different PR.
The update to the syntax allows a server or build time rendering solution to ignore client side bindings as they are not needed until interaction on the client.
Resolves #7104
=> Change client only bindings to single curly braces and categorize single, double, and tripe curly brace bindings

change/@microsoft-fast-element-1c8a3d5b-c73b-45c9-8c58-e1b7bca16f72.json, packages/web-components/fast-element/src/components/fast-definitions.ts
The use of `@observable` in the `FASTElementDefinition` class causes the `__decorate` tslib helper function to be inlined in the dist builds.
There's another use of `Observable.defineProperty` in this module. It's in a loop that goes through attributes defined on the extending class (I think that's what's going on).
=> fix: use Observable.defineProperty instead of observable decorator

change/@microsoft-fast-element-17db0ea7-f7ca-4fde-b632-3f7b76094e31.json, change/@microsoft-fast-html-5e230d8e-5ebb-4d62-82d0-d7cac55b02a0.json, packages/web-components/fast-element/docs/api-report.api.md, packages/web-components/fast-element/src/components/element-controller.spec.ts, packages/web-components/fast-element/src/components/element-controller.ts, packages/web-components/fast-element/src/components/fast-definitions.ts, packages/web-components/fast-html/README.md, packages/web-components/fast-html/docs/api-report.api.md, packages/web-components/fast-html/src/components/template.ts, packages/web-components/fast-html/src/fixtures/attribute/main.ts, packages/web-components/fast-html/src/fixtures/binding/main.ts, packages/web-components/fast-html/src/fixtures/children/main.ts, packages/web-components/fast-html/src/fixtures/dot-syntax/main.ts, packages/web-components/fast-html/src/fixtures/event/main.ts, packages/web-components/fast-html/src/fixtures/partial/main.ts, packages/web-components/fast-html/src/fixtures/ref/main.ts, packages/web-components/fast-html/src/fixtures/repeat/main.ts, packages/web-components/fast-html/src/fixtures/slotted/main.ts, packages/web-components/fast-html/src/fixtures/when/main.ts
This change:
- Observes changes to `shadowOptions` on FASTElement custom elements
- Updates the `shadowOptions` with `TemplateElement` from the `@microsoft/fast-html` package to allow a shadowRoot to be attached when the template is defined
This change should solve the FOUC from defining the template after the custom element has been defined.
=> Allow shadowOptions to be observed

change/@microsoft-fast-html-98036136-a981-4bed-ab60-a39d4f7a70f8.json, packages/web-components/fast-html/src/components/utilities.spec.ts, packages/web-components/fast-html/src/components/utilities.ts
This fixes a stack overflow issue due to incorrectly slicing inner HTML strings when evaluating templates.
=> Fixes an issue with transforming innerHTML where the inner contents were not slicing correctly

change/@microsoft-fast-element-fde2bff1-bf4a-4866-8530-b73a5275fb9a.json, package-lock.json, packages/web-components/fast-element/package.json
A security fix for a devDependency on [tensile-perf](https://github.com/microsoft/tensile-perf/pull/36) allows us to update the underlying `express` dependency which had a security issue.
=> Fix a devDependency security issue due to an outdated version of express

change/@microsoft-fast-html-718a16b3-6a90-48ae-a28a-4593812510cd.json, packages/web-components/fast-html/src/components/template.ts, packages/web-components/fast-html/src/components/utilities.spec.ts, packages/web-components/fast-html/src/components/utilities.ts
This change:
- Fixes an issue with single quotes in f-when binding interpretation
- Adds ability to chain logic in f-when binding expression
=> Add chaining logic for f-when

change/@microsoft-fast-html-b4d2eaa6-6071-46b4-895a-18c23115ba2e.json, packages/web-components/fast-html/README.md, packages/web-components/fast-html/RENDERING.md
This change adds some documentation detailing how initial state can be applied to elements as well as what markers need to be added to the DOM on initial render.
=> Add information about non-browser rendering of hydratable markup and initial state

change/@microsoft-fast-html-9cab46dc-d71f-4d95-af56-6a19ba01b917.json, packages/web-components/fast-html/src/components/template.ts, packages/web-components/fast-html/src/fixtures/repeat/main.ts, packages/web-components/fast-html/src/fixtures/repeat/repeat.fixture.html, packages/web-components/fast-html/src/fixtures/repeat/repeat.spec.ts
This change keeps the context when using an `f-when` in an `f-repeat`.
Closes #7118
=> Keep a f-repeat context when creating bindings for f-when

change/@microsoft-fast-element-d8fc1632-3727-43ae-b5a2-de9d3a91d47b.json, change/@microsoft-fast-html-4a8ab298-12f3-427d-adb9-f38aee45f39f.json, packages/web-components/fast-element/src/components/hydration.spec.ts, packages/web-components/fast-element/src/components/hydration.ts, packages/web-components/fast-element/src/hydration/target-builder.ts, packages/web-components/fast-html/RENDERING.md
This change adds enumerated binding markers.
Due to the non-browser environment expected from SSR we must remove the assumption that an element is tracking it's internal attributes and so enumerating the binding markers allows a non-browser environment to add a hydration marker after/before every binding instead of having to create additional logic to track the number of attributes within an element tag.
Closes #7120
=> Add enumerated hydration binding markers

change/@microsoft-fast-html-9fa2cc7f-15be-4946-b0e5-586e7b3583ea.json, packages/web-components/fast-html/src/components/template.ts, packages/web-components/fast-html/src/fixtures/event/event.fixture.html, packages/web-components/fast-html/src/fixtures/event/event.spec.ts, packages/web-components/fast-html/src/fixtures/event/main.ts
Currently, if the event handler is defined as a method (`method() {...} `)instead of a property (`method = () => {...}`), the event handler will not be bound to the correct `this` context, hence `this` inside the event handler would be `undefined`.
Test added.
=> fix: event handler binding in fast-html

change/@microsoft-fast-element-618572f2-1aac-463b-8d2d-d70aef99b60e.json, packages/web-components/fast-element/package.json, packages/web-components/fast-element/src/components/hydration.spec.ts, packages/web-components/fast-element/src/components/hydration.ts
This change:
- Fixes an issue where if the number on an attribute binding marker did not start at `0` the binding would not be detected accurately.
- Adds the view template hydration script as an export as this will be used in FAST HTML to automatically include the `HydratableElementController`
=> Update logic for enumerated attribute hydration markers, add view hydration as export

change/@microsoft-fast-html-f2182c6e-460a-4b78-9b2d-32177d0d098e.json, packages/web-components/fast-html/README.md, packages/web-components/fast-html/RENDERING.md, packages/web-components/fast-html/docs/api-report.api.md, packages/web-components/fast-html/src/components/element.ts, packages/web-components/fast-html/src/components/index.ts, packages/web-components/fast-html/src/components/template.ts, packages/web-components/fast-html/src/fixtures/attribute/attribute.fixture.html, packages/web-components/fast-html/src/fixtures/attribute/main.ts, packages/web-components/fast-html/src/fixtures/binding/binding.fixture.html, packages/web-components/fast-html/src/fixtures/binding/main.ts, packages/web-components/fast-html/src/fixtures/children/children.fixture.html, packages/web-components/fast-html/src/fixtures/children/main.ts, packages/web-components/fast-html/src/fixtures/dot-syntax/dot-syntax.fixture.html, packages/web-components/fast-html/src/fixtures/dot-syntax/main.ts, packages/web-components/fast-html/src/fixtures/event/event.fixture.html, packages/web-components/fast-html/src/fixtures/event/main.ts, packages/web-components/fast-html/src/fixtures/partial/main.ts, packages/web-components/fast-html/src/fixtures/ref/main.ts, packages/web-components/fast-html/src/fixtures/ref/ref.fixture.html, packages/web-components/fast-html/src/fixtures/repeat/main.ts, packages/web-components/fast-html/src/fixtures/repeat/repeat.fixture.html, packages/web-components/fast-html/src/fixtures/slotted/main.ts, packages/web-components/fast-html/src/fixtures/slotted/slotted.fixture.html, packages/web-components/fast-html/src/fixtures/when/main.ts, packages/web-components/fast-html/src/fixtures/when/when.fixture.html, packages/web-components/fast-html/src/index.ts
This change:
- Requires that using `@microsoft/fast-html` rendered markup include hydratable markup.
- Adds default shadowOptions so they do not need to be passed
- Adds a `RenderableFASTElement` export which will automatically add and remove the `defer-hydration` attributes
=> Add a RenderableFASTElement and default shadow options

sites/website/src/docs/advanced/working-without-decorators.md
After looking into #7128 it was discovered that actually the updated syntax for adding attributes was never updated in the documentation. This is therefore not a bug fix, but a documentation update.
Resolves #7128 
- Run an update to push the change to the documentation site
=> Update documentation for working without decorators

change/@microsoft-fast-html-46a53b56-06e0-4eb5-b49e-f817eb5e3e9e.json, packages/web-components/fast-html/src/components/element.ts
This change:
- Fixes an issue where adding components that have already been defined with a template should be possible
- Add an optional user defined function to await if the user needs to perform additional hydratable actions such as fetching intiial state to apply to the custom element
=> Fix the RenderableFASTElement to account for rendering when hydration is not needed

change/@microsoft-fast-html-8b040ddd-b291-494f-ac1d-7fbd352cc642.json, packages/web-components/fast-html/README.md, packages/web-components/fast-html/src/components/template.ts, packages/web-components/fast-html/src/fixtures/ref/ref.spec.ts, packages/web-components/fast-html/src/fixtures/slotted/main.ts, packages/web-components/fast-html/src/fixtures/slotted/slotted.fixture.html, packages/web-components/fast-html/src/fixtures/slotted/slotted.spec.ts
Currently, the `f-slotted` directive only supports `{propertyName}` syntax, which maps to `slotted("propertyName")`. But we can't use the filter feature of `slotted` directive. This PR adds support to the `elements()` filter:
```html
<slot f-slotted="{foo filter elements()}"></slot>
```
```html
<slot f-slotted="{foo filter elements(div, p, ul)}"></slot>
```
* Resolves: #7138
=> add filter support to f-slotted attribute

change/@microsoft-fast-html-2c73ef1a-df0e-4441-bde3-cffe1891a077.json, packages/web-components/fast-html/docs/api-report.api.md, packages/web-components/fast-html/src/components/element.ts, packages/web-components/fast-html/src/fixtures/attribute/main.ts, packages/web-components/fast-html/src/fixtures/binding/main.ts, packages/web-components/fast-html/src/fixtures/children/main.ts, packages/web-components/fast-html/src/fixtures/dot-syntax/main.ts, packages/web-components/fast-html/src/fixtures/event/main.ts, packages/web-components/fast-html/src/fixtures/partial/main.ts, packages/web-components/fast-html/src/fixtures/ref/main.ts, packages/web-components/fast-html/src/fixtures/repeat/main.ts, packages/web-components/fast-html/src/fixtures/slotted/main.ts, packages/web-components/fast-html/src/fixtures/when/main.ts
This PR replaces the `RenderableFASTElement` class with a mixin function, which allows the necessary hydration attributes and behaviors to be added to a component class without changing the base extending class.
=> fix(fast-html): replace RenderableFASTElement with a mixin function

change/@microsoft-fast-html-9d4421c0-5569-451d-8a32-ff02e3ec471d.json, packages/web-components/fast-html/RENDERING.md
This change adds docs on client side bindings of attribute directives and events.
Closes #7162
=> Add further docs on client side bindings and hydration markers

change/@microsoft-fast-html-00a629f9-6a3c-4cdf-8631-baf8d507efd4.json, packages/web-components/fast-html/src/components/schema.spec.ts, packages/web-components/fast-html/src/components/schema.ts, packages/web-components/fast-html/src/components/template.ts, packages/web-components/fast-html/src/components/utilities.spec.ts, packages/web-components/fast-html/src/components/utilities.ts, packages/web-components/fast-html/src/fixtures/observer-map/main.ts, packages/web-components/fast-html/src/fixtures/observer-map/observer-map.fixture.html
This change adds an `anyOf` with `$ref` to other schemas.
Closes #7179 
- Implement schema `$ref` lookup for `anyOf` containing `$ref` in the ObserverMap to further inform the creation of Proxy objects.
=> Update schema to reference children schemas that tie an attribute to data

change/@microsoft-fast-html-b0c85295-af2d-4063-8faa-1a4b64555fcf.json, packages/web-components/fast-html/src/components/schema.spec.ts, packages/web-components/fast-html/src/components/schema.ts
This change accounts for child custom element refs to exist within contexts (repeats).
Further improves work on #7179
=> Add anyOf with  to contexts
